// EscolaPlay - Top-up extra do 6.º ano - Matemática (gerado, AE 2018, alinhado com MX 6 — Porto Editora)
// 3 tópicos novos: Números inteiros relativos, Equações simples, Probabilidades
const EXERCISES_6_M_EXTRA2 = [
  // ===== Tópico A: Números inteiros relativos (6me2_001 - 6me2_025) =====
  { id:'6me2_001', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:1,
    q:'🔢 Qual destes números é negativo?',
    opts:['+5','0','−7','+1'], ans:2,
    exp:'O número −7 tem sinal negativo, sendo menor do que zero.' },
  { id:'6me2_002', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:1,
    q:'🔢 Na reta numérica, à direita do zero ficam os números…',
    opts:['Negativos','Positivos','Iguais a zero','Decimais'], ans:1,
    exp:'Por convenção, os números positivos situam-se à direita do zero.' },
  { id:'6me2_003', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:1,
    q:'🔢 Qual é o simétrico de +4?',
    opts:['+4','−4','0','+8'], ans:1,
    exp:'O simétrico de um número troca o sinal: simétrico de +4 é −4.' },
  { id:'6me2_004', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:1,
    q:'🔢 Qual é o valor absoluto de −9, isto é |−9|?',
    opts:['−9','0','9','−1'], ans:2,
    exp:'O valor absoluto é a distância do número a zero, sempre não negativo: |−9| = 9.' },
  { id:'6me2_005', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:1,
    q:'🔢 Qual destas afirmações é verdadeira?',
    opts:['−5 > −2','−5 < −2','−5 = −2','−5 > 0'], ans:1,
    exp:'Entre dois negativos, é maior o que está mais perto do zero. −2 está mais perto, logo −5 < −2.' },
  { id:'6me2_006', s:'matematica', t:'Números inteiros relativos', type:'tf', diff:1,
    q:'🔢 Verdadeiro ou falso: o zero não é positivo nem negativo.',
    ans:true,
    exp:'Por convenção, o zero não tem sinal — não é positivo nem negativo.' },
  { id:'6me2_007', s:'matematica', t:'Números inteiros relativos', type:'tf', diff:1,
    q:'🔢 Verdadeiro ou falso: |0| = 0.',
    ans:true,
    exp:'A distância do zero a si próprio é zero.' },
  { id:'6me2_008', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:1,
    q:'🔢 Quanto é (+3) + (+5)?',
    opts:['+2','+8','−8','−2'], ans:1,
    exp:'Soma de dois positivos: somam-se os valores e mantém-se o sinal: +8.' },
  { id:'6me2_009', s:'matematica', t:'Números inteiros relativos', type:'fill', diff:1,
    q:'🔢 Calcula: |−12| = ?',
    ans:['12','+12'],
    exp:'O valor absoluto retira o sinal: |−12| = 12.' },
  { id:'6me2_010', s:'matematica', t:'Números inteiros relativos', type:'fill', diff:1,
    q:'🔢 Indica o simétrico de −7.',
    ans:['7','+7'],
    exp:'O simétrico de −7 é +7 (mesma distância ao zero, sinal contrário).' },
  { id:'6me2_011', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:2,
    q:'🔢 Quanto é (−3) + (+5)?',
    opts:['−8','+8','+2','−2'], ans:2,
    exp:'Sinais diferentes: subtraem-se os valores absolutos (5−3=2) e mantém-se o sinal do maior (+).' },
  { id:'6me2_012', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:2,
    q:'🔢 Quanto é (−4) + (−6)?',
    opts:['+10','−10','−2','+2'], ans:1,
    exp:'Sinais iguais (negativos): somam-se os valores absolutos (4+6=10) e mantém-se o sinal: −10.' },
  { id:'6me2_013', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:2,
    q:'🔢 Quanto é (+7) − (+10)?',
    opts:['+3','−3','+17','−17'], ans:1,
    exp:'7 − 10 = −3 (subtrair um maior de um menor dá negativo).' },
  { id:'6me2_014', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:2,
    q:'🔢 Quanto é (−8) − (−3)?',
    opts:['−11','+11','−5','+5'], ans:2,
    exp:'Subtrair um negativo é somar o positivo: −8 + 3 = −5.' },
  { id:'6me2_015', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:2,
    q:'🔢 A temperatura de manhã era −2 °C e à tarde subiu 7 °C. Qual a temperatura da tarde?',
    opts:['+5 °C','−5 °C','+9 °C','−9 °C'], ans:0,
    exp:'−2 + 7 = +5. A temperatura passou para 5 °C.' },
  { id:'6me2_016', s:'matematica', t:'Números inteiros relativos', type:'tf', diff:2,
    q:'🔢 Verdadeiro ou falso: ordenando por ordem crescente os números −5, −1, 0, +3, fica −5 < −1 < 0 < +3.',
    ans:true,
    exp:'Ordem correta na reta numérica: do mais à esquerda (−5) ao mais à direita (+3).' },
  { id:'6me2_017', s:'matematica', t:'Números inteiros relativos', type:'tf', diff:2,
    q:'🔢 Verdadeiro ou falso: dois números simétricos têm a mesma distância ao zero.',
    ans:true,
    exp:'É a definição de simétrico: mesma distância ao zero, sinais contrários.' },
  { id:'6me2_018', s:'matematica', t:'Números inteiros relativos', type:'fill', diff:2,
    q:'🔢 Calcula: (−5) + (+12) = ?',
    ans:['7','+7'],
    exp:'12 − 5 = 7; o sinal do maior (+) prevalece: +7.' },
  { id:'6me2_019', s:'matematica', t:'Números inteiros relativos', type:'fill', diff:2,
    q:'🔢 Calcula: (−6) − (+4) = ?',
    ans:['-10','−10'],
    exp:'(−6) − (+4) = −6 − 4 = −10.' },
  { id:'6me2_020', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:2,
    q:'🔢 O elevador estava no 3.º andar (+3) e desceu 5 andares. Em que piso ficou?',
    opts:['+2','−2','+8','−8'], ans:1,
    exp:'+3 − 5 = −2, ou seja, no piso −2 (cave 2).' },
  { id:'6me2_021', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:3,
    q:'🔢 Calcula: (−7) + (+3) − (−2).',
    opts:['−2','−6','−12','+2'], ans:0,
    exp:'(−7) + 3 = −4; −4 − (−2) = −4 + 2 = −2.' },
  { id:'6me2_022', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:3,
    q:'🔢 Numa região, a temperatura passou de −4 °C para +6 °C. Qual a variação?',
    opts:['+2 °C','+10 °C','−10 °C','−2 °C'], ans:1,
    exp:'Variação = final − inicial = 6 − (−4) = 6 + 4 = +10 °C.' },
  { id:'6me2_023', s:'matematica', t:'Números inteiros relativos', type:'tf', diff:3,
    q:'🔢 Verdadeiro ou falso: |−3| + |+5| = |−3 + 5|.',
    ans:false,
    exp:'|−3| + |+5| = 3 + 5 = 8, mas |−3 + 5| = |2| = 2. Logo, são diferentes.' },
  { id:'6me2_024', s:'matematica', t:'Números inteiros relativos', type:'fill', diff:3,
    q:'🔢 Um submarino estava a −120 m. Subiu 45 m e depois desceu 30 m. A que profundidade ficou?',
    ans:['-105','−105'],
    exp:'−120 + 45 − 30 = −75 − 30 = −105 m.' },
  { id:'6me2_025', s:'matematica', t:'Números inteiros relativos', type:'mc', diff:3,
    q:'🔢 Indica o conjunto dos inteiros relativos cujo valor absoluto é menor que 3.',
    opts:['{−3, −2, −1, 0, 1, 2, 3}','{−2, −1, 0, 1, 2}','{0, 1, 2}','{−2, 0, 2}'], ans:1,
    exp:'|x| < 3 significa −3 < x < 3; inteiros: −2, −1, 0, 1, 2.' },

  // ===== Tópico B: Equações simples (6me2_026 - 6me2_050) =====
  { id:'6me2_026', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ Uma equação é uma igualdade que…',
    opts:['Não tem letras','Tem pelo menos uma incógnita','Não pode ser resolvida','Nunca tem solução'], ans:1,
    exp:'Equação é uma igualdade com uma ou mais incógnitas (letras representando números desconhecidos).' },
  { id:'6me2_027', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ Em x + 5 = 12, o 1.º membro é…',
    opts:['12','x + 5','5','x'], ans:1,
    exp:'O 1.º membro é o que está antes do sinal "=", ou seja, x + 5.' },
  { id:'6me2_028', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ Em x + 5 = 12, o 2.º membro é…',
    opts:['x','x + 5','12','5'], ans:2,
    exp:'O 2.º membro está após o sinal "=", isto é, 12.' },
  { id:'6me2_029', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ A incógnita na equação x + 3 = 10 é…',
    opts:['3','10','x','13'], ans:2,
    exp:'A incógnita é a letra que representa o valor desconhecido — neste caso, x.' },
  { id:'6me2_030', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ Resolve: x + 4 = 9.',
    opts:['x = 5','x = 13','x = 4','x = 9'], ans:0,
    exp:'Subtraindo 4 a ambos os membros: x = 9 − 4 = 5.' },
  { id:'6me2_031', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ Resolve: x − 6 = 2.',
    opts:['x = −4','x = 4','x = 8','x = 12'], ans:2,
    exp:'Somando 6 a ambos os membros: x = 2 + 6 = 8.' },
  { id:'6me2_032', s:'matematica', t:'Equações simples', type:'mc', diff:1,
    q:'➕ Resolve: 3x = 12.',
    opts:['x = 4','x = 9','x = 36','x = 3'], ans:0,
    exp:'Dividindo por 3 ambos os membros: x = 12 ÷ 3 = 4.' },
  { id:'6me2_033', s:'matematica', t:'Equações simples', type:'tf', diff:1,
    q:'➕ Verdadeiro ou falso: o número 5 é solução da equação x + 2 = 7.',
    ans:true,
    exp:'Substituindo: 5 + 2 = 7. A igualdade verifica-se, logo 5 é solução.' },
  { id:'6me2_034', s:'matematica', t:'Equações simples', type:'fill', diff:1,
    q:'➕ Resolve: x + 7 = 15. x = ?',
    ans:['8','+8'],
    exp:'x = 15 − 7 = 8.' },
  { id:'6me2_035', s:'matematica', t:'Equações simples', type:'fill', diff:1,
    q:'➕ Resolve: x ÷ 4 = 3. x = ?',
    ans:['12','+12'],
    exp:'x = 3 × 4 = 12.' },
  { id:'6me2_036', s:'matematica', t:'Equações simples', type:'mc', diff:2,
    q:'➕ Resolve: 2x + 1 = 11.',
    opts:['x = 5','x = 6','x = 10','x = 12'], ans:0,
    exp:'2x = 11 − 1 = 10; x = 10 ÷ 2 = 5.' },
  { id:'6me2_037', s:'matematica', t:'Equações simples', type:'mc', diff:2,
    q:'➕ Resolve: 5x − 3 = 17.',
    opts:['x = 4','x = 14','x = 5','x = 20'], ans:0,
    exp:'5x = 17 + 3 = 20; x = 20 ÷ 5 = 4.' },
  { id:'6me2_038', s:'matematica', t:'Equações simples', type:'mc', diff:2,
    q:'➕ Verifica qual destes números é solução de x − 4 = 9.',
    opts:['5','9','13','−5'], ans:2,
    exp:'13 − 4 = 9. A igualdade verifica-se.' },
  { id:'6me2_039', s:'matematica', t:'Equações simples', type:'mc', diff:2,
    q:'➕ A soma de um número com 8 é igual a 20. Qual é o número?',
    opts:['12','28','8','20'], ans:0,
    exp:'x + 8 = 20 → x = 20 − 8 = 12.' },
  { id:'6me2_040', s:'matematica', t:'Equações simples', type:'mc', diff:2,
    q:'➕ O dobro de um número é 24. Qual é o número?',
    opts:['12','24','48','6'], ans:0,
    exp:'2x = 24 → x = 12.' },
  { id:'6me2_041', s:'matematica', t:'Equações simples', type:'tf', diff:2,
    q:'➕ Verdadeiro ou falso: o princípio da equivalência permite somar ou subtrair o mesmo número aos dois membros sem alterar a solução.',
    ans:true,
    exp:'É o princípio da equivalência por adição/subtração: mantém o conjunto-solução.' },
  { id:'6me2_042', s:'matematica', t:'Equações simples', type:'tf', diff:2,
    q:'➕ Verdadeiro ou falso: numa equação, podemos multiplicar ambos os membros por zero sem problema.',
    ans:false,
    exp:'Multiplicar por zero anula tudo (0 = 0), perdendo-se informação. Não é permitido.' },
  { id:'6me2_043', s:'matematica', t:'Equações simples', type:'fill', diff:2,
    q:'➕ Resolve: 4x = 28. x = ?',
    ans:['7','+7'],
    exp:'x = 28 ÷ 4 = 7.' },
  { id:'6me2_044', s:'matematica', t:'Equações simples', type:'fill', diff:2,
    q:'➕ Resolve: x − 9 = −2. x = ?',
    ans:['7','+7'],
    exp:'x = −2 + 9 = 7.' },
  { id:'6me2_045', s:'matematica', t:'Equações simples', type:'mc', diff:2,
    q:'➕ A Ana tem o triplo da idade do irmão. Se ela tem 18 anos, qual a idade do irmão? (3x = 18)',
    opts:['3','6','9','15'], ans:1,
    exp:'3x = 18 → x = 18 ÷ 3 = 6 anos.' },
  { id:'6me2_046', s:'matematica', t:'Equações simples', type:'mc', diff:3,
    q:'➕ Resolve: 3x + 5 = 2x + 11.',
    opts:['x = 6','x = 16','x = 3','x = 8'], ans:0,
    exp:'3x − 2x = 11 − 5 → x = 6.' },
  { id:'6me2_047', s:'matematica', t:'Equações simples', type:'mc', diff:3,
    q:'➕ Resolve: x ÷ 2 + 3 = 7.',
    opts:['x = 5','x = 8','x = 10','x = 14'], ans:1,
    exp:'x ÷ 2 = 7 − 3 = 4; x = 4 × 2 = 8.' },
  { id:'6me2_048', s:'matematica', t:'Equações simples', type:'tf', diff:3,
    q:'➕ Verdadeiro ou falso: 2 é solução de 4x − 3 = 5.',
    ans:true,
    exp:'4 × 2 − 3 = 8 − 3 = 5. A igualdade verifica-se.' },
  { id:'6me2_049', s:'matematica', t:'Equações simples', type:'fill', diff:3,
    q:'➕ Pensa num número. Multiplica-o por 5 e tira 4. O resultado é 21. Qual é o número?',
    ans:['5','+5'],
    exp:'5x − 4 = 21 → 5x = 25 → x = 5.' },
  { id:'6me2_050', s:'matematica', t:'Equações simples', type:'mc', diff:3,
    q:'➕ A soma de três números consecutivos é 30. Qual é o menor? (x + (x+1) + (x+2) = 30)',
    opts:['8','9','10','11'], ans:1,
    exp:'3x + 3 = 30 → 3x = 27 → x = 9. Os números são 9, 10 e 11.' },

  // ===== Tópico C: Probabilidades (6me2_051 - 6me2_075) =====
  { id:'6me2_051', s:'matematica', t:'Probabilidades', type:'mc', diff:1,
    q:'🎲 Uma experiência aleatória é aquela em que…',
    opts:['Sabemos sempre o resultado','Não conseguimos prever com certeza o resultado','Não há resultados possíveis','O resultado é sempre o mesmo'], ans:1,
    exp:'Numa experiência aleatória, conhecemos os resultados possíveis, mas não sabemos qual ocorrerá.' },
  { id:'6me2_052', s:'matematica', t:'Probabilidades', type:'mc', diff:1,
    q:'🎲 Uma experiência determinística é aquela em que…',
    opts:['O resultado é imprevisível','O resultado é conhecido à partida','Tem várias soluções','Depende da sorte'], ans:1,
    exp:'Numa experiência determinística, sabemos qual será o resultado (ex.: aquecer água a 100 °C ferve).' },
  { id:'6me2_053', s:'matematica', t:'Probabilidades', type:'mc', diff:1,
    q:'🎲 Ao lançar uma moeda equilibrada, o espaço de resultados é…',
    opts:['{cara}','{coroa}','{cara, coroa}','{1, 2, 3, 4, 5, 6}'], ans:2,
    exp:'A moeda tem dois resultados possíveis: cara e coroa.' },
  { id:'6me2_054', s:'matematica', t:'Probabilidades', type:'mc', diff:1,
    q:'🎲 Ao lançar um dado de 6 faces, o espaço de resultados é…',
    opts:['{1, 2, 3}','{1, 2, 3, 4, 5}','{1, 2, 3, 4, 5, 6}','{0, 1, 2, 3, 4, 5}'], ans:2,
    exp:'Um dado padrão tem 6 faces numeradas de 1 a 6.' },
  { id:'6me2_055', s:'matematica', t:'Probabilidades', type:'mc', diff:1,
    q:'🎲 Um acontecimento é certo quando…',
    opts:['Nunca acontece','Acontece sempre','Pode ou não acontecer','É impossível'], ans:1,
    exp:'Acontecimento certo: ocorre em todas as realizações da experiência (P = 1).' },
  { id:'6me2_056', s:'matematica', t:'Probabilidades', type:'mc', diff:1,
    q:'🎲 Um acontecimento impossível tem probabilidade igual a…',
    opts:['1','0','1/2','100'], ans:1,
    exp:'O acontecimento impossível nunca ocorre, logo P = 0.' },
  { id:'6me2_057', s:'matematica', t:'Probabilidades', type:'tf', diff:1,
    q:'🎲 Verdadeiro ou falso: a probabilidade de um acontecimento está sempre entre 0 e 1.',
    ans:true,
    exp:'0 ≤ P(A) ≤ 1: 0 = impossível, 1 = certo.' },
  { id:'6me2_058', s:'matematica', t:'Probabilidades', type:'tf', diff:1,
    q:'🎲 Verdadeiro ou falso: ao lançar um dado equilibrado, a probabilidade de sair "7" é zero.',
    ans:true,
    exp:'O dado só tem faces de 1 a 6, logo "sair 7" é impossível: P = 0.' },
  { id:'6me2_059', s:'matematica', t:'Probabilidades', type:'fill', diff:1,
    q:'🎲 Completa: a fórmula clássica é P(A) = casos favoráveis ÷ casos ______.',
    ans:['possiveis','possíveis'],
    exp:'P(A) = nº de casos favoráveis dividido pelo nº de casos possíveis.' },
  { id:'6me2_060', s:'matematica', t:'Probabilidades', type:'fill', diff:1,
    q:'🎲 Ao lançar uma moeda equilibrada, a probabilidade de sair "cara" é (em fração)…',
    ans:['1/2','0.5','50%'],
    exp:'1 caso favorável (cara) em 2 possíveis (cara, coroa): P = 1/2.' },
  { id:'6me2_061', s:'matematica', t:'Probabilidades', type:'mc', diff:2,
    q:'🎲 Ao lançar um dado equilibrado, qual é P(sair número par)?',
    opts:['1/6','2/6','3/6','4/6'], ans:2,
    exp:'Casos favoráveis: 2, 4, 6 (3 casos) em 6 possíveis: 3/6 = 1/2.' },
  { id:'6me2_062', s:'matematica', t:'Probabilidades', type:'mc', diff:2,
    q:'🎲 Ao lançar um dado equilibrado, qual é P(sair "5")?',
    opts:['1/6','1/5','5/6','1/2'], ans:0,
    exp:'1 caso favorável em 6 possíveis: P = 1/6.' },
  { id:'6me2_063', s:'matematica', t:'Probabilidades', type:'mc', diff:2,
    q:'🎲 Numa caixa há 4 bolas vermelhas e 6 azuis. Qual é P(tirar uma bola vermelha)?',
    opts:['4/6','4/10','6/10','1/4'], ans:1,
    exp:'4 favoráveis em 4+6=10 possíveis: P = 4/10 = 2/5.' },
  { id:'6me2_064', s:'matematica', t:'Probabilidades', type:'mc', diff:2,
    q:'🎲 Numa caixa há 4 bolas vermelhas e 6 azuis. Qual é P(tirar uma bola azul)?',
    opts:['4/10','6/10','1/2','1/6'], ans:1,
    exp:'6 favoráveis em 10 possíveis: P = 6/10 = 3/5.' },
  { id:'6me2_065', s:'matematica', t:'Probabilidades', type:'mc', diff:2,
    q:'🎲 Ao lançar um dado equilibrado, qual é P(sair número maior que 4)?',
    opts:['1/6','2/6','3/6','4/6'], ans:1,
    exp:'Maiores que 4: 5 e 6 (2 casos) em 6: P = 2/6 = 1/3.' },
  { id:'6me2_066', s:'matematica', t:'Probabilidades', type:'tf', diff:2,
    q:'🎲 Verdadeiro ou falso: ao lançar um dado, P(sair número par) + P(sair número ímpar) = 1.',
    ans:true,
    exp:'Par e ímpar são acontecimentos complementares; a soma das probabilidades é 1.' },
  { id:'6me2_067', s:'matematica', t:'Probabilidades', type:'tf', diff:2,
    q:'🎲 Verdadeiro ou falso: a probabilidade 1/2 corresponde a 50%.',
    ans:true,
    exp:'1/2 = 0,5 = 50%.' },
  { id:'6me2_068', s:'matematica', t:'Probabilidades', type:'fill', diff:2,
    q:'🎲 Numa caixa com 5 bolas brancas e 5 pretas, P(tirar uma branca) = ? (em fração simplificada)',
    ans:['1/2','5/10','0.5','50%'],
    exp:'5/10 = 1/2.' },
  { id:'6me2_069', s:'matematica', t:'Probabilidades', type:'fill', diff:2,
    q:'🎲 Ao lançar um dado equilibrado, P(sair número ímpar) = ? (em fração)',
    ans:['1/2','3/6','0.5','50%'],
    exp:'Ímpares: 1, 3, 5 (3 casos em 6): 3/6 = 1/2.' },
  { id:'6me2_070', s:'matematica', t:'Probabilidades', type:'mc', diff:2,
    q:'🎲 Numa roleta com 8 setores iguais numerados de 1 a 8, qual é P(sair múltiplo de 3)?',
    opts:['1/8','2/8','3/8','4/8'], ans:1,
    exp:'Múltiplos de 3 entre 1 e 8: 3 e 6 (2 casos) em 8: P = 2/8 = 1/4.' },
  { id:'6me2_071', s:'matematica', t:'Probabilidades', type:'mc', diff:3,
    q:'🎲 Se P(A) = 1/4, qual é a probabilidade do acontecimento contrário (não A)?',
    opts:['1/4','1/2','3/4','1'], ans:2,
    exp:'P(não A) = 1 − P(A) = 1 − 1/4 = 3/4.' },
  { id:'6me2_072', s:'matematica', t:'Probabilidades', type:'mc', diff:3,
    q:'🎲 Numa caixa há 3 bolas vermelhas, 2 azuis e 5 verdes. Qual é P(tirar bola não verde)?',
    opts:['5/10','3/10','1/2','2/10'], ans:0,
    exp:'Não verdes: 3+2 = 5 em 10 totais: P = 5/10 = 1/2.' },
  { id:'6me2_073', s:'matematica', t:'Probabilidades', type:'tf', diff:3,
    q:'🎲 Verdadeiro ou falso: ao lançar um dado equilibrado, sair "número menor que 7" é um acontecimento certo.',
    ans:true,
    exp:'Todos os resultados (1 a 6) são menores que 7, logo P = 1.' },
  { id:'6me2_074', s:'matematica', t:'Probabilidades', type:'fill', diff:3,
    q:'🎲 Numa turma com 25 alunos, 10 são rapazes. Escolhendo um aluno ao acaso, P(ser rapariga) = ? (em fração simplificada)',
    ans:['3/5','15/25','0.6','60%'],
    exp:'Raparigas: 25 − 10 = 15. P = 15/25 = 3/5.' },
  { id:'6me2_075', s:'matematica', t:'Probabilidades', type:'mc', diff:3,
    q:'🎲 Lançam-se duas moedas equilibradas. Qual é P(sair duas caras)?',
    opts:['1/2','1/3','1/4','2/4'], ans:2,
    exp:'Casos possíveis: (CC, CK, KC, KK) — 4 casos. Favorável: CC. P = 1/4.' }
];
