// EscolaPlay - 2.º ano - Matemática - REVISÃO FINAL (preparação para teste de fim de ano)
// 40 exercícios a cobrir toda a matéria das fichas: ordenar números, antes/depois,
// decomposição e leitura por extenso, números até 1000, tabuada do 3 (múltiplos),
// sequências de crescimento, frações (representar/ligar/ordenar), perímetro, área em
// quadrícula, ângulos retos, divisão/distribuir equitativamente.
const EXERCISES_2_M_EXTRA4 = [

  // ===== Ordenar e comparar (ordem crescente) =====
  { id:'2mrf_001', s:'matematica', t:'Revisão final', type:'mc', diff:1,
    q:'📏 Alturas: 127, 115, 138, 113, 120. Qual é a MAIS BAIXA?',
    opts:['113','138','127','115'], ans:0,
    exp:'113 é o menor número, logo é a altura mais baixa.' },
  { id:'2mrf_002', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'📏 Ordena por ordem crescente: 127, 115, 138, 113, 120. Qual fica em 2.º lugar?',
    opts:['113','115','120','127'], ans:1,
    exp:'Por ordem crescente: 113, 115, 120, 127, 138. O 2.º é 115.' },
  { id:'2mrf_003', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'📏 Ordem crescente de 127, 115, 138, 113, 120: o ÚLTIMO (maior) é ___.',
    ans:['138'], exp:'O maior número é 138, fica no fim da ordem crescente.' },
  { id:'2mrf_004', s:'matematica', t:'Revisão final', type:'tf', diff:1,
    q:'"Ordem crescente" significa do menor para o maior.',
    ans:true, exp:'Crescente = do menor para o maior. Decrescente = do maior para o menor.' },

  // ===== Número antes e depois =====
  { id:'2mrf_005', s:'matematica', t:'Revisão final', type:'fill', diff:1,
    q:'🔢 O número imediatamente ANTES de 322 é ___.',
    ans:['321'], exp:'Antes = menos 1. 322 − 1 = 321.' },
  { id:'2mrf_006', s:'matematica', t:'Revisão final', type:'fill', diff:1,
    q:'🔢 O número imediatamente DEPOIS de 599 é ___.',
    ans:['600'], exp:'Depois = mais 1. 599 + 1 = 600.' },
  { id:'2mrf_007', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🔢 Qual é o número imediatamente antes de 500?',
    opts:['499','501','490','400'], ans:0,
    exp:'Antes de 500 é 500 − 1 = 499.' },
  { id:'2mrf_008', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'🔢 Escreve o número que vem depois de 566: ___.',
    ans:['567'], exp:'566 + 1 = 567.' },

  // ===== Decomposição e leitura por extenso (até 1000) =====
  { id:'2mrf_009', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🔢 A decomposição de 324 é...',
    opts:['300 + 20 + 4','3 + 2 + 4','30 + 20 + 4','300 + 200 + 4'], ans:0,
    exp:'324 = 3 centenas + 2 dezenas + 4 unidades = 300 + 20 + 4.' },
  { id:'2mrf_010', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'🔢 Completa a decomposição de 556: 500 + ___ + 6.',
    ans:['50'], exp:'556 = 500 + 50 + 6 (5 centenas, 5 dezenas, 6 unidades).' },
  { id:'2mrf_011', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'✍️ Como se lê o número 324?',
    opts:['trinta e dois e quatro','trezentos e vinte e quatro','três e vinte e quatro','trezentos e quarenta e dois'], ans:1,
    exp:'324 lê-se "trezentos e vinte e quatro".' },
  { id:'2mrf_012', s:'matematica', t:'Revisão final', type:'mc', diff:3,
    q:'✍️ Que número é "setecentos e noventa e oito"?',
    opts:['798','708','789','7098'], ans:0,
    exp:'700 + 90 + 8 = 798.' },
  { id:'2mrf_013', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'🔢 Quantas centenas tem o número 556? ___',
    ans:['5','5 centenas'], exp:'O algarismo das centenas é o 5: 556 tem 5 centenas.' },
  { id:'2mrf_014', s:'matematica', t:'Revisão final', type:'tf', diff:2,
    q:'No número 438, o algarismo 4 vale 400.',
    ans:true, exp:'O 4 está nas centenas, logo vale 400. 438 = 400 + 30 + 8.' },

  // ===== Tabuada do 3 (múltiplos) =====
  { id:'2mrf_015', s:'matematica', t:'Revisão final', type:'mc', diff:1,
    q:'✖️ Quanto é 3 × 6?',
    opts:['15','18','21','9'], ans:1,
    exp:'3 × 6 = 18 (conta de 3 em 3: 3,6,9,12,15,18).' },
  { id:'2mrf_016', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'✖️ Qual destes números é um produto da tabuada do 3?',
    opts:['16','25','24','29'], ans:2,
    exp:'24 = 3 × 8. Os outros não são múltiplos de 3.' },
  { id:'2mrf_017', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'✖️ Qual destes NÃO é múltiplo de 3?',
    opts:['12','21','27','28'], ans:3,
    exp:'28 não está na tabuada do 3. 12=3×4, 21=3×7, 27=3×9.' },
  { id:'2mrf_018', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'✖️ Continua de 3 em 3: 3, 6, 9, 12, ___.',
    ans:['15'], exp:'12 + 3 = 15.' },
  { id:'2mrf_019', s:'matematica', t:'Revisão final', type:'tf', diff:2,
    q:'O número 30 é um produto da tabuada do 3.',
    ans:true, exp:'Verdadeiro: 3 × 10 = 30.' },

  // ===== Sequências de crescimento =====
  { id:'2mrf_020', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🔴 Sequência: Fig.1 = 3 círculos, Fig.2 = 4, Fig.3 = 5. Quantos tem a Fig.4?',
    opts:['5','6','7','8'], ans:1,
    exp:'Aumenta 1 de cada vez: 3, 4, 5, 6. A Fig.4 tem 6.' },
  { id:'2mrf_021', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'🔴 Na mesma sequência (3, 4, 5, 6, …), quantos círculos tem a Figura 5? ___',
    ans:['7'], exp:'6 + 1 = 7. A Figura 5 tem 7 círculos.' },
  { id:'2mrf_022', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🙂 Carinhas: Fig.1 = 2, Fig.2 = 4, Fig.3 = 6. Quantas tem a Fig.4?',
    opts:['7','8','10','6'], ans:1,
    exp:'Aumenta 2 de cada vez: 2, 4, 6, 8. A Fig.4 tem 8.' },
  { id:'2mrf_023', s:'matematica', t:'Revisão final', type:'fill', diff:3,
    q:'🙂 Na sequência 2, 4, 6, 8, …, quantas carinhas tem a Figura 6? ___',
    ans:['12'], exp:'De 2 em 2: 2,4,6,8,10,12. A Figura 6 tem 12.' },

  // ===== Frações simples =====
  { id:'2mrf_024', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🍕 Uma figura está dividida em 4 partes iguais e 1 está pintada. Que fração representa a parte pintada?',
    opts:['1/2','1/4','4/1','3/4'], ans:1,
    exp:'1 parte pintada em 4 partes iguais = 1/4.' },
  { id:'2mrf_025', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🍕 Metade de uma figura está pintada. Que fração é?',
    opts:['1/2','1/4','2/2','1/3'], ans:0,
    exp:'Metade = 1 de 2 partes iguais = 1/2.' },
  { id:'2mrf_026', s:'matematica', t:'Revisão final', type:'mc', diff:3,
    q:'🍕 Uma figura tem 8 partes iguais e 3 estão pintadas. A fração pintada é...',
    opts:['8/3','3/8','3/5','1/8'], ans:1,
    exp:'3 partes pintadas em 8 = 3/8 (em cima o que está pintado, em baixo o total).' },
  { id:'2mrf_027', s:'matematica', t:'Revisão final', type:'tf', diff:2,
    q:'Na fração 3/4, o número de baixo (4) é o total de partes iguais.',
    ans:true, exp:'O denominador (baixo) = total de partes; o numerador (cima) = partes pintadas.' },
  { id:'2mrf_028', s:'matematica', t:'Revisão final', type:'mc', diff:3,
    q:'🍕 Qual é a MAIOR fração: 3/4 ou 1/2?',
    opts:['3/4','1/2','são iguais','não dá para saber'], ans:0,
    exp:'3/4 (três quartos) é mais do que 1/2 (metade).' },
  { id:'2mrf_029', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'🍕 Numa figura com 5 partes iguais e 2 pintadas, a fração pintada é ___ (escreve como a/b).',
    ans:['2/5'], exp:'2 partes em 5 = 2/5.' },

  // ===== Perímetro =====
  { id:'2mrf_030', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'📐 Um triângulo tem lados 4 cm, 4 cm e 3 cm. Qual é o perímetro?',
    opts:['10 cm','11 cm','12 cm','7 cm'], ans:1,
    exp:'Perímetro = soma dos lados = 4 + 4 + 3 = 11 cm.' },
  { id:'2mrf_031', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'📐 Um quadrado tem todos os lados com 3 cm. Qual é o perímetro?',
    opts:['9 cm','6 cm','12 cm','3 cm'], ans:2,
    exp:'4 lados iguais: 3 + 3 + 3 + 3 = 12 cm.' },
  { id:'2mrf_032', s:'matematica', t:'Revisão final', type:'fill', diff:3,
    q:'📐 Perímetro de uma figura com lados 3, 1, 3, 5, 6 e 4 cm: ___ cm.',
    ans:['22'], exp:'Soma todos os lados: 3+1+3+5+6+4 = 22 cm.' },
  { id:'2mrf_033', s:'matematica', t:'Revisão final', type:'tf', diff:1,
    q:'O perímetro é a soma das medidas de todos os lados de uma figura.',
    ans:true, exp:'Perímetro = "contorno" = soma de todos os lados.' },

  // ===== Área em quadrícula =====
  { id:'2mrf_034', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'🟧 Uma figura no quadriculado ocupa 6 quadrículas. Qual é a área (em quadrículas)?',
    opts:['6','12','3','36'], ans:0,
    exp:'A área é o número de quadrículas que a figura ocupa: 6.' },
  { id:'2mrf_035', s:'matematica', t:'Revisão final', type:'fill', diff:2,
    q:'🟧 Uma figura cobre 8 quadrículas. A sua área é ___ quadrículas.',
    ans:['8'], exp:'Conta-se quantas quadrículas a figura cobre: 8.' },
  { id:'2mrf_036', s:'matematica', t:'Revisão final', type:'tf', diff:2,
    q:'Para medir a área no quadriculado, contamos quantas quadrículas a figura ocupa.',
    ans:true, exp:'A área conta as quadrículas; o perímetro conta o contorno.' },

  // ===== Ângulos retos =====
  { id:'2mrf_037', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'📐 Quantos ângulos retos (cantos "quadrados") tem um quadrado?',
    opts:['2','3','4','0'], ans:2,
    exp:'Um quadrado tem 4 cantos certos = 4 ângulos retos.' },
  { id:'2mrf_038', s:'matematica', t:'Revisão final', type:'tf', diff:2,
    q:'Um ângulo reto é o cantinho como o de uma folha ou de um livro.',
    ans:true, exp:'O ângulo reto é o canto "quadrado", como o vértice de uma folha A4.' },

  // ===== Divisão / distribuir equitativamente =====
  { id:'2mrf_039', s:'matematica', t:'Revisão final', type:'mc', diff:2,
    q:'✏️ Distribui 6 lápis igualmente por 2 estojos. Quantos ficam em cada um?',
    opts:['2','3','4','6'], ans:1,
    exp:'6 : 2 = 3. Ficam 3 lápis em cada estojo.' },
  { id:'2mrf_040', s:'matematica', t:'Revisão final', type:'mc', diff:3,
    q:'🃏 O João reparte 24 cromos igualmente por 2 amigos. Quantos dá a cada um?',
    opts:['10','12','14','24'], ans:1,
    exp:'24 : 2 = 12. Cada amigo recebe 12 cromos.' }

];
if (typeof module !== 'undefined' && module.exports) module.exports = EXERCISES_2_M_EXTRA4;
if (typeof window !== 'undefined') window.EXERCISES_2_M_EXTRA4 = EXERCISES_2_M_EXTRA4;
