// EscolaPlay - Top-up 2 do 6.º ano - Ciências Naturais (Uau! Vida 6 — Parte 2, Areal)
// +50 exercícios NOVOS para as categorias de teste do 3.º período (sem repetir o content_6_c_extra3.js):
//   "As plantas e o meio"  (foco: raiz, seiva, xilema/floema, estomas, transpiração, respiração, importância)
//   "Reprodução das plantas com semente"  (foco: reprodução assexuada, peças da flor, fruto/semente, dispersão, germinação)
const EXERCISES_6_C_EXTRA4 = [

    // ============================================================
    // AS PLANTAS E O MEIO (+25)
    // ============================================================

    { id:"t4b-01", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"Que parte da planta absorve a água e os sais minerais do solo?",
      opts:["As folhas","O caule","A raiz","A flor"], ans:2,
      exp:"É a RAIZ que absorve a água e os sais minerais do solo, através dos pelos absorventes." },
    { id:"t4b-02", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"À mistura de água e sais minerais absorvida pela raiz chamamos...",
      opts:["seiva elaborada","seiva bruta","néctar","pólen"], ans:1,
      exp:"Água + sais minerais = SEIVA BRUTA (ou xilémica). É transportada das raízes para as folhas." },
    { id:"t4b-03", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Os vasos que transportam a seiva bruta da raiz até às folhas são o...",
      opts:["floema","xilema","estoma","pecíolo"], ans:1,
      exp:"O XILEMA (vasos lenhosos) conduz a seiva bruta de baixo para cima, da raiz às folhas." },
    { id:"t4b-04", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Os vasos que distribuem a seiva elaborada por toda a planta são o...",
      opts:["xilema","floema","estoma","cálice"], ans:1,
      exp:"O FLOEMA (vasos liberinos) distribui a seiva elaborada (com glicose) por toda a planta." },
    { id:"t4b-05", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:1,
      q:"As pequenas aberturas na epiderme das folhas que permitem as trocas gasosas chamam-se ___.",
      ans:["estomas"],
      exp:"Os ESTOMAS abrem e fecham para regular a entrada de CO₂ e a saída de O₂ e de vapor de água." },
    { id:"t4b-06", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:2,
      q:"A seiva bruta sobe da raiz até às folhas através do floema.",
      ans:false,
      exp:"Falso. A seiva bruta sobe pelo XILEMA. O floema distribui a seiva elaborada." },
    { id:"t4b-07", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"A libertação de vapor de água pelos estomas das folhas chama-se...",
      opts:["respiração","transpiração","fotossíntese","fecundação"], ans:1,
      exp:"A TRANSPIRAÇÃO é a perda de vapor de água pelos estomas; ajuda a arrefecer a planta e a puxar a seiva bruta." },
    { id:"t4b-08", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:2,
      q:"A transpiração nas folhas ajuda a fazer subir a seiva bruta.",
      ans:true,
      exp:"Verdadeiro. A saída de vapor de água cria uma sucção que ajuda a puxar a seiva bruta pelo xilema." },
    { id:"t4b-09", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:1,
      q:"O gás que a planta retira do ar, pelos estomas, para fazer a fotossíntese é o dióxido de ___.",
      ans:["carbono"],
      exp:"A planta absorve dióxido de carbono (CO₂) do ar — é um dos reagentes da fotossíntese." },
    { id:"t4b-10", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"A energia utilizada pela planta na fotossíntese provém...",
      opts:["do solo","da luz solar","da água","do vento"], ans:1,
      exp:"A energia da LUZ SOLAR é captada pela clorofila e usada para produzir glicose." },
    { id:"t4b-11", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Na fotossíntese, além de oxigénio, a planta produz uma substância que lhe serve de alimento:",
      opts:["clorofila","glicose","água","sais minerais"], ans:1,
      exp:"A fotossíntese produz GLICOSE (alimento da planta) e liberta oxigénio." },
    { id:"t4b-12", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:1,
      q:"As plantas, além de fazerem fotossíntese, também respiram.",
      ans:true,
      exp:"Verdadeiro. As plantas RESPIRAM 24 horas por dia (consomem O₂); só fazem fotossíntese quando há luz." },
    { id:"t4b-13", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Durante a noite, sem luz, a planta...",
      opts:["faz fotossíntese","apenas respira","não troca gases nenhuns","produz glicose"], ans:1,
      exp:"Sem luz não há fotossíntese; à noite a planta APENAS respira (consome O₂, liberta CO₂)." },
    { id:"t4b-14", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:3,
      q:"Em dias muito quentes e secos, os estomas fecham. O que acontece à fotossíntese?",
      opts:["aumenta","diminui, porque entra menos CO₂","fica igual","a planta deixa de respirar"], ans:1,
      exp:"Com os estomas fechados entra menos CO₂, logo a taxa de fotossíntese DIMINUI (a água é um fator limitante)." },
    { id:"t4b-15", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:2,
      q:"Os estomas localizam-se sobretudo na página inferior (de baixo) das folhas.",
      ans:true,
      exp:"Verdadeiro. Ficam sobretudo na parte de baixo da folha, o que reduz a perda de água ao sol." },
    { id:"t4b-16", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"As plantas são fundamentais para os outros seres vivos porque...",
      opts:["libertam oxigénio e servem de alimento","consomem todo o oxigénio do ar","não têm qualquer utilidade","produzem plástico"], ans:0,
      exp:"As plantas libertam O₂ na fotossíntese e estão na base das cadeias alimentares (são produtores)." },
    { id:"t4b-17", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Qual destes produtos NÃO tem origem nas plantas?",
      opts:["papel","cortiça","plástico derivado do petróleo","madeira"], ans:2,
      exp:"Papel, cortiça e madeira vêm de plantas. O plástico deriva do petróleo, não das plantas." },
    { id:"t4b-18", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Numa cadeia alimentar, as plantas ocupam o papel de...",
      opts:["consumidores","produtores","decompositores","predadores"], ans:1,
      exp:"As plantas são PRODUTORES: fabricam o próprio alimento e sustentam os consumidores." },
    { id:"t4b-19", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:2,
      q:"Os seres vivos que produzem o seu próprio alimento, como as plantas, dizem-se ___.",
      ans:["autotróficos","autotroficos","autotrófico","autotrofico"],
      exp:"AUTOTRÓFICOS = produzem o próprio alimento (fotossíntese). Os animais são heterotróficos." },
    { id:"t4b-20", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:2,
      q:"Na respiração celular, a planta consome oxigénio e liberta dióxido de carbono.",
      ans:true,
      exp:"Verdadeiro. A respiração celular consome O₂ + glicose e liberta energia, CO₂ e água." },
    { id:"t4b-21", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"A planta guarda reservas de alimento sobretudo sob a forma de...",
      opts:["amido","clorofila","água","oxigénio"], ans:0,
      exp:"O excesso de glicose é armazenado como AMIDO (por exemplo em tubérculos como a batata)." },
    { id:"t4b-22", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Uma folha com pouca clorofila (amarelada) faz...",
      opts:["mais fotossíntese","menos fotossíntese","apenas respiração e nunca fotossíntese","fecundação"], ans:1,
      exp:"Menos clorofila significa menos captação de luz, logo MENOS fotossíntese." },
    { id:"t4b-23", s:"ciencias", t:"As plantas e o meio", type:"match", diff:2,
      q:"Associa cada estrutura da planta à sua função.",
      pairs:[["Raiz","Absorve água e sais minerais"],["Xilema","Conduz a seiva bruta para cima"],["Floema","Distribui a seiva elaborada"],["Estomas","Permitem as trocas gasosas"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Raiz (absorção), xilema (sobe seiva bruta), floema (distribui seiva elaborada), estomas (trocas gasosas)." },
    { id:"t4b-24", s:"ciencias", t:"As plantas e o meio", type:"match", diff:3,
      q:"Associa cada processo da planta à sua descrição.",
      pairs:[["Fotossíntese","Produz glicose e O₂, com luz"],["Respiração celular","Consome O₂ e glicose, liberta energia"],["Transpiração","Liberta vapor de água pelos estomas"],["Absorção radicular","Entrada de água e sais pela raiz"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Fotossíntese e respiração são processos quase inversos; transpiração e absorção tratam da água." },
    { id:"t4b-25", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:3,
      q:"Ao fim da tarde, a taxa de fotossíntese de uma planta começa a baixar sobretudo porque...",
      opts:["há menos luz","há mais água","há mais dióxido de carbono","há mais sais minerais"], ans:0,
      exp:"A luz é um fator limitante: com menos luz ao entardecer, a fotossíntese diminui." },

    // ============================================================
    // REPRODUÇÃO DAS PLANTAS COM SEMENTE (+25)
    // ============================================================

    { id:"t5b-01", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:1,
      q:"A reprodução das plantas que NÃO envolve flores nem sementes chama-se...",
      opts:["sexuada","assexuada","polinização","germinação"], ans:1,
      exp:"A reprodução ASSEXUADA (vegetativa) origina novas plantas sem flores nem sementes." },
    { id:"t5b-02", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"O morangueiro multiplica-se por caules rastejantes chamados...",
      opts:["tubérculos","estolhos","bolbos","estacas"], ans:1,
      exp:"Os ESTOLHOS são caules rastejantes que dão origem a novas plantas (ex.: morangueiro)." },
    { id:"t5b-03", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"A batateira multiplica-se a partir de caules subterrâneos chamados...",
      opts:["bolbos","rizomas","tubérculos","estolhos"], ans:2,
      exp:"A batata é um TUBÉRCULO — caule subterrâneo que rebenta e origina novas plantas." },
    { id:"t5b-04", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"A cebola e a tulipa reproduzem-se por...",
      opts:["bolbos","tubérculos","estacas","sementes"], ans:0,
      exp:"BOLBOS = caule curto rodeado de folhas carnudas com reservas (cebola, tulipa, alho)." },
    { id:"t5b-05", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Cortar um ramo de roseira e plantá-lo para nascer uma nova planta é reprodução por...",
      opts:["semente","estaca","polinização","germinação"], ans:1,
      exp:"A ESTACA (estacaria) é um pedaço de caule que, plantado, origina uma nova planta igual à mãe." },
    { id:"t5b-06", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:2,
      q:"Na reprodução assexuada, as novas plantas são geneticamente iguais à planta-mãe.",
      ans:true,
      exp:"Verdadeiro. Não há união de gâmetas, por isso as novas plantas são clones da planta-mãe." },
    { id:"t5b-07", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:3,
      q:"Uma vantagem da reprodução assexuada é...",
      opts:["maior variedade genética","ser rápida e não precisar de polinizadores","originar sempre sementes","atrair mais insetos"], ans:1,
      exp:"A reprodução assexuada é rápida e dispensa polinizadores; a desvantagem é a pouca variedade genética." },
    { id:"t5b-08", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:1,
      q:"Ao conjunto das pétalas de uma flor chamamos ___.",
      ans:["corola"],
      exp:"COROLA = conjunto das pétalas (atraem polinizadores). O conjunto das sépalas é o cálice." },
    { id:"t5b-09", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:1,
      q:"As pétalas (corola), geralmente coloridas, servem sobretudo para...",
      opts:["proteger o botão","atrair os polinizadores","produzir pólen","absorver água"], ans:1,
      exp:"As pétalas coloridas e perfumadas ATRAEM os polinizadores (abelhas, borboletas, etc.)." },
    { id:"t5b-10", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:1,
      q:"As sépalas (cálice) têm como função...",
      opts:["atrair insetos","proteger a flor enquanto está em botão","produzir óvulos","fazer fotossíntese"], ans:1,
      exp:"As sépalas (geralmente verdes) formam o cálice, que PROTEGE a flor antes de abrir." },
    { id:"t5b-11", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Cada estame é constituído por...",
      opts:["estigma e estilete","filete e antera","ovário e óvulo","sépala e pétala"], ans:1,
      exp:"Um estame = FILETE (haste) + ANTERA (onde se produz o pólen)." },
    { id:"t5b-12", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:1,
      q:"O pólen é produzido nas anteras dos estames.",
      ans:true,
      exp:"Verdadeiro. As ANTERAS dos estames produzem os grãos de pólen (gâmetas masculinos)." },
    { id:"t5b-13", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Os óvulos da flor encontram-se dentro do...",
      opts:["estigma","ovário","filete","pedúnculo"], ans:1,
      exp:"O OVÁRIO (na base do gineceu) contém os óvulos. Após a fecundação, transforma-se em fruto." },
    { id:"t5b-14", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:2,
      q:"Após a fecundação, o óvulo transforma-se em ___.",
      ans:["semente"],
      exp:"Óvulo fecundado → SEMENTE; ovário → fruto. A semente contém o embrião da nova planta." },
    { id:"t5b-15", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"A semente é constituída por tegumento, reservas alimentares e...",
      opts:["ovário","embrião","pólen","néctar"], ans:1,
      exp:"A semente tem tegumento (proteção), reservas (cotilédones) e o EMBRIÃO (futura planta)." },
    { id:"t5b-16", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:2,
      q:"O invólucro que protege a semente chama-se ___.",
      ans:["tegumento"],
      exp:"O TEGUMENTO é a casca que protege o embrião e as reservas da semente." },
    { id:"t5b-17", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Frutos como a maçã, a laranja e o pêssego são frutos...",
      opts:["secos","carnudos","sem sementes","assexuados"], ans:1,
      exp:"Frutos CARNUDOS têm pericarpo mole e sumarento (maçã, laranja, pêssego)." },
    { id:"t5b-18", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Frutos como o feijão, a ervilha e a noz são frutos...",
      opts:["carnudos","secos","bagas","sem semente"], ans:1,
      exp:"Frutos SECOS têm pericarpo duro/seco (feijão, ervilha, noz, avelã)." },
    { id:"t5b-19", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"A dispersão das sementes feita por animais chama-se...",
      opts:["anemocoria","hidrocoria","zoocoria","autocoria"], ans:2,
      exp:"ZOOCORIA = dispersão por animais (frutos comidos ou sementes que se agarram ao pelo)." },
    { id:"t5b-20", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:3,
      q:"A giesta, cujo fruto rebenta e lança as sementes para longe, é um exemplo de autodisseminação (autocoria).",
      ans:true,
      exp:"Verdadeiro. Na AUTOCORIA é a própria planta que projeta as sementes (giesta, ervilhaca)." },
    { id:"t5b-21", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:3,
      q:"As flores polinizadas pelo vento (anemófilas) costumam ser...",
      opts:["grandes, coloridas e perfumadas","pequenas, discretas e com muito pólen leve","carnudas e doces","sem pólen"], ans:1,
      exp:"Sem precisarem de atrair animais, as flores anemófilas são discretas e produzem muito pólen leve." },
    { id:"t5b-22", s:"ciencias", t:"Reprodução das plantas com semente", type:"match", diff:2,
      q:"Associa cada forma de reprodução assexuada ao seu exemplo.",
      pairs:[["Estolho","Morangueiro"],["Tubérculo","Batateira"],["Bolbo","Cebola"],["Estaca","Roseira"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Estolho (morangueiro), tubérculo (batata), bolbo (cebola/tulipa), estaca (roseira/videira)." },
    { id:"t5b-23", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Durante a germinação, a parte do embrião que origina o caule é o...",
      opts:["radícula","caulículo","tegumento","cotilédone"], ans:1,
      exp:"A radícula origina a raiz e o CAULÍCULO origina o caule; a gémula dá as primeiras folhas." },
    { id:"t5b-24", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:2,
      q:"A gémula dá origem às primeiras folhas da nova planta.",
      ans:true,
      exp:"Verdadeiro. A gémula desenvolve-se nas primeiras folhas, que depois começam a fazer fotossíntese." },
    { id:"t5b-25", s:"ciencias", t:"Reprodução das plantas com semente", type:"match", diff:2,
      q:"Associa cada conjunto da flor à sua definição.",
      pairs:[["Androceu","Parte masculina (estames)"],["Gineceu","Parte feminina (carpelos)"],["Cálice","Conjunto das sépalas"],["Corola","Conjunto das pétalas"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Androceu (♂, estames) e gineceu (♀, carpelos) reproduzem; cálice e corola protegem/atraem." }

];
if (typeof window !== 'undefined') window.EXERCISES_6_C_EXTRA4 = EXERCISES_6_C_EXTRA4;
