// EscolaPlay - Banco extra do 6.º ano - Inglês (gerado, A1+/A2 CEFR, AE 2018)
// Manuais de referência: Porto Editora "What's Up 6", Texto "Lift Off 6", Leya
const EXERCISES_6_I_EXTRA = [

    // ===================== PAST SIMPLE (50) =====================
    { id:'6ie1', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ Choose the past simple of "go": Yesterday I ___ to school.',
      opts:['goed','went','goes','going'], ans:1,
      exp:'"Go" é irregular: past simple = "went".' },
    { id:'6ie2', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ Last weekend we ___ a great film.',
      opts:['watch','watched','watching','watches'], ans:1,
      exp:'"Watch" é regular: acrescenta -ed → watched.' },
    { id:'6ie3', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ She ___ her homework yesterday.',
      opts:['do','did','done','does'], ans:1,
      exp:'"Do" no past simple = "did" (irregular).' },
    { id:'6ie4', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ I ___ a sandwich for lunch.',
      opts:['eat','ate','eaten','eated'], ans:1,
      exp:'"Eat" → "ate" (irregular).' },
    { id:'6ie5', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ He ___ a new bike last week.',
      opts:['buy','buyed','bought','buying'], ans:2,
      exp:'"Buy" → "bought" (irregular).' },
    { id:'6ie6', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ They ___ to the cinema on Saturday.',
      opts:['go','went','goed','going'], ans:1,
      exp:'"Go" → "went". A frase indica passado (Saturday).' },
    { id:'6ie7', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ Negative: "We saw a film" → "We ___ a film."',
      opts:["didn't see","didn't saw","not saw","don't see"], ans:0,
      exp:'Negativa: didn\'t + verbo na forma base → didn\'t see.' },
    { id:'6ie8', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ Question: "___ you visit your grandma yesterday?"',
      opts:['Do','Did','Are','Was'], ans:1,
      exp:'Perguntas no past simple → Did + sujeito + verbo base.' },
    { id:'6ie9', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ My dad ___ a cake for my birthday.',
      opts:['make','maked','made','making'], ans:2,
      exp:'"Make" → "made" (irregular).' },
    { id:'6ie10', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ We ___ pizza last night.',
      opts:['have','haved','had','having'], ans:2,
      exp:'"Have" → "had" (irregular).' },
    { id:'6ie11', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ Last summer I ___ to Spain with my family.',
      opts:['travel','traveled','travelled','travelling'], ans:2,
      exp:'"Travel" (BrE) duplica o l → travelled.' },
    { id:'6ie12', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ She ___ a beautiful song at the concert.',
      opts:['sing','sang','sung','singed'], ans:1,
      exp:'"Sing" → "sang" (past simple).' },
    { id:'6ie13', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ I ___ a letter to my pen friend last week.',
      opts:['write','writed','wrote','writing'], ans:2,
      exp:'"Write" → "wrote" (irregular).' },
    { id:'6ie14', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ He ___ football yesterday afternoon.',
      opts:['play','plays','played','playing'], ans:2,
      exp:'"Play" é regular: play + ed = played.' },
    { id:'6ie15', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ The children ___ at 8 a.m. this morning.',
      opts:['get up','got up','getted up','getting up'], ans:1,
      exp:'"Get" → "got" (irregular). Past simple de "get up" = "got up".' },
    { id:'6ie16', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ I ___ my keys, but then I ___ them under the sofa.',
      opts:['lose / find','lost / found','losed / finded','losing / finding'], ans:1,
      exp:'"Lose" → "lost" e "find" → "found" (ambos irregulares).' },
    { id:'6ie17', s:'ingles', t:'Past simple', type:'mc', diff:3,
      q:'⏰ Choose the correct sentence:',
      opts:['She didn\'t went to school.','She didn\'t go to school.','She not go to school.','She no went to school.'], ans:1,
      exp:'Após didn\'t usa-se sempre o verbo na forma base: didn\'t go.' },
    { id:'6ie18', s:'ingles', t:'Past simple', type:'mc', diff:3,
      q:'⏰ Choose the correct question:',
      opts:['Did you saw the film?','Did you see the film?','You did see the film?','Saw you the film?'], ans:1,
      exp:'Em perguntas, didn\'t/Did + sujeito + verbo base. → Did you see?' },
    { id:'6ie19', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ My grandfather ___ me a great story last night.',
      opts:['tell','told','telled','telling'], ans:1,
      exp:'"Tell" → "told" (irregular).' },
    { id:'6ie20', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ The dog ___ around the park very fast.',
      opts:['run','runned','ran','running'], ans:2,
      exp:'"Run" → "ran" (irregular).' },
    { id:'6ie21', s:'ingles', t:'Past simple', type:'fill', diff:1,
      q:'⏰ Fill in the past simple of "play": Last Sunday we ___ in the park.',
      ans:['played'],
      exp:'"Play" é regular: play + ed = played.' },
    { id:'6ie22', s:'ingles', t:'Past simple', type:'fill', diff:1,
      q:'⏰ Fill in the past simple of "see": I ___ a rainbow yesterday.',
      ans:['saw'],
      exp:'"See" → "saw" (irregular).' },
    { id:'6ie23', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in the past simple of "drink": She ___ a glass of water.',
      ans:['drank'],
      exp:'"Drink" → "drank" (irregular).' },
    { id:'6ie24', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in the past simple of "sleep": I ___ for ten hours last night.',
      ans:['slept'],
      exp:'"Sleep" → "slept" (irregular).' },
    { id:'6ie25', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: He ___ (give) me a present for my birthday.',
      ans:['gave'],
      exp:'"Give" → "gave" (irregular).' },
    { id:'6ie26', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: They ___ (come) to my house yesterday.',
      ans:['came'],
      exp:'"Come" → "came" (irregular).' },
    { id:'6ie27', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: We ___ (take) lots of photos on holiday.',
      ans:['took'],
      exp:'"Take" → "took" (irregular).' },
    { id:'6ie28', s:'ingles', t:'Past simple', type:'fill', diff:3,
      q:'⏰ Fill in the negative: I ___ (not see) my friends yesterday.',
      ans:["didn't see","did not see"],
      exp:'Negativa: didn\'t + verbo base → didn\'t see.' },
    { id:'6ie29', s:'ingles', t:'Past simple', type:'fill', diff:3,
      q:'⏰ Fill in the question: ___ you ___ (eat) breakfast this morning?',
      ans:['Did / eat','did / eat','Did you eat','did eat'],
      exp:'Pergunta: Did + sujeito + verbo base. → Did you eat?' },
    { id:'6ie30', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: I ___ (read) a great book last week.',
      ans:['read'],
      exp:'"Read" → "read" (escrita igual, mas pronunciado /red/).' },
    { id:'6ie31', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: She ___ (think) it was a good idea.',
      ans:['thought'],
      exp:'"Think" → "thought" (irregular).' },
    { id:'6ie32', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: We ___ (sit) on the bench in the garden.',
      ans:['sat'],
      exp:'"Sit" → "sat" (irregular).' },
    { id:'6ie33', s:'ingles', t:'Past simple', type:'fill', diff:1,
      q:'⏰ Fill in: He ___ (study) hard for the test.',
      ans:['studied'],
      exp:'"Study" termina em consoante + y → studied (y → ied).' },
    { id:'6ie34', s:'ingles', t:'Past simple', type:'fill', diff:1,
      q:'⏰ Fill in: They ___ (visit) their grandparents.',
      ans:['visited'],
      exp:'"Visit" é regular: visit + ed = visited.' },
    { id:'6ie35', s:'ingles', t:'Past simple', type:'fill', diff:2,
      q:'⏰ Fill in: The bus ___ (stop) at the station.',
      ans:['stopped'],
      exp:'"Stop" duplica o p → stopped (regra CVC).' },
    { id:'6ie36', s:'ingles', t:'Past simple', type:'tf', diff:1,
      q:'⏰ True or False: The past simple of "have" is "haved".',
      ans:false,
      exp:'Falso. "Have" → "had" (irregular).' },
    { id:'6ie37', s:'ingles', t:'Past simple', type:'tf', diff:1,
      q:'⏰ True or False: We use "did" to make questions in the past simple.',
      ans:true,
      exp:'Verdadeiro. Did + sujeito + verbo base = pergunta.' },
    { id:'6ie38', s:'ingles', t:'Past simple', type:'tf', diff:2,
      q:'⏰ True or False: After "didn\'t" we use the past form (e.g. "didn\'t went").',
      ans:false,
      exp:'Falso. Após didn\'t usa-se sempre o verbo na forma base: didn\'t go.' },
    { id:'6ie39', s:'ingles', t:'Past simple', type:'tf', diff:2,
      q:'⏰ True or False: "Yesterday", "last week" and "two days ago" are time expressions used with the past simple.',
      ans:true,
      exp:'Verdadeiro. São marcadores típicos de passado.' },
    { id:'6ie40', s:'ingles', t:'Past simple', type:'tf', diff:2,
      q:'⏰ True or False: The past simple of "stand" is "stood".',
      ans:true,
      exp:'Verdadeiro. "Stand" → "stood" (irregular).' },
    { id:'6ie41', s:'ingles', t:'Past simple', type:'mc', diff:3,
      q:'⏰ Choose the correct sentence:',
      opts:['I bought a book and read it.','I buyed a book and readed it.','I bought a book and readed it.','I buy a book and read it yesterday.'], ans:0,
      exp:'"Buy" → "bought"; "read" mantém-se "read" no past simple.' },
    { id:'6ie42', s:'ingles', t:'Past simple', type:'mc', diff:3,
      q:'⏰ Choose the correct sentence with "ago":',
      opts:['Two years ago I live in Lisbon.','Two years ago I lived in Lisbon.','Two years ago I living in Lisbon.','Two years ago I am living in Lisbon.'], ans:1,
      exp:'"ago" exige past simple → I lived.' },
    { id:'6ie43', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ Past simple of "say":',
      opts:['sayed','sayd','said','sed'], ans:2,
      exp:'"Say" → "said" (irregular, pronuncia-se /sed/).' },
    { id:'6ie44', s:'ingles', t:'Past simple', type:'match', diff:2,
      q:'⏰ Match each verb with its past simple form:',
      pairs:[['eat','ate'],['go','went'],['see','saw'],['have','had']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Verbos irregulares: eat-ate, go-went, see-saw, have-had.' },
    { id:'6ie45', s:'ingles', t:'Past simple', type:'match', diff:2,
      q:'⏰ Match each verb with its past simple form:',
      pairs:[['buy','bought'],['think','thought'],['take','took'],['make','made']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Irregulares: buy-bought, think-thought, take-took, make-made.' },
    { id:'6ie46', s:'ingles', t:'Past simple', type:'match', diff:3,
      q:'⏰ Match each verb with its past simple form:',
      pairs:[['write','wrote'],['drink','drank'],['sing','sang'],['run','ran']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Padrão i → a/o em vários verbos irregulares.' },
    { id:'6ie47', s:'ingles', t:'Past simple', type:'mc', diff:3,
      q:'⏰ Which sentence is correct?',
      opts:['Did she went home?','Did she go home?','Does she went home?','She did went home?'], ans:1,
      exp:'Pergunta: Did + sujeito + verbo base → Did she go?' },
    { id:'6ie48', s:'ingles', t:'Past simple', type:'mc', diff:1,
      q:'⏰ I ___ to my friend on the phone for an hour.',
      opts:['talk','talks','talked','talking'], ans:2,
      exp:'"Talk" é regular → talked.' },
    { id:'6ie49', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ Negative form: "She had a dog." → "She ___ a dog."',
      opts:["hadn't","didn't have","not had","don't have"], ans:1,
      exp:'Negativa de past simple → didn\'t + verbo base → didn\'t have.' },
    { id:'6ie50', s:'ingles', t:'Past simple', type:'mc', diff:2,
      q:'⏰ When ___ you ___ your homework?',
      opts:['did / do','do / did','did / did','do / do'], ans:0,
      exp:'Pergunta com Wh-: When + did + sujeito + verbo base → did you do?' },

    // ===================== PRESENT CONTINUOUS (50) =====================
    { id:'6ie51', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 I ___ a book right now.',
      opts:['read','am reading','reads','reading'], ans:1,
      exp:'Present continuous: am/is/are + V-ing → I am reading.' },
    { id:'6ie52', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 She ___ TV at the moment.',
      opts:['watch','watches','is watching','are watching'], ans:2,
      exp:'3.ª pessoa singular: is + V-ing → is watching.' },
    { id:'6ie53', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 They ___ football in the garden.',
      opts:['is playing','are playing','am playing','plays'], ans:1,
      exp:'They → are + V-ing → are playing.' },
    { id:'6ie54', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 We ___ English now.',
      opts:['study','studies','are studying','is studying'], ans:2,
      exp:'We → are + studying.' },
    { id:'6ie55', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Choose the correct -ing form of "run":',
      opts:['runing','runnning','running','runeing'], ans:2,
      exp:'CVC: duplica-se a consoante final → running.' },
    { id:'6ie56', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Choose the correct -ing form of "write":',
      opts:['writeing','writting','writing','wrting'], ans:2,
      exp:'Verbos terminados em -e: cai o e → writing.' },
    { id:'6ie57', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Choose the correct -ing form of "lie":',
      opts:['lieing','lying','lyeing','liing'], ans:1,
      exp:'Verbos terminados em -ie: ie → y + ing → lying.' },
    { id:'6ie58', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Negative: "He is sleeping." → "He ___ sleeping."',
      opts:['is not','are not','am not','do not'], ans:0,
      exp:'Negativa: is not (isn\'t) + V-ing.' },
    { id:'6ie59', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Question: "___ you eating?"',
      opts:['Do','Are','Is','Am'], ans:1,
      exp:'You → Are + sujeito + V-ing? → Are you eating?' },
    { id:'6ie60', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 Listen! The baby ___.',
      opts:['cry','cries','is crying','are crying'], ans:2,
      exp:'Ação a decorrer agora → is crying.' },
    { id:'6ie61', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Look! It ___ outside.',
      opts:['rain','rains','is raining','are raining'], ans:2,
      exp:'It → is + raining (ação no momento).' },
    { id:'6ie62', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 My brother and I ___ a film tonight.',
      opts:['watch','watches','am watching','are watching'], ans:3,
      exp:'My brother and I = we → are watching.' },
    { id:'6ie63', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 The cat ___ on the sofa.',
      opts:['sleep','sleeps','is sleeping','are sleeping'], ans:2,
      exp:'The cat = it → is + sleeping.' },
    { id:'6ie64', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 She ___ her friend at the moment.',
      opts:['help','helps','is helping','are helping'], ans:2,
      exp:'She → is + helping.' },
    { id:'6ie65', s:'ingles', t:'Present continuous', type:'mc', diff:3,
      q:'🏃 Choose the correct sentence:',
      opts:['I am study English now.','I studying English now.','I am studying English now.','I study English now.'], ans:2,
      exp:'Present continuous = am/is/are + V-ing → I am studying.' },
    { id:'6ie66', s:'ingles', t:'Present continuous', type:'mc', diff:3,
      q:'🏃 Choose the correct question:',
      opts:['What you doing?','What are you doing?','What do you doing?','What you are doing?'], ans:1,
      exp:'Wh- + are/is + sujeito + V-ing → What are you doing?' },
    { id:'6ie67', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Negative: "We are dancing." → "We ___ dancing."',
      opts:['are not','is not','am not','do not'], ans:0,
      exp:'We + are not (aren\'t) + V-ing.' },
    { id:'6ie68', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 The students ___ to the teacher right now.',
      opts:['listen','listens','is listening','are listening'], ans:3,
      exp:'The students = they → are + listening.' },
    { id:'6ie69', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Tom ___ his bike in the park.',
      opts:['ride','rides','is riding','are riding'], ans:2,
      exp:'Tom = he → is + riding (verbo termina em -e: cai o e).' },
    { id:'6ie70', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 What ___ doing now?',
      opts:['do you','are you','you are','is you'], ans:1,
      exp:'What + are + you + doing? → Que estás a fazer agora?' },
    { id:'6ie71', s:'ingles', t:'Present continuous', type:'fill', diff:1,
      q:'🏃 Fill in: I ___ (read) a book now.',
      ans:['am reading',"'m reading"],
      exp:'I + am + reading.' },
    { id:'6ie72', s:'ingles', t:'Present continuous', type:'fill', diff:1,
      q:'🏃 Fill in: She ___ (sing) a song.',
      ans:['is singing',"'s singing"],
      exp:'She + is + singing.' },
    { id:'6ie73', s:'ingles', t:'Present continuous', type:'fill', diff:2,
      q:'🏃 Fill in: They ___ (swim) in the pool.',
      ans:['are swimming',"'re swimming"],
      exp:'They + are + swimming (CVC: duplica-se o m).' },
    { id:'6ie74', s:'ingles', t:'Present continuous', type:'fill', diff:2,
      q:'🏃 Fill in: We ___ (have) lunch right now.',
      ans:['are having',"'re having"],
      exp:'We + are + having (cai o -e final).' },
    { id:'6ie75', s:'ingles', t:'Present continuous', type:'fill', diff:2,
      q:'🏃 Fill in: He ___ (write) an email.',
      ans:['is writing',"'s writing"],
      exp:'He + is + writing (cai o -e final).' },
    { id:'6ie76', s:'ingles', t:'Present continuous', type:'fill', diff:2,
      q:'🏃 Fill in: The dog ___ (run) in the garden.',
      ans:['is running',"'s running"],
      exp:'It + is + running (CVC: duplica-se o n).' },
    { id:'6ie77', s:'ingles', t:'Present continuous', type:'fill', diff:1,
      q:'🏃 Fill in: I ___ (study) for the test.',
      ans:['am studying',"'m studying"],
      exp:'I + am + studying.' },
    { id:'6ie78', s:'ingles', t:'Present continuous', type:'fill', diff:3,
      q:'🏃 Fill in negative: She ___ (not listen) to music.',
      ans:["isn't listening",'is not listening'],
      exp:'She + is not (isn\'t) + listening.' },
    { id:'6ie79', s:'ingles', t:'Present continuous', type:'fill', diff:3,
      q:'🏃 Fill in question: What ___ you ___ (do) now?',
      ans:['are / doing','are doing'],
      exp:'What + are + you + doing? → Que estás a fazer?' },
    { id:'6ie80', s:'ingles', t:'Present continuous', type:'fill', diff:2,
      q:'🏃 Fill in: It ___ (rain) right now.',
      ans:['is raining',"'s raining"],
      exp:'It + is + raining.' },
    { id:'6ie81', s:'ingles', t:'Present continuous', type:'fill', diff:2,
      q:'🏃 Fill in -ing: lie → ___',
      ans:['lying'],
      exp:'Verbos em -ie: ie → y + ing → lying.' },
    { id:'6ie82', s:'ingles', t:'Present continuous', type:'fill', diff:1,
      q:'🏃 Fill in -ing: play → ___',
      ans:['playing'],
      exp:'Verbo termina em -ay → simplesmente acrescenta -ing.' },
    { id:'6ie83', s:'ingles', t:'Present continuous', type:'tf', diff:1,
      q:'🏃 True or False: The present continuous expresses an action happening now.',
      ans:true,
      exp:'Verdadeiro. Usa-se para ações no momento da fala.' },
    { id:'6ie84', s:'ingles', t:'Present continuous', type:'tf', diff:1,
      q:'🏃 True or False: We use "do/does" to make questions in the present continuous.',
      ans:false,
      exp:'Falso. Usa-se am/is/are + sujeito + V-ing.' },
    { id:'6ie85', s:'ingles', t:'Present continuous', type:'tf', diff:2,
      q:'🏃 True or False: "I am go to school now" is correct.',
      ans:false,
      exp:'Falso. O correto é "I am going to school now".' },
    { id:'6ie86', s:'ingles', t:'Present continuous', type:'tf', diff:2,
      q:'🏃 True or False: "Now", "at the moment" and "right now" are typical with present continuous.',
      ans:true,
      exp:'Verdadeiro. São marcadores temporais típicos.' },
    { id:'6ie87', s:'ingles', t:'Present continuous', type:'tf', diff:2,
      q:'🏃 True or False: The -ing form of "swim" is "swimming".',
      ans:true,
      exp:'Verdadeiro. Regra CVC: duplica-se o m → swimming.' },
    { id:'6ie88', s:'ingles', t:'Present continuous', type:'mc', diff:3,
      q:'🏃 Choose the correct sentence:',
      opts:['He doesn\'t playing now.','He isn\'t playing now.','He not playing now.','He don\'t playing now.'], ans:1,
      exp:'Negativa do present continuous: isn\'t + V-ing.' },
    { id:'6ie89', s:'ingles', t:'Present continuous', type:'mc', diff:3,
      q:'🏃 Choose the correct -ing form of "sit":',
      opts:['siting','sitting','siteing','siting'], ans:1,
      exp:'CVC: duplica-se o t → sitting.' },
    { id:'6ie90', s:'ingles', t:'Present continuous', type:'match', diff:2,
      q:'🏃 Match each verb with its -ing form:',
      pairs:[['run','running'],['write','writing'],['lie','lying'],['play','playing']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Regras de spelling: run→running (CVC), write→writing (cai o e), lie→lying (ie→y), play→playing.' },
    { id:'6ie91', s:'ingles', t:'Present continuous', type:'match', diff:2,
      q:'🏃 Match each subject with the right form of "to be":',
      pairs:[['I','am'],['He / She / It','is'],['You / We / They','are'],['The dogs','are']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'I am, he/she/it is, you/we/they/plural are.' },
    { id:'6ie92', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 The boys ___ basketball now.',
      opts:['plays','play','is playing','are playing'], ans:3,
      exp:'The boys = they → are + playing.' },
    { id:'6ie93', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 Look at her! She ___ a beautiful dress.',
      opts:['wear','wears','is wearing','are wearing'], ans:2,
      exp:'She → is + wearing.' },
    { id:'6ie94', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 What ___ she ___?',
      opts:['is / doing','does / do','is / do','are / doing'], ans:0,
      exp:'What + is + she + doing? (3.ª pessoa singular).' },
    { id:'6ie95', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 We ___ to the radio at the moment.',
      opts:['listen','listens','is listening','are listening'], ans:3,
      exp:'We → are + listening.' },
    { id:'6ie96', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 He ___ a sandwich right now.',
      opts:['eat','eats','is eating','are eating'], ans:2,
      exp:'He → is + eating.' },
    { id:'6ie97', s:'ingles', t:'Present continuous', type:'mc', diff:3,
      q:'🏃 Choose the correct sentence:',
      opts:['Are you reading a book?','Do you reading a book?','You are reading a book?','Reading you a book?'], ans:0,
      exp:'Pergunta: Are + you + V-ing? → Are you reading?' },
    { id:'6ie98', s:'ingles', t:'Present continuous', type:'mc', diff:1,
      q:'🏃 I ___ my homework now.',
      opts:['do','does','am doing','is doing'], ans:2,
      exp:'I + am + doing.' },
    { id:'6ie99', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 The teacher ___ on the board.',
      opts:['write','writes','is writing','are writing'], ans:2,
      exp:'The teacher = he/she → is + writing.' },
    { id:'6ie100', s:'ingles', t:'Present continuous', type:'mc', diff:2,
      q:'🏃 They ___ a movie at the cinema right now.',
      opts:['watch','watches','is watching','are watching'], ans:3,
      exp:'They → are + watching.' },

    // ===================== FUTURE (50) =====================
    { id:'6ie101', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 Tomorrow I ___ visit my grandma.',
      opts:['will','willl','am','do'], ans:0,
      exp:'Future simple: will + verbo base → will visit.' },
    { id:'6ie102', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 We ___ go to the beach next Sunday.',
      opts:['will','wills','willing','willed'], ans:0,
      exp:'will + verbo base; will é igual para todos os sujeitos.' },
    { id:'6ie103', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 She ___ play tennis next weekend.',
      opts:['will play','wills play','will plays','is play'], ans:0,
      exp:'will + verbo base = will play (não muda para 3.ª pessoa).' },
    { id:'6ie104', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 I think it ___ rain tomorrow.',
      opts:['will','is going to','am going','wills'], ans:0,
      exp:'Predições com base na opinião → will (I think it will...).' },
    { id:'6ie105', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 Look at those clouds! It ___ rain.',
      opts:['will','is going to','goes to','wills'], ans:1,
      exp:'Predições com evidência → going to (it is going to rain).' },
    { id:'6ie106', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 I ___ buy a new bike next month. (plano)',
      opts:['will','am going to','is going to','goes to'], ans:1,
      exp:'Planos / intenções → be going to → I am going to buy.' },
    { id:'6ie107', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 Negative: "He will come." → "He ___ come."',
      opts:['will not','wills not','not will','don\'t will'], ans:0,
      exp:'Negativa: will not (won\'t) + verbo base.' },
    { id:'6ie108', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 Question: "___ you help me, please?"',
      opts:['Do','Will','Are','Is'], ans:1,
      exp:'Will + sujeito + verbo base? → Will you help me?' },
    { id:'6ie109', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 They ___ travel to Paris next summer. (plano)',
      opts:['will','are going to','is going to','am going to'], ans:1,
      exp:'They → are going to + verbo base = plano.' },
    { id:'6ie110', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 The contraction of "will not" is:',
      opts:['willn\'t','won\'t','willnot','wont'], ans:1,
      exp:'will not = won\'t.' },
    { id:'6ie111', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 I am tired. I ___ have a nap. (decisão no momento)',
      opts:['will','am going to','is going to','do'], ans:0,
      exp:'Decisões espontâneas → will → I will have a nap.' },
    { id:'6ie112', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 I ___ meet John at 5 p.m. (compromisso/marcação)',
      opts:['will meet','am meeting','meet','meets'], ans:1,
      exp:'Compromissos/arranjos → present continuous → am meeting.' },
    { id:'6ie113', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 Tomorrow ___ be a sunny day.',
      opts:['will','wills','is','do'], ans:0,
      exp:'will + verbo base → will be.' },
    { id:'6ie114', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 We ___ a party next Saturday. We have already invited everyone! (plano)',
      opts:['will have','are going to have','is going to have','have'], ans:1,
      exp:'Planos confirmados → be going to → are going to have.' },
    { id:'6ie115', s:'ingles', t:'Future', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['He will to come tomorrow.','He will come tomorrow.','He wills come tomorrow.','He coming tomorrow.'], ans:1,
      exp:'will + verbo base (sem "to") → will come.' },
    { id:'6ie116', s:'ingles', t:'Future', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['I am going to study tonight.','I going to study tonight.','I am go to study tonight.','I am going study tonight.'], ans:0,
      exp:'be + going to + verbo base → I am going to study.' },
    { id:'6ie117', s:'ingles', t:'Future', type:'fill', diff:1,
      q:'🌍 Fill in: I ___ (call) you later. (decisão agora)',
      ans:['will call',"'ll call"],
      exp:'Decisão no momento → will + verbo base = will call.' },
    { id:'6ie118', s:'ingles', t:'Future', type:'fill', diff:2,
      q:'🌍 Fill in: She ___ (visit) her cousins next month. (plano)',
      ans:['is going to visit',"'s going to visit"],
      exp:'Planos → be going to → is going to visit.' },
    { id:'6ie119', s:'ingles', t:'Future', type:'fill', diff:2,
      q:'🌍 Fill in: It ___ (snow) tomorrow. (predição)',
      ans:['will snow',"'ll snow"],
      exp:'Predição com opinião → will → will snow.' },
    { id:'6ie120', s:'ingles', t:'Future', type:'fill', diff:2,
      q:'🌍 Fill in: We ___ (not / go) to school on Sunday.',
      ans:["won't go",'will not go'],
      exp:'Negativa do future simple: will not (won\'t) + verbo base.' },
    { id:'6ie121', s:'ingles', t:'Future', type:'fill', diff:2,
      q:'🌍 Fill in: ___ you ___ (help) me?',
      ans:['Will / help','Will help','will / help'],
      exp:'Pergunta: Will + sujeito + verbo base? → Will you help?' },
    { id:'6ie122', s:'ingles', t:'Future', type:'fill', diff:2,
      q:'🌍 Fill in: I ___ (meet) my friend at 7 p.m. (arranjo)',
      ans:['am meeting',"'m meeting"],
      exp:'Arranjos com hora marcada → present continuous → am meeting.' },
    { id:'6ie123', s:'ingles', t:'Future', type:'fill', diff:1,
      q:'🌍 Fill in: He ___ (be) 12 next year.',
      ans:['will be',"'ll be"],
      exp:'Future simple: will + be → will be.' },
    { id:'6ie124', s:'ingles', t:'Future', type:'fill', diff:2,
      q:'🌍 Fill in: Look! The girl ___ (fall) off her bike! (predição com evidência)',
      ans:['is going to fall',"'s going to fall"],
      exp:'Predição visível → going to → is going to fall.' },
    { id:'6ie125', s:'ingles', t:'Future', type:'fill', diff:3,
      q:'🌍 Fill in: They ___ (start) building a new school next year. (plano)',
      ans:['are going to start',"'re going to start"],
      exp:'Planos → be going to → are going to start.' },
    { id:'6ie126', s:'ingles', t:'Future', type:'tf', diff:1,
      q:'🌍 True or False: After "will" we use the verb in the base form.',
      ans:true,
      exp:'Verdadeiro. will + verbo base.' },
    { id:'6ie127', s:'ingles', t:'Future', type:'tf', diff:1,
      q:'🌍 True or False: "won\'t" is the contraction of "will not".',
      ans:true,
      exp:'Verdadeiro. will not = won\'t.' },
    { id:'6ie128', s:'ingles', t:'Future', type:'tf', diff:2,
      q:'🌍 True or False: "Be going to" is used for plans and intentions.',
      ans:true,
      exp:'Verdadeiro. Planos: be going to + verbo base.' },
    { id:'6ie129', s:'ingles', t:'Future', type:'tf', diff:2,
      q:'🌍 True or False: "I will to go to bed early" is correct.',
      ans:false,
      exp:'Falso. Após will não se usa "to" → I will go.' },
    { id:'6ie130', s:'ingles', t:'Future', type:'tf', diff:2,
      q:'🌍 True or False: "I am meeting Sara at 6 p.m." can refer to a future arrangement.',
      ans:true,
      exp:'Verdadeiro. Present continuous para arranjos futuros.' },
    { id:'6ie131', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 "Tomorrow", "next week", "in 2030" are time expressions for the ___.',
      opts:['past','present','future','present continuous only'], ans:2,
      exp:'São marcadores temporais de futuro.' },
    { id:'6ie132', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 "She won\'t come" means:',
      opts:['She will come','She will not come','She comes','She came'], ans:1,
      exp:'won\'t = will not → ela não virá.' },
    { id:'6ie133', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 ___ I open the window?',
      opts:['Will','Do','Am','Is'], ans:0,
      exp:'Pergunta de oferta com Will → Shall/Will I open?' },
    { id:'6ie134', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 If I see Tom, I ___ tell him.',
      opts:['will','am going to','going','do'], ans:0,
      exp:'1.º condicional: if + present, will + verbo base.' },
    { id:'6ie135', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 The contraction of "I will" is:',
      opts:['I\'ll','I\'ve','I\'d','I\'m'], ans:0,
      exp:'I will = I\'ll.' },
    { id:'6ie136', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 The contraction of "she will" is:',
      opts:['she\'l','she\'ll','she\'s','she\'d'], ans:1,
      exp:'she will = she\'ll.' },
    { id:'6ie137', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 I have my ticket. I ___ fly to London tomorrow. (plano)',
      opts:['will','am going to','do','goes'], ans:1,
      exp:'Plano confirmado → be going to → am going to fly.' },
    { id:'6ie138', s:'ingles', t:'Future', type:'mc', diff:3,
      q:'🌍 Choose the BEST option: "I haven\'t decided yet, but maybe I ___ go to the party."',
      opts:['will','am going to','am','do'], ans:0,
      exp:'Decisão pouco firme/predição → will.' },
    { id:'6ie139', s:'ingles', t:'Future', type:'mc', diff:3,
      q:'🌍 Choose the BEST option: "The sky is dark. It ___ rain soon."',
      opts:['will','is going to','goes to','rains'], ans:1,
      exp:'Evidência presente → going to.' },
    { id:'6ie140', s:'ingles', t:'Future', type:'match', diff:2,
      q:'🌍 Match each contraction with its full form:',
      pairs:[["I'll","I will"],["won't","will not"],["she'll","she will"],["they'll","they will"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Contrações de will: I\'ll, she\'ll, they\'ll; e won\'t para "will not".' },
    { id:'6ie141', s:'ingles', t:'Future', type:'match', diff:3,
      q:'🌍 Match each situation with its future form:',
      pairs:[['Decision now','will'],['Plan / intention','be going to'],['Future arrangement','present continuous'],['Prediction with evidence','be going to']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'will = decisão; going to = plano/predição com evidência; present continuous = arranjos.' },
    { id:'6ie142', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 We ___ have a test next Monday. (informação)',
      opts:['will','wills','are','do'], ans:0,
      exp:'will + verbo base → will have.' },
    { id:'6ie143', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 What ___ you ___ this weekend? (plano)',
      opts:['will / do','are / going to do','do / do','are / do'], ans:1,
      exp:'Plano → What are you going to do?' },
    { id:'6ie144', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 Negative of "I am going to play" is:',
      opts:["I'm not going to play","I don't go to play","I am not play","I won't going to play"], ans:0,
      exp:'Negativa: am not + going to + verbo → I\'m not going to play.' },
    { id:'6ie145', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 Tomorrow she ___ be at the beach.',
      opts:['will','wills','willn\'t','is'], ans:0,
      exp:'will + be → will be.' },
    { id:'6ie146', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 We are tired. We ___ go to bed now.',
      opts:['will','are going to','do','goes'], ans:0,
      exp:'Decisão no momento → will → will go.' },
    { id:'6ie147', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 Choose the correct question with "going to":',
      opts:['Are you going to study?','Do you going to study?','You going to study?','Are you go to study?'], ans:0,
      exp:'be + sujeito + going to + verbo base → Are you going to study?' },
    { id:'6ie148', s:'ingles', t:'Future', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['Maybe she will phone tonight.','Maybe she phones tonight.','Maybe she is phoning tonight.','Maybe she phoning tonight.'], ans:0,
      exp:'"Maybe" + will → Maybe she will phone (predição incerta).' },
    { id:'6ie149', s:'ingles', t:'Future', type:'mc', diff:1,
      q:'🌍 Next year, my brother ___ start university.',
      opts:['will','wills','are','am'], ans:0,
      exp:'will + verbo base → will start.' },
    { id:'6ie150', s:'ingles', t:'Future', type:'mc', diff:2,
      q:'🌍 They ___ go camping next weekend. They have already booked the campsite. (plano firme)',
      opts:['will','are going to','do','goes'], ans:1,
      exp:'Plano firme → be going to → are going to go.' },

    // ===================== COMPARATIVES & SUPERLATIVES (50) =====================
    { id:'6ie151', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Comparative of "tall":',
      opts:['taller','more tall','tallest','tall'], ans:0,
      exp:'Adjetivos curtos: + er → taller.' },
    { id:'6ie152', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Superlative of "tall":',
      opts:['taller','more tall','the tallest','most tall'], ans:2,
      exp:'Adjetivos curtos: the + adj + est → the tallest.' },
    { id:'6ie153', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Comparative of "big":',
      opts:['biger','bigger','more big','biggest'], ans:1,
      exp:'CVC: duplica-se a consoante final → bigger.' },
    { id:'6ie154', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Superlative of "happy":',
      opts:['happiest','the happiest','more happy','most happy'], ans:1,
      exp:'Adjetivo terminado em -y: y → i + est → the happiest.' },
    { id:'6ie155', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Comparative of "happy":',
      opts:['happier','happyer','more happy','happiest'], ans:0,
      exp:'y → i + er → happier.' },
    { id:'6ie156', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Comparative of "expensive":',
      opts:['expensiver','more expensive','expensivest','most expensive'], ans:1,
      exp:'Adjetivos longos: more + adj → more expensive.' },
    { id:'6ie157', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Superlative of "interesting":',
      opts:['interestinger','the most interesting','more interesting','interestest'], ans:1,
      exp:'Adjetivos longos: the most + adj → the most interesting.' },
    { id:'6ie158', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Comparative of "good":',
      opts:['gooder','better','best','more good'], ans:1,
      exp:'good → better → the best (irregular).' },
    { id:'6ie159', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Superlative of "good":',
      opts:['gooder','better','the best','more good'], ans:2,
      exp:'good → better → the best.' },
    { id:'6ie160', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Comparative of "bad":',
      opts:['badder','worse','worst','more bad'], ans:1,
      exp:'bad → worse → the worst (irregular).' },
    { id:'6ie161', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Superlative of "bad":',
      opts:['baddest','worse','the worst','more bad'], ans:2,
      exp:'bad → worse → the worst.' },
    { id:'6ie162', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 We use "than" with:',
      opts:['superlatives','comparatives','adverbs only','plural nouns'], ans:1,
      exp:'Comparativos: A is + er/more...+ than + B.' },
    { id:'6ie163', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 We use "the" with:',
      opts:['comparatives','superlatives','adverbs only','prepositions'], ans:1,
      exp:'Superlativos: the + tallest / the most + adj.' },
    { id:'6ie164', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 My brother is ___ than me.',
      opts:['old','older','oldest','more older'], ans:1,
      exp:'older + than (comparativo).' },
    { id:'6ie165', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 The Nile is ___ river in the world.',
      opts:['the longer','the longest','longer','longest'], ans:1,
      exp:'Superlativo: the + adj + est → the longest.' },
    { id:'6ie166', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 This book is ___ than that one.',
      opts:['interestinger','more interesting','most interesting','the most interesting'], ans:1,
      exp:'Adjetivo longo: more + adj + than → more interesting than.' },
    { id:'6ie167', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['She is more taller than me.','She is taller than me.','She is more tall than me.','She is the more tall than me.'], ans:1,
      exp:'tall é curto → taller (não se usa "more taller").' },
    { id:'6ie168', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['He is the most fast runner.','He is the fastest runner.','He is more fast runner.','He is the more fastest runner.'], ans:1,
      exp:'fast é curto → the fastest.' },
    { id:'6ie169', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Comparative of "far":',
      opts:['farer','farther','farest','more far'], ans:1,
      exp:'far → farther / further (irregular).' },
    { id:'6ie170', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Superlative of "much":',
      opts:['mucher','more','the most','the much'], ans:2,
      exp:'much/many → more → the most (irregular).' },
    { id:'6ie171', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:1,
      q:'🌍 Fill in: A cheetah is ___ (fast) than a horse.',
      ans:['faster'],
      exp:'fast é curto → faster.' },
    { id:'6ie172', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:1,
      q:'🌍 Fill in: Mount Everest is the ___ (high) mountain in the world.',
      ans:['highest'],
      exp:'high é curto → the highest.' },
    { id:'6ie173', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:2,
      q:'🌍 Fill in: This exercise is ___ (difficult) than that one.',
      ans:['more difficult'],
      exp:'difficult é longo → more difficult.' },
    { id:'6ie174', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:2,
      q:'🌍 Fill in: Math is the ___ (interesting) subject for me.',
      ans:['most interesting'],
      exp:'interesting é longo → the most interesting.' },
    { id:'6ie175', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:2,
      q:'🌍 Fill in: My grades are ___ (good) than last year.',
      ans:['better'],
      exp:'good → better (irregular).' },
    { id:'6ie176', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:2,
      q:'🌍 Fill in: This is the ___ (bad) film I have ever seen.',
      ans:['worst'],
      exp:'bad → worse → the worst.' },
    { id:'6ie177', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:3,
      q:'🌍 Fill in: Today is ___ (hot) than yesterday.',
      ans:['hotter'],
      exp:'hot é curto + CVC → hotter.' },
    { id:'6ie178', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:2,
      q:'🌍 Fill in: She is the ___ (young) in the family.',
      ans:['youngest'],
      exp:'young é curto → the youngest.' },
    { id:'6ie179', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:2,
      q:'🌍 Fill in: My bag is ___ (heavy) than yours.',
      ans:['heavier'],
      exp:'heavy → y → i + er → heavier.' },
    { id:'6ie180', s:'ingles', t:'Comparatives & superlatives', type:'fill', diff:3,
      q:'🌍 Fill in: He is the ___ (good) student in the class.',
      ans:['best'],
      exp:'good → better → the best.' },
    { id:'6ie181', s:'ingles', t:'Comparatives & superlatives', type:'tf', diff:1,
      q:'🌍 True or False: "More good" is correct.',
      ans:false,
      exp:'Falso. good → better (irregular).' },
    { id:'6ie182', s:'ingles', t:'Comparatives & superlatives', type:'tf', diff:1,
      q:'🌍 True or False: With short adjectives we add -er for the comparative.',
      ans:true,
      exp:'Verdadeiro. tall → taller, fast → faster.' },
    { id:'6ie183', s:'ingles', t:'Comparatives & superlatives', type:'tf', diff:2,
      q:'🌍 True or False: With long adjectives we use "more" or "the most".',
      ans:true,
      exp:'Verdadeiro. interesting → more/most interesting.' },
    { id:'6ie184', s:'ingles', t:'Comparatives & superlatives', type:'tf', diff:2,
      q:'🌍 True or False: "Worse" and "the worst" are the comparative and superlative of "bad".',
      ans:true,
      exp:'Verdadeiro. bad → worse → the worst.' },
    { id:'6ie185', s:'ingles', t:'Comparatives & superlatives', type:'tf', diff:2,
      q:'🌍 True or False: "She is the more clever girl" is correct.',
      ans:false,
      exp:'Falso. clever pode usar "the cleverest" ou "the most clever".' },
    { id:'6ie186', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 The ___ city in Portugal is Lisbon.',
      opts:['biger','bigger','biggest','more big'], ans:2,
      exp:'Superlativo: the + biggest (CVC).' },
    { id:'6ie187', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 An elephant is ___ than a dog.',
      opts:['heavier','more heavy','heaviest','heavyer'], ans:0,
      exp:'heavy → heavier (y → i + er).' },
    { id:'6ie188', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 My new phone is ___ than my old one.',
      opts:['most modern','more modern','moderner','modernest'], ans:1,
      exp:'modern (longo) → more modern.' },
    { id:'6ie189', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Who is ___ in your class?',
      opts:['the taller','the tallest','tallest','most tall'], ans:1,
      exp:'Superlativo: the tallest.' },
    { id:'6ie190', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:3,
      q:'🌍 Comparative of "little":',
      opts:['littler','less','more little','the least'], ans:1,
      exp:'little → less → the least (irregular, quantidade).' },
    { id:'6ie191', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:3,
      q:'🌍 Superlative of "little":',
      opts:['little','less','the least','most little'], ans:2,
      exp:'little → less → the least.' },
    { id:'6ie192', s:'ingles', t:'Comparatives & superlatives', type:'match', diff:2,
      q:'🌍 Match each adjective with its comparative form:',
      pairs:[['tall','taller'],['big','bigger'],['happy','happier'],['expensive','more expensive']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Curtos +er; CVC duplica; -y → -ier; longos: more.' },
    { id:'6ie193', s:'ingles', t:'Comparatives & superlatives', type:'match', diff:2,
      q:'🌍 Match each adjective with its superlative form:',
      pairs:[['good','the best'],['bad','the worst'],['far','the farthest'],['much','the most']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Superlativos irregulares.' },
    { id:'6ie194', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 A cheetah runs ___ than a man.',
      opts:['fast','faster','fastest','more fast'], ans:1,
      exp:'fast (curto) → faster.' },
    { id:'6ie195', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 What is the ___ animal in the world?',
      opts:['danger','more dangerous','most dangerous','dangerest'], ans:2,
      exp:'dangerous (longo) → the most dangerous.' },
    { id:'6ie196', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 My brother is ___ than my sister.',
      opts:['younger','more young','youngest','youngerer'], ans:0,
      exp:'young (curto) → younger.' },
    { id:'6ie197', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:2,
      q:'🌍 Today is ___ day of the year!',
      opts:['the happy','happier','the happiest','more happy'], ans:2,
      exp:'happy → the happiest.' },
    { id:'6ie198', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['She is most beautiful than her sister.','She is more beautiful than her sister.','She is beautifuler than her sister.','She is beautifulest than her sister.'], ans:1,
      exp:'beautiful (longo) → more beautiful + than.' },
    { id:'6ie199', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['Mount Everest is the higher mountain.','Mount Everest is the highest mountain.','Mount Everest is more high mountain.','Mount Everest is most high mountain.'], ans:1,
      exp:'Superlativo de high → the highest.' },
    { id:'6ie200', s:'ingles', t:'Comparatives & superlatives', type:'mc', diff:1,
      q:'🌍 Math is ___ than English. (na minha opinião)',
      opts:['easier','easyer','more easy','easiest'], ans:0,
      exp:'easy → y → i + er → easier.' },

    // ===================== DAILY ROUTINES (50) =====================
    { id:'6ie201', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I wake up at 7 a.m." significa:',
      opts:['Vou para a cama às 7','Acordo às 7','Tomo banho às 7','Janto às 7'], ans:1,
      exp:'wake up = acordar.' },
    { id:'6ie202', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I have breakfast" significa:',
      opts:['Tomo o pequeno-almoço','Almoço','Janto','Lancho'], ans:0,
      exp:'breakfast = pequeno-almoço.' },
    { id:'6ie203', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I go to school" significa:',
      opts:['Vou para casa','Vou para a cama','Vou para a escola','Vou ao médico'], ans:2,
      exp:'go to school = ir para a escola.' },
    { id:'6ie204', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I have lunch" significa:',
      opts:['Tomo o pequeno-almoço','Almoço','Janto','Bebo'], ans:1,
      exp:'lunch = almoço.' },
    { id:'6ie205', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I have dinner" significa:',
      opts:['Tomo o pequeno-almoço','Almoço','Janto','Saio'], ans:2,
      exp:'dinner = jantar.' },
    { id:'6ie206', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I brush my teeth" significa:',
      opts:['Lavo os dentes','Lavo as mãos','Lavo o cabelo','Lavo a cara'], ans:0,
      exp:'brush my teeth = lavar/escovar os dentes.' },
    { id:'6ie207', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I do my homework" significa:',
      opts:['Faço a cama','Faço os trabalhos de casa','Faço o jantar','Faço desporto'], ans:1,
      exp:'homework = trabalhos de casa.' },
    { id:'6ie208', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I go to bed" significa:',
      opts:['Vou para a escola','Vou para a cama','Acordo','Levanto-me'], ans:1,
      exp:'go to bed = ir para a cama.' },
    { id:'6ie209', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I get up at 7:30" significa:',
      opts:['Acordo às 7:30','Levanto-me às 7:30','Vou ao trabalho às 7:30','Lancho às 7:30'], ans:1,
      exp:'get up = levantar-se da cama.' },
    { id:'6ie210', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I take a shower" significa:',
      opts:['Tomo banho','Tomo o pequeno-almoço','Tomo um café','Tomo um livro'], ans:0,
      exp:'take a shower = tomar duche/banho.' },
    { id:'6ie211', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I get dressed" significa:',
      opts:['Visto-me','Lavo-me','Levanto-me','Saio'], ans:0,
      exp:'get dressed = vestir-se.' },
    { id:'6ie212', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I watch TV in the evening" significa:',
      opts:['Vejo TV de manhã','Vejo TV ao final do dia / à noite','Estudo TV','Compro TV'], ans:1,
      exp:'in the evening = ao final do dia / à noitinha.' },
    { id:'6ie213', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ Em inglês, "estudar" diz-se:',
      opts:['play','study','sleep','eat'], ans:1,
      exp:'estudar = study.' },
    { id:'6ie214', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "I play with my friends" significa:',
      opts:['Trabalho','Brinco / jogo com os meus amigos','Estudo com a família','Como com os amigos'], ans:1,
      exp:'play = brincar / jogar.' },
    { id:'6ie215', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ Que parte do dia é "in the morning"?',
      opts:['De manhã','De tarde','À noite','De madrugada'], ans:0,
      exp:'in the morning = de manhã.' },
    { id:'6ie216', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ Que parte do dia é "in the afternoon"?',
      opts:['De manhã','De tarde','À noite','À meia-noite'], ans:1,
      exp:'in the afternoon = de tarde.' },
    { id:'6ie217', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ Que parte do dia é "at night"?',
      opts:['De manhã','De tarde','À noite','Ao meio-dia'], ans:2,
      exp:'at night = à noite.' },
    { id:'6ie218', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ Em inglês, "fim de semana" diz-se:',
      opts:['weekend','weekday','week','weekly'], ans:0,
      exp:'fim de semana = weekend.' },
    { id:'6ie219', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "What time do you wake up?" significa:',
      opts:['Quem te acorda?','A que horas acordas?','Onde acordas?','Porque acordas?'], ans:1,
      exp:'What time = a que horas. wake up = acordar.' },
    { id:'6ie220', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ Como se diz "Eu apanho o autocarro"?',
      opts:['I take the bus','I make the bus','I get the bus to','I do the bus'], ans:0,
      exp:'apanhar o autocarro = take the bus.' },
    { id:'6ie221', s:'ingles', t:'Daily routines', type:'fill', diff:1,
      q:'⏰ Fill in: I ___ up at 7 a.m. (acordar)',
      ans:['wake'],
      exp:'wake up = acordar.' },
    { id:'6ie222', s:'ingles', t:'Daily routines', type:'fill', diff:1,
      q:'⏰ Fill in: I ___ breakfast at 8.',
      ans:['have'],
      exp:'have breakfast = tomar o pequeno-almoço.' },
    { id:'6ie223', s:'ingles', t:'Daily routines', type:'fill', diff:1,
      q:'⏰ Fill in: I ___ to school at 8:30.',
      ans:['go'],
      exp:'go to school = ir para a escola.' },
    { id:'6ie224', s:'ingles', t:'Daily routines', type:'fill', diff:1,
      q:'⏰ Fill in: At 1 p.m. we ___ lunch in the canteen.',
      ans:['have'],
      exp:'have lunch = almoçar.' },
    { id:'6ie225', s:'ingles', t:'Daily routines', type:'fill', diff:1,
      q:'⏰ Fill in: I ___ my homework after school.',
      ans:['do'],
      exp:'do homework = fazer os trabalhos de casa.' },
    { id:'6ie226', s:'ingles', t:'Daily routines', type:'fill', diff:1,
      q:'⏰ Fill in: I ___ to bed at 10 p.m.',
      ans:['go'],
      exp:'go to bed = ir para a cama.' },
    { id:'6ie227', s:'ingles', t:'Daily routines', type:'fill', diff:2,
      q:'⏰ Fill in: I ___ my teeth every morning.',
      ans:['brush'],
      exp:'brush my teeth = lavar os dentes.' },
    { id:'6ie228', s:'ingles', t:'Daily routines', type:'fill', diff:2,
      q:'⏰ Fill in: I ___ a shower before breakfast.',
      ans:['take','have'],
      exp:'take/have a shower = tomar duche.' },
    { id:'6ie229', s:'ingles', t:'Daily routines', type:'fill', diff:2,
      q:'⏰ Fill in: I ___ TV in the evening.',
      ans:['watch'],
      exp:'watch TV = ver televisão.' },
    { id:'6ie230', s:'ingles', t:'Daily routines', type:'fill', diff:2,
      q:'⏰ Translate: "Eu levanto-me às 7." → I ___ at 7.',
      ans:['get up'],
      exp:'levantar-se = get up.' },
    { id:'6ie231', s:'ingles', t:'Daily routines', type:'tf', diff:1,
      q:'⏰ True or False: "Breakfast" is the morning meal.',
      ans:true,
      exp:'Verdadeiro. Breakfast = pequeno-almoço.' },
    { id:'6ie232', s:'ingles', t:'Daily routines', type:'tf', diff:1,
      q:'⏰ True or False: "Lunch" is the evening meal.',
      ans:false,
      exp:'Falso. Lunch = almoço; dinner = jantar.' },
    { id:'6ie233', s:'ingles', t:'Daily routines', type:'tf', diff:2,
      q:'⏰ True or False: "Wake up" and "get up" mean exactly the same.',
      ans:false,
      exp:'Falso. wake up = acordar; get up = sair da cama.' },
    { id:'6ie234', s:'ingles', t:'Daily routines', type:'tf', diff:2,
      q:'⏰ True or False: "Brush my hair" means escovar o cabelo.',
      ans:true,
      exp:'Verdadeiro. brush my hair = escovar o cabelo.' },
    { id:'6ie235', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I have a snack at 4 p.m." significa:',
      opts:['Almoço às 4','Lancho às 4','Jantos às 4','Acordo às 4'], ans:1,
      exp:'snack = lanche.' },
    { id:'6ie236', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ Em inglês, "Sou pontual" diz-se:',
      opts:['I am punctual','I am late','I am early','I am tired'], ans:0,
      exp:'punctual = pontual.' },
    { id:'6ie237', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "What\'s the time?" significa:',
      opts:['Que tempo está?','Que horas são?','Que dia é hoje?','Onde estás?'], ans:1,
      exp:'What\'s the time? = Que horas são?' },
    { id:'6ie238', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "It\'s half past seven" significa:',
      opts:['7:00','7:15','7:30','7:45'], ans:2,
      exp:'half past seven = sete e meia (7:30).' },
    { id:'6ie239', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "It\'s a quarter to nine" significa:',
      opts:['9:00','9:15','9:45','8:45'], ans:3,
      exp:'a quarter to nine = um quarto para as nove (8:45).' },
    { id:'6ie240', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "It\'s a quarter past eight" significa:',
      opts:['7:45','8:15','8:30','8:45'], ans:1,
      exp:'a quarter past eight = oito e um quarto (8:15).' },
    { id:'6ie241', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "After school I do my homework" significa:',
      opts:['Antes da escola','Depois da escola','Durante a escola','Em vez da escola'], ans:1,
      exp:'after school = depois da escola.' },
    { id:'6ie242', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "Before going to bed I read a book" significa:',
      opts:['Antes de me deitar leio um livro','Depois de me deitar leio um livro','Enquanto leio vou para a cama','Acordo a ler um livro'], ans:0,
      exp:'before = antes; before going to bed = antes de ir para a cama.' },
    { id:'6ie243', s:'ingles', t:'Daily routines', type:'match', diff:2,
      q:'⏰ Match each routine activity with its Portuguese translation:',
      pairs:[['wake up','acordar'],['have breakfast','tomar o pequeno-almoço'],['go to school','ir para a escola'],['go to bed','ir para a cama']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Rotinas básicas em inglês.' },
    { id:'6ie244', s:'ingles', t:'Daily routines', type:'match', diff:2,
      q:'⏰ Match each meal with its time:',
      pairs:[['breakfast','morning'],['lunch','midday'],['snack','afternoon'],['dinner','evening']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'breakfast (manhã), lunch (meio-dia), snack (tarde), dinner (noite).' },
    { id:'6ie245', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "What do you usually do in the morning?" significa:',
      opts:['Que fazes geralmente de manhã?','Onde estás de manhã?','Quem és tu?','Quando acordas?'], ans:0,
      exp:'usually = geralmente; in the morning = de manhã.' },
    { id:'6ie246', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I get home at 5 p.m." significa:',
      opts:['Saio de casa às 5','Chego a casa às 5','Vou para a escola às 5','Almoço às 5'], ans:1,
      exp:'get home = chegar a casa.' },
    { id:'6ie247', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I leave home at 8" significa:',
      opts:['Chego a casa às 8','Saio de casa às 8','Acordo às 8','Janto às 8'], ans:1,
      exp:'leave home = sair de casa.' },
    { id:'6ie248', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ "I have classes from 8:30 to 1:30" significa:',
      opts:['Tenho aulas das 8:30 às 13:30','Tenho aulas só às 8:30','Tenho aulas das 13:30 às 8:30','Não tenho aulas'], ans:0,
      exp:'from ... to ... = de ... a ...' },
    { id:'6ie249', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'⏰ "After dinner" em português é:',
      opts:['Antes do jantar','Depois do jantar','Durante o jantar','Em vez do jantar'], ans:1,
      exp:'after dinner = depois do jantar.' },
    { id:'6ie250', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'⏰ Pessoa pontual = arrives ___:',
      opts:['late','early','on time','never'], ans:2,
      exp:'on time = à hora certa.' },

    // ===================== HEALTH & BODY (50) =====================
    { id:'6ie251', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Head" em português é:',
      opts:['cabeça','cabelo','pé','mão'], ans:0,
      exp:'head = cabeça.' },
    { id:'6ie252', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Hair" em português é:',
      opts:['cabeça','cabelo','orelha','olho'], ans:1,
      exp:'hair = cabelo.' },
    { id:'6ie253', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Eye" em português é:',
      opts:['olho','orelha','nariz','boca'], ans:0,
      exp:'eye = olho.' },
    { id:'6ie254', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Ear" em português é:',
      opts:['olho','orelha','nariz','perna'], ans:1,
      exp:'ear = orelha / ouvido.' },
    { id:'6ie255', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Nose" em português é:',
      opts:['olho','orelha','nariz','dente'], ans:2,
      exp:'nose = nariz.' },
    { id:'6ie256', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Mouth" em português é:',
      opts:['boca','orelha','olho','mão'], ans:0,
      exp:'mouth = boca.' },
    { id:'6ie257', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Hand" em português é:',
      opts:['pé','mão','perna','braço'], ans:1,
      exp:'hand = mão.' },
    { id:'6ie258', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Arm" em português é:',
      opts:['perna','braço','mão','pé'], ans:1,
      exp:'arm = braço.' },
    { id:'6ie259', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Leg" em português é:',
      opts:['braço','perna','pé','joelho'], ans:1,
      exp:'leg = perna.' },
    { id:'6ie260', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Foot" em português é:',
      opts:['mão','pé','perna','braço'], ans:1,
      exp:'foot = pé. (plural: feet).' },
    { id:'6ie261', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Knee" em português é:',
      opts:['cotovelo','joelho','tornozelo','pulso'], ans:1,
      exp:'knee = joelho.' },
    { id:'6ie262', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Shoulder" em português é:',
      opts:['ombro','cotovelo','peito','costas'], ans:0,
      exp:'shoulder = ombro.' },
    { id:'6ie263', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Back" em português é:',
      opts:['barriga','peito','costas','pescoço'], ans:2,
      exp:'back = costas.' },
    { id:'6ie264', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Chest" em português é:',
      opts:['barriga','peito','costas','pescoço'], ans:1,
      exp:'chest = peito (zona do tórax).' },
    { id:'6ie265', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Stomach" em português é:',
      opts:['estômago / barriga','garganta','peito','costas'], ans:0,
      exp:'stomach = estômago / barriga.' },
    { id:'6ie266', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Neck" em português é:',
      opts:['pescoço','peito','costas','cabeça'], ans:0,
      exp:'neck = pescoço.' },
    { id:'6ie267', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Finger" em português é:',
      opts:['dedo do pé','dedo da mão','unha','pulso'], ans:1,
      exp:'finger = dedo da mão (toe = dedo do pé).' },
    { id:'6ie268', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "I have a headache" significa:',
      opts:['Tenho dor de cabeça','Tenho dor de barriga','Tenho febre','Tenho tosse'], ans:0,
      exp:'headache = dor de cabeça.' },
    { id:'6ie269', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "I have a stomachache" significa:',
      opts:['Tenho dor de cabeça','Tenho dor de barriga','Tenho dor de garganta','Tenho dor de dentes'], ans:1,
      exp:'stomachache = dor de barriga / estômago.' },
    { id:'6ie270', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "I have a sore throat" significa:',
      opts:['Tenho dor de cabeça','Tenho dor de garganta','Tenho dor de costas','Tenho dor de barriga'], ans:1,
      exp:'sore throat = dor de garganta.' },
    { id:'6ie271', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "I have a cold" significa:',
      opts:['Estou constipado','Tenho frio','Tenho febre','Tenho tosse'], ans:0,
      exp:'cold = constipação.' },
    { id:'6ie272', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "I have the flu" significa:',
      opts:['Tenho gripe','Tenho fome','Tenho frio','Tenho calor'], ans:0,
      exp:'flu = gripe.' },
    { id:'6ie273', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "I have a fever" significa:',
      opts:['Tenho fome','Tenho febre','Tenho frio','Tenho sono'], ans:1,
      exp:'fever = febre.' },
    { id:'6ie274', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "I have a cough" significa:',
      opts:['Tenho tosse','Tenho febre','Tenho dor de cabeça','Tenho fome'], ans:0,
      exp:'cough = tosse.' },
    { id:'6ie275', s:'ingles', t:'Health & body', type:'fill', diff:1,
      q:'🏥 Fill in: I see with my ___ (olhos).',
      ans:['eyes'],
      exp:'eyes = olhos (plural de eye).' },
    { id:'6ie276', s:'ingles', t:'Health & body', type:'fill', diff:1,
      q:'🏥 Fill in: I hear with my ___ (orelhas).',
      ans:['ears'],
      exp:'ears = orelhas / ouvidos.' },
    { id:'6ie277', s:'ingles', t:'Health & body', type:'fill', diff:1,
      q:'🏥 Fill in: I smell with my ___ (nariz).',
      ans:['nose'],
      exp:'nose = nariz.' },
    { id:'6ie278', s:'ingles', t:'Health & body', type:'fill', diff:1,
      q:'🏥 Fill in: I walk with my ___ (pés).',
      ans:['feet'],
      exp:'feet = pés (plural de foot, irregular).' },
    { id:'6ie279', s:'ingles', t:'Health & body', type:'fill', diff:2,
      q:'🏥 Fill in: I have a ___ (febre) of 39°C.',
      ans:['fever'],
      exp:'fever = febre.' },
    { id:'6ie280', s:'ingles', t:'Health & body', type:'fill', diff:2,
      q:'🏥 Fill in: My head hurts. I have a ___.',
      ans:['headache'],
      exp:'headache = dor de cabeça.' },
    { id:'6ie281', s:'ingles', t:'Health & body', type:'fill', diff:2,
      q:'🏥 Fill in: He went to the ___ because he was sick. (médico)',
      ans:['doctor',"doctor's"],
      exp:'doctor = médico; go to the doctor\'s = ir ao médico.' },
    { id:'6ie282', s:'ingles', t:'Health & body', type:'fill', diff:2,
      q:'🏥 Fill in: When you are ill you should take ___ (medicamentos).',
      ans:['medicine','medicines'],
      exp:'medicine = medicamento.' },
    { id:'6ie283', s:'ingles', t:'Health & body', type:'tf', diff:1,
      q:'🏥 True or False: "Hand" means mão.',
      ans:true,
      exp:'Verdadeiro. hand = mão.' },
    { id:'6ie284', s:'ingles', t:'Health & body', type:'tf', diff:1,
      q:'🏥 True or False: "Foot" plural is "foots".',
      ans:false,
      exp:'Falso. foot → feet (plural irregular).' },
    { id:'6ie285', s:'ingles', t:'Health & body', type:'tf', diff:2,
      q:'🏥 True or False: "Toothache" means dor de dentes.',
      ans:true,
      exp:'Verdadeiro. toothache = dor de dentes.' },
    { id:'6ie286', s:'ingles', t:'Health & body', type:'tf', diff:2,
      q:'🏥 True or False: "I have a headache" means tenho dor de barriga.',
      ans:false,
      exp:'Falso. headache = dor de cabeça; stomachache = dor de barriga.' },
    { id:'6ie287', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "What\'s the matter?" significa:',
      opts:['Que se passa? / O que tens?','Quem és?','Onde estás?','Que horas são?'], ans:0,
      exp:'What\'s the matter? = O que se passa? Pergunta típica do médico.' },
    { id:'6ie288', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 No médico, ele pode dizer: "You should take this ___."',
      opts:['fever','medicine','doctor','headache'], ans:1,
      exp:'medicine = medicamento.' },
    { id:'6ie289', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "I feel sick" significa:',
      opts:['Sinto-me bem','Sinto-me doente','Estou contente','Estou cansado'], ans:1,
      exp:'sick = doente.' },
    { id:'6ie290', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 Para uma boa saúde, é importante:',
      opts:['eat junk food','do exercise and eat healthy','sleep 2 hours','watch TV all day'], ans:1,
      exp:'do exercise + eat healthy = exercício e alimentação saudável.' },
    { id:'6ie291', s:'ingles', t:'Health & body', type:'mc', diff:3,
      q:'🏥 "I have a backache" significa:',
      opts:['Dor de cabeça','Dor de costas','Dor de barriga','Dor de dentes'], ans:1,
      exp:'backache = dor de costas.' },
    { id:'6ie292', s:'ingles', t:'Health & body', type:'mc', diff:3,
      q:'🏥 "I have an earache" significa:',
      opts:['Dor de ouvidos','Dor de cabeça','Dor de garganta','Dor de barriga'], ans:0,
      exp:'earache = dor de ouvidos.' },
    { id:'6ie293', s:'ingles', t:'Health & body', type:'match', diff:2,
      q:'🏥 Match each body part with its Portuguese name:',
      pairs:[['head','cabeça'],['hand','mão'],['foot','pé'],['leg','perna']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Partes do corpo essenciais.' },
    { id:'6ie294', s:'ingles', t:'Health & body', type:'match', diff:2,
      q:'🏥 Match each illness with its Portuguese name:',
      pairs:[['cold','constipação'],['flu','gripe'],['cough','tosse'],['fever','febre']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Doenças comuns.' },
    { id:'6ie295', s:'ingles', t:'Health & body', type:'match', diff:3,
      q:'🏥 Match each "ache" with the body part:',
      pairs:[['headache','head'],['stomachache','stomach'],['backache','back'],['toothache','tooth']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'parte do corpo + ache = dor.' },
    { id:'6ie296', s:'ingles', t:'Health & body', type:'mc', diff:1,
      q:'🏥 "Doctor" em português é:',
      opts:['enfermeiro','médico','professor','dentista'], ans:1,
      exp:'doctor = médico.' },
    { id:'6ie297', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Nurse" em português é:',
      opts:['médico','enfermeiro','dentista','professor'], ans:1,
      exp:'nurse = enfermeiro/a.' },
    { id:'6ie298', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Hospital" em português é:',
      opts:['hospital','farmácia','escola','consultório'], ans:0,
      exp:'hospital = hospital (cognato).' },
    { id:'6ie299', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "Pharmacy / Chemist\'s" em português é:',
      opts:['hospital','farmácia','escola','clínica'], ans:1,
      exp:'pharmacy / chemist\'s = farmácia.' },
    { id:'6ie300', s:'ingles', t:'Health & body', type:'mc', diff:2,
      q:'🏥 "I should drink a lot of water" significa:',
      opts:['Devia beber muita água','Não posso beber água','Bebo um pouco de água','Não gosto de água'], ans:0,
      exp:'should = devia / deveria (conselho).' },

    // ===================== QUANTIFIERS (50) =====================
    { id:'6ie301', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "I have ___ apples." (afirmativa, plural)',
      opts:['some','any','much','a little'], ans:0,
      exp:'Afirmativas com plural → some.' },
    { id:'6ie302', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "I don\'t have ___ apples." (negativa)',
      opts:['some','any','much','a little'], ans:1,
      exp:'Negativas e perguntas com plural → any.' },
    { id:'6ie303', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "Do you have ___ sugar?" (pergunta, incontável)',
      opts:['some','any','much','many'], ans:1,
      exp:'Perguntas → any. (Em ofertas/ pedidos pode usar-se "some").' },
    { id:'6ie304', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "How ___ books do you have?" (contável)',
      opts:['much','many','any','little'], ans:1,
      exp:'Contáveis → how many.' },
    { id:'6ie305', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "How ___ water do you drink?" (incontável)',
      opts:['much','many','any','little'], ans:0,
      exp:'Incontáveis → how much.' },
    { id:'6ie306', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I have ___ friends." (muitos)',
      opts:['much','many','a little','any'], ans:1,
      exp:'Contáveis no plural com "muitos" → many ou a lot of.' },
    { id:'6ie307', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There is ___ milk in the fridge." (pouco)',
      opts:['a few','a little','many','any'], ans:1,
      exp:'Incontáveis com "um pouco" → a little.' },
    { id:'6ie308', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I have ___ friends in Lisbon." (poucos)',
      opts:['a few','a little','much','any'], ans:0,
      exp:'Contáveis com "poucos" → a few.' },
    { id:'6ie309', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There are ___ chairs in the room." (muitas)',
      opts:['much','many','a little','some'], ans:1,
      exp:'chairs (contável, plural) → many.' },
    { id:'6ie310', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There isn\'t ___ bread on the table." (incontável)',
      opts:['many','any','some','few'], ans:1,
      exp:'Negativa com incontável → any.' },
    { id:'6ie311', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There are ___ students in the class." (muitos)',
      opts:['a lot of','much','any','little'], ans:0,
      exp:'a lot of serve para contável e incontável.' },
    { id:'6ie312', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I drink ___ coffee in the morning." (afirmativa, incontável)',
      opts:['some','any','many','few'], ans:0,
      exp:'Afirmativa com incontável → some.' },
    { id:'6ie313', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "Would you like ___ tea?" (oferta)',
      opts:['some','any','many','few'], ans:0,
      exp:'Em ofertas e pedidos usa-se "some" mesmo em pergunta.' },
    { id:'6ie314', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I have ___ money." (nenhum)',
      opts:['some','no','many','few'], ans:1,
      exp:'no = nenhum/nenhuma (sem auxiliar).' },
    { id:'6ie315', s:'ingles', t:'Quantifiers', type:'mc', diff:3,
      q:'🌍 "I don\'t eat ___ chocolate." (incontável)',
      opts:['many','much','few','a few'], ans:1,
      exp:'Negativa com incontável → much.' },
    { id:'6ie316', s:'ingles', t:'Quantifiers', type:'mc', diff:3,
      q:'🌍 "How ___ time do you need?"',
      opts:['many','much','few','little'], ans:1,
      exp:'time (incontável) → How much.' },
    { id:'6ie317', s:'ingles', t:'Quantifiers', type:'fill', diff:1,
      q:'🌍 Fill in: I have ___ books at home. (afirmativa, alguns)',
      ans:['some'],
      exp:'Afirmativa + plural → some.' },
    { id:'6ie318', s:'ingles', t:'Quantifiers', type:'fill', diff:1,
      q:'🌍 Fill in: I don\'t have ___ time. (incontável, negativa)',
      ans:['any'],
      exp:'Negativa → any.' },
    { id:'6ie319', s:'ingles', t:'Quantifiers', type:'fill', diff:2,
      q:'🌍 Fill in: How ___ apples are there? (contável)',
      ans:['many'],
      exp:'Contável → many.' },
    { id:'6ie320', s:'ingles', t:'Quantifiers', type:'fill', diff:2,
      q:'🌍 Fill in: How ___ sugar do you want? (incontável)',
      ans:['much'],
      exp:'Incontável → much.' },
    { id:'6ie321', s:'ingles', t:'Quantifiers', type:'fill', diff:2,
      q:'🌍 Fill in: There are ___ (poucos) cookies left. Hurry!',
      ans:['a few'],
      exp:'cookies (contável) + poucos → a few.' },
    { id:'6ie322', s:'ingles', t:'Quantifiers', type:'fill', diff:2,
      q:'🌍 Fill in: We need ___ (um pouco de) milk for the cake.',
      ans:['a little'],
      exp:'milk (incontável) + um pouco → a little.' },
    { id:'6ie323', s:'ingles', t:'Quantifiers', type:'fill', diff:2,
      q:'🌍 Fill in: There is ___ (muito) water in the bottle.',
      ans:['a lot of','much'],
      exp:'a lot of (afirmativa) ou much (mais formal/negativa).' },
    { id:'6ie324', s:'ingles', t:'Quantifiers', type:'fill', diff:3,
      q:'🌍 Fill in: I have ___ (nenhum) friends here.',
      ans:['no'],
      exp:'no + substantivo (sem auxiliar negativo).' },
    { id:'6ie325', s:'ingles', t:'Quantifiers', type:'tf', diff:1,
      q:'🌍 True or False: "Many" is used with countable plural nouns.',
      ans:true,
      exp:'Verdadeiro. many + contável plural.' },
    { id:'6ie326', s:'ingles', t:'Quantifiers', type:'tf', diff:1,
      q:'🌍 True or False: "Much" is used with countable plural nouns.',
      ans:false,
      exp:'Falso. much + incontável.' },
    { id:'6ie327', s:'ingles', t:'Quantifiers', type:'tf', diff:2,
      q:'🌍 True or False: "Some" is mainly used in affirmative sentences.',
      ans:true,
      exp:'Verdadeiro. some → afirmativas (e ofertas).' },
    { id:'6ie328', s:'ingles', t:'Quantifiers', type:'tf', diff:2,
      q:'🌍 True or False: "Any" is mainly used in negatives and questions.',
      ans:true,
      exp:'Verdadeiro. any → negativas e perguntas.' },
    { id:'6ie329', s:'ingles', t:'Quantifiers', type:'tf', diff:2,
      q:'🌍 True or False: "A lot of" can be used with both countable and uncountable nouns.',
      ans:true,
      exp:'Verdadeiro. a lot of serve para ambos.' },
    { id:'6ie330', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I have ___ orange juice in my glass." (incontável)',
      opts:['many','some','a few','any'], ans:1,
      exp:'orange juice é incontável; afirmativa → some.' },
    { id:'6ie331', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There aren\'t ___ eggs in the fridge."',
      opts:['some','any','much','a little'], ans:1,
      exp:'Negativa + plural → any.' },
    { id:'6ie332', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I have ___ (poucos) coins in my pocket."',
      opts:['a few','a little','many','much'], ans:0,
      exp:'coins (contável) → a few.' },
    { id:'6ie333', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There is ___ (pouca) cheese left."',
      opts:['a few','a little','many','much'], ans:1,
      exp:'cheese (incontável) → a little.' },
    { id:'6ie334', s:'ingles', t:'Quantifiers', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['How much books do you read?','How many books do you read?','How many water do you drink?','How much books do you read?'], ans:1,
      exp:'books (contável) → How many.' },
    { id:'6ie335', s:'ingles', t:'Quantifiers', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['I have a few money.','I have a little money.','I have many money.','I have a few moneys.'], ans:1,
      exp:'money é incontável → a little money.' },
    { id:'6ie336', s:'ingles', t:'Quantifiers', type:'match', diff:2,
      q:'🌍 Match each quantifier with its use:',
      pairs:[['many','contável (muitos)'],['much','incontável (muito)'],['a few','contável (poucos)'],['a little','incontável (pouco)']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'many/much e a few/a little distinguem-se por contável/incontável.' },
    { id:'6ie337', s:'ingles', t:'Quantifiers', type:'match', diff:2,
      q:'🌍 Match each sentence with the correct quantifier:',
      pairs:[['Affirmative + plural','some'],['Negative + plural','any'],['Question + uncountable','any / much'],['No quantity','no']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'some afirmativa, any negativa/pergunta, no = nenhum.' },
    { id:'6ie338', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "Bread" é:',
      opts:['contável','incontável','sempre plural','sempre singular'], ans:1,
      exp:'bread, water, milk, sugar... são incontáveis.' },
    { id:'6ie339', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "Apple" é:',
      opts:['contável','incontável','adjectivo','verbo'], ans:0,
      exp:'apple, book, chair... são contáveis.' },
    { id:'6ie340', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I have ___ (muito) homework today."',
      opts:['many','a lot of','few','a few'], ans:1,
      exp:'homework é incontável → a lot of (ou much).' },
    { id:'6ie341', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "There are ___ (muitos) cars in the street."',
      opts:['much','many','little','a little'], ans:1,
      exp:'cars (contável plural) → many.' },
    { id:'6ie342', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "I don\'t have ___ ideas about that."',
      opts:['some','any','little','a little'], ans:1,
      exp:'Negativa + plural → any.' },
    { id:'6ie343', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "Is there ___ cheese in the fridge?"',
      opts:['some','any','many','few'], ans:1,
      exp:'Pergunta + incontável → any.' },
    { id:'6ie344', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "Can I have ___ water, please?" (pedido)',
      opts:['any','some','many','few'], ans:1,
      exp:'Pedidos educados → some (mesmo em pergunta).' },
    { id:'6ie345', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "Money" é contável ou incontável?',
      opts:['contável','incontável'], ans:1,
      exp:'money é sempre incontável (não dizemos "moneys").' },
    { id:'6ie346', s:'ingles', t:'Quantifiers', type:'mc', diff:1,
      q:'🌍 "Information" é contável ou incontável?',
      opts:['contável','incontável'], ans:1,
      exp:'information é incontável em inglês.' },
    { id:'6ie347', s:'ingles', t:'Quantifiers', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['I have a little friends.','I have a few friends.','I have many friend.','I have any friends.'], ans:1,
      exp:'friends (contável) + poucos → a few.' },
    { id:'6ie348', s:'ingles', t:'Quantifiers', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['There is much milk in the carton.','There is many milk in the carton.','There is a few milk in the carton.','There are much milk in the carton.'], ans:0,
      exp:'milk incontável → much milk (mais comum em afirmativas: a lot of).' },
    { id:'6ie349', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "She drinks ___ glasses of water a day." (oito)',
      opts:['much','many','any','little'], ans:1,
      exp:'glasses (contável plural) → many.' },
    { id:'6ie350', s:'ingles', t:'Quantifiers', type:'mc', diff:2,
      q:'🌍 "We have ___ (algum) homework for tomorrow."',
      opts:['some','any','many','few'], ans:0,
      exp:'Afirmativa + incontável → some.' },

    // ===================== ADVERBS OF FREQUENCY (50) =====================
    { id:'6ie351', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Always" em português é:',
      opts:['nunca','sempre','às vezes','raramente'], ans:1,
      exp:'always = sempre.' },
    { id:'6ie352', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Never" em português é:',
      opts:['sempre','nunca','às vezes','geralmente'], ans:1,
      exp:'never = nunca.' },
    { id:'6ie353', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Sometimes" em português é:',
      opts:['sempre','nunca','às vezes','raramente'], ans:2,
      exp:'sometimes = às vezes.' },
    { id:'6ie354', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Usually" em português é:',
      opts:['geralmente','nunca','às vezes','raramente'], ans:0,
      exp:'usually = geralmente / habitualmente.' },
    { id:'6ie355', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Often" em português é:',
      opts:['raramente','frequentemente','nunca','sempre'], ans:1,
      exp:'often = frequentemente / muitas vezes.' },
    { id:'6ie356', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Rarely / Seldom" em português é:',
      opts:['sempre','raramente','geralmente','frequentemente'], ans:1,
      exp:'rarely / seldom = raramente.' },
    { id:'6ie357', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Onde se coloca o adverbio de frequência? "I ___ get up early."',
      opts:['always','always not','not always','do always'], ans:0,
      exp:'Antes do verbo principal → I always get up early.' },
    { id:'6ie358', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Com o verbo "to be" o adverbio vai ___:',
      opts:['antes do verbo','depois do verbo','no fim','não se usa'], ans:1,
      exp:'Com to be: He is always late (depois do verbo to be).' },
    { id:'6ie359', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Choose the correct sentence:',
      opts:['I always am happy.','I am always happy.','Always I am happy.','Am I always happy.'], ans:1,
      exp:'Com to be: I am always happy (depois do verbo to be).' },
    { id:'6ie360', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Choose the correct sentence:',
      opts:['She always plays tennis.','She plays always tennis.','Always she plays tennis.','She plays tennis always.'], ans:0,
      exp:'Antes do verbo principal → She always plays tennis.' },
    { id:'6ie361', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 100% do tempo:',
      opts:['always','sometimes','never','rarely'], ans:0,
      exp:'always = 100%.' },
    { id:'6ie362', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 0% do tempo:',
      opts:['always','sometimes','never','often'], ans:2,
      exp:'never = 0%.' },
    { id:'6ie363', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Que adverbio é mais frequente?',
      opts:['rarely','sometimes','often','never'], ans:2,
      exp:'often (frequentemente) > sometimes (às vezes) > rarely (raramente).' },
    { id:'6ie364', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "I ___ go to bed late." (raramente)',
      opts:['always','rarely','often','usually'], ans:1,
      exp:'rarely = raramente.' },
    { id:'6ie365', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "She ___ eats vegetables." (sempre)',
      opts:['never','sometimes','always','rarely'], ans:2,
      exp:'always (sempre).' },
    { id:'6ie366', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "We ___ go to the cinema on Fridays." (geralmente)',
      opts:['never','usually','rarely','seldom'], ans:1,
      exp:'usually = geralmente.' },
    { id:'6ie367', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "How ___ do you go swimming?"',
      opts:['much','many','often','little'], ans:2,
      exp:'How often = com que frequência.' },
    { id:'6ie368', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Resposta a "How often do you study?"',
      opts:['Yes, I do.','Every day.','At school.','For one hour.'], ans:1,
      exp:'How often → frequência (every day, twice a week, etc.).' },
    { id:'6ie369', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:1,
      q:'🌍 Fill in: I ___ (sempre) brush my teeth before bed.',
      ans:['always'],
      exp:'always = sempre. Coloca-se antes do verbo principal.' },
    { id:'6ie370', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:1,
      q:'🌍 Fill in: He ___ (nunca) eats fast food.',
      ans:['never'],
      exp:'never = nunca.' },
    { id:'6ie371', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:2,
      q:'🌍 Fill in: We ___ (às vezes) play in the park.',
      ans:['sometimes'],
      exp:'sometimes = às vezes.' },
    { id:'6ie372', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:2,
      q:'🌍 Fill in: She ___ (frequentemente) goes swimming.',
      ans:['often'],
      exp:'often = frequentemente.' },
    { id:'6ie373', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:2,
      q:'🌍 Fill in: I ___ (geralmente) get up at 7.',
      ans:['usually'],
      exp:'usually = geralmente.' },
    { id:'6ie374', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:2,
      q:'🌍 Fill in: They ___ (raramente) watch TV.',
      ans:['rarely','seldom'],
      exp:'rarely / seldom = raramente.' },
    { id:'6ie375', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:2,
      q:'🌍 Reorder: (always / I / breakfast / have) ___',
      ans:['I always have breakfast'],
      exp:'Adverbio antes do verbo principal → I always have breakfast.' },
    { id:'6ie376', s:'ingles', t:'Adverbs of frequency', type:'fill', diff:3,
      q:'🌍 Reorder: (is / he / late / always) ___',
      ans:['He is always late','he is always late'],
      exp:'Com to be: He is always late.' },
    { id:'6ie377', s:'ingles', t:'Adverbs of frequency', type:'tf', diff:1,
      q:'🌍 True or False: "Always" goes before the main verb.',
      ans:true,
      exp:'Verdadeiro. I always study.' },
    { id:'6ie378', s:'ingles', t:'Adverbs of frequency', type:'tf', diff:2,
      q:'🌍 True or False: With the verb "to be", the adverb goes before the verb.',
      ans:false,
      exp:'Falso. Vai depois do verbo to be: He is always nice.' },
    { id:'6ie379', s:'ingles', t:'Adverbs of frequency', type:'tf', diff:2,
      q:'🌍 True or False: "Never" is used with negative form (never don\'t).',
      ans:false,
      exp:'Falso. "Never" já tem sentido negativo: I never go (não "I don\'t never go").' },
    { id:'6ie380', s:'ingles', t:'Adverbs of frequency', type:'tf', diff:2,
      q:'🌍 True or False: "Often" means muitas vezes / frequentemente.',
      ans:true,
      exp:'Verdadeiro. often = frequentemente.' },
    { id:'6ie381', s:'ingles', t:'Adverbs of frequency', type:'tf', diff:1,
      q:'🌍 True or False: "Sometimes" means às vezes.',
      ans:true,
      exp:'Verdadeiro. sometimes = às vezes.' },
    { id:'6ie382', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['I don\'t never eat meat.','I never eat meat.','I never don\'t eat meat.','Never I eat meat.'], ans:1,
      exp:'never já tem sentido negativo → I never eat meat.' },
    { id:'6ie383', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:3,
      q:'🌍 Choose the correct sentence:',
      opts:['He often is sick.','He is often sick.','Often he sick is.','He sick is often.'], ans:1,
      exp:'Com to be: He is often sick (depois do verbo to be).' },
    { id:'6ie384', s:'ingles', t:'Adverbs of frequency', type:'match', diff:2,
      q:'🌍 Match each adverb with its frequency (%):',
      pairs:[['always','100%'],['usually','80%'],['sometimes','50%'],['never','0%']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Frequências aproximadas dos adverbios.' },
    { id:'6ie385', s:'ingles', t:'Adverbs of frequency', type:'match', diff:2,
      q:'🌍 Match each adverb with its Portuguese:',
      pairs:[['always','sempre'],['often','frequentemente'],['sometimes','às vezes'],['never','nunca']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Tradução de adverbios de frequência.' },
    { id:'6ie386', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "Once a week" significa:',
      opts:['Uma vez por semana','Duas vezes por semana','Todos os dias','Todas as semanas'], ans:0,
      exp:'once = uma vez; once a week = uma vez por semana.' },
    { id:'6ie387', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "Twice a month" significa:',
      opts:['Uma vez por mês','Duas vezes por mês','Todos os meses','Cada dois meses'], ans:1,
      exp:'twice = duas vezes; twice a month = duas vezes por mês.' },
    { id:'6ie388', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Every day" significa:',
      opts:['Todos os dias','Cada semana','Cada mês','Às vezes'], ans:0,
      exp:'every day = todos os dias.' },
    { id:'6ie389', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Three times a week" significa:',
      opts:['Três vezes por semana','Três horas por semana','Três dias por semana','Cada três semanas'], ans:0,
      exp:'three times a week = três vezes por semana.' },
    { id:'6ie390', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "I go to the gym ___ a week."',
      opts:['twice','two','second','two times only'], ans:0,
      exp:'twice a week = duas vezes por semana.' },
    { id:'6ie391', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Choose the correct sentence:',
      opts:['Sometimes I read a book.','I sometimes read a book.','I read a book sometimes.','All are correct.'], ans:3,
      exp:'"Sometimes" pode ir no início, no meio ou no fim da frase.' },
    { id:'6ie392', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "She ___ studies on Sundays." (raramente)',
      opts:['rarely','always','often','usually'], ans:0,
      exp:'rarely = raramente.' },
    { id:'6ie393', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "My grandparents ___ visit us." (frequentemente)',
      opts:['rarely','often','never','seldom'], ans:1,
      exp:'often = frequentemente.' },
    { id:'6ie394', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "I ___ drink coffee. I prefer tea." (nunca)',
      opts:['always','sometimes','never','usually'], ans:2,
      exp:'never = nunca.' },
    { id:'6ie395', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 "Tom ___ tired in the morning." (verbo to be, sempre)',
      opts:['is always','always is','always','is'], ans:0,
      exp:'Com to be: is always (depois do verbo to be).' },
    { id:'6ie396', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 Choose the correct sentence:',
      opts:['How often you go to the cinema?','How often do you go to the cinema?','How often are you go to the cinema?','How often go you to the cinema?'], ans:1,
      exp:'Pergunta no presente simples: How often + do/does + sujeito + verbo.' },
    { id:'6ie397', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:3,
      q:'🌍 Reorder: "always / late / Sara / is / never"',
      opts:['Sara is always never late.','Sara is never always late.','Sara is never late.','Sara always is never late.'], ans:2,
      exp:'Não se usa "always never" juntos. A frase correta é "Sara is never late".' },
    { id:'6ie398', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "Hardly ever" significa quase ___:',
      opts:['sempre','nunca','agora','já'], ans:1,
      exp:'hardly ever = quase nunca.' },
    { id:'6ie399', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:2,
      q:'🌍 "I ___ have time to play." (quase nunca)',
      opts:['always','hardly ever','often','usually'], ans:1,
      exp:'hardly ever = quase nunca.' },
    { id:'6ie400', s:'ingles', t:'Adverbs of frequency', type:'mc', diff:1,
      q:'🌍 Em "She always smiles", o adverbio "always" significa:',
      opts:['nunca','sempre','às vezes','raramente'], ans:1,
      exp:'always = sempre.' }

];
if (typeof window !== 'undefined') window.EXERCISES_6_I_EXTRA = EXERCISES_6_I_EXTRA;
