// EscolaPlay - 6.º ano - Matemática - Tópico dedicado: RAZÕES (treino para teste)
// Foco exclusivo no conceito de razão (não proporções): definição, termos, equivalência,
// simplificação, mesma/diferente espécie, parte-parte/parte-todo, comparação, contextos.
const EXERCISES_6_M_EXTRA3 = [

    // ---- diff 1: conceito, termos, leitura ----
    { id:'6me3_001', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'➗ A razão entre dois números a e b (b≠0) é...',
      opts:['a soma a+b','o quociente a/b','o produto a×b','a diferença a−b'], ans:1,
      exp:'Uma razão compara duas grandezas por quociente (divisão): a/b.' },
    { id:'6me3_002', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'🗣️ A razão 3:5 lê-se...',
      opts:['3 mais 5','3 está para 5','3 vezes 5','3 menos 5'], ans:1,
      exp:'a:b lê-se "a está para b".' },
    { id:'6me3_003', s:'matematica', t:'Razões', type:'fill', diff:1,
      q:'Na razão 7:2, o antecedente é ___.',
      ans:['7'], exp:'O antecedente é o primeiro termo da razão (o de cima).' },
    { id:'6me3_004', s:'matematica', t:'Razões', type:'fill', diff:1,
      q:'Na razão 7:2, o consequente é ___.',
      ans:['2'], exp:'O consequente é o segundo termo da razão (o de baixo).' },
    { id:'6me3_005', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'✍️ Outra forma de escrever a razão 4:9 é...',
      opts:['4/9','9/4','4×9','4+9'], ans:0,
      exp:'a:b é o mesmo que a fração a/b → 4:9 = 4/9.' },
    { id:'6me3_006', s:'matematica', t:'Razões', type:'tf', diff:1,
      q:'A razão 2:3 é igual à razão 3:2.',
      ans:false, exp:'Falso. A ordem importa: 2:3 ≠ 3:2.' },
    { id:'6me3_007', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'👫 Numa turma há 12 rapazes e 15 raparigas. A razão de rapazes para raparigas é...',
      opts:['12:15','15:12','12:27','27:15'], ans:0,
      exp:'Rapazes para raparigas → 12:15 (a ordem segue o enunciado).' },
    { id:'6me3_008', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'👫 Na mesma turma (12 rapazes, 15 raparigas), a razão de rapazes para o total de alunos é...',
      opts:['12:15','12:27','27:12','15:27'], ans:1,
      exp:'Total = 12+15 = 27. Rapazes para total → 12:27.' },
    { id:'6me3_009', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'🟰 A razão 6:8 é equivalente a...',
      opts:['3:4','4:3','6:4','2:8'], ans:0,
      exp:'Dividindo os dois termos por 2: 6:8 = 3:4.' },
    { id:'6me3_010', s:'matematica', t:'Razões', type:'tf', diff:1,
      q:'As razões 1:2 e 4:8 são equivalentes.',
      ans:true, exp:'Verdadeiro. 4:8 dividido por 4 = 1:2.' },
    { id:'6me3_011', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'🔁 Para obter razões equivalentes deve-se...',
      opts:['multiplicar só o antecedente','multiplicar só o consequente','multiplicar ou dividir os DOIS termos pelo mesmo número','somar o mesmo número aos dois termos'], ans:2,
      exp:'Multiplica-se ou divide-se os dois termos pelo mesmo número (≠0).' },
    { id:'6me3_012', s:'matematica', t:'Razões', type:'fill', diff:1,
      q:'50% corresponde à razão 1:___.',
      ans:['2'], exp:'50% = metade = 1:2.' },
    { id:'6me3_013', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'🍬 "Por cada 2 rapazes há 3 raparigas." A razão rapazes:raparigas é...',
      opts:['2:3','3:2','2:5','5:2'], ans:0,
      exp:'Rapazes para raparigas → 2:3.' },
    { id:'6me3_014', s:'matematica', t:'Razões', type:'tf', diff:1,
      q:'Uma razão entre duas grandezas da mesma espécie (ex.: dois comprimentos) não tem unidades.',
      ans:true, exp:'Verdadeiro. Sendo da mesma espécie, as unidades cancelam-se.' },
    { id:'6me3_015', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'⬆️ Numa razão, o número de cima (o primeiro) chama-se...',
      opts:['consequente','antecedente','quociente','produto'], ans:1,
      exp:'Antecedente = 1.º termo; consequente = 2.º termo.' },
    { id:'6me3_016', s:'matematica', t:'Razões', type:'fill', diff:1,
      q:'Simplifica a razão 4:6 (escreve na forma a:b mais simples).',
      ans:['2:3','2 : 3'], exp:'4:6 dividido por 2 = 2:3.' },
    { id:'6me3_017', s:'matematica', t:'Razões', type:'mc', diff:1,
      q:'➗ A razão 5:10 simplificada é...',
      opts:['1:2','2:1','5:1','1:5'], ans:0,
      exp:'5:10 dividido por 5 = 1:2.' },
    { id:'6me3_018', s:'matematica', t:'Razões', type:'tf', diff:1,
      q:'A razão 5:2 já está na forma mais simples (irredutível).',
      ans:true, exp:'Verdadeiro. 5 e 2 não têm divisor comum além de 1.' },

    // ---- diff 2: equivalência, simplificação, comparação, contextos ----
    { id:'6me3_019', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'➗ Simplifica a razão 18:24.',
      opts:['3:4','4:3','9:12','2:3'], ans:0,
      exp:'18:24 dividido por 6 = 3:4.' },
    { id:'6me3_020', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🟰 Qual razão é equivalente a 5:4?',
      opts:['10:8','8:10','5:8','4:5'], ans:0,
      exp:'Multiplicando os dois termos por 2: 5:4 = 10:8.' },
    { id:'6me3_021', s:'matematica', t:'Razões', type:'fill', diff:2,
      q:'Completa a igualdade de razões: 3:4 = 9:___.',
      ans:['12'], exp:'3×3 = 9, logo 4×3 = 12. Razão 9:12.' },
    { id:'6me3_022', s:'matematica', t:'Razões', type:'fill', diff:2,
      q:'Completa: 2:7 = ___:21.',
      ans:['6'], exp:'7×3 = 21, logo 2×3 = 6. Razão 6:21.' },
    { id:'6me3_023', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🧁 Receita: 2 chávenas de farinha para 1 de açúcar. Para 6 de farinha, quantas de açúcar (mesma razão)?',
      opts:['2','3','4','6'], ans:1,
      exp:'6 é o triplo de 2, logo o açúcar também triplica: 1×3 = 3.' },
    { id:'6me3_024', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'⚖️ A razão entre 250 g e 1 kg, na forma mais simples, é... (1 kg = 1000 g)',
      opts:['1:4','4:1','250:1','1:250'], ans:0,
      exp:'250:1000 = 1:4 (dividindo por 250). Converte sempre para a mesma unidade.' },
    { id:'6me3_025', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'📊 Qual é maior: a razão 3:4 ou a razão 5:8?',
      opts:['3:4','5:8','são iguais','não dá para saber'], ans:0,
      exp:'3:4 = 0,75 e 5:8 = 0,625. Logo 3:4 é maior.' },
    { id:'6me3_026', s:'matematica', t:'Razões', type:'tf', diff:2,
      q:'A razão 4:6 é maior do que a razão 1:2.',
      ans:true, exp:'Verdadeiro. 4:6 ≈ 0,67 e 1:2 = 0,5.' },
    { id:'6me3_027', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🚗 Um carro percorre 240 km em 3 horas. A razão distância:tempo (velocidade média) é...',
      opts:['60 km/h','80 km/h','720 km/h','120 km/h'], ans:1,
      exp:'240 km ÷ 3 h = 80 km/h. É uma razão entre grandezas de espécies diferentes.' },
    { id:'6me3_028', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'👧 A razão entre 15 raparigas e 10 rapazes, simplificada, é...',
      opts:['3:2','2:3','5:2','15:10'], ans:0,
      exp:'15:10 dividido por 5 = 3:2.' },
    { id:'6me3_029', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'❌ Qual destas NÃO é equivalente a 2:3?',
      opts:['4:6','6:9','8:12','3:2'], ans:3,
      exp:'3:2 é a razão invertida — não é equivalente a 2:3.' },
    { id:'6me3_030', s:'matematica', t:'Razões', type:'fill', diff:2,
      q:'Escreve a forma irredutível de 24:36 (forma a:b).',
      ans:['2:3','2 : 3'], exp:'24:36 dividido por 12 = 2:3.' },
    { id:'6me3_031', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🎨 Mistura-se tinta: 3 partes de azul para 2 de amarelo. A razão azul:total é...',
      opts:['3:2','3:5','2:5','5:3'], ans:1,
      exp:'Total = 3+2 = 5 partes. Azul:total = 3:5.' },
    { id:'6me3_032', s:'matematica', t:'Razões', type:'tf', diff:2,
      q:'As razões 9:12 e 3:4 representam a mesma comparação.',
      ans:true, exp:'Verdadeiro. 9:12 dividido por 3 = 3:4.' },
    { id:'6me3_033', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🔢 O número 0,5 escrito como razão na forma mais simples é...',
      opts:['1:2','2:1','5:1','1:5'], ans:0,
      exp:'0,5 = 5:10 = 1:2.' },
    { id:'6me3_034', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'📈 A razão 1:4 corresponde a que percentagem?',
      opts:['14%','25%','40%','4%'], ans:1,
      exp:'1:4 = 1/4 = 0,25 = 25%.' },
    { id:'6me3_035', s:'matematica', t:'Razões', type:'fill', diff:2,
      q:'3 está para 5 assim como 12 está para ___.',
      ans:['20'], exp:'3×4 = 12, logo 5×4 = 20.' },
    { id:'6me3_036', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🔴 Numa caixa há 8 bolas vermelhas e 12 azuis. A razão vermelhas:azuis simplificada é...',
      opts:['2:3','3:2','8:12','4:6'], ans:0,
      exp:'8:12 dividido por 4 = 2:3.' },
    { id:'6me3_037', s:'matematica', t:'Razões', type:'mc', diff:2,
      q:'🏙️ A densidade populacional é a razão entre...',
      opts:['população e área','área e população','população e tempo','área e tempo'], ans:0,
      exp:'Densidade populacional = população ÷ área (habitantes por km²).' },
    { id:'6me3_038', s:'matematica', t:'Razões', type:'fill', diff:2,
      q:'Completa: 4:5 = 16:___.',
      ans:['20'], exp:'4×4 = 16, logo 5×4 = 20.' },

    // ---- diff 3: repartir, escalas, problemas ----
    { id:'6me3_039', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'📐 A razão entre dois ângulos é 2:3 e a soma é 90°. O menor ângulo mede...',
      opts:['18°','36°','54°','45°'], ans:1,
      exp:'2+3 = 5 partes; 90÷5 = 18°. Menor = 2×18 = 36°.' },
    { id:'6me3_040', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'💶 Reparte 30 € na razão 2:3. As parcelas são...',
      opts:['10 € e 20 €','12 € e 18 €','15 € e 15 €','6 € e 24 €'], ans:1,
      exp:'2+3 = 5 partes; 30÷5 = 6. Parcelas: 2×6 = 12 € e 3×6 = 18 €.' },
    { id:'6me3_041', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'👧👦 A razão entre as idades de Ana e Rui é 4:5. Se Rui tem 20 anos, Ana tem...',
      opts:['16 anos','15 anos','25 anos','24 anos'], ans:0,
      exp:'4:5 = x:20 → cada parte vale 20÷5 = 4; Ana = 4×4 = 16 anos.' },
    { id:'6me3_042', s:'matematica', t:'Razões', type:'fill', diff:3,
      q:'Reparte 35 rebuçados na razão 3:4. A parte maior tem ___ rebuçados.',
      ans:['20'], exp:'3+4 = 7 partes; 35÷7 = 5. Maior = 4×5 = 20.' },
    { id:'6me3_043', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'🟰 Em razões equivalentes: 2:3 = x:18. Quanto vale x?',
      opts:['9','12','6','15'], ans:1,
      exp:'3×6 = 18, logo x = 2×6 = 12.' },
    { id:'6me3_044', s:'matematica', t:'Razões', type:'tf', diff:3,
      q:'A razão 5:2 pode ser simplificada.',
      ans:false, exp:'Falso. 5 e 2 não têm divisor comum (além de 1): já é irredutível.' },
    { id:'6me3_045', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'🗺️ Numa escala 1:50 000, 1 cm no mapa representa, na realidade...',
      opts:['50 km','5 km','0,5 km','50 m'], ans:2,
      exp:'1 cm × 50 000 = 50 000 cm = 500 m = 0,5 km.' },
    { id:'6me3_046', s:'matematica', t:'Razões', type:'fill', diff:3,
      q:'Sumo : água = 1:4. Para 200 ml de sumo, a quantidade de água é ___ ml.',
      ans:['800'], exp:'A água é o quádruplo do sumo: 4×200 = 800 ml.' },
    { id:'6me3_047', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'⏱️ A razão entre 1 hora e 15 minutos (na mesma unidade) é...',
      opts:['1:15','4:1','1:4','60:15'], ans:1,
      exp:'1 hora = 60 min. 60:15 = 4:1 (dividindo por 15).' },
    { id:'6me3_048', s:'matematica', t:'Razões', type:'mc', diff:3,
      q:'🟰 Como 4:5 = 16:20, dizemos que as duas razões são...',
      opts:['inversas','equivalentes','opostas','irredutíveis'], ans:1,
      exp:'Representam a mesma comparação → são razões equivalentes.' }

];
if (typeof window !== 'undefined') window.EXERCISES_6_M_EXTRA3 = EXERCISES_6_M_EXTRA3;
