// EscolaPlay - Top-up 6.º ano - Ciências Naturais (Uau! Vida 6 — Parte 2, Areal)
// 50 exercícios para o 3.º período: Tema 4 (As plantas e o meio) + Tema 5 (Reprodução das plantas com semente).
// Mapeamento de tópicos da app:
//   Tema 4 -> "As plantas e o meio"
//   Tema 5 -> "Reprodução das plantas com semente"
const EXERCISES_6_C_EXTRA3 = [

    // ============================================================
    // TEMA 4 — AS PLANTAS E O MEIO  (t: As plantas e o meio)
    // ============================================================

    // --- Lição 1.1 Fotossíntese ---
    { id:"t4-1.1-01", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"Na fotossíntese, as plantas produzem...",
      opts:["Glicose e dióxido de carbono","Oxigénio e água","Glicose e oxigénio","Glicose e água"], ans:2,
      exp:"A fotossíntese converte dióxido de carbono + água em glicose + oxigénio, usando a energia luminosa captada pela clorofila." },
    { id:"t4-1.1-02", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Na fotossíntese, as plantas consomem...",
      opts:["Dióxido de carbono e água","Oxigénio e água","Glicose e dióxido de carbono","Glicose e oxigénio"], ans:0,
      exp:"As plantas absorvem água pelas raízes e dióxido de carbono do ar (pelos estomas das folhas). São estes os reagentes da fotossíntese." },
    { id:"t4-1.1-03", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:1,
      q:"A fotossíntese ocorre em organitos celulares chamados...",
      opts:["mitocôndrias","núcleos","cloroplastos","vacúolos"], ans:2,
      exp:"Os cloroplastos contêm clorofila — o pigmento verde que capta a energia luminosa necessária à fotossíntese." },
    { id:"t4-1.1-04", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:1,
      q:"A clorofila é o pigmento responsável pela captação da luz na fotossíntese.",
      ans:true,
      exp:"Correto. A clorofila dá a cor verde às folhas e absorve a energia luminosa que vai impulsionar a reação da fotossíntese." },
    { id:"t4-1.1-05", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:1,
      q:"A fotossíntese transforma dióxido de carbono e água em glicose e ___.",
      ans:["oxigénio","oxigenio"],
      exp:"O oxigénio libertado pela fotossíntese é o gás que animais e plantas usam depois na respiração celular." },
    { id:"t4-1.1-06", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:1,
      q:"A substância das folhas que dá a cor verde e capta a luz solar chama-se ___.",
      ans:["clorofila"],
      exp:"A clorofila está dentro dos cloroplastos. Quando uma folha tem pouca clorofila (folha amarela ou variegada), a fotossíntese é menor." },
    { id:"t4-1.1-07", s:"ciencias", t:"As plantas e o meio", type:"match", diff:2,
      q:"Associa cada elemento ao seu papel na fotossíntese.",
      pairs:[["Dióxido de carbono","Reagente — entra pelos estomas"],["Água","Reagente — absorvido pelas raízes"],["Glicose","Produto — usado como alimento pela planta"],["Oxigénio","Produto — libertado para a atmosfera"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Reagentes (entram): CO₂ + água. Produtos (saem): glicose + O₂. A energia vem da luz, captada pela clorofila." },

    // --- Lição 1.2 Respiração celular e fatores limitantes ---
    { id:"t4-1.2-01", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Na respiração celular, as células consomem...",
      opts:["Dióxido de carbono e água","Oxigénio e glicose","Glicose e dióxido de carbono","Oxigénio e água"], ans:1,
      exp:"A respiração celular consome oxigénio e glicose, libertando energia, dióxido de carbono e água. É o inverso da fotossíntese." },
    { id:"t4-1.2-02", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"A respiração celular nas plantas...",
      opts:["ocorre apenas durante o dia","ocorre apenas nas folhas verdes","ocorre em todas as células, de dia e de noite","só ocorre quando a planta tem flores"], ans:2,
      exp:"Todas as células vivas respiram, em qualquer altura do dia. Já a fotossíntese só ocorre nas células com clorofila e quando há luz." },
    { id:"t4-1.2-03", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Quando as temperaturas são muito elevadas, a taxa de fotossíntese...",
      opts:["aumenta sem limite","diminui","mantém-se inalterada","é igual a zero"], ans:1,
      exp:"Temperaturas muito altas desnaturam as enzimas envolvidas na fotossíntese, fazendo descer a sua taxa. Temperaturas demasiado baixas também a reduzem." },
    { id:"t4-1.2-04", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:3,
      q:"Quanto maior for a intensidade luminosa, maior será sempre a taxa de fotossíntese.",
      ans:false,
      exp:"Falso. A taxa aumenta com a luz, mas só até um certo ponto. A partir daí estabiliza, porque outros fatores (água, CO₂, temperatura) passam a limitar." },
    { id:"t4-1.2-05", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:2,
      q:"A reação celular em que se consome glicose e oxigénio para libertar energia chama-se ___ celular.",
      ans:["respiração","respiracao"],
      exp:"A respiração celular liberta a energia armazenada na glicose — energia que a planta usa para crescer, transportar substâncias e produzir novas estruturas." },
    { id:"t4-1.2-06", s:"ciencias", t:"As plantas e o meio", type:"match", diff:2,
      q:"Associa cada fator ambiental ao seu efeito na fotossíntese.",
      pairs:[["Pouca luz","Taxa de fotossíntese baixa"],["Temperatura muito alta","Enzimas desnaturam — taxa cai"],["Falta de água","Estomas fecham — entra menos CO₂"],["Mais CO₂ disponível","Taxa aumenta (até certo ponto)"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Luz, temperatura, água e CO₂ são os principais fatores limitantes da fotossíntese." },

    // --- Lição 1.3 Importância das plantas e florestas autóctones ---
    { id:"t4-1.3-01", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Fazem parte da floresta autóctone portuguesa...",
      opts:["eucaliptos e sobreiros","sobreiros e azinheiras","eucaliptos e carvalhos","azinheiras e eucaliptos"], ans:1,
      exp:"Sobreiro, azinheira, carvalho e pinheiro-bravo são típicos da floresta portuguesa. O eucalipto é introduzido (não é autóctone)." },
    { id:"t4-1.3-02", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"São exemplos de espécies invasoras presentes em Portugal...",
      opts:["carvalho e sobreiro","azinheira e pinheiro-manso","eucalipto e acácia","sobreiro e pinheiro-bravo"], ans:2,
      exp:"Eucalipto e acácia foram introduzidos pelo Homem e expandiram-se rapidamente, prejudicando as espécies autóctones." },
    { id:"t4-1.3-03", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"São exemplos de objetos que têm plantas como matéria-prima...",
      opts:["sacos de plástico e medicamentos","sacos de plástico e cestos de vinho","rolhas de cortiça e medicamentos","rolhas de cortiça e pneus de automóveis"], ans:2,
      exp:"A cortiça vem do sobreiro e muitos medicamentos têm origem em plantas. Plásticos e pneus vêm do petróleo, não de plantas." },
    { id:"t4-1.3-04", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:1,
      q:"O eucalipto é uma espécie autóctone portuguesa.",
      ans:false,
      exp:"Falso. O eucalipto foi introduzido em Portugal vindo da Austrália. Espalhou-se muito e considera-se uma espécie invasora." },
    { id:"t4-1.3-05", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:1,
      q:"As florestas ajudam a regular a humidade do ar e o clima.",
      ans:true,
      exp:"Correto. As plantas libertam vapor de água (transpiração) e sombra; em conjunto, as florestas amenizam temperaturas e mantêm a humidade." },
    { id:"t4-1.3-06", s:"ciencias", t:"As plantas e o meio", type:"match", diff:2,
      q:"Associa cada produto à planta de onde provém.",
      pairs:[["Cortiça","Sobreiro"],["Bolota","Azinheira / Carvalho"],["Pinhão","Pinheiro-manso"],["Madeira","Pinheiro / Eucalipto"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Cada espécie tem aproveitamentos diferentes. A cortiça do sobreiro é uma das principais matérias-primas portuguesas." },

    // --- Lição 1.4 Revisão Tema 4 ---
    { id:"t4-1.4-01", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:3,
      q:"Os órgãos de reserva das plantas...",
      opts:["são apenas importantes para a alimentação do ser humano","são apenas frutos e caules","são utilizados pela planta para guardar reservas e sobreviver, por exemplo, no inverno","apresentam sempre estomas"], ans:2,
      exp:"Os órgãos de reserva (tubérculos, bolbos, raízes tuberosas) guardam alimento para a planta passar épocas difíceis ou recomeçar o crescimento." },
    { id:"t4-1.4-02", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"As principais causas da destruição das florestas são...",
      opts:["desflorestação e incêndios","desflorestação e preservação de incêndios","plantação de árvores e limpeza das florestas","combate à poluição e preservação de árvores"], ans:0,
      exp:"Desflorestação (corte sem reposição) e incêndios são as grandes ameaças. A reflorestação e a limpeza dos matos são medidas de proteção." },
    { id:"t4-1.4-03", s:"ciencias", t:"As plantas e o meio", type:"mc", diff:2,
      q:"Uma das medidas que protege a floresta é...",
      opts:["a desflorestação","a sua limpeza","provocar incêndios controlados sem regras","o abate de árvores autóctones"], ans:1,
      exp:"A limpeza das florestas (matos secos, ramos) reduz o risco de propagação de incêndios. A reflorestação e a vigilância também ajudam." },
    { id:"t4-1.4-04", s:"ciencias", t:"As plantas e o meio", type:"tf", diff:2,
      q:"As plantas são seres autotróficos porque produzem o seu próprio alimento.",
      ans:true,
      exp:"Correto. Autotrófico significa que produz o próprio alimento (glicose) através da fotossíntese. Os animais são heterotróficos." },
    { id:"t4-1.4-05", s:"ciencias", t:"As plantas e o meio", type:"fill", diff:2,
      q:"A plantação de árvores em zonas desflorestadas chama-se ___.",
      ans:["reflorestação","reflorestacao"],
      exp:"A reflorestação devolve a cobertura vegetal a terrenos que perderam a floresta, ajudando a recuperar biodiversidade e a fixar o solo." },
    { id:"t4-1.4-06", s:"ciencias", t:"As plantas e o meio", type:"match", diff:2,
      q:"Associa cada termo à sua definição.",
      pairs:[["Autotrófico","Produz o próprio alimento"],["Heterotrófico","Alimenta-se de outros seres vivos"],["Espécie autóctone","Originária do território (ex.: sobreiro)"],["Espécie invasora","Introduzida e que prejudica as nativas"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Estes quatro conceitos são o vocabulário-chave do Tema 4." },

    // ============================================================
    // TEMA 5 — REPRODUÇÃO DAS PLANTAS COM SEMENTE  (t: Reprodução das plantas com semente)
    // ============================================================

    // --- Lição 2.1 A flor (peças florais) ---
    { id:"t5-2.1-01", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Uma flor completa é constituída por...",
      opts:["sépalas, pétalas, ovários e folhas","sépalas, pétalas, estames e carpelos","sementes, pétalas, estames e carpelos","sépalas, pedúnculo, pétalas e carpelos"], ans:1,
      exp:"A flor completa tem as 4 peças florais: sépalas (cálice), pétalas (corola), estames (androceu) e carpelos (gineceu)." },
    { id:"t5-2.1-02", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"O androceu e o gineceu de uma flor têm função...",
      opts:["de proteção","de suporte","reprodutora","fotossintética"], ans:2,
      exp:"Androceu (estames) e gineceu (carpelos) são as peças reprodutoras. Cálice e corola servem para proteção e atração de polinizadores." },
    { id:"t5-2.1-03", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Os grãos de pólen produzem-se...",
      opts:["nos estames (anteras)","nos carpelos (estigma)","nas sépalas","no pedúnculo"], ans:0,
      exp:"O pólen é produzido nas anteras dos estames — a parte masculina da flor. Cada estame tem filete + antera." },
    { id:"t5-2.1-04", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:2,
      q:"O ovário, o estilete e o estigma fazem parte do gineceu.",
      ans:true,
      exp:"Correto. O gineceu (parte feminina) inclui o estigma (recebe o pólen), o estilete (canal) e o ovário (com os óvulos)." },
    { id:"t5-2.1-05", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:1,
      q:"O conjunto das sépalas de uma flor chama-se ___.",
      ans:["cálice","calice"],
      exp:"O cálice protege a flor enquanto está em botão. As pétalas formam a corola, que atrai polinizadores." },
    { id:"t5-2.1-06", s:"ciencias", t:"Reprodução das plantas com semente", type:"match", diff:2,
      q:"Associa cada peça floral à sua função.",
      pairs:[["Sépalas","Protegem a flor antes de abrir"],["Pétalas","Atraem os polinizadores"],["Estames","Produzem pólen (parte masculina)"],["Carpelos","Contêm os óvulos (parte feminina)"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Cálice e corola são peças de proteção/atração; androceu e gineceu são as peças reprodutoras." },

    // --- Lição 2.2 Polinização e fecundação ---
    { id:"t5-2.2-01", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Se não ocorrer polinização, não ocorre...",
      opts:["a dispersão das sementes","a frutificação","a floração","a germinação"], ans:1,
      exp:"Sem polinização não há fecundação; sem fecundação, o ovário não se transforma em fruto (frutificação)." },
    { id:"t5-2.2-02", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:1,
      q:"Um exemplo de agente polinizador é...",
      opts:["o sol","a chuva","o vento","o solo"], ans:2,
      exp:"Os principais agentes polinizadores são o vento, a água e os animais (sobretudo insetos como abelhas e borboletas)." },
    { id:"t5-2.2-03", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:3,
      q:"A polinização cruzada acontece quando...",
      opts:["o pólen passa de uma flor para o estigma da mesma flor","o pólen passa de uma flor para outra flor da mesma planta","o pólen passa de uma flor para uma flor de outra planta da mesma espécie","o ovário se transforma em fruto"], ans:2,
      exp:"Polinização cruzada → entre plantas diferentes. Autopolinização (direta) → mesma flor ou mesma planta." },
    { id:"t5-2.2-04", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:2,
      q:"Na autopolinização, o pólen é transferido entre flores de plantas diferentes.",
      ans:false,
      exp:"Falso. Na autopolinização (polinização direta) o pólen vai para o estigma da MESMA flor ou de outra flor da mesma planta. Entre plantas diferentes chama-se polinização cruzada." },
    { id:"t5-2.2-05", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:2,
      q:"Depois de chegar ao estigma, o grão de pólen forma um tubo polínico até ao óvulo.",
      ans:true,
      exp:"Correto. O grão de pólen germina no estigma e cria o tubo polínico, que atravessa o estilete até ao óvulo para a fecundação." },
    { id:"t5-2.2-06", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:2,
      q:"A união do núcleo do grão de pólen com o núcleo do óvulo chama-se ___.",
      ans:["fecundação","fecundacao"],
      exp:"Da fecundação resulta o zigoto, que se desenvolve em embrião. O óvulo passa a semente e o ovário a fruto." },

    // --- Lição 2.3 Fruto, semente e dispersão ---
    { id:"t5-2.3-01", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:1,
      q:"Ao conjunto formado pelo embrião e pelas suas reservas alimentares chamamos...",
      opts:["ovo","semente","ovário","tubo polínico"], ans:1,
      exp:"A semente é formada por tegumento (proteção), embrião (nova planta) e reservas alimentares (cotilédones)." },
    { id:"t5-2.3-02", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"O processo de formação de um fruto denomina-se...",
      opts:["germinação","reprodução","dispersão","frutificação"], ans:3,
      exp:"Após a fecundação, o ovário transforma-se em fruto — este processo é a frutificação." },
    { id:"t5-2.3-03", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"O fruto é constituído por...",
      opts:["sementes e pericarpo","sementes e pedúnculo","sementes e estames","sementes e tubo polínico"], ans:0,
      exp:"O pericarpo é a parede do fruto (com epicarpo, mesocarpo e endocarpo) e envolve as sementes." },
    { id:"t5-2.3-04", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:1,
      q:"Depois da fecundação, o ovário transforma-se em fruto e os óvulos em sementes.",
      ans:true,
      exp:"Correto. Ovário → fruto; óvulos (já fecundados) → sementes. É a base de todo o ciclo reprodutor das plantas com flor." },
    { id:"t5-2.3-05", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:2,
      q:"A dispersão de sementes pelo vento chama-se ___.",
      ans:["anemocoria"],
      exp:"Anemo- = vento. Sementes leves com asas (ex.: bordo) ou pelos (ex.: dente-de-leão) são típicas da anemocoria." },
    { id:"t5-2.3-06", s:"ciencias", t:"Reprodução das plantas com semente", type:"fill", diff:2,
      q:"A dispersão de sementes pela água chama-se ___.",
      ans:["hidrocoria"],
      exp:"Hidro- = água. O coco é o exemplo clássico: flutua e pode ser levado pelo mar até a outra ilha antes de germinar." },
    { id:"t5-2.3-07", s:"ciencias", t:"Reprodução das plantas com semente", type:"match", diff:2,
      q:"Associa cada tipo de dispersão ao seu agente e a um exemplo.",
      pairs:[["Anemocoria","Vento — ex.: dente-de-leão"],["Hidrocoria","Água — ex.: coco"],["Zoocoria","Animais — ex.: cerejas comidas por aves"],["Autocoria","A própria planta — ex.: ervilha que rebenta a vagem"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"A dispersão permite que as sementes germinem longe da planta-mãe, reduzindo a competição por luz, água e nutrientes." },

    // --- Lição 2.4 Germinação ---
    { id:"t5-2.4-01", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"Numa planta, o primeiro órgão a desenvolver-se a partir da semente é...",
      opts:["o caulículo","a gémula","as folhas","a radícula"], ans:3,
      exp:"A radícula sai primeiro: fixa a planta ao solo e absorve água. Só depois se desenvolvem o caulículo (caule jovem) e a gémula (folhas)." },
    { id:"t5-2.4-02", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:2,
      q:"As reservas alimentares de que o embrião se alimenta durante a germinação encontram-se...",
      opts:["no tegumento","nos cotilédones","na radícula","no pedúnculo"], ans:1,
      exp:"Os cotilédones guardam as reservas. Quando a planta jovem produzir as primeiras folhas verdes, passa a alimentar-se por fotossíntese." },
    { id:"t5-2.4-03", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:1,
      q:"Para germinar, uma semente precisa de...",
      opts:["ausência total de água","temperaturas muito baixas","água, oxigénio e temperatura adequada","luz solar direta obrigatória"], ans:2,
      exp:"Condições favoráveis: água, oxigénio e temperatura adequada. A luz só é necessária em algumas espécies; muitas sementes germinam no escuro." },
    { id:"t5-2.4-04", s:"ciencias", t:"Reprodução das plantas com semente", type:"tf", diff:1,
      q:"Todas as sementes precisam de luz para germinar.",
      ans:false,
      exp:"Falso. Muitas sementes germinam às escuras (debaixo da terra). A luz é necessária para a fotossíntese depois das primeiras folhas aparecerem, não para iniciar a germinação." },

    // --- Lição 2.5 Revisão Tema 5 ---
    { id:"t5-2.5-01", s:"ciencias", t:"Reprodução das plantas com semente", type:"mc", diff:3,
      q:"Uma planta com flor reproduz-se de forma...",
      opts:["sexuada, envolvendo células femininas e masculinas","assexuada, envolvendo um esporângio","assexuada, envolvendo células femininas e um óvulo","sexuada, envolvendo um espermatozoide e um oócito"], ans:0,
      exp:"Plantas com flor reproduzem-se sexuadamente: o gâmeta masculino (no grão de pólen) une-se com o gâmeta feminino (no óvulo)." },
    { id:"t5-2.5-02", s:"ciencias", t:"Reprodução das plantas com semente", type:"match", diff:2,
      q:"Associa cada termo à sua definição.",
      pairs:[["Polinização","Transferência do pólen das anteras para o estigma"],["Fecundação","União do pólen com o óvulo"],["Frutificação","Transformação do ovário em fruto"],["Germinação","Desenvolvimento do embrião numa nova planta"]],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:"Estas 4 etapas formam o ciclo de vida das plantas com flor: polinização → fecundação → frutificação → dispersão → germinação." }

];
if (typeof window !== 'undefined') window.EXERCISES_6_C_EXTRA3 = EXERCISES_6_C_EXTRA3;
