// EscolaPlay - Banco extra do 6.º ano - HGP (gerado, AE 2018)
const EXERCISES_6_H_EXTRA = [
    // ============================================================
    // EXPANSÃO MARÍTIMA (séc. XV-XVI) - 50
    // ============================================================
    { id:'6he1', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'⛵ Em que ano os portugueses chegaram à Índia?',
      opts:['1492','1498','1500','1519'], ans:1,
      exp:'Vasco da Gama chegou a Calecute, na Índia, em 1498.' },
    { id:'6he2', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'🌍 Que cidade do Norte de África foi conquistada em 1415?',
      opts:['Tânger','Ceuta','Arzila','Mazagão'], ans:1,
      exp:'A conquista de Ceuta (1415) marca o início da Expansão.' },
    { id:'6he3', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'👑 Que rei reinava aquando da conquista de Ceuta?',
      opts:['D. João I','D. Manuel I','D. Afonso V','D. João II'], ans:0,
      exp:'D. João I, fundador da Dinastia de Avis, conquistou Ceuta em 1415.' },
    { id:'6he4', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'⛵ Quem é considerado o grande impulsionador das navegações?',
      opts:['D. Pedro','Infante D. Henrique','D. Duarte','D. Afonso V'], ans:1,
      exp:'O Infante D. Henrique impulsionou a Escola de Sagres e as navegações africanas.' },
    { id:'6he5', s:'hgp', t:'Expansão Marítima', type:'fill', diff:1,
      q:'🏝️ A ilha da ___ foi descoberta em 1419.',
      ans:['Madeira','madeira'],
      exp:'A Madeira foi descoberta em 1419 por João Gonçalves Zarco e Tristão Vaz Teixeira.' },
    { id:'6he6', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🏝️ Em que ano foi descoberto o arquipélago dos Açores?',
      opts:['1415','1419','1427','1434'], ans:2,
      exp:'Os Açores foram descobertos em 1427 (atribuído a Diogo de Silves).' },
    { id:'6he7', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🌊 Quem dobrou o Cabo da Boa Esperança em 1488?',
      opts:['Vasco da Gama','Bartolomeu Dias','Pedro Álvares Cabral','Fernão de Magalhães'], ans:1,
      exp:'Bartolomeu Dias dobrou o Cabo da Boa Esperança em 1488, abrindo caminho para a Índia.' },
    { id:'6he8', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'🇧🇷 Quem chegou ao Brasil em 1500?',
      opts:['Vasco da Gama','Pedro Álvares Cabral','Bartolomeu Dias','Diogo Cão'], ans:1,
      exp:'Pedro Álvares Cabral chegou ao Brasil a 22 de abril de 1500.' },
    { id:'6he9', s:'hgp', t:'Expansão Marítima', type:'fill', diff:1,
      q:'🌍 Em 1494, Portugal e Castela assinaram o Tratado de ___.',
      ans:['Tordesilhas','tordesilhas'],
      exp:'O Tratado de Tordesilhas (1494) dividiu o mundo entre Portugal e Castela.' },
    { id:'6he10', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⛵ Quem foi o primeiro navegador da viagem de circum-navegação (1519-1522)?',
      opts:['Vasco da Gama','Fernão de Magalhães','Sebastião Elcano','Diogo Cão'], ans:1,
      exp:'Fernão de Magalhães iniciou a viagem; após a sua morte, Sebastião Elcano completou-a.' },
    { id:'6he11', s:'hgp', t:'Expansão Marítima', type:'tf', diff:1,
      q:'⛵ Vasco da Gama chegou à Índia em 1498.',
      ans:true,
      exp:'Verdadeiro. Vasco da Gama desembarcou em Calecute em 1498.' },
    { id:'6he12', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'👑 Que rei era cognominado "o Venturoso"?',
      opts:['D. João II','D. Manuel I','D. Afonso V','D. João III'], ans:1,
      exp:'D. Manuel I foi chamado "o Venturoso" por ter reinado durante grandes descobertas.' },
    { id:'6he13', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'👑 Que rei era cognominado "Príncipe Perfeito"?',
      opts:['D. João I','D. João II','D. Manuel I','D. Sebastião'], ans:1,
      exp:'D. João II foi chamado "Príncipe Perfeito" pela sua governação firme.' },
    { id:'6he14', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'🏛️ Onde se situava a famosa Escola atribuída ao Infante D. Henrique?',
      opts:['Lisboa','Sagres','Porto','Lagos'], ans:1,
      exp:'A "Escola de Sagres" (Algarve) reuniu cartógrafos, astrónomos e marinheiros.' },
    { id:'6he15', s:'hgp', t:'Expansão Marítima', type:'fill', diff:2,
      q:'🌊 ___ chegou à foz do rio Congo em 1482.',
      ans:['Diogo Cão','diogo cão','Diogo Cao'],
      exp:'Diogo Cão alcançou a foz do rio Zaire (Congo) em 1482.' },
    { id:'6he16', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⛵ Que tipo de embarcação leve foi muito usado nas descobertas?',
      opts:['galera','caravela','trirreme','fragata'], ans:1,
      exp:'A caravela, ágil e adequada à navegação atlântica, foi essencial na Expansão.' },
    { id:'6he17', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🧭 Que instrumento permitia medir a altura dos astros?',
      opts:['bússola','astrolábio','quadrante','sextante moderno'], ans:1,
      exp:'O astrolábio media a altura do sol e estrelas para calcular a latitude.' },
    { id:'6he18', s:'hgp', t:'Expansão Marítima', type:'tf', diff:1,
      q:'🌍 O Tratado de Tordesilhas foi assinado entre Portugal e França.',
      ans:false,
      exp:'Falso. Foi assinado entre Portugal e Castela (Espanha).' },
    { id:'6he19', s:'hgp', t:'Expansão Marítima', type:'order', diff:2,
      q:'Ordena cronologicamente os acontecimentos:',
      items:['Conquista de Ceuta','Descoberta da Madeira','Cabo da Boa Esperança','Chegada à Índia'],
      ans:'1,2,3,4',
      exp:'1415 Ceuta → 1419 Madeira → 1488 Boa Esperança → 1498 Índia.' },
    { id:'6he20', s:'hgp', t:'Expansão Marítima', type:'order', diff:3,
      q:'Ordena cronologicamente:',
      items:['Descoberta dos Açores','Tratado de Tordesilhas','Chegada ao Brasil','Circum-navegação'],
      ans:'1,2,3,4',
      exp:'1427 Açores → 1494 Tordesilhas → 1500 Brasil → 1519-22 circum-navegação.' },
    { id:'6he21', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🇧🇷 Em que armada seguia Pedro Álvares Cabral quando chegou ao Brasil?',
      opts:['armada para Ceuta','armada para a Índia','armada para Açores','armada para o Congo'], ans:1,
      exp:'Cabral comandava uma armada com destino à Índia quando chegou ao Brasil em 1500.' },
    { id:'6he22', s:'hgp', t:'Expansão Marítima', type:'fill', diff:1,
      q:'🌍 Vasco da Gama chegou à cidade de ___ , na Índia.',
      ans:['Calecute','calecute'],
      exp:'Calecute (atual Kozhikode), no Índico, foi onde Vasco da Gama desembarcou.' },
    { id:'6he23', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'🌶️ Que produto valioso era principal motivo do comércio com a Índia?',
      opts:['ouro','especiarias','seda','marfim'], ans:1,
      exp:'As especiarias (pimenta, cravo, canela) eram muito valiosas na Europa.' },
    { id:'6he24', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⚔️ Que feitoria portuguesa foi construída em 1482 na costa da Guiné?',
      opts:['Mina (São Jorge)','Goa','Macau','Ormuz'], ans:0,
      exp:'A fortaleza de São Jorge da Mina foi construída em 1482, no atual Gana.' },
    { id:'6he25', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'⛵ Quem comandava a armada que partiu de Lisboa para a Índia em 1497?',
      opts:['Bartolomeu Dias','Vasco da Gama','Pedro Álvares Cabral','Diogo Cão'], ans:1,
      exp:'Vasco da Gama partiu em julho de 1497 e chegou em maio de 1498.' },
    { id:'6he26', s:'hgp', t:'Expansão Marítima', type:'tf', diff:2,
      q:'🌍 A primeira viagem de circum-navegação demonstrou que a Terra é redonda.',
      ans:true,
      exp:'A viagem de Magalhães-Elcano (1519-1522) provou na prática a esfericidade da Terra.' },
    { id:'6he27', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🌍 Em que continente fica Calecute?',
      opts:['África','Ásia','América','Oceânia'], ans:1,
      exp:'Calecute fica na Ásia, na atual Índia.' },
    { id:'6he28', s:'hgp', t:'Expansão Marítima', type:'fill', diff:2,
      q:'⛵ Em 1488, Bartolomeu Dias dobrou o Cabo da ___ Esperança.',
      ans:['Boa','boa'],
      exp:'O Cabo da Boa Esperança fica no extremo sul de África.' },
    { id:'6he29', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⛵ Quem deu o nome de "Vera Cruz" à terra descoberta em 1500?',
      opts:['Vasco da Gama','Pedro Álvares Cabral','D. Manuel I','Bartolomeu Dias'], ans:1,
      exp:'Cabral chamou Terra de Vera Cruz; mais tarde passou a chamar-se Brasil.' },
    { id:'6he30', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'⚔️ Quem foi o 1.º Vice-Rei da Índia portuguesa (1505)?',
      opts:['Afonso de Albuquerque','D. Francisco de Almeida','Vasco da Gama','D. João de Castro'], ans:1,
      exp:'D. Francisco de Almeida foi nomeado primeiro Vice-Rei da Índia em 1505.' },
    { id:'6he31', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'⚔️ Quem conquistou Goa, Malaca e Ormuz para Portugal?',
      opts:['Vasco da Gama','Afonso de Albuquerque','D. João de Castro','Bartolomeu Dias'], ans:1,
      exp:'Afonso de Albuquerque conquistou Goa (1510), Malaca (1511) e Ormuz (1515).' },
    { id:'6he32', s:'hgp', t:'Expansão Marítima', type:'match', diff:3,
      q:'Associa cada navegador ao seu feito:',
      pairs:[['Bartolomeu Dias','Cabo da Boa Esperança'],['Vasco da Gama','Chegada à Índia'],['Pedro Álvares Cabral','Chegada ao Brasil'],['Fernão de Magalhães','Início da circum-navegação']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Cada navegador é lembrado pelo seu grande feito.' },
    { id:'6he33', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'⛵ De onde partiu Vasco da Gama para a Índia?',
      opts:['Porto','Lisboa (Restelo)','Lagos','Sagres'], ans:1,
      exp:'A armada partiu do Restelo, em Lisboa, em julho de 1497.' },
    { id:'6he34', s:'hgp', t:'Expansão Marítima', type:'tf', diff:1,
      q:'👑 D. Manuel I mandou construir o Mosteiro dos Jerónimos.',
      ans:true,
      exp:'O Mosteiro dos Jerónimos celebra a chegada de Vasco da Gama à Índia.' },
    { id:'6he35', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🏛️ Que estilo arquitetónico floresceu no reinado de D. Manuel I?',
      opts:['Românico','Gótico','Manuelino','Barroco'], ans:2,
      exp:'O estilo Manuelino, com motivos marítimos, é típico desta época.' },
    { id:'6he36', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'🌍 Que mar Vasco da Gama atravessou para chegar à Índia?',
      opts:['Mar Mediterrâneo','Mar Vermelho','Mar Arábico','Mar Negro'], ans:2,
      exp:'O Mar Arábico (parte do Índico) foi atravessado a caminho de Calecute.' },
    { id:'6he37', s:'hgp', t:'Expansão Marítima', type:'fill', diff:2,
      q:'🌍 ___ foi o navegador que iniciou a viagem da circum-navegação em 1519.',
      ans:['Fernão de Magalhães','Magalhães','Fernao de Magalhaes'],
      exp:'Fernão de Magalhães partiu em 1519, ao serviço de Espanha.' },
    { id:'6he38', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⛵ Onde morreu Fernão de Magalhães em 1521?',
      opts:['nas Filipinas','no Brasil','no Cabo Verde','na Índia'], ans:0,
      exp:'Magalhães morreu nas Filipinas; Sebastião Elcano completou a viagem.' },
    { id:'6he39', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'🌍 Qual foi o primeiro continente que os portugueses exploraram?',
      opts:['América','África','Ásia','Oceânia'], ans:1,
      exp:'Os portugueses exploraram primeiro a costa de África (séc. XV).' },
    { id:'6he40', s:'hgp', t:'Expansão Marítima', type:'tf', diff:2,
      q:'🇧🇷 O Brasil foi a primeira terra descoberta por Portugal.',
      ans:false,
      exp:'Falso. Antes do Brasil já tinham sido descobertos vários territórios africanos e ilhas atlânticas.' },
    { id:'6he41', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'🧭 A bússola serve para indicar...',
      opts:['a hora','a direção','a profundidade','o vento'], ans:1,
      exp:'A bússola indica a direção (norte magnético).' },
    { id:'6he42', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'⛵ Que poeta escreveu "Os Lusíadas" sobre a viagem de Vasco da Gama?',
      opts:['Fernando Pessoa','Luís de Camões','Gil Vicente','Almeida Garrett'], ans:1,
      exp:'Luís de Camões publicou "Os Lusíadas" em 1572, celebrando os feitos portugueses.' },
    { id:'6he43', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⛪ A obrigatoriedade de cristianizar foi uma das motivações da Expansão. Verdadeiro?',
      opts:['Sim, motivo religioso','Não, só motivo económico','Não, só motivo militar','Não, só curiosidade'], ans:0,
      exp:'A propagação da fé cristã foi uma das motivações importantes.' },
    { id:'6he44', s:'hgp', t:'Expansão Marítima', type:'fill', diff:2,
      q:'🏝️ As ilhas da Madeira e dos ___ foram colonizadas no séc. XV.',
      ans:['Açores','acores','Acores'],
      exp:'A Madeira (1419) e os Açores (1427) foram povoadas por colonos portugueses.' },
    { id:'6he45', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'⚔️ Em que ano foi conquistada Goa por Afonso de Albuquerque?',
      opts:['1498','1500','1510','1515'], ans:2,
      exp:'Goa foi conquistada em 1510 e tornou-se capital do Estado da Índia.' },
    { id:'6he46', s:'hgp', t:'Expansão Marítima', type:'tf', diff:2,
      q:'🌶️ As especiarias eram usadas para conservar e dar sabor aos alimentos.',
      ans:true,
      exp:'Verdadeiro. Eram muito procuradas porque ajudavam a conservar carnes e dar sabor.' },
    { id:'6he47', s:'hgp', t:'Expansão Marítima', type:'mc', diff:1,
      q:'🇵🇹 A Dinastia que iniciou a Expansão Marítima foi a:',
      opts:['Borgonha','Avis','Bragança','Filipina'], ans:1,
      exp:'A Dinastia de Avis (D. João I a D. Henrique) iniciou e desenvolveu a Expansão.' },
    { id:'6he48', s:'hgp', t:'Expansão Marítima', type:'mc', diff:2,
      q:'⛵ Que ano marca o "início" simbólico da Expansão Portuguesa?',
      opts:['1385','1415','1488','1500'], ans:1,
      exp:'1415, com a conquista de Ceuta, é considerado o início da Expansão.' },
    { id:'6he49', s:'hgp', t:'Expansão Marítima', type:'order', diff:3,
      q:'Ordena os reis cronologicamente:',
      items:['D. João I','D. Afonso V','D. João II','D. Manuel I'],
      ans:'1,2,3,4',
      exp:'D. João I (1385) → D. Afonso V → D. João II → D. Manuel I.' },
    { id:'6he50', s:'hgp', t:'Expansão Marítima', type:'mc', diff:3,
      q:'⛵ A Expansão Portuguesa permitiu o contacto com novos:',
      opts:['povos, plantas e animais','apenas povos','apenas plantas','apenas animais'], ans:0,
      exp:'A Expansão proporcionou o intercâmbio de povos, culturas, plantas e animais.' },

    // ============================================================
    // UNIÃO IBÉRICA (1580-1640) - 50
    // ============================================================
    { id:'6he51', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'⚔️ Onde desapareceu D. Sebastião em 1578?',
      opts:['Aljubarrota','Alcácer-Quibir','Toro','Ourique'], ans:1,
      exp:'D. Sebastião desapareceu na batalha de Alcácer-Quibir, em Marrocos.' },
    { id:'6he52', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'👑 Quem sucedeu a D. Sebastião?',
      opts:['Filipe II','Cardeal D. Henrique','D. António','D. João IV'], ans:1,
      exp:'O Cardeal D. Henrique (tio-avô de D. Sebastião) foi rei entre 1578 e 1580.' },
    { id:'6he53', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'🇪🇸 Que rei espanhol se tornou rei de Portugal em 1580?',
      opts:['Filipe I (II de Espanha)','Carlos V','Filipe IV','Fernando V'], ans:0,
      exp:'Filipe II de Espanha tornou-se Filipe I de Portugal em 1580.' },
    { id:'6he54', s:'hgp', t:'União Ibérica', type:'fill', diff:1,
      q:'🇪🇸 A União Ibérica durou ___ anos.',
      ans:['60','sessenta'],
      exp:'A União Ibérica durou 60 anos, de 1580 a 1640.' },
    { id:'6he55', s:'hgp', t:'União Ibérica', type:'tf', diff:1,
      q:'⚔️ A batalha de Alcácer-Quibir ocorreu em 1578.',
      ans:true,
      exp:'Verdadeiro. A batalha foi a 4 de agosto de 1578.' },
    { id:'6he56', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'👑 Quantos reis da dinastia Filipina governaram Portugal?',
      opts:['1','2','3','4'], ans:2,
      exp:'Foram 3: Filipe I, Filipe II e Filipe III de Portugal.' },
    { id:'6he57', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'📜 Em que Cortes Filipe II foi aclamado rei de Portugal?',
      opts:['Cortes de Lisboa','Cortes de Tomar (1581)','Cortes de Coimbra','Cortes de Évora'], ans:1,
      exp:'Filipe II foi aclamado nas Cortes de Tomar em 1581, jurando respeitar a autonomia portuguesa.' },
    { id:'6he58', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'🇵🇹 O sentimento de esperança no regresso de D. Sebastião chama-se:',
      opts:['saudosismo','sebastianismo','manuelismo','iberismo'], ans:1,
      exp:'O sebastianismo é a crença no regresso de D. Sebastião para salvar Portugal.' },
    { id:'6he59', s:'hgp', t:'União Ibérica', type:'fill', diff:2,
      q:'⚔️ A batalha onde D. Sebastião desapareceu chama-se Alcácer-___.',
      ans:['Quibir','quibir'],
      exp:'Alcácer-Quibir, em Marrocos, foi a batalha decisiva de 1578.' },
    { id:'6he60', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'🌍 Durante a União Ibérica, Portugal perdeu várias possessões. Quem ocupou parte do Brasil?',
      opts:['Franceses','Holandeses','Ingleses','Italianos'], ans:1,
      exp:'Os holandeses ocuparam parte do Brasil, sobretudo o Nordeste, durante a União Ibérica.' },
    { id:'6he61', s:'hgp', t:'União Ibérica', type:'tf', diff:2,
      q:'👑 Filipe II prometeu respeitar as leis e a autonomia portuguesa.',
      ans:true,
      exp:'Verdadeiro. Nas Cortes de Tomar (1581) Filipe II jurou respeitar a autonomia.' },
    { id:'6he62', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'⚔️ Quem se opôs a Filipe II como pretendente ao trono português?',
      opts:['D. António, Prior do Crato','D. João IV','D. Pedro II','D. Manuel II'], ans:0,
      exp:'D. António, Prior do Crato, foi o pretendente português, mas foi derrotado.' },
    { id:'6he63', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'📅 Em que ano teve início a União Ibérica?',
      opts:['1578','1580','1581','1640'], ans:1,
      exp:'A União Ibérica começou em 1580, com Filipe II a tornar-se rei de Portugal.' },
    { id:'6he64', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'📅 Em que ano terminou a União Ibérica?',
      opts:['1620','1640','1668','1700'], ans:1,
      exp:'A União Ibérica terminou em 1640, com a Restauração da Independência.' },
    { id:'6he65', s:'hgp', t:'União Ibérica', type:'order', diff:2,
      q:'Ordena cronologicamente:',
      items:['Alcácer-Quibir','Reinado do Cardeal D. Henrique','Cortes de Tomar','Restauração'],
      ans:'1,2,3,4',
      exp:'1578 Alcácer-Quibir → 1578-1580 Cardeal D. Henrique → 1581 Tomar → 1640 Restauração.' },
    { id:'6he66', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'⚔️ Que armada espanhola foi destruída pelos ingleses em 1588?',
      opts:['Armada Real','Armada Invencível','Armada de Castela','Armada da Índia'], ans:1,
      exp:'A "Armada Invencível" de Filipe II foi derrotada pelos ingleses em 1588 (afetando também Portugal).' },
    { id:'6he67', s:'hgp', t:'União Ibérica', type:'tf', diff:2,
      q:'🇵🇹 Durante a União Ibérica, Portugal manteve a sua moeda e leis próprias.',
      ans:true,
      exp:'Verdadeiro. Pelo juramento de Tomar, Portugal manteve algumas instituições próprias.' },
    { id:'6he68', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'👑 Que rei filipino reinava em 1640?',
      opts:['Filipe I','Filipe II','Filipe III','Filipe IV'], ans:2,
      exp:'Filipe III de Portugal (Filipe IV de Espanha) reinava em 1640.' },
    { id:'6he69', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⚔️ Quem era D. Sebastião antes de desaparecer?',
      opts:['Rei de Portugal','Príncipe herdeiro','Cardeal','Duque'], ans:0,
      exp:'D. Sebastião era rei de Portugal e morreu/desapareceu sem herdeiros.' },
    { id:'6he70', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'🇵🇹 Que país europeu enriqueceu com o Império Português durante a União Ibérica?',
      opts:['Espanha','França','Inglaterra','Holanda'], ans:0,
      exp:'A Coroa Espanhola, através da União, beneficiou do Império Português.' },
    { id:'6he71', s:'hgp', t:'União Ibérica', type:'fill', diff:2,
      q:'👑 D. Sebastião era cognominado "o ___".',
      ans:['Desejado','desejado'],
      exp:'D. Sebastião foi chamado "o Desejado" porque o povo o esperava.' },
    { id:'6he72', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⚔️ Que países atacaram colónias portuguesas durante a União Ibérica?',
      opts:['Holanda e Inglaterra','França e Itália','Alemanha e Suécia','Rússia e Polónia'], ans:0,
      exp:'Holanda e Inglaterra atacaram territórios portugueses, vendo-os como inimigos de Espanha.' },
    { id:'6he73', s:'hgp', t:'União Ibérica', type:'tf', diff:1,
      q:'⚔️ Em Alcácer-Quibir morreu o rei D. Sebastião.',
      ans:true,
      exp:'D. Sebastião desapareceu/morreu em Alcácer-Quibir, sem deixar herdeiros.' },
    { id:'6he74', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'📜 As Cortes de Tomar realizaram-se em que ano?',
      opts:['1578','1580','1581','1640'], ans:2,
      exp:'As Cortes de Tomar tiveram lugar em 1581, ano da aclamação de Filipe II.' },
    { id:'6he75', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'🇵🇹 A 4ª Dinastia, que se seguiu à União Ibérica, foi a Dinastia de:',
      opts:['Avis','Bragança','Borgonha','Habsburgo'], ans:1,
      exp:'A Dinastia de Bragança começou com D. João IV em 1640.' },
    { id:'6he76', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'🌍 Que importante feitoria portuguesa no Oriente foi atacada pelos holandeses?',
      opts:['Macau','Ormuz','Malaca','todas as anteriores'], ans:3,
      exp:'Macau, Ormuz e Malaca foram alvos dos holandeses durante a União Ibérica.' },
    { id:'6he77', s:'hgp', t:'União Ibérica', type:'fill', diff:2,
      q:'🇪🇸 O sucessor de D. Sebastião foi o Cardeal D. ___.',
      ans:['Henrique','henrique'],
      exp:'O Cardeal D. Henrique reinou de 1578 a 1580, sem deixar descendência.' },
    { id:'6he78', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'📅 Quanto tempo reinou o Cardeal D. Henrique?',
      opts:['cerca de 2 anos','cerca de 5 anos','cerca de 10 anos','cerca de 20 anos'], ans:0,
      exp:'O Cardeal D. Henrique reinou aproximadamente 2 anos (1578-1580).' },
    { id:'6he79', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'🇵🇹 Que pretendentes portugueses reclamavam o trono em 1580?',
      opts:['D. António e D. Catarina','D. João e D. Maria','D. Pedro e D. Isabel','D. Manuel e D. Joana'], ans:0,
      exp:'D. António, Prior do Crato, e D. Catarina disputavam o trono com Filipe II.' },
    { id:'6he80', s:'hgp', t:'União Ibérica', type:'tf', diff:3,
      q:'🇵🇹 Filipe II tinha parentesco com a família real portuguesa.',
      ans:true,
      exp:'Verdadeiro. Filipe II era neto de D. Manuel I, por linha materna.' },
    { id:'6he81', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⛵ Durante a União Ibérica, o que aconteceu ao Império Português?',
      opts:['Cresceu muito','Manteve-se igual','Sofreu perdas','Foi todo abandonado'], ans:2,
      exp:'O Império Português sofreu perdas (Brasil, Oriente) devido aos ataques aos inimigos de Espanha.' },
    { id:'6he82', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⚔️ O exército português em Alcácer-Quibir lutava contra:',
      opts:['os ingleses','os turcos','o sultão de Marrocos','os holandeses'], ans:2,
      exp:'D. Sebastião combateu o sultão de Marrocos em Alcácer-Quibir.' },
    { id:'6he83', s:'hgp', t:'União Ibérica', type:'fill', diff:1,
      q:'🇪🇸 A União Ibérica foi a união entre Portugal e ___.',
      ans:['Espanha','espanha','Castela'],
      exp:'A União Ibérica uniu as coroas de Portugal e Espanha (Castela).' },
    { id:'6he84', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⛵ Que nome geral se dá aos reis Filipe I, II e III de Portugal?',
      opts:['Avisinos','Filipinos','Bragantinos','Manuelinos'], ans:1,
      exp:'Os três reis foram da Dinastia Filipina (também chamada Habsburgo).' },
    { id:'6he85', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'🇪🇸 O nome "Filipe II" refere-se ao rei como rei de:',
      opts:['Portugal','Espanha','ambos','nenhum'], ans:1,
      exp:'Filipe II era rei de Espanha, mas Filipe I em Portugal.' },
    { id:'6he86', s:'hgp', t:'União Ibérica', type:'tf', diff:2,
      q:'⛵ Os holandeses fundaram a Companhia das Índias Ocidentais para atacar o império português.',
      ans:true,
      exp:'Verdadeiro. Holanda criou companhias para competir com Portugal e Espanha.' },
    { id:'6he87', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'🇵🇹 Como reagiu o povo português à União Ibérica?',
      opts:['Aceitação total','Algum descontentamento','Indiferença','Apoio entusiástico'], ans:1,
      exp:'Apesar das promessas de Tomar, houve descontentamento crescente, levando à Restauração.' },
    { id:'6he88', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'⛵ Onde se encontra o cabo geográfico que limita o Reino de Marrocos a sul?',
      opts:['no Norte de África','no Oriente','na Ásia','no Brasil'], ans:0,
      exp:'O Reino de Marrocos situa-se no Norte de África, onde teve lugar Alcácer-Quibir.' },
    { id:'6he89', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'📜 As Cortes de Tomar foram convocadas por:',
      opts:['D. Sebastião','Cardeal D. Henrique','Filipe II','D. António'], ans:2,
      exp:'Filipe II convocou as Cortes em 1581 para ser aclamado rei de Portugal.' },
    { id:'6he90', s:'hgp', t:'União Ibérica', type:'fill', diff:2,
      q:'🇵🇹 Durante a União Ibérica, a capital de Portugal continuou a ser ___.',
      ans:['Lisboa','lisboa'],
      exp:'Lisboa manteve-se como capital de Portugal.' },
    { id:'6he91', s:'hgp', t:'União Ibérica', type:'tf', diff:2,
      q:'🇵🇹 Durante a União Ibérica, a moeda portuguesa foi substituída pela espanhola.',
      ans:false,
      exp:'Falso. Pelo juramento de Tomar, Portugal manteve a moeda própria.' },
    { id:'6he92', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'⛵ Que potências marítimas surgiram nesta época, fazendo concorrência a Portugal?',
      opts:['Holanda e Inglaterra','França e Itália','Suécia e Dinamarca','Alemanha e Áustria'], ans:0,
      exp:'Holanda e Inglaterra emergiram como potências marítimas e comerciais.' },
    { id:'6he93', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'⚔️ A batalha de Alcácer-Quibir teve lugar em:',
      opts:['Espanha','Portugal','Marrocos','França'], ans:2,
      exp:'A batalha foi em Marrocos (Norte de África).' },
    { id:'6he94', s:'hgp', t:'União Ibérica', type:'order', diff:3,
      q:'Ordena os reis filipinos:',
      items:['Filipe I','Filipe II','Filipe III'],
      ans:'1,2,3',
      exp:'Filipe I (1580-1598), Filipe II (1598-1621), Filipe III (1621-1640).' },
    { id:'6he95', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⛵ Por que motivo D. Sebastião foi para Marrocos?',
      opts:['Comércio','Cruzada/conquista','Diplomacia','Lazer'], ans:1,
      exp:'D. Sebastião empreendeu uma cruzada/expedição militar contra os "infiéis".' },
    { id:'6he96', s:'hgp', t:'União Ibérica', type:'tf', diff:2,
      q:'🇵🇹 A "esperança" no regresso de D. Sebastião deu origem ao mito sebastianista.',
      ans:true,
      exp:'O sebastianismo é uma crença messiânica no regresso do rei.' },
    { id:'6he97', s:'hgp', t:'União Ibérica', type:'mc', diff:3,
      q:'🇪🇸 O reino de Castela e o reino de Aragão estavam unidos na pessoa de:',
      opts:['Carlos V','Filipe II','D. Sebastião','D. Henrique'], ans:1,
      exp:'Filipe II reinava sobre Castela e Aragão (Espanha unificada).' },
    { id:'6he98', s:'hgp', t:'União Ibérica', type:'mc', diff:2,
      q:'⛵ Os 60 anos de União Ibérica enfraqueceram principalmente:',
      opts:['a economia portuguesa','a língua portuguesa','o futebol','o clima'], ans:0,
      exp:'A economia e o império portugueses sofreram com a União Ibérica.' },
    { id:'6he99', s:'hgp', t:'União Ibérica', type:'mc', diff:1,
      q:'🇵🇹 Quem terminou a União Ibérica?',
      opts:['D. Manuel I','D. João IV','D. Pedro IV','D. Maria II'], ans:1,
      exp:'D. João IV foi aclamado rei após a Restauração da Independência (1640).' },
    { id:'6he100', s:'hgp', t:'União Ibérica', type:'fill', diff:2,
      q:'🇵🇹 Após Alcácer-Quibir, gerou-se uma crise de ___ no trono português.',
      ans:['sucessão','sucessao'],
      exp:'A morte de D. Sebastião sem herdeiros gerou uma crise de sucessão.' },

    // ============================================================
    // RESTAURAÇÃO DA INDEPENDÊNCIA (1640) - 50
    // ============================================================
    { id:'6he101', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'📅 Em que data se restaurou a Independência de Portugal?',
      opts:['1 de dezembro de 1640','5 de outubro de 1640','25 de abril de 1640','10 de junho de 1640'], ans:0,
      exp:'A 1 de dezembro de 1640 deu-se a Restauração da Independência.' },
    { id:'6he102', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'👑 Quem foi aclamado rei após a Restauração?',
      opts:['D. João IV','D. João V','D. Pedro II','D. Manuel II'], ans:0,
      exp:'D. João IV, Duque de Bragança, foi aclamado rei.' },
    { id:'6he103', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'🏛️ Onde decorreu a revolta da Restauração?',
      opts:['Castelo de São Jorge','Paço da Ribeira','Mosteiro dos Jerónimos','Palácio da Ajuda'], ans:1,
      exp:'A revolta começou no Paço da Ribeira, em Lisboa.' },
    { id:'6he104', s:'hgp', t:'Restauração da Independência', type:'fill', diff:1,
      q:'👑 D. João IV deu início à Dinastia de ___.',
      ans:['Bragança','braganca','Braganca'],
      exp:'D. João IV foi o primeiro rei da 4ª Dinastia, de Bragança.' },
    { id:'6he105', s:'hgp', t:'Restauração da Independência', type:'tf', diff:1,
      q:'🇵🇹 A Restauração pôs fim aos 60 anos de domínio espanhol.',
      ans:true,
      exp:'Verdadeiro. A Restauração terminou a União Ibérica.' },
    { id:'6he106', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Quanto tempo durou a Guerra da Restauração?',
      opts:['10 anos','28 anos','60 anos','5 anos'], ans:1,
      exp:'A Guerra da Restauração durou 28 anos (1640-1668).' },
    { id:'6he107', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'📜 Em que ano Espanha reconheceu oficialmente a independência de Portugal?',
      opts:['1640','1668','1700','1755'], ans:1,
      exp:'O Tratado de Lisboa (1668) reconheceu a independência portuguesa.' },
    { id:'6he108', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Como se chamou o conflito entre Portugal e Espanha após a Restauração?',
      opts:['Guerra dos Cem Anos','Guerra da Restauração','Guerra Peninsular','Guerra Civil'], ans:1,
      exp:'A Guerra da Restauração (1640-1668) opôs Portugal e Espanha.' },
    { id:'6he109', s:'hgp', t:'Restauração da Independência', type:'fill', diff:2,
      q:'📜 O tratado que reconheceu a independência foi o Tratado de ___.',
      ans:['Lisboa','lisboa'],
      exp:'O Tratado de Lisboa de 1668 pôs fim oficial ao conflito.' },
    { id:'6he110', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Como se chamavam os homens que prepararam a revolta de 1640?',
      opts:['Conjurados','Comuneros','Cruzados','Constitucionais'], ans:0,
      exp:'Os "Conjurados" prepararam a revolta da Restauração.' },
    { id:'6he111', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Quem foi um dos principais conjurados de 1640?',
      opts:['Salgueiro Maia','João Pinto Ribeiro','Marquês de Pombal','Otelo Saraiva'], ans:1,
      exp:'João Pinto Ribeiro foi um dos líderes da conjura da Restauração.' },
    { id:'6he112', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Outro conjurado famoso foi:',
      opts:['D. Miguel de Almeida','D. Pedro V','D. Carlos I','D. Manuel II'], ans:0,
      exp:'D. Miguel de Almeida foi outro conjurado destacado em 1640.' },
    { id:'6he113', s:'hgp', t:'Restauração da Independência', type:'tf', diff:1,
      q:'👑 D. João IV era Duque de Bragança antes de ser rei.',
      ans:true,
      exp:'Verdadeiro. Era o 8.º Duque de Bragança quando foi aclamado rei.' },
    { id:'6he114', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Quem governava a Espanha quando ocorreu a Restauração?',
      opts:['Filipe III','Filipe IV (Filipe III de Portugal)','Carlos II','Filipe V'], ans:1,
      exp:'Filipe IV de Espanha (Filipe III de Portugal) reinava em 1640.' },
    { id:'6he115', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'🏛️ Quem governava Portugal em nome de Filipe III antes da Restauração?',
      opts:['Vice-rei','Margarida de Saboia','Olivares','Conde-Duque'], ans:1,
      exp:'Margarida de Saboia, Duquesa de Mântua, governava Portugal como vice-rainha.' },
    { id:'6he116', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Que ministro espanhol provocou descontentamento em Portugal?',
      opts:['Olivares','Filipe IV','Carlos V','Cisneros'], ans:0,
      exp:'O Conde-Duque de Olivares quis aumentar impostos e centralizar o poder.' },
    { id:'6he117', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'⚔️ A Restauração foi uma:',
      opts:['Revolta política','Festa religiosa','Descoberta','Reforma agrícola'], ans:0,
      exp:'A Restauração foi uma revolta política para acabar com o domínio espanhol.' },
    { id:'6he118', s:'hgp', t:'Restauração da Independência', type:'fill', diff:1,
      q:'📅 A Restauração ocorreu no dia ___ de dezembro.',
      ans:['1','primeiro'],
      exp:'A Restauração foi a 1 de dezembro de 1640.' },
    { id:'6he119', s:'hgp', t:'Restauração da Independência', type:'order', diff:2,
      q:'Ordena cronologicamente:',
      items:['Início da União Ibérica','Restauração','Fim da Guerra','Tratado de Lisboa'],
      ans:'1,2,3,4',
      exp:'1580 União → 1640 Restauração → 1668 Fim da guerra/Tratado.' },
    { id:'6he120', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ A batalha decisiva da Guerra da Restauração foi:',
      opts:['Aljubarrota','Ameixial e Montes Claros','Toro','Ourique'], ans:1,
      exp:'As batalhas do Ameixial (1663) e Montes Claros (1665) foram decisivas.' },
    { id:'6he121', s:'hgp', t:'Restauração da Independência', type:'tf', diff:2,
      q:'👑 D. João IV foi aclamado rei pelo povo de Lisboa.',
      ans:true,
      exp:'Verdadeiro. Foi aclamado rei após a revolta no Paço da Ribeira.' },
    { id:'6he122', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'🇵🇹 A Praça da Restauração situa-se em:',
      opts:['Porto','Lisboa','Coimbra','Évora'], ans:1,
      exp:'A Praça dos Restauradores está em Lisboa, com o obelisco em memória de 1640.' },
    { id:'6he123', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Quem comandou a vice-rainha Margarida de Saboia em 1640?',
      opts:['Conde-Duque de Olivares','Miguel de Vasconcelos','D. António','D. Pedro'], ans:1,
      exp:'Miguel de Vasconcelos, secretário de Estado, foi morto na revolta.' },
    { id:'6he124', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Em que país pediu D. João IV ajuda durante a Guerra da Restauração?',
      opts:['Inglaterra e França','Alemanha','Itália','Holanda apenas'], ans:0,
      exp:'Portugal pediu apoio a Inglaterra, França e também Holanda contra Espanha.' },
    { id:'6he125', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'🇵🇹 O dia 1 de dezembro é feriado nacional para celebrar:',
      opts:['o 25 de Abril','a Restauração da Independência','a República','o Natal'], ans:1,
      exp:'1 de dezembro é o Dia da Restauração da Independência (feriado).' },
    { id:'6he126', s:'hgp', t:'Restauração da Independência', type:'tf', diff:2,
      q:'👑 D. João IV foi o primeiro rei da Dinastia de Bragança.',
      ans:true,
      exp:'Verdadeiro. Iniciou a 4ª Dinastia, de Bragança.' },
    { id:'6he127', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Que rainha de Inglaterra casou com o filho de D. João IV?',
      opts:['Isabel I','Catarina de Bragança (casou com Carlos II)','Maria Antonieta','Vitória'], ans:1,
      exp:'Catarina de Bragança, filha de D. João IV, casou com Carlos II de Inglaterra.' },
    { id:'6he128', s:'hgp', t:'Restauração da Independência', type:'fill', diff:2,
      q:'⚔️ A Guerra da Restauração começou em ___ e terminou em 1668.',
      ans:['1640','1641'],
      exp:'A guerra começou logo em 1640 e prolongou-se até 1668.' },
    { id:'6he129', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'🏛️ A Praça dos Restauradores tem um monumento a quem?',
      opts:['Aos descobridores','Aos heróis da Restauração','Aos reis','Aos militares de Abril'], ans:1,
      exp:'O obelisco homenageia os heróis da Restauração de 1640.' },
    { id:'6he130', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'👑 Quem governou Portugal após D. João IV?',
      opts:['D. Afonso VI','D. Pedro II','D. João V','D. José I'], ans:0,
      exp:'D. Afonso VI sucedeu a D. João IV; mais tarde foi substituído por D. Pedro II.' },
    { id:'6he131', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Em 1665, os portugueses venceram a batalha de:',
      opts:['Aljubarrota','Montes Claros','Toro','Salado'], ans:1,
      exp:'Em Montes Claros (1665), Portugal venceu uma batalha decisiva contra Espanha.' },
    { id:'6he132', s:'hgp', t:'Restauração da Independência', type:'tf', diff:1,
      q:'⚔️ A Guerra da Restauração foi vencida por Portugal.',
      ans:true,
      exp:'Verdadeiro. Portugal conseguiu manter a sua independência.' },
    { id:'6he133', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'🇵🇹 D. João IV nasceu em que cidade?',
      opts:['Lisboa','Vila Viçosa','Porto','Coimbra'], ans:1,
      exp:'D. João IV nasceu em Vila Viçosa, residência dos Duques de Bragança.' },
    { id:'6he134', s:'hgp', t:'Restauração da Independência', type:'fill', diff:2,
      q:'👑 D. João IV pertencia à família dos Duques de ___.',
      ans:['Bragança','braganca','Braganca'],
      exp:'D. João IV era o 8.º Duque de Bragança.' },
    { id:'6he135', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'🇵🇹 A 4ª Dinastia (Bragança) reinou até:',
      opts:['1755','1820','1910','1974'], ans:2,
      exp:'A Dinastia de Bragança terminou em 1910 com a implantação da República.' },
    { id:'6he136', s:'hgp', t:'Restauração da Independência', type:'match', diff:3,
      q:'Associa cada figura ao seu papel em 1640:',
      pairs:[['D. João IV','Rei aclamado'],['Margarida de Saboia','Vice-rainha'],['Miguel de Vasconcelos','Secretário morto'],['João Pinto Ribeiro','Conjurado']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Cada figura teve papel próprio na Restauração.' },
    { id:'6he137', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'🇵🇹 A Restauração devolveu a Portugal a sua:',
      opts:['Independência','Religião','Língua','Geografia'], ans:0,
      exp:'A Restauração devolveu a Independência política a Portugal.' },
    { id:'6he138', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'📜 Quantos anos demorou Espanha a reconhecer a independência?',
      opts:['1','10','28','60'], ans:2,
      exp:'Espanha reconheceu a independência só em 1668, ou seja, 28 anos depois.' },
    { id:'6he139', s:'hgp', t:'Restauração da Independência', type:'tf', diff:2,
      q:'⚔️ Durante a Guerra da Restauração, Portugal teve apoio inglês.',
      ans:true,
      exp:'Verdadeiro. A aliança com Inglaterra foi importante (casamento Catarina-Carlos II).' },
    { id:'6he140', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'🇵🇹 O que aconteceu a Miguel de Vasconcelos durante a revolta?',
      opts:['Foi exilado','Foi morto','Fugiu para Espanha','Tornou-se aliado'], ans:1,
      exp:'Miguel de Vasconcelos foi morto pelos conjurados no Paço da Ribeira.' },
    { id:'6he141', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'🇵🇹 O grito de "Viva D. João IV, rei de Portugal!" foi ouvido em:',
      opts:['Madrid','Lisboa','Roma','Paris'], ans:1,
      exp:'O grito de aclamação ouviu-se em Lisboa, no dia 1 de dezembro de 1640.' },
    { id:'6he142', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'👑 Quem foi rainha consorte de D. João IV?',
      opts:['D. Maria Francisca','D. Luísa de Gusmão','D. Maria Pia','D. Amélia'], ans:1,
      exp:'D. Luísa de Gusmão, esposa de D. João IV, teve papel ativo no apoio à causa.' },
    { id:'6he143', s:'hgp', t:'Restauração da Independência', type:'fill', diff:2,
      q:'👑 A esposa de D. João IV era ___ de Gusmão.',
      ans:['Luísa','luisa','Luisa'],
      exp:'D. Luísa de Gusmão foi rainha de Portugal.' },
    { id:'6he144', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Que tipo de regime Portugal manteve após a Restauração?',
      opts:['República','Monarquia absoluta','Democracia','Império'], ans:1,
      exp:'Portugal manteve a Monarquia, agora com a Dinastia de Bragança.' },
    { id:'6he145', s:'hgp', t:'Restauração da Independência', type:'tf', diff:1,
      q:'🇵🇹 D. João IV era da Dinastia de Avis.',
      ans:false,
      exp:'Falso. D. João IV iniciou a Dinastia de Bragança (4ª Dinastia).' },
    { id:'6he146', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Que feriado nacional celebra a Restauração?',
      opts:['10 de junho','25 de abril','1 de dezembro','5 de outubro'], ans:2,
      exp:'1 de dezembro é o feriado nacional da Restauração.' },
    { id:'6he147', s:'hgp', t:'Restauração da Independência', type:'mc', diff:3,
      q:'⚔️ Que potência ajudou Portugal contra Espanha durante a guerra?',
      opts:['França e Inglaterra','Itália','Áustria','Suécia'], ans:0,
      exp:'França e Inglaterra apoiaram Portugal contra Espanha.' },
    { id:'6he148', s:'hgp', t:'Restauração da Independência', type:'fill', diff:1,
      q:'🇵🇹 ___ de Bragança casou com Carlos II de Inglaterra.',
      ans:['Catarina','catarina'],
      exp:'Catarina de Bragança, filha de D. João IV, casou com Carlos II de Inglaterra.' },
    { id:'6he149', s:'hgp', t:'Restauração da Independência', type:'mc', diff:2,
      q:'⚔️ Após 1668, Portugal:',
      opts:['Continuou dependente','Voltou a ser independente reconhecido','Uniu-se à França','Tornou-se república'], ans:1,
      exp:'Após o Tratado de Lisboa (1668), Portugal foi reconhecido como país independente.' },
    { id:'6he150', s:'hgp', t:'Restauração da Independência', type:'mc', diff:1,
      q:'⚔️ Os conjurados eram:',
      opts:['nobres e fidalgos portugueses','soldados espanhóis','padres italianos','franceses'], ans:0,
      exp:'Os conjurados eram nobres e fidalgos portugueses descontentes com Espanha.' },

    // ============================================================
    // ILUMINISMO E MARQUÊS DE POMBAL (séc. XVIII) - 50
    // ============================================================
    { id:'6he151', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'👑 De que rei foi ministro o Marquês de Pombal?',
      opts:['D. João V','D. José I','D. Maria I','D. João VI'], ans:1,
      exp:'O Marquês de Pombal foi ministro de D. José I.' },
    { id:'6he152', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'🌍 Em que ano ocorreu o terramoto de Lisboa?',
      opts:['1640','1750','1755','1820'], ans:2,
      exp:'O grande terramoto de Lisboa foi a 1 de novembro de 1755.' },
    { id:'6he153', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'🏛️ Quem dirigiu a reconstrução de Lisboa após o terramoto?',
      opts:['Marquês de Pombal','D. João V','D. Maria I','Cardeal Cerejeira'], ans:0,
      exp:'O Marquês de Pombal dirigiu a reconstrução pombalina da Baixa de Lisboa.' },
    { id:'6he154', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'fill', diff:1,
      q:'🏛️ O verdadeiro nome do Marquês de Pombal era ___ José de Carvalho e Melo.',
      ans:['Sebastião','sebastiao','Sebastiao'],
      exp:'Sebastião José de Carvalho e Melo, futuro Marquês de Pombal.' },
    { id:'6he155', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:1,
      q:'💡 O Iluminismo defendia o uso da razão e da ciência.',
      ans:true,
      exp:'Verdadeiro. O Iluminismo valorizava a razão, a ciência e o progresso.' },
    { id:'6he156', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🌍 Em que dia ocorreu o terramoto de 1755?',
      opts:['25 de abril','1 de novembro','5 de outubro','1 de dezembro'], ans:1,
      exp:'O terramoto foi no Dia de Todos os Santos, 1 de novembro de 1755.' },
    { id:'6he157', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🌊 Após o terramoto, Lisboa foi atingida por:',
      opts:['neve','tsunami e incêndios','um vulcão','uma seca'], ans:1,
      exp:'Houve um tsunami e incêndios que destruíram grande parte da cidade.' },
    { id:'6he158', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🏛️ A área reconstruída por Pombal chama-se:',
      opts:['Alfama','Bairro Alto','Baixa Pombalina','Belém'], ans:2,
      exp:'A Baixa Pombalina foi planeada e reconstruída segundo um traçado em quadrícula.' },
    { id:'6he159', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'fill', diff:2,
      q:'⛪ Em 1759, o Marquês expulsou os ___ de Portugal.',
      ans:['Jesuítas','jesuítas','jesuitas'],
      exp:'Os Jesuítas foram expulsos em 1759 por ordem do Marquês de Pombal.' },
    { id:'6he160', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'💡 O Iluminismo é também chamado:',
      opts:['Idade das Trevas','Século das Luzes','Renascimento','Idade Média'], ans:1,
      exp:'O Iluminismo é o "Século das Luzes" (séc. XVIII).' },
    { id:'6he161', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:1,
      q:'👑 D. José I governou no séc. XVIII.',
      ans:true,
      exp:'D. José I reinou de 1750 a 1777.' },
    { id:'6he162', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🌍 Por que ficou famoso o terramoto de 1755?',
      opts:['Pelas vítimas e destruição','Por durar uma semana','Por não ter consequências','Por ser pequeno'], ans:0,
      exp:'O terramoto causou enormes danos e milhares de vítimas em Lisboa.' },
    { id:'6he163', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'⚖️ Em 1761, Pombal aboliu a escravatura no:',
      opts:['Brasil','continente português','Império inteiro','Açores'], ans:1,
      exp:'Em 1761, Pombal aboliu a escravatura em Portugal continental (não em todo o império).' },
    { id:'6he164', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'📚 Pombal reformou o ensino, criando:',
      opts:['as escolas régias','as universidades religiosas','os colégios jesuítas','as madraças'], ans:0,
      exp:'Pombal criou as escolas régias e reformou o ensino primário e a universidade.' },
    { id:'6he165', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'fill', diff:2,
      q:'🏛️ Pombal reformou a Universidade de ___.',
      ans:['Coimbra','coimbra'],
      exp:'A Universidade de Coimbra foi reformada em 1772 pelo Marquês de Pombal.' },
    { id:'6he166', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'🏛️ Quantos andares têm geralmente os edifícios pombalinos?',
      opts:['1','2 a 5','10','mais de 20'], ans:1,
      exp:'Os edifícios pombalinos têm normalmente entre 2 e 5 andares.' },
    { id:'6he167', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🏛️ Os edifícios pombalinos foram desenhados para resistir a:',
      opts:['cheias','terramotos','tempestades','neve'], ans:1,
      exp:'A "gaiola pombalina" é uma estrutura de madeira anti-sísmica.' },
    { id:'6he168', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:2,
      q:'🏛️ A Praça do Comércio é um exemplo da reconstrução pombalina.',
      ans:true,
      exp:'A Praça do Comércio (Terreiro do Paço) foi reconstruída segundo o plano de Pombal.' },
    { id:'6he169', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'💼 Pombal apoiou a economia criando:',
      opts:['Companhias de Comércio','sindicatos','partidos','escolas religiosas'], ans:0,
      exp:'Pombal criou Companhias de Comércio (ex.: Vinhos do Alto Douro).' },
    { id:'6he170', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'🍷 Que companhia comercial Pombal criou para o vinho?',
      opts:['Companhia das Índias','Companhia do Vinho do Porto / Alto Douro','Companhia do Algodão','Companhia das Vinhas'], ans:1,
      exp:'A Companhia Geral da Agricultura das Vinhas do Alto Douro (1756) regulava o vinho do Porto.' },
    { id:'6he171', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'⛪ Os Jesuítas eram membros de uma ordem:',
      opts:['religiosa','militar','económica','política'], ans:0,
      exp:'A Companhia de Jesus (jesuítas) é uma ordem religiosa católica.' },
    { id:'6he172', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'💡 Que filósofos defenderam ideias do Iluminismo?',
      opts:['Voltaire e Rousseau','Aristóteles e Platão','São Tomás','Camões'], ans:0,
      exp:'Voltaire, Rousseau, Montesquieu e Diderot foram filósofos iluministas.' },
    { id:'6he173', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'order', diff:2,
      q:'Ordena cronologicamente:',
      items:['Reinado de D. João V','Terramoto de Lisboa','Expulsão dos Jesuítas','Reforma da Universidade de Coimbra'],
      ans:'1,2,3,4',
      exp:'D. João V (até 1750) → 1755 terramoto → 1759 jesuítas → 1772 Universidade.' },
    { id:'6he174', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'👑 Pombal recebeu o título de Marquês em que ano?',
      opts:['1750','1755','1769','1777'], ans:2,
      exp:'Recebeu o título de Marquês de Pombal em 1769.' },
    { id:'6he175', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:2,
      q:'👑 Após D. José I morrer, Pombal continuou no poder.',
      ans:false,
      exp:'Falso. D. Maria I afastou Pombal do poder em 1777.' },
    { id:'6he176', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'👑 Quem sucedeu a D. José I?',
      opts:['D. Maria I','D. João VI','D. Pedro IV','D. Maria II'], ans:0,
      exp:'D. Maria I, "a Pia", sucedeu a D. José I em 1777.' },
    { id:'6he177', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'fill', diff:1,
      q:'👑 D. José I é cognominado "o ___".',
      ans:['Reformador','reformador'],
      exp:'D. José I é conhecido como "o Reformador" devido às reformas pombalinas.' },
    { id:'6he178', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'⚖️ Em 1758 ocorreu uma tentativa de regicídio. Quem foi a vítima?',
      opts:['D. José I (sobreviveu)','D. João V','Pombal','D. Maria I'], ans:0,
      exp:'D. José I sofreu um atentado em 1758, do qual sobreviveu.' },
    { id:'6he179', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'⚔️ Quem foi acusado e condenado pelo atentado a D. José I?',
      opts:['Os Távoras','Os Bragança','Os Albuquerque','Os Almeida'], ans:0,
      exp:'A família Távora foi condenada e executada — episódio conhecido como "Processo dos Távoras".' },
    { id:'6he180', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'🌍 O terramoto destruiu sobretudo:',
      opts:['Lisboa','Porto','Évora','Braga'], ans:0,
      exp:'O terramoto destruiu principalmente Lisboa.' },
    { id:'6he181', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🏛️ Que ruas da Baixa de Lisboa têm nome de profissões (ex: Rua dos Sapateiros)?',
      opts:['Pré-pombalinas','Da Baixa Pombalina','Do Bairro Alto','Do Chiado'], ans:1,
      exp:'A Baixa Pombalina tem várias ruas com nome de antigas atividades profissionais.' },
    { id:'6he182', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:2,
      q:'💡 As ideias do Iluminismo influenciaram as reformas de Pombal.',
      ans:true,
      exp:'Verdadeiro. Pombal era um déspota esclarecido influenciado pelo Iluminismo.' },
    { id:'6he183', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'💡 Como se chama o regime em que o monarca governa de forma absoluta mas com ideias iluministas?',
      opts:['Despotismo Esclarecido','Liberalismo','Anarquia','Comunismo'], ans:0,
      exp:'O Despotismo Esclarecido (ou Iluminado) era praticado por reis como D. José I.' },
    { id:'6he184', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🏛️ Quem foi o famoso engenheiro militar da reconstrução de Lisboa?',
      opts:['Manuel da Maia','Aleixo Boto','Eugénio dos Santos','todos contribuíram'], ans:3,
      exp:'Manuel da Maia, Eugénio dos Santos e Carlos Mardel contribuíram para o plano.' },
    { id:'6he185', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'fill', diff:2,
      q:'🏛️ A famosa estátua de D. José I encontra-se no Terreiro do ___.',
      ans:['Paço','paco','Paco'],
      exp:'A estátua equestre de D. José I está no Terreiro do Paço (Praça do Comércio).' },
    { id:'6he186', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🌍 O terramoto sentiu-se em:',
      opts:['Apenas Lisboa','Apenas Portugal','Toda a Europa Ocidental e Norte de África','Apenas Madrid'], ans:2,
      exp:'O terramoto teve consequências em vários países, incluindo Marrocos e Espanha.' },
    { id:'6he187', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'📚 A reforma pombalina do ensino criou que disciplina nas escolas?',
      opts:['Ciências experimentais','Latim','Catequese','Música religiosa'], ans:0,
      exp:'Pombal valorizou as ciências experimentais e a matemática.' },
    { id:'6he188', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:1,
      q:'⛪ Pombal era amigo dos Jesuítas.',
      ans:false,
      exp:'Falso. Pombal expulsou os Jesuítas em 1759.' },
    { id:'6he189', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'💼 Pombal pretendia que Portugal fosse:',
      opts:['mais dependente da Inglaterra','mais autónomo economicamente','colónia espanhola','colónia francesa'], ans:1,
      exp:'Pombal queria reduzir a dependência de Portugal face à Inglaterra.' },
    { id:'6he190', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'🏛️ A Praça do Comércio está aberta para o:',
      opts:['rio Tejo','oceano','rio Douro','rio Mondego'], ans:0,
      exp:'A Praça do Comércio abre-se para o rio Tejo.' },
    { id:'6he191', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'👑 D. Maria I afastou Pombal porque:',
      opts:['era amigo dela','era contra a religião','tinha tomado decisões muito autoritárias','tinha morrido'], ans:2,
      exp:'D. Maria I afastou Pombal devido ao seu autoritarismo, no que ficou conhecido como "Viradeira".' },
    { id:'6he192', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'fill', diff:3,
      q:'👑 O período em que D. Maria I anulou medidas pombalinas chama-se ___.',
      ans:['Viradeira','viradeira'],
      exp:'A "Viradeira" é o período em que D. Maria I reverteu várias medidas de Pombal.' },
    { id:'6he193', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'💼 Pombal criou em Coimbra o Real Colégio dos:',
      opts:['Nobres','Pobres','Estrangeiros','Religiosos'], ans:0,
      exp:'O Real Colégio dos Nobres foi criado para educar a nobreza.' },
    { id:'6he194', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'🏛️ As Idades das Luzes refere-se ao século:',
      opts:['XVI','XVII','XVIII','XIX'], ans:2,
      exp:'O Iluminismo desenvolve-se durante o séc. XVIII.' },
    { id:'6he195', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'tf', diff:2,
      q:'💡 O Iluminismo defendia que todos deveriam ter acesso à educação.',
      ans:true,
      exp:'Verdadeiro. Os iluministas defendiam a educação como caminho para o progresso.' },
    { id:'6he196', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'🇵🇹 Pombal apoiou as manufacturas, ou seja, a:',
      opts:['agricultura','indústria artesanal','pesca','navegação'], ans:1,
      exp:'Pombal incentivou as manufaturas (têxtil, vidro, cerâmica) para fortalecer a economia.' },
    { id:'6he197', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:1,
      q:'⛪ Os Jesuítas controlavam, em Portugal, sobretudo:',
      opts:['o exército','o ensino','a agricultura','a pesca'], ans:1,
      exp:'A Companhia de Jesus controlava grande parte do ensino antes da expulsão.' },
    { id:'6he198', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'match', diff:3,
      q:'Associa cada ação a Pombal:',
      pairs:[['1755','Terramoto'],['1759','Expulsão dos Jesuítas'],['1761','Abolição escravatura no continente'],['1772','Reforma da Universidade']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Datas e ações principais do governo pombalino.' },
    { id:'6he199', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:2,
      q:'👑 D. Maria I foi a primeira:',
      opts:['Rainha de Portugal a reinar por direito próprio','Rainha consorte','Princesa estrangeira','Imperatriz'], ans:0,
      exp:'D. Maria I foi a primeira mulher a reinar em Portugal por direito próprio.' },
    { id:'6he200', s:'hgp', t:'Iluminismo e Marquês de Pombal', type:'mc', diff:3,
      q:'💡 Em que país europeu nasceu o movimento iluminista?',
      opts:['Inglaterra e França','Alemanha','Itália','Rússia'], ans:0,
      exp:'O Iluminismo desenvolveu-se especialmente em França e Inglaterra no séc. XVIII.' },

    // ============================================================
    // LIBERALISMO (séc. XIX) - 50
    // ============================================================
    { id:'6he201', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'⚔️ Em que ano se deram as primeiras invasões francesas a Portugal?',
      opts:['1755','1807','1820','1834'], ans:1,
      exp:'A primeira invasão francesa ocorreu em 1807.' },
    { id:'6he202', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'👑 Para onde fugiu a corte portuguesa em 1807?',
      opts:['França','Inglaterra','Brasil','Espanha'], ans:2,
      exp:'A família real e a corte fugiram para o Brasil em 1807.' },
    { id:'6he203', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'🌹 A Revolução Liberal teve início em:',
      opts:['Lisboa, 1820','Porto, 1820','Évora, 1834','Coimbra, 1820'], ans:1,
      exp:'A Revolução Liberal começou no Porto, em 24 de agosto de 1820.' },
    { id:'6he204', s:'hgp', t:'Liberalismo', type:'fill', diff:1,
      q:'📜 A primeira Constituição Portuguesa foi aprovada em ___.',
      ans:['1822','mil oitocentos e vinte e dois'],
      exp:'A Constituição de 1822 foi a primeira Constituição liberal portuguesa.' },
    { id:'6he205', s:'hgp', t:'Liberalismo', type:'tf', diff:1,
      q:'⚔️ Napoleão Bonaparte ordenou as invasões francesas a Portugal.',
      ans:true,
      exp:'Verdadeiro. Napoleão queria obrigar Portugal a aplicar o Bloqueio Continental.' },
    { id:'6he206', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Quem comandou a primeira invasão francesa (1807)?',
      opts:['Junot','Soult','Massena','Murat'], ans:0,
      exp:'O General Junot comandou a primeira invasão francesa em 1807.' },
    { id:'6he207', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Quem comandou a segunda invasão francesa (1809)?',
      opts:['Junot','Soult','Massena','Wellington'], ans:1,
      exp:'O General Soult comandou a segunda invasão francesa em 1809.' },
    { id:'6he208', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Quem comandou a terceira invasão francesa (1810)?',
      opts:['Junot','Soult','Massena','Murat'], ans:2,
      exp:'O General Massena comandou a terceira invasão francesa em 1810.' },
    { id:'6he209', s:'hgp', t:'Liberalismo', type:'fill', diff:2,
      q:'🇧🇷 O Brasil tornou-se independente em ___.',
      ans:['1822','mil oitocentos e vinte e dois'],
      exp:'O Brasil tornou-se independente em 7 de setembro de 1822, com D. Pedro.' },
    { id:'6he210', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'👑 Quem proclamou a independência do Brasil?',
      opts:['D. João VI','D. Pedro (depois Pedro IV de Portugal)','D. Miguel','D. Maria II'], ans:1,
      exp:'D. Pedro, filho de D. João VI, proclamou a independência do Brasil em 1822.' },
    { id:'6he211', s:'hgp', t:'Liberalismo', type:'tf', diff:1,
      q:'🌹 O Liberalismo defende as liberdades individuais e a separação de poderes.',
      ans:true,
      exp:'Verdadeiro. O Liberalismo defende liberdades, igualdade perante a lei e divisão de poderes.' },
    { id:'6he212', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Em que data se realizou a Revolução Liberal do Porto?',
      opts:['24 de agosto de 1820','1 de dezembro de 1820','5 de outubro de 1820','25 de abril de 1820'], ans:0,
      exp:'A Revolução Liberal teve início a 24 de agosto de 1820, no Porto.' },
    { id:'6he213', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'👑 Em que ano regressou D. João VI do Brasil?',
      opts:['1820','1821','1822','1823'], ans:1,
      exp:'D. João VI regressou em 1821, atendendo aos pedidos dos liberais.' },
    { id:'6he214', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'⚔️ Que General inglês ajudou Portugal contra os franceses?',
      opts:['Wellington','Nelson','Churchill','Marlborough'], ans:0,
      exp:'O Duque de Wellington (Arthur Wellesley) ajudou Portugal contra Napoleão.' },
    { id:'6he215', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'⚔️ Que linha defensiva foi construída por Wellington?',
      opts:['Linhas de Torres Vedras','Muralha de Lisboa','Castelo de Almeida','Forte de Sagres'], ans:0,
      exp:'As Linhas de Torres Vedras (1810) impediram o avanço francês até Lisboa.' },
    { id:'6he216', s:'hgp', t:'Liberalismo', type:'order', diff:2,
      q:'Ordena cronologicamente:',
      items:['Invasões Francesas','Revolução Liberal','Independência do Brasil','Guerras Liberais'],
      ans:'1,2,3,4',
      exp:'1807-10 invasões → 1820 Liberal → 1822 Brasil → 1828-34 Guerras Liberais.' },
    { id:'6he217', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ As Guerras Liberais opuseram:',
      opts:['D. Pedro e D. Miguel','D. João VI e D. Pedro','D. Miguel e D. Maria II','D. Pedro IV e D. Pedro V'], ans:0,
      exp:'D. Pedro (liberal) opôs-se ao seu irmão D. Miguel (absolutista).' },
    { id:'6he218', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Quando ocorreram as Guerras Liberais?',
      opts:['1807-1810','1820-1822','1828-1834','1834-1851'], ans:2,
      exp:'As Guerras Liberais decorreram entre 1828 e 1834.' },
    { id:'6he219', s:'hgp', t:'Liberalismo', type:'fill', diff:2,
      q:'⚔️ A vitória final dos liberais deu-se na Convenção de ___-Monte.',
      ans:['Évora','evora','Evora'],
      exp:'A Convenção de Évora-Monte (1834) pôs fim à Guerra Civil com vitória liberal.' },
    { id:'6he220', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'👑 Quem era D. Miguel?',
      opts:['Filho de D. João VI, defensor do absolutismo','Filho de D. Pedro IV','Sobrinho de D. José','Pai de D. Maria II'], ans:0,
      exp:'D. Miguel era filho de D. João VI e defensor do absolutismo.' },
    { id:'6he221', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'👑 Quem era D. Maria II em relação a D. Pedro?',
      opts:['filha','irmã','tia','prima'], ans:0,
      exp:'D. Maria II era filha de D. Pedro IV.' },
    { id:'6he222', s:'hgp', t:'Liberalismo', type:'tf', diff:2,
      q:'📜 A Constituição de 1822 instituía a soberania popular.',
      ans:true,
      exp:'Verdadeiro. A Constituição de 1822 estabelecia que o poder vinha do povo.' },
    { id:'6he223', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'🌹 O contrário do liberalismo é o:',
      opts:['comunismo','absolutismo','federalismo','progresso'], ans:1,
      exp:'O absolutismo é o regime em que o rei tem poder total.' },
    { id:'6he224', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'📜 A Constituição de 1822 dividia o poder em quantos órgãos?',
      opts:['1','2','3 (legislativo, executivo, judicial)','4'], ans:2,
      exp:'A separação de poderes do Iluminismo: legislativo, executivo e judicial.' },
    { id:'6he225', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'🇵🇹 Que cidade resistiu como bastião liberal durante o cerco miguelista?',
      opts:['Lisboa','Porto','Coimbra','Braga'], ans:1,
      exp:'O Porto resistiu durante o famoso "Cerco do Porto" (1832-1833).' },
    { id:'6he226', s:'hgp', t:'Liberalismo', type:'fill', diff:2,
      q:'⚔️ As tropas inglesas vieram ajudar Portugal contra os ___.',
      ans:['franceses','Franceses'],
      exp:'Os ingleses ajudaram Portugal contra os franceses (Napoleão).' },
    { id:'6he227', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'⚔️ Os defensores do absolutismo eram chamados:',
      opts:['liberais','miguelistas/absolutistas','republicanos','jacobinos'], ans:1,
      exp:'Os miguelistas defendiam o regime absoluto.' },
    { id:'6he228', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'📅 Em que ano terminaram as Guerras Liberais?',
      opts:['1828','1832','1834','1836'], ans:2,
      exp:'As Guerras Liberais terminaram em 1834.' },
    { id:'6he229', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'👑 Quem foi rainha de Portugal após as Guerras Liberais?',
      opts:['D. Maria I','D. Maria II','D. Amélia','D. Estefânia'], ans:1,
      exp:'D. Maria II reinou após a vitória liberal em 1834.' },
    { id:'6he230', s:'hgp', t:'Liberalismo', type:'tf', diff:2,
      q:'🇧🇷 D. Pedro foi rei do Brasil e de Portugal.',
      ans:true,
      exp:'Verdadeiro. D. Pedro foi Imperador do Brasil (Pedro I) e rei de Portugal (Pedro IV).' },
    { id:'6he231', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'⚔️ Quem ganhou as Guerras Liberais?',
      opts:['Os miguelistas','Os liberais','Os ingleses','Os franceses'], ans:1,
      exp:'Os liberais venceram, instaurando a Monarquia Constitucional.' },
    { id:'6he232', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ A invasão de 1807 forçou a corte a partir para:',
      opts:['Inglaterra','Brasil','França','África'], ans:1,
      exp:'A corte fugiu para o Brasil sob proteção da marinha inglesa.' },
    { id:'6he233', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'🌹 A Revolução Liberal foi inspirada por:',
      opts:['Iluminismo','Renascimento','Reforma Protestante','Idade Média'], ans:0,
      exp:'O Liberalismo é uma consequência das ideias do Iluminismo.' },
    { id:'6he234', s:'hgp', t:'Liberalismo', type:'fill', diff:2,
      q:'⚔️ As Linhas de Torres ___ impediram o avanço francês.',
      ans:['Vedras','vedras'],
      exp:'As Linhas de Torres Vedras protegeram Lisboa.' },
    { id:'6he235', s:'hgp', t:'Liberalismo', type:'tf', diff:1,
      q:'⚔️ As invasões francesas causaram destruição em Portugal.',
      ans:true,
      exp:'Verdadeiro. Houve grandes destruições e roubos de obras de arte.' },
    { id:'6he236', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'⚔️ A política de Napoleão proibia o comércio com:',
      opts:['Espanha','Inglaterra','França','Brasil'], ans:1,
      exp:'O Bloqueio Continental proibia o comércio com Inglaterra.' },
    { id:'6he237', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'👑 Que rei português pediu auxílio inglês durante as invasões?',
      opts:['D. José I','D. João VI (Príncipe Regente)','D. Pedro IV','D. Maria II'], ans:1,
      exp:'D. João VI, então Príncipe Regente, contou com a aliança inglesa.' },
    { id:'6he238', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'🌹 A bandeira da Revolução Liberal era a defesa de:',
      opts:['monarquia absoluta','constituição','independência','colónias'], ans:1,
      exp:'Os liberais defendiam uma Constituição que limitasse o poder real.' },
    { id:'6he239', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'📜 A Constituição estabelece:',
      opts:['as leis fundamentais do país','os preços dos produtos','a religião oficial apenas','os horários escolares'], ans:0,
      exp:'A Constituição é a lei fundamental que organiza o Estado.' },
    { id:'6he240', s:'hgp', t:'Liberalismo', type:'fill', diff:1,
      q:'🌹 A Revolução Liberal aconteceu na cidade do ___.',
      ans:['Porto','porto'],
      exp:'O Porto foi o palco da Revolução Liberal de 1820.' },
    { id:'6he241', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'👑 Como acabou a vida de D. Miguel após Évora-Monte?',
      opts:['Foi executado','Foi exilado','Continuou rei','Tornou-se padre'], ans:1,
      exp:'D. Miguel foi exilado para fora de Portugal após Évora-Monte.' },
    { id:'6he242', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Quem era considerado "o Rei-Soldado" das Guerras Liberais?',
      opts:['D. Miguel','D. Pedro IV','D. João VI','D. Pedro V'], ans:1,
      exp:'D. Pedro IV ficou conhecido como "Rei-Soldado" pela sua participação militar.' },
    { id:'6he243', s:'hgp', t:'Liberalismo', type:'tf', diff:2,
      q:'🇵🇹 Após as Guerras Liberais, Portugal tornou-se uma Monarquia Constitucional.',
      ans:true,
      exp:'Verdadeiro. A Monarquia Constitucional vigorou de 1834 a 1910.' },
    { id:'6he244', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'📜 A Carta Constitucional foi outorgada em 1826 por:',
      opts:['D. João VI','D. Pedro IV','D. Miguel','D. Maria II'], ans:1,
      exp:'D. Pedro IV outorgou a Carta Constitucional em 1826.' },
    { id:'6he245', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'🌹 Que documento substituiu temporariamente a Constituição de 1822?',
      opts:['Carta Constitucional de 1826','Decreto Pombalino','Estatuto Real','Lei Salazarista'], ans:0,
      exp:'A Carta Constitucional de 1826 vigorou em alternância com a Constituição de 1822.' },
    { id:'6he246', s:'hgp', t:'Liberalismo', type:'mc', diff:1,
      q:'⚔️ Quem comandava as tropas francesas em Portugal?',
      opts:['Generais de Napoleão','Generais ingleses','Generais espanhóis','Generais portugueses'], ans:0,
      exp:'Os Generais de Napoleão (Junot, Soult, Massena) comandaram as invasões.' },
    { id:'6he247', s:'hgp', t:'Liberalismo', type:'fill', diff:2,
      q:'👑 D. Pedro IV foi também imperador do ___.',
      ans:['Brasil','brasil'],
      exp:'D. Pedro IV de Portugal era D. Pedro I do Brasil.' },
    { id:'6he248', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'⚔️ Em que continente decorreram as Guerras Liberais?',
      opts:['América','África','Europa','Ásia'], ans:2,
      exp:'As Guerras Liberais decorreram em Portugal, na Europa.' },
    { id:'6he249', s:'hgp', t:'Liberalismo', type:'mc', diff:3,
      q:'⚔️ As Cortes Constituintes reuniram-se em:',
      opts:['Porto, 1820','Lisboa, 1821','Coimbra, 1822','Évora, 1834'], ans:1,
      exp:'As Cortes Constituintes reuniram-se em Lisboa, em 1821.' },
    { id:'6he250', s:'hgp', t:'Liberalismo', type:'mc', diff:2,
      q:'🌹 O lema das revoluções liberais era:',
      opts:['Liberdade, Igualdade, Fraternidade','Pátria, Família, Trabalho','Deus, Pátria, Rei','Pão, Paz, Trabalho'], ans:0,
      exp:'O lema vem da Revolução Francesa: Liberdade, Igualdade, Fraternidade.' },

    // ============================================================
    // MONARQUIA CONSTITUCIONAL (1834-1910) - 50
    // ============================================================
    { id:'6he251', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:1,
      q:'👑 Quem foi a primeira rainha da Monarquia Constitucional?',
      opts:['D. Maria I','D. Maria II','D. Amélia','D. Estefânia'], ans:1,
      exp:'D. Maria II reinou como rainha constitucional desde 1834.' },
    { id:'6he252', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:1,
      q:'📅 A Monarquia Constitucional vigorou em Portugal de:',
      opts:['1820 a 1910','1834 a 1910','1826 a 1910','1822 a 1910'], ans:1,
      exp:'A Monarquia Constitucional consolidou-se em 1834, terminando em 1910.' },
    { id:'6he253', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'⚔️ Cartismo e Setembrismo eram:',
      opts:['Bandas musicais','Movimentos políticos','Doenças','Festas religiosas'], ans:1,
      exp:'Cartistas (defensores da Carta de 1826) e Setembristas (defensores da Constituição de 1822) eram movimentos políticos.' },
    { id:'6he254', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:1,
      q:'⚔️ O regicídio aconteceu em ___.',
      ans:['1908','mil novecentos e oito'],
      exp:'O regicídio teve lugar em 1 de fevereiro de 1908.' },
    { id:'6he255', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:1,
      q:'👑 D. Carlos I foi assassinado em 1908.',
      ans:true,
      exp:'Verdadeiro. D. Carlos I e o Príncipe Luís Filipe foram mortos em Lisboa em 1908.' },
    { id:'6he256', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'👑 Quem foi assassinado juntamente com D. Carlos I?',
      opts:['D. Manuel II','Príncipe Luís Filipe','D. Pedro V','D. Amélia'], ans:1,
      exp:'O Príncipe herdeiro Luís Filipe morreu também no atentado de 1908.' },
    { id:'6he257', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'👑 Quem foi o último rei de Portugal?',
      opts:['D. Carlos I','D. Manuel II','D. Pedro V','D. Luís I'], ans:1,
      exp:'D. Manuel II foi o último rei, derrubado pela República em 1910.' },
    { id:'6he258', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'⚔️ Em que ano ocorreu o Ultimato Inglês?',
      opts:['1808','1890','1908','1910'], ans:1,
      exp:'O Ultimato Inglês ocorreu em janeiro de 1890.' },
    { id:'6he259', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'🌍 O Ultimato Inglês obrigou Portugal a abandonar territórios em:',
      opts:['Ásia','África (entre Angola e Moçambique)','América','Oceânia'], ans:1,
      exp:'O Ultimato obrigou Portugal a desistir do "Mapa Cor-de-Rosa" em África.' },
    { id:'6he260', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:2,
      q:'🌍 O Ultimato Inglês foi imposto pela ___.',
      ans:['Inglaterra','inglaterra','Grã-Bretanha'],
      exp:'A Inglaterra impôs o Ultimato a Portugal em 1890.' },
    { id:'6he261', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🇵🇹 O Ultimato Inglês causou:',
      opts:['Festejos','Forte revolta popular','Indiferença','Guerra civil'], ans:1,
      exp:'O Ultimato gerou grande indignação e impulsionou os republicanos.' },
    { id:'6he262', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'👑 Quem foi o "Rei Sábio" da Monarquia Constitucional?',
      opts:['D. Pedro V','D. Luís I','D. Carlos I','D. Manuel II'], ans:0,
      exp:'D. Pedro V era conhecido como "o Sábio" ou "o Esperançoso".' },
    { id:'6he263', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'🚂 Em que reinado se desenvolveu o caminho-de-ferro em Portugal?',
      opts:['D. Maria II','D. Pedro V','D. Luís I','D. Carlos I'], ans:1,
      exp:'No reinado de D. Pedro V (1853-1861) inaugura-se a primeira linha férrea (1856).' },
    { id:'6he264', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:2,
      q:'🚂 A primeira linha de comboio em Portugal foi inaugurada em 1856.',
      ans:true,
      exp:'Verdadeiro. A linha Lisboa-Carregado foi inaugurada em 28 de outubro de 1856.' },
    { id:'6he265', s:'hgp', t:'Monarquia Constitucional', type:'order', diff:2,
      q:'Ordena os reis cronologicamente:',
      items:['D. Maria II','D. Pedro V','D. Luís I','D. Carlos I'],
      ans:'1,2,3,4',
      exp:'D. Maria II → D. Pedro V → D. Luís I → D. Carlos I → D. Manuel II.' },
    { id:'6he266', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:1,
      q:'📜 Os Cartistas defendiam:',
      opts:['Constituição de 1822','Carta Constitucional de 1826','República','Ditadura'], ans:1,
      exp:'Os Cartistas defendiam a Carta de 1826, mais conservadora.' },
    { id:'6he267', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'📜 Os Setembristas defendiam:',
      opts:['Constituição de 1822','Carta Constitucional de 1826','República','Absolutismo'], ans:0,
      exp:'Os Setembristas defendiam a Constituição de 1822, mais democrática.' },
    { id:'6he268', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:2,
      q:'👑 D. Carlos I foi assassinado no ___ do Comércio.',
      ans:['Terreiro','terreiro'],
      exp:'O regicídio ocorreu no Terreiro do Paço (Praça do Comércio).' },
    { id:'6he269', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'⚔️ A revolução do 5 de outubro de 1910 derrubou:',
      opts:['D. Carlos I','D. Manuel II','D. Pedro V','D. Maria II'], ans:1,
      exp:'D. Manuel II foi destronado pela implantação da República.' },
    { id:'6he270', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:1,
      q:'👑 D. Maria II teve dois maridos. O segundo foi:',
      opts:['D. Fernando II (de Saxe-Coburgo)','D. Pedro IV','D. Luís I','D. Manuel I'], ans:0,
      exp:'D. Maria II casou com D. Fernando II, da Casa de Saxe-Coburgo-Gotha.' },
    { id:'6he271', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'🏛️ Que palácio foi construído no séc. XIX por D. Fernando II?',
      opts:['Palácio da Pena','Palácio de Belém','Palácio Nacional de Sintra','Palácio de Mafra'], ans:0,
      exp:'O Palácio da Pena, em Sintra, foi mandado construir por D. Fernando II.' },
    { id:'6he272', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:2,
      q:'🌍 O "Mapa Cor-de-Rosa" pretendia unir Angola e Moçambique.',
      ans:true,
      exp:'Verdadeiro. O Mapa Cor-de-Rosa propunha um vasto território português entre Angola e Moçambique.' },
    { id:'6he273', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'🌍 Em que conferência se discutiu a partilha de África?',
      opts:['Berlim (1884-85)','Viena (1815)','Versalhes (1919)','Yalta (1945)'], ans:0,
      exp:'A Conferência de Berlim (1884-85) regulou a partilha de África entre potências europeias.' },
    { id:'6he274', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🇵🇹 Que partido cresceu muito após o Ultimato?',
      opts:['Republicano','Cartista','Miguelista','Monárquico'], ans:0,
      exp:'O Partido Republicano cresceu fortemente após o Ultimato Inglês.' },
    { id:'6he275', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:1,
      q:'👑 O último rei de Portugal foi D. ___ II.',
      ans:['Manuel','manuel'],
      exp:'D. Manuel II foi o último rei (1908-1910).' },
    { id:'6he276', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🚂 Em que séc. surgiram caminhos-de-ferro, telégrafo e indústria em Portugal?',
      opts:['XVII','XVIII','XIX','XX'], ans:2,
      exp:'O séc. XIX trouxe a Revolução Industrial e novos transportes.' },
    { id:'6he277', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'⚔️ Que regime substituiu a Monarquia Constitucional?',
      opts:['Estado Novo','República','Ditadura militar','União Ibérica'], ans:1,
      exp:'A Primeira República substituiu a Monarquia em 1910.' },
    { id:'6he278', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'🚂 Que ministro impulsionou as obras públicas no séc. XIX?',
      opts:['Marquês de Pombal','Fontes Pereira de Melo','Mouzinho da Silveira','Sidónio Pais'], ans:1,
      exp:'Fontes Pereira de Melo (Fontismo) impulsionou estradas, caminhos-de-ferro e portos.' },
    { id:'6he279', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:2,
      q:'🚂 A política de obras públicas do séc. XIX é chamada ___ ismo.',
      ans:['Font','font','Fontismo'],
      exp:'O "Fontismo" deve o nome a Fontes Pereira de Melo.' },
    { id:'6he280', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:2,
      q:'👑 D. Luís I era pai de D. Carlos I.',
      ans:true,
      exp:'Verdadeiro. D. Luís I (1861-1889) foi sucedido pelo filho D. Carlos I.' },
    { id:'6he281', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'⚔️ Em 1908, quem assassinou D. Carlos I?',
      opts:['Republicanos','Monárquicos','Carbonários (republicanos)','Espanhóis'], ans:2,
      exp:'O atentado foi cometido por carbonários e ativistas republicanos.' },
    { id:'6he282', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'⚔️ Quem foram os atiradores que mataram D. Carlos I?',
      opts:['Manuel Buíça e Alfredo Costa','Dois soldados','Dois nobres','Dois padres'], ans:0,
      exp:'Manuel Buíça e Alfredo Costa foram os autores do regicídio de 1908.' },
    { id:'6he283', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:1,
      q:'🇵🇹 D. Manuel II reinou apenas:',
      opts:['cerca de 2 anos','10 anos','20 anos','30 anos'], ans:0,
      exp:'D. Manuel II reinou de 1908 a 1910 (cerca de 2 anos).' },
    { id:'6he284', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🚂 Que outras infraestruturas se desenvolveram no séc. XIX?',
      opts:['Estradas, telégrafo, portos','Apenas estradas','Apenas portos','Apenas correios'], ans:0,
      exp:'O Fontismo desenvolveu estradas, caminho-de-ferro, telégrafo e portos.' },
    { id:'6he285', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:2,
      q:'🌍 Portugal tinha colónias em África no séc. XIX.',
      ans:true,
      exp:'Verdadeiro. Angola, Moçambique, Cabo Verde, Guiné, S. Tomé e Príncipe.' },
    { id:'6he286', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'🌍 Quem foram exploradores portugueses de África no séc. XIX?',
      opts:['Serpa Pinto, Capelo e Ivens','Vasco da Gama','Cabral','Magalhães'], ans:0,
      exp:'Serpa Pinto, Capelo e Ivens fizeram famosas explorações em África.' },
    { id:'6he287', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'📜 Quantas Constituições teve a Monarquia Constitucional?',
      opts:['1','2 (Constituição 1822 e Carta 1826)','3','4'], ans:1,
      exp:'A Constituição de 1822 e a Carta Constitucional de 1826 alternaram.' },
    { id:'6he288', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:2,
      q:'⚔️ A maior crise diplomática do séc. XIX foi o ___ Inglês.',
      ans:['Ultimato','ultimato'],
      exp:'O Ultimato Inglês de 1890.' },
    { id:'6he289', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🇵🇹 Que partidos dominavam a política da Monarquia Constitucional?',
      opts:['Partido Regenerador e Partido Progressista','PS e PSD','BE e CDS','PCP e CDS'], ans:0,
      exp:'Partido Regenerador e Partido Progressista alternavam no poder ("rotativismo").' },
    { id:'6he290', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'⚖️ A alternância no governo entre dois partidos chamava-se:',
      opts:['Rotativismo','Despotismo','Federalismo','Cesarismo'], ans:0,
      exp:'O Rotativismo era a prática de alternância entre os dois grandes partidos.' },
    { id:'6he291', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:1,
      q:'🚂 No séc. XIX surgiram fábricas em Portugal.',
      ans:true,
      exp:'Verdadeiro. A Revolução Industrial chegou tardiamente a Portugal no séc. XIX.' },
    { id:'6he292', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🇵🇹 Em que cidade ocorreu o regicídio?',
      opts:['Porto','Lisboa','Évora','Braga'], ans:1,
      exp:'O regicídio teve lugar em Lisboa, no Terreiro do Paço.' },
    { id:'6he293', s:'hgp', t:'Monarquia Constitucional', type:'match', diff:3,
      q:'Associa cada rei à sua característica:',
      pairs:[['D. Pedro V','o Sábio'],['D. Carlos I','assassinado em 1908'],['D. Manuel II','último rei'],['D. Maria II','primeira rainha constitucional']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Cada rei teve a sua marca na Monarquia Constitucional.' },
    { id:'6he294', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:3,
      q:'⚔️ Em 1891, ocorreu uma revolta republicana em:',
      opts:['Lisboa','Porto (31 de janeiro)','Évora','Coimbra'], ans:1,
      exp:'A Revolta de 31 de janeiro de 1891 foi a primeira tentativa republicana, no Porto.' },
    { id:'6he295', s:'hgp', t:'Monarquia Constitucional', type:'fill', diff:3,
      q:'⚔️ A revolta de 31 de Janeiro ocorreu na cidade do ___.',
      ans:['Porto','porto'],
      exp:'A revolta de 31 de janeiro de 1891 ocorreu no Porto.' },
    { id:'6he296', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'⚔️ A Monarquia Constitucional terminou em:',
      opts:['1 de dezembro de 1910','5 de outubro de 1910','25 de abril de 1910','10 de junho de 1910'], ans:1,
      exp:'A República foi implantada a 5 de outubro de 1910.' },
    { id:'6he297', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'👑 Após a República, D. Manuel II:',
      opts:['Foi preso','Foi exilado para Inglaterra','Tornou-se presidente','Foi morto'], ans:1,
      exp:'D. Manuel II foi exilado e viveu em Inglaterra até morrer.' },
    { id:'6he298', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:2,
      q:'🇵🇹 No séc. XIX, a maior parte da população era:',
      opts:['rural e analfabeta','urbana e culta','noble','operária'], ans:0,
      exp:'A maioria da população portuguesa era rural e analfabeta.' },
    { id:'6he299', s:'hgp', t:'Monarquia Constitucional', type:'tf', diff:3,
      q:'🚂 No séc. XIX surgiram em Lisboa os elétricos (carros americanos).',
      ans:true,
      exp:'Verdadeiro. Os primeiros elétricos surgiram no final do séc. XIX em Lisboa e Porto.' },
    { id:'6he300', s:'hgp', t:'Monarquia Constitucional', type:'mc', diff:1,
      q:'👑 D. Maria II reinou aproximadamente entre:',
      opts:['1820-1840','1834-1853','1853-1861','1861-1889'], ans:1,
      exp:'D. Maria II reinou entre 1834 e 1853.' },
];
if (typeof window !== 'undefined') window.EXERCISES_6_H_EXTRA = EXERCISES_6_H_EXTRA;
