// EscolaPlay - Banco extra do 2.º ano (gerado, AE 2018)
// Para integrar em content.js dentro de EXERCISES_2.
// PT-PT, Acordo Ortográfico de 1990. Vocabulário do 1.º ciclo.
const EXERCISES_2_EXTRA = [

    // ============================================================
    // ===================== PORTUGUÊS ============================
    // ============================================================

    // ----- Vogais e consoantes (8) -----
    { id:'2p15', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🍎 Quantas vogais tem a palavra "maçã"?',
      opts:['1','2','3','4'], ans:1,
      exp:'maçã → "a" e "ã" → 2 vogais.' },
    { id:'2p16', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐱 Qual é a vogal da palavra "gato"?',
      opts:['a, o','e, i','u, o','a, e'], ans:0,
      exp:'gato → as vogais são "a" e "o".' },
    { id:'2p17', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'☀️ A letra "s" é uma vogal.',
      ans:false,
      exp:'O "s" é uma consoante. As vogais são a, e, i, o, u.' },
    { id:'2p18', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🌙 Quantas consoantes tem a palavra "lua"?',
      opts:['1','2','3','0'], ans:0,
      exp:'lua → só o "l" é consoante. "u" e "a" são vogais.' },
    { id:'2p19', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'🍞 Escreve as vogais da palavra "pão".',
      ans:['ão','a o','a,o','ao'],
      exp:'pão → vogais "ã" e "o".' },
    { id:'2p20', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐦 Qual destas palavras tem só uma vogal?',
      opts:['sol','casa','livro','mãe'], ans:0,
      exp:'sol → só tem a vogal "o".' },
    { id:'2p21', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:2,
      q:'🔤 A letra "y" é uma vogal do alfabeto português.',
      ans:false,
      exp:'As vogais portuguesas são a, e, i, o, u.' },
    { id:'2p22', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🏠 Quantas consoantes tem a palavra "escola"?',
      opts:['2','3','4','5'], ans:1,
      exp:'escola → consoantes: s, c, l → 3 consoantes.' },

    // ----- Sílabas (10) -----
    { id:'2p23', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐶 Quantas sílabas tem a palavra "cão"?',
      ans:['1','um','uma'],
      exp:'cão = 1 sílaba.' },
    { id:'2p24', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐱 Quantas sílabas tem a palavra "gato"?',
      ans:['2','dois','duas'],
      exp:'ga-to = 2 sílabas.' },
    { id:'2p25', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🍌 Como se divide a palavra "banana" em sílabas?',
      opts:['ba-na-na','ban-an-a','b-an-ana','bana-na'], ans:0,
      exp:'ba-na-na → 3 sílabas.' },
    { id:'2p26', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🪑 Como se divide a palavra "cadeira"?',
      opts:['ca-dei-ra','ca-de-ira','cad-ei-ra','ca-d-ei-ra'], ans:0,
      exp:'ca-dei-ra → 3 sílabas. "ei" é um ditongo.' },
    { id:'2p27', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'📚 Quantas sílabas tem "livro"?',
      ans:['2','dois','duas'],
      exp:'li-vro = 2 sílabas.' },
    { id:'2p28', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🦋 Como se divide "borboleta"?',
      opts:['bor-bo-le-ta','borb-ole-ta','bor-bole-ta','bo-rbo-le-ta'], ans:0,
      exp:'bor-bo-le-ta → 4 sílabas.' },
    { id:'2p29', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🌻 Quantas sílabas tem "girassol"?',
      ans:['3','três','tres'],
      exp:'gi-ras-sol = 3 sílabas.' },
    { id:'2p30', s:'portugues', t:'Sílabas', type:'mc', diff:2,
      q:'🐟 Quantas sílabas tem "peixe"?',
      opts:['1','2','3','4'], ans:1,
      exp:'pei-xe = 2 sílabas.' },
    { id:'2p31', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🍫 Como se divide "chocolate"?',
      opts:['ch-oc-ol-ate','cho-co-la-te','choc-o-late','cho-col-ate'], ans:1,
      exp:'cho-co-la-te → 4 sílabas.' },
    { id:'2p32', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'☀️ Quantas sílabas tem "sol"?',
      ans:['1','um','uma'],
      exp:'sol = 1 sílaba.' },

    // ----- Ditongos (10) -----
    { id:'2p33', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'👩 Qual destas palavras tem um ditongo?',
      opts:['mãe','sapo','gato','livro'], ans:0,
      exp:'mãe → "ãe" é um ditongo (duas vogais juntas).' },
    { id:'2p34', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'☁️ Qual destas palavras tem o ditongo "éu"?',
      opts:['casa','céu','bola','dia'], ans:1,
      exp:'céu → "éu" é um ditongo.' },
    { id:'2p35', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'🐂 A palavra "boi" tem um ditongo.',
      ans:true,
      exp:'boi → "oi" é um ditongo.' },
    { id:'2p36', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'Qual destas palavras NÃO tem ditongo?',
      opts:['pai','dia','sol','rei'], ans:2,
      exp:'sol não tem duas vogais juntas. As outras têm.' },
    { id:'2p37', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'✋ Escreve o ditongo da palavra "mão".',
      ans:['ão','ao'],
      exp:'mão → ditongo "ão".' },
    { id:'2p38', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'👑 Qual é o ditongo da palavra "rei"?',
      opts:['re','ei','rei','er'], ans:1,
      exp:'rei → ditongo "ei".' },
    { id:'2p39', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'🐔 A palavra "pão" tem um ditongo.',
      ans:true,
      exp:'pão → "ão" é um ditongo nasal.' },
    { id:'2p40', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🦁 Qual é o ditongo em "leão"?',
      opts:['le','ão','ea','oa'], ans:1,
      exp:'le-ão → "ão" é o ditongo.' },
    { id:'2p41', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌈 Qual destas palavras tem ditongo?',
      opts:['arco','noite','lua','flor'], ans:1,
      exp:'noite → "oi" é um ditongo.' },
    { id:'2p42', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'🐂 Qual é o ditongo da palavra "pai"?',
      ans:['ai'],
      exp:'pai → ditongo "ai".' },

    // ----- Sinónimos (12) -----
    { id:'2p43', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'😊 Qual é o sinónimo de "feliz"?',
      opts:['triste','contente','zangado','cansado'], ans:1,
      exp:'feliz = contente.' },
    { id:'2p44', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🏃 Qual é o sinónimo de "rápido"?',
      opts:['lento','veloz','grande','pequeno'], ans:1,
      exp:'rápido = veloz.' },
    { id:'2p45', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🏠 Qual é o sinónimo de "casa"?',
      opts:['rua','lar','escola','quintal'], ans:1,
      exp:'casa = lar.' },
    { id:'2p46', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'😂 Sinónimo de "engraçado": ___',
      ans:['divertido','cómico','comico'],
      exp:'engraçado = divertido = cómico.' },
    { id:'2p47', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'😴 Qual é o sinónimo de "cansado"?',
      opts:['acordado','fatigado','feliz','rápido'], ans:1,
      exp:'cansado = fatigado.' },
    { id:'2p48', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🐶 Qual é o sinónimo de "amigo"?',
      opts:['irmão','companheiro','primo','vizinho'], ans:1,
      exp:'amigo = companheiro.' },
    { id:'2p49', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🌟 Sinónimo de "bonito": ___',
      ans:['belo','lindo'],
      exp:'bonito = belo = lindo.' },
    { id:'2p50', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🍰 Qual é o sinónimo de "saboroso"?',
      opts:['amargo','delicioso','salgado','azedo'], ans:1,
      exp:'saboroso = delicioso.' },
    { id:'2p51', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🤐 Qual é o sinónimo de "calmo"?',
      opts:['nervoso','tranquilo','rápido','triste'], ans:1,
      exp:'calmo = tranquilo.' },
    { id:'2p52', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🎁 Qual é o sinónimo de "presente"?',
      opts:['caixa','prenda','flor','livro'], ans:1,
      exp:'presente = prenda.' },
    { id:'2p53', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'😢 Sinónimo de "triste": ___',
      ans:['infeliz','choroso'],
      exp:'triste = infeliz.' },
    { id:'2p54', s:'portugues', t:'Sinónimos', type:'mc', diff:1,
      q:'🦁 Qual é o sinónimo de "valente"?',
      opts:['medroso','corajoso','triste','fraco'], ans:1,
      exp:'valente = corajoso.' },

    // ----- Antónimos (12) -----
    { id:'2p55', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'😊 Qual é o antónimo de "feliz"?',
      opts:['contente','triste','alegre','rir'], ans:1,
      exp:'feliz ≠ triste.' },
    { id:'2p56', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'☀️ Qual é o antónimo de "dia"?',
      opts:['noite','manhã','sol','luz'], ans:0,
      exp:'dia ≠ noite.' },
    { id:'2p57', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'🐘 Qual é o antónimo de "grande"?',
      opts:['enorme','pequeno','alto','gordo'], ans:1,
      exp:'grande ≠ pequeno.' },
    { id:'2p58', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🌑 Antónimo de "claro": ___',
      ans:['escuro'],
      exp:'claro ≠ escuro.' },
    { id:'2p59', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'🏃 Qual é o antónimo de "rápido"?',
      opts:['veloz','lento','forte','feliz'], ans:1,
      exp:'rápido ≠ lento.' },
    { id:'2p60', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'🌅 Qual é o antónimo de "novo"?',
      opts:['velho','jovem','bom','grande'], ans:0,
      exp:'novo ≠ velho.' },
    { id:'2p61', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🌞 Antónimo de "cheio": ___',
      ans:['vazio'],
      exp:'cheio ≠ vazio.' },
    { id:'2p62', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'⬆️ Qual é o antónimo de "subir"?',
      opts:['saltar','descer','correr','andar'], ans:1,
      exp:'subir ≠ descer.' },
    { id:'2p63', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'🤝 Qual é o antónimo de "amigo"?',
      opts:['colega','inimigo','primo','irmão'], ans:1,
      exp:'amigo ≠ inimigo.' },
    { id:'2p64', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'😄 Antónimo de "rir": ___',
      ans:['chorar'],
      exp:'rir ≠ chorar.' },
    { id:'2p65', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'💪 Qual é o antónimo de "forte"?',
      opts:['grande','fraco','alto','rápido'], ans:1,
      exp:'forte ≠ fraco.' },
    { id:'2p66', s:'portugues', t:'Antónimos', type:'mc', diff:1,
      q:'🤫 Qual é o antónimo de "barulhento"?',
      opts:['silencioso','alto','grande','rápido'], ans:0,
      exp:'barulhento ≠ silencioso.' },

    // ----- Família de palavras (10) -----
    { id:'2p67', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🍞 Qual destas palavras pertence à família de "pão"?',
      opts:['padaria','livraria','escola','rua'], ans:0,
      exp:'pão → padaria, padeiro, padarias.' },
    { id:'2p68', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌊 Qual destas palavras pertence à família de "mar"?',
      opts:['terra','marinheiro','sol','rio'], ans:1,
      exp:'mar → marinheiro, marítimo, maré.' },
    { id:'2p69', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌸 Qual destas palavras NÃO é da família de "flor"?',
      opts:['florista','florido','feliz','florescer'], ans:2,
      exp:'feliz não vem de flor.' },
    { id:'2p70', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🐟 Quem trabalha a vender peixe é o ___.',
      ans:['peixeiro'],
      exp:'peixe → peixeiro, peixaria.' },
    { id:'2p71', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras pertence à família de "terra"?',
      opts:['água','terreno','sol','mar'], ans:1,
      exp:'terra → terreno, terrestre, aterrar.' },
    { id:'2p72', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'📚 Qual destas palavras pertence à família de "livro"?',
      opts:['caderno','livraria','lápis','escola'], ans:1,
      exp:'livro → livraria, livreiro.' },
    { id:'2p73', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🏫 Quem ensina na escola é o ___.',
      ans:['professor','professora'],
      exp:'escola → professor, escolar.' },
    { id:'2p74', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🥛 Qual destas palavras pertence à família de "leite"?',
      opts:['leitaria','padaria','peixaria','loja'], ans:0,
      exp:'leite → leitaria, leiteiro.' },
    { id:'2p75', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras pertence à família de "jardim"?',
      opts:['cozinheiro','jardineiro','médico','padeiro'], ans:1,
      exp:'jardim → jardineiro, jardinagem.' },
    { id:'2p76', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🍞 Quem faz o pão é o ___.',
      ans:['padeiro'],
      exp:'pão → padeiro, padaria.' },

    // ----- Tipos de frase (12) -----
    { id:'2p77', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'❓ "Tens fome?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Termina com "?" → interrogativa.' },
    { id:'2p78', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🌞 "O sol está a brilhar." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Termina com "." e afirma → declarativa.' },
    { id:'2p79', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎂 "Que bolo lindo!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Termina com "!" → exclamativa.' },
    { id:'2p80', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🪑 "Senta-te, por favor." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem ou pedido → imperativa.' },
    { id:'2p81', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐶 "Como se chama o teu cão?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2p82', s:'portugues', t:'Tipos de frase', type:'fill', diff:1,
      q:'Que sinal de pontuação tem uma frase exclamativa? ___',
      ans:['!','ponto de exclamação','exclamação'],
      exp:'A frase exclamativa termina com "!".' },
    { id:'2p83', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🚪 "Abre a porta." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem → imperativa.' },
    { id:'2p84', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎉 "Que festa divertida!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção e termina com "!" → exclamativa.' },
    { id:'2p85', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐱 "O gato bebe leite." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2p86', s:'portugues', t:'Tipos de frase', type:'fill', diff:1,
      q:'Que sinal usamos no fim de uma pergunta? ___',
      ans:['?','ponto de interrogação','interrogação'],
      exp:'A frase interrogativa termina com "?".' },
    { id:'2p87', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🛏️ "Vai para a cama." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'É uma ordem → imperativa.' },
    { id:'2p88', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🧒 "Onde está a Maria?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },

    // ----- Singular e plural (12) -----
    { id:'2p89', s:'portugues', t:'Singular e plural', type:'fill', diff:2,
      q:'🐶 Plural de "cão": ___',
      ans:['cães'],
      exp:'cão → cães (palavras em "-ão" mudam).' },
    { id:'2p90', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐦 Plural de "ave": ___',
      ans:['aves'],
      exp:'Acrescenta-se "s" no final.' },
    { id:'2p91', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🦁 Plural de "animal": ___',
      ans:['animais'],
      exp:'Palavras em "-al" → "-ais".' },
    { id:'2p92', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🌻 Plural de "flor": ___',
      ans:['flores'],
      exp:'Palavras em "-or" → "-ores".' },
    { id:'2p93', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'📒 Qual é o plural de "caderno"?',
      opts:['caderno','cadernos','cadernes','cadernois'], ans:1,
      exp:'caderno → cadernos.' },
    { id:'2p94', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🌞 Plural de "sol": ___',
      ans:['sóis','sois'],
      exp:'Palavras em "-ol" → "-óis".' },
    { id:'2p95', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'👨 Plural de "homem": ___',
      ans:['homens'],
      exp:'Palavras em "-m" → "-ns".' },
    { id:'2p96', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🍐 Plural de "pera": ___',
      ans:['peras'],
      exp:'pera → peras.' },
    { id:'2p97', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🐠 Qual é o plural de "peixe"?',
      opts:['peixs','peixes','peixos','peixeis'], ans:1,
      exp:'peixe → peixes.' },
    { id:'2p98', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🇵🇹 Plural de "irmão": ___',
      ans:['irmãos','irmaos'],
      exp:'irmão → irmãos.' },
    { id:'2p99', s:'portugues', t:'Singular e plural', type:'fill', diff:2,
      q:'⚽ Plural de "bola": ___',
      ans:['bolas'],
      exp:'bola → bolas.' },
    { id:'2p100', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🇵🇹 Qual é o plural de "pão"?',
      opts:['pãos','pães','pans','pã'], ans:1,
      exp:'pão → pães.' },

    // ----- Verbos no presente (12) -----
    { id:'2p101', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🍎 Eu ___ (comer) uma maçã.',
      ans:['como'],
      exp:'Verbo comer → eu como.' },
    { id:'2p102', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'💧 Tu ___ (beber) água.',
      ans:['bebes'],
      exp:'Verbo beber → tu bebes.' },
    { id:'2p103', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎨 A Maria ___ (pintar) um desenho.',
      ans:['pinta'],
      exp:'Verbo pintar → ela pinta.' },
    { id:'2p104', s:'portugues', t:'Verbos no presente', type:'fill', diff:2,
      q:'🛌 Nós ___ (dormir) cedo.',
      ans:['dormimos'],
      exp:'Verbo dormir → nós dormimos.' },
    { id:'2p105', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎵 Eles ___ (cantar) uma canção.',
      ans:['cantam'],
      exp:'Verbo cantar → eles cantam.' },
    { id:'2p106', s:'portugues', t:'Verbos no presente', type:'mc', diff:1,
      q:'🏃 Qual é a forma certa? "Eu ___ no parque."',
      opts:['corro','corres','corre','correm'], ans:0,
      exp:'Eu corro (verbo correr no presente).' },
    { id:'2p107', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'📚 O João ___ (estudar) para o teste.',
      ans:['estuda'],
      exp:'Verbo estudar → ele estuda.' },
    { id:'2p108', s:'portugues', t:'Verbos no presente', type:'mc', diff:1,
      q:'🐶 Qual é a forma certa? "Os cães ___ no jardim."',
      opts:['brinca','brincas','brincam','brincamos'], ans:2,
      exp:'Eles/elas brincam (3.ª pessoa do plural).' },
    { id:'2p109', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🚲 Vós ___ (andar) de bicicleta.',
      ans:['andais'],
      exp:'Verbo andar → vós andais.' },
    { id:'2p110', s:'portugues', t:'Verbos no presente', type:'mc', diff:1,
      q:'🍝 "A mãe ___ uma sopa." Qual é a forma certa?',
      opts:['cozinho','cozinhas','cozinha','cozinham'], ans:2,
      exp:'Ela cozinha (3.ª pessoa do singular).' },
    { id:'2p111', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'⚽ Tu ___ (jogar) à bola.',
      ans:['jogas'],
      exp:'Verbo jogar → tu jogas.' },
    { id:'2p112', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'📖 Nós ___ (ler) um livro.',
      ans:['lemos'],
      exp:'Verbo ler → nós lemos.' },

    // ============================================================
    // ===================== MATEMÁTICA ===========================
    // ============================================================

    // ----- Números até 100 (12) -----
    { id:'2m21', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Qual é o número antes de 50? ___',
      ans:['49'],
      exp:'O número antes de 50 é 49.' },
    { id:'2m22', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Qual é o número depois de 79? ___',
      ans:['80'],
      exp:'Depois de 79 vem 80.' },
    { id:'2m23', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o maior?',
      opts:['56','65','45','67'], ans:3,
      exp:'67 é o maior. Compara primeiro as dezenas: 6 dezenas, mas 67 > 65.' },
    { id:'2m24', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o menor?',
      opts:['23','32','13','31'], ans:2,
      exp:'13 é o menor (1 dezena).' },
    { id:'2m25', s:'matematica', t:'Números até 100', type:'order', diff:1,
      q:'Ordena do menor para o maior:',
      items:['9','19','29','91'],
      exp:'9 < 19 < 29 < 91.' },
    { id:'2m26', s:'matematica', t:'Números até 100', type:'order', diff:1,
      q:'Ordena do maior para o menor:',
      items:['88','58','38','18'],
      exp:'88 > 58 > 38 > 18.' },
    { id:'2m27', s:'matematica', t:'Números até 100', type:'fill', diff:2,
      q:'🔢 Quantas dezenas tem 100? ___',
      ans:['10','dez'],
      exp:'100 = 10 dezenas.' },
    { id:'2m28', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Que número está entre 56 e 58?',
      opts:['55','57','59','60'], ans:1,
      exp:'56, 57, 58 → o número entre é 57.' },
    { id:'2m29', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve por extenso o número 25: ___',
      ans:['vinte e cinco'],
      exp:'25 = vinte e cinco.' },
    { id:'2m30', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Quantos números pares há entre 1 e 10?',
      opts:['3','4','5','6'], ans:2,
      exp:'Pares: 2, 4, 6, 8, 10 → 5 números.' },
    { id:'2m31', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 O número 70 tem quantas dezenas?',
      opts:['7','0','70','17'], ans:0,
      exp:'70 = 7 dezenas.' },
    { id:'2m32', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve o número "quarenta e oito" em algarismos: ___',
      ans:['48'],
      exp:'quarenta e oito = 48.' },

    // ----- Dezenas e unidades (10) -----
    { id:'2m33', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:2,
      q:'🔢 No número 35: ___ dezenas e ___ unidades. (responde só dezenas)',
      ans:['3','três','tres'],
      exp:'35 = 3 dezenas + 5 unidades.' },
    { id:'2m34', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Quantas unidades tem o número 86?',
      opts:['8','6','86','80'], ans:1,
      exp:'86 = 8 dezenas + 6 unidades.' },
    { id:'2m35', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 4 dezenas e 7 unidades fazem o número ___.',
      ans:['47'],
      exp:'40 + 7 = 47.' },
    { id:'2m36', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Que número tem 9 dezenas e 0 unidades?',
      opts:['9','19','90','99'], ans:2,
      exp:'9 dezenas = 90.' },
    { id:'2m37', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Quantas dezenas tem 50? ___',
      ans:['5','cinco'],
      exp:'50 = 5 dezenas.' },
    { id:'2m38', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Que número tem 7 dezenas e 4 unidades?',
      opts:['47','74','78','17'], ans:1,
      exp:'7 dezenas + 4 unidades = 70 + 4 = 74.' },
    { id:'2m39', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 No número 92, quanto vale o algarismo 9? ___',
      ans:['90','noventa','9 dezenas'],
      exp:'O 9 está nas dezenas → vale 90.' },
    { id:'2m40', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Quantas dezenas tem o número 23?',
      opts:['2','3','23','20'], ans:0,
      exp:'23 = 2 dezenas + 3 unidades.' },
    { id:'2m41', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 6 dezenas + 0 unidades = ___',
      ans:['60','sessenta'],
      exp:'6 dezenas = 60.' },
    { id:'2m42', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 No número 58, quanto vale o algarismo 8?',
      opts:['8 dezenas','8 unidades','80','58'], ans:1,
      exp:'O 8 está nas unidades → vale 8.' },

    // ----- Adição até 100 (14) -----
    { id:'2m43', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 12 + 6 = ___',
      ans:['18'],
      exp:'12 + 6 = 18.' },
    { id:'2m44', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 20 + 30 = ___',
      ans:['50'],
      exp:'2 dezenas + 3 dezenas = 5 dezenas = 50.' },
    { id:'2m45', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 35 + 14 = ___',
      ans:['49'],
      exp:'5+4=9. 3+1=4. Resultado: 49.' },
    { id:'2m46', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 27 + 18 = ___',
      ans:['45'],
      exp:'7+8=15 (escrevo 5, transporto 1). 2+1+1=4. Resultado: 45.' },
    { id:'2m47', s:'matematica', t:'Adição até 100', type:'problem', diff:1,
      q:'🍪 A Eduarda comeu 12 bolachas e a Joana comeu 9. Quantas comeram juntas?',
      ans:['21'],
      material:'Soma: 12 + 9.',
      solution:'Unidades: 2 + 9 = 11 (escrevo 1, transporto 1). Dezenas: 1 + 1 = 2. Resultado: 21 bolachas.',
      exp:'Adição com transporte.' },
    { id:'2m48', s:'matematica', t:'Adição até 100', type:'problem', diff:2,
      q:'🌸 No jardim há 24 rosas e 18 margaridas. Quantas flores há ao todo?',
      ans:['42'],
      material:'Soma: 24 + 18.',
      solution:'Unidades: 4+8=12 (escrevo 2, transporto 1). Dezenas: 2+1+1=4. Resultado: 42 flores.',
      exp:'Adição com transporte.' },
    { id:'2m49', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 40 + 25 = ?',
      opts:['55','65','75','45'], ans:1,
      exp:'40 + 25 = 65.' },
    { id:'2m50', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 56 + 33 = ___',
      ans:['89'],
      exp:'6+3=9. 5+3=8. Resultado: 89.' },
    { id:'2m51', s:'matematica', t:'Adição até 100', type:'problem', diff:2,
      q:'🍎🍎🍎 A Maria tinha 15 maçãs. A avó deu-lhe mais 7. Com quantas ficou?',
      ans:['22'],
      material:'Soma: 15 + 7.',
      solution:'5+7=12 (escrevo 2, transporto 1). 1+1=2. Resultado: 22 maçãs.',
      exp:'Adição com transporte.' },
    { id:'2m52', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 50 + 50 = ___',
      ans:['100','cem'],
      exp:'50 + 50 = 100.' },
    { id:'2m53', s:'matematica', t:'Adição até 100', type:'problem', diff:1,
      q:'📚 O Tomás leu 23 páginas de manhã e 19 à tarde. Quantas leu no total?',
      ans:['42'],
      material:'Soma: 23 + 19.',
      solution:'3+9=12 (escrevo 2, transporto 1). 2+1+1=4. Resultado: 42 páginas.',
      exp:'Adição com transporte.' },
    { id:'2m54', s:'matematica', t:'Adição até 100', type:'mc', diff:2,
      q:'➕ 38 + 25 = ?',
      opts:['53','63','73','43'], ans:1,
      exp:'8+5=13 (transporto 1). 3+2+1=6. Resultado: 63.' },
    { id:'2m55', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 60 + 9 = ___',
      ans:['69'],
      exp:'60 + 9 = 69.' },
    { id:'2m56', s:'matematica', t:'Adição até 100', type:'problem', diff:1,
      q:'🐱🐱🐱 No parque há 11 gatos pretos e 8 gatos brancos. Quantos gatos há?',
      ans:['19'],
      material:'Soma: 11 + 8.',
      solution:'1 + 8 = 9 (unidades). 1 + 0 = 1 (dezenas). Resultado: 19 gatos.',
      exp:'Adição sem transporte.' },

    // ----- Subtração até 100 (14) -----
    { id:'2m57', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 18 − 5 = ___',
      ans:['13'],
      exp:'18 − 5 = 13.' },
    { id:'2m58', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 30 − 10 = ___',
      ans:['20'],
      exp:'3 dezenas − 1 dezena = 2 dezenas = 20.' },
    { id:'2m59', s:'matematica', t:'Subtração até 100', type:'fill', diff:3,
      q:'➖ 45 − 23 = ___',
      ans:['22'],
      exp:'5−3=2. 4−2=2. Resultado: 22.' },
    { id:'2m60', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 52 − 28 = ___',
      ans:['24'],
      exp:'2 < 8 → empresta 1 dezena. 12−8=4. 4−2=2. Resultado: 24.' },
    { id:'2m61', s:'matematica', t:'Subtração até 100', type:'problem', diff:2,
      q:'🍫 O Pedro tinha 30 chocolates e deu 13 ao irmão. Com quantos ficou?',
      ans:['17'],
      material:'Subtração: 30 − 13.',
      solution:'30 − 10 = 20. 20 − 3 = 17. Ficou com 17 chocolates.',
      exp:'Subtração com empréstimo.' },
    { id:'2m62', s:'matematica', t:'Subtração até 100', type:'problem', diff:1,
      q:'🐠 Num aquário havia 25 peixes. Foram vendidos 9. Quantos restam?',
      ans:['16'],
      material:'Subtração: 25 − 9.',
      solution:'25 − 5 = 20. 20 − 4 = 16. Restam 16 peixes.',
      exp:'Subtração com empréstimo.' },
    { id:'2m63', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
      q:'➖ 60 − 20 = ?',
      opts:['30','40','50','80'], ans:1,
      exp:'60 − 20 = 40.' },
    { id:'2m64', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 73 − 35 = ___',
      ans:['38'],
      exp:'3 < 5 → empresta 1 dezena. 13−5=8. 6−3=3. Resultado: 38.' },
    { id:'2m65', s:'matematica', t:'Subtração até 100', type:'problem', diff:1,
      q:'🍭 A Sofia tem 40 rebuçados. Comeu 15. Quantos lhe restam?',
      ans:['25'],
      material:'Subtração: 40 − 15.',
      solution:'40 − 10 = 30. 30 − 5 = 25. Restam 25 rebuçados.',
      exp:'Subtração com empréstimo.' },
    { id:'2m66', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 99 − 9 = ___',
      ans:['90'],
      exp:'9−9=0. 9−0=9. Resultado: 90.' },
    { id:'2m67', s:'matematica', t:'Subtração até 100', type:'problem', diff:1,
      q:'🚌 No autocarro vinham 27 pessoas. Saíram 8. Quantas ficaram?',
      ans:['19'],
      material:'Subtração: 27 − 8.',
      solution:'27 − 7 = 20. 20 − 1 = 19. Ficaram 19 pessoas.',
      exp:'Subtração com empréstimo.' },
    { id:'2m68', s:'matematica', t:'Subtração até 100', type:'mc', diff:2,
      q:'➖ 84 − 47 = ?',
      opts:['37','43','47','27'], ans:0,
      exp:'14−7=7 (empresta). 7−4=3. Resultado: 37.' },
    { id:'2m69', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 100 − 50 = ___',
      ans:['50'],
      exp:'100 − 50 = 50.' },
    { id:'2m70', s:'matematica', t:'Subtração até 100', type:'problem', diff:1,
      q:'🐦 Na árvore havia 18 pássaros. 6 voaram. Quantos restam?',
      ans:['12'],
      material:'Subtração: 18 − 6.',
      solution:'8 − 6 = 2. 1 − 0 = 1. Restam 12 pássaros.',
      exp:'Subtração simples.' },

    // ----- Tabuada do 2 (10) -----
    { id:'2m71', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 1 = ___',
      ans:['2'],
      exp:'2 × 1 = 2.' },
    { id:'2m72', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 3 = ___',
      ans:['6'],
      exp:'2 × 3 = 2 + 2 + 2 = 6.' },
    { id:'2m73', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 5 = ___',
      ans:['10'],
      exp:'2 × 5 = 10.' },
    { id:'2m74', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ 2 × 4 = ?',
      opts:['6','8','10','12'], ans:1,
      exp:'2 × 4 = 8.' },
    { id:'2m75', s:'matematica', t:'Tabuada do 2', type:'fill', diff:2,
      q:'✖️ 2 × 8 = ___',
      ans:['16'],
      exp:'2 × 8 = 16.' },
    { id:'2m76', s:'matematica', t:'Tabuada do 2', type:'mc', diff:2,
      q:'✖️ 2 × 9 = ?',
      opts:['16','17','18','20'], ans:2,
      exp:'2 × 9 = 18.' },
    { id:'2m77', s:'matematica', t:'Tabuada do 2', type:'fill', diff:2,
      q:'✖️ 2 × 10 = ___',
      ans:['20'],
      exp:'2 × 10 = 20.' },
    { id:'2m78', s:'matematica', t:'Tabuada do 2', type:'problem', diff:1,
      q:'🚲 Cada bicicleta tem 2 rodas. Quantas rodas têm 6 bicicletas?',
      ans:['12'],
      material:'Multiplicação: 2 × 6.',
      solution:'2 × 6 = 12. Há 12 rodas.',
      exp:'Multiplicação como soma repetida.' },
    { id:'2m79', s:'matematica', t:'Tabuada do 2', type:'problem', diff:1,
      q:'👟 Cada par de sapatos tem 2 sapatos. Quantos sapatos há em 7 pares?',
      ans:['14'],
      material:'Multiplicação: 2 × 7.',
      solution:'2 × 7 = 14. Há 14 sapatos.',
      exp:'Tabuada do 2.' },
    { id:'2m80', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ Quanto é o dobro de 6?',
      opts:['8','10','12','14'], ans:2,
      exp:'O dobro = × 2. 2 × 6 = 12.' },

    // ----- Tabuada do 5 (10) -----
    { id:'2m81', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 1 = ___',
      ans:['5'],
      exp:'5 × 1 = 5.' },
    { id:'2m82', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ 5 × 2 = ___',
      ans:['10'],
      exp:'5 × 2 = 10.' },
    { id:'2m83', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ 5 × 3 = ___',
      ans:['15'],
      exp:'5 × 3 = 15.' },
    { id:'2m84', s:'matematica', t:'Tabuada do 5', type:'mc', diff:2,
      q:'✖️ 5 × 6 = ?',
      opts:['25','30','35','40'], ans:1,
      exp:'5 × 6 = 30.' },
    { id:'2m85', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 7 = ___',
      ans:['35'],
      exp:'5 × 7 = 35.' },
    { id:'2m86', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 8 = ___',
      ans:['40'],
      exp:'5 × 8 = 40.' },
    { id:'2m87', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 10 = ___',
      ans:['50'],
      exp:'5 × 10 = 50.' },
    { id:'2m88', s:'matematica', t:'Tabuada do 5', type:'problem', diff:1,
      q:'✋ Cada mão tem 5 dedos. Quantos dedos há em 4 mãos?',
      ans:['20'],
      material:'Multiplicação: 5 × 4.',
      solution:'5 × 4 = 20. Há 20 dedos.',
      exp:'Tabuada do 5.' },
    { id:'2m89', s:'matematica', t:'Tabuada do 5', type:'problem', diff:1,
      q:'🌟 Cada estrela vale 5 pontos. Quantos pontos valem 6 estrelas?',
      ans:['30'],
      material:'Multiplicação: 5 × 6.',
      solution:'5 × 6 = 30. Valem 30 pontos.',
      exp:'Tabuada do 5.' },
    { id:'2m90', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ Os múltiplos de 5 acabam sempre em:',
      opts:['1 ou 6','0 ou 5','2 ou 7','3 ou 8'], ans:1,
      exp:'5, 10, 15, 20… acabam em 0 ou 5.' },

    // ----- Tabuada do 10 (8) -----
    { id:'2m91', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ 10 × 1 = ___',
      ans:['10'],
      exp:'10 × 1 = 10.' },
    { id:'2m92', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 4 = ___',
      ans:['40'],
      exp:'Junta um zero ao 4 → 40.' },
    { id:'2m93', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 6 = ___',
      ans:['60'],
      exp:'10 × 6 = 60.' },
    { id:'2m94', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 9 = ?',
      opts:['80','90','99','100'], ans:1,
      exp:'10 × 9 = 90.' },
    { id:'2m95', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ 10 × 10 = ___',
      ans:['100','cem'],
      exp:'10 × 10 = 100.' },
    { id:'2m96', s:'matematica', t:'Tabuada do 10', type:'problem', diff:1,
      q:'💰 Cada caixa tem 10 moedas. Quantas moedas há em 5 caixas?',
      ans:['50'],
      material:'Multiplicação: 10 × 5.',
      solution:'10 × 5 = 50. Há 50 moedas.',
      exp:'Tabuada do 10.' },
    { id:'2m97', s:'matematica', t:'Tabuada do 10', type:'problem', diff:1,
      q:'🎈 Cada saco tem 10 balões. Quantos balões há em 7 sacos?',
      ans:['70'],
      material:'Multiplicação: 10 × 7.',
      solution:'10 × 7 = 70. Há 70 balões.',
      exp:'Tabuada do 10.' },
    { id:'2m98', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ Para multiplicar por 10:',
      opts:['somo o número','tiro um zero','junto um zero ao número','divido por 2'], ans:2,
      exp:'Junta-se um zero. 5 → 50, 8 → 80.' },

    // ----- Sólidos geométricos (8) -----
    { id:'2m99', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🎲 Um dado tem a forma de:',
      opts:['esfera','cubo','cone','cilindro'], ans:1,
      exp:'O dado é um cubo (6 faces iguais).' },
    { id:'2m100', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🍦 Um gelado de cone tem a forma de:',
      opts:['cubo','cilindro','cone','esfera'], ans:2,
      exp:'O gelado tem forma de cone (ponta numa extremidade).' },
    { id:'2m101', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🥫 Uma lata de conserva tem a forma de:',
      opts:['cubo','cilindro','esfera','pirâmide'], ans:1,
      exp:'A lata é um cilindro.' },
    { id:'2m102', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'📦 Uma caixa de sapatos tem a forma de:',
      opts:['cubo','paralelepípedo','cilindro','cone'], ans:1,
      exp:'A caixa de sapatos é um paralelepípedo.' },
    { id:'2m103', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:2,
      q:'⚽ A bola de futebol é uma esfera.',
      ans:true,
      exp:'A bola tem forma de esfera.' },
    { id:'2m104', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🔺 Qual destes sólidos tem uma ponta?',
      opts:['cubo','esfera','cone','cilindro'], ans:2,
      exp:'O cone tem uma ponta (vértice).' },
    { id:'2m105', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:2,
      q:'🎲 Quantas faces tem um cubo? ___',
      ans:['6','seis'],
      exp:'O cubo tem 6 faces (todas quadradas).' },
    { id:'2m106', s:'matematica', t:'Sólidos geométricos', type:'match', diff:1,
      q:'Associa o objeto ao sólido:',
      pairs:[['🎲 dado','cubo'],['⚽ bola','esfera'],['🥫 lata','cilindro'],['🍦 gelado','cone']],
      exp:'Cada objeto do dia-a-dia tem uma forma geométrica.' },

    // ----- Figuras planas (10) -----
    { id:'2m107', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'⬜ Quantos lados tem um quadrado?',
      opts:['3','4','5','6'], ans:1,
      exp:'O quadrado tem 4 lados iguais.' },
    { id:'2m108', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🔵 Qual destas figuras NÃO tem lados rectos?',
      opts:['triângulo','quadrado','círculo','retângulo'], ans:2,
      exp:'O círculo é redondo, sem lados rectos.' },
    { id:'2m109', s:'matematica', t:'Figuras planas', type:'fill', diff:2,
      q:'🔺 Quantos lados tem um triângulo? ___',
      ans:['3','três','tres'],
      exp:'O triângulo tem 3 lados.' },
    { id:'2m110', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🟦 Uma figura com 4 lados (2 grandes e 2 pequenos) é um:',
      opts:['quadrado','triângulo','retângulo','círculo'], ans:2,
      exp:'O retângulo tem 4 lados, 2 a 2 iguais.' },
    { id:'2m111', s:'matematica', t:'Figuras planas', type:'tf', diff:2,
      q:'⬜ O quadrado tem todos os lados iguais.',
      ans:true,
      exp:'Sim, o quadrado tem 4 lados iguais.' },
    { id:'2m112', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🔺 Quantos vértices (cantos) tem um triângulo?',
      opts:['2','3','4','5'], ans:1,
      exp:'O triângulo tem 3 vértices.' },
    { id:'2m113', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'⬜ Quantos vértices tem um quadrado? ___',
      ans:['4','quatro'],
      exp:'O quadrado tem 4 vértices.' },
    { id:'2m114', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🚸 Que forma tem o sinal de stop (forma da placa)?',
      opts:['quadrado','triângulo','octógono','círculo'], ans:2,
      exp:'O sinal de stop é um octógono (8 lados).' },
    { id:'2m115', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🌞 Que forma tem a Lua cheia?',
      opts:['quadrado','triângulo','retângulo','círculo'], ans:3,
      exp:'A Lua cheia parece um círculo.' },
    { id:'2m116', s:'matematica', t:'Figuras planas', type:'match', diff:1,
      q:'Associa cada figura ao seu nome:',
      pairs:[['🔺','triângulo'],['⬜','quadrado'],['🔵','círculo'],['🟦','retângulo']],
      exp:'Cada figura tem um nome próprio.' },

    // ----- Medir tempo (10) -----
    { id:'2m117', s:'matematica', t:'Medir tempo', type:'fill', diff:2,
      q:'⏰ Quantas horas tem um dia? ___',
      ans:['24','vinte e quatro'],
      exp:'1 dia = 24 horas.' },
    { id:'2m118', s:'matematica', t:'Medir tempo', type:'fill', diff:2,
      q:'📅 Quantos meses tem um ano? ___',
      ans:['12','doze'],
      exp:'1 ano = 12 meses.' },
    { id:'2m119', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'📅 Qual é o primeiro mês do ano?',
      opts:['Dezembro','Janeiro','Março','Junho'], ans:1,
      exp:'O ano começa em Janeiro.' },
    { id:'2m120', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Qual é o último mês do ano?',
      opts:['Outubro','Novembro','Dezembro','Janeiro'], ans:2,
      exp:'O ano termina em Dezembro.' },
    { id:'2m121', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'⏱️ Quantos segundos tem um minuto? ___',
      ans:['60','sessenta'],
      exp:'1 minuto = 60 segundos.' },
    { id:'2m122', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Quantos dias tem o mês de Fevereiro (ano normal)?',
      opts:['28','29','30','31'], ans:0,
      exp:'Fevereiro tem 28 dias (29 em ano bissexto).' },
    { id:'2m123', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 Quantas estações tem o ano? ___',
      ans:['4','quatro'],
      exp:'4 estações: primavera, verão, outono e inverno.' },
    { id:'2m124', s:'matematica', t:'Medir tempo', type:'order', diff:1,
      q:'Ordena os meses (do primeiro ao último):',
      items:['Janeiro','Abril','Julho','Outubro'],
      exp:'Janeiro (1), Abril (4), Julho (7), Outubro (10).' },
    { id:'2m125', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'⏰ Quantas horas tem meio dia?',
      opts:['6','12','24','30'], ans:1,
      exp:'Meio dia = 12 horas.' },
    { id:'2m126', s:'matematica', t:'Medir tempo', type:'match', diff:1,
      q:'Associa o tempo à medida:',
      pairs:[['1 hora','60 minutos'],['1 dia','24 horas'],['1 semana','7 dias'],['1 ano','12 meses']],
      exp:'Medidas de tempo principais.' },

    // ----- Dinheiro (€) (12) -----
    { id:'2m127', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 Quantos cêntimos tem 1 euro? ___',
      ans:['100','cem'],
      exp:'1€ = 100 cêntimos.' },
    { id:'2m128', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💰 Qual é a moeda usada em Portugal?',
      opts:['dólar','euro','libra','peso'], ans:1,
      exp:'A moeda em Portugal é o euro (€).' },
    { id:'2m129', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:1,
      q:'🍞 Um pão custa 1€ e um leite 2€. Quanto custa o lanche?',
      ans:['3','3€','3 euros'],
      material:'Soma: 1 + 2.',
      solution:'1 + 2 = 3. O lanche custa 3€.',
      exp:'Adição com euros.' },
    { id:'2m130', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🎁 A Joana tinha 20€ e comprou uma boneca de 12€. Quanto lhe ficou?',
      ans:['8','8€','8 euros'],
      material:'Subtração: 20 − 12.',
      solution:'20 − 12 = 8. Ficou com 8€.',
      exp:'Subtração com euros.' },
    { id:'2m131', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:1,
      q:'🍬 Cada rebuçado custa 5 cêntimos. Quanto custam 4 rebuçados?',
      ans:['20','20 cêntimos','20 centimos','20c'],
      material:'Multiplicação: 5 × 4.',
      solution:'5 × 4 = 20. Custam 20 cêntimos.',
      exp:'Multiplicação com cêntimos.' },
    { id:'2m132', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Qual destas notas existe?',
      opts:['3€','5€','7€','15€'], ans:1,
      exp:'Notas: 5€, 10€, 20€, 50€, 100€, 200€, 500€.' },
    { id:'2m133', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:1,
      q:'🍎 Uma maçã custa 2€. Quanto custam 5 maçãs?',
      ans:['10','10€','10 euros'],
      material:'Multiplicação: 2 × 5.',
      solution:'2 × 5 = 10. Custam 10€.',
      exp:'Multiplicação com euros.' },
    { id:'2m134', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:1,
      q:'📚 Um livro custa 8€ e um caderno 4€. Quanto custam juntos?',
      ans:['12','12€','12 euros'],
      material:'Soma: 8 + 4.',
      solution:'8 + 4 = 12. Custam 12€.',
      exp:'Adição com euros.' },
    { id:'2m135', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 50 cêntimos + 50 cêntimos = ?',
      opts:['1€','50€','100€','5€'], ans:0,
      exp:'50 + 50 = 100 cêntimos = 1€.' },
    { id:'2m136', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:1,
      q:'🍫 Um chocolate custa 1€ e a Eduarda paga com uma nota de 5€. Quanto recebe de troco?',
      ans:['4','4€','4 euros'],
      material:'Subtração: 5 − 1.',
      solution:'5 − 1 = 4. Recebe 4€ de troco.',
      exp:'Subtração com troco.' },
    { id:'2m137', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💰 Símbolo do euro: ___',
      ans:['€','euro'],
      exp:'O símbolo do euro é €.' },
    { id:'2m138', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🎈 A Sofia comprou 3 balões a 2€ cada. Quanto pagou?',
      ans:['6','6€','6 euros'],
      material:'Multiplicação: 2 × 3.',
      solution:'2 × 3 = 6. Pagou 6€.',
      exp:'Multiplicação com euros.' },

    // ============================================================
    // ===================== ESTUDO DO MEIO =======================
    // ============================================================

    // ----- O meu corpo (10) -----
    { id:'2e15', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🦴 O que protege os nossos órgãos por dentro?',
      opts:['músculos','ossos','pele','cabelo'], ans:1,
      exp:'Os ossos formam o esqueleto e protegem os órgãos.' },
    { id:'2e16', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'❤️ Qual é o órgão que bombeia o sangue?',
      opts:['estômago','pulmões','coração','cérebro'], ans:2,
      exp:'O coração bombeia o sangue para todo o corpo.' },
    { id:'2e17', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🫁 Com que órgão respiramos?',
      opts:['estômago','pulmões','coração','rins'], ans:1,
      exp:'Os pulmões servem para respirar.' },
    { id:'2e18', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:2,
      q:'🦷 Como se chamam os ossinhos brancos da nossa boca? ___',
      ans:['dentes'],
      exp:'Os dentes servem para mastigar a comida.' },
    { id:'2e19', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:1,
      q:'🧠 O cérebro fica dentro da cabeça.',
      ans:true,
      exp:'O cérebro está protegido pelo crânio (osso da cabeça).' },
    { id:'2e20', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'💪 O que nos ajuda a mover o corpo?',
      opts:['ossos','músculos','pele','cabelo'], ans:1,
      exp:'Os músculos contraem-se para mover o corpo.' },
    { id:'2e21', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:1,
      q:'👁️ Quantos olhos temos? ___',
      ans:['2','dois'],
      exp:'Temos 2 olhos para ver.' },
    { id:'2e22', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:1,
      q:'🦴 Os bebés têm os mesmos dentes que os adultos.',
      ans:false,
      exp:'Os bebés têm dentes de leite. Depois caem e nascem os dentes definitivos.' },
    { id:'2e23', s:'estudo_meio', t:'O meu corpo', type:'match', diff:1,
      q:'Associa cada parte ao seu uso:',
      pairs:[['👁️ olhos','ver'],['👂 ouvidos','ouvir'],['👃 nariz','cheirar'],['👅 língua','provar']],
      exp:'Cada parte do corpo tem uma função.' },
    { id:'2e24', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🚶 Quais são os membros inferiores?',
      opts:['braços','pernas','dedos','ombros'], ans:1,
      exp:'Membros inferiores = pernas. Membros superiores = braços.' },

    // ----- A minha família (8) -----
    { id:'2e25', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👵 A mãe da minha mãe é a minha:',
      opts:['tia','avó','prima','madrinha'], ans:1,
      exp:'A mãe da mãe (ou do pai) é a avó.' },
    { id:'2e26', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👴 O pai do meu pai é o meu:',
      opts:['tio','primo','avô','padrinho'], ans:2,
      exp:'O pai do pai (ou da mãe) é o avô.' },
    { id:'2e27', s:'estudo_meio', t:'A minha família', type:'fill', diff:1,
      q:'👧 O filho do meu tio é o meu ___.',
      ans:['primo'],
      exp:'Os filhos dos tios são os primos.' },
    { id:'2e28', s:'estudo_meio', t:'A minha família', type:'tf', diff:1,
      q:'👨‍👩‍👧 A família alargada inclui os avós, tios e primos.',
      ans:true,
      exp:'A família alargada vai além dos pais e irmãos.' },
    { id:'2e29', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'🧒 A irmã da minha mãe é a minha:',
      opts:['avó','tia','prima','madrinha'], ans:1,
      exp:'Irmã da mãe (ou do pai) = tia.' },
    { id:'2e30', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👨‍👩‍👧‍👦 A família nuclear é formada por:',
      opts:['avós e tios','pais e irmãos','vizinhos','colegas'], ans:1,
      exp:'A família nuclear são os pais e irmãos.' },
    { id:'2e31', s:'estudo_meio', t:'A minha família', type:'fill', diff:2,
      q:'👶 Os filhos dos meus avós são os meus pais e os meus ___.',
      ans:['tios'],
      exp:'Os filhos dos avós são os pais e os tios.' },
    { id:'2e32', s:'estudo_meio', t:'A minha família', type:'tf', diff:1,
      q:'👨 O marido da minha tia é também meu tio.',
      ans:true,
      exp:'O marido da tia é tio (por casamento).' },

    // ----- A escola (6) -----
    { id:'2e33', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🏫 Quem ensina na escola?',
      opts:['médico','professor','padeiro','bombeiro'], ans:1,
      exp:'O professor ensina os alunos.' },
    { id:'2e34', s:'estudo_meio', t:'A escola', type:'tf', diff:1,
      q:'📚 Devemos cuidar dos nossos materiais escolares.',
      ans:true,
      exp:'Cuidar dos materiais é importante e mostra responsabilidade.' },
    { id:'2e35', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🍽️ Onde almoçamos na escola?',
      opts:['na sala de aula','no recreio','no refeitório','no ginásio'], ans:2,
      exp:'No refeitório (cantina) é onde se come.' },
    { id:'2e36', s:'estudo_meio', t:'A escola', type:'tf', diff:1,
      q:'⏰ Devemos chegar a horas à escola.',
      ans:true,
      exp:'Pontualidade é uma regra importante.' },
    { id:'2e37', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🏫 Quem ajuda a manter a escola limpa?',
      opts:['professores','funcionários','alunos','médicos'], ans:1,
      exp:'Os funcionários (auxiliares) ajudam a manter a escola limpa.' },
    { id:'2e38', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🧒 Como devemos tratar os colegas?',
      opts:['com violência','com respeito','com gritos','com indiferença'], ans:1,
      exp:'Devemos tratar todos com respeito e amizade.' },

    // ----- Animais (14) -----
    { id:'2e39', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐄 A vaca é um animal:',
      opts:['ovíparo','vivíparo','aquático','réptil'], ans:1,
      exp:'A vaca é vivípara (nasce da mãe).' },
    { id:'2e40', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐔 A galinha é um animal:',
      opts:['ovíparo','vivíparo','mamífero','peixe'], ans:0,
      exp:'A galinha põe ovos → ovíparo.' },
    { id:'2e41', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐶 O cão é um mamífero.',
      ans:true,
      exp:'O cão é mamífero (a mãe amamenta as crias).' },
    { id:'2e42', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🦋 A borboleta é um:',
      opts:['mamífero','réptil','inseto','peixe'], ans:2,
      exp:'A borboleta tem 6 patas → é um inseto.' },
    { id:'2e43', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐑 Animais que comem só plantas chamam-se:',
      opts:['carnívoros','herbívoros','omnívoros','insectívoros'], ans:1,
      exp:'Herbívoros comem só plantas. Ex: vaca, ovelha, coelho.' },
    { id:'2e44', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🦁 Animais que comem só carne chamam-se:',
      opts:['herbívoros','carnívoros','omnívoros','frugívoros'], ans:1,
      exp:'Carnívoros comem só carne. Ex: leão, lobo.' },
    { id:'2e45', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐍 As cobras são répteis.',
      ans:true,
      exp:'As cobras são répteis (corpo coberto por escamas).' },
    { id:'2e46', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐦 As aves têm o corpo coberto por:',
      opts:['pelo','escamas','penas','pele lisa'], ans:2,
      exp:'As aves têm penas.' },
    { id:'2e47', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐢 A tartaruga é um:',
      opts:['mamífero','peixe','réptil','anfíbio'], ans:2,
      exp:'A tartaruga é réptil.' },
    { id:'2e48', s:'estudo_meio', t:'Animais', type:'fill', diff:1,
      q:'🐰 Quantas patas tem o coelho? ___',
      ans:['4','quatro'],
      exp:'O coelho tem 4 patas.' },
    { id:'2e49', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐟 Os peixes vivem na:',
      opts:['terra','água','árvore','areia'], ans:1,
      exp:'Os peixes vivem na água.' },
    { id:'2e50', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐝 A abelha é um inseto.',
      ans:true,
      exp:'A abelha é um inseto (6 patas).' },
    { id:'2e51', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐷 Animais que comem plantas e carne chamam-se:',
      opts:['herbívoros','carnívoros','omnívoros','aquáticos'], ans:2,
      exp:'Omnívoros comem plantas e carne. Ex: porco, humano.' },
    { id:'2e52', s:'estudo_meio', t:'Animais', type:'match', diff:1,
      q:'Associa cada animal ao seu grupo:',
      pairs:[['🐶 cão','mamífero'],['🐔 galinha','ave'],['🐟 truta','peixe'],['🦋 borboleta','inseto']],
      exp:'Os animais classificam-se em grupos.' },

    // ----- Plantas (10) -----
    { id:'2e53', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'🌳 Qual é a parte da planta que aguenta o peso e leva a seiva?',
      opts:['raiz','caule','folha','flor'], ans:1,
      exp:'O caule sustenta a planta e leva a seiva.' },
    { id:'2e54', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌷 De onde nasce o fruto da planta?',
      opts:['raiz','caule','flor','folha'], ans:2,
      exp:'A flor transforma-se em fruto.' },
    { id:'2e55', s:'estudo_meio', t:'Plantas', type:'fill', diff:2,
      q:'💧 As plantas precisam de ___ , luz e ar para viver.',
      ans:['água','agua'],
      exp:'A água é essencial à vida das plantas.' },
    { id:'2e56', s:'estudo_meio', t:'Plantas', type:'tf', diff:1,
      q:'🌳 As árvores são plantas.',
      ans:true,
      exp:'As árvores são plantas grandes com tronco lenhoso.' },
    { id:'2e57', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🍎 A maçã é um:',
      opts:['vegetal','fruto','flor','folha'], ans:1,
      exp:'A maçã é um fruto da macieira.' },
    { id:'2e58', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🥬 Qual destes alimentos vem da raiz?',
      opts:['maçã','cenoura','tomate','laranja'], ans:1,
      exp:'A cenoura é uma raiz comestível.' },
    { id:'2e59', s:'estudo_meio', t:'Plantas', type:'tf', diff:1,
      q:'🌻 Todas as plantas têm flores.',
      ans:false,
      exp:'Algumas plantas não têm flores (ex: musgo, fetos).' },
    { id:'2e60', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌱 Onde fica a raiz de uma planta?',
      opts:['no ar','na água','dentro da terra','nas folhas'], ans:2,
      exp:'A raiz fica dentro da terra e absorve a água.' },
    { id:'2e61', s:'estudo_meio', t:'Plantas', type:'match', diff:1,
      q:'Associa cada parte da planta à sua função:',
      pairs:[['🌱 raiz','absorve a água'],['🌳 caule','sustenta a planta'],['🍃 folha','faz alimento'],['🌸 flor','dá origem ao fruto']],
      exp:'Cada parte da planta tem uma função.' },
    { id:'2e62', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🍐 A pera é um fruto. Onde cresce?',
      opts:['na raiz','na pereira','no chão','no caule'], ans:1,
      exp:'A pera cresce na pereira (árvore).' },

    // ----- Estações do ano (10) -----
    { id:'2e63', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'🌸 Em que estação as flores nascem em maior quantidade?',
      opts:['Primavera','Verão','Outono','Inverno'], ans:0,
      exp:'A Primavera é a estação das flores.' },
    { id:'2e64', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'❄️ Qual é a estação mais fria?',
      opts:['Primavera','Verão','Outono','Inverno'], ans:3,
      exp:'O Inverno é a estação mais fria.' },
    { id:'2e65', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:1,
      q:'🍂 A estação em que as folhas caem é o ___.',
      ans:['outono','Outono'],
      exp:'No Outono, as folhas mudam de cor e caem.' },
    { id:'2e66', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:1,
      q:'☀️ No verão usamos roupa quente.',
      ans:false,
      exp:'No verão usamos roupa fresca porque está calor.' },
    { id:'2e67', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌧️ Em que estação chove mais?',
      opts:['Verão','Inverno','Primavera','não há diferença'], ans:1,
      exp:'No Inverno chove mais e está mais frio.' },
    { id:'2e68', s:'estudo_meio', t:'Estações do ano', type:'order', diff:1,
      q:'Ordena as estações pela ordem normal do ano:',
      items:['Primavera','Verão','Outono','Inverno'],
      exp:'Primavera → Verão → Outono → Inverno.' },
    { id:'2e69', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'❄️ Em que mês começa o Inverno?',
      opts:['Setembro','Dezembro','Março','Junho'], ans:1,
      exp:'O Inverno começa em Dezembro.' },
    { id:'2e70', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌷 Em que mês começa a Primavera?',
      opts:['Janeiro','Março','Junho','Setembro'], ans:1,
      exp:'A Primavera começa em Março.' },
    { id:'2e71', s:'estudo_meio', t:'Estações do ano', type:'match', diff:1,
      q:'Associa cada estação a uma característica:',
      pairs:[['🌸 Primavera','flores'],['☀️ Verão','calor'],['🍂 Outono','folhas caem'],['❄️ Inverno','frio']],
      exp:'Cada estação tem características próprias.' },
    { id:'2e72', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:1,
      q:'☀️ A estação mais quente é o ___.',
      ans:['verão','Verão','verao'],
      exp:'No verão está calor.' },

    // ----- Os sentidos (8) -----
    { id:'2e73', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👁️ Com que sentido vemos as cores?',
      opts:['audição','visão','olfato','tato'], ans:1,
      exp:'A visão é o sentido dos olhos.' },
    { id:'2e74', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👃 Com que sentido cheiramos uma flor?',
      opts:['olfato','paladar','tato','visão'], ans:0,
      exp:'O olfato é o sentido do nariz (cheiro).' },
    { id:'2e75', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👅 Com que sentido provamos a comida?',
      opts:['visão','olfato','paladar','tato'], ans:2,
      exp:'O paladar é o sentido da língua (saborear).' },
    { id:'2e76', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'✋ Com que sentido sabemos se algo é macio ou áspero?',
      opts:['visão','tato','olfato','audição'], ans:1,
      exp:'O tato é o sentido da pele (tocar).' },
    { id:'2e77', s:'estudo_meio', t:'Os sentidos', type:'match', diff:1,
      q:'Associa cada sentido ao órgão:',
      pairs:[['visão','👁️ olhos'],['audição','👂 ouvidos'],['olfato','👃 nariz'],['paladar','👅 língua']],
      exp:'Cada sentido tem um órgão próprio.' },
    { id:'2e78', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:1,
      q:'👂 Ouvimos os sons com os ouvidos.',
      ans:true,
      exp:'A audição é o sentido dos ouvidos.' },
    { id:'2e79', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'✋ A pele é o órgão do sentido:',
      opts:['paladar','tato','visão','audição'], ans:1,
      exp:'O tato faz-se através da pele.' },
    { id:'2e80', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'👁️👂👃👅✋ Quantos sentidos temos? ___',
      ans:['5','cinco'],
      exp:'5 sentidos: visão, audição, olfato, paladar e tato.' },

    // ----- Profissões (10) -----
    { id:'2e81', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🚒 Quem apaga os incêndios?',
      opts:['médico','bombeiro','professor','padeiro'], ans:1,
      exp:'O bombeiro apaga incêndios e ajuda em emergências.' },
    { id:'2e82', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🍞 Quem faz o pão?',
      opts:['cozinheiro','padeiro','professor','médico'], ans:1,
      exp:'O padeiro trabalha na padaria a fazer pão.' },
    { id:'2e83', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🚜 Quem cultiva os alimentos no campo?',
      opts:['carpinteiro','agricultor','médico','bombeiro'], ans:1,
      exp:'O agricultor cultiva e cuida das plantas no campo.' },
    { id:'2e84', s:'estudo_meio', t:'Profissões', type:'fill', diff:1,
      q:'👨‍🏫 Quem ensina os alunos? O ___.',
      ans:['professor','professora'],
      exp:'O professor ensina na escola.' },
    { id:'2e85', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🐶 Quem trata dos animais doentes?',
      opts:['médico','veterinário','jardineiro','pintor'], ans:1,
      exp:'O veterinário cuida dos animais.' },
    { id:'2e86', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🚓 Quem ajuda a manter a ordem nas ruas?',
      opts:['polícia','médico','padeiro','professor'], ans:0,
      exp:'A polícia mantém a segurança e ajuda as pessoas.' },
    { id:'2e87', s:'estudo_meio', t:'Profissões', type:'match', diff:1,
      q:'Associa cada profissão à sua ferramenta:',
      pairs:[['👨‍⚕️ Médico','💉 estetoscópio'],['👨‍🍳 Cozinheiro','🍳 frigideira'],['👨‍🚒 Bombeiro','🚒 mangueira'],['👨‍🌾 Agricultor','🚜 trator']],
      exp:'Cada profissão usa instrumentos próprios.' },
    { id:'2e88', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🛠️ Quem faz e arranja móveis de madeira?',
      opts:['eletricista','carpinteiro','pintor','canalizador'], ans:1,
      exp:'O carpinteiro trabalha com madeira.' },
    { id:'2e89', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'💌 Quem entrega as cartas e encomendas?',
      opts:['carteiro','jornalista','motorista','padeiro'], ans:0,
      exp:'O carteiro entrega as cartas.' },
    { id:'2e90', s:'estudo_meio', t:'Profissões', type:'fill', diff:1,
      q:'✂️ Quem corta o cabelo? O ___.',
      ans:['cabeleireiro','barbeiro'],
      exp:'O cabeleireiro corta e arranja o cabelo.' },

    // ----- Portugal (12) -----
    { id:'2e91', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🇵🇹 Em que continente fica Portugal?',
      opts:['África','América','Europa','Ásia'], ans:2,
      exp:'Portugal fica na Europa.' },
    { id:'2e92', s:'estudo_meio', t:'Portugal', type:'fill', diff:1,
      q:'🏛️ A capital de Portugal é ___.',
      ans:['Lisboa','lisboa'],
      exp:'Lisboa é a capital.' },
    { id:'2e93', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌊 Que oceano banha Portugal?',
      opts:['Pacífico','Atlântico','Índico','Ártico'], ans:1,
      exp:'Portugal é banhado pelo oceano Atlântico.' },
    { id:'2e94', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🏞️ Qual é o maior rio de Portugal?',
      opts:['Douro','Tejo','Mondego','Guadiana'], ans:1,
      exp:'O Tejo é o maior rio de Portugal.' },
    { id:'2e95', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌍 Quais são os arquipélagos portugueses?',
      opts:['Açores e Madeira','Canárias e Madeira','Açores e Canárias','Cabo Verde e Açores'], ans:0,
      exp:'Portugal tem 2 arquipélagos: Açores e Madeira.' },
    { id:'2e96', s:'estudo_meio', t:'Portugal', type:'tf', diff:1,
      q:'🇵🇹 A bandeira de Portugal tem as cores verde e vermelho.',
      ans:true,
      exp:'A bandeira é verde e vermelha, com o brasão.' },
    { id:'2e97', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🗣️ Qual é a língua oficial de Portugal?',
      opts:['espanhol','francês','português','inglês'], ans:2,
      exp:'A língua oficial é o português.' },
    { id:'2e98', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌆 Qual destas é uma cidade portuguesa?',
      opts:['Madrid','Porto','Roma','Paris'], ans:1,
      exp:'Porto é a 2.ª maior cidade de Portugal.' },
    { id:'2e99', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🏰 Que país faz fronteira com Portugal?',
      opts:['França','Espanha','Itália','Inglaterra'], ans:1,
      exp:'Portugal faz fronteira só com Espanha (a leste).' },
    { id:'2e100', s:'estudo_meio', t:'Portugal', type:'fill', diff:1,
      q:'🌊 O rio Douro passa na cidade do ___.',
      ans:['Porto','porto'],
      exp:'O rio Douro passa no Porto.' },
    { id:'2e101', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🇵🇹 Como se chama o Hino Nacional de Portugal?',
      opts:['A Marselhesa','A Portuguesa','O Hino','A Bandeira'], ans:1,
      exp:'O hino chama-se "A Portuguesa".' },
    { id:'2e102', s:'estudo_meio', t:'Portugal', type:'match', diff:1,
      q:'Associa cada cidade à sua característica:',
      pairs:[['Lisboa','capital'],['Porto','rio Douro'],['Coimbra','universidade'],['Faro','Algarve']],
      exp:'Cidades portuguesas e características.' },

    // ============================================================
    // ===================== INGLÊS ===============================
    // ============================================================

    // ----- Cores (10) -----
    { id:'2i19', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🟡 Que cor é esta em inglês?',
      opts:['yellow','blue','green'], ans:0,
      exp:'🟡 = yellow (amarelo).' },
    { id:'2i20', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'⚫ Que cor é esta em inglês?',
      opts:['white','red','black'], ans:2,
      exp:'⚫ = black (preto).' },
    { id:'2i21', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'⚪ Que cor é esta em inglês?',
      opts:['white','black','pink'], ans:0,
      exp:'⚪ = white (branco).' },
    { id:'2i22', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🟠 Que cor é esta em inglês?',
      opts:['yellow','orange','red'], ans:1,
      exp:'🟠 = orange (laranja).' },
    { id:'2i23', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🟣 Que cor é esta em inglês?',
      opts:['purple','pink','blue'], ans:0,
      exp:'🟣 = purple (roxo).' },
    { id:'2i24', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🟤 Que cor é esta em inglês?',
      opts:['black','brown','red'], ans:1,
      exp:'🟤 = brown (castanho).' },
    { id:'2i25', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🍓 Um morango é vermelho. Em inglês, vermelho é:',
      opts:['blue','red','green'], ans:1,
      exp:'vermelho = red.' },
    { id:'2i26', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌳 Uma árvore é verde. Em inglês, verde é:',
      opts:['green','yellow','blue'], ans:0,
      exp:'verde = green.' },
    { id:'2i27', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌊 O mar é azul. Em inglês, azul é:',
      opts:['black','blue','brown'], ans:1,
      exp:'azul = blue.' },
    { id:'2i28', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🍌 Uma banana é amarela. Em inglês, amarelo é:',
      opts:['yellow','orange','white'], ans:0,
      exp:'amarelo = yellow.' },

    // ----- Números (10) -----
    { id:'2i29', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🤟 Quantos dedos? Em inglês:',
      opts:['two','three','four'], ans:1,
      exp:'🤟 = 3 = three.' },
    { id:'2i30', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'✋ Quantos dedos? Em inglês:',
      opts:['four','five','six'], ans:1,
      exp:'✋ = 5 = five.' },
    { id:'2i31', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'⭐⭐⭐⭐ Quantas estrelas? Em inglês:',
      opts:['three','four','five'], ans:1,
      exp:'⭐⭐⭐⭐ = 4 = four.' },
    { id:'2i32', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🍎🍎🍎🍎🍎🍎 Quantas maçãs? Em inglês:',
      opts:['five','six','seven'], ans:1,
      exp:'6 maçãs = six.' },
    { id:'2i33', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🐶🐶🐶🐶🐶🐶🐶 Quantos cães? Em inglês:',
      opts:['six','seven','eight'], ans:1,
      exp:'7 cães = seven.' },
    { id:'2i34', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🐱🐱🐱🐱🐱🐱🐱🐱 Quantos gatos? Em inglês:',
      opts:['seven','eight','nine'], ans:1,
      exp:'8 gatos = eight.' },
    { id:'2i35', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🍪🍪🍪🍪🍪🍪🍪🍪🍪 Quantas bolachas? Em inglês:',
      opts:['eight','nine','ten'], ans:1,
      exp:'9 bolachas = nine.' },
    { id:'2i36', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔟 Em inglês, o número 10 diz-se:',
      opts:['ten','six','two'], ans:0,
      exp:'10 = ten.' },
    { id:'2i37', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🍎 Quantas maçãs? Em inglês:',
      opts:['one','two','three'], ans:0,
      exp:'1 maçã = one.' },
    { id:'2i38', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🐱🐱 Quantos gatos? Em inglês:',
      opts:['one','two','three'], ans:1,
      exp:'2 gatos = two.' },

    // ----- Animais (12) -----
    { id:'2i39', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐴 Que animal é em inglês?',
      opts:['horse','cow','pig'], ans:0,
      exp:'🐴 = horse (cavalo).' },
    { id:'2i40', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐦 Que animal é em inglês?',
      opts:['fish','bird','rabbit'], ans:1,
      exp:'🐦 = bird (pássaro).' },
    { id:'2i41', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐮 Que animal é em inglês?',
      opts:['horse','cow','pig'], ans:1,
      exp:'🐮 = cow (vaca).' },
    { id:'2i42', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐷 Que animal é em inglês?',
      opts:['cow','dog','pig'], ans:2,
      exp:'🐷 = pig (porco).' },
    { id:'2i43', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🦁 Que animal é em inglês?',
      opts:['lion','tiger','bear'], ans:0,
      exp:'🦁 = lion (leão).' },
    { id:'2i44', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐘 Que animal é em inglês?',
      opts:['horse','elephant','cow'], ans:1,
      exp:'🐘 = elephant (elefante).' },
    { id:'2i45', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐭 Que animal é em inglês?',
      opts:['mouse','cat','rabbit'], ans:0,
      exp:'🐭 = mouse (rato).' },
    { id:'2i46', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐔 Que animal é em inglês?',
      opts:['duck','hen','bird'], ans:1,
      exp:'🐔 = hen (galinha).' },
    { id:'2i47', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🦆 Que animal é em inglês?',
      opts:['duck','bird','hen'], ans:0,
      exp:'🦆 = duck (pato).' },
    { id:'2i48', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐻 Que animal é em inglês?',
      opts:['lion','bear','dog'], ans:1,
      exp:'🐻 = bear (urso).' },
    { id:'2i49', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐶 O cão diz "ladrar". O cão em inglês é:',
      opts:['cat','dog','fish'], ans:1,
      exp:'cão = dog.' },
    { id:'2i50', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐱 O gato faz "miau". O gato em inglês é:',
      opts:['dog','cat','rabbit'], ans:1,
      exp:'gato = cat.' },

    // ----- Família (10) -----
    { id:'2i51', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👦 O teu irmão em inglês é:',
      opts:['sister','brother','dad'], ans:1,
      exp:'irmão = brother.' },
    { id:'2i52', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👵 A tua avó em inglês é:',
      opts:['grandma','grandpa','mum'], ans:0,
      exp:'avó = grandma (também "grandmother").' },
    { id:'2i53', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👴 O teu avô em inglês é:',
      opts:['grandma','grandpa','dad'], ans:1,
      exp:'avô = grandpa (também "grandfather").' },
    { id:'2i54', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👶 O bebé em inglês é:',
      opts:['baby','boy','girl'], ans:0,
      exp:'bebé = baby.' },
    { id:'2i55', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👧 A menina em inglês é:',
      opts:['boy','girl','baby'], ans:1,
      exp:'menina = girl.' },
    { id:'2i56', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👦 O menino em inglês é:',
      opts:['girl','boy','baby'], ans:1,
      exp:'menino = boy.' },
    { id:'2i57', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👨‍👩‍👧 A tua família em inglês é:',
      opts:['family','friend','school'], ans:0,
      exp:'família = family.' },
    { id:'2i58', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👨 O irmão da tua mãe (tio) em inglês é:',
      opts:['uncle','aunt','cousin'], ans:0,
      exp:'tio = uncle.' },
    { id:'2i59', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👩 A irmã do teu pai (tia) em inglês é:',
      opts:['uncle','aunt','sister'], ans:1,
      exp:'tia = aunt.' },
    { id:'2i60', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👨 O teu pai em inglês também se diz:',
      opts:['mother','father','brother'], ans:1,
      exp:'pai = dad ou father.' },

    // ----- Cumprimentos (10) -----
    { id:'2i61', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'👋 Para dizer "Olá" em inglês:',
      opts:['Hello','Bye','Sorry'], ans:0,
      exp:'Olá = Hello (também "Hi").' },
    { id:'2i62', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'👋 Para dizer "Adeus" em inglês:',
      opts:['Hello','Bye','Please'], ans:1,
      exp:'Adeus = Bye (também "Goodbye").' },
    { id:'2i63', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'☀️ "Boa tarde" em inglês:',
      opts:['Good morning','Good afternoon','Good night'], ans:1,
      exp:'Boa tarde = Good afternoon.' },
    { id:'2i64', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🙏 Para pedir algo com educação dizes:',
      opts:['Sorry','Please','Hello'], ans:1,
      exp:'Por favor = Please.' },
    { id:'2i65', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'😔 Para pedir desculpa dizes:',
      opts:['Sorry','Thank you','Please'], ans:0,
      exp:'Desculpa = Sorry.' },
    { id:'2i66', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'😊 Quando te perguntam "How are you?" podes responder:',
      opts:['I am fine','Goodbye','Hello'], ans:0,
      exp:'How are you? = Como estás? Resposta: I am fine (estou bem).' },
    { id:'2i67', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🌅 De manhã cumprimentamos com:',
      opts:['Good morning','Good night','Bye'], ans:0,
      exp:'Bom dia = Good morning.' },
    { id:'2i68', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🤝 Quando conheces alguém novo podes dizer:',
      opts:['Bye','Nice to meet you','Sorry'], ans:1,
      exp:'Prazer em conhecer-te = Nice to meet you.' },
    { id:'2i69', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🎂 No teu aniversário dizem-te:',
      opts:['Happy Birthday','Good night','Sorry'], ans:0,
      exp:'Feliz aniversário = Happy Birthday.' },
    { id:'2i70', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'❓ "What is your name?" significa:',
      opts:['Como te chamas?','Quantos anos tens?','Estás bem?'], ans:0,
      exp:'What is your name? = Como te chamas?' }

];
if (typeof window !== 'undefined') window.EXERCISES_2_EXTRA = EXERCISES_2_EXTRA;
