// EscolaPlay - Banco de exercicios 5.º ano
// Tipos: mc (escolha multipla), tf (v/f), fill (preencher), order (ordenar), match (associar)
// Estrutura: { id, s (disciplina), t (topico), type, diff (1-3), q (pergunta), ..., exp (explicacao) }

const SUBJECTS = {
    portugues:   { name: 'Portugues',   icon: 'fa-book',         color: '#e11d48' },
    matematica:  { name: 'Matematica',  icon: 'fa-calculator',   color: '#2563eb' },
    ingles:      { name: 'Ingles',      icon: 'fa-language',     color: '#16a34a' },
    ciencias:    { name: 'Ciencias',    icon: 'fa-leaf',         color: '#0891b2' },
    historia:    { name: 'Historia',    icon: 'fa-landmark',     color: '#b45309' },
    geografia:   { name: 'Geografia',   icon: 'fa-earth-europe', color: '#7c3aed' }
};

const EXERCISES = [
    // ========== PORTUGUES ==========
    { id:'p1', s:'portugues', t:'Classes de palavras', type:'mc', diff:1, q:'Qual destas palavras e um nome?', opts:['correr','bonito','cao','rapidamente'], ans:2, exp:'"Cao" e um nome (substantivo). "Correr" e verbo, "bonito" e adjetivo, "rapidamente" e adverbio.' },
    { id:'p2', s:'portugues', t:'Classes de palavras', type:'mc', diff:1, q:'Na frase "A menina esta feliz", a palavra "feliz" e um...', opts:['nome','adjetivo','verbo','adverbio'], ans:1, exp:'Adjetivo qualifica o nome ("menina feliz").' },
    { id:'p3', s:'portugues', t:'Verbos', type:'mc', diff:2, q:'Qual e o tempo verbal da forma "comeu"?', opts:['presente do indicativo','preterito perfeito do indicativo','preterito imperfeito do indicativo','futuro do indicativo'], ans:1, exp:'"Comeu" indica uma accao concluida no passado -> preterito perfeito.' },
    { id:'p4', s:'portugues', t:'Verbos', type:'mc', diff:2, q:'Na frase "Nos iremos a praia", o verbo esta no...', opts:['presente','preterito perfeito','preterito imperfeito','futuro'], ans:3, exp:'"Iremos" = futuro do indicativo.' },
    { id:'p5', s:'portugues', t:'Funcoes sintaticas', type:'mc', diff:2, q:'Na frase "O Joao comprou um livro", qual e o sujeito?', opts:['comprou','um livro','O Joao','livro'], ans:2, exp:'O sujeito e quem pratica a accao: "O Joao".' },
    { id:'p6', s:'portugues', t:'Funcoes sintaticas', type:'mc', diff:2, q:'Na frase "A Maria ofereceu flores a avo", "flores" e...', opts:['sujeito','complemento directo','complemento indirecto','predicado'], ans:1, exp:'Responde a "o que ofereceu?" -> complemento directo.' },
    { id:'p7', s:'portugues', t:'Recursos expressivos', type:'mc', diff:2, q:'"O tempo voa" e um exemplo de:', opts:['comparacao','metafora','personificacao','enumeracao'], ans:2, exp:'Dar accoes humanas ("voar") a algo nao humano (o tempo) = personificacao.' },
    { id:'p8', s:'portugues', t:'Recursos expressivos', type:'mc', diff:1, q:'"Ela e rapida como o vento" e um exemplo de:', opts:['metafora','comparacao','personificacao','onomatopeia'], ans:1, exp:'Usa "como" a comparar duas coisas -> comparacao.' },
    { id:'p9', s:'portugues', t:'Ortografia', type:'tf', diff:1, q:'A palavra "excecao" escreve-se com "cc".', ans:false, exp:'Escreve-se "excecao" (c).' },
    { id:'p10', s:'portugues', t:'Pontuacao', type:'mc', diff:1, q:'Qual o sinal de pontuacao correcto no fim de uma pergunta?', opts:['.','?','!',','], ans:1, exp:'Ponto de interrogacao "?".' },
    { id:'p11', s:'portugues', t:'Plurais', type:'fill', diff:1, q:'Qual e o plural de "pao"?', ans:['paes'], exp:'Palavras terminadas em "-ao" podem fazer plural em "-oes", "-aes" ou "-aos". Pao -> paes.' },
    { id:'p12', s:'portugues', t:'Plurais', type:'fill', diff:2, q:'Qual e o plural de "animal"?', ans:['animais'], exp:'Palavras em "-al" fazem plural em "-ais": animal -> animais.' },
    { id:'p13', s:'portugues', t:'Classes de palavras', type:'mc', diff:2, q:'Na frase "Ele correu muito", a palavra "muito" e...', opts:['nome','adjetivo','adverbio','verbo'], ans:2, exp:'"Muito" modifica o verbo "correu" -> adverbio de quantidade.' },
    { id:'p14', s:'portugues', t:'Verbos', type:'fill', diff:2, q:'Conjuga o verbo "ser" na 1.a pessoa do plural do presente: "nos ___".', ans:['somos'], exp:'Presente do indicativo: eu sou, tu es, ele e, nos somos.' },
    { id:'p15', s:'portugues', t:'Tipos de texto', type:'mc', diff:1, q:'Um texto que conta uma historia e um texto:', opts:['descritivo','narrativo','argumentativo','poetico'], ans:1, exp:'Texto narrativo conta acontecimentos.' },
    { id:'p16', s:'portugues', t:'Determinantes', type:'mc', diff:2, q:'Em "A minha casa e grande", "minha" e um determinante:', opts:['artigo','possessivo','demonstrativo','indefinido'], ans:1, exp:'Indica posse -> determinante possessivo.' },
    { id:'p17', s:'portugues', t:'Pronomes', type:'mc', diff:2, q:'Na frase "Ele foi ao parque", "Ele" e um pronome:', opts:['pessoal','possessivo','demonstrativo','relativo'], ans:0, exp:'Substitui um nome proprio ou referente -> pronome pessoal.' },
    { id:'p18', s:'portugues', t:'Ortografia', type:'tf', diff:1, q:'Escreve-se "hospital" com "h" inicial.', ans:true, exp:'Correcto: hospital (com h mudo).' },
    { id:'p19', s:'portugues', t:'Recursos expressivos', type:'fill', diff:2, q:'"Zzzzz" a imitar o som do sono e um exemplo de ___.', ans:['onomatopeia','onomatopeias'], exp:'Onomatopeia = palavra que imita um som.' },
    { id:'p20', s:'portugues', t:'Funcoes sintaticas', type:'order', diff:3, q:'Ordena a frase: "livro / O / Pedro / lendo / um / esta"', items:['O','Pedro','esta','lendo','um','livro'], exp:'Sujeito + verbo + complemento.' },

    // ========== MATEMATICA ==========
    { id:'m1', s:'matematica', t:'Divisibilidade', type:'mc', diff:1, q:'Qual destes numeros e multiplo de 7?', opts:['15','21','25','30'], ans:1, exp:'21 = 7 x 3. Os outros nao sao divisiveis por 7.' },
    { id:'m2', s:'matematica', t:'Divisibilidade', type:'mc', diff:2, q:'Quais sao os divisores de 12?', opts:['1, 2, 3, 4, 6, 12','1, 2, 4, 6, 12','1, 3, 4, 12','2, 3, 4, 6'], ans:0, exp:'Divisores: 1, 2, 3, 4, 6, 12 (numeros que dividem 12 sem resto).' },
    { id:'m3', s:'matematica', t:'Numeros primos', type:'tf', diff:2, q:'O numero 9 e um numero primo.', ans:false, exp:'9 = 3 x 3, tem mais divisores alem de 1 e 9, logo nao e primo.' },
    { id:'m4', s:'matematica', t:'Numeros primos', type:'mc', diff:2, q:'Qual destes e um numero primo?', opts:['15','21','17','25'], ans:2, exp:'17 so e divisivel por 1 e por 17.' },
    { id:'m5', s:'matematica', t:'Fraccoes', type:'fill', diff:2, q:'1/2 + 1/4 = ?/4', ans:['3','3/4'], exp:'1/2 = 2/4. Logo 2/4 + 1/4 = 3/4.' },
    { id:'m6', s:'matematica', t:'Fraccoes', type:'mc', diff:2, q:'Qual fraccao e equivalente a 2/3?', opts:['4/6','3/4','2/6','4/9'], ans:0, exp:'2/3 = 4/6 (multiplicar cima e baixo por 2).' },
    { id:'m7', s:'matematica', t:'Percentagens', type:'fill', diff:2, q:'Quanto e 25% de 80?', ans:['20'], exp:'25% = 1/4. 80 : 4 = 20.' },
    { id:'m8', s:'matematica', t:'Percentagens', type:'mc', diff:2, q:'Quanto e 50% de 120?', opts:['30','50','60','120'], ans:2, exp:'50% = metade -> 120 : 2 = 60.' },
    { id:'m9', s:'matematica', t:'Potencias', type:'fill', diff:2, q:'Quanto e 2^3?', ans:['8'], exp:'2^3 = 2 x 2 x 2 = 8.' },
    { id:'m10', s:'matematica', t:'Potencias', type:'mc', diff:2, q:'Quanto e 5^2?', opts:['10','15','20','25'], ans:3, exp:'5^2 = 5 x 5 = 25.' },
    { id:'m11', s:'matematica', t:'Areas', type:'fill', diff:2, q:'Qual a area de um rectangulo com 6 cm x 4 cm?', ans:['24','24 cm2','24cm2'], exp:'Area do rectangulo = base x altura = 6 x 4 = 24 cm^2.' },
    { id:'m12', s:'matematica', t:'Areas', type:'mc', diff:2, q:'Area de um triangulo com base 10 e altura 6:', opts:['16','30','60','36'], ans:1, exp:'Area do triangulo = (base x altura) / 2 = (10 x 6)/2 = 30.' },
    { id:'m13', s:'matematica', t:'Volume', type:'mc', diff:2, q:'Volume de um cubo com aresta 3 cm:', opts:['9 cm3','18 cm3','27 cm3','36 cm3'], ans:2, exp:'Volume cubo = aresta^3 = 3^3 = 27 cm^3.' },
    { id:'m14', s:'matematica', t:'Dizimas', type:'mc', diff:2, q:'Qual e a fraccao equivalente a 0,5?', opts:['1/5','1/2','1/10','5/10'], ans:1, exp:'0,5 = 1/2 (tambem 5/10, mas 1/2 e a forma simplificada).' },
    { id:'m15', s:'matematica', t:'Dizimas', type:'fill', diff:2, q:'Escreve 3/4 como dizima.', ans:['0,75','0.75'], exp:'3 : 4 = 0,75.' },
    { id:'m16', s:'matematica', t:'Operacoes', type:'fill', diff:1, q:'Quanto e 37 + 48?', ans:['85'], exp:'37 + 48 = 85.' },
    { id:'m17', s:'matematica', t:'Operacoes', type:'fill', diff:2, q:'Quanto e 144 : 12?', ans:['12'], exp:'144 : 12 = 12.' },
    { id:'m18', s:'matematica', t:'MMC/MDC', type:'mc', diff:3, q:'Qual e o MDC de 12 e 18?', opts:['2','3','6','12'], ans:2, exp:'Divisores comuns: 1, 2, 3, 6. Maior = 6.' },
    { id:'m19', s:'matematica', t:'Sequencias', type:'fill', diff:2, q:'Proximo numero da sequencia 2, 4, 8, 16, ___', ans:['32'], exp:'Cada termo e o dobro do anterior: 16 x 2 = 32.' },
    { id:'m20', s:'matematica', t:'Estatistica', type:'fill', diff:2, q:'Qual a media de 4, 6, 8, 10?', ans:['7'], exp:'(4+6+8+10)/4 = 28/4 = 7.' },

    // ========== INGLES ==========
    { id:'i1', s:'ingles', t:'Greetings', type:'mc', diff:1, q:'How do you say "Bom dia" in English?', opts:['Good night','Good morning','Good afternoon','Good evening'], ans:1, exp:'"Good morning" = bom dia.' },
    { id:'i2', s:'ingles', t:'Greetings', type:'mc', diff:1, q:'How do you say "Adeus" in English?', opts:['Hello','Goodbye','Please','Thanks'], ans:1, exp:'"Goodbye" = adeus.' },
    { id:'i3', s:'ingles', t:'Numbers', type:'mc', diff:1, q:'How do you write 15 in English?', opts:['fifty','fifteen','five','fourteen'], ans:1, exp:'15 = fifteen. 50 = fifty.' },
    { id:'i4', s:'ingles', t:'Numbers', type:'fill', diff:1, q:'Write the number 20 in English.', ans:['twenty'], exp:'20 = twenty.' },
    { id:'i5', s:'ingles', t:'Days', type:'mc', diff:1, q:'Which day comes after Monday?', opts:['Sunday','Friday','Tuesday','Wednesday'], ans:2, exp:'Monday -> Tuesday.' },
    { id:'i6', s:'ingles', t:'Months', type:'fill', diff:1, q:'What is the first month of the year? (English)', ans:['january'], exp:'January = Janeiro.' },
    { id:'i7', s:'ingles', t:'Family', type:'mc', diff:1, q:'My mother\'s brother is my...', opts:['cousin','uncle','nephew','grandfather'], ans:1, exp:'Mother\'s brother = uncle (tio).' },
    { id:'i8', s:'ingles', t:'Family', type:'mc', diff:1, q:'"Irma" in English is:', opts:['brother','sister','cousin','aunt'], ans:1, exp:'Sister = irma.' },
    { id:'i9', s:'ingles', t:'Verb to be', type:'mc', diff:1, q:'Complete: "I ___ a student."', opts:['is','are','am','be'], ans:2, exp:'I am, you are, he/she/it is.' },
    { id:'i10', s:'ingles', t:'Verb to be', type:'mc', diff:1, q:'Complete: "They ___ happy."', opts:['is','am','are','be'], ans:2, exp:'They are happy.' },
    { id:'i11', s:'ingles', t:'Present simple', type:'mc', diff:2, q:'Complete: "She ___ English every day."', opts:['study','studies','studying','studied'], ans:1, exp:'3rd person singular adds -s/-es: she studies.' },
    { id:'i12', s:'ingles', t:'Colors', type:'fill', diff:1, q:'"Vermelho" in English:', ans:['red'], exp:'Red = vermelho.' },
    { id:'i13', s:'ingles', t:'Colors', type:'fill', diff:1, q:'"Azul" in English:', ans:['blue'], exp:'Blue = azul.' },
    { id:'i14', s:'ingles', t:'Prepositions', type:'mc', diff:2, q:'"The cat is ___ the table." (em cima)', opts:['in','on','under','between'], ans:1, exp:'On = em cima de.' },
    { id:'i15', s:'ingles', t:'Prepositions', type:'mc', diff:2, q:'"The ball is ___ the box." (dentro)', opts:['on','under','in','next to'], ans:2, exp:'In = dentro de.' },
    { id:'i16', s:'ingles', t:'Plurals', type:'mc', diff:2, q:'Plural of "child":', opts:['childs','childes','children','child'], ans:2, exp:'Irregular plural: child -> children.' },
    { id:'i17', s:'ingles', t:'Questions', type:'mc', diff:2, q:'Como se pergunta "Qual e o teu nome?"', opts:['How are you?','What is your name?','Where are you from?','How old are you?'], ans:1, exp:'What is your name? = Qual e o teu nome?' },
    { id:'i18', s:'ingles', t:'School', type:'mc', diff:1, q:'"Professor" in English:', opts:['student','teacher','principal','classmate'], ans:1, exp:'Teacher = professor.' },
    { id:'i19', s:'ingles', t:'School', type:'fill', diff:1, q:'"Livro" in English:', ans:['book'], exp:'Book = livro.' },
    { id:'i20', s:'ingles', t:'Articles', type:'mc', diff:2, q:'Complete: "I saw ___ elephant."', opts:['a','an','the','no article'], ans:1, exp:'"An" antes de vogal: an elephant.' },

    // ========== CIENCIAS ==========
    { id:'c1', s:'ciencias', t:'Seres vivos', type:'mc', diff:1, q:'Qual destes e um ser vivo?', opts:['rocha','arvore','agua','nuvem'], ans:1, exp:'Arvore e o unico que nasce, cresce, reproduz-se e morre.' },
    { id:'c2', s:'ciencias', t:'Classificacao', type:'mc', diff:2, q:'Os mamiferos sao caracterizados por:', opts:['poem ovos','tem escamas','amamentam as crias','vivem so na agua'], ans:2, exp:'A caracteristica principal dos mamiferos e amamentar as crias.' },
    { id:'c3', s:'ciencias', t:'Vertebrados', type:'mc', diff:2, q:'Qual destes animais e um reptil?', opts:['sapo','lagarto','truta','pombo'], ans:1, exp:'Lagarto = reptil. Sapo = anfibio. Truta = peixe. Pombo = ave.' },
    { id:'c4', s:'ciencias', t:'Vertebrados', type:'mc', diff:1, q:'Qual deste animais e um peixe?', opts:['golfinho','tubarao','baleia','foca'], ans:1, exp:'Tubarao e peixe (respira por branquias). Os outros sao mamiferos.' },
    { id:'c5', s:'ciencias', t:'Anfibios', type:'tf', diff:2, q:'Os anfibios vivem parte da vida na agua e parte em terra.', ans:true, exp:'Correcto. Anfibio significa "duas vidas".' },
    { id:'c6', s:'ciencias', t:'Aves', type:'mc', diff:1, q:'Qual destas caracteristicas e propria das aves?', opts:['escamas','penas','pelos','carapaca'], ans:1, exp:'Aves tem o corpo coberto por penas.' },
    { id:'c7', s:'ciencias', t:'Invertebrados', type:'mc', diff:2, q:'Qual destes e um invertebrado?', opts:['gato','aranha','peixe','pombo'], ans:1, exp:'Aranhas sao invertebrados (aracnideos). Os outros tem coluna vertebral.' },
    { id:'c8', s:'ciencias', t:'Alimentacao', type:'mc', diff:2, q:'Um animal que so come plantas e:', opts:['carnivoro','omnivoro','herbivoro','detritivoro'], ans:2, exp:'Herbivoro come so plantas. Carnivoro come carne. Omnivoro come ambos.' },
    { id:'c9', s:'ciencias', t:'Alimentacao', type:'mc', diff:2, q:'O ser humano e um animal:', opts:['carnivoro','herbivoro','omnivoro','detritivoro'], ans:2, exp:'O ser humano come plantas e animais -> omnivoro.' },
    { id:'c10', s:'ciencias', t:'Cadeia alimentar', type:'mc', diff:2, q:'Numa cadeia alimentar, quem esta na base?', opts:['predadores','herbivoros','produtores (plantas)','decompositores'], ans:2, exp:'As plantas (produtores) estao na base da cadeia alimentar.' },
    { id:'c11', s:'ciencias', t:'Plantas', type:'mc', diff:2, q:'Como se chama o processo pelo qual as plantas produzem alimento?', opts:['respiracao','fotossintese','transpiracao','germinacao'], ans:1, exp:'Fotossintese: plantas usam luz solar + CO2 + agua para produzir acucar.' },
    { id:'c12', s:'ciencias', t:'Plantas', type:'mc', diff:1, q:'Qual destas partes da planta absorve agua do solo?', opts:['folha','caule','flor','raiz'], ans:3, exp:'A raiz absorve agua e nutrientes do solo.' },
    { id:'c13', s:'ciencias', t:'Rochas', type:'mc', diff:2, q:'Qual destas e uma rocha sedimentar?', opts:['granito','basalto','calcario','marmore'], ans:2, exp:'Calcario e sedimentar. Granito = magmatica. Marmore = metamorfica.' },
    { id:'c14', s:'ciencias', t:'Solo', type:'tf', diff:1, q:'O solo e composto por minerais, agua, ar e materia organica.', ans:true, exp:'Correcto. Todos estes elementos fazem parte do solo.' },
    { id:'c15', s:'ciencias', t:'Agua', type:'mc', diff:2, q:'No ciclo da agua, quando a agua se transforma em vapor chama-se:', opts:['condensacao','evaporacao','precipitacao','infiltracao'], ans:1, exp:'Liquido -> gas = evaporacao.' },
    { id:'c16', s:'ciencias', t:'Agua', type:'mc', diff:2, q:'Quando o vapor de agua arrefece e forma nuvens, chama-se:', opts:['evaporacao','condensacao','solidificacao','precipitacao'], ans:1, exp:'Gas -> liquido = condensacao.' },
    { id:'c17', s:'ciencias', t:'Habitat', type:'mc', diff:1, q:'Qual e o habitat do urso polar?', opts:['deserto','floresta tropical','Artico (gelo)','savana'], ans:2, exp:'O urso polar vive no Artico, em regioes geladas.' },
    { id:'c18', s:'ciencias', t:'Ecossistema', type:'tf', diff:2, q:'Um ecossistema inclui seres vivos e o ambiente onde vivem.', ans:true, exp:'Correcto: ecossistema = biocenose (seres vivos) + biotopo (ambiente).' },
    { id:'c19', s:'ciencias', t:'Reproducao', type:'mc', diff:2, q:'Qual destes animais poe ovos?', opts:['leao','cao','galinha','cavalo'], ans:2, exp:'Galinha e ovipara (poe ovos). Os outros sao viviparos.' },
    { id:'c20', s:'ciencias', t:'Revestimento', type:'match', diff:2, q:'Associa o animal ao seu revestimento:', pairs:[['peixe','escamas'],['passaro','penas'],['cao','pelo'],['tartaruga','carapaca']], exp:'Cada grupo tem um revestimento caracteristico.' },

    // ========== HISTORIA ==========
    { id:'h1', s:'historia', t:'Pre-historia', type:'mc', diff:1, q:'O que faziam os primeiros povos da Peninsula Iberica no Paleolitico?', opts:['agricultura','caca e recoleccao','construiam castelos','navegavam'], ans:1, exp:'No Paleolitico viviam da caca, pesca e recoleccao.' },
    { id:'h2', s:'historia', t:'Romanos', type:'mc', diff:2, q:'Quando chegaram os romanos a Peninsula Iberica?', opts:['seculo I d.C.','seculo III a.C.','seculo V d.C.','seculo VIII d.C.'], ans:1, exp:'Os romanos chegaram no seculo III a.C. (218 a.C.).' },
    { id:'h3', s:'historia', t:'Romanos', type:'mc', diff:2, q:'Que legado deixaram os romanos na Peninsula?', opts:['lingua arabe','lingua latina','escrita chinesa','religiao judaica'], ans:1, exp:'O Latim deu origem ao Portugues. Tambem deixaram estradas, pontes, direito romano.' },
    { id:'h4', s:'historia', t:'Barbaros', type:'mc', diff:2, q:'Que povo barbaro se fixou na Peninsula apos queda de Roma?', opts:['vikings','visigodos','hunos','celtas'], ans:1, exp:'Os visigodos fundaram um reino na Peninsula no seculo V.' },
    { id:'h5', s:'historia', t:'Muculmanos', type:'mc', diff:2, q:'Em que ano chegaram os muculmanos a Peninsula Iberica?', opts:['711','1143','1249','1415'], ans:0, exp:'Em 711 os muculmanos chegaram e conquistaram grande parte da Peninsula.' },
    { id:'h6', s:'historia', t:'Reconquista', type:'mc', diff:2, q:'Como se chamou a luta dos cristaos para expulsar os muculmanos?', opts:['Cruzada','Reconquista','Revolucao','Invasao'], ans:1, exp:'Reconquista: luta dos reinos cristaos para recuperar os territorios.' },
    { id:'h7', s:'historia', t:'Fundacao', type:'mc', diff:1, q:'Quem foi o primeiro rei de Portugal?', opts:['D. Sancho I','D. Dinis','D. Afonso Henriques','D. Joao I'], ans:2, exp:'D. Afonso Henriques foi o primeiro rei de Portugal.' },
    { id:'h8', s:'historia', t:'Fundacao', type:'fill', diff:2, q:'Em que ano foi assinado o Tratado de Zamora, que reconheceu Portugal como reino? (so o ano)', ans:['1143'], exp:'Em 1143, entre D. Afonso Henriques e D. Afonso VII de Leao.' },
    { id:'h9', s:'historia', t:'Fundacao', type:'mc', diff:2, q:'Em 1179, que documento do Papa reconheceu Portugal?', opts:['Bula Manifestis Probatum','Tratado de Alcanices','Carta de Lei','Concilio de Niceia'], ans:0, exp:'Bula Manifestis Probatum (Papa Alexandre III, 1179).' },
    { id:'h10', s:'historia', t:'Batalhas', type:'mc', diff:2, q:'Qual foi a batalha importante que D. Afonso Henriques venceu em 1139?', opts:['Batalha de Aljubarrota','Batalha de Ourique','Batalha de Salado','Batalha de Toro'], ans:1, exp:'Batalha de Ourique (1139), apos a qual foi aclamado rei.' },
    { id:'h11', s:'historia', t:'Reconquista', type:'mc', diff:2, q:'Qual foi o ultimo territorio conquistado na Reconquista portuguesa?', opts:['Lisboa','Alentejo','Algarve','Porto'], ans:2, exp:'O Algarve foi conquistado em 1249 por D. Afonso III.' },
    { id:'h12', s:'historia', t:'Reconquista', type:'fill', diff:2, q:'Em que ano foi conquistado o Algarve? (so o ano)', ans:['1249'], exp:'1249, por D. Afonso III -> fim da Reconquista portuguesa.' },
    { id:'h13', s:'historia', t:'Reis', type:'mc', diff:2, q:'Qual destes reis ficou conhecido como "O Lavrador"?', opts:['D. Dinis','D. Sancho I','D. Afonso III','D. Fernando'], ans:0, exp:'D. Dinis (1279-1325), que promoveu a agricultura.' },
    { id:'h14', s:'historia', t:'Cultura', type:'mc', diff:2, q:'Quem fundou a primeira universidade portuguesa em 1290?', opts:['D. Sancho I','D. Afonso III','D. Dinis','D. Joao I'], ans:2, exp:'D. Dinis fundou a Universidade em Lisboa (mais tarde em Coimbra).' },
    { id:'h15', s:'historia', t:'Lisboa', type:'mc', diff:2, q:'Em que ano foi conquistada Lisboa aos muculmanos?', opts:['1128','1143','1147','1179'], ans:2, exp:'Lisboa foi conquistada em 1147 por D. Afonso Henriques.' },
    { id:'h16', s:'historia', t:'Simbolos', type:'mc', diff:1, q:'Os 5 escudetes azuis na bandeira representam:', opts:['os 5 continentes','os 5 reis mouros vencidos em Ourique','as 5 regioes','os 5 oceanos'], ans:1, exp:'Os 5 escudetes representam os 5 reis mouros vencidos na Batalha de Ourique.' },
    { id:'h17', s:'historia', t:'Dinastias', type:'mc', diff:2, q:'Como se chamou a primeira dinastia portuguesa?', opts:['Avis','Borgonha','Braganca','Filipina'], ans:1, exp:'Dinastia de Borgonha (1139-1383), iniciada por D. Afonso Henriques.' },
    { id:'h18', s:'historia', t:'Ordem cronologica', type:'order', diff:3, q:'Ordena por data (mais antigo ao mais recente):', items:['Romanos chegam a Peninsula','Muculmanos chegam a Peninsula','Fundacao de Portugal (1143)','Conquista do Algarve (1249)'], exp:'218 a.C. -> 711 -> 1143 -> 1249.' },
    { id:'h19', s:'historia', t:'Romanos', type:'tf', diff:1, q:'A cidade romana de Olissipo e a actual Lisboa.', ans:true, exp:'Correcto: Olissipo -> Lisboa.' },
    { id:'h20', s:'historia', t:'Romanos', type:'match', diff:3, q:'Associa a cidade romana ao nome actual:', pairs:[['Bracara','Braga'],['Ebora','Evora'],['Olissipo','Lisboa'],['Conimbriga','Coimbra']], exp:'Muitas cidades portuguesas tem origem romana.' },

    // ========== GEOGRAFIA ==========
    { id:'g1', s:'geografia', t:'Localizacao', type:'mc', diff:1, q:'Portugal fica em que continente?', opts:['America','Africa','Europa','Asia'], ans:2, exp:'Portugal esta localizado na Europa, na Peninsula Iberica.' },
    { id:'g2', s:'geografia', t:'Fronteiras', type:'mc', diff:1, q:'Com que pais faz Portugal fronteira terrestre?', opts:['Franca','Espanha','Italia','Marrocos'], ans:1, exp:'Portugal faz fronteira apenas com Espanha (a norte e leste).' },
    { id:'g3', s:'geografia', t:'Oceanos', type:'mc', diff:1, q:'Qual e o oceano que banha Portugal?', opts:['Pacifico','Atlantico','Indico','Artico'], ans:1, exp:'Oceano Atlantico banha a costa oeste e sul.' },
    { id:'g4', s:'geografia', t:'Ilhas', type:'mc', diff:1, q:'Quais sao as regioes autonomas de Portugal?', opts:['Algarve e Alentejo','Madeira e Acores','Lisboa e Porto','Minho e Douro'], ans:1, exp:'Madeira e Acores sao as duas regioes autonomas.' },
    { id:'g5', s:'geografia', t:'Ilhas', type:'tf', diff:2, q:'O arquipelago dos Acores tem 9 ilhas principais.', ans:true, exp:'Correcto: Sao Miguel, Santa Maria, Terceira, Graciosa, Sao Jorge, Pico, Faial, Flores, Corvo.' },
    { id:'g6', s:'geografia', t:'Rios', type:'mc', diff:2, q:'Qual e o maior rio portugues (em extensao em Portugal)?', opts:['Douro','Tejo','Mondego','Guadiana'], ans:1, exp:'O Tejo e o maior rio que atravessa Portugal.' },
    { id:'g7', s:'geografia', t:'Rios', type:'mc', diff:2, q:'Em que cidade portuguesa desagua o rio Douro?', opts:['Lisboa','Faro','Porto','Coimbra'], ans:2, exp:'O Douro desagua no Porto.' },
    { id:'g8', s:'geografia', t:'Rios', type:'mc', diff:2, q:'Em que cidade desagua o rio Tejo?', opts:['Porto','Lisboa','Faro','Coimbra'], ans:1, exp:'O Tejo desagua em Lisboa.' },
    { id:'g9', s:'geografia', t:'Relevo', type:'mc', diff:2, q:'Qual e o ponto mais alto de Portugal continental?', opts:['Serra da Estrela','Pico do Arieiro','Montejunto','Serra do Geres'], ans:0, exp:'Serra da Estrela (Torre - 1993 m). Pico (Acores) e o mais alto do pais (2351 m).' },
    { id:'g10', s:'geografia', t:'Relevo', type:'fill', diff:2, q:'Como se chama o ponto mais alto de Portugal (na ilha do Pico)?', ans:['pico','montanha do pico','pico montanha'], exp:'Montanha do Pico - 2351 m, na ilha do Pico (Acores).' },
    { id:'g11', s:'geografia', t:'Capitais', type:'mc', diff:1, q:'Qual e a capital de Portugal?', opts:['Porto','Lisboa','Coimbra','Faro'], ans:1, exp:'Lisboa e a capital.' },
    { id:'g12', s:'geografia', t:'Distritos', type:'fill', diff:2, q:'Quantos distritos tem Portugal continental?', ans:['18'], exp:'Portugal continental tem 18 distritos.' },
    { id:'g13', s:'geografia', t:'Clima', type:'mc', diff:2, q:'Que tipo de clima predomina em Portugal?', opts:['tropical','mediterranico','polar','desertico'], ans:1, exp:'Clima mediterranico: invernos suaves e chuvosos, veroes quentes e secos.' },
    { id:'g14', s:'geografia', t:'Europa', type:'mc', diff:2, q:'Quantos paises fazem fronteira com Espanha?', opts:['2','3','4','5'], ans:3, exp:'Portugal, Franca, Andorra, Marrocos (por via maritima, mas na Ceuta/Melilla).' },
    { id:'g15', s:'geografia', t:'Continentes', type:'mc', diff:1, q:'Quantos continentes existem?', opts:['5','6','7','8'], ans:2, exp:'7 continentes: Africa, America do Norte, America do Sul, Antartida, Asia, Europa, Oceania.' },
    { id:'g16', s:'geografia', t:'Europa', type:'mc', diff:2, q:'Qual e o pais mais populoso da Europa?', opts:['Franca','Alemanha','Reino Unido','Italia'], ans:1, exp:'Alemanha tem cerca de 84 milhoes de habitantes.' },
    { id:'g17', s:'geografia', t:'Europa', type:'mc', diff:2, q:'Qual e a capital de Espanha?', opts:['Barcelona','Sevilha','Madrid','Valencia'], ans:2, exp:'Madrid e a capital de Espanha.' },
    { id:'g18', s:'geografia', t:'Pontos cardeais', type:'match', diff:2, q:'Associa o ponto cardeal a sua localizacao relativa em Portugal:', pairs:[['Norte','Minho'],['Sul','Algarve'],['Este','Beira Interior (fronteira Espanha)'],['Oeste','Oceano Atlantico']], exp:'Pontos cardeais localizam regioes relativamente ao centro.' },
    { id:'g19', s:'geografia', t:'Clima', type:'tf', diff:2, q:'O clima do Algarve e geralmente mais quente e seco que o do Minho.', ans:true, exp:'Correcto: o Algarve (sul) e mais quente e seco; o Minho (noroeste) e mais chuvoso.' },
    { id:'g20', s:'geografia', t:'Fronteiras', type:'order', diff:2, q:'Ordena os rios de norte para sul (em Portugal continental):', items:['Minho','Douro','Tejo','Guadiana'], exp:'Minho (fronteira norte) -> Douro -> Tejo -> Guadiana (fronteira sul).' }
];

// Expor globalmente
window.SUBJECTS = SUBJECTS;
window.EXERCISES = EXERCISES;
