// EscolaPlay - Top-up extra do 2.º ano - Inglês (gerado, A1- CEFR, AE 2018)
const EXERCISES_2_I_EXTRA2 = [

    // ================== CORES (36) ==================
    { id:'2ie1', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is the sun? ☀️',
      opts:['blue','yellow','green','black'], ans:1,
      exp:'O sol é amarelo (yellow).' },
    { id:'2ie2', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is grass? 🌱',
      opts:['red','green','pink','grey'], ans:1,
      exp:'A relva é verde (green).' },
    { id:'2ie3', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is the sea? 🌊',
      opts:['blue','brown','yellow','white'], ans:0,
      exp:'O mar é azul (blue).' },
    { id:'2ie4', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is a tomato? 🍅',
      opts:['green','blue','red','black'], ans:2,
      exp:'O tomate é vermelho (red).' },
    { id:'2ie5', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is snow? ❄️',
      opts:['white','black','grey','brown'], ans:0,
      exp:'A neve é branca (white).' },
    { id:'2ie6', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is a banana? 🍌',
      opts:['red','yellow','blue','pink'], ans:1,
      exp:'A banana é amarela (yellow).' },
    { id:'2ie7', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is an orange? 🍊',
      opts:['orange','purple','green','grey'], ans:0,
      exp:'A laranja é cor de laranja (orange).' },
    { id:'2ie8', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 "Cor-de-rosa" em inglês é:',
      opts:['pink','purple','red','brown'], ans:0,
      exp:'cor-de-rosa = pink.' },
    { id:'2ie9', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 "Castanho" em inglês é:',
      opts:['black','brown','grey','blue'], ans:1,
      exp:'castanho = brown.' },
    { id:'2ie10', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 "Cinzento" em inglês é:',
      opts:['grey','green','gold','pink'], ans:0,
      exp:'cinzento = grey (também escrito gray).' },
    { id:'2ie11', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 "Roxo" em inglês é:',
      opts:['purple','pink','blue','orange'], ans:0,
      exp:'roxo = purple.' },
    { id:'2ie12', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is the night sky? 🌙',
      opts:['white','yellow','black','pink'], ans:2,
      exp:'O céu à noite é preto (black).' },
    { id:'2ie13', s:'ingles', t:'Cores', type:'fill', diff:1,
      q:'Completa: "The apple is ___." 🍎',
      ans:['red','Red'],
      exp:'A maçã é vermelha = red.' },
    { id:'2ie14', s:'ingles', t:'Cores', type:'fill', diff:1,
      q:'Completa: "The grass is ___." 🌱',
      ans:['green','Green'],
      exp:'A relva é verde = green.' },
    { id:'2ie15', s:'ingles', t:'Cores', type:'fill', diff:1,
      q:'Completa: "The sky is ___." ☁️',
      ans:['blue','Blue'],
      exp:'O céu é azul = blue.' },
    { id:'2ie16', s:'ingles', t:'Cores', type:'fill', diff:1,
      q:'Completa: "Pigs are usually ___." 🐷',
      ans:['pink','Pink'],
      exp:'Os porcos são geralmente cor-de-rosa (pink).' },
    { id:'2ie17', s:'ingles', t:'Cores', type:'tf', diff:2,
      q:'A palavra "white" significa "branco". ⬜',
      ans:true,
      exp:'Sim, white = branco.' },
    { id:'2ie18', s:'ingles', t:'Cores', type:'tf', diff:2,
      q:'A palavra "black" significa "azul". ⬛',
      ans:false,
      exp:'Errado: black = preto. Azul = blue.' },
    { id:'2ie19', s:'ingles', t:'Cores', type:'tf', diff:2,
      q:'A palavra "yellow" significa "amarelo". 💛',
      ans:true,
      exp:'Certo: yellow = amarelo.' },
    { id:'2ie20', s:'ingles', t:'Cores', type:'match', diff:1,
      q:'Liga as cores ao português:',
      pairs:[['red','vermelho'],['blue','azul'],['green','verde'],['yellow','amarelo']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'red=vermelho, blue=azul, green=verde, yellow=amarelo.' },
    { id:'2ie21', s:'ingles', t:'Cores', type:'match', diff:1,
      q:'Liga as cores ao português:',
      pairs:[['black','preto'],['white','branco'],['brown','castanho'],['pink','cor-de-rosa']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'black=preto, white=branco, brown=castanho, pink=cor-de-rosa.' },
    { id:'2ie22', s:'ingles', t:'Cores', type:'match', diff:1,
      q:'Liga as cores ao português:',
      pairs:[['orange','laranja'],['purple','roxo'],['grey','cinzento']],
      ans:[[0,0],[1,1],[2,2]],
      exp:'orange=laranja, purple=roxo, grey=cinzento.' },
    { id:'2ie23', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is milk? 🥛',
      opts:['black','white','green','red'], ans:1,
      exp:'O leite é branco (white).' },
    { id:'2ie24', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is a strawberry? 🍓',
      opts:['blue','red','green','grey'], ans:1,
      exp:'O morango é vermelho (red).' },
    { id:'2ie25', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is a frog? 🐸',
      opts:['green','red','black','yellow'], ans:0,
      exp:'A rã é verde (green).' },
    { id:'2ie26', s:'ingles', t:'Cores', type:'mc', diff:2,
      q:'🌈 What color do you get mixing red and blue?',
      opts:['green','purple','orange','pink'], ans:1,
      exp:'Vermelho + azul = roxo (purple).' },
    { id:'2ie27', s:'ingles', t:'Cores', type:'mc', diff:2,
      q:'🌈 What color do you get mixing yellow and red?',
      opts:['orange','green','blue','black'], ans:0,
      exp:'Amarelo + vermelho = laranja (orange).' },
    { id:'2ie28', s:'ingles', t:'Cores', type:'mc', diff:2,
      q:'🌈 What color do you get mixing yellow and blue?',
      opts:['green','purple','pink','brown'], ans:0,
      exp:'Amarelo + azul = verde (green).' },
    { id:'2ie29', s:'ingles', t:'Cores', type:'fill', diff:1,
      q:'Completa: "The lemon is ___." 🍋',
      ans:['yellow','Yellow'],
      exp:'O limão é amarelo = yellow.' },
    { id:'2ie30', s:'ingles', t:'Cores', type:'fill', diff:1,
      q:'Completa: "Chocolate is ___." 🍫',
      ans:['brown','Brown'],
      exp:'O chocolate é castanho = brown.' },
    { id:'2ie31', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is a carrot? 🥕',
      opts:['orange','purple','pink','blue'], ans:0,
      exp:'A cenoura é cor de laranja (orange).' },
    { id:'2ie32', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 What color is a polar bear? 🐻‍❄️',
      opts:['black','white','brown','grey'], ans:1,
      exp:'O urso polar é branco (white).' },
    { id:'2ie33', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 "Dourado" em inglês é:',
      opts:['gold','silver','bronze','grey'], ans:0,
      exp:'dourado = gold.' },
    { id:'2ie34', s:'ingles', t:'Cores', type:'mc', diff:1,
      q:'🌈 "Prateado" em inglês é:',
      opts:['silver','gold','grey','white'], ans:0,
      exp:'prateado = silver.' },
    { id:'2ie35', s:'ingles', t:'Cores', type:'tf', diff:2,
      q:'A palavra "green" significa "verde". 🟢',
      ans:true,
      exp:'Certo: green = verde.' },
    { id:'2ie36', s:'ingles', t:'Cores', type:'mc', diff:2,
      q:'🌈 "My favourite colour is ___" significa:',
      opts:['A minha cor favorita é','Eu gosto de cor','Tenho uma cor'], ans:0,
      exp:'My favourite colour is = A minha cor favorita é.' },

    // ================== NÚMEROS (36) ==================
    { id:'2ie37', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "1" em inglês é:',
      opts:['one','two','three','four'], ans:0,
      exp:'1 = one.' },
    { id:'2ie38', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "2" em inglês é:',
      opts:['one','two','three','five'], ans:1,
      exp:'2 = two.' },
    { id:'2ie39', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "3" em inglês é:',
      opts:['four','three','two','six'], ans:1,
      exp:'3 = three.' },
    { id:'2ie40', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "4" em inglês é:',
      opts:['five','four','six','three'], ans:1,
      exp:'4 = four.' },
    { id:'2ie41', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "5" em inglês é:',
      opts:['five','four','nine','one'], ans:0,
      exp:'5 = five.' },
    { id:'2ie42', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "6" em inglês é:',
      opts:['seven','six','sixteen','sixty'], ans:1,
      exp:'6 = six.' },
    { id:'2ie43', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "7" em inglês é:',
      opts:['seven','six','eight','three'], ans:0,
      exp:'7 = seven.' },
    { id:'2ie44', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "8" em inglês é:',
      opts:['eight','nine','seven','six'], ans:0,
      exp:'8 = eight.' },
    { id:'2ie45', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "9" em inglês é:',
      opts:['ten','nine','eight','five'], ans:1,
      exp:'9 = nine.' },
    { id:'2ie46', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "10" em inglês é:',
      opts:['ten','one','two','twelve'], ans:0,
      exp:'10 = ten.' },
    { id:'2ie47', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "11" em inglês é:',
      opts:['eleven','twelve','ten','one'], ans:0,
      exp:'11 = eleven.' },
    { id:'2ie48', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "12" em inglês é:',
      opts:['twelve','eleven','ten','twenty'], ans:0,
      exp:'12 = twelve.' },
    { id:'2ie49', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "13" em inglês é:',
      opts:['thirty','thirteen','three','third'], ans:1,
      exp:'13 = thirteen.' },
    { id:'2ie50', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "15" em inglês é:',
      opts:['fifteen','fifty','five','fifth'], ans:0,
      exp:'15 = fifteen.' },
    { id:'2ie51', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "20" em inglês é:',
      opts:['twelve','twenty','two','ten'], ans:1,
      exp:'20 = twenty.' },
    { id:'2ie52', s:'ingles', t:'Números', type:'fill', diff:1,
      q:'Completa: "1, 2, ___" (em inglês)',
      ans:['three','Three'],
      exp:'1=one, 2=two, 3=three.' },
    { id:'2ie53', s:'ingles', t:'Números', type:'fill', diff:1,
      q:'Completa: "8, 9, ___" (em inglês)',
      ans:['ten','Ten'],
      exp:'8=eight, 9=nine, 10=ten.' },
    { id:'2ie54', s:'ingles', t:'Números', type:'fill', diff:2,
      q:'Completa: "How old are you? I am ___ (7) years old." 🎂',
      ans:['seven','Seven'],
      exp:'7 anos = seven years old.' },
    { id:'2ie55', s:'ingles', t:'Números', type:'fill', diff:1,
      q:'Completa: "4 + 1 = ___" (em inglês)',
      ans:['five','Five'],
      exp:'4+1=5 = five.' },
    { id:'2ie56', s:'ingles', t:'Números', type:'tf', diff:2,
      q:'"five" significa 5. ✋',
      ans:true,
      exp:'Certo: five = 5.' },
    { id:'2ie57', s:'ingles', t:'Números', type:'tf', diff:2,
      q:'"eight" significa 9.',
      ans:false,
      exp:'Errado: eight = 8. nine = 9.' },
    { id:'2ie58', s:'ingles', t:'Números', type:'tf', diff:2,
      q:'"twelve" significa 12.',
      ans:true,
      exp:'Certo: twelve = 12.' },
    { id:'2ie59', s:'ingles', t:'Números', type:'match', diff:1,
      q:'Liga os números:',
      pairs:[['one','1'],['two','2'],['three','3'],['four','4']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'one=1, two=2, three=3, four=4.' },
    { id:'2ie60', s:'ingles', t:'Números', type:'match', diff:1,
      q:'Liga os números:',
      pairs:[['five','5'],['six','6'],['seven','7'],['eight','8']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'five=5, six=6, seven=7, eight=8.' },
    { id:'2ie61', s:'ingles', t:'Números', type:'match', diff:1,
      q:'Liga os números:',
      pairs:[['nine','9'],['ten','10'],['eleven','11'],['twelve','12']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'nine=9, ten=10, eleven=11, twelve=12.' },
    { id:'2ie62', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "14" em inglês é:',
      opts:['fourteen','forty','four','fourth'], ans:0,
      exp:'14 = fourteen.' },
    { id:'2ie63', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "16" em inglês é:',
      opts:['sixteen','sixty','six','seventeen'], ans:0,
      exp:'16 = sixteen.' },
    { id:'2ie64', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "17" em inglês é:',
      opts:['seventeen','seventy','seven','sixteen'], ans:0,
      exp:'17 = seventeen.' },
    { id:'2ie65', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "18" em inglês é:',
      opts:['eighteen','eighty','eight','eleven'], ans:0,
      exp:'18 = eighteen.' },
    { id:'2ie66', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "19" em inglês é:',
      opts:['nineteen','ninety','nine','ninetheen'], ans:0,
      exp:'19 = nineteen.' },
    { id:'2ie67', s:'ingles', t:'Números', type:'mc', diff:2,
      q:'🔢 How many fingers do you have on one hand? ✋',
      opts:['three','five','ten','two'], ans:1,
      exp:'Numa mão tens 5 dedos = five.' },
    { id:'2ie68', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 How many eyes do you have? 👀',
      opts:['one','two','three','four'], ans:1,
      exp:'Tens 2 olhos = two.' },
    { id:'2ie69', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "2 + 2" in English is:',
      opts:['three','four','five','six'], ans:1,
      exp:'2+2=4 = four.' },
    { id:'2ie70', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "5 + 5" in English is:',
      opts:['nine','ten','eleven','twelve'], ans:1,
      exp:'5+5=10 = ten.' },
    { id:'2ie71', s:'ingles', t:'Números', type:'mc', diff:1,
      q:'🔢 "10 - 4" in English is:',
      opts:['five','six','seven','four'], ans:1,
      exp:'10-4=6 = six.' },
    { id:'2ie72', s:'ingles', t:'Números', type:'fill', diff:1,
      q:'Completa: "5, 6, ___" (em inglês)',
      ans:['seven','Seven'],
      exp:'5=five, 6=six, 7=seven.' },

    // ================== ANIMAIS (34) ==================
    { id:'2ie73', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐶 "Cão" em inglês é:',
      opts:['cat','dog','cow','pig'], ans:1,
      exp:'cão = dog.' },
    { id:'2ie74', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐱 "Gato" em inglês é:',
      opts:['cat','dog','rat','bat'], ans:0,
      exp:'gato = cat.' },
    { id:'2ie75', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐦 "Pássaro" em inglês é:',
      opts:['fish','bird','frog','bear'], ans:1,
      exp:'pássaro = bird.' },
    { id:'2ie76', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐟 "Peixe" em inglês é:',
      opts:['fish','dish','wish','fox'], ans:0,
      exp:'peixe = fish.' },
    { id:'2ie77', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐰 "Coelho" em inglês é:',
      opts:['rabbit','mouse','horse','cow'], ans:0,
      exp:'coelho = rabbit.' },
    { id:'2ie78', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐴 "Cavalo" em inglês é:',
      opts:['house','horse','mouse','cow'], ans:1,
      exp:'cavalo = horse.' },
    { id:'2ie79', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐮 "Vaca" em inglês é:',
      opts:['cat','cow','dog','duck'], ans:1,
      exp:'vaca = cow.' },
    { id:'2ie80', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐷 "Porco" em inglês é:',
      opts:['pig','dog','duck','frog'], ans:0,
      exp:'porco = pig.' },
    { id:'2ie81', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐑 "Ovelha" em inglês é:',
      opts:['ship','sheep','cheap','goat'], ans:1,
      exp:'ovelha = sheep.' },
    { id:'2ie82', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐔 "Galinha" em inglês é:',
      opts:['chicken','duck','bird','horse'], ans:0,
      exp:'galinha = chicken.' },
    { id:'2ie83', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🦆 "Pato" em inglês é:',
      opts:['duck','dog','dock','deer'], ans:0,
      exp:'pato = duck.' },
    { id:'2ie84', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐭 "Rato" em inglês é:',
      opts:['mouse','house','horse','moose'], ans:0,
      exp:'rato = mouse.' },
    { id:'2ie85', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🦁 "Leão" em inglês é:',
      opts:['tiger','lion','bear','wolf'], ans:1,
      exp:'leão = lion.' },
    { id:'2ie86', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐘 "Elefante" em inglês é:',
      opts:['elephant','elefant','elephand','elephont'], ans:0,
      exp:'elefante = elephant.' },
    { id:'2ie87', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐵 "Macaco" em inglês é:',
      opts:['donkey','monkey','money','monk'], ans:1,
      exp:'macaco = monkey.' },
    { id:'2ie88', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐍 "Cobra" em inglês é:',
      opts:['snail','snake','spider','shark'], ans:1,
      exp:'cobra = snake.' },
    { id:'2ie89', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐸 "Rã" em inglês é:',
      opts:['frog','dog','fog','log'], ans:0,
      exp:'rã = frog.' },
    { id:'2ie90', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐢 "Tartaruga" em inglês é:',
      opts:['turtle','turkey','tiger','toad'], ans:0,
      exp:'tartaruga = turtle.' },
    { id:'2ie91', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐻 "Urso" em inglês é:',
      opts:['beer','bear','bird','boar'], ans:1,
      exp:'urso = bear.' },
    { id:'2ie92', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐯 "Tigre" em inglês é:',
      opts:['tiger','tigger','tiguer','tigar'], ans:0,
      exp:'tigre = tiger.' },
    { id:'2ie93', s:'ingles', t:'Animais', type:'fill', diff:1,
      q:'Completa: "The ___ says woof!" 🐶',
      ans:['dog','Dog'],
      exp:'O cão diz woof. dog = cão.' },
    { id:'2ie94', s:'ingles', t:'Animais', type:'fill', diff:1,
      q:'Completa: "The ___ says meow!" 🐱',
      ans:['cat','Cat'],
      exp:'O gato diz meow. cat = gato.' },
    { id:'2ie95', s:'ingles', t:'Animais', type:'fill', diff:1,
      q:'Completa: "The ___ says moo!" 🐮',
      ans:['cow','Cow'],
      exp:'A vaca diz moo. cow = vaca.' },
    { id:'2ie96', s:'ingles', t:'Animais', type:'fill', diff:1,
      q:'Completa: "The ___ says quack!" 🦆',
      ans:['duck','Duck'],
      exp:'O pato diz quack. duck = pato.' },
    { id:'2ie97', s:'ingles', t:'Animais', type:'tf', diff:2,
      q:'A palavra "fish" significa "peixe". 🐟',
      ans:true,
      exp:'Certo: fish = peixe.' },
    { id:'2ie98', s:'ingles', t:'Animais', type:'tf', diff:2,
      q:'A palavra "horse" significa "vaca".',
      ans:false,
      exp:'Errado: horse = cavalo. Vaca = cow.' },
    { id:'2ie99', s:'ingles', t:'Animais', type:'tf', diff:2,
      q:'A palavra "elephant" significa "elefante". 🐘',
      ans:true,
      exp:'Certo: elephant = elefante.' },
    { id:'2ie100', s:'ingles', t:'Animais', type:'match', diff:1,
      q:'Liga os animais:',
      pairs:[['dog','cão'],['cat','gato'],['bird','pássaro'],['fish','peixe']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'dog=cão, cat=gato, bird=pássaro, fish=peixe.' },
    { id:'2ie101', s:'ingles', t:'Animais', type:'match', diff:1,
      q:'Liga os animais:',
      pairs:[['cow','vaca'],['pig','porco'],['horse','cavalo'],['sheep','ovelha']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'cow=vaca, pig=porco, horse=cavalo, sheep=ovelha.' },
    { id:'2ie102', s:'ingles', t:'Animais', type:'match', diff:1,
      q:'Liga os animais:',
      pairs:[['lion','leão'],['monkey','macaco'],['snake','cobra'],['bear','urso']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'lion=leão, monkey=macaco, snake=cobra, bear=urso.' },
    { id:'2ie103', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🦒 "Girafa" em inglês é:',
      opts:['giraffe','girafa','jiraffe','giraf'], ans:0,
      exp:'girafa = giraffe.' },
    { id:'2ie104', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🦓 "Zebra" em inglês é:',
      opts:['zebra','sebra','zibra','zebrah'], ans:0,
      exp:'zebra = zebra.' },
    { id:'2ie105', s:'ingles', t:'Animais', type:'mc', diff:1,
      q:'🐧 "Pinguim" em inglês é:',
      opts:['penguin','pinguin','penguim','pengun'], ans:0,
      exp:'pinguim = penguin.' },
    { id:'2ie106', s:'ingles', t:'Animais', type:'mc', diff:2,
      q:'🐑 Plural irregular: o plural de "sheep" é:',
      opts:['sheeps','sheep','sheepes','shep'], ans:1,
      exp:'O plural de sheep é sheep (igual no singular e no plural).' },

    // ================== FAMÍLIA (37) ==================
    { id:'2ie107', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👩 "Mãe" em inglês é:',
      opts:['mother','father','sister','daughter'], ans:0,
      exp:'mãe = mother (também mum, mom).' },
    { id:'2ie108', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👨 "Pai" em inglês é:',
      opts:['mother','father','brother','son'], ans:1,
      exp:'pai = father (também dad).' },
    { id:'2ie109', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👦 "Irmão" em inglês é:',
      opts:['sister','brother','baby','son'], ans:1,
      exp:'irmão = brother.' },
    { id:'2ie110', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👧 "Irmã" em inglês é:',
      opts:['sister','brother','mother','daughter'], ans:0,
      exp:'irmã = sister.' },
    { id:'2ie111', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👶 "Bebé" em inglês é:',
      opts:['boy','girl','baby','kid'], ans:2,
      exp:'bebé = baby.' },
    { id:'2ie112', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👵 "Avó" em inglês é:',
      opts:['grandma','grandpa','mother','aunt'], ans:0,
      exp:'avó = grandma (também grandmother).' },
    { id:'2ie113', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👴 "Avô" em inglês é:',
      opts:['grandma','grandpa','father','uncle'], ans:1,
      exp:'avô = grandpa (também grandfather).' },
    { id:'2ie114', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👦 "Filho" em inglês é:',
      opts:['son','sun','daughter','boy'], ans:0,
      exp:'filho = son.' },
    { id:'2ie115', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👧 "Filha" em inglês é:',
      opts:['son','daughter','sister','baby'], ans:1,
      exp:'filha = daughter.' },
    { id:'2ie116', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👨‍👩‍👧 "Família" em inglês é:',
      opts:['family','friend','famous','farm'], ans:0,
      exp:'família = family.' },
    { id:'2ie117', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'👩 Outra forma carinhosa para "mother" é:',
      opts:['dad','mum','sis','bro'], ans:1,
      exp:'mum = mãe (informal). Também "mom" no inglês americano.' },
    { id:'2ie118', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'👨 Outra forma carinhosa para "father" é:',
      opts:['dad','mum','son','bro'], ans:0,
      exp:'dad = pai (informal).' },
    { id:'2ie119', s:'ingles', t:'Família', type:'fill', diff:1,
      q:'Completa: "My ___ is a woman." (Mãe) 👩',
      ans:['mother','Mother','mum','Mum'],
      exp:'mãe = mother (ou mum).' },
    { id:'2ie120', s:'ingles', t:'Família', type:'fill', diff:1,
      q:'Completa: "My ___ is a man." (Pai) 👨',
      ans:['father','Father','dad','Dad'],
      exp:'pai = father (ou dad).' },
    { id:'2ie121', s:'ingles', t:'Família', type:'fill', diff:2,
      q:'Completa: "I have one ___ and one sister." (irmão) 👦',
      ans:['brother','Brother'],
      exp:'irmão = brother.' },
    { id:'2ie122', s:'ingles', t:'Família', type:'fill', diff:2,
      q:'Completa: "My grandma and ___ are old." 👴',
      ans:['grandpa','Grandpa','grandfather','Grandfather'],
      exp:'avô = grandpa / grandfather.' },
    { id:'2ie123', s:'ingles', t:'Família', type:'tf', diff:2,
      q:'A palavra "sister" significa "irmã". 👧',
      ans:true,
      exp:'Certo: sister = irmã.' },
    { id:'2ie124', s:'ingles', t:'Família', type:'tf', diff:2,
      q:'A palavra "brother" significa "pai".',
      ans:false,
      exp:'Errado: brother = irmão. Pai = father.' },
    { id:'2ie125', s:'ingles', t:'Família', type:'tf', diff:2,
      q:'A palavra "baby" significa "bebé". 👶',
      ans:true,
      exp:'Certo: baby = bebé.' },
    { id:'2ie126', s:'ingles', t:'Família', type:'tf', diff:2,
      q:'"grandma" significa "tia".',
      ans:false,
      exp:'Errado: grandma = avó. Tia = aunt.' },
    { id:'2ie127', s:'ingles', t:'Família', type:'match', diff:1,
      q:'Liga os membros da família:',
      pairs:[['mother','mãe'],['father','pai'],['brother','irmão'],['sister','irmã']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'mother=mãe, father=pai, brother=irmão, sister=irmã.' },
    { id:'2ie128', s:'ingles', t:'Família', type:'match', diff:1,
      q:'Liga os membros da família:',
      pairs:[['baby','bebé'],['grandma','avó'],['grandpa','avô'],['family','família']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'baby=bebé, grandma=avó, grandpa=avô, family=família.' },
    { id:'2ie129', s:'ingles', t:'Família', type:'match', diff:1,
      q:'Liga os membros da família:',
      pairs:[['son','filho'],['daughter','filha'],['uncle','tio'],['aunt','tia']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'son=filho, daughter=filha, uncle=tio, aunt=tia.' },
    { id:'2ie130', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👫 "Primo" em inglês é:',
      opts:['uncle','aunt','cousin','brother'], ans:2,
      exp:'primo = cousin.' },
    { id:'2ie131', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'❓ "Who is your mother?" significa:',
      opts:['Quem é a tua mãe?','Onde está a tua mãe?','Como é a tua mãe?'], ans:0,
      exp:'Who is your mother? = Quem é a tua mãe?' },
    { id:'2ie132', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'👨‍👩‍👧 "Parents" significa:',
      opts:['avós','pais (mãe e pai)','tios','primos'], ans:1,
      exp:'parents = pais (mãe e pai).' },
    { id:'2ie133', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'👵👴 "Grandparents" significa:',
      opts:['avós','pais','irmãos','primos'], ans:0,
      exp:'grandparents = avós.' },
    { id:'2ie134', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'👨‍👩‍👧‍👦 "I have two ___ and one sister." (irmãos)',
      opts:['brother','brothers','sister','sisters'], ans:1,
      exp:'Plural de brother = brothers.' },
    { id:'2ie135', s:'ingles', t:'Família', type:'fill', diff:2,
      q:'Completa: "My grandma is my mother\'s ___." 👵',
      ans:['mother','Mother','mom','mum'],
      exp:'A avó é a mãe da minha mãe (mother).' },
    { id:'2ie136', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👶 "Baby" no plural é:',
      opts:['babys','babies','baby','babes'], ans:1,
      exp:'Plural de baby = babies (y → ies).' },
    { id:'2ie137', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👨 "He is my ___ ." Ele é o meu pai.',
      opts:['mother','father','sister','aunt'], ans:1,
      exp:'pai = father.' },
    { id:'2ie138', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👩 "She is my ___ ." Ela é a minha mãe.',
      opts:['father','mother','brother','son'], ans:1,
      exp:'mãe = mother.' },
    { id:'2ie139', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'❤️ "I love my ___ ." (família)',
      opts:['family','friend','farm','funny'], ans:0,
      exp:'Eu amo a minha família = I love my family.' },
    { id:'2ie140', s:'ingles', t:'Família', type:'tf', diff:2,
      q:'"Grandfather" significa "avô".',
      ans:true,
      exp:'Certo: grandfather = avô.' },
    { id:'2ie141', s:'ingles', t:'Família', type:'mc', diff:1,
      q:'👦👧 "Sister" e "brother" são:',
      opts:['avós','irmãos','tios','primos'], ans:1,
      exp:'sister = irmã, brother = irmão. São irmãos.' },
    { id:'2ie142', s:'ingles', t:'Família', type:'mc', diff:2,
      q:'👨‍👩‍👧 "I have a big family." significa:',
      opts:['Tenho uma família grande.','Tenho uma família pequena.','Não tenho família.'], ans:0,
      exp:'big = grande. Tenho uma família grande.' },
    { id:'2ie143', s:'ingles', t:'Família', type:'fill', diff:2,
      q:'Completa: "My ___ is a baby." (irmã pequenina) 👶',
      ans:['sister','Sister'],
      exp:'A minha irmã é um bebé. sister = irmã.' },

    // ================== CUMPRIMENTOS (37) ==================
    { id:'2ie144', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'👋 "Olá" em inglês (formal):',
      opts:['Hello','Bye','Sorry','Please'], ans:0,
      exp:'Olá = Hello.' },
    { id:'2ie145', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'👋 "Olá" em inglês (informal, curto):',
      opts:['Hi','Bye','OK','No'], ans:0,
      exp:'Olá (informal) = Hi.' },
    { id:'2ie146', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'👋 "Adeus" em inglês:',
      opts:['Hello','Goodbye','Sorry','Thanks'], ans:1,
      exp:'Adeus = Goodbye (também Bye).' },
    { id:'2ie147', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🌅 "Bom dia" em inglês:',
      opts:['Good night','Good morning','Good afternoon','Good evening'], ans:1,
      exp:'Bom dia = Good morning.' },
    { id:'2ie148', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'☀️ "Boa tarde" em inglês:',
      opts:['Good morning','Good afternoon','Good night','Good evening'], ans:1,
      exp:'Boa tarde = Good afternoon.' },
    { id:'2ie149', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🌙 "Boa noite" (ao deitar) em inglês:',
      opts:['Good night','Good morning','Good evening','Goodbye'], ans:0,
      exp:'Boa noite (ao deitar) = Good night.' },
    { id:'2ie150', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'🌆 "Boa noite" (ao chegar/cumprimentar) em inglês:',
      opts:['Good night','Good evening','Good morning','Good afternoon'], ans:1,
      exp:'Good evening = Boa noite (cumprimento, ao final do dia).' },
    { id:'2ie151', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🙏 "Por favor" em inglês:',
      opts:['Please','Sorry','Thanks','Hello'], ans:0,
      exp:'Por favor = Please.' },
    { id:'2ie152', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🙏 "Obrigado" em inglês:',
      opts:['Sorry','Please','Thank you','You\'re welcome'], ans:2,
      exp:'Obrigado = Thank you (também Thanks).' },
    { id:'2ie153', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'😊 "De nada" em inglês:',
      opts:['Thank you','You\'re welcome','Please','Sorry'], ans:1,
      exp:'De nada = You\'re welcome.' },
    { id:'2ie154', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'😔 "Desculpa" em inglês:',
      opts:['Sorry','Thanks','Hello','OK'], ans:0,
      exp:'Desculpa = Sorry.' },
    { id:'2ie155', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🙋 "Com licença" em inglês:',
      opts:['Sorry','Excuse me','Please','Thanks'], ans:1,
      exp:'Com licença = Excuse me.' },
    { id:'2ie156', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'😊 "How are you?" significa:',
      opts:['Como estás?','Como te chamas?','Quantos anos tens?'], ans:0,
      exp:'How are you? = Como estás?' },
    { id:'2ie157', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'😊 Resposta a "How are you?":',
      opts:['I am fine, thank you','Goodbye','Sorry'], ans:0,
      exp:'I am fine, thank you = Estou bem, obrigado.' },
    { id:'2ie158', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'❓ "What is your name?" significa:',
      opts:['Como te chamas?','Onde vives?','Quantos anos tens?'], ans:0,
      exp:'What is your name? = Como te chamas?' },
    { id:'2ie159', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'😀 "My name is..." significa:',
      opts:['O meu nome é...','Eu tenho...','Eu vivo em...'], ans:0,
      exp:'My name is = O meu nome é (chamo-me).' },
    { id:'2ie160', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'🤝 "Nice to meet you" significa:',
      opts:['Prazer em conhecer-te','Adeus','Bom dia'], ans:0,
      exp:'Nice to meet you = Prazer em conhecer-te.' },
    { id:'2ie161', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'❓ "How old are you?" significa:',
      opts:['Quantos anos tens?','Como estás?','Como te chamas?'], ans:0,
      exp:'How old are you? = Quantos anos tens?' },
    { id:'2ie162', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'🎂 Resposta a "How old are you?" se tens 7 anos:',
      opts:['I am seven','I am fine','My name is seven'], ans:0,
      exp:'I am seven (years old) = Tenho sete anos.' },
    { id:'2ie163', s:'ingles', t:'Cumprimentos', type:'fill', diff:1,
      q:'Completa: "___ morning, teacher!" 🌅',
      ans:['Good','good'],
      exp:'Bom dia = Good morning.' },
    { id:'2ie164', s:'ingles', t:'Cumprimentos', type:'fill', diff:1,
      q:'Completa: "Thank ___ !" 🙏',
      ans:['you','You'],
      exp:'Obrigado = Thank you.' },
    { id:'2ie165', s:'ingles', t:'Cumprimentos', type:'fill', diff:2,
      q:'Completa: "___ night! See you tomorrow." 🌙',
      ans:['Good','good'],
      exp:'Boa noite = Good night (ao deitar).' },
    { id:'2ie166', s:'ingles', t:'Cumprimentos', type:'fill', diff:1,
      q:'Completa: "What is your ___ ?" (nome)',
      ans:['name','Name'],
      exp:'name = nome. What is your name? = Como te chamas?' },
    { id:'2ie167', s:'ingles', t:'Cumprimentos', type:'tf', diff:2,
      q:'"Hello" significa "Olá". 👋',
      ans:true,
      exp:'Certo: Hello = Olá.' },
    { id:'2ie168', s:'ingles', t:'Cumprimentos', type:'tf', diff:2,
      q:'"Bye" significa "Olá".',
      ans:false,
      exp:'Errado: Bye = Adeus. Olá = Hello.' },
    { id:'2ie169', s:'ingles', t:'Cumprimentos', type:'tf', diff:2,
      q:'"Please" significa "Por favor".',
      ans:true,
      exp:'Certo: Please = Por favor.' },
    { id:'2ie170', s:'ingles', t:'Cumprimentos', type:'match', diff:1,
      q:'Liga os cumprimentos:',
      pairs:[['Hello','Olá'],['Goodbye','Adeus'],['Please','Por favor'],['Sorry','Desculpa']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Hello=Olá, Goodbye=Adeus, Please=Por favor, Sorry=Desculpa.' },
    { id:'2ie171', s:'ingles', t:'Cumprimentos', type:'match', diff:1,
      q:'Liga os cumprimentos:',
      pairs:[['Good morning','Bom dia'],['Good afternoon','Boa tarde'],['Good night','Boa noite'],['Thank you','Obrigado']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Good morning=Bom dia, Good afternoon=Boa tarde, Good night=Boa noite, Thank you=Obrigado.' },
    { id:'2ie172', s:'ingles', t:'Cumprimentos', type:'match', diff:1,
      q:'Liga as expressões:',
      pairs:[['How are you?','Como estás?'],['What is your name?','Como te chamas?'],['Nice to meet you','Prazer em conhecer-te']],
      ans:[[0,0],[1,1],[2,2]],
      exp:'How are you?=Como estás?, What is your name?=Como te chamas?, Nice to meet you=Prazer em conhecer-te.' },
    { id:'2ie173', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🎂 "Feliz aniversário" em inglês:',
      opts:['Happy Birthday','Happy New Year','Merry Christmas','Good night'], ans:0,
      exp:'Feliz aniversário = Happy Birthday.' },
    { id:'2ie174', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🎄 "Feliz Natal" em inglês:',
      opts:['Happy Birthday','Merry Christmas','Happy Easter','Good evening'], ans:1,
      exp:'Feliz Natal = Merry Christmas.' },
    { id:'2ie175', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🎉 "Feliz Ano Novo" em inglês:',
      opts:['Happy New Year','Merry Christmas','Happy Birthday','Good night'], ans:0,
      exp:'Feliz Ano Novo = Happy New Year.' },
    { id:'2ie176', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'👋 Curto e informal para "Adeus":',
      opts:['Bye','Hello','Sorry','Please'], ans:0,
      exp:'Bye = Adeus (forma curta de Goodbye).' },
    { id:'2ie177', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'😊 "See you tomorrow!" significa:',
      opts:['Vemo-nos amanhã!','Bom dia!','Boa noite!'], ans:0,
      exp:'See you tomorrow = Vemo-nos amanhã.' },
    { id:'2ie178', s:'ingles', t:'Cumprimentos', type:'mc', diff:2,
      q:'🙏 Resposta educada quando alguém te dá algo:',
      opts:['Sorry','Thank you','Goodbye','Hello'], ans:1,
      exp:'Quando recebes algo dizes Thank you (Obrigado).' },
    { id:'2ie179', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'😊 Resposta a "Thank you":',
      opts:['You\'re welcome','Sorry','Hello','Goodbye'], ans:0,
      exp:'A resposta a "Thank you" é "You\'re welcome" (de nada).' },
    { id:'2ie180', s:'ingles', t:'Cumprimentos', type:'mc', diff:1,
      q:'🤔 "Excuse me" usa-se quando queres:',
      opts:['pedir desculpa por interromper','dizer obrigado','dizer adeus'], ans:0,
      exp:'Excuse me = Com licença / Desculpe (para interromper ou pedir atenção).' }

];
if (typeof window !== 'undefined') window.EXERCISES_2_I_EXTRA2 = EXERCISES_2_I_EXTRA2;
