// EscolaPlay - Orientadores 3.º período 2.º ano
// Banco de exercícios alinhado com Aprendizagens Essenciais (AE)
// e manuais do 2.º ano. ~150 exercícios distribuídos por 19 tópicos.
// PT-PT (Acordo Ortográfico de 1990).

const EXERCISES_2_ORIENT_P3 = [

    // ============================================================
    // ===================== MATEMÁTICA ===========================
    // ============================================================

    // ----- Números até 1000 (10) -----
    { id:'2op_n1k_1', s:'matematica', t:'Números até 1000', type:'mc', diff:1,
      q:'🔢 O número 354 lê-se:',
      opts:['Trezentos e cinquenta e quatro','Três cinco quatro','Trinta e cinco quatro','Quatro cinquenta três'], ans:0,
      exp:'354 = trezentos e cinquenta e quatro.' },
    { id:'2op_n1k_2', s:'matematica', t:'Números até 1000', type:'fill', diff:1,
      q:'🔢 Escreve o número "duzentos e oito" em algarismos.',
      ans:['208'],
      exp:'Duzentos = 200; oito unidades = 8. Sem dezenas, escrevemos 0 no lugar das dezenas. 208.' },
    { id:'2op_n1k_3', s:'matematica', t:'Números até 1000', type:'mc', diff:1,
      q:'🔢 Qual destes números é maior?',
      opts:['418','481','148','184'], ans:1,
      exp:'481 > 418 > 184 > 148. As centenas vencem; depois as dezenas.' },
    { id:'2op_n1k_4', s:'matematica', t:'Números até 1000', type:'fill', diff:2,
      q:'🔢 Decompõe: 627 = ___ centenas + ___ dezenas + ___ unidades (escreve só os 3 algarismos com espaços).',
      ans:['6 2 7'],
      exp:'627 = 6 centenas + 2 dezenas + 7 unidades.' },
    { id:'2op_n1k_5', s:'matematica', t:'Números até 1000', type:'mc', diff:2,
      q:'🔢 Em 504, o algarismo 5 vale:',
      opts:['5','50','500','5000'], ans:2,
      exp:'O 5 está nas centenas → vale 500.' },
    { id:'2op_n1k_6', s:'matematica', t:'Números até 1000', type:'fill', diff:2,
      q:'🔢 Que número está entre 399 e 401?',
      ans:['400'],
      exp:'400. Vem logo a seguir a 399 e antes de 401.' },
    { id:'2op_n1k_7', s:'matematica', t:'Números até 1000', type:'mc', diff:2,
      q:'🔢 Ordena por ordem crescente: 712, 127, 271, 172.',
      opts:['127, 172, 271, 712','712, 271, 172, 127','127, 271, 172, 712','172, 127, 271, 712'], ans:0,
      exp:'Crescente = do menor para o maior: 127 < 172 < 271 < 712.' },
    { id:'2op_n1k_8', s:'matematica', t:'Números até 1000', type:'fill', diff:3,
      q:'🔢 Arredonda 348 à dezena mais próxima.',
      ans:['350'],
      exp:'348 está mais perto de 350 do que de 340 (8 ≥ 5, sobe).' },
    { id:'2op_n1k_9', s:'matematica', t:'Números até 1000', type:'mc', diff:3,
      q:'🔢 Qual é o número anterior a 600?',
      opts:['599','601','590','690'], ans:0,
      exp:'599 vem antes de 600.' },
    { id:'2op_n1k_10', s:'matematica', t:'Números até 1000', type:'fill', diff:3,
      q:'🔢 Numa biblioteca há 4 estantes com 100 livros cada e mais 35 livros. Quantos livros há ao todo?',
      ans:['435'],
      exp:'4 × 100 = 400 livros. +35 = 435 livros.' },

    // ----- Propriedades da multiplicação (8) -----
    { id:'2op_pmul_1', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Se 4 × 6 = 24, quanto é 6 × 4?',
      opts:['24','12','30','10'], ans:0,
      exp:'A ordem dos factores não altera o produto (propriedade comutativa). 6 × 4 = 4 × 6 = 24.' },
    { id:'2op_pmul_2', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Qual o resultado de 7 × 1?',
      opts:['1','7','8','0'], ans:1,
      exp:'Qualquer número multiplicado por 1 dá o próprio número (elemento neutro). 7 × 1 = 7.' },
    { id:'2op_pmul_3', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Quanto é 9 × 0?',
      opts:['9','0','1','90'], ans:1,
      exp:'Qualquer número multiplicado por 0 dá 0 (elemento absorvente).' },
    { id:'2op_pmul_4', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:2,
      q:'✖️ Sabes que 3 × 8 = 24. Quanto é 8 × 3?',
      ans:['24'],
      exp:'8 × 3 = 3 × 8 = 24 (comutativa).' },
    { id:'2op_pmul_5', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:2,
      q:'✖️ 5 × (2 × 3) = ?',
      opts:['30','15','25','11'], ans:0,
      exp:'(2 × 3) = 6. Depois 5 × 6 = 30. Podes também fazer (5×2)×3 = 10×3 = 30 (associativa).' },
    { id:'2op_pmul_6', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:2,
      q:'✖️ Completa: 6 × (4 + 2) = (6 × 4) + (6 × ___).',
      ans:['2'],
      exp:'Distributiva: a × (b + c) = (a × b) + (a × c). Aqui, c = 2.' },
    { id:'2op_pmul_7', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:3,
      q:'✖️ Calcula 7 × 12 separando: 7 × 12 = 7 × 10 + 7 × 2 = ?',
      opts:['72','84','70','94'], ans:1,
      exp:'7 × 10 = 70; 7 × 2 = 14. 70 + 14 = 84. Usei a propriedade distributiva.' },
    { id:'2op_pmul_8', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:3,
      q:'✖️ Calcula 8 × 25 mentalmente usando 8 × 25 = 8 × (20 + 5).',
      ans:['200'],
      exp:'8 × 20 = 160; 8 × 5 = 40. 160 + 40 = 200.' },

    // ----- Relação multiplicação e divisão (8) -----
    { id:'2op_rmd_1', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:1,
      q:'➗ Se 5 × 6 = 30, então 30 ÷ 5 = ?',
      opts:['6','5','30','25'], ans:0,
      exp:'A divisão é a operação inversa da multiplicação. 30 ÷ 5 = 6.' },
    { id:'2op_rmd_2', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:1,
      q:'➗ Sabendo que 4 × 7 = 28, quanto é 28 ÷ 7?',
      opts:['7','4','28','14'], ans:1,
      exp:'28 ÷ 7 = 4. Usar a multiplicação que conheces para descobrir a divisão.' },
    { id:'2op_rmd_3', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:1,
      q:'➗ Completa a família de factos: 3 × 8 = 24, 8 × 3 = 24, 24 ÷ 3 = ___, 24 ÷ 8 = ___ (escreve os dois resultados separados por espaço).',
      ans:['8 3'],
      exp:'A família tem 4 factos: 3×8=24, 8×3=24, 24÷3=8, 24÷8=3.' },
    { id:'2op_rmd_4', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:2,
      q:'➗ Que multiplicação ajuda a calcular 45 ÷ 9?',
      opts:['9 × 5 = 45','9 × 4 = 36','45 × 9 = 405','9 + 5 = 14'], ans:0,
      exp:'9 × 5 = 45, portanto 45 ÷ 9 = 5.' },
    { id:'2op_rmd_5', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:2,
      q:'➗ 56 ÷ 8 = ___',
      ans:['7'],
      exp:'Pensar: 8 × ? = 56. Como 8 × 7 = 56, então 56 ÷ 8 = 7.' },
    { id:'2op_rmd_6', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:2,
      q:'➗ Quantos grupos de 4 cabem em 32?',
      opts:['6','7','8','9'], ans:2,
      exp:'32 ÷ 4 = 8 (porque 4 × 8 = 32).' },
    { id:'2op_rmd_7', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:3,
      q:'➗ A Eduarda tem 36 bombons para dividir igualmente por 6 amigos. Quantos bombons recebe cada um?',
      ans:['6'],
      exp:'36 ÷ 6 = 6. Cada amigo recebe 6 bombons (6 × 6 = 36).' },
    { id:'2op_rmd_8', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:3,
      q:'➗ A Vanessa tem 24€ e quer comprar livros que custam 3€ cada. Quantos livros consegue comprar?',
      opts:['7','8','9','6'], ans:1,
      exp:'24 ÷ 3 = 8 livros (3 × 8 = 24).' },

    // ----- Cálculo mental (10) -----
    { id:'2op_cm_1', s:'matematica', t:'Cálculo mental', type:'fill', diff:1,
      q:'🧠 47 + 10 = ___',
      ans:['57'],
      exp:'Somar 10 a 47 muda só a dezena: 47 → 57.' },
    { id:'2op_cm_2', s:'matematica', t:'Cálculo mental', type:'fill', diff:1,
      q:'🧠 80 − 10 = ___',
      ans:['70'],
      exp:'Tirar 10 a 80: 80 → 70.' },
    { id:'2op_cm_3', s:'matematica', t:'Cálculo mental', type:'mc', diff:1,
      q:'🧠 Dobro de 25 = ?',
      opts:['45','50','55','75'], ans:1,
      exp:'25 + 25 = 50. Ou 2 × 25 = 50.' },
    { id:'2op_cm_4', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 47 + 9 = ___ (truque: 47 + 10 − 1)',
      ans:['56'],
      exp:'47 + 10 = 57. Como somei 1 a mais, subtraio 1: 57 − 1 = 56.' },
    { id:'2op_cm_5', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 35 + 27 = ___ (decompõe: 30+20 + 5+7)',
      ans:['62'],
      exp:'30+20 = 50; 5+7 = 12; 50+12 = 62.' },
    { id:'2op_cm_6', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 Metade de 80 = ___',
      ans:['40'],
      exp:'80 ÷ 2 = 40.' },
    { id:'2op_cm_7', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 64 − 9 = ___ (truque: 64 − 10 + 1)',
      ans:['55'],
      exp:'64 − 10 = 54; somo 1 porque tirei 1 a mais: 54 + 1 = 55.' },
    { id:'2op_cm_8', s:'matematica', t:'Cálculo mental', type:'mc', diff:3,
      q:'🧠 53 + 38 (calcula mentalmente)',
      opts:['81','91','85','89'], ans:1,
      exp:'53 + 40 = 93; −2 (porque somei 2 a mais) = 91.' },
    { id:'2op_cm_9', s:'matematica', t:'Cálculo mental', type:'fill', diff:3,
      q:'🧠 100 − 47 = ___',
      ans:['53'],
      exp:'Pensa que números faltam de 47 até 100: 47 + 3 = 50; 50 + 50 = 100. Total: 3 + 50 = 53.' },
    { id:'2op_cm_10', s:'matematica', t:'Cálculo mental', type:'fill', diff:3,
      q:'🧠 Dobro do dobro de 6 = ___',
      ans:['24'],
      exp:'Dobro de 6 = 12. Dobro de 12 = 24. (= 4 × 6).' },

    // ----- Sequências de crescimento (8) -----
    { id:'2op_seq_1', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Qual é o número seguinte? 2, 4, 6, 8, ___',
      ans:['10'],
      exp:'A sequência aumenta de 2 em 2 (pares). Depois do 8 vem 10.' },
    { id:'2op_seq_2', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Qual é o número seguinte? 5, 10, 15, 20, ___',
      ans:['25'],
      exp:'Aumenta de 5 em 5. Depois de 20 vem 25.' },
    { id:'2op_seq_3', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Qual é o número seguinte? 10, 20, 30, 40, ___',
      ans:['50'],
      exp:'Aumenta de 10 em 10. Depois de 40 vem 50.' },
    { id:'2op_seq_4', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Qual a regra? 3, 6, 9, 12, 15... aumenta de ___ em ___ (escreve só um número).',
      ans:['3'],
      exp:'Diferença entre termos: 6−3=3, 9−6=3, etc. Aumenta de 3 em 3.' },
    { id:'2op_seq_5', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Que número está em falta? 11, 14, ___, 20, 23',
      ans:['17'],
      exp:'Aumenta de 3 em 3. 14 + 3 = 17.' },
    { id:'2op_seq_6', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Continua a sequência: 100, 110, 120, ___',
      ans:['130'],
      exp:'Aumenta de 10 em 10. Depois de 120 vem 130.' },
    { id:'2op_seq_7', s:'matematica', t:'Sequências de crescimento', type:'mc', diff:3,
      q:'📈 Qual o 6.º termo da sequência 7, 14, 21, 28, ...?',
      opts:['35','42','49','56'], ans:1,
      exp:'Tabuada do 7: 7, 14, 21, 28, 35, 42. O 6.º termo é 42.' },
    { id:'2op_seq_8', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:3,
      q:'📈 Que número falta? 50, 45, ___, 35, 30 (sequência DECRESCENTE de 5)',
      ans:['40'],
      exp:'Diminui de 5 em 5. 45 − 5 = 40.' },

    // ----- Perímetro (8) -----
    { id:'2op_per_1', s:'matematica', t:'Perímetro', type:'mc', diff:1,
      q:'📏 O perímetro de uma figura é:',
      opts:['A área de dentro','A soma de todos os lados','O lado maior','O número de lados'], ans:1,
      exp:'Perímetro = comprimento da linha que contorna a figura = soma de todos os lados.' },
    { id:'2op_per_2', s:'matematica', t:'Perímetro', type:'fill', diff:1,
      q:'📏 Qual o perímetro de um quadrado com 4 cm de lado?',
      ans:['16','16 cm','16cm'],
      exp:'Quadrado tem 4 lados iguais. 4 × 4 = 16 cm.' },
    { id:'2op_per_3', s:'matematica', t:'Perímetro', type:'fill', diff:1,
      q:'📏 Um triângulo tem lados de 3 cm, 4 cm e 5 cm. Qual o perímetro?',
      ans:['12','12 cm','12cm'],
      exp:'Soma dos lados: 3 + 4 + 5 = 12 cm.' },
    { id:'2op_per_4', s:'matematica', t:'Perímetro', type:'fill', diff:2,
      q:'📏 Um retângulo tem 6 cm de comprimento e 3 cm de largura. Qual o perímetro?',
      ans:['18','18 cm','18cm'],
      exp:'Retângulo: 2 lados iguais e 2 iguais. 6+3+6+3 = 18 cm. Ou 2×(6+3) = 18.' },
    { id:'2op_per_5', s:'matematica', t:'Perímetro', type:'mc', diff:2,
      q:'📏 Quadrado com 7 cm de lado tem perímetro:',
      opts:['14 cm','21 cm','28 cm','49 cm'], ans:2,
      exp:'4 × 7 = 28 cm.' },
    { id:'2op_per_6', s:'matematica', t:'Perímetro', type:'fill', diff:2,
      q:'📏 Pentágono regular (5 lados iguais) com cada lado de 6 cm. Perímetro = ___',
      ans:['30','30 cm','30cm'],
      exp:'5 × 6 = 30 cm.' },
    { id:'2op_per_7', s:'matematica', t:'Perímetro', type:'fill', diff:3,
      q:'📏 Um terreno retangular tem 25 m de comprimento e 15 m de largura. Quantos metros de rede são precisos para o cercar todo?',
      ans:['80','80 m','80m'],
      exp:'Perímetro = 2×(25+15) = 2×40 = 80 m.' },
    { id:'2op_per_8', s:'matematica', t:'Perímetro', type:'mc', diff:3,
      q:'📏 Um quadrado tem perímetro 36 cm. Quanto mede cada lado?',
      opts:['9 cm','6 cm','12 cm','4 cm'], ans:0,
      exp:'4 lados iguais → 36 ÷ 4 = 9 cm.' },

    // ----- Ângulos retos (8) -----
    { id:'2op_ang_1', s:'matematica', t:'Ângulos retos', type:'mc', diff:1,
      q:'📐 Um ângulo reto tem:',
      opts:['Mais de 90°','Menos de 90°','Exatamente 90°','180°'], ans:2,
      exp:'O ângulo reto mede exatamente 90 graus. Forma o canto de um "L" ou de um quadrado.' },
    { id:'2op_ang_2', s:'matematica', t:'Ângulos retos', type:'tf', diff:1,
      q:'📐 Os 4 cantos de um quadrado são ângulos retos.',
      ans:true,
      exp:'Verdadeiro. Todo o quadrado e todo o retângulo têm 4 ângulos retos (90° cada).' },
    { id:'2op_ang_3', s:'matematica', t:'Ângulos retos', type:'mc', diff:1,
      q:'📐 Qual destas formas TEM sempre ângulos retos?',
      opts:['Triângulo equilátero','Círculo','Retângulo','Pentágono'], ans:2,
      exp:'O retângulo tem sempre 4 ângulos retos. O círculo não tem ângulos. Os outros podem ou não.' },
    { id:'2op_ang_4', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Um ângulo MAIOR que reto chama-se:',
      opts:['Agudo','Reto','Obtuso','Pequeno'], ans:2,
      exp:'Agudo < 90° (reto) < Obtuso. Obtuso é maior que 90°.' },
    { id:'2op_ang_5', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Um ângulo MENOR que reto chama-se:',
      opts:['Obtuso','Agudo','Raso','Giro'], ans:1,
      exp:'Ângulo agudo é menor que 90°. "Agudo" como uma faca afiada (estreito).' },
    { id:'2op_ang_6', s:'matematica', t:'Ângulos retos', type:'tf', diff:2,
      q:'📐 Os ponteiros do relógio às 3 horas formam um ângulo reto.',
      ans:true,
      exp:'Verdadeiro. Às 3:00 o ponteiro pequeno aponta para o 3 e o grande para o 12 — formam exatamente 90°.' },
    { id:'2op_ang_7', s:'matematica', t:'Ângulos retos', type:'mc', diff:3,
      q:'📐 Quantos ângulos retos tem um quadrado?',
      opts:['1','2','3','4'], ans:3,
      exp:'4 ângulos retos — um em cada canto.' },
    { id:'2op_ang_8', s:'matematica', t:'Ângulos retos', type:'mc', diff:3,
      q:'📐 Qual destes objetos do dia-a-dia mostra um ângulo reto?',
      opts:['Uma bola','Uma página de caderno (no canto)','Uma laranja','Uma roda'], ans:1,
      exp:'O canto da folha de papel ou de um caderno é um ângulo reto. Bolas e rodas são redondas (sem ângulos).' },

    // ============================================================
    // ===================== PORTUGUÊS ============================
    // ============================================================

    // ----- Conetores (e, ou) (8) -----
    { id:'2op_con_1', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:1,
      q:'🔗 "Comi pão ___ bebi leite." Que conetor encaixa?',
      opts:['e','ou','mas','porque'], ans:0,
      exp:'"E" liga duas ações que aconteceram juntas (adição).' },
    { id:'2op_con_2', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:1,
      q:'🔗 "Queres maçã ___ banana?" Que conetor encaixa?',
      opts:['e','ou','porque','com'], ans:1,
      exp:'"OU" indica alternativa — escolhe uma das duas.' },
    { id:'2op_con_3', s:'portugues', t:'Conetores (e, ou)', type:'tf', diff:1,
      q:'🔗 O conetor "e" serve para LIGAR duas ideias.',
      ans:true,
      exp:'Verdadeiro. "E" é um conetor de ADIÇÃO — junta ideias.' },
    { id:'2op_con_4', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:2,
      q:'🔗 "Posso ir contigo ___ ficar em casa, escolho eu." Qual o conetor certo?',
      opts:['e','ou','mas','porque'], ans:1,
      exp:'É uma alternativa (uma OU outra opção).' },
    { id:'2op_con_5', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:2,
      q:'🔗 Qual frase usa "e" CORRETAMENTE?',
      opts:['Choveu e fez sol no mesmo segundo.','O cão e o gato dormem na cesta.','Comi e não comi.','E ou não?'], ans:1,
      exp:'"O cão e o gato dormem" — "e" liga dois sujeitos que fazem a mesma ação.' },
    { id:'2op_con_6', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:2,
      q:'🔗 Liga as frases com UM conetor: "Tenho fome. Tenho sede." → "Tenho fome ___ sede."',
      ans:['e'],
      exp:'"E" junta as duas ideias relacionadas.' },
    { id:'2op_con_7', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:3,
      q:'🔗 "O cão é castanho ___ branco — não sei bem qual." A frase pede:',
      opts:['e (ambos)','ou (um dos dois)','mas','porque'], ans:1,
      exp:'"OU" — incerteza, uma das duas cores. Se fossem ambas seria "e".' },
    { id:'2op_con_8', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:3,
      q:'🔗 Escolhe E ou OU para esta frase: "Hoje vou ao cinema ___ ao parque, ainda não decidi."',
      ans:['ou'],
      exp:'Vou a UM dos dois (alternativa) — "ou".' },

    // ----- Interjeições (8) -----
    { id:'2op_int_1', s:'portugues', t:'Interjeições', type:'mc', diff:1,
      q:'❗ "Ah! Que surpresa!" A palavra "Ah" é uma:',
      opts:['Verbo','Interjeição','Adjetivo','Nome'], ans:1,
      exp:'Interjeição = palavra que exprime EMOÇÃO. "Ah!" mostra surpresa/admiração.' },
    { id:'2op_int_2', s:'portugues', t:'Interjeições', type:'mc', diff:1,
      q:'❗ Que interjeição se usa para CUMPRIMENTAR?',
      opts:['Olá!','Ai!','Bah!','Ufa!'], ans:0,
      exp:'"Olá!" é interjeição de saudação.' },
    { id:'2op_int_3', s:'portugues', t:'Interjeições', type:'tf', diff:1,
      q:'❗ "Ai!" exprime dor ou aflição.',
      ans:true,
      exp:'Verdadeiro. "Ai!" usa-se quando nos magoamos ou ficamos surpreendidos.' },
    { id:'2op_int_4', s:'portugues', t:'Interjeições', type:'mc', diff:2,
      q:'❗ Que interjeição mostra ALEGRIA?',
      opts:['Ai!','Viva!','Bah!','Ué!'], ans:1,
      exp:'"Viva!" celebra, mostra alegria. Também: "Hurra!", "Boa!".' },
    { id:'2op_int_5', s:'portugues', t:'Interjeições', type:'mc', diff:2,
      q:'❗ "Ufa! Que cansaço!" A interjeição "Ufa!" exprime:',
      opts:['Alegria','Cansaço/alívio','Surpresa','Dor'], ans:1,
      exp:'"Ufa!" é alívio depois de um esforço.' },
    { id:'2op_int_6', s:'portugues', t:'Interjeições', type:'fill', diff:2,
      q:'❗ Que interjeição se usa para DESPEDIR?',
      ans:['adeus','adeus!','tchau','tchau!','até logo'],
      exp:'"Adeus!" ou "Tchau!" são interjeições de despedida.' },
    { id:'2op_int_7', s:'portugues', t:'Interjeições', type:'mc', diff:3,
      q:'❗ "Coitado!" exprime:',
      opts:['Alegria','Pena/compaixão','Raiva','Ordem'], ans:1,
      exp:'"Coitado!" mostra pena por alguém que sofre.' },
    { id:'2op_int_8', s:'portugues', t:'Interjeições', type:'mc', diff:3,
      q:'❗ Qual destas frases TEM uma interjeição?',
      opts:['O sol nasceu.','Bravo! Que jogo!','A Maria estuda.','O cão dorme.'], ans:1,
      exp:'"Bravo!" — interjeição de aplauso/aprovação. É o típico ponto de exclamação a seguir.' },

    // ----- Determinantes artigos (8) -----
    { id:'2op_da_1', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "O", "a", "os", "as" são:',
      opts:['Nomes','Verbos','Artigos definidos','Adjetivos'], ans:2,
      exp:'O, a, os, as = artigos DEFINIDOS (já conheço a coisa específica).' },
    { id:'2op_da_2', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "Um", "uma", "uns", "umas" são:',
      opts:['Artigos indefinidos','Artigos definidos','Pronomes','Verbos'], ans:0,
      exp:'Um, uma, uns, umas = artigos INDEFINIDOS (não específico, qualquer um).' },
    { id:'2op_da_3', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "A menina lê um livro." Qual é o artigo DEFINIDO?',
      opts:['A','um','livro','menina'], ans:0,
      exp:'"A" — sabemos qual menina. "Um" é INDEFINIDO (qualquer livro).' },
    { id:'2op_da_4', s:'portugues', t:'Determinantes artigos', type:'fill', diff:2,
      q:'🔤 Escreve o artigo definido apropriado: ___ cão dorme.',
      ans:['o','O'],
      exp:'"O cão" — masculino singular. Artigo definido = O.' },
    { id:'2op_da_5', s:'portugues', t:'Determinantes artigos', type:'mc', diff:2,
      q:'🔤 Plural de "a flor":',
      opts:['o flores','as flores','uma flores','umas flor'], ans:1,
      exp:'"a" no plural feminino = "as". "as flores".' },
    { id:'2op_da_6', s:'portugues', t:'Determinantes artigos', type:'mc', diff:2,
      q:'🔤 Qual frase usa o artigo INDEFINIDO?',
      opts:['O sol brilha.','As crianças cantam.','Uma menina chegou.','Os meus pais.'], ans:2,
      exp:'"Uma" é indefinido — uma qualquer menina, não específica.' },
    { id:'2op_da_7', s:'portugues', t:'Determinantes artigos', type:'fill', diff:3,
      q:'🔤 Completa com o artigo certo: ___ lápis estão na mesa (plural masculino definido).',
      ans:['os','Os'],
      exp:'Masculino plural definido = "os".' },
    { id:'2op_da_8', s:'portugues', t:'Determinantes artigos', type:'mc', diff:3,
      q:'🔤 Em "A Joana viu uma estrela", quantos artigos há no total?',
      opts:['1','2','3','0'], ans:1,
      exp:'2 artigos: "A" (definido — sabemos qual Joana) + "uma" (indefinido — uma estrela qualquer).' },

    // ----- Sílaba átona (8) -----
    { id:'2op_sa_1', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 A sílaba que se diz com MAIS FORÇA chama-se:',
      opts:['Átona','Tónica','Forte','Grande'], ans:1,
      exp:'Sílaba TÓNICA = a que se ouve mais forte. As outras sílabas são ÁTONAS.' },
    { id:'2op_sa_2', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 Em "ca-SA", qual é a sílaba tónica?',
      opts:['CA','SA','Nenhuma','As duas'], ans:1,
      exp:'CA-SA. A força está em SA. As outras (CA) são átonas.' },
    { id:'2op_sa_3', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 Em "BO-la", qual é a sílaba átona?',
      opts:['BO','la','As duas','Nenhuma'], ans:1,
      exp:'BO-LA. Tónica = BO. Átona = la.' },
    { id:'2op_sa_4', s:'portugues', t:'Sílaba átona', type:'mc', diff:2,
      q:'🔡 Em "MA-LA", as sílabas átonas são:',
      opts:['Só MA','Só LA','MA e LA','Nenhuma — todas são tónicas'], ans:1,
      exp:'Tónica = MA (a que se ouve mais). Átona = LA.' },
    { id:'2op_sa_5', s:'portugues', t:'Sílaba átona', type:'mc', diff:2,
      q:'🔡 Em "ca-DER-no" qual a tónica?',
      opts:['CA','DER','NO','Nenhuma'], ans:1,
      exp:'CA-DER-NO. Tónica = DER. As outras (CA e NO) são átonas.' },
    { id:'2op_sa_6', s:'portugues', t:'Sílaba átona', type:'fill', diff:2,
      q:'🔡 Em "GA-to", a sílaba átona é: ___',
      ans:['to','TO','to (segunda)'],
      exp:'GA-TO. Tónica = GA (forte). Átona = TO.' },
    { id:'2op_sa_7', s:'portugues', t:'Sílaba átona', type:'mc', diff:3,
      q:'🔡 Em "bor-bo-LE-ta", quantas sílabas átonas há?',
      opts:['1','2','3','4'], ans:2,
      exp:'BOR-BO-LE-TA. Tónica = LE. Átonas = BOR, BO, TA. Total: 3.' },
    { id:'2op_sa_8', s:'portugues', t:'Sílaba átona', type:'mc', diff:3,
      q:'🔡 Em "ca-VA-lo", as sílabas átonas são:',
      opts:['CA e VA','VA e LO','CA e LO','VA apenas'], ans:2,
      exp:'CA-VA-LO. Tónica = VA. Átonas = CA e LO.' },

    // ----- Compreensão de texto (8) -----
    { id:'2op_ct_1', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 Lê: "O sol brilhava no céu. A Maria corria no jardim com o seu cão."\nQuem corria no jardim?',
      opts:['O sol','A Maria','O cão sozinho','Ninguém'], ans:1,
      exp:'O texto diz "A Maria corria no jardim com o seu cão" — Maria é o sujeito.' },
    { id:'2op_ct_2', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 Lê: "Choveu toda a manhã. À tarde, o sol apareceu." Quando apareceu o sol?',
      opts:['De manhã','À tarde','À noite','Não diz'], ans:1,
      exp:'O texto é claro: "À tarde, o sol apareceu."' },
    { id:'2op_ct_3', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 Lê: "O João tem 3 maçãs. Comeu 1." Quantas maçãs lhe restam?',
      opts:['1','2','3','4'], ans:1,
      exp:'3 − 1 = 2 maçãs.' },
    { id:'2op_ct_4', s:'portugues', t:'Compreensão de texto', type:'mc', diff:2,
      q:'📖 "A Eduarda foi à escola de mochila às costas. Tinha lápis, borracha e livros lá dentro." O que NÃO estava na mochila?',
      opts:['Lápis','Borracha','Livros','Régua'], ans:3,
      exp:'O texto menciona lápis, borracha e livros. Régua NÃO é referida.' },
    { id:'2op_ct_5', s:'portugues', t:'Compreensão de texto', type:'mc', diff:2,
      q:'📖 "Ontem fez frio. A Sofia vestiu o casaco verde e foi para a escola." Que cor era o casaco?',
      opts:['Vermelho','Azul','Verde','Amarelo'], ans:2,
      exp:'O texto diz "casaco verde".' },
    { id:'2op_ct_6', s:'portugues', t:'Compreensão de texto', type:'fill', diff:2,
      q:'📖 "O pai do João é professor." Que profissão tem o pai do João?',
      ans:['professor'],
      exp:'O texto diz claramente "é professor".' },
    { id:'2op_ct_7', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "A Carolina adora ler. Tem livros de aventuras, mistério e poesia. Os preferidos são os de mistério." Qual género ela prefere?',
      opts:['Aventuras','Mistério','Poesia','Banda desenhada'], ans:1,
      exp:'O texto diz "Os preferidos são os de mistério".' },
    { id:'2op_ct_8', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "O cão do João partiu uma cadeira. O João ficou triste mas perdoou-o." Como se sentiu o João?',
      opts:['Feliz','Triste','Zangado para sempre','Não diz'], ans:1,
      exp:'O texto diz que "ficou triste" mas depois perdoou.' },

    // ----- Textos narrativos (8) -----
    { id:'2op_tn_1', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 Um texto narrativo serve para:',
      opts:['Dar instruções','Contar uma história','Listar regras','Mostrar imagens'], ans:1,
      exp:'Narrativo = NARRA, conta uma história com personagens, espaço, tempo e ação.' },
    { id:'2op_tn_2', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 As "personagens" de uma história são:',
      opts:['O sítio onde acontece','Quem participa na ação','O tempo','O fim'], ans:1,
      exp:'Personagens são as pessoas/animais que vivem a história.' },
    { id:'2op_tn_3', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 O "espaço" de uma narrativa é:',
      opts:['Quem','O quê','Onde acontece','Quando'], ans:2,
      exp:'Espaço = onde se passa a história (casa, escola, floresta...).' },
    { id:'2op_tn_4', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 Quem CONTA a história num texto narrativo chama-se:',
      opts:['Personagem','Narrador','Autor','Leitor'], ans:1,
      exp:'NARRADOR é quem conta. Autor é quem escreve (pessoa real).' },
    { id:'2op_tn_5', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 Toda a história tem geralmente:',
      opts:['Só fim','Início, meio e fim','Só meio','Só personagens'], ans:1,
      exp:'A estrutura clássica é: introdução (início) → desenvolvimento (meio) → conclusão (fim).' },
    { id:'2op_tn_6', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 "Era uma vez uma princesa que vivia num castelo." Que tipo de texto é?',
      opts:['Informativo','Narrativo','Receita','Carta'], ans:1,
      exp:'É o início típico de um conto/narrativa. "Era uma vez..." é um marcador clássico.' },
    { id:'2op_tn_7', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 "Há muito tempo, num castelo, vivia uma princesa." Aqui já estão indicados:',
      opts:['Só personagem','Só espaço','Personagem, espaço e tempo','Só tempo'], ans:2,
      exp:'Tempo: "há muito tempo". Espaço: "num castelo". Personagem: "uma princesa".' },
    { id:'2op_tn_8', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 Numa narrativa, a "ação" é:',
      opts:['O que acontece (sequência de eventos)','As personagens em si','A cor do livro','O título'], ans:0,
      exp:'AÇÃO = a sequência de eventos que acontecem na história.' },

    // ----- Poesia e BD (8) -----
    { id:'2op_pbd_1', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'📜 Uma poesia organiza-se em:',
      opts:['Capítulos','Versos e estrofes','Linhas em prosa','Bocados'], ans:1,
      exp:'Verso = linha do poema. Estrofe = grupo de versos.' },
    { id:'2op_pbd_2', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'📜 Quando duas palavras acabam com o mesmo som diz-se que:',
      opts:['Ficam iguais','Rimam','Voam','São sinónimos'], ans:1,
      exp:'Rimam → "gato" e "pato" rimam (ambas terminam em -ato).' },
    { id:'2op_pbd_3', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'💬 Numa BD, o "balão" serve para:',
      opts:['Decorar','Mostrar o que a personagem diz ou pensa','Numerar páginas','Cor de fundo'], ans:1,
      exp:'O balão (ou balão de fala) mostra o que a personagem diz/pensa.' },
    { id:'2op_pbd_4', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'💬 Em BD, cada quadrado/cena chama-se:',
      opts:['Página','Vinheta','Estrofe','Capítulo'], ans:1,
      exp:'Vinheta é cada quadrado/cena da BD. Várias vinhetas em sequência formam a história.' },
    { id:'2op_pbd_5', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'💥 "BUM!" "ZÁS!" "PAFT!" em BD são:',
      opts:['Personagens','Onomatopeias','Títulos','Acentos'], ans:1,
      exp:'Onomatopeias = palavras que IMITAM sons (explosão, batida, queda).' },
    { id:'2op_pbd_6', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'📜 "O sol é vivo, é cor de mel / brilha no céu como pastel." Que som rima?',
      opts:['mel e pastel (rima -el)','sol e céu','vivo e brilha','As duas linhas não rimam'], ans:0,
      exp:'"mel" e "pastel" terminam ambas em -el — rimam.' },
    { id:'2op_pbd_7', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'💬 Um balão de fala COM ZIGZAG geralmente indica:',
      opts:['Sussurro','Grito ou choque','Pensamento','Canto'], ans:1,
      exp:'Balão em ziguezague = grito, gritaria, susto.' },
    { id:'2op_pbd_8', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'📜 Um conjunto de 4 versos juntos forma uma:',
      opts:['Quadra (estrofe de 4 versos)','Frase','Linha','Música'], ans:0,
      exp:'Estrofe de 4 versos = QUADRA. De 3 = terceto. De 2 = dístico.' },

    // ============================================================
    // ==================== ESTUDO DO MEIO ========================
    // ============================================================

    // ----- Portugal na Europa e no mundo (8) -----
    { id:'2op_pem_1', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🌍 Portugal é um país do continente:',
      opts:['África','Ásia','Europa','América'], ans:2,
      exp:'Portugal fica na Europa, mais especificamente na Península Ibérica (oeste da Europa).' },
    { id:'2op_pem_2', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🏛️ A capital de Portugal é:',
      opts:['Porto','Lisboa','Coimbra','Faro'], ans:1,
      exp:'Lisboa é a capital de Portugal.' },
    { id:'2op_pem_3', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🌊 Portugal fica à beira do oceano:',
      opts:['Atlântico','Pacífico','Índico','Ártico'], ans:0,
      exp:'Portugal está na costa do Oceano Atlântico.' },
    { id:'2op_pem_4', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:2,
      q:'🤝 O único país com que Portugal partilha fronteira terrestre é:',
      opts:['França','Espanha','Marrocos','Itália'], ans:1,
      exp:'Portugal só faz fronteira terrestre com Espanha (a leste e a norte).' },
    { id:'2op_pem_5', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'tf', diff:2,
      q:'🌍 Portugal faz parte da União Europeia.',
      ans:true,
      exp:'Verdadeiro. Portugal entrou na União Europeia (na altura CEE) em 1986.' },
    { id:'2op_pem_6', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:2,
      q:'🏝️ Quais são as duas regiões autónomas de Portugal?',
      opts:['Algarve e Alentejo','Açores e Madeira','Porto e Lisboa','Minho e Beira'], ans:1,
      exp:'Açores e Madeira são as duas Regiões Autónomas (arquipélagos no Atlântico).' },
    { id:'2op_pem_7', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:3,
      q:'🗣️ A língua portuguesa também é falada noutros países como:',
      opts:['Espanha e França','Brasil, Angola, Moçambique','Inglaterra e Alemanha','China e Japão'], ans:1,
      exp:'Brasil, Angola, Moçambique, Cabo Verde, S. Tomé, Guiné-Bissau e Timor — todos países lusófonos (de língua portuguesa).' },
    { id:'2op_pem_8', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:3,
      q:'🇪🇺 A moeda de Portugal é:',
      opts:['Escudo','Euro (€)','Libra','Dólar'], ans:1,
      exp:'O Euro (€) é a moeda de Portugal desde 2002 (antes era o Escudo).' },

    // ----- Influências de outras culturas (8) -----
    { id:'2op_inf_1', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:1,
      q:'🍕 A pizza, comida muito apreciada em Portugal, vem da:',
      opts:['China','Itália','Japão','Inglaterra'], ans:1,
      exp:'A pizza é típica de Itália. Adotámo-la na nossa alimentação.' },
    { id:'2op_inf_2', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:1,
      q:'🍣 O sushi vem de que país?',
      opts:['China','Tailândia','Japão','Coreia'], ans:2,
      exp:'O sushi é um prato típico do Japão. Hoje há restaurantes japoneses em Portugal.' },
    { id:'2op_inf_3', s:'estudo_meio', t:'Influências de outras culturas', type:'tf', diff:1,
      q:'🌍 Em Portugal vivem pessoas de muitos países diferentes.',
      ans:true,
      exp:'Verdadeiro. Em Portugal há comunidades brasileira, ucraniana, cabo-verdiana, chinesa, nepalesa, etc.' },
    { id:'2op_inf_4', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:2,
      q:'☕ O hábito de tomar chá veio em parte da:',
      opts:['Inglaterra/Ásia','Espanha','Brasil','Marrocos'], ans:0,
      exp:'O chá veio para a Europa através de comerciantes ingleses, mas as folhas vinham da Ásia (China, Índia).' },
    { id:'2op_inf_5', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:2,
      q:'🎵 Que estilo de música americano é hoje muito ouvido em Portugal?',
      opts:['Fado','Hip-hop','Música clássica','Folclore'], ans:1,
      exp:'O hip-hop nasceu nos EUA e é hoje muito ouvido por jovens portugueses.' },
    { id:'2op_inf_6', s:'estudo_meio', t:'Influências de outras culturas', type:'tf', diff:2,
      q:'🌱 As batatas, tomates e milho que comemos hoje vieram originalmente da América.',
      ans:true,
      exp:'Verdadeiro. Trouxeram-nas para a Europa após os Descobrimentos. Antes não existiam cá.' },
    { id:'2op_inf_7', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'🛕 A festa do Diwali (festa das luzes) vem de:',
      opts:['Portugal','Índia','Japão','França'], ans:1,
      exp:'Diwali é uma festa hindu da Índia. Em Portugal celebram-na as comunidades indianas.' },
    { id:'2op_inf_8', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'👋 Saber dizer "olá" noutras línguas é importante porque:',
      opts:['Não tem utilidade','Mostra respeito pela cultura do outro','Só quem viaja precisa','Substitui o português'], ans:1,
      exp:'Saber palavras de outras línguas é uma forma de respeito e curiosidade pelas culturas dos outros.' },

    // ----- Múltiplas pertenças e grupos (8) -----
    { id:'2op_mp_1', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:1,
      q:'👨‍👩‍👧 Pertenço à minha:',
      opts:['Família','Cidade','Família, escola, turma — todos','Só escola'], ans:2,
      eque:'Cada criança pertence a vários grupos ao mesmo tempo: família, turma, escola, talvez clube, vizinhança, etc.',
      exp:'Cada criança pertence a vários grupos ao mesmo tempo: família, turma, escola, talvez clube, vizinhança, etc.' },
    { id:'2op_mp_2', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'tf', diff:1,
      q:'👥 Uma pessoa pode pertencer a vários grupos ao mesmo tempo.',
      ans:true,
      exp:'Verdadeiro. Posso ser irmão (família), aluno (escola), jogador de futebol (clube) — tudo em simultâneo.' },
    { id:'2op_mp_3', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:1,
      q:'🏫 A turma é um grupo:',
      opts:['Familiar','Escolar','Desportivo','Religioso'], ans:1,
      exp:'A turma é o grupo escolar mais próximo — colegas que partilham a mesma sala/professor.' },
    { id:'2op_mp_4', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:2,
      q:'⚽ Um clube de futebol é um grupo:',
      opts:['Familiar','Religioso','Desportivo','Político'], ans:2,
      exp:'Clube desportivo. Reúne pessoas que partilham gosto pelo desporto.' },
    { id:'2op_mp_5', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:2,
      q:'🤝 Numa turma diversa, cada colega pode ter:',
      opts:['A mesma religião só','As mesmas roupas','Origens e culturas diferentes','Os mesmos pais'], ans:2,
      exp:'A diversidade enriquece a turma — colegas podem vir de várias culturas, países, religiões.' },
    { id:'2op_mp_6', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'tf', diff:2,
      q:'👨‍👩‍👧‍👦 Há diferentes tipos de família (com pai e mãe, só com mãe, com avós, etc.) e todas são válidas.',
      ans:true,
      exp:'Verdadeiro. Há famílias muito diferentes, todas igualmente válidas e importantes.' },
    { id:'2op_mp_7', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🌍 "Pertencer" significa:',
      opts:['Ter coisas','Fazer parte de um grupo e sentir-se ligado','Mandar nos outros','Estar sozinho'], ans:1,
      exp:'Pertencer é sentir-se parte de algo (família, turma, etc.) — laços de identidade e ligação.' },
    { id:'2op_mp_8', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🤗 Quando alguém é novo na turma, devemos:',
      opts:['Ignorar','Acolher e ajudar a integrar','Rir','Ficar em silêncio'], ans:1,
      exp:'Acolher os colegas novos é importante para que se sintam parte do grupo.' },

    // ----- Direitos da criança (8) -----
    { id:'2op_dc_1', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:1,
      q:'📜 Todas as crianças têm o direito à:',
      opts:['Trabalho','Educação','Conduzir','Casamento'], ans:1,
      exp:'A educação é um direito FUNDAMENTAL de todas as crianças.' },
    { id:'2op_dc_2', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:1,
      q:'🏥 Outro direito da criança é:',
      opts:['Pagar impostos','Saúde','Votar','Conduzir'], ans:1,
      exp:'Direito à saúde — todas as crianças devem ter cuidados de saúde.' },
    { id:'2op_dc_3', s:'estudo_meio', t:'Direitos da criança', type:'tf', diff:1,
      q:'🎈 As crianças têm o direito a brincar.',
      ans:true,
      exp:'Verdadeiro. O direito ao lazer e à brincadeira está na Convenção dos Direitos da Criança.' },
    { id:'2op_dc_4', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:2,
      q:'🗣️ As crianças têm o direito a:',
      opts:['Estar caladas sempre','Ser ouvidas e dar a sua opinião','Mandar nos adultos','Não ir à escola'], ans:1,
      exp:'Direito de participação: a criança tem direito a ser ouvida e expressar a sua opinião.' },
    { id:'2op_dc_5', s:'estudo_meio', t:'Direitos da criança', type:'tf', diff:2,
      q:'👨‍👩‍👧 Toda a criança tem direito a uma família/cuidadores que tomam conta dela.',
      ans:true,
      exp:'Verdadeiro. Direito à proteção familiar e a viver em ambiente seguro.' },
    { id:'2op_dc_6', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:2,
      q:'🛡️ As crianças devem ser protegidas:',
      opts:['Só algumas','Só os mais pequenos','Todas, sem distinção','Só se obedecerem'], ans:2,
      exp:'TODAS as crianças têm direito à proteção, sem distinção (nem por origem, religião, género, etc.).' },
    { id:'2op_dc_7', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'📋 O documento internacional sobre direitos da criança chama-se:',
      opts:['Constituição','Convenção dos Direitos da Criança','Manual da escola','Lei das férias'], ans:1,
      exp:'A Convenção sobre os Direitos da Criança foi aprovada pelas Nações Unidas em 1989.' },
    { id:'2op_dc_8', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'🌍 Os direitos da criança aplicam-se:',
      opts:['Só em Portugal','Em todos os países do mundo','Só na Europa','Só nas escolas'], ans:1,
      exp:'A Convenção dos Direitos da Criança aplica-se em todos os países que a assinaram (quase todos).' },

    // ----- Diálogo e compromisso (8) -----
    { id:'2op_di_1', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:1,
      q:'💬 Quando alguém fala devemos:',
      opts:['Interromper','Ouvir com atenção','Falar mais alto','Sair'], ans:1,
      exp:'Ouvir com atenção é o primeiro passo para um bom diálogo.' },
    { id:'2op_di_2', s:'estudo_meio', t:'Diálogo e compromisso', type:'tf', diff:1,
      q:'🤝 É importante usar palavras como "por favor" e "obrigado".',
      ans:true,
      exp:'Verdadeiro. São palavras que mostram respeito.' },
    { id:'2op_di_3', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:1,
      q:'😡 Quando há um desacordo, a melhor forma de resolver é:',
      opts:['Bater','Gritar mais alto','Conversar com calma','Não falar nunca mais'], ans:2,
      exp:'Falar com calma — o diálogo resolve conflitos melhor que a violência.' },
    { id:'2op_di_4', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:2,
      q:'🤝 Quando dois amigos querem coisas diferentes, podem:',
      opts:['Brigar até alguém ceder','Procurar um compromisso (cada um cede um pouco)','Não brincar mais','Esperar que alguém decida por eles'], ans:1,
      exp:'Compromisso = cada um cede um pouco para chegar a um acordo onde ambos ficam satisfeitos.' },
    { id:'2op_di_5', s:'estudo_meio', t:'Diálogo e compromisso', type:'tf', diff:2,
      q:'💬 No diálogo é importante ouvir o outro e expressar a sua opinião sem agressividade.',
      ans:true,
      exp:'Verdadeiro. Ouvir + falar com respeito = bom diálogo.' },
    { id:'2op_di_6', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:2,
      q:'🤝 Cumprir o que se combina chama-se:',
      opts:['Compromisso','Conflito','Discussão','Castigo'], ans:0,
      exp:'Compromisso é o que assumimos cumprir. Se prometo, devo cumprir.' },
    { id:'2op_di_7', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🕊️ "Negociar" significa:',
      opts:['Lutar','Conversar para chegar a acordo','Mandar','Fugir'], ans:1,
      exp:'Negociar = falar/discutir até chegar a um acordo que sirva às partes.' },
    { id:'2op_di_8', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🌟 Numa turma, regras combinadas em conjunto são respeitadas porque:',
      opts:['Foram impostas','Todos contribuíram e concordaram','São fáceis de quebrar','Ninguém quer'], ans:1,
      exp:'Quando todos participam na criação das regras, sentem-nas como suas e cumprem mais facilmente.' },

    // ============================================================
    // ============= EXERCÍCIOS EXTRA (+1 por tópico) ==============
    // ============================================================

    // ----- Números até 1000 (mais 8) -----
    { id:'2op_n1k_11', s:'matematica', t:'Números até 1000', type:'mc', diff:1,
      q:'🔢 O número "quatrocentos e doze" escreve-se:',
      opts:['412','421','4012','142'], ans:0,
      exp:'400 + 12 = 412.' },
    { id:'2op_n1k_12', s:'matematica', t:'Números até 1000', type:'fill', diff:1,
      q:'🔢 Quantas centenas tem o número 730?',
      ans:['7','sete'],
      exp:'730 = 7 centenas + 3 dezenas + 0 unidades.' },
    { id:'2op_n1k_13', s:'matematica', t:'Números até 1000', type:'mc', diff:2,
      q:'🔢 Qual é o número seguinte a 599?',
      opts:['600','699','510','5910'], ans:0,
      exp:'599 + 1 = 600. Quando as 9 dezenas e unidades passam, sobe a centena.' },
    { id:'2op_n1k_14', s:'matematica', t:'Números até 1000', type:'fill', diff:2,
      q:'🔢 Escreve 800 + 40 + 6 = ___',
      ans:['846'],
      exp:'846 = 8 centenas + 4 dezenas + 6 unidades.' },
    { id:'2op_n1k_15', s:'matematica', t:'Números até 1000', type:'mc', diff:2,
      q:'🔢 Qual número é PAR?',
      opts:['347','253','490','161'], ans:2,
      exp:'490 acaba em 0 (par). Pares acabam em 0, 2, 4, 6 ou 8.' },
    { id:'2op_n1k_16', s:'matematica', t:'Números até 1000', type:'fill', diff:3,
      q:'🔢 Arredonda 173 à centena mais próxima.',
      ans:['200'],
      exp:'173 está mais perto de 200 do que de 100 (porque 73 > 50).' },
    { id:'2op_n1k_17', s:'matematica', t:'Números até 1000', type:'mc', diff:3,
      q:'🔢 A diferença entre 305 e 297 é:',
      opts:['8','12','602','7'], ans:0,
      exp:'305 − 297 = 8.' },
    { id:'2op_n1k_18', s:'matematica', t:'Números até 1000', type:'fill', diff:3,
      q:'🔢 Que número está exactamente a meio entre 200 e 300?',
      ans:['250'],
      exp:'(200 + 300) ÷ 2 = 500 ÷ 2 = 250.' },

    // ----- Propriedades da multiplicação (mais 8) -----
    { id:'2op_pmul_9', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Quanto é 0 × 100?',
      opts:['100','0','1','1000'], ans:1,
      exp:'Qualquer número multiplicado por 0 dá 0.' },
    { id:'2op_pmul_10', s:'matematica', t:'Propriedades da multiplicação', type:'tf', diff:1,
      q:'✖️ A ordem dos factores altera o produto: 3 × 4 ≠ 4 × 3.',
      ans:false,
      exp:'Falso! Pela propriedade comutativa, 3 × 4 = 4 × 3 = 12. A ordem NÃO altera.' },
    { id:'2op_pmul_11', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:2,
      q:'✖️ Aplica a comutativa: 9 × 6 = 6 × ___',
      ans:['9'],
      exp:'9 × 6 = 6 × 9 = 54. A ordem não importa.' },
    { id:'2op_pmul_12', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:2,
      q:'✖️ Calcula (4 × 5) × 2 usando a associativa.',
      opts:['40','25','22','60'], ans:0,
      exp:'(4×5)×2 = 20×2 = 40. Ou 4×(5×2) = 4×10 = 40.' },
    { id:'2op_pmul_13', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:2,
      q:'✖️ Quanto é 1000 × 1?',
      ans:['1000','1 000','mil'],
      exp:'Elemento neutro: qualquer número × 1 = o próprio número.' },
    { id:'2op_pmul_14', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:3,
      q:'✖️ Usa a distributiva: 8 × 11 = 8 × (10 + 1) = ?',
      opts:['18','80','88','89'], ans:2,
      exp:'8×10 = 80; 8×1 = 8; 80 + 8 = 88.' },
    { id:'2op_pmul_15', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:3,
      q:'✖️ Mentalmente: 6 × 21 = 6 × 20 + 6 × 1 = ___',
      ans:['126'],
      exp:'6×20 = 120; 6×1 = 6; 120 + 6 = 126.' },
    { id:'2op_pmul_16', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:3,
      q:'✖️ 4 × 25 = ? Usa decomposição (25 = 20 + 5).',
      opts:['100','80','105','85'], ans:0,
      exp:'4×20 = 80; 4×5 = 20; 80 + 20 = 100.' },

    // ----- Relação multiplicação e divisão (mais 8) -----
    { id:'2op_rmd_9', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:1,
      q:'➗ Se 6 × 4 = 24, então 24 ÷ 6 = ___',
      ans:['4'],
      exp:'Operação inversa: se 6 × 4 = 24, então 24 ÷ 6 = 4.' },
    { id:'2op_rmd_10', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:1,
      q:'➗ Qual a multiplicação que ajuda a calcular 35 ÷ 5?',
      opts:['5 × 7 = 35','5 × 6 = 30','5 + 7 = 12','5 × 8 = 40'], ans:0,
      exp:'5 × 7 = 35, logo 35 ÷ 5 = 7.' },
    { id:'2op_rmd_11', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:2,
      q:'➗ 72 ÷ 8 = ___ (Pensa: 8 × ? = 72)',
      ans:['9'],
      exp:'8 × 9 = 72, logo 72 ÷ 8 = 9.' },
    { id:'2op_rmd_12', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:2,
      q:'➗ Numa caixa cabem 6 bolos. Quantas caixas preciso para 54 bolos?',
      opts:['8','9','10','6'], ans:1,
      exp:'54 ÷ 6 = 9 caixas. (6 × 9 = 54).' },
    { id:'2op_rmd_13', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:2,
      q:'➗ A família de factos do 7 × 5 = 35 inclui também: 35 ÷ 7 = ___',
      ans:['5'],
      exp:'A divisão é a inversa: se 7 × 5 = 35, então 35 ÷ 7 = 5 e 35 ÷ 5 = 7.' },
    { id:'2op_rmd_14', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:3,
      q:'➗ A Eduarda dividiu 48 lápis igualmente por 6 colegas. Cada um ficou com:',
      opts:['7','8','6','9'], ans:1,
      exp:'48 ÷ 6 = 8 lápis cada (6 × 8 = 48).' },
    { id:'2op_rmd_15', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:3,
      q:'➗ Numa quinta há 81 árvores plantadas em 9 fileiras iguais. Quantas árvores em cada fileira?',
      ans:['9'],
      exp:'81 ÷ 9 = 9 árvores por fileira (9 × 9 = 81).' },
    { id:'2op_rmd_16', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:3,
      q:'➗ 63 doces para 9 crianças. Cada uma recebe quantos?',
      opts:['6','7','8','9'], ans:1,
      exp:'63 ÷ 9 = 7. (9 × 7 = 63).' },

    // ----- Cálculo mental (mais 8) -----
    { id:'2op_cm_11', s:'matematica', t:'Cálculo mental', type:'fill', diff:1,
      q:'🧠 36 + 100 = ___',
      ans:['136'],
      exp:'Somar 100 a 36 muda só a centena (adiciona 1 centena).' },
    { id:'2op_cm_12', s:'matematica', t:'Cálculo mental', type:'fill', diff:1,
      q:'🧠 Dobro de 30 = ___',
      ans:['60'],
      exp:'30 + 30 = 60. Ou 2 × 30 = 60.' },
    { id:'2op_cm_13', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 58 + 9 = ___ (truque +10−1)',
      ans:['67'],
      exp:'58 + 10 = 68; tira 1 = 67.' },
    { id:'2op_cm_14', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 73 − 11 = ___',
      ans:['62'],
      exp:'73 − 10 − 1 = 63 − 1 = 62. Decomposição.' },
    { id:'2op_cm_15', s:'matematica', t:'Cálculo mental', type:'mc', diff:2,
      q:'🧠 Metade de 100 + Metade de 60 = ?',
      opts:['60','80','100','120'], ans:1,
      exp:'Metade de 100 = 50. Metade de 60 = 30. 50 + 30 = 80.' },
    { id:'2op_cm_16', s:'matematica', t:'Cálculo mental', type:'fill', diff:3,
      q:'🧠 99 + 47 = ___ (truque: 100 + 47 − 1)',
      ans:['146'],
      exp:'100 + 47 = 147; tira 1 = 146.' },
    { id:'2op_cm_17', s:'matematica', t:'Cálculo mental', type:'fill', diff:3,
      q:'🧠 Soma 25 + 75 mentalmente: ___',
      ans:['100'],
      exp:'25 + 75 = 100. Truque: vê pares que somam dezenas redondas.' },
    { id:'2op_cm_18', s:'matematica', t:'Cálculo mental', type:'mc', diff:3,
      q:'🧠 64 + 28 mentalmente:',
      opts:['82','92','86','94'], ans:1,
      exp:'64 + 30 = 94; tira 2 = 92. Ou 60+20=80; 4+8=12; 80+12=92.' },

    // ----- Sequências de crescimento (mais 8) -----
    { id:'2op_seq_9', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Continua: 4, 8, 12, 16, ___',
      ans:['20'],
      exp:'Aumenta de 4 em 4 (tabuada do 4). 16 + 4 = 20.' },
    { id:'2op_seq_10', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Próximo: 1, 3, 5, 7, ___',
      ans:['9'],
      exp:'Aumenta de 2 em 2 (números ímpares). 7 + 2 = 9.' },
    { id:'2op_seq_11', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Qual é a regra? 6, 12, 18, 24, 30. Aumenta de ___ em ___',
      ans:['6'],
      exp:'12 − 6 = 6. Aumenta de 6 em 6 (múltiplos de 6).' },
    { id:'2op_seq_12', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Termo em falta: 25, 30, ___, 40, 45',
      ans:['35'],
      exp:'Aumenta de 5 em 5. 30 + 5 = 35.' },
    { id:'2op_seq_13', s:'matematica', t:'Sequências de crescimento', type:'mc', diff:2,
      q:'📈 Qual o 5.º termo de: 9, 18, 27, ...?',
      opts:['36','45','54','40'], ans:1,
      exp:'Tabuada do 9: 9, 18, 27, 36, 45. O 5.º é 45.' },
    { id:'2op_seq_14', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:3,
      q:'📈 Sequência decrescente: 30, 27, 24, ___, 18',
      ans:['21'],
      exp:'Diminui de 3 em 3. 24 − 3 = 21.' },
    { id:'2op_seq_15', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:3,
      q:'📈 Termo em falta: 0, 8, 16, ___, 32',
      ans:['24'],
      exp:'Aumenta de 8 em 8. 16 + 8 = 24.' },
    { id:'2op_seq_16', s:'matematica', t:'Sequências de crescimento', type:'mc', diff:3,
      q:'📈 Padrão figurativo: 1 quadrado, 2 quadrados, 4 quadrados, 8 quadrados. Próximo?',
      opts:['10','16','12','14'], ans:1,
      exp:'Cada termo DOBRA o anterior: 1→2→4→8→16.' },

    // ----- Perímetro (mais 8) -----
    { id:'2op_per_9', s:'matematica', t:'Perímetro', type:'fill', diff:1,
      q:'📏 Quadrado com 5 cm de lado. Perímetro = ___',
      ans:['20','20 cm','20cm'],
      exp:'4 × 5 = 20 cm.' },
    { id:'2op_per_10', s:'matematica', t:'Perímetro', type:'fill', diff:1,
      q:'📏 Triângulo equilátero com lados de 6 cm. Perímetro = ___',
      ans:['18','18 cm','18cm'],
      exp:'3 lados iguais. 3 × 6 = 18 cm.' },
    { id:'2op_per_11', s:'matematica', t:'Perímetro', type:'mc', diff:2,
      q:'📏 Retângulo com 10 cm de comprimento e 4 cm de largura tem perímetro:',
      opts:['14 cm','24 cm','28 cm','40 cm'], ans:2,
      exp:'2 × (10 + 4) = 2 × 14 = 28 cm.' },
    { id:'2op_per_12', s:'matematica', t:'Perímetro', type:'fill', diff:2,
      q:'📏 Hexágono regular (6 lados iguais) com lado de 5 cm. Perímetro = ___',
      ans:['30','30 cm','30cm'],
      exp:'6 × 5 = 30 cm.' },
    { id:'2op_per_13', s:'matematica', t:'Perímetro', type:'mc', diff:2,
      q:'📏 Para fazer o perímetro de qualquer polígono, faz-se:',
      opts:['Multiplicação dos lados','Soma de todos os lados','Divisão dos lados','Maior lado'], ans:1,
      exp:'Perímetro = SOMA dos comprimentos de todos os lados.' },
    { id:'2op_per_14', s:'matematica', t:'Perímetro', type:'fill', diff:3,
      q:'📏 Tens uma caixa retangular com 30 cm × 20 cm. Quantos cm de fita precisas para a contornar?',
      ans:['100','100 cm','100cm'],
      exp:'Perímetro = 2 × (30 + 20) = 2 × 50 = 100 cm.' },
    { id:'2op_per_15', s:'matematica', t:'Perímetro', type:'mc', diff:3,
      q:'📏 Um quadrado tem perímetro 48 m. Cada lado mede:',
      opts:['10 m','12 m','24 m','8 m'], ans:1,
      exp:'4 lados iguais → 48 ÷ 4 = 12 m.' },
    { id:'2op_per_16', s:'matematica', t:'Perímetro', type:'fill', diff:3,
      q:'📏 Triângulo com lados 7 cm, 10 cm e 8 cm. Perímetro = ___',
      ans:['25','25 cm','25cm'],
      exp:'7 + 10 + 8 = 25 cm.' },

    // ----- Ângulos retos (mais 8) -----
    { id:'2op_ang_9', s:'matematica', t:'Ângulos retos', type:'mc', diff:1,
      q:'📐 Um ângulo reto tem ___ graus.',
      opts:['45','60','90','180'], ans:2,
      exp:'O ângulo reto mede exactamente 90°.' },
    { id:'2op_ang_10', s:'matematica', t:'Ângulos retos', type:'tf', diff:1,
      q:'📐 Os ponteiros do relógio às 6 horas formam um ângulo reto.',
      ans:false,
      exp:'Falso. Às 6h formam um ângulo raso (180°). Às 3h ou 9h é que formam reto (90°).' },
    { id:'2op_ang_11', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Quantos ângulos retos tem um retângulo?',
      opts:['2','3','4','1'], ans:2,
      exp:'Um retângulo tem 4 cantos, todos a 90° — 4 ângulos retos.' },
    { id:'2op_ang_12', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Um ângulo de 45° é:',
      opts:['Reto','Agudo (menor que 90°)','Obtuso (maior que 90°)','Raso'], ans:1,
      exp:'45° < 90°, portanto é agudo.' },
    { id:'2op_ang_13', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Um ângulo de 120° é:',
      opts:['Agudo','Reto','Obtuso','Raso'], ans:2,
      exp:'120° > 90°, portanto é obtuso. (90° < obtuso < 180°)' },
    { id:'2op_ang_14', s:'matematica', t:'Ângulos retos', type:'tf', diff:3,
      q:'📐 Numa folha de papel em forma de quadrado há 4 ângulos retos.',
      ans:true,
      exp:'Verdadeiro. Um quadrado tem 4 cantos, todos retos.' },
    { id:'2op_ang_15', s:'matematica', t:'Ângulos retos', type:'mc', diff:3,
      q:'📐 Que objeto NÃO tem ângulos retos?',
      opts:['Livro','Janela','Bola','Quadro'], ans:2,
      exp:'A bola é redonda — não tem ângulos. Os outros são retangulares.' },
    { id:'2op_ang_16', s:'matematica', t:'Ângulos retos', type:'mc', diff:3,
      q:'📐 Um triângulo retângulo tem quantos ângulos retos?',
      opts:['Zero','Um','Dois','Três'], ans:1,
      exp:'Por definição, um triângulo retângulo tem EXATAMENTE 1 ângulo reto.' },

    // ----- Conetores (e, ou) (mais 8) -----
    { id:'2op_con_9', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:1,
      q:'🔗 "Hoje chove ___ está frio." Que conetor encaixa?',
      opts:['e','ou','sem','para'], ans:0,
      exp:'Chove E está frio — as duas coisas em conjunto. Adição.' },
    { id:'2op_con_10', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:1,
      q:'🔗 "Vou contigo de carro ___ de comboio?" Qual conetor?',
      opts:['e','ou','com','para'], ans:1,
      exp:'Escolha entre dois meios → OU.' },
    { id:'2op_con_11', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:1,
      q:'🔗 Liga: "Bebi água. Comi pão." → "Bebi água ___ comi pão."',
      ans:['e'],
      exp:'Duas ações em conjunto — "E".' },
    { id:'2op_con_12', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:2,
      q:'🔗 Em qual destas frases o "ou" NÃO está usado correctamente?',
      opts:['Café ou chá?','Hoje ou amanhã?','O cão ou o gato dormem no sofá juntos.','Vou andar ou correr.'], ans:2,
      exp:'A 3.ª frase usa "ou" mas diz que estão JUNTOS — devia ser "e". Não pode ser uma alternativa se ambos estão.' },
    { id:'2op_con_13', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:2,
      q:'🔗 Liga estas duas opções: "Posso fazer agora. Posso fazer mais tarde." → "Posso fazer agora ___ mais tarde."',
      ans:['ou'],
      exp:'Uma OU outra (alternativa).' },
    { id:'2op_con_14', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:3,
      q:'🔗 "Estuda muito ___ não passa de ano." Que ideia transmite?',
      opts:['Que vai estudar e passar','Tem de estudar OU haverá consequência','São coisas ao acaso','Sem sentido'], ans:1,
      exp:'"OU" aqui ameaça uma alternativa: ou estuda, ou não passa.' },
    { id:'2op_con_15', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:3,
      q:'🔗 Escolhe e ou ou: "Vou às compras ___ levo a lista de tudo o que preciso."',
      ans:['e'],
      exp:'As duas ações em conjunto — "E".' },
    { id:'2op_con_16', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:3,
      q:'🔗 Qual frase tem o conetor MAL usado?',
      opts:['Vou de bicicleta ou a pé.','O pão e o leite estão na mesa.','Comi maçã e gostei.','O cão ou o gato latem juntos.'], ans:3,
      exp:'A 4.ª — cães e gatos a latir JUNTOS deveria ser com "e" não "ou".' },

    // ----- Interjeições (mais 8) -----
    { id:'2op_int_9', s:'portugues', t:'Interjeições', type:'mc', diff:1,
      q:'❗ "Hurra!" exprime:',
      opts:['Tristeza','Alegria/aprovação','Dor','Surpresa negativa'], ans:1,
      exp:'"Hurra!" celebra — é alegria, aprovação.' },
    { id:'2op_int_10', s:'portugues', t:'Interjeições', type:'mc', diff:1,
      q:'❗ "Psiu!" usa-se para:',
      opts:['Cumprimentar','Pedir silêncio','Dizer adeus','Festejar'], ans:1,
      exp:'"Psiu!" pede silêncio ou chamar a atenção de alguém em segredo.' },
    { id:'2op_int_11', s:'portugues', t:'Interjeições', type:'fill', diff:2,
      q:'❗ Que interjeição usas para parabéns?',
      ans:['parabéns','parabéns!','viva','viva!','bravo','bravo!'],
      exp:'"Parabéns!", "Viva!" ou "Bravo!" são todas interjeições de celebração.' },
    { id:'2op_int_12', s:'portugues', t:'Interjeições', type:'mc', diff:2,
      q:'❗ "Caramba! Que sorte!" Que tipo de emoção exprime "Caramba!"?',
      opts:['Tristeza','Espanto/surpresa','Cansaço','Dor'], ans:1,
      exp:'"Caramba!" mostra espanto, surpresa.' },
    { id:'2op_int_13', s:'portugues', t:'Interjeições', type:'mc', diff:2,
      q:'❗ Qual NÃO é uma interjeição?',
      opts:['Ai!','Olá!','Mesa','Ufa!'], ans:2,
      exp:'"Mesa" é um nome (substantivo). As outras são interjeições.' },
    { id:'2op_int_14', s:'portugues', t:'Interjeições', type:'mc', diff:3,
      q:'❗ "Eh lá!" pode exprimir:',
      opts:['Surpresa ou admiração','Tristeza','Despedida','Ordem'], ans:0,
      exp:'"Eh lá!" mostra surpresa, espanto.' },
    { id:'2op_int_15', s:'portugues', t:'Interjeições', type:'mc', diff:3,
      q:'❗ Qual frase TEM 2 interjeições?',
      opts:['Olá! Bom dia.','O sol nasceu.','Ah! Coitado! Já passou tudo.','Ele foi à escola.'], ans:2,
      exp:'"Ah!" + "Coitado!" — duas interjeições na mesma frase.' },
    { id:'2op_int_16', s:'portugues', t:'Interjeições', type:'fill', diff:3,
      q:'❗ Completa com a interjeição apropriada: "___ ! Que dor, picou-me uma abelha!"',
      ans:['ai','ai!','ui','ui!'],
      exp:'"Ai!" ou "Ui!" exprime dor súbita.' },

    // ----- Determinantes artigos (mais 8) -----
    { id:'2op_da_9', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "As" é artigo:',
      opts:['Definido masculino','Definido feminino plural','Indefinido masculino','Indefinido feminino'], ans:1,
      exp:'"As" — definido, feminino, plural. (Ex: As meninas brincam.)' },
    { id:'2op_da_10', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "Uns" é artigo:',
      opts:['Definido masculino plural','Indefinido masculino plural','Possessivo','Demonstrativo'], ans:1,
      exp:'"Uns" — indefinido, masculino, plural. (Ex: Uns rapazes...)' },
    { id:'2op_da_11', s:'portugues', t:'Determinantes artigos', type:'fill', diff:2,
      q:'🔤 Preenche com artigo INDEFINIDO feminino singular: ___ bonita flor.',
      ans:['uma','Uma'],
      exp:'"Uma" — indefinido, feminino, singular.' },
    { id:'2op_da_12', s:'portugues', t:'Determinantes artigos', type:'mc', diff:2,
      q:'🔤 Em "Os pais da Maria são professores", quantos artigos definidos há?',
      opts:['1','2','3','0'], ans:1,
      exp:'2: "Os" (pais) e "a" dentro de "da" (de+a).' },
    { id:'2op_da_13', s:'portugues', t:'Determinantes artigos', type:'mc', diff:2,
      q:'🔤 Plural de "um menino":',
      opts:['o meninos','uns meninos','umas meninos','dos meninos'], ans:1,
      exp:'"um" no plural masculino = "uns". "Uns meninos".' },
    { id:'2op_da_14', s:'portugues', t:'Determinantes artigos', type:'mc', diff:3,
      q:'🔤 Em "O João viu uma princesa no jardim", quantos artigos há ao todo?',
      opts:['1','2','3','4'], ans:2,
      exp:'3 artigos: "O" (João), "uma" (princesa), "o" dentro de "no" = em + o (jardim).' },
    { id:'2op_da_15', s:'portugues', t:'Determinantes artigos', type:'fill', diff:3,
      q:'🔤 Completa: ___ cães correm e ___ gata dorme. (artigos definidos)',
      ans:['Os a','Os, a','os a'],
      exp:'"Os cães" (masc. plural) + "a gata" (fem. sing.).' },
    { id:'2op_da_16', s:'portugues', t:'Determinantes artigos', type:'mc', diff:3,
      q:'🔤 Que diferença há entre "a árvore" e "uma árvore"?',
      opts:['Nenhuma','"A" é definida (específica), "uma" é indefinida (qualquer)','"A" é plural','"Uma" não é determinante'], ans:1,
      exp:'A árvore = sei qual. Uma árvore = uma árvore qualquer, não específica.' },

    // ----- Sílaba átona (mais 8) -----
    { id:'2op_sa_9', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 Em "PE-na", qual é a sílaba átona?',
      opts:['PE','na','As duas','Nenhuma'], ans:1,
      exp:'PE-NA. Tónica = PE (mais forte). Átona = na (mais fraca).' },
    { id:'2op_sa_10', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 Em "li-VRO", a tónica é:',
      opts:['li','VRO','As duas','Nenhuma'], ans:1,
      exp:'LI-VRO. A força está em VRO. Tónica = VRO; átona = li.' },
    { id:'2op_sa_11', s:'portugues', t:'Sílaba átona', type:'fill', diff:2,
      q:'🔡 Sílabas átonas de "CA-be-ça" (escreve as que NÃO são tónicas, separadas por espaço):',
      ans:['be ça','ce ca','ce ça','be',':be ça'],
      exp:'CA-BE-ÇA. Tónica = CA. Átonas = be e ça.' },
    { id:'2op_sa_12', s:'portugues', t:'Sílaba átona', type:'mc', diff:2,
      q:'🔡 "Café" tem acento no E. Qual é a tónica?',
      opts:['CA','FÉ','As duas','Nenhuma'], ans:1,
      exp:'O acento gráfico MARCA a tónica. CA-FÉ → tónica FÉ.' },
    { id:'2op_sa_13', s:'portugues', t:'Sílaba átona', type:'fill', diff:2,
      q:'🔡 Quantas sílabas átonas tem "mochila"? (mo-CHI-la)',
      ans:['2','duas'],
      exp:'MO-CHI-LA. Tónica CHI. Átonas: mo e la = 2 átonas.' },
    { id:'2op_sa_14', s:'portugues', t:'Sílaba átona', type:'mc', diff:3,
      q:'🔡 Em "computador" (com-pu-ta-DOR), as átonas são:',
      opts:['com, pu, ta','DOR só','com, pu, DOR','Nenhuma'], ans:0,
      exp:'COM-PU-TA-DOR. Tónica = DOR. Átonas: com, pu, ta (3 átonas).' },
    { id:'2op_sa_15', s:'portugues', t:'Sílaba átona', type:'tf', diff:3,
      q:'🔡 Numa palavra só pode haver UMA sílaba tónica.',
      ans:true,
      exp:'Verdadeiro. Cada palavra tem APENAS 1 sílaba tónica. As outras são átonas.' },
    { id:'2op_sa_16', s:'portugues', t:'Sílaba átona', type:'mc', diff:3,
      q:'🔡 "Bo-NE-co" — tónica:',
      opts:['Bo','NE','co','Não há'], ans:1,
      exp:'BO-NE-CO. Força em NE. Tónica = NE; átonas = bo e co.' },

    // ----- Compreensão de texto (mais 8) -----
    { id:'2op_ct_9', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 "O Rui tem 8 anos. A irmã tem mais 2 anos que ele." Que idade tem a irmã?',
      opts:['8','10','6','12'], ans:1,
      exp:'8 + 2 = 10 anos.' },
    { id:'2op_ct_10', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 "Estavam 5 pássaros na árvore. Voaram 2." Quantos ficaram?',
      opts:['3','5','7','2'], ans:0,
      exp:'5 − 2 = 3 pássaros.' },
    { id:'2op_ct_11', s:'portugues', t:'Compreensão de texto', type:'mc', diff:2,
      q:'📖 "A Joana adora o seu cão Bobi. Hoje deu-lhe banho e levou-o ao parque." Como se chama o cão?',
      opts:['Toby','Bobi','Rex','Não diz'], ans:1,
      exp:'O texto diz "o seu cão Bobi".' },
    { id:'2op_ct_12', s:'portugues', t:'Compreensão de texto', type:'mc', diff:2,
      q:'📖 "Faltavam 3 dias para o aniversário do Pedro. Ele estava muito ansioso." O que sentia o Pedro?',
      opts:['Tédio','Ansiedade/expectativa','Tristeza','Indiferença'], ans:1,
      exp:'O texto diz "muito ansioso" — ansiedade pela festa.' },
    { id:'2op_ct_13', s:'portugues', t:'Compreensão de texto', type:'fill', diff:2,
      q:'📖 "A vovó fez sopa de legumes para o jantar." O que fez a vovó?',
      ans:['sopa','sopa de legumes'],
      exp:'O texto diz "fez sopa de legumes".' },
    { id:'2op_ct_14', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "Choveu o dia inteiro. As crianças não puderam ir ao parque, mas ficaram a jogar dentro de casa." Porque NÃO foram ao parque?',
      opts:['Não quiseram','Choveu o dia inteiro','Estavam doentes','O parque estava fechado'], ans:1,
      exp:'O texto explica que choveu o dia inteiro.' },
    { id:'2op_ct_15', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "A Laura tinha 12€. Comprou um livro de 5€ e um lápis de 1€." Quanto dinheiro ficou com ela?',
      opts:['7€','6€','5€','8€'], ans:1,
      exp:'5 + 1 = 6 gastos. 12 − 6 = 6€.' },
    { id:'2op_ct_16', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "O sol já tinha desaparecido quando o João chegou a casa." Quando chegou o João?',
      opts:['De manhã cedo','À tarde','Quando o sol se pôs (já era noite)','A meio do dia'], ans:2,
      exp:'"O sol já tinha desaparecido" — sugere fim do dia, anoitecer.' },

    // ----- Textos narrativos (mais 8) -----
    { id:'2op_tn_9', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 Em "Era uma vez uma princesa...", "uma princesa" é:',
      opts:['Personagem','Espaço','Tempo','Ação'], ans:0,
      exp:'É quem participa na história — personagem.' },
    { id:'2op_tn_10', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 "...vivia num castelo." "Castelo" é:',
      opts:['Personagem','Espaço (onde se passa)','Tempo','Ação'], ans:1,
      exp:'O lugar onde decorre a história — espaço.' },
    { id:'2op_tn_11', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 "Há muito tempo, num reino distante..." Que indicador de TEMPO está presente?',
      opts:['Há muito tempo','Num reino','Distante','Nenhum'], ans:0,
      exp:'"Há muito tempo" indica tempo (passado, distante).' },
    { id:'2op_tn_12', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 Numa narrativa, o "início" serve para:',
      opts:['Resolver o conflito','Apresentar personagens, espaço, tempo','Terminar a história','Pôr os créditos'], ans:1,
      exp:'O início (introdução) apresenta personagens, lugar, tempo.' },
    { id:'2op_tn_13', s:'portugues', t:'Textos narrativos', type:'fill', diff:2,
      q:'📚 As 3 partes principais de uma narrativa são: início, ___ e fim.',
      ans:['meio','desenvolvimento'],
      exp:'Início → meio (desenvolvimento) → fim (conclusão).' },
    { id:'2op_tn_14', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 Diferença entre AUTOR e NARRADOR:',
      opts:['São a mesma coisa','Autor é a pessoa real que escreve; narrador é a voz dentro da história','Autor é a personagem','Narrador é o leitor'], ans:1,
      exp:'AUTOR = quem escreveu (pessoa real). NARRADOR = quem conta a história dentro do texto.' },
    { id:'2op_tn_15', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 "Eu fui à floresta e vi um lobo." A narração é em:',
      opts:['1.ª pessoa','3.ª pessoa','Sem narrador','Em segredo'], ans:0,
      exp:'Eu/me/meu → 1.ª pessoa. O narrador participa na história.' },
    { id:'2op_tn_16', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 "Ele foi à floresta e viu um lobo." A narração é em:',
      opts:['1.ª pessoa','3.ª pessoa','Sem personagens','No futuro'], ans:1,
      exp:'Ele/ela/eles → 3.ª pessoa. O narrador conta de fora.' },

    // ----- Poesia e BD (mais 8) -----
    { id:'2op_pbd_9', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'📜 "Sol" e "lua" rimam?',
      opts:['Sim','Não'], ans:1,
      exp:'Não rimam. "Sol" termina em -ol, "lua" termina em -ua. Sons finais diferentes.' },
    { id:'2op_pbd_10', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'📜 "Mar" e "luar" rimam?',
      opts:['Sim','Não'], ans:0,
      exp:'Sim! Ambas terminam em -ar. Rimam.' },
    { id:'2op_pbd_11', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'💬 Numa BD, o que se ouve (sons como "BUM!") chama-se:',
      opts:['Onomatopeia','Verso','Personagem','Estrofe'], ans:0,
      exp:'Onomatopeia = palavra que imita um som.' },
    { id:'2op_pbd_12', s:'portugues', t:'Poesia e BD', type:'fill', diff:2,
      q:'📜 Estrofe com 4 versos chama-se ___',
      ans:['quadra'],
      exp:'Quadra = 4 versos. Terceto = 3. Dístico = 2.' },
    { id:'2op_pbd_13', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'💬 Numa BD, um balão de pensamento tem:',
      opts:['Contorno liso','Contorno em bolhas','Sem contorno','Letras a vermelho'], ans:1,
      exp:'Balão de pensamento tem contorno em forma de pequenas bolhas/nuvens.' },
    { id:'2op_pbd_14', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'📜 "ZÁS!" "PAFT!" "TILIM!" são exemplos de:',
      opts:['Versos','Onomatopeias','Estrofes','Personagens'], ans:1,
      exp:'Todas são palavras que imitam sons — onomatopeias.' },
    { id:'2op_pbd_15', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'💬 Numa BD, cada quadradinho com uma cena chama-se:',
      opts:['Verso','Vinheta','Estrofe','Estrela'], ans:1,
      exp:'Vinheta = cada quadradinho. Conjunto de vinhetas = página de BD.' },
    { id:'2op_pbd_16', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'📜 Uma poesia SEM rima chama-se:',
      opts:['Sem versos','Verso branco/livre','Prosa','Música'], ans:1,
      exp:'Verso branco (ou livre) — poesia sem rima fixa, mas continua a ter ritmo e versos.' },

    // ----- Portugal na Europa e no mundo (mais 8) -----
    { id:'2op_pem_9', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🌍 A Península Ibérica é formada por:',
      opts:['Portugal e França','Portugal e Espanha','Espanha e Itália','Portugal e Marrocos'], ans:1,
      exp:'Portugal + Espanha formam a Península Ibérica.' },
    { id:'2op_pem_10', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'tf', diff:1,
      q:'🌍 A Madeira é uma região autónoma de Portugal.',
      ans:true,
      exp:'Verdadeiro. A Madeira e os Açores são Regiões Autónomas (arquipélagos).' },
    { id:'2op_pem_11', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:2,
      q:'🇵🇹 A bandeira de Portugal tem as cores:',
      opts:['Azul e amarelo','Verde e vermelho','Vermelho e branco','Azul e branco'], ans:1,
      exp:'A bandeira de Portugal é VERDE e VERMELHA, com o escudo no centro.' },
    { id:'2op_pem_12', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'fill', diff:2,
      q:'🇵🇹 O hino nacional português chama-se ___',
      ans:['A Portuguesa','a portuguesa'],
      exp:'O hino chama-se "A Portuguesa".' },
    { id:'2op_pem_13', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:2,
      q:'🌊 Os arquipélagos dos Açores e da Madeira estão no:',
      opts:['Mar Mediterrâneo','Oceano Atlântico','Mar Báltico','Oceano Pacífico'], ans:1,
      exp:'Ambos os arquipélagos estão no Oceano Atlântico.' },
    { id:'2op_pem_14', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:3,
      q:'🌍 Qual destes países fala português?',
      opts:['Espanha','Itália','Brasil','França'], ans:2,
      exp:'O Brasil é o maior país de língua portuguesa do mundo.' },
    { id:'2op_pem_15', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'fill', diff:3,
      q:'🎂 Em que dia se comemora o Dia de Portugal (mês e dia)?',
      ans:['10 de junho','10 junho','10/06'],
      exp:'10 de junho — Dia de Portugal, de Camões e das Comunidades.' },
    { id:'2op_pem_16', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:3,
      q:'🌍 Os países africanos que falam português incluem:',
      opts:['Egipto e Líbia','Angola e Moçambique','Marrocos e Argélia','África do Sul'], ans:1,
      exp:'Angola, Moçambique, Cabo Verde, S. Tomé e Príncipe, Guiné-Bissau são países lusófonos africanos.' },

    // ----- Influências de outras culturas (mais 8) -----
    { id:'2op_inf_9', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:1,
      q:'🌍 Pessoas que vêm viver para Portugal de outros países chamam-se:',
      opts:['Turistas','Imigrantes','Trabalhadores','Embaixadores'], ans:1,
      exp:'Imigrantes = pessoas que vêm de outro país para viver. Emigrantes = portugueses que saem.' },
    { id:'2op_inf_10', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:1,
      q:'🍫 O chocolate (cacau) veio originalmente da:',
      opts:['Europa','América','Ásia','Antárctida'], ans:1,
      exp:'O cacau é originário da América Central e do Sul. Veio para a Europa após os Descobrimentos.' },
    { id:'2op_inf_11', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:2,
      q:'🍞 A palavra "almofada" tem origem:',
      opts:['Latina','Árabe','Francesa','Inglesa'], ans:1,
      exp:'"Almofada", "azeite", "alface" — todas vêm do árabe (presença em Portugal há séculos).' },
    { id:'2op_inf_12', s:'estudo_meio', t:'Influências de outras culturas', type:'tf', diff:2,
      q:'🌍 Aprender línguas estrangeiras ajuda-nos a conhecer outras culturas.',
      ans:true,
      exp:'Verdadeiro. Saber uma língua abre janelas para a cultura desse povo.' },
    { id:'2op_inf_13', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:2,
      q:'🌍 A festa do "Halloween" tem origem:',
      opts:['Portuguesa','Celta/EUA','Brasileira','Espanhola'], ans:1,
      exp:'Halloween tem origem celta (antigos povos da Europa) e ficou famosa pelos EUA.' },
    { id:'2op_inf_14', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'🌍 Por que é importante respeitar a cultura dos outros?',
      opts:['Para sermos como eles','Para vivermos em paz e aprendermos','Porque é obrigatório','Para imitar'], ans:1,
      exp:'Respeitar permite convivência pacífica e aprendizagem mútua.' },
    { id:'2op_inf_15', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'🌍 "Pizza", "spaghetti", "lasanha" são exemplos de:',
      opts:['Comida portuguesa','Influência italiana na alimentação','Festas religiosas','Línguas estrangeiras'], ans:1,
      exp:'Todas estas comidas vêm da Itália. Influência italiana na nossa alimentação.' },
    { id:'2op_inf_16', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'👗 Um "sari" é uma roupa tradicional de que país?',
      opts:['Japão','Índia','Brasil','EUA'], ans:1,
      exp:'O sari é uma roupa tradicional feminina da Índia.' },

    // ----- Múltiplas pertenças e grupos (mais 8) -----
    { id:'2op_mp_9', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:1,
      q:'👫 O grupo mais próximo de uma criança é:',
      opts:['A turma','A família','O país','A vizinhança'], ans:1,
      exp:'A família é o primeiro grupo de pertença, o mais próximo e importante.' },
    { id:'2op_mp_10', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'tf', diff:1,
      q:'👨‍👩‍👧 Há diferentes tipos de família e todas são válidas.',
      ans:true,
      exp:'Verdadeiro. Famílias com pai e mãe, só com mãe ou pai, com avós, adotivas — todas são famílias.' },
    { id:'2op_mp_11', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:2,
      q:'⚽ Pertencer a um clube significa:',
      opts:['Pagar muito','Ser membro de um grupo desportivo/cultural','Não conhecer ninguém','Estar sozinho'], ans:1,
      exp:'Clube = grupo organizado, geralmente desportivo, cultural ou recreativo.' },
    { id:'2op_mp_12', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:2,
      q:'🏫 Quem faz parte da escola, além dos alunos?',
      opts:['Só os professores','Professores, auxiliares, cantineiros, etc.','Só o diretor','Só o porteiro'], ans:1,
      exp:'A comunidade escolar inclui muita gente: professores, auxiliares, cozinheiros, etc.' },
    { id:'2op_mp_13', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'tf', diff:2,
      q:'🌍 Posso pertencer ao mesmo tempo à minha família, escola e a um clube de futebol.',
      ans:true,
      exp:'Verdadeiro. São múltiplas pertenças — vários grupos em simultâneo.' },
    { id:'2op_mp_14', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🤝 Quando um colega NOVO chega à turma, devemos:',
      opts:['Ignorá-lo','Acolher e ajudar a integrar','Rir dele','Não falar'], ans:1,
      exp:'Acolher e ajudar a integrar — é o que esperamos que façam por nós também.' },
    { id:'2op_mp_15', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🌍 A diversidade dentro de um grupo é:',
      opts:['Um problema','Uma riqueza — aprendemos mais','Uma confusão','Para evitar'], ans:1,
      exp:'A diversidade enriquece os grupos. Vemos várias perspectivas.' },
    { id:'2op_mp_16', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🇵🇹 Pertencer ao "país" significa:',
      opts:['Ser o presidente','Ser cidadão de um lugar (com a sua cultura)','Pagar passaporte','Falar inglês'], ans:1,
      exp:'Pertencer a um país = ser cidadão dele, partilhar a sua cultura e identidade.' },

    // ----- Direitos da criança (mais 8) -----
    { id:'2op_dc_9', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:1,
      q:'📚 Toda a criança tem o direito de:',
      opts:['Trabalhar','Estudar e ir à escola','Conduzir','Votar'], ans:1,
      exp:'Direito à educação — fundamental para todas as crianças.' },
    { id:'2op_dc_10', s:'estudo_meio', t:'Direitos da criança', type:'tf', diff:1,
      q:'🎈 Brincar é um direito da criança.',
      ans:true,
      exp:'Verdadeiro. O direito ao lazer e à brincadeira está protegido na Convenção.' },
    { id:'2op_dc_11', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:2,
      q:'🏥 Quando uma criança está doente, deve poder:',
      opts:['Esperar até crescer','Ter cuidados médicos','Pagar antes','Trabalhar'], ans:1,
      exp:'Direito à saúde — toda a criança deve ter cuidados médicos.' },
    { id:'2op_dc_12', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:2,
      q:'🏠 As crianças têm direito a viver:',
      opts:['Sozinhas','Em ambiente seguro com adultos que cuidam','Onde quiserem','Em qualquer lugar'], ans:1,
      exp:'Direito à proteção familiar — ambiente seguro com pais ou cuidadores.' },
    { id:'2op_dc_13', s:'estudo_meio', t:'Direitos da criança', type:'tf', diff:2,
      q:'🛡️ Nenhuma criança pode ser maltratada ou explorada no trabalho.',
      ans:true,
      exp:'Verdadeiro. O trabalho infantil e maus-tratos são proibidos pela Convenção.' },
    { id:'2op_dc_14', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'📋 Em que ano foi aprovada a Convenção dos Direitos da Criança?',
      opts:['1900','1945','1989','2010'], ans:2,
      exp:'1989 — aprovada pelas Nações Unidas.' },
    { id:'2op_dc_15', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'🌍 Em Portugal, a comissão que protege crianças em risco chama-se:',
      opts:['CPCJ','UNICEF','OMS','UE'], ans:0,
      exp:'CPCJ = Comissão de Proteção de Crianças e Jovens. Atua em todos os municípios.' },
    { id:'2op_dc_16', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'🗣️ As crianças têm direito a:',
      opts:['Estar sempre caladas','Dar a sua opinião e ser ouvidas','Mandar nos adultos','Não pensar'], ans:1,
      exp:'Direito de participação — expressar opinião e ser ouvida.' },

    // ----- Diálogo e compromisso (mais 8) -----
    { id:'2op_di_9', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:1,
      q:'💬 Quando alguém está a falar comigo, devo:',
      opts:['Falar mais alto que ele','Olhar para o telemóvel','Ouvir com atenção','Sair'], ans:2,
      exp:'Ouvir com atenção é o primeiro passo de um bom diálogo.' },
    { id:'2op_di_10', s:'estudo_meio', t:'Diálogo e compromisso', type:'tf', diff:1,
      q:'🤝 Cumprimentar com "bom dia" e "obrigado" mostra respeito.',
      ans:true,
      exp:'Verdadeiro. São palavras de boa educação que mostram respeito.' },
    { id:'2op_di_11', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:2,
      q:'⚖️ Se houver conflito entre amigos, a melhor solução é:',
      opts:['Lutar','Calar e esperar','Conversar e procurar um meio-termo','Pedir ao professor sempre'], ans:2,
      exp:'Diálogo + compromisso — cada um cede um pouco para todos ficarem bem.' },
    { id:'2op_di_12', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:2,
      q:'🤝 Um "compromisso" entre duas pessoas significa:',
      opts:['Uma só decide','Cada um cede um pouco para chegar a acordo','Ambos perdem','Nada muda'], ans:1,
      exp:'Compromisso = acordo onde cada parte cede algo para chegar a uma solução comum.' },
    { id:'2op_di_13', s:'estudo_meio', t:'Diálogo e compromisso', type:'tf', diff:2,
      q:'💬 Posso discordar de alguém sem ser desrespeitoso.',
      ans:true,
      exp:'Verdadeiro. Discordar é normal — mas devemos exprimir a opinião sem ofender.' },
    { id:'2op_di_14', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🤝 Se prometi à minha mãe que arrumava o quarto, o melhor é:',
      opts:['Esquecer','Cumprir','Atrasar sempre','Pedir à irmã'], ans:1,
      exp:'Cumprir compromissos — é assim que se constrói confiança.' },
    { id:'2op_di_15', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🌟 Numa discussão, devo:',
      opts:['Falar primeiro sempre','Ouvir o outro, depois explicar a minha visão','Gritar mais alto','Não responder'], ans:1,
      exp:'Bom diálogo: ouvir primeiro, depois falar com calma e respeito.' },
    { id:'2op_di_16', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🏫 As regras da turma cumprem-se melhor quando:',
      opts:['São impostas pelo professor','Todos participam a defini-las','Ninguém sabe','São escondidas'], ans:1,
      exp:'Quando todos participam na criação das regras, sentem-nas como suas e cumprem-nas mais facilmente.' }

];

// Limpar campo 'eque' (typo) — fallback se algum exercicio tiver atributo incorreto
for (const e of EXERCISES_2_ORIENT_P3) { if (e.eque !== undefined) delete e.eque; }

if (typeof window !== 'undefined') window.EXERCISES_2_ORIENT_P3 = EXERCISES_2_ORIENT_P3;
