// EscolaPlay - Top-up dificuldade 3 do 2.º ano - Matemática (gerado, alinhado com Supermiúdos)
// Exercícios diff:3 para 17 tópicos sem dif. alta + diff:1 para 4 tópicos sem dif. baixa.
const EXERCISES_2_M_EXTRA3 = [
  // ===== Números até 100 (diff:3) =====
  { id:'2me3_001', s:'matematica', t:'Números até 100', type:'mc', diff:3,
    q:'🔢 Qual destes números é maior: 79 ou 97?',
    opts:['79','97','São iguais','Não dá para saber'], ans:1,
    exp:'97 é maior que 79 porque tem 9 dezenas e o 79 só tem 7 dezenas.' },
  { id:'2me3_002', s:'matematica', t:'Números até 100', type:'fill', diff:3,
    q:'🔢 Ordena do menor para o maior: 45, 54, 44. O do meio é ___.',
    ans:['45','quarenta e cinco'],
    exp:'Por ordem: 44, 45, 54. O número do meio é o 45.' },
  { id:'2me3_003', s:'matematica', t:'Números até 100', type:'tf', diff:3,
    q:'🔢 O número 38 é par. Verdadeiro ou falso?',
    ans:true,
    exp:'38 acaba em 8. Os números pares acabam em 0, 2, 4, 6 ou 8.' },
  { id:'2me3_004', s:'matematica', t:'Números até 100', type:'mc', diff:3,
    q:'🔢 Que número vem logo a seguir a 89?',
    opts:['88','90','99','80'], ans:1,
    exp:'A seguir a 89 vem 90. Sobe-se uma unidade.' },
  { id:'2me3_005', s:'matematica', t:'Números até 100', type:'mc', diff:3,
    q:'🔢 Qual destes números é ímpar?',
    opts:['24','46','37','60'], ans:2,
    exp:'37 acaba em 7. Os números ímpares acabam em 1, 3, 5, 7 ou 9.' },

  // ===== Tabuada do 2 (diff:3) =====
  { id:'2me3_006', s:'matematica', t:'Tabuada do 2', type:'fill', diff:3,
    q:'✖️ A Ana tem 6 sacos com 2 maçãs em cada. Quantas maçãs tem ao todo?',
    ans:['12','doze'],
    exp:'6 × 2 = 12 maçãs.' },
  { id:'2me3_007', s:'matematica', t:'Tabuada do 2', type:'mc', diff:3,
    q:'✖️ Cada bicicleta tem 2 rodas. Quantas rodas têm 8 bicicletas?',
    opts:['10','14','16','18'], ans:2,
    exp:'8 × 2 = 16 rodas.' },
  { id:'2me3_008', s:'matematica', t:'Tabuada do 2', type:'fill', diff:3,
    q:'✖️ 2 × ___ = 14. Que número falta?',
    ans:['7','sete'],
    exp:'2 × 7 = 14. O número que falta é o 7.' },
  { id:'2me3_009', s:'matematica', t:'Tabuada do 2', type:'tf', diff:3,
    q:'✖️ 2 × 9 dá o mesmo que 9 × 2. Verdadeiro ou falso?',
    ans:true,
    exp:'Trocar a ordem dá o mesmo resultado: 18.' },
  { id:'2me3_010', s:'matematica', t:'Tabuada do 2', type:'mc', diff:3,
    q:'✖️ O Tomás tinha 5 pares de meias. Quantas meias tem no total?',
    opts:['7','10','12','15'], ans:1,
    exp:'Cada par tem 2 meias. 5 × 2 = 10 meias.' },

  // ===== Tabuada do 5 (diff:3) =====
  { id:'2me3_011', s:'matematica', t:'Tabuada do 5', type:'fill', diff:3,
    q:'✖️ A mãe deu 5 cêntimos a cada um dos 7 amigos. Quantos cêntimos deu ao todo?',
    ans:['35','trinta e cinco'],
    exp:'7 × 5 = 35 cêntimos.' },
  { id:'2me3_012', s:'matematica', t:'Tabuada do 5', type:'mc', diff:3,
    q:'✖️ Cada caixa tem 5 lápis. Quantos lápis há em 6 caixas?',
    opts:['25','30','35','40'], ans:1,
    exp:'6 × 5 = 30 lápis.' },
  { id:'2me3_013', s:'matematica', t:'Tabuada do 5', type:'fill', diff:3,
    q:'✖️ 5 × ___ = 45. Que número falta?',
    ans:['9','nove'],
    exp:'5 × 9 = 45. O número que falta é o 9.' },
  { id:'2me3_014', s:'matematica', t:'Tabuada do 5', type:'mc', diff:3,
    q:'✖️ Numa mão temos 5 dedos. Quantos dedos há em 4 mãos?',
    opts:['15','18','20','25'], ans:2,
    exp:'4 × 5 = 20 dedos.' },
  { id:'2me3_015', s:'matematica', t:'Tabuada do 5', type:'fill', diff:3,
    q:'✖️ 8 × 5 = ___',
    ans:['40','quarenta'],
    exp:'8 × 5 = 40.' },

  // ===== Tabuada do 10 (diff:3) =====
  { id:'2me3_016', s:'matematica', t:'Tabuada do 10', type:'fill', diff:3,
    q:'✖️ Cada saco tem 10 rebuçados. Quantos rebuçados há em 7 sacos?',
    ans:['70','setenta'],
    exp:'7 × 10 = 70 rebuçados.' },
  { id:'2me3_017', s:'matematica', t:'Tabuada do 10', type:'mc', diff:3,
    q:'✖️ 10 × 8 = ?',
    opts:['18','70','80','90'], ans:2,
    exp:'10 × 8 = 80. Para multiplicar por 10 basta juntar um zero.' },
  { id:'2me3_018', s:'matematica', t:'Tabuada do 10', type:'fill', diff:3,
    q:'✖️ 10 × ___ = 60. Que número falta?',
    ans:['6','seis'],
    exp:'10 × 6 = 60. O número que falta é o 6.' },
  { id:'2me3_019', s:'matematica', t:'Tabuada do 10', type:'tf', diff:3,
    q:'✖️ 10 × 9 é maior do que 10 × 8. Verdadeiro ou falso?',
    ans:true,
    exp:'10 × 9 = 90 e 10 × 8 = 80. 90 é maior do que 80.' },
  { id:'2me3_020', s:'matematica', t:'Tabuada do 10', type:'mc', diff:3,
    q:'✖️ A Sofia leu 10 páginas por dia durante 5 dias. Quantas páginas leu?',
    opts:['15','40','50','55'], ans:2,
    exp:'5 × 10 = 50 páginas.' },

  // ===== Tabuada do 3 (diff:3) =====
  { id:'2me3_021', s:'matematica', t:'Tabuada do 3', type:'fill', diff:3,
    q:'✖️ Cada triciclo tem 3 rodas. Quantas rodas têm 6 triciclos?',
    ans:['18','dezoito'],
    exp:'6 × 3 = 18 rodas.' },
  { id:'2me3_022', s:'matematica', t:'Tabuada do 3', type:'mc', diff:3,
    q:'✖️ 3 × 7 = ?',
    opts:['18','21','24','27'], ans:1,
    exp:'3 × 7 = 21.' },
  { id:'2me3_023', s:'matematica', t:'Tabuada do 3', type:'fill', diff:3,
    q:'✖️ 3 × ___ = 24. Que número falta?',
    ans:['8','oito'],
    exp:'3 × 8 = 24. O número que falta é o 8.' },
  { id:'2me3_024', s:'matematica', t:'Tabuada do 3', type:'mc', diff:3,
    q:'✖️ O Rui comeu 3 bolachas em cada lanche. Em 9 lanches, quantas bolachas comeu?',
    opts:['18','24','27','30'], ans:2,
    exp:'9 × 3 = 27 bolachas.' },
  { id:'2me3_025', s:'matematica', t:'Tabuada do 3', type:'fill', diff:3,
    q:'✖️ 3 × 5 = ___',
    ans:['15','quinze'],
    exp:'3 × 5 = 15.' },

  // ===== Comprimento (diff:3) =====
  { id:'2me3_026', s:'matematica', t:'Comprimento', type:'mc', diff:3,
    q:'📏 Qual é maior: 1 metro ou 90 centímetros?',
    opts:['1 metro','90 cm','São iguais','Depende'], ans:0,
    exp:'1 metro tem 100 cm. 100 é maior do que 90.' },
  { id:'2me3_027', s:'matematica', t:'Comprimento', type:'fill', diff:3,
    q:'📏 Uma fita tem 80 cm e outra tem 50 cm. Quantos cm tem ao todo?',
    ans:['130','cento e trinta'],
    exp:'80 + 50 = 130 cm.' },
  { id:'2me3_028', s:'matematica', t:'Comprimento', type:'tf', diff:3,
    q:'📏 1 metro é igual a 100 cm. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. 1 m = 100 cm.' },
  { id:'2me3_029', s:'matematica', t:'Comprimento', type:'mc', diff:3,
    q:'📏 O lápis do João mede 15 cm e o da Maria mede 12 cm. Quantos cm o do João é maior?',
    opts:['2 cm','3 cm','5 cm','7 cm'], ans:1,
    exp:'15 - 12 = 3 cm.' },
  { id:'2me3_030', s:'matematica', t:'Comprimento', type:'mc', diff:3,
    q:'📏 Que objeto mede mais ou menos 1 metro?',
    opts:['Um lápis','Uma porta','Um livro','Uma moeda'], ans:1,
    exp:'Uma porta tem cerca de 2 metros. Mas, das opções, é a única perto de 1 metro de largura.' },

  // ===== Massa (diff:3) =====
  { id:'2me3_031', s:'matematica', t:'Massa', type:'mc', diff:3,
    q:'⚖️ Qual é mais pesado: 1 kg de algodão ou 1 kg de pedras?',
    opts:['Algodão','Pedras','Pesam o mesmo','Não dá para saber'], ans:2,
    exp:'1 kg é sempre 1 kg. Pesam o mesmo!' },
  { id:'2me3_032', s:'matematica', t:'Massa', type:'fill', diff:3,
    q:'⚖️ A Joana pesa 25 kg e o irmão pesa 18 kg. Quantos kg pesam juntos?',
    ans:['43','quarenta e três'],
    exp:'25 + 18 = 43 kg.' },
  { id:'2me3_033', s:'matematica', t:'Massa', type:'tf', diff:3,
    q:'⚖️ 1 kg é igual a 1000 gramas. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. 1 quilo tem 1000 gramas.' },
  { id:'2me3_034', s:'matematica', t:'Massa', type:'mc', diff:3,
    q:'⚖️ Quanto pesa, mais ou menos, uma maçã?',
    opts:['200 g','5 kg','20 kg','100 kg'], ans:0,
    exp:'Uma maçã pesa cerca de 200 gramas.' },
  { id:'2me3_035', s:'matematica', t:'Massa', type:'mc', diff:3,
    q:'⚖️ Um saco tem 3 kg. Outro tem 5 kg. Qual é a diferença?',
    opts:['1 kg','2 kg','3 kg','8 kg'], ans:1,
    exp:'5 - 3 = 2 kg.' },

  // ===== Capacidade (diff:3) =====
  { id:'2me3_036', s:'matematica', t:'Capacidade', type:'mc', diff:3,
    q:'🥤 Uma garrafa tem 2 litros e outra tem 1 litro. Quantos litros têm juntas?',
    opts:['1 L','2 L','3 L','4 L'], ans:2,
    exp:'2 + 1 = 3 litros.' },
  { id:'2me3_037', s:'matematica', t:'Capacidade', type:'fill', diff:3,
    q:'🥤 O depósito tem 10 L de água. Tiraram 4 L. Quantos litros restam?',
    ans:['6','seis'],
    exp:'10 - 4 = 6 litros.' },
  { id:'2me3_038', s:'matematica', t:'Capacidade', type:'tf', diff:3,
    q:'🥤 Uma piscina tem mais litros do que um copo. Verdadeiro ou falso?',
    ans:true,
    exp:'Claro! A piscina é muito maior do que um copo.' },
  { id:'2me3_039', s:'matematica', t:'Capacidade', type:'mc', diff:3,
    q:'🥤 Que recipiente leva mais ou menos 1 litro?',
    opts:['Uma colher','Um pacote de leite','Uma piscina','Uma gota'], ans:1,
    exp:'Um pacote de leite tem cerca de 1 litro.' },
  { id:'2me3_040', s:'matematica', t:'Capacidade', type:'mc', diff:3,
    q:'🥤 Tinha 5 L de sumo. Bebi 2 L de manhã e 1 L à tarde. Quantos L sobram?',
    opts:['1 L','2 L','3 L','4 L'], ans:1,
    exp:'5 - 2 - 1 = 2 litros.' },

  // ===== Tabuada do 6 (diff:3) =====
  { id:'2me3_041', s:'matematica', t:'Tabuada do 6', type:'fill', diff:3,
    q:'✖️ Cada caixa tem 6 ovos. Quantos ovos há em 4 caixas?',
    ans:['24','vinte e quatro'],
    exp:'4 × 6 = 24 ovos.' },
  { id:'2me3_042', s:'matematica', t:'Tabuada do 6', type:'mc', diff:3,
    q:'✖️ 6 × 5 = ?',
    opts:['25','30','35','36'], ans:1,
    exp:'6 × 5 = 30.' },
  { id:'2me3_043', s:'matematica', t:'Tabuada do 6', type:'fill', diff:3,
    q:'✖️ 6 × ___ = 18. Que número falta?',
    ans:['3','três'],
    exp:'6 × 3 = 18. O número que falta é o 3.' },
  { id:'2me3_044', s:'matematica', t:'Tabuada do 6', type:'mc', diff:3,
    q:'✖️ Cada aranha tem 6 patas (digamos). Quantas patas têm 7 aranhas?',
    opts:['36','40','42','48'], ans:2,
    exp:'7 × 6 = 42 patas.' },
  { id:'2me3_045', s:'matematica', t:'Tabuada do 6', type:'fill', diff:3,
    q:'✖️ 6 × 6 = ___',
    ans:['36','trinta e seis'],
    exp:'6 × 6 = 36.' },

  // ===== Tabuada do 8 (diff:3) =====
  { id:'2me3_046', s:'matematica', t:'Tabuada do 8', type:'fill', diff:3,
    q:'✖️ Cada polvo tem 8 braços. Quantos braços têm 3 polvos?',
    ans:['24','vinte e quatro'],
    exp:'3 × 8 = 24 braços.' },
  { id:'2me3_047', s:'matematica', t:'Tabuada do 8', type:'mc', diff:3,
    q:'✖️ 8 × 5 = ?',
    opts:['30','35','40','45'], ans:2,
    exp:'8 × 5 = 40.' },
  { id:'2me3_048', s:'matematica', t:'Tabuada do 8', type:'fill', diff:3,
    q:'✖️ 8 × ___ = 32. Que número falta?',
    ans:['4','quatro'],
    exp:'8 × 4 = 32. O número que falta é o 4.' },
  { id:'2me3_049', s:'matematica', t:'Tabuada do 8', type:'mc', diff:3,
    q:'✖️ A Inês juntou 6 grupos de 8 cromos. Quantos cromos juntou?',
    opts:['42','46','48','56'], ans:2,
    exp:'6 × 8 = 48 cromos.' },
  { id:'2me3_050', s:'matematica', t:'Tabuada do 8', type:'fill', diff:3,
    q:'✖️ 8 × 2 = ___',
    ans:['16','dezasseis'],
    exp:'8 × 2 = 16.' },

  // ===== Tabuada do 9 (diff:3) =====
  { id:'2me3_051', s:'matematica', t:'Tabuada do 9', type:'fill', diff:3,
    q:'✖️ 9 × 3 = ___',
    ans:['27','vinte e sete'],
    exp:'9 × 3 = 27.' },
  { id:'2me3_052', s:'matematica', t:'Tabuada do 9', type:'mc', diff:3,
    q:'✖️ Cada caixa tem 9 lápis. Quantos lápis há em 4 caixas?',
    opts:['27','32','36','40'], ans:2,
    exp:'4 × 9 = 36 lápis.' },
  { id:'2me3_053', s:'matematica', t:'Tabuada do 9', type:'fill', diff:3,
    q:'✖️ 9 × ___ = 45. Que número falta?',
    ans:['5','cinco'],
    exp:'9 × 5 = 45. O número que falta é o 5.' },
  { id:'2me3_054', s:'matematica', t:'Tabuada do 9', type:'mc', diff:3,
    q:'✖️ 9 × 6 = ?',
    opts:['45','54','56','63'], ans:1,
    exp:'9 × 6 = 54.' },
  { id:'2me3_055', s:'matematica', t:'Tabuada do 9', type:'tf', diff:3,
    q:'✖️ 9 × 2 = 2 × 9. Verdadeiro ou falso?',
    ans:true,
    exp:'Trocar a ordem dá o mesmo: 18.' },

  // ===== Divisão (diff:3) =====
  { id:'2me3_056', s:'matematica', t:'Divisão', type:'fill', diff:3,
    q:'➗ A mãe tem 12 bolachas para dar a 4 amigos. Quantas bolachas dá a cada um?',
    ans:['3','três'],
    exp:'12 ÷ 4 = 3 bolachas para cada um.' },
  { id:'2me3_057', s:'matematica', t:'Divisão', type:'mc', diff:3,
    q:'➗ 20 ÷ 5 = ?',
    opts:['2','3','4','5'], ans:2,
    exp:'20 ÷ 5 = 4. (5 × 4 = 20)' },
  { id:'2me3_058', s:'matematica', t:'Divisão', type:'mc', diff:3,
    q:'➗ Tenho 18 cromos para repartir igualmente por 2 amigos. Quantos cromos para cada um?',
    opts:['7','8','9','10'], ans:2,
    exp:'18 ÷ 2 = 9 cromos.' },
  { id:'2me3_059', s:'matematica', t:'Divisão', type:'fill', diff:3,
    q:'➗ 15 ÷ 3 = ___',
    ans:['5','cinco'],
    exp:'15 ÷ 3 = 5. (3 × 5 = 15)' },
  { id:'2me3_060', s:'matematica', t:'Divisão', type:'mc', diff:3,
    q:'➗ 10 gomas para 2 crianças, em partes iguais. Quantas gomas para cada uma?',
    opts:['3','4','5','6'], ans:2,
    exp:'10 ÷ 2 = 5 gomas.' },

  // ===== Frações simples (diff:3) =====
  { id:'2me3_061', s:'matematica', t:'Frações simples', type:'fill', diff:3,
    q:'🍕 Metade de uma pizza é o mesmo que ___ da pizza.',
    ans:['1/2','meio','metade'],
    exp:'Metade escreve-se 1/2.' },
  { id:'2me3_062', s:'matematica', t:'Frações simples', type:'mc', diff:3,
    q:'🍕 O bolo está em 4 fatias iguais. Comi 1. Que parte do bolo comi?',
    opts:['1/2','1/3','1/4','3/4'], ans:2,
    exp:'1 fatia em 4 é 1/4 do bolo.' },
  { id:'2me3_063', s:'matematica', t:'Frações simples', type:'mc', diff:3,
    q:'🍕 Uma pizza foi cortada em 4 fatias iguais. Comi 3. Que parte comi?',
    opts:['1/4','2/4','3/4','4/4'], ans:2,
    exp:'3 fatias de 4 é 3/4 da pizza.' },
  { id:'2me3_064', s:'matematica', t:'Frações simples', type:'fill', diff:3,
    q:'🍕 Metade de 10 maçãs são ___ maçãs.',
    ans:['5','cinco'],
    exp:'Metade de 10 é 5. (10 ÷ 2 = 5)' },
  { id:'2me3_065', s:'matematica', t:'Frações simples', type:'mc', diff:3,
    q:'🍕 Quanto é 1/4 de 8 bombons?',
    opts:['1','2','3','4'], ans:1,
    exp:'8 ÷ 4 = 2 bombons.' },

  // ===== Figuras planas (diff:3) =====
  { id:'2me3_066', s:'matematica', t:'Figuras planas', type:'mc', diff:3,
    q:'🔷 Uma figura tem 3 lados e 3 cantos. Que figura é?',
    opts:['Quadrado','Triângulo','Círculo','Retângulo'], ans:1,
    exp:'O triângulo tem 3 lados e 3 cantos.' },
  { id:'2me3_067', s:'matematica', t:'Figuras planas', type:'tf', diff:3,
    q:'🔷 Um quadrado é um tipo de retângulo com todos os lados iguais. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim! O quadrado tem 4 lados iguais e 4 cantos retos, como um retângulo especial.' },
  { id:'2me3_068', s:'matematica', t:'Figuras planas', type:'mc', diff:3,
    q:'🔷 Quantos lados tem um retângulo?',
    opts:['3','4','5','6'], ans:1,
    exp:'O retângulo tem 4 lados.' },
  { id:'2me3_069', s:'matematica', t:'Figuras planas', type:'mc', diff:3,
    q:'🔷 Que figura não tem cantos?',
    opts:['Quadrado','Triângulo','Círculo','Retângulo'], ans:2,
    exp:'O círculo é redondo e não tem cantos.' },
  { id:'2me3_070', s:'matematica', t:'Figuras planas', type:'fill', diff:3,
    q:'🔷 Uma figura com 4 lados todos iguais chama-se ___.',
    ans:['quadrado'],
    exp:'O quadrado tem 4 lados iguais.' },

  // ===== Sólidos geométricos (diff:3) =====
  { id:'2me3_071', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:3,
    q:'🎲 Que sólido tem a forma de uma bola?',
    opts:['Cubo','Cilindro','Esfera','Cone'], ans:2,
    exp:'A esfera tem a forma de uma bola.' },
  { id:'2me3_072', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:3,
    q:'🎲 Um dado tem a forma de quê?',
    opts:['Esfera','Cubo','Cilindro','Cone'], ans:1,
    exp:'O dado é um cubo: 6 faces quadradas iguais.' },
  { id:'2me3_073', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:3,
    q:'🎲 Uma lata de atum tem a forma de quê?',
    opts:['Cubo','Esfera','Cilindro','Pirâmide'], ans:2,
    exp:'A lata é um cilindro.' },
  { id:'2me3_074', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:3,
    q:'🎲 A esfera consegue rolar. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim! A esfera rola porque é redonda em todos os lados.' },
  { id:'2me3_075', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:3,
    q:'🎲 Quantas faces tem um cubo?',
    opts:['4','5','6','8'], ans:2,
    exp:'O cubo tem 6 faces, todas quadradas.' },

  // ===== Dinheiro (€) (diff:3) =====
  { id:'2me3_076', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:3,
    q:'💰 O Pedro tem 2 moedas de 1€ e 3 moedas de 50 cêntimos. Quanto tem ao todo (em €)?',
    ans:['3,50','3.50','3,50€','3 euros e 50 cêntimos'],
    exp:'2€ + 1,50€ = 3,50€.' },
  { id:'2me3_077', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:3,
    q:'💰 Tens 5€. Compras um livro de 3€. Quanto sobra?',
    opts:['1€','2€','3€','5€'], ans:1,
    exp:'5 - 3 = 2 euros.' },
  { id:'2me3_078', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:3,
    q:'💰 Tens 10€. Compras pão por 2€ e fruta por 3€. Quanto te sobra?',
    opts:['3€','4€','5€','6€'], ans:2,
    exp:'10 - 2 - 3 = 5 euros.' },
  { id:'2me3_079', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:3,
    q:'💰 Quantas moedas de 50 cêntimos são precisas para fazer 2€?',
    ans:['4','quatro'],
    exp:'4 × 50 cêntimos = 200 cêntimos = 2€.' },
  { id:'2me3_080', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:3,
    q:'💰 Um gelado custa 1,20€. Tenho 2€. Quanto recebo de troco?',
    opts:['0,50€','0,80€','1€','1,20€'], ans:1,
    exp:'2,00 - 1,20 = 0,80€.' },

  // ===== Medir tempo (diff:3) =====
  { id:'2me3_081', s:'matematica', t:'Medir tempo', type:'fill', diff:3,
    q:'⏰ Agora são 13h45. Quantos minutos faltam para as 14h?',
    ans:['15','quinze'],
    exp:'De 13h45 a 14h00 são 15 minutos.' },
  { id:'2me3_082', s:'matematica', t:'Medir tempo', type:'mc', diff:3,
    q:'⏰ O filme começou às 16h e durou 2 horas. A que horas acabou?',
    opts:['17h','18h','19h','20h'], ans:1,
    exp:'16h + 2h = 18h.' },
  { id:'2me3_083', s:'matematica', t:'Medir tempo', type:'mc', diff:3,
    q:'⏰ Quantos minutos há entre as 9h00 e as 9h30?',
    opts:['15','20','30','60'], ans:2,
    exp:'De 9h00 a 9h30 são 30 minutos.' },
  { id:'2me3_084', s:'matematica', t:'Medir tempo', type:'tf', diff:3,
    q:'⏰ Meia hora são 30 minutos. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. Metade de 60 é 30.' },
  { id:'2me3_085', s:'matematica', t:'Medir tempo', type:'mc', diff:3,
    q:'⏰ A aula começa às 10h e dura 45 minutos. A que horas acaba?',
    opts:['10h30','10h40','10h45','11h00'], ans:2,
    exp:'10h + 45 min = 10h45.' },

  // ===== Dezenas e unidades (diff:1) =====
  { id:'2me3_086', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
    q:'🔢 No número 47, qual é o algarismo das dezenas?',
    ans:['4','quatro'],
    exp:'No 47, o 4 é o algarismo da esquerda — está nas dezenas.' },
  { id:'2me3_087', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
    q:'🔢 No número 63, qual é o algarismo das unidades?',
    opts:['6','3','60','63'], ans:1,
    exp:'O algarismo das unidades é o da direita: 3.' },
  { id:'2me3_088', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
    q:'🔢 Quantas unidades tem 1 dezena?',
    ans:['10','dez'],
    exp:'1 dezena = 10 unidades.' },
  { id:'2me3_089', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
    q:'🔢 O número 50 tem quantas dezenas?',
    opts:['1','3','5','10'], ans:2,
    exp:'50 = 5 dezenas.' },
  { id:'2me3_090', s:'matematica', t:'Dezenas e unidades', type:'tf', diff:1,
    q:'🔢 No número 28, o 2 vale 2 dezenas. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. 2 dezenas = 20. E 28 = 20 + 8.' },

  // ===== Dezenas e unidades (diff:3) =====
  { id:'2me3_091', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:3,
    q:'🔢 Qual é maior: 7 dezenas ou 70 unidades?',
    opts:['7 dezenas','70 unidades','São iguais','Não dá para saber'], ans:2,
    exp:'Pegadinha! 7 dezenas = 70 unidades. São iguais!' },
  { id:'2me3_092', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:3,
    q:'🔢 5 dezenas + 8 unidades = ___',
    ans:['58','cinquenta e oito'],
    exp:'5 dezenas = 50. 50 + 8 = 58.' },
  { id:'2me3_093', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:3,
    q:'🔢 No número 84, troquei o 8 com o 4. Que número fica?',
    opts:['44','48','84','88'], ans:1,
    exp:'Trocando os algarismos fica 48.' },
  { id:'2me3_094', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:3,
    q:'🔢 3 dezenas + 12 unidades = ___',
    ans:['42','quarenta e dois'],
    exp:'3 dezenas = 30. 30 + 12 = 42.' },
  { id:'2me3_095', s:'matematica', t:'Dezenas e unidades', type:'tf', diff:3,
    q:'🔢 O número 90 tem 9 dezenas e 0 unidades. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. 9 dezenas = 90 e não há unidades soltas.' },

  // ===== Medir tempo (diff:1) =====
  { id:'2me3_096', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
    q:'⏰ Quantos minutos tem 1 hora?',
    ans:['60','sessenta'],
    exp:'1 hora = 60 minutos.' },
  { id:'2me3_097', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
    q:'⏰ Quantas horas tem 1 dia?',
    opts:['12','18','24','60'], ans:2,
    exp:'1 dia tem 24 horas.' },
  { id:'2me3_098', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
    q:'⏰ Quantos dias tem uma semana?',
    ans:['7','sete'],
    exp:'1 semana tem 7 dias.' },
  { id:'2me3_099', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
    q:'⏰ Quantos meses tem 1 ano?',
    opts:['7','10','12','24'], ans:2,
    exp:'1 ano tem 12 meses.' },
  { id:'2me3_100', s:'matematica', t:'Medir tempo', type:'tf', diff:1,
    q:'⏰ Meia hora são 30 minutos. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim, metade de 60 é 30.' },

  // ===== Adição até 100 (diff:1) =====
  { id:'2me3_101', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
    q:'➕ 20 + 30 = ___',
    ans:['50','cinquenta'],
    exp:'20 + 30 = 50.' },
  { id:'2me3_102', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
    q:'➕ 10 + 5 = ?',
    opts:['10','15','20','50'], ans:1,
    exp:'10 + 5 = 15.' },
  { id:'2me3_103', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
    q:'➕ 40 + 10 = ___',
    ans:['50','cinquenta'],
    exp:'40 + 10 = 50.' },
  { id:'2me3_104', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
    q:'➕ 25 + 5 = ?',
    opts:['20','25','30','35'], ans:2,
    exp:'25 + 5 = 30.' },
  { id:'2me3_105', s:'matematica', t:'Adição até 100', type:'tf', diff:1,
    q:'➕ 50 + 50 = 100. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. 50 + 50 = 100.' },

  // ===== Subtração até 100 (diff:1) =====
  { id:'2me3_106', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
    q:'➖ 20 - 10 = ___',
    ans:['10','dez'],
    exp:'20 - 10 = 10.' },
  { id:'2me3_107', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
    q:'➖ 50 - 20 = ?',
    opts:['20','30','40','70'], ans:1,
    exp:'50 - 20 = 30.' },
  { id:'2me3_108', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
    q:'➖ 15 - 5 = ___',
    ans:['10','dez'],
    exp:'15 - 5 = 10.' },
  { id:'2me3_109', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
    q:'➖ 30 - 10 = ?',
    opts:['10','20','30','40'], ans:1,
    exp:'30 - 10 = 20.' },
  { id:'2me3_110', s:'matematica', t:'Subtração até 100', type:'tf', diff:1,
    q:'➖ 100 - 50 = 50. Verdadeiro ou falso?',
    ans:true,
    exp:'Sim. 100 - 50 = 50.' },

  // ===== Tabuada do 7 (diff:3) reforço =====
  { id:'2me3_111', s:'matematica', t:'Tabuada do 7', type:'fill', diff:3,
    q:'✖️ 7 × 3 = ___',
    ans:['21','vinte e um'],
    exp:'7 × 3 = 21.' },
  { id:'2me3_112', s:'matematica', t:'Tabuada do 7', type:'mc', diff:3,
    q:'✖️ Cada semana tem 7 dias. Quantos dias há em 4 semanas?',
    opts:['21','24','28','35'], ans:2,
    exp:'4 × 7 = 28 dias.' },
  { id:'2me3_113', s:'matematica', t:'Tabuada do 7', type:'fill', diff:3,
    q:'✖️ 7 × ___ = 35. Que número falta?',
    ans:['5','cinco'],
    exp:'7 × 5 = 35. O número que falta é o 5.' },
  { id:'2me3_114', s:'matematica', t:'Tabuada do 7', type:'mc', diff:3,
    q:'✖️ 7 × 6 = ?',
    opts:['36','40','42','48'], ans:2,
    exp:'7 × 6 = 42.' },
  { id:'2me3_115', s:'matematica', t:'Tabuada do 7', type:'tf', diff:3,
    q:'✖️ 7 × 2 = 2 × 7. Verdadeiro ou falso?',
    ans:true,
    exp:'Trocar a ordem dá o mesmo: 14.' },
];

if (typeof module !== 'undefined' && module.exports) module.exports = EXERCISES_2_M_EXTRA3;
