// EscolaPlay - Top-up extra do 2.º ano - Estudo do Meio (gerado, AE 2018)
const EXERCISES_2_E_EXTRA2 = [

    // ============================================================
    // ===================== O MEU CORPO (39) =====================
    // ============================================================
    { id:'2ee1', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'❤️ Em que parte do corpo está o coração?',
      opts:['Na cabeça','No tronco','No braço','Na perna'], ans:1,
      exp:'O coração está no tronco, no peito.' },
    { id:'2ee2', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🧠 Onde está o cérebro?',
      opts:['No tronco','Na cabeça','Nas pernas','Nas mãos'], ans:1,
      exp:'O cérebro está dentro da cabeça, protegido pelo crânio.' },
    { id:'2ee3', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🫁 Para que servem os pulmões?',
      opts:['Para pensar','Para respirar','Para comer','Para correr'], ans:1,
      exp:'Os pulmões servem para respirar (entra ar).' },
    { id:'2ee4', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🦴 O que protege o nosso corpo por dentro?',
      opts:['Os músculos','O esqueleto','A pele','O sangue'], ans:1,
      exp:'O esqueleto é formado pelos ossos e dá forma ao corpo.' },
    { id:'2ee5', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:2,
      q:'🦷 Os dentes servem para ___ os alimentos.',
      ans:['mastigar','triturar','cortar'],
      exp:'Os dentes mastigam (trituram) a comida.' },
    { id:'2ee6', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'✋ Quantos dedos tem cada mão?',
      opts:['3','4','5','6'], ans:2,
      exp:'Cada mão tem 5 dedos.' },
    { id:'2ee7', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:2,
      q:'🦵 As pernas fazem parte dos membros inferiores.',
      ans:true,
      exp:'As pernas são os membros inferiores; os braços são os superiores.' },
    { id:'2ee8', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🧍 Quais são as 3 grandes partes do corpo?',
      opts:['cabeça, tronco e membros','cabeça, mãos e pés','olhos, nariz e boca','braços, pernas e mãos'], ans:0,
      exp:'O corpo divide-se em cabeça, tronco e membros.' },
    { id:'2ee9', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'💪 Os braços são membros:',
      opts:['inferiores','superiores','médios','laterais'], ans:1,
      exp:'Os braços são os membros superiores.' },
    { id:'2ee10', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:2,
      q:'🍽️ O ___ é o órgão onde a comida é digerida.',
      ans:['estômago','estomago'],
      exp:'O estômago digere os alimentos.' },
    { id:'2ee11', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'❤️ O coração faz o sangue circular pelo corpo. É um:',
      opts:['músculo','osso','órgão da pele','sentido'], ans:0,
      exp:'O coração é um músculo muito importante.' },
    { id:'2ee12', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:1,
      q:'🦴 Os ossos são moles.',
      ans:false,
      exp:'Os ossos são duros e formam o esqueleto.' },
    { id:'2ee13', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🚿 Para cuidar do corpo devemos:',
      opts:['nunca tomar banho','tomar banho e lavar as mãos','dormir só ao fim de semana','comer só doces'], ans:1,
      exp:'Higiene diária é importante: banho, mãos lavadas, dentes lavados.' },
    { id:'2ee14', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🦷 Devemos lavar os dentes:',
      opts:['1 vez por semana','depois das refeições','só de manhã','nunca'], ans:1,
      exp:'Devemos lavar os dentes depois das refeições.' },
    { id:'2ee15', s:'estudo_meio', t:'O meu corpo', type:'match', diff:1,
      q:'Associa cada órgão à sua função:',
      pairs:[['❤️ coração','bombear o sangue'],['🫁 pulmões','respirar'],['🧠 cérebro','pensar'],['🍽️ estômago','digerir']],
      exp:'Cada órgão tem uma função própria.' },
    { id:'2ee16', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🦴 Quantos ossos protegem o cérebro?',
      opts:['1 (o crânio)','o esqueleto todo','as costelas','não há ossos'], ans:0,
      exp:'O crânio é um conjunto de ossos que protege o cérebro.' },
    { id:'2ee17', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:1,
      q:'👁️ Os olhos servem para ___.',
      ans:['ver','olhar'],
      exp:'Os olhos servem para ver.' },
    { id:'2ee18', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'😴 Quantas horas, mais ou menos, deve dormir uma criança?',
      opts:['2 horas','5 horas','9 a 11 horas','24 horas'], ans:2,
      exp:'As crianças precisam de 9 a 11 horas de sono.' },
    { id:'2ee19', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:1,
      q:'🥗 Comer fruta e legumes faz bem ao corpo.',
      ans:true,
      exp:'Fruta e legumes dão vitaminas ao corpo.' },
    { id:'2ee20', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🚶 Para sermos saudáveis devemos:',
      opts:['ficar parados','fazer exercício','comer só doces','não dormir'], ans:1,
      exp:'O exercício físico mantém o corpo saudável.' },
    { id:'2ee21', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🦴 Quantas costelas, mais ou menos, tem o ser humano?',
      opts:['10','24','100','2'], ans:1,
      exp:'O ser humano tem cerca de 24 costelas (12 de cada lado).' },
    { id:'2ee22', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'👃 O nariz serve para:',
      opts:['ouvir','cheirar e respirar','ver','provar'], ans:1,
      exp:'O nariz serve para cheirar e para respirar.' },
    { id:'2ee23', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🩸 O coração faz circular o:',
      opts:['ar','sangue','água','suor'], ans:1,
      exp:'O coração bombeia o sangue para todo o corpo.' },
    { id:'2ee24', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:1,
      q:'🦵 As ___ servem para andar e correr.',
      ans:['pernas'],
      exp:'As pernas (membros inferiores) servem para andar.' },
    { id:'2ee25', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🦷 Os dentes de leite são:',
      opts:['os primeiros dentes da criança','os dentes dos avós','feitos de leite','os dentes do siso'], ans:0,
      exp:'Os dentes de leite são os primeiros, depois caem.' },
    { id:'2ee26', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:1,
      q:'💧 Devemos beber água todos os dias.',
      ans:true,
      exp:'A água é essencial à vida e ao bom funcionamento do corpo.' },
    { id:'2ee27', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🧴 Que produto usamos para lavar os dentes?',
      opts:['champô','pasta de dentes','sabão','perfume'], ans:1,
      exp:'A pasta de dentes (e a escova) limpam os dentes.' },
    { id:'2ee28', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🤲 Os braços terminam nas:',
      opts:['mãos','pernas','orelhas','costas'], ans:0,
      exp:'Os braços terminam nas mãos.' },
    { id:'2ee29', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'🦵 As pernas terminam nos:',
      opts:['joelhos','pés','cotovelos','dedos das mãos'], ans:1,
      exp:'As pernas terminam nos pés.' },
    { id:'2ee30', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:1,
      q:'👄 A ___ usamos para falar e comer.',
      ans:['boca'],
      exp:'A boca serve para falar, comer e beber.' },
    { id:'2ee31', s:'estudo_meio', t:'O meu corpo', type:'order', diff:2,
      q:'Ordena estas partes do corpo, de cima para baixo:',
      items:['cabeça','tronco','pernas','pés'],
      exp:'cabeça → tronco → pernas → pés.' },
    { id:'2ee32', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'💪 Os músculos servem para:',
      opts:['ouvir','mexer o corpo','ver','digerir'], ans:1,
      exp:'Os músculos permitem mover o corpo.' },
    { id:'2ee33', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:2,
      q:'🧴 Lavar as mãos antes de comer evita doenças.',
      ans:true,
      exp:'Lavar as mãos retira micróbios e evita doenças.' },
    { id:'2ee34', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:1,
      q:'👂 As orelhas fazem parte da:',
      opts:['cabeça','tronco','perna','barriga'], ans:0,
      exp:'As orelhas estão na cabeça.' },
    { id:'2ee35', s:'estudo_meio', t:'O meu corpo', type:'match', diff:1,
      q:'Associa cada parte da cabeça:',
      pairs:[['👁️ olhos','ver'],['👃 nariz','cheirar'],['👂 orelhas','ouvir'],['👄 boca','falar']],
      exp:'Cada parte da cabeça tem uma função.' },
    { id:'2ee36', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🌡️ Quando estamos doentes devemos ir ao:',
      opts:['cabeleireiro','médico','padeiro','jardineiro'], ans:1,
      exp:'O médico cuida da nossa saúde.' },
    { id:'2ee37', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:2,
      q:'🦴 O conjunto de todos os ossos chama-se ___.',
      ans:['esqueleto'],
      exp:'O esqueleto é formado por todos os ossos.' },
    { id:'2ee38', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:2,
      q:'🩸 Que líquido vermelho corre nas nossas veias?',
      opts:['água','leite','sangue','sumo'], ans:2,
      exp:'O sangue corre pelas veias e artérias.' },
    { id:'2ee39', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:1,
      q:'🧠 O cérebro controla todo o corpo.',
      ans:true,
      exp:'O cérebro envia ordens a todo o corpo.' },

    // ============================================================
    // ===================== A MINHA FAMÍLIA (41) =================
    // ============================================================
    { id:'2ee40', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👨 O pai do meu pai é o meu:',
      opts:['tio','primo','avô','irmão'], ans:2,
      exp:'O pai do pai é o avô.' },
    { id:'2ee41', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👩 A mãe da minha mãe é a minha:',
      opts:['tia','prima','avó','madrinha'], ans:2,
      exp:'A mãe da mãe é a avó.' },
    { id:'2ee42', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👦 O filho do meu tio é o meu:',
      opts:['irmão','primo','avô','sobrinho'], ans:1,
      exp:'O filho do tio é o primo.' },
    { id:'2ee43', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👧 A irmã do meu pai é a minha:',
      opts:['avó','tia','prima','madrinha'], ans:1,
      exp:'A irmã do pai é a tia.' },
    { id:'2ee44', s:'estudo_meio', t:'A minha família', type:'fill', diff:1,
      q:'👨 O irmão da minha mãe é o meu ___.',
      ans:['tio'],
      exp:'O irmão da mãe é o tio.' },
    { id:'2ee45', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👫 Os filhos dos mesmos pais são:',
      opts:['primos','irmãos','tios','sobrinhos'], ans:1,
      exp:'Filhos dos mesmos pais são irmãos.' },
    { id:'2ee46', s:'estudo_meio', t:'A minha família', type:'tf', diff:1,
      q:'👵 Os avós são os pais dos nossos pais.',
      ans:true,
      exp:'Os avós são os pais dos nossos pais.' },
    { id:'2ee47', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👨‍👩‍👧 Família nuclear é formada por:',
      opts:['avós e netos','pais e filhos','primos','vizinhos'], ans:1,
      exp:'A família nuclear é os pais e os filhos.' },
    { id:'2ee48', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'🎂 Como se chama o dia em que fazemos anos?',
      opts:['Natal','Páscoa','aniversário','feriado'], ans:2,
      exp:'No aniversário celebramos o dia em que nascemos.' },
    { id:'2ee49', s:'estudo_meio', t:'A minha família', type:'fill', diff:2,
      q:'👨‍👩‍👦 O conjunto pai, mãe e filhos chama-se ___.',
      ans:['família','familia'],
      exp:'A família é o conjunto de pessoas com laços familiares.' },
    { id:'2ee50', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👶 O filho do meu irmão é o meu:',
      opts:['primo','sobrinho','tio','avô'], ans:1,
      exp:'O filho do irmão é o sobrinho.' },
    { id:'2ee51', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'🏡 Onde vive normalmente a família?',
      opts:['na escola','em casa','no supermercado','no campo'], ans:1,
      exp:'A família vive em casa.' },
    { id:'2ee52', s:'estudo_meio', t:'A minha família', type:'tf', diff:1,
      q:'👵👴 Os avós são mais velhos do que os pais.',
      ans:true,
      exp:'Os avós são os pais dos nossos pais, por isso são mais velhos.' },
    { id:'2ee53', s:'estudo_meio', t:'A minha família', type:'match', diff:1,
      q:'Associa cada parente à relação:',
      pairs:[['👨 pai','o que me deu vida'],['👵 avó','mãe da minha mãe'],['👨 tio','irmão da mãe'],['👦 primo','filho do tio']],
      exp:'Estes são parentes próximos.' },
    { id:'2ee54', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'🎁 Que dia comemoramos com toda a família e oferecemos prendas em dezembro?',
      opts:['Carnaval','Natal','Páscoa','Dia dos Namorados'], ans:1,
      exp:'O Natal é a 25 de dezembro.' },
    { id:'2ee55', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'🥚 Em que festa se comem as amêndoas e folares?',
      opts:['Natal','Páscoa','Carnaval','São João'], ans:1,
      exp:'Na Páscoa há amêndoas, folares e o pão-de-ló.' },
    { id:'2ee56', s:'estudo_meio', t:'A minha família', type:'fill', diff:2,
      q:'👨‍👩 A pessoa com quem o meu pai casou é a minha ___.',
      ans:['mãe','mae'],
      exp:'A mãe é a mulher casada com o pai.' },
    { id:'2ee57', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'🏠 Os meus avós, tios e primos são a minha família:',
      opts:['nuclear','alargada','escolar','vizinha'], ans:1,
      exp:'A família alargada inclui avós, tios, primos.' },
    { id:'2ee58', s:'estudo_meio', t:'A minha família', type:'tf', diff:2,
      q:'👫 Todos têm de ter o mesmo número de irmãos.',
      ans:false,
      exp:'Cada família é diferente — uns têm muitos irmãos, outros nenhum.' },
    { id:'2ee59', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'👵 A mãe do meu pai é minha avó. O pai do meu pai é o meu:',
      opts:['avô','tio','padrinho','padrasto'], ans:0,
      exp:'O pai do pai é o avô.' },
    { id:'2ee60', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'❤️ Como devemos tratar a nossa família?',
      opts:['com carinho e respeito','com gritos','sem falar','com medo'], ans:0,
      exp:'A família trata-se com carinho e respeito.' },
    { id:'2ee61', s:'estudo_meio', t:'A minha família', type:'fill', diff:2,
      q:'🎉 No dia do meu ___ as pessoas dão-me parabéns.',
      ans:['aniversário','aniversario'],
      exp:'No aniversário, dão-nos os parabéns.' },
    { id:'2ee62', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'👶 Quando nasce um irmão mais novo, eu sou o:',
      opts:['filho mais velho','irmão mais novo','primo','tio'], ans:0,
      exp:'Sou o irmão mais velho do bebé.' },
    { id:'2ee63', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'🍽️ A refeição em família ao fim do dia é o:',
      opts:['pequeno-almoço','almoço','jantar','lanche'], ans:2,
      exp:'O jantar é a refeição da noite.' },
    { id:'2ee64', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'🌅 Que refeição se faz logo de manhã?',
      opts:['jantar','pequeno-almoço','lanche','ceia'], ans:1,
      exp:'O pequeno-almoço é a primeira refeição do dia.' },
    { id:'2ee65', s:'estudo_meio', t:'A minha família', type:'tf', diff:2,
      q:'👨‍👩‍👧‍👦 Há famílias com 1, 2 ou mais filhos.',
      ans:true,
      exp:'Cada família tem o número de filhos que é a sua realidade.' },
    { id:'2ee66', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'👴 Os meus pais e os meus avós formam a árvore...',
      opts:['de fruto','genealógica','de Natal','do jardim'], ans:1,
      exp:'A árvore genealógica mostra a história da família.' },
    { id:'2ee67', s:'estudo_meio', t:'A minha família', type:'order', diff:2,
      q:'Ordena por idade, do mais velho para o mais novo:',
      items:['avô','pai','irmão mais velho','bebé'],
      exp:'avô → pai → irmão mais velho → bebé.' },
    { id:'2ee68', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👨 O marido da minha tia é o meu:',
      opts:['avô','tio','primo','irmão'], ans:1,
      exp:'O marido da tia também é tio.' },
    { id:'2ee69', s:'estudo_meio', t:'A minha família', type:'fill', diff:1,
      q:'🎂 Eu nasci no dia do meu ___.',
      ans:['nascimento','aniversário','aniversario'],
      exp:'O dia do nascimento é o aniversário.' },
    { id:'2ee70', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'👫 Eu e o meu irmão temos os mesmos:',
      opts:['amigos','pais','professores','vizinhos'], ans:1,
      exp:'Irmãos têm os mesmos pais.' },
    { id:'2ee71', s:'estudo_meio', t:'A minha família', type:'tf', diff:2,
      q:'🤝 As tarefas de casa devem ser partilhadas pela família.',
      ans:true,
      exp:'Todos devemos ajudar nas tarefas de casa.' },
    { id:'2ee72', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'👵 Onde nascem normalmente os bebés humanos?',
      opts:['na maternidade (hospital)','na escola','no jardim','no campo'], ans:0,
      exp:'A maioria dos bebés nasce em hospitais/maternidades.' },
    { id:'2ee73', s:'estudo_meio', t:'A minha família', type:'mc', diff:1,
      q:'❤️ A família serve para:',
      opts:['nos amar e cuidar','trabalhar só','jogar','não falar'], ans:0,
      exp:'A família ama, cuida e protege.' },
    { id:'2ee74', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'👴 Os meus avós contam-me histórias sobre o:',
      opts:['futuro','passado','jardim','jogo'], ans:1,
      exp:'Os avós contam histórias do passado, da sua vida.' },
    { id:'2ee75', s:'estudo_meio', t:'A minha família', type:'fill', diff:2,
      q:'👨‍👩‍👧 O ___ é o homem casado com a minha mãe.',
      ans:['pai'],
      exp:'O pai é o homem casado com a mãe.' },
    { id:'2ee76', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'👶 Quando crescemos passamos por estas fases. Qual é a 1.ª?',
      opts:['adulto','idoso','bebé','jovem'], ans:2,
      exp:'Bebé → criança → jovem → adulto → idoso.' },
    { id:'2ee77', s:'estudo_meio', t:'A minha família', type:'order', diff:1,
      q:'Ordena as fases da vida:',
      items:['bebé','criança','jovem','adulto','idoso'],
      exp:'bebé → criança → jovem → adulto → idoso.' },
    { id:'2ee78', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'🍰 Quem normalmente sopra as velas no aniversário?',
      opts:['o avô','o aniversariante','o vizinho','o cão'], ans:1,
      exp:'O aniversariante sopra as velas.' },
    { id:'2ee79', s:'estudo_meio', t:'A minha família', type:'mc', diff:2,
      q:'❤️ A pessoa com quem partilho o quarto pode ser o meu:',
      opts:['professor','irmão','médico','vizinho'], ans:1,
      exp:'Em muitas famílias, irmãos partilham o quarto.' },
    { id:'2ee80', s:'estudo_meio', t:'A minha família', type:'tf', diff:1,
      q:'👵 Os idosos são pessoas mais velhas.',
      ans:true,
      exp:'Os idosos são as pessoas com mais idade.' },

    // ============================================================
    // ===================== A ESCOLA (43) ========================
    // ============================================================
    { id:'2ee81', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'🎒 O que levamos para a escola para guardar os livros?',
      opts:['mala','mochila','panela','cesta'], ans:1,
      exp:'A mochila serve para levar livros e cadernos.' },
    { id:'2ee82', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'✏️ Com que objeto escrevemos no caderno?',
      opts:['lápis','colher','tesoura','pincel'], ans:0,
      exp:'O lápis serve para escrever (e a borracha apaga).' },
    { id:'2ee83', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🧽 O que usamos para apagar o lápis?',
      opts:['régua','borracha','afia','caneta'], ans:1,
      exp:'A borracha apaga o que está escrito a lápis.' },
    { id:'2ee84', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📏 O que usamos para medir e fazer linhas direitas?',
      opts:['régua','borracha','tesoura','lápis'], ans:0,
      exp:'A régua mede e ajuda a traçar linhas direitas.' },
    { id:'2ee85', s:'estudo_meio', t:'A escola', type:'fill', diff:1,
      q:'👨‍🏫 Quem ensina na escola é o ___.',
      ans:['professor','professora'],
      exp:'O professor ensina os alunos.' },
    { id:'2ee86', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📚 Espaço da escola onde se leem livros:',
      opts:['cantina','biblioteca','pátio','ginásio'], ans:1,
      exp:'A biblioteca é o espaço de livros e leitura.' },
    { id:'2ee87', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🍽️ Onde almoçam os alunos na escola?',
      opts:['biblioteca','cantina','sala de aula','pátio'], ans:1,
      exp:'A cantina (refeitório) é onde se come.' },
    { id:'2ee88', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'⚽ Onde os alunos brincam no recreio?',
      opts:['biblioteca','pátio','sala','cantina'], ans:1,
      exp:'O pátio (recreio) é o espaço de brincar.' },
    { id:'2ee89', s:'estudo_meio', t:'A escola', type:'tf', diff:2,
      q:'🤫 Devemos respeitar os colegas e o professor.',
      ans:true,
      exp:'O respeito é fundamental na escola.' },
    { id:'2ee90', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'✋ Quando queremos falar na sala de aula:',
      opts:['gritamos','colocamos o dedo no ar','batemos na mesa','saímos'], ans:1,
      exp:'Pedimos a vez levantando o dedo (o braço).' },
    { id:'2ee91', s:'estudo_meio', t:'A escola', type:'fill', diff:1,
      q:'📓 Escrevemos os apontamentos no ___.',
      ans:['caderno'],
      exp:'O caderno serve para escrever.' },
    { id:'2ee92', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'✂️ Para cortar papel usamos:',
      opts:['lápis','tesoura','régua','borracha'], ans:1,
      exp:'A tesoura corta papel.' },
    { id:'2ee93', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🖍️ Para pintar usamos:',
      opts:['borracha','lápis de cor','régua','agrafador'], ans:1,
      exp:'Os lápis de cor (ou canetas) servem para pintar.' },
    { id:'2ee94', s:'estudo_meio', t:'A escola', type:'tf', diff:1,
      q:'📚 Devemos cuidar dos livros e cadernos.',
      ans:true,
      exp:'Devemos respeitar e cuidar dos materiais.' },
    { id:'2ee95', s:'estudo_meio', t:'A escola', type:'match', diff:1,
      q:'Associa cada material à sua função:',
      pairs:[['✏️ lápis','escrever'],['🧽 borracha','apagar'],['📏 régua','medir'],['✂️ tesoura','cortar']],
      exp:'Cada objeto escolar tem a sua função.' },
    { id:'2ee96', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🎒 Onde guardamos a mochila na sala?',
      opts:['no chão ou no cabide','no telhado','na cantina','em casa'], ans:0,
      exp:'A mochila fica no cabide ou ao lado da mesa.' },
    { id:'2ee97', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🚪 Quando entramos na sala devemos:',
      opts:['gritar','cumprimentar e sentar','correr','sair'], ans:1,
      exp:'Cumprimentamos o professor e os colegas.' },
    { id:'2ee98', s:'estudo_meio', t:'A escola', type:'fill', diff:2,
      q:'🔔 Quando toca a campainha vamos para o ___.',
      ans:['recreio','intervalo','pátio'],
      exp:'A campainha pode anunciar o recreio.' },
    { id:'2ee99', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'👫 Quem são as outras crianças da minha sala?',
      opts:['vizinhos','colegas','tios','primos'], ans:1,
      exp:'As crianças da minha sala são os meus colegas.' },
    { id:'2ee100', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📝 Para fazer um trabalho de casa precisamos de:',
      opts:['só televisão','lápis e caderno','só telemóvel','nada'], ans:1,
      exp:'Para o TPC usamos lápis, caderno e o que for pedido.' },
    { id:'2ee101', s:'estudo_meio', t:'A escola', type:'tf', diff:2,
      q:'🤝 Devemos partilhar o material com um colega que não tem.',
      ans:true,
      exp:'Partilhar é uma boa atitude.' },
    { id:'2ee102', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'🏫 A pessoa que dirige a escola chama-se:',
      opts:['enfermeiro','diretor','padeiro','jardineiro'], ans:1,
      exp:'O diretor (ou diretora) dirige a escola.' },
    { id:'2ee103', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🧹 Quem ajuda a limpar a escola?',
      opts:['os alunos só','os funcionários','os polícias','os médicos'], ans:1,
      exp:'Os funcionários (auxiliares) cuidam e limpam a escola.' },
    { id:'2ee104', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🖋️ Para escrever a tinta usamos uma:',
      opts:['caneta','borracha','régua','tesoura'], ans:0,
      exp:'A caneta escreve a tinta.' },
    { id:'2ee105', s:'estudo_meio', t:'A escola', type:'fill', diff:1,
      q:'🏃 No ___ brincamos com os colegas.',
      ans:['recreio','intervalo','pátio'],
      exp:'No recreio (intervalo) brincamos.' },
    { id:'2ee106', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📖 O que abrimos para ler textos e exercícios?',
      opts:['caderno só','livro/manual','régua','mochila'], ans:1,
      exp:'O livro (manual) tem textos para ler.' },
    { id:'2ee107', s:'estudo_meio', t:'A escola', type:'tf', diff:1,
      q:'⚠️ Não devemos correr nas escadas.',
      ans:true,
      exp:'Correr nas escadas é perigoso.' },
    { id:'2ee108', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🧴 Para lavar as mãos vamos à:',
      opts:['cantina','casa de banho','biblioteca','sala'], ans:1,
      exp:'Lavamos as mãos na casa de banho.' },
    { id:'2ee109', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📅 Os dias úteis de escola, normalmente, são de:',
      opts:['sábado a domingo','segunda a sexta-feira','só ao sábado','só ao domingo'], ans:1,
      exp:'Vamos à escola de segunda a sexta-feira.' },
    { id:'2ee110', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'⏰ Devemos chegar à escola:',
      opts:['atrasados','a horas','depois do almoço','quando quisermos'], ans:1,
      exp:'A pontualidade é importante.' },
    { id:'2ee111', s:'estudo_meio', t:'A escola', type:'fill', diff:2,
      q:'🏫 O lugar onde aprendemos chama-se ___.',
      ans:['escola'],
      exp:'A escola é o lugar onde aprendemos.' },
    { id:'2ee112', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🖌️ Para fazer um desenho podemos usar:',
      opts:['lápis de cor','tesoura','régua só','agrafador'], ans:0,
      exp:'Lápis de cor, canetas e marcadores servem para desenhar.' },
    { id:'2ee113', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📐 Que objeto tem forma triangular para medir ângulos?',
      opts:['régua','esquadro','borracha','livro'], ans:1,
      exp:'O esquadro é um instrumento para ângulos.' },
    { id:'2ee114', s:'estudo_meio', t:'A escola', type:'tf', diff:2,
      q:'😡 Podemos bater nos colegas quando ficamos zangados.',
      ans:false,
      exp:'Nunca devemos bater. Deve-se conversar e pedir ajuda.' },
    { id:'2ee115', s:'estudo_meio', t:'A escola', type:'match', diff:2,
      q:'Associa cada espaço da escola à sua função:',
      pairs:[['📚 biblioteca','ler livros'],['🍽️ cantina','almoçar'],['⚽ pátio','brincar'],['📝 sala','aprender']],
      exp:'Cada espaço tem uma função.' },
    { id:'2ee116', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🪑 Sentamo-nos na sala numa:',
      opts:['cama','cadeira','sofá','almofada'], ans:1,
      exp:'Sentamo-nos numa cadeira, junto à mesa.' },
    { id:'2ee117', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'🖊️ O afia (apara-lápis) serve para:',
      opts:['apagar','afiar o lápis','medir','cortar'], ans:1,
      exp:'O afia faz uma ponta nova no lápis.' },
    { id:'2ee118', s:'estudo_meio', t:'A escola', type:'fill', diff:1,
      q:'🎨 Os ___ de cor servem para pintar.',
      ans:['lápis','lapis'],
      exp:'Lápis de cor pintam o desenho.' },
    { id:'2ee119', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'📝 O que fazemos com o trabalho de casa?',
      opts:['rasgamos','levamos para a escola','deitamos fora','damos ao cão'], ans:1,
      exp:'Levamos o TPC para o professor corrigir.' },
    { id:'2ee120', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'👨‍🏫 Quando o professor explica devemos:',
      opts:['estar atentos e calados','falar uns com os outros','dormir','jogar à bola'], ans:0,
      exp:'Devemos estar atentos para aprender.' },
    { id:'2ee121', s:'estudo_meio', t:'A escola', type:'mc', diff:1,
      q:'📦 Onde guardamos os lápis e canetas?',
      opts:['mochila','estojo','cesto','cantina'], ans:1,
      exp:'O estojo (penal) guarda o material.' },
    { id:'2ee122', s:'estudo_meio', t:'A escola', type:'mc', diff:2,
      q:'🚪 No fim do dia, antes de sair, devemos:',
      opts:['arrumar o material','rasgar tudo','correr','gritar'], ans:0,
      exp:'Arrumamos o material e a sala.' },
    { id:'2ee123', s:'estudo_meio', t:'A escola', type:'tf', diff:1,
      q:'😊 Na escola fazemos novos amigos.',
      ans:true,
      exp:'Os colegas tornam-se amigos.' },

    // ============================================================
    // ===================== ANIMAIS (33) =========================
    // ============================================================
    { id:'2ee124', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐶 O cão é um animal:',
      opts:['selvagem','doméstico','marinho','voador'], ans:1,
      exp:'O cão é um animal doméstico, vive com as pessoas.' },
    { id:'2ee125', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🦁 O leão é um animal:',
      opts:['doméstico','selvagem','aquático','de carga'], ans:1,
      exp:'O leão é selvagem, vive na natureza (savana).' },
    { id:'2ee126', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🦋 A borboleta é um:',
      opts:['mamífero','peixe','inseto','réptil'], ans:2,
      exp:'A borboleta é um inseto (6 patas, asas).' },
    { id:'2ee127', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐸 A rã é um:',
      opts:['réptil','anfíbio','peixe','ave'], ans:1,
      exp:'A rã é um anfíbio (vive na água e em terra).' },
    { id:'2ee128', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐍 As cobras são répteis.',
      ans:true,
      exp:'As cobras são répteis (escamas, rastejam).' },
    { id:'2ee129', s:'estudo_meio', t:'Animais', type:'mc', diff:2,
      q:'🥕 Animais que comem só plantas chamam-se:',
      opts:['carnívoros','herbívoros','omnívoros','aquáticos'], ans:1,
      exp:'Herbívoros comem plantas (ex: vaca, coelho).' },
    { id:'2ee130', s:'estudo_meio', t:'Animais', type:'mc', diff:2,
      q:'🥩 Animais que comem só carne chamam-se:',
      opts:['herbívoros','carnívoros','omnívoros','peixes'], ans:1,
      exp:'Carnívoros comem carne (ex: leão, lobo).' },
    { id:'2ee131', s:'estudo_meio', t:'Animais', type:'fill', diff:1,
      q:'🐝 A abelha produz ___.',
      ans:['mel'],
      exp:'A abelha faz o mel.' },
    { id:'2ee132', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐮 A vaca dá-nos:',
      opts:['ovos','mel','leite','lã'], ans:2,
      exp:'A vaca dá leite, do qual se faz queijo, manteiga, iogurtes.' },
    { id:'2ee133', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐑 De que animal vem a lã?',
      opts:['vaca','ovelha','porco','pato'], ans:1,
      exp:'A lã vem da ovelha.' },
    { id:'2ee134', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐔 Que animal põe ovos para comermos?',
      opts:['vaca','galinha','cão','gato'], ans:1,
      exp:'A galinha põe ovos.' },
    { id:'2ee135', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐬 O golfinho é um peixe.',
      ans:false,
      exp:'O golfinho é um mamífero, embora viva no mar.' },
    { id:'2ee136', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🦅 A águia é uma:',
      opts:['ave','mamífero','réptil','peixe'], ans:0,
      exp:'A águia é uma ave de rapina.' },
    { id:'2ee137', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐴 O cavalo serve normalmente para:',
      opts:['nadar','andar e transporte','voar','escavar'], ans:1,
      exp:'O cavalo é usado para transporte e equitação.' },
    { id:'2ee138', s:'estudo_meio', t:'Animais', type:'fill', diff:1,
      q:'🐠 Os peixes respiram pelas ___.',
      ans:['guelras','brânquias','branquias'],
      exp:'Os peixes respiram pelas guelras (brânquias).' },
    { id:'2ee139', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐧 Que ave não voa?',
      opts:['andorinha','pinguim','pomba','pardal'], ans:1,
      exp:'O pinguim é uma ave que não voa, mas nada muito bem.' },
    { id:'2ee140', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐢 Os mamíferos:',
      opts:['põem ovos sempre','dão de mamar às crias','têm escamas','vivem na água'], ans:1,
      exp:'Os mamíferos amamentam as crias com leite.' },
    { id:'2ee141', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐱 O gato é um mamífero.',
      ans:true,
      exp:'O gato é mamífero (dá de mamar).' },
    { id:'2ee142', s:'estudo_meio', t:'Animais', type:'match', diff:1,
      q:'Associa cada animal à sua casa:',
      pairs:[['🐝 abelha','colmeia'],['🕊️ pomba','ninho'],['🐶 cão','canil'],['🐜 formiga','formigueiro']],
      exp:'Cada animal tem o seu abrigo.' },
    { id:'2ee143', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐦 Quantas patas tem uma ave?',
      opts:['2','4','6','8'], ans:0,
      exp:'As aves têm 2 patas e 2 asas.' },
    { id:'2ee144', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐌 O caracol move-se:',
      opts:['voando','rastejando','nadando rapidamente','correndo'], ans:1,
      exp:'O caracol arrasta-se devagar.' },
    { id:'2ee145', s:'estudo_meio', t:'Animais', type:'fill', diff:1,
      q:'🦋 As borboletas têm ___ asas.',
      ans:['4','quatro'],
      exp:'As borboletas têm 4 asas.' },
    { id:'2ee146', s:'estudo_meio', t:'Animais', type:'mc', diff:2,
      q:'🦒 Que animal tem o pescoço muito comprido?',
      opts:['girafa','elefante','rinoceronte','urso'], ans:0,
      exp:'A girafa tem o pescoço muito longo.' },
    { id:'2ee147', s:'estudo_meio', t:'Animais', type:'mc', diff:2,
      q:'🐘 O elefante tem uma característica especial:',
      opts:['penas grandes','tromba','escamas','asas'], ans:1,
      exp:'O elefante tem uma tromba longa.' },
    { id:'2ee148', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🦅 Todas as aves voam.',
      ans:false,
      exp:'Algumas aves não voam (ex: pinguim, avestruz).' },
    { id:'2ee149', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐙 O polvo vive:',
      opts:['na floresta','no mar','no deserto','no telhado'], ans:1,
      exp:'O polvo vive no mar.' },
    { id:'2ee150', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🦌 O lince-ibérico vive em:',
      opts:['Portugal e Espanha','África','América','Ásia'], ans:0,
      exp:'O lince-ibérico vive na Península Ibérica.' },
    { id:'2ee151', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐝 Quantas patas tem um inseto?',
      opts:['4','6','8','10'], ans:1,
      exp:'Os insetos têm 6 patas.' },
    { id:'2ee152', s:'estudo_meio', t:'Animais', type:'fill', diff:1,
      q:'🐦 As aves nascem de ___.',
      ans:['ovos','ovo'],
      exp:'As aves põem ovos e os filhos saem deles.' },
    { id:'2ee153', s:'estudo_meio', t:'Animais', type:'order', diff:1,
      q:'Ordena as fases de vida da borboleta:',
      items:['ovo','lagarta','crisálida','borboleta'],
      exp:'ovo → lagarta → crisálida → borboleta.' },
    { id:'2ee154', s:'estudo_meio', t:'Animais', type:'mc', diff:1,
      q:'🐺 O cão descende do:',
      opts:['gato','lobo','urso','leão'], ans:1,
      exp:'O cão descende do lobo.' },
    { id:'2ee155', s:'estudo_meio', t:'Animais', type:'match', diff:1,
      q:'Associa o animal ao alimento que dá:',
      pairs:[['🐮 vaca','leite'],['🐔 galinha','ovos'],['🐝 abelha','mel'],['🐑 ovelha','lã']],
      exp:'Os animais dão-nos vários produtos.' },
    { id:'2ee156', s:'estudo_meio', t:'Animais', type:'tf', diff:1,
      q:'🐶 Devemos cuidar dos animais com carinho.',
      ans:true,
      exp:'Os animais merecem respeito e cuidado.' },

    // ============================================================
    // ===================== PLANTAS (39) =========================
    // ============================================================
    { id:'2ee157', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'🌱 Qual é a parte da planta que está dentro da terra?',
      opts:['flor','folha','raiz','fruto'], ans:2,
      exp:'A raiz fica enterrada e absorve água.' },
    { id:'2ee158', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'🍃 Qual é a parte da planta que faz o alimento?',
      opts:['raiz','caule','folha','fruto'], ans:2,
      exp:'As folhas fazem o alimento (fotossíntese).' },
    { id:'2ee159', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌳 A oliveira dá:',
      opts:['azeitonas','laranjas','maçãs','peras'], ans:0,
      exp:'A oliveira dá azeitonas (de onde vem o azeite).' },
    { id:'2ee160', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌰 O sobreiro dá:',
      opts:['cortiça','azeitonas','pinhões','laranjas'], ans:0,
      exp:'O sobreiro é a árvore da cortiça.' },
    { id:'2ee161', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌲 O pinheiro dá:',
      opts:['azeitonas','pinhões','maçãs','peras'], ans:1,
      exp:'O pinheiro dá pinhões.' },
    { id:'2ee162', s:'estudo_meio', t:'Plantas', type:'fill', diff:2,
      q:'🌻 O ___ é a parte colorida da planta que dá origem ao fruto.',
      ans:['flor'],
      exp:'A flor transforma-se em fruto.' },
    { id:'2ee163', s:'estudo_meio', t:'Plantas', type:'tf', diff:2,
      q:'🌳 As árvores são plantas grandes com tronco lenhoso.',
      ans:true,
      exp:'As árvores têm tronco grosso e duro (lenhoso).' },
    { id:'2ee164', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🍅 O tomate é um:',
      opts:['vegetal','fruto','flor','raiz'], ans:1,
      exp:'O tomate é o fruto do tomateiro.' },
    { id:'2ee165', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🥔 A batata é uma:',
      opts:['fruta','raiz/tubérculo','flor','folha'], ans:1,
      exp:'A batata é um tubérculo (cresce debaixo da terra).' },
    { id:'2ee166', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🥬 A alface é uma:',
      opts:['raiz','folha','fruto','flor'], ans:1,
      exp:'Comemos as folhas da alface.' },
    { id:'2ee167', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌷 O brócolo é uma:',
      opts:['raiz','flor','folha','fruto'], ans:1,
      exp:'Os brócolos são as flores ainda não abertas.' },
    { id:'2ee168', s:'estudo_meio', t:'Plantas', type:'fill', diff:2,
      q:'☀️ As plantas precisam de sol, ar e ___ para viver.',
      ans:['água','agua'],
      exp:'Sol, ar e água são essenciais às plantas.' },
    { id:'2ee169', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌳 O tronco da árvore é coberto por:',
      opts:['casca','escamas','penas','pele'], ans:0,
      exp:'O tronco é coberto por casca.' },
    { id:'2ee170', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌰 O fruto da castanheira é:',
      opts:['o pinhão','a castanha','a azeitona','a laranja'], ans:1,
      exp:'A castanheira dá castanhas.' },
    { id:'2ee171', s:'estudo_meio', t:'Plantas', type:'tf', diff:1,
      q:'🌲 As plantas dão oxigénio ao ar.',
      ans:true,
      exp:'As plantas libertam oxigénio que respiramos.' },
    { id:'2ee172', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌳 De onde vem a madeira?',
      opts:['das raízes','do tronco das árvores','das folhas','das flores'], ans:1,
      exp:'A madeira vem do tronco das árvores.' },
    { id:'2ee173', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🍇 O cacho de ___ cresce na videira.',
      opts:['cerejas','uvas','laranjas','maçãs'], ans:1,
      exp:'A uva cresce em cachos na videira.' },
    { id:'2ee174', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'🌷 A flor que cheira muito bem e tem espinhos é a:',
      opts:['rosa','margarida','girassol','tulipa'], ans:0,
      exp:'A rosa tem espinhos no caule.' },
    { id:'2ee175', s:'estudo_meio', t:'Plantas', type:'fill', diff:1,
      q:'🍊 A laranja cresce na ___.',
      ans:['laranjeira'],
      exp:'A laranja é fruto da laranjeira.' },
    { id:'2ee176', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌾 A farinha do pão vem do:',
      opts:['arroz','trigo','milho só','feijão'], ans:1,
      exp:'A farinha de trigo serve para fazer o pão.' },
    { id:'2ee177', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🍒 As cerejas são um:',
      opts:['vegetal','fruto','flor','tubérculo'], ans:1,
      exp:'As cerejas são frutos da cerejeira.' },
    { id:'2ee178', s:'estudo_meio', t:'Plantas', type:'tf', diff:2,
      q:'🌱 As sementes podem dar origem a novas plantas.',
      ans:true,
      exp:'Das sementes nascem plantas novas.' },
    { id:'2ee179', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'💧 Como se chama o líquido que sobe pelo caule da planta?',
      opts:['sangue','seiva','sumo','água'], ans:1,
      exp:'A seiva é o "alimento" da planta.' },
    { id:'2ee180', s:'estudo_meio', t:'Plantas', type:'order', diff:1,
      q:'Ordena o crescimento da planta:',
      items:['semente','rebento','planta jovem','planta com flores'],
      exp:'semente → rebento → planta jovem → planta com flores.' },
    { id:'2ee181', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌿 As plantas que comemos chamam-se:',
      opts:['ornamentais','comestíveis','venenosas','tropicais'], ans:1,
      exp:'Plantas comestíveis são as que se comem.' },
    { id:'2ee182', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'🌹 As plantas que se cultivam pela beleza chamam-se:',
      opts:['comestíveis','ornamentais','aromáticas','medicinais'], ans:1,
      exp:'Plantas ornamentais decoram (rosas, malmequeres).' },
    { id:'2ee183', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌿 A salsa e os coentros são plantas:',
      opts:['venenosas','aromáticas','aquáticas','tropicais'], ans:1,
      exp:'São plantas aromáticas, usam-se na cozinha.' },
    { id:'2ee184', s:'estudo_meio', t:'Plantas', type:'fill', diff:1,
      q:'🌳 A árvore que dá maçãs chama-se ___.',
      ans:['macieira'],
      exp:'A maçã é fruto da macieira.' },
    { id:'2ee185', s:'estudo_meio', t:'Plantas', type:'tf', diff:1,
      q:'🌲 O pinheiro é uma árvore.',
      ans:true,
      exp:'O pinheiro é uma árvore de folha persistente.' },
    { id:'2ee186', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌻 O girassol vira-se para o:',
      opts:['mar','sol','chão','vento'], ans:1,
      exp:'O girassol acompanha o sol durante o dia.' },
    { id:'2ee187', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌳 O fruto do pinheiro chama-se:',
      opts:['pinha','azeitona','noz','figo'], ans:0,
      exp:'A pinha é o fruto do pinheiro (com pinhões).' },
    { id:'2ee188', s:'estudo_meio', t:'Plantas', type:'match', diff:1,
      q:'Associa cada árvore ao fruto:',
      pairs:[['🌳 oliveira','azeitona'],['🌳 macieira','maçã'],['🌲 pinheiro','pinhão'],['🌳 castanheira','castanha']],
      exp:'Cada árvore dá um fruto.' },
    { id:'2ee189', s:'estudo_meio', t:'Plantas', type:'mc', diff:2,
      q:'🌷 Que parte da planta tem cores e cheira bem?',
      opts:['raiz','caule','flor','tronco'], ans:2,
      exp:'A flor tem cores e cheiro para atrair insetos.' },
    { id:'2ee190', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌳 Como devemos cuidar das plantas?',
      opts:['regar e tratar','arrancar','queimar','pisar'], ans:0,
      exp:'Devemos cuidar e proteger as plantas.' },
    { id:'2ee191', s:'estudo_meio', t:'Plantas', type:'fill', diff:1,
      q:'🍐 A pera cresce na ___.',
      ans:['pereira'],
      exp:'A pereira é a árvore das peras.' },
    { id:'2ee192', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌳 A cortiça de Portugal vem do:',
      opts:['pinheiro','sobreiro','eucalipto','carvalho'], ans:1,
      exp:'O sobreiro dá a cortiça (Portugal é o maior produtor mundial).' },
    { id:'2ee193', s:'estudo_meio', t:'Plantas', type:'tf', diff:2,
      q:'🍂 No outono caem as folhas de algumas árvores.',
      ans:true,
      exp:'Árvores de folha caduca perdem folhas no outono.' },
    { id:'2ee194', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'🌽 O milho é um:',
      opts:['fruto','cereal','tubérculo','flor'], ans:1,
      exp:'O milho é um cereal.' },
    { id:'2ee195', s:'estudo_meio', t:'Plantas', type:'mc', diff:1,
      q:'💧 As plantas absorvem a água pela:',
      opts:['flor','folha','raiz','fruto'], ans:2,
      exp:'A raiz absorve a água do solo.' },

    // ============================================================
    // ===================== ESTAÇÕES DO ANO (38) =================
    // ============================================================
    { id:'2ee196', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'☀️ Em que estação vamos à praia?',
      opts:['Inverno','Verão','Outono','Primavera'], ans:1,
      exp:'O verão é quente, ideal para a praia.' },
    { id:'2ee197', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'🍂 Em que estação as folhas mudam de cor?',
      opts:['Verão','Outono','Inverno','Primavera'], ans:1,
      exp:'No outono as folhas ficam amarelas e castanhas.' },
    { id:'2ee198', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'❄️ Em alguns países, em que estação cai neve?',
      opts:['Verão','Inverno','Primavera','Outono'], ans:1,
      exp:'A neve cai no Inverno (no frio).' },
    { id:'2ee199', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌸 Em que estação nascem muitas flores?',
      opts:['Primavera','Outono','Inverno','não há'], ans:0,
      exp:'A Primavera é a estação das flores.' },
    { id:'2ee200', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:2,
      q:'🍇 O ___ é a estação em que se faz a vindima.',
      ans:['outono','Outono'],
      exp:'A vindima (colheita das uvas) faz-se no outono.' },
    { id:'2ee201', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌧️ Que objeto usamos quando chove?',
      opts:['guarda-sol','guarda-chuva','chapéu de palha','óculos'], ans:1,
      exp:'O guarda-chuva protege-nos da chuva.' },
    { id:'2ee202', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'☀️ Que objeto usamos com muito sol forte?',
      opts:['cachecol','luvas','óculos de sol','botas de neve'], ans:2,
      exp:'Os óculos de sol protegem os olhos.' },
    { id:'2ee203', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:1,
      q:'🍓 No verão amadurecem muitos frutos.',
      ans:true,
      exp:'Verão é época de morangos, melancia, pêssegos.' },
    { id:'2ee204', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'❄️ Em que mês acaba o Inverno?',
      opts:['Janeiro','Março','Junho','Setembro'], ans:1,
      exp:'O Inverno termina em março.' },
    { id:'2ee205', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'☀️ Em que mês começa o Verão?',
      opts:['Junho','Setembro','Dezembro','Março'], ans:0,
      exp:'O verão começa em junho.' },
    { id:'2ee206', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🍂 Em que mês começa o Outono?',
      opts:['Setembro','Junho','Março','Dezembro'], ans:0,
      exp:'O outono começa em setembro.' },
    { id:'2ee207', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌞 Quantas estações tem o ano?',
      opts:['2','3','4','5'], ans:2,
      exp:'O ano tem 4 estações.' },
    { id:'2ee208', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:2,
      q:'🌸 As 4 estações são: Primavera, Verão, Outono e ___.',
      ans:['Inverno','inverno'],
      exp:'As 4 estações: Primavera, Verão, Outono, Inverno.' },
    { id:'2ee209', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'🥶 Em que estação usamos cachecol e luvas?',
      opts:['Verão','Inverno','Primavera','Outono'], ans:1,
      exp:'No Inverno está frio.' },
    { id:'2ee210', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:1,
      q:'🌧️ No outono começa a chover mais.',
      ans:true,
      exp:'No outono começam as chuvas.' },
    { id:'2ee211', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🍉 Que fruto associamos ao verão?',
      opts:['castanha','melancia','laranja','maçã'], ans:1,
      exp:'A melancia é típica do verão.' },
    { id:'2ee212', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌰 Que fruto associamos ao outono?',
      opts:['cereja','castanha','melancia','morango'], ans:1,
      exp:'A castanha é típica de outono (S. Martinho).' },
    { id:'2ee213', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🍊 Que fruto é típico do inverno?',
      opts:['laranja/tangerina','melancia','morango','cereja'], ans:0,
      exp:'Citrinos são típicos do inverno.' },
    { id:'2ee214', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🍓 Que fruto é típico da primavera?',
      opts:['castanha','morango','noz','laranja'], ans:1,
      exp:'O morango aparece na primavera.' },
    { id:'2ee215', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:1,
      q:'❄️ O Inverno é a estação mais ___.',
      ans:['fria','fria do ano'],
      exp:'No Inverno está frio.' },
    { id:'2ee216', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'🍂 Em São Martinho (11 de novembro) comem-se:',
      opts:['gelados','castanhas','melancia','laranjas'], ans:1,
      exp:'No S. Martinho comem-se castanhas assadas (magusto).' },
    { id:'2ee217', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:1,
      q:'🌞 Os dias são mais compridos no verão.',
      ans:true,
      exp:'No verão o sol nasce mais cedo e põe-se mais tarde.' },
    { id:'2ee218', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:1,
      q:'🌜 Os dias são mais curtos no inverno.',
      ans:true,
      exp:'No inverno escurece mais cedo.' },
    { id:'2ee219', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'🌳 Em que estação se podam as árvores e se semeia?',
      opts:['Verão','Outono','Inverno/Primavera','não há'], ans:2,
      exp:'A poda faz-se no inverno; sementeiras na primavera.' },
    { id:'2ee220', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'🍃 Que tipo de roupa usamos na primavera?',
      opts:['só agasalhos','roupa leve mas com casaco fino','fato de banho só','botas de neve'], ans:1,
      exp:'Na primavera o tempo varia, usamos roupa leve com casaco.' },
    { id:'2ee221', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:2,
      q:'☀️ A estação em que vamos de férias à praia é o ___.',
      ans:['verão','Verão','verao'],
      exp:'No verão são as férias grandes (praia).' },
    { id:'2ee222', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌸 Que mês é da Páscoa, normalmente?',
      opts:['Janeiro','Março/Abril','Junho','Agosto'], ans:1,
      exp:'A Páscoa é entre março e abril (primavera).' },
    { id:'2ee223', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🎄 Em que estação é o Natal?',
      opts:['Verão','Outono','Inverno','Primavera'], ans:2,
      exp:'O Natal (25/12) é no Inverno.' },
    { id:'2ee224', s:'estudo_meio', t:'Estações do ano', type:'order', diff:2,
      q:'Ordena os meses pela ordem do calendário:',
      items:['janeiro','abril','julho','outubro'],
      exp:'janeiro → abril → julho → outubro.' },
    { id:'2ee225', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'📅 Quantos meses tem cada estação, mais ou menos?',
      opts:['1','2','3','4'], ans:2,
      exp:'Cada estação tem cerca de 3 meses.' },
    { id:'2ee226', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🐦 As andorinhas voltam a Portugal na:',
      opts:['Primavera','Inverno','Outono só','nunca'], ans:0,
      exp:'As andorinhas chegam na primavera.' },
    { id:'2ee227', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:2,
      q:'🌷 Na primavera o tempo aquece e nascem flores.',
      ans:true,
      exp:'A primavera é a estação do despertar da natureza.' },
    { id:'2ee228', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌳 Que estação vem a seguir ao verão?',
      opts:['Inverno','Outono','Primavera','outro verão'], ans:1,
      exp:'Depois do verão vem o outono.' },
    { id:'2ee229', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌷 Que estação vem a seguir ao inverno?',
      opts:['Verão','Primavera','Outono','outra vez Inverno'], ans:1,
      exp:'Depois do inverno vem a primavera.' },
    { id:'2ee230', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:1,
      q:'🍂 Cai a folha das árvores no ___.',
      ans:['outono','Outono'],
      exp:'No outono caem as folhas (das árvores de folha caduca).' },
    { id:'2ee231', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:1,
      q:'🌧️ A chuva forma-se a partir de:',
      opts:['areia','água que evapora','vento','sol'], ans:1,
      exp:'A água evapora, forma nuvens e cai como chuva.' },
    { id:'2ee232', s:'estudo_meio', t:'Estações do ano', type:'match', diff:1,
      q:'Associa cada estação ao fruto típico:',
      pairs:[['🌸 Primavera','morango'],['☀️ Verão','melancia'],['🍂 Outono','castanha'],['❄️ Inverno','laranja']],
      exp:'Cada estação tem frutos típicos.' },
    { id:'2ee233', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:2,
      q:'⛄ Onde, em Portugal, costuma cair mais neve?',
      opts:['Algarve','Serra da Estrela','Lisboa','Açores tropical'], ans:1,
      exp:'A Serra da Estrela é o local com mais neve em Portugal.' },

    // ============================================================
    // ===================== OS SENTIDOS (40) =====================
    // ============================================================
    { id:'2ee234', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👁️ Quantos olhos temos?',
      opts:['1','2','3','4'], ans:1,
      exp:'Temos 2 olhos.' },
    { id:'2ee235', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👂 Quantas orelhas temos?',
      opts:['1','2','3','4'], ans:1,
      exp:'Temos 2 orelhas.' },
    { id:'2ee236', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👃 Quantos narizes temos?',
      opts:['1','2','3','4'], ans:0,
      exp:'Temos 1 nariz.' },
    { id:'2ee237', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👅 O órgão do paladar é a:',
      opts:['boca','língua','garganta','dente'], ans:1,
      exp:'A língua é o órgão do paladar.' },
    { id:'2ee238', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'👁️ Os olhos são o órgão da ___.',
      ans:['visão','visao','vista'],
      exp:'A visão faz-se com os olhos.' },
    { id:'2ee239', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:2,
      q:'👂 As orelhas (ouvidos) são o órgão da ___.',
      ans:['audição','audicao'],
      exp:'A audição faz-se com os ouvidos.' },
    { id:'2ee240', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'👃 O nariz é o órgão do ___.',
      ans:['olfato'],
      exp:'O olfato faz-se com o nariz (cheiros).' },
    { id:'2ee241', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'👅 A língua é o órgão do ___.',
      ans:['paladar','gosto'],
      exp:'O paladar é o sabor (com a língua).' },
    { id:'2ee242', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'✋ A pele é o órgão do ___.',
      ans:['tato'],
      exp:'O tato faz-se com a pele.' },
    { id:'2ee243', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'🍦 Para sentir o sabor doce de um gelado uso o:',
      opts:['olfato','paladar','tato','visão'], ans:1,
      exp:'O paladar permite saborear.' },
    { id:'2ee244', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'🌹 Para sentir o cheiro de uma rosa uso o:',
      opts:['paladar','tato','olfato','audição'], ans:2,
      exp:'O olfato é para os cheiros.' },
    { id:'2ee245', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🎵 Para ouvir música uso a:',
      opts:['visão','audição','olfato','tato'], ans:1,
      exp:'A audição é para os sons.' },
    { id:'2ee246', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'🐶 Para ver um cachorro a brincar uso a:',
      opts:['visão','audição','olfato','paladar'], ans:0,
      exp:'A visão permite ver.' },
    { id:'2ee247', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🧊 Para sentir que o gelo é frio uso o:',
      opts:['olfato','paladar','tato','visão'], ans:2,
      exp:'O tato sente o frio, o calor, a textura.' },
    { id:'2ee248', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:2,
      q:'🥒 Os sabores são doce, salgado, ácido e amargo.',
      ans:true,
      exp:'4 sabores básicos (e o umami).' },
    { id:'2ee249', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🍋 O limão tem sabor:',
      opts:['doce','salgado','ácido','amargo'], ans:2,
      exp:'O limão é ácido (azedo).' },
    { id:'2ee250', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🍫 O chocolate normalmente é:',
      opts:['doce','ácido','salgado','amargo'], ans:0,
      exp:'O chocolate de leite é doce.' },
    { id:'2ee251', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🧂 O sal tem sabor:',
      opts:['doce','salgado','ácido','sem sabor'], ans:1,
      exp:'O sal é salgado.' },
    { id:'2ee252', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:1,
      q:'👀 Os olhos veem cores e formas.',
      ans:true,
      exp:'A visão permite distinguir cores e formas.' },
    { id:'2ee253', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'✋ Para saber se uma coisa é áspera ou macia uso o:',
      opts:['olfato','paladar','tato','audição'], ans:2,
      exp:'O tato distingue texturas.' },
    { id:'2ee254', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'👁️ Devemos proteger os olhos do sol forte com:',
      opts:['guarda-chuva','óculos de sol','luvas','cachecol'], ans:1,
      exp:'Os óculos de sol protegem os olhos.' },
    { id:'2ee255', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'🦻 Os sons muito altos podem fazer mal aos:',
      opts:['olhos','ouvidos','dedos','pés'], ans:1,
      exp:'O barulho excessivo prejudica os ouvidos.' },
    { id:'2ee256', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'👁️👂👃👅✋ Há ___ sentidos.',
      ans:['5','cinco'],
      exp:'5 sentidos: visão, audição, olfato, paladar e tato.' },
    { id:'2ee257', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:2,
      q:'👃 As pessoas com constipação não cheiram bem.',
      ans:true,
      exp:'O nariz tapado dificulta o olfato.' },
    { id:'2ee258', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🦮 Quem não vê chama-se:',
      opts:['surdo','cego/invisual','mudo','manco'], ans:1,
      exp:'Quem não vê é cego (invisual). Pode usar bengala ou cão-guia.' },
    { id:'2ee259', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🤟 Quem não ouve chama-se:',
      opts:['cego','surdo','mudo','manco'], ans:1,
      exp:'Quem não ouve é surdo. Pode usar língua gestual.' },
    { id:'2ee260', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'👀 Que cor é a banana? Uso o sentido da:',
      opts:['visão','audição','olfato','paladar'], ans:0,
      exp:'A visão distingue as cores.' },
    { id:'2ee261', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👂 Para ouvir alguém a falar uso a:',
      opts:['visão','audição','olfato','tato'], ans:1,
      exp:'A audição capta a voz.' },
    { id:'2ee262', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:1,
      q:'👅 O sumo de laranja é ___.',
      ans:['ácido','acido','azedo','doce'],
      exp:'O sumo de laranja é ligeiramente ácido (e doce).' },
    { id:'2ee263', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'✋ Que parte do corpo cobre todo o nosso corpo (órgão do tato)?',
      opts:['cabelo','pele','unhas','músculos'], ans:1,
      exp:'A pele cobre o corpo e é o órgão do tato.' },
    { id:'2ee264', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:2,
      q:'👃 Não devemos meter objetos pequenos no nariz.',
      ans:true,
      exp:'É perigoso. Devemos cuidar do nariz.' },
    { id:'2ee265', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🔥 Tocar no fogo dá uma sensação de:',
      opts:['frio','dor / queimadura','suave','nada'], ans:1,
      exp:'Sentimos dor; é o tato a avisar de perigo.' },
    { id:'2ee266', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'🍭 Sabor doce, salgado e ácido são apreciados pelo:',
      opts:['olfato','paladar','tato','visão'], ans:1,
      exp:'O paladar é o sentido dos sabores.' },
    { id:'2ee267', s:'estudo_meio', t:'Os sentidos', type:'match', diff:1,
      q:'Associa o sentido à ação:',
      pairs:[['👁️ visão','ver as cores'],['👂 audição','ouvir música'],['👃 olfato','cheirar uma flor'],['👅 paladar','provar o chocolate']],
      exp:'Cada sentido tem ações próprias.' },
    { id:'2ee268', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🧴 Para cuidar dos ouvidos:',
      opts:['meter cotonetes fundo','não meter objetos pontiagudos','ouvir muito alto','molhar muito'], ans:1,
      exp:'Não devemos meter objetos pontiagudos nos ouvidos.' },
    { id:'2ee269', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'👀 Para cuidar dos olhos:',
      opts:['olhar para o sol','ler com muita luz e ir ao oftalmologista','esfregar muito','tocar com mãos sujas'], ans:1,
      exp:'Boa luz, repouso e consultas regulares ao oftalmologista.' },
    { id:'2ee270', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:2,
      q:'👁️👂 Os sentidos ajudam-nos a conhecer o mundo.',
      ans:true,
      exp:'Os sentidos dão-nos informação sobre o ambiente.' },
    { id:'2ee271', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:2,
      q:'👀 As pessoas que veem mal podem usar ___.',
      ans:['óculos','oculos'],
      exp:'Os óculos ajudam a ver melhor.' },
    { id:'2ee272', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:1,
      q:'🌶️ A malagueta é:',
      opts:['doce','picante','salgada só','sem sabor'], ans:1,
      exp:'A malagueta é picante.' },
    { id:'2ee273', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:2,
      q:'👃 O olfato e o ___ funcionam juntos para apreciarmos a comida.',
      opts:['paladar','tato','audição','visão'], ans:0,
      exp:'Olfato e paladar trabalham juntos no sabor.' },

    // ============================================================
    // ===================== PROFISSÕES (39) ======================
    // ============================================================
    { id:'2ee274', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'👨‍⚕️ Quem trata das pessoas doentes?',
      opts:['médico','padeiro','motorista','jardineiro'], ans:0,
      exp:'O médico trata as pessoas doentes.' },
    { id:'2ee275', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'👩‍⚕️ Quem ajuda o médico no hospital?',
      opts:['enfermeiro','padeiro','professor','agricultor'], ans:0,
      exp:'O enfermeiro/a ajuda o médico e cuida dos doentes.' },
    { id:'2ee276', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🎣 Quem apanha peixe no mar?',
      opts:['pescador','agricultor','padeiro','médico'], ans:0,
      exp:'O pescador captura peixe.' },
    { id:'2ee277', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🌳 Quem cuida das plantas e jardins?',
      opts:['jardineiro','médico','bombeiro','padeiro'], ans:0,
      exp:'O jardineiro cuida dos jardins.' },
    { id:'2ee278', s:'estudo_meio', t:'Profissões', type:'mc', diff:2,
      q:'🍳 Quem cozinha refeições no restaurante?',
      opts:['cozinheiro','professor','médico','padeiro'], ans:0,
      exp:'O cozinheiro prepara as refeições.' },
    { id:'2ee279', s:'estudo_meio', t:'Profissões', type:'fill', diff:2,
      q:'👮 Quem mantém a ordem e ajuda nas ruas? O ___.',
      ans:['polícia','policia'],
      exp:'A polícia ajuda e protege os cidadãos.' },
    { id:'2ee280', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🚌 Quem conduz o autocarro?',
      opts:['motorista','padeiro','médico','pescador'], ans:0,
      exp:'O motorista conduz veículos.' },
    { id:'2ee281', s:'estudo_meio', t:'Profissões', type:'mc', diff:2,
      q:'🔧 Quem arranja canos, torneiras e fugas de água?',
      opts:['eletricista','canalizador','pintor','carpinteiro'], ans:1,
      exp:'O canalizador arranja canos e torneiras.' },
    { id:'2ee282', s:'estudo_meio', t:'Profissões', type:'mc', diff:2,
      q:'⚡ Quem instala e arranja a luz e cabos elétricos?',
      opts:['eletricista','canalizador','padeiro','jardineiro'], ans:0,
      exp:'O eletricista trata da eletricidade.' },
    { id:'2ee283', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🎨 Quem pinta paredes e edifícios?',
      opts:['pintor','professor','padeiro','médico'], ans:0,
      exp:'O pintor pinta paredes.' },
    { id:'2ee284', s:'estudo_meio', t:'Profissões', type:'mc', diff:2,
      q:'🛒 Quem nos atende no supermercado/loja?',
      opts:['comerciante/empregado','médico','agricultor','bombeiro'], ans:0,
      exp:'O empregado de loja atende clientes.' },
    { id:'2ee285', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'📰 Quem escreve as notícias?',
      opts:['jornalista','professor só','médico','agricultor'], ans:0,
      exp:'O jornalista informa-nos sobre os acontecimentos.' },
    { id:'2ee286', s:'estudo_meio', t:'Profissões', type:'tf', diff:2,
      q:'👨‍🚒 O bombeiro também salva pessoas em acidentes.',
      ans:true,
      exp:'Os bombeiros apagam fogos e salvam vidas.' },
    { id:'2ee287', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'⚽ Quem joga no campo e marca golos?',
      opts:['futebolista','médico','padeiro','professor'], ans:0,
      exp:'O futebolista é um atleta de futebol.' },
    { id:'2ee288', s:'estudo_meio', t:'Profissões', type:'fill', diff:1,
      q:'🎬 Quem representa nos filmes? O ___.',
      ans:['ator','actor'],
      exp:'O ator (atriz) representa em filmes/teatro.' },
    { id:'2ee289', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🎵 Quem canta numa banda ou faz CDs?',
      opts:['cantor','professor','médico','padeiro'], ans:0,
      exp:'O cantor (cantora) canta profissionalmente.' },
    { id:'2ee290', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'✈️ Quem pilota o avião?',
      opts:['piloto','marinheiro','motorista','professor'], ans:0,
      exp:'O piloto conduz o avião.' },
    { id:'2ee291', s:'estudo_meio', t:'Profissões', type:'mc', diff:2,
      q:'🚢 Quem trabalha no mar a navegar em barcos?',
      opts:['marinheiro','jardineiro','médico','pintor'], ans:0,
      exp:'O marinheiro trabalha em navios.' },
    { id:'2ee292', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🧱 Quem constrói casas e prédios?',
      opts:['pedreiro','agricultor','médico','padeiro'], ans:0,
      exp:'O pedreiro/construtor faz a construção.' },
    { id:'2ee293', s:'estudo_meio', t:'Profissões', type:'fill', diff:1,
      q:'🦷 O ___ trata dos dentes.',
      ans:['dentista'],
      exp:'O dentista cuida dos dentes.' },
    { id:'2ee294', s:'estudo_meio', t:'Profissões', type:'tf', diff:2,
      q:'👨‍🚒 Os bombeiros usam fato amarelo e capacete.',
      ans:true,
      exp:'O equipamento dos bombeiros protege-os.' },
    { id:'2ee295', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'💊 Quem vende medicamentos na farmácia?',
      opts:['farmacêutico','médico','enfermeiro','dentista'], ans:0,
      exp:'O farmacêutico trabalha na farmácia.' },
    { id:'2ee296', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'⚖️ Quem julga os casos no tribunal?',
      opts:['juiz','padeiro','agricultor','pintor'], ans:0,
      exp:'O juiz julga e decide os casos.' },
    { id:'2ee297', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'⚖️ Quem defende as pessoas no tribunal?',
      opts:['advogado','médico','enfermeiro','professor'], ans:0,
      exp:'O advogado defende clientes na justiça.' },
    { id:'2ee298', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'👗 Quem faz roupa?',
      opts:['costureiro','padeiro','médico','jardineiro'], ans:0,
      exp:'O costureiro/alfaiate faz roupa.' },
    { id:'2ee299', s:'estudo_meio', t:'Profissões', type:'fill', diff:2,
      q:'🛍️ Quem vende coisas na loja chama-se ___ .',
      ans:['comerciante','vendedor','vendedora'],
      exp:'O comerciante/vendedor vende produtos.' },
    { id:'2ee300', s:'estudo_meio', t:'Profissões', type:'mc', diff:2,
      q:'🍷 Quem trabalha nas vinhas e faz o vinho?',
      opts:['agricultor/vinicultor','padeiro','marinheiro','pescador'], ans:0,
      exp:'O agricultor/vinicultor cultiva uvas e produz vinho.' },
    { id:'2ee301', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🐟 Onde trabalha o pescador?',
      opts:['no mar/rio','no campo','na floresta','na padaria'], ans:0,
      exp:'O pescador trabalha no mar ou no rio.' },
    { id:'2ee302', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🌾 Onde trabalha o agricultor?',
      opts:['no campo','no mar','na fábrica','no escritório'], ans:0,
      exp:'O agricultor trabalha no campo.' },
    { id:'2ee303', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🏥 Onde trabalha o médico?',
      opts:['hospital/centro de saúde','padaria','escola só','quartel'], ans:0,
      exp:'O médico trabalha em hospitais e centros de saúde.' },
    { id:'2ee304', s:'estudo_meio', t:'Profissões', type:'tf', diff:2,
      q:'👨‍🏫 Todas as profissões são importantes para a sociedade.',
      ans:true,
      exp:'Todas as profissões servem a comunidade.' },
    { id:'2ee305', s:'estudo_meio', t:'Profissões', type:'match', diff:2,
      q:'Associa cada profissão ao local de trabalho:',
      pairs:[['👨‍⚕️ médico','hospital'],['👨‍🏫 professor','escola'],['🍞 padeiro','padaria'],['🚒 bombeiro','quartel']],
      exp:'Cada profissão tem o seu local.' },
    { id:'2ee306', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🚒 Os bombeiros trabalham no:',
      opts:['quartel','hospital','padaria','tribunal'], ans:0,
      exp:'Os bombeiros trabalham num quartel.' },
    { id:'2ee307', s:'estudo_meio', t:'Profissões', type:'fill', diff:1,
      q:'👮 A esquadra é onde trabalha a ___.',
      ans:['polícia','policia'],
      exp:'A polícia trabalha na esquadra.' },
    { id:'2ee308', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🚜 O agricultor pode usar:',
      opts:['trator','autocarro','barco','avião'], ans:0,
      exp:'O trator é uma das máquinas do agricultor.' },
    { id:'2ee309', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🎓 Para ser professor é preciso:',
      opts:['saber só ler','estudar muito (universidade)','ter um carro','ter força'], ans:1,
      exp:'O professor estuda muitos anos para ensinar.' },
    { id:'2ee310', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'💇 Quem corta o cabelo?',
      opts:['cabeleireiro/barbeiro','padeiro','médico','jardineiro'], ans:0,
      exp:'O cabeleireiro/barbeiro corta o cabelo.' },
    { id:'2ee311', s:'estudo_meio', t:'Profissões', type:'order', diff:2,
      q:'Ordena os passos para obter pão (do início ao fim):',
      items:['agricultor cultiva trigo','moinho mói o trigo','padeiro faz o pão','vendemos na padaria'],
      exp:'Cultivo → moagem → padeiro → venda.' },
    { id:'2ee312', s:'estudo_meio', t:'Profissões', type:'mc', diff:1,
      q:'🍞 Onde compramos o pão?',
      opts:['padaria','farmácia','escola','sapataria'], ans:0,
      exp:'O pão vende-se na padaria.' },

    // ============================================================
    // ===================== PORTUGAL (36) ========================
    // ============================================================
    { id:'2ee313', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🇵🇹 Quantas estrelas tem a bandeira de Portugal?',
      opts:['nenhuma','5','7','12'], ans:0,
      exp:'A bandeira de Portugal não tem estrelas; tem o brasão e a esfera armilar.' },
    { id:'2ee314', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌊 Que rio passa em Lisboa?',
      opts:['Douro','Tejo','Mondego','Sado'], ans:1,
      exp:'O Tejo passa em Lisboa.' },
    { id:'2ee315', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🍷 De que cidade portuguesa é famoso o vinho do Porto?',
      opts:['Lisboa','Porto','Faro','Évora'], ans:1,
      exp:'O Vinho do Porto vem da região do Douro/Porto.' },
    { id:'2ee316', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🐟 Que peixe se come muito em Portugal?',
      opts:['bacalhau','tubarão','baleia','golfinho'], ans:0,
      exp:'O bacalhau é o "fiel amigo" dos portugueses.' },
    { id:'2ee317', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌍 Que país está a leste de Portugal?',
      opts:['França','Espanha','Marrocos','Itália'], ans:1,
      exp:'Espanha faz fronteira com Portugal a leste.' },
    { id:'2ee318', s:'estudo_meio', t:'Portugal', type:'fill', diff:1,
      q:'🇵🇹 A capital de Portugal é ___.',
      ans:['Lisboa','lisboa'],
      exp:'Lisboa é a capital.' },
    { id:'2ee319', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌊 Que oceano fica a oeste de Portugal?',
      opts:['Pacífico','Atlântico','Índico','Mediterrâneo'], ans:1,
      exp:'O oceano Atlântico banha Portugal a oeste.' },
    { id:'2ee320', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🏰 Em que cidade fica a Torre de Belém?',
      opts:['Porto','Lisboa','Coimbra','Faro'], ans:1,
      exp:'A Torre de Belém fica em Lisboa.' },
    { id:'2ee321', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🎓 Em que cidade fica a Universidade mais antiga de Portugal?',
      opts:['Lisboa','Porto','Coimbra','Évora'], ans:2,
      exp:'A Universidade de Coimbra é a mais antiga (1290).' },
    { id:'2ee322', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'☀️ Que região fica no sul de Portugal e tem muitas praias?',
      opts:['Algarve','Minho','Beira','Trás-os-Montes'], ans:0,
      exp:'O Algarve é o sul, com praias famosas.' },
    { id:'2ee323', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🏝️ Que arquipélago português fica perto de África?',
      opts:['Açores','Madeira','Bermudas','Canárias'], ans:1,
      exp:'A Madeira fica perto de África.' },
    { id:'2ee324', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🌋 Os Açores são um arquipélago no oceano:',
      opts:['Pacífico','Atlântico','Índico','Ártico'], ans:1,
      exp:'Os Açores estão no oceano Atlântico.' },
    { id:'2ee325', s:'estudo_meio', t:'Portugal', type:'fill', diff:2,
      q:'🇵🇹 A bandeira portuguesa é verde e ___.',
      ans:['vermelha','vermelho','encarnada'],
      exp:'A bandeira é verde e vermelha (encarnada).' },
    { id:'2ee326', s:'estudo_meio', t:'Portugal', type:'tf', diff:1,
      q:'🇵🇹 O Dia de Portugal é a 10 de junho.',
      ans:true,
      exp:'10 de junho — Dia de Portugal, de Camões e das Comunidades.' },
    { id:'2ee327', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🐓 O símbolo de Portugal "trazido das viagens" é o:',
      opts:['Galo de Barcelos','leão','urso','cavalo'], ans:0,
      exp:'O Galo de Barcelos é um símbolo popular.' },
    { id:'2ee328', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🎵 A música tradicional portuguesa mais conhecida no mundo é o:',
      opts:['fado','samba','rock','tango'], ans:0,
      exp:'O fado é Património Imaterial da Humanidade.' },
    { id:'2ee329', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🍮 Doce típico português, originário de Belém:',
      opts:['pastel de nata','bolo de chocolate','gelado','muffin'], ans:0,
      exp:'Os pastéis de nata (de Belém) são típicos.' },
    { id:'2ee330', s:'estudo_meio', t:'Portugal', type:'fill', diff:1,
      q:'🌊 O rio ___ atravessa o Porto.',
      ans:['Douro','douro'],
      exp:'O rio Douro passa no Porto.' },
    { id:'2ee331', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🏞️ Faro fica em que região?',
      opts:['Algarve','Alentejo','Minho','Madeira'], ans:0,
      exp:'Faro é a capital do Algarve.' },
    { id:'2ee332', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🌳 Évora fica em que região?',
      opts:['Algarve','Alentejo','Beira','Açores'], ans:1,
      exp:'Évora é uma cidade do Alentejo.' },
    { id:'2ee333', s:'estudo_meio', t:'Portugal', type:'tf', diff:2,
      q:'🏔️ O ponto mais alto de Portugal continental é a Serra da Estrela.',
      ans:true,
      exp:'A Torre, na Serra da Estrela (1993 m).' },
    { id:'2ee334', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🏔️ O ponto mais alto de Portugal fica em:',
      opts:['Açores (Pico)','Madeira','Lisboa','Porto'], ans:0,
      exp:'A montanha do Pico, nos Açores, tem 2351 m — o mais alto.' },
    { id:'2ee335', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🇵🇹 O Hino Nacional chama-se:',
      opts:['A Portuguesa','Os Lusíadas','A Bandeira','A Marselhesa'], ans:0,
      exp:'O hino é "A Portuguesa".' },
    { id:'2ee336', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🇵🇹 Quem é o chefe de estado de Portugal?',
      opts:['o rei','o presidente da República','o primeiro-ministro só','o juiz'], ans:1,
      exp:'O Presidente da República é o chefe de Estado.' },
    { id:'2ee337', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🏛️ Quem dirige o Governo de Portugal?',
      opts:['Presidente da República','Primeiro-Ministro','o juiz','o Papa'], ans:1,
      exp:'O Primeiro-Ministro chefia o Governo.' },
    { id:'2ee338', s:'estudo_meio', t:'Portugal', type:'fill', diff:1,
      q:'🌍 Portugal fica no continente ___.',
      ans:['europeu','Europa','europa'],
      exp:'Portugal é um país europeu.' },
    { id:'2ee339', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🍴 Prato típico português com bacalhau:',
      opts:['Bacalhau à Brás','sushi','pizza','hambúrguer'], ans:0,
      exp:'Bacalhau à Brás (e muitos outros) é típico português.' },
    { id:'2ee340', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🐟 Sardinhas assadas são típicas das festas:',
      opts:['de Natal','de Santo António / São João','de Páscoa','de Carnaval'], ans:1,
      exp:'Sardinhas assadas nos Santos Populares (junho).' },
    { id:'2ee341', s:'estudo_meio', t:'Portugal', type:'tf', diff:1,
      q:'🐓 Em Portugal fala-se português.',
      ans:true,
      exp:'A língua oficial é o português.' },
    { id:'2ee342', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'⚽ A seleção portuguesa de futebol é também conhecida como:',
      opts:['os Tigres','a Seleção das Quinas','as Águias','os Leões'], ans:1,
      exp:'A Seleção das Quinas (referência às quinas do escudo).' },
    { id:'2ee343', s:'estudo_meio', t:'Portugal', type:'match', diff:1,
      q:'Associa cada cidade à sua região:',
      pairs:[['Porto','Norte'],['Lisboa','Centro/Lisboa'],['Évora','Alentejo'],['Faro','Algarve']],
      exp:'Cidades em diferentes regiões de Portugal.' },
    { id:'2ee344', s:'estudo_meio', t:'Portugal', type:'mc', diff:2,
      q:'🚗 De Lisboa para o Porto, vamos para o:',
      opts:['Norte','Sul','Leste','Oeste'], ans:0,
      exp:'O Porto fica a norte de Lisboa.' },
    { id:'2ee345', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🚗 De Lisboa para Faro, vamos para o:',
      opts:['Norte','Sul','Leste','Oeste'], ans:1,
      exp:'Faro fica a sul de Lisboa.' },
    { id:'2ee346', s:'estudo_meio', t:'Portugal', type:'fill', diff:2,
      q:'🏙️ A 2.ª maior cidade de Portugal é o ___.',
      ans:['Porto','porto'],
      exp:'O Porto é a 2.ª maior cidade portuguesa.' },
    { id:'2ee347', s:'estudo_meio', t:'Portugal', type:'mc', diff:1,
      q:'🇵🇹 A moeda usada em Portugal é o:',
      opts:['euro','dólar','real','escudo'], ans:0,
      exp:'Portugal usa o euro (€).' },
    { id:'2ee348', s:'estudo_meio', t:'Portugal', type:'order', diff:1,
      q:'Ordena de norte para sul (continente):',
      items:['Braga','Porto','Coimbra','Lisboa','Faro'],
      exp:'Braga → Porto → Coimbra → Lisboa → Faro.' }
];
if (typeof window !== 'undefined') window.EXERCISES_2_E_EXTRA2 = EXERCISES_2_E_EXTRA2;
