// EscolaPlay - Banco extra do 5.º ano - HGP (gerado, AE 2018)
const EXERCISES_5_H_EXTRA = [
    // ============================================================
    // GEOGRAFIA
    // ============================================================

    // ----- Localização (35) -----
    { id:'5he1', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🇵🇹 Em que península se localiza Portugal?',
      opts:['Itálica','Ibérica','Escandinava','Balcânica'], ans:1,
      exp:'Portugal fica na Península Ibérica, juntamente com Espanha.' },
    { id:'5he2', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🌍 Em que continente se localiza Portugal?',
      opts:['África','Ásia','Europa','América'], ans:2,
      exp:'Portugal localiza-se na Europa.' },
    { id:'5he3', s:'hgp', t:'Localização', type:'fill', diff:1,
      q:'🗺️ Portugal localiza-se no sudoeste da ___ .',
      ans:['Europa','europa'],
      exp:'Portugal fica no sudoeste da Europa.' },
    { id:'5he4', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🌊 Que oceano banha a costa portuguesa?',
      opts:['Pacífico','Atlântico','Índico','Ártico'], ans:1,
      exp:'O Oceano Atlântico banha a costa de Portugal.' },
    { id:'5he5', s:'hgp', t:'Localização', type:'tf', diff:1,
      q:'Portugal fica na Península Ibérica.',
      ans:true,
      exp:'Sim, Portugal fica na Península Ibérica.' },
    { id:'5he6', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🌐 Em que hemisfério está Portugal?',
      opts:['Sul','Norte','Oriental','Ártico'], ans:1,
      exp:'Portugal está no Hemisfério Norte.' },
    { id:'5he7', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🗺️ Portugal Continental tem aproximadamente que forma?',
      opts:['quadrada','retangular','triangular','circular'], ans:1,
      exp:'O território continental tem forma aproximadamente retangular.' },
    { id:'5he8', s:'hgp', t:'Localização', type:'fill', diff:1,
      q:'O território português é formado pelo Continente, pelos Açores e pela ___.',
      ans:['Madeira','madeira'],
      exp:'Portugal = Continente + Açores + Madeira.' },
    { id:'5he9', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🏝️ Os arquipélagos portugueses são:',
      opts:['Açores e Canárias','Madeira e Baleares','Açores e Madeira','Madeira e Canárias'], ans:2,
      exp:'Açores e Madeira são os dois arquipélagos portugueses.' },
    { id:'5he10', s:'hgp', t:'Localização', type:'tf', diff:1,
      q:'Portugal é uma ilha.',
      ans:false,
      exp:'Portugal Continental fica em península; só os arquipélagos são ilhas.' },
    { id:'5he11', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🌍 Portugal localiza-se em que parte da Europa?',
      opts:['Norte','Centro','Sudoeste','Leste'], ans:2,
      exp:'Portugal localiza-se no sudoeste da Europa.' },
    { id:'5he12', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🗺️ Para ler um mapa usamos a:',
      opts:['lupa','legenda e rosa-dos-ventos','régua','calculadora'], ans:1,
      exp:'A legenda e a rosa-dos-ventos ajudam a ler o mapa.' },
    { id:'5he13', s:'hgp', t:'Localização', type:'fill', diff:2,
      q:'O instrumento que aponta sempre para Norte chama-se ___.',
      ans:['bússola','bussola'],
      exp:'A bússola aponta para o Norte magnético.' },
    { id:'5he14', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🌐 Portugal Continental fica:',
      opts:['no centro da Europa','no extremo sudoeste da Europa','no leste da Europa','no norte da Europa'], ans:1,
      exp:'Portugal está no extremo sudoeste da Europa.' },
    { id:'5he15', s:'hgp', t:'Localização', type:'tf', diff:1,
      q:'A Península Ibérica é formada por Portugal e Espanha.',
      ans:true,
      exp:'A Península Ibérica é constituída por Portugal e Espanha.' },
    { id:'5he16', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🌍 Em que hemisfério se situa Portugal?',
      opts:['Hemisfério Sul','Hemisfério Leste','Hemisfério Norte','Hemisfério Oeste'], ans:2,
      exp:'Portugal situa-se no Hemisfério Norte, acima do Trópico de Câncer.' },
    { id:'5he17', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🗺️ A representação reduzida da Terra numa folha chama-se:',
      opts:['globo','mapa','planta','desenho'], ans:1,
      exp:'O mapa é a representação plana e reduzida da Terra.' },
    { id:'5he18', s:'hgp', t:'Localização', type:'fill', diff:2,
      q:'A representação esférica da Terra chama-se ___ .',
      ans:['globo','globo terrestre'],
      exp:'O globo terrestre é a representação esférica da Terra.' },
    { id:'5he19', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🇵🇹 A oeste de Portugal Continental está:',
      opts:['Espanha','o Mar Mediterrâneo','o Oceano Atlântico','França'], ans:2,
      exp:'A oeste fica o Oceano Atlântico.' },
    { id:'5he20', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🇵🇹 A leste de Portugal Continental fica:',
      opts:['o Atlântico','Espanha','o Mediterrâneo','França'], ans:1,
      exp:'A leste de Portugal está Espanha.' },
    { id:'5he21', s:'hgp', t:'Localização', type:'tf', diff:1,
      q:'A Madeira fica perto de Portugal Continental.',
      ans:false,
      exp:'A Madeira está no Atlântico, ao largo da costa africana, longe do Continente.' },
    { id:'5he22', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🌊 O conjunto Continente + Madeira + Açores chama-se:',
      opts:['Lusitânia','Hispania','Território Português','Ibéria'], ans:2,
      exp:'É o Território Português.' },
    { id:'5he23', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🗺️ As linhas imaginárias verticais no globo chamam-se:',
      opts:['paralelos','meridianos','equadores','trópicos'], ans:1,
      exp:'Os meridianos vão do Pólo Norte ao Pólo Sul.' },
    { id:'5he24', s:'hgp', t:'Localização', type:'fill', diff:2,
      q:'As linhas imaginárias horizontais do globo chamam-se ___.',
      ans:['paralelos'],
      exp:'Os paralelos são linhas imaginárias horizontais.' },
    { id:'5he25', s:'hgp', t:'Localização', type:'mc', diff:3,
      q:'🌐 O paralelo principal chama-se:',
      opts:['Trópico de Câncer','Equador','Trópico de Capricórnio','Meridiano de Greenwich'], ans:1,
      exp:'O Equador divide a Terra em Hemisfério Norte e Sul.' },
    { id:'5he26', s:'hgp', t:'Localização', type:'mc', diff:3,
      q:'🌐 O meridiano principal chama-se:',
      opts:['Equador','Greenwich','Capricórnio','Trópico Norte'], ans:1,
      exp:'O Meridiano de Greenwich é o meridiano principal (0º).' },
    { id:'5he27', s:'hgp', t:'Localização', type:'tf', diff:2,
      q:'A escala num mapa permite calcular distâncias reais.',
      ans:true,
      exp:'A escala mostra a relação entre o mapa e a realidade.' },
    { id:'5he28', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🗺️ Os símbolos usados no mapa são explicados na:',
      opts:['margem','escala','legenda','título'], ans:2,
      exp:'A legenda explica o significado dos símbolos.' },
    { id:'5he29', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🇵🇹 Portugal Continental e Espanha formam a Península:',
      opts:['Itálica','Ibérica','Anatólica','Arábica'], ans:1,
      exp:'A Península Ibérica é formada pelos dois países.' },
    { id:'5he30', s:'hgp', t:'Localização', type:'fill', diff:1,
      q:'O Oceano ___ banha a costa portuguesa.',
      ans:['Atlântico','atlântico','Atlantico'],
      exp:'O Oceano Atlântico banha Portugal.' },
    { id:'5he31', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🌍 Quem dividiu primeiro o globo em hemisférios?',
      opts:['os romanos','os gregos','os portugueses','os egípcios'], ans:1,
      exp:'Os gregos antigos criaram a divisão em hemisférios.' },
    { id:'5he32', s:'hgp', t:'Localização', type:'tf', diff:1,
      q:'O Atlântico fica a oeste de Portugal Continental.',
      ans:true,
      exp:'O Oceano Atlântico fica a oeste.' },
    { id:'5he33', s:'hgp', t:'Localização', type:'mc', diff:2,
      q:'🗺️ Numa rosa-dos-ventos, em cima fica:',
      opts:['Sul','Norte','Este','Oeste'], ans:1,
      exp:'Por convenção, o Norte fica em cima.' },
    { id:'5he34', s:'hgp', t:'Localização', type:'match', diff:2,
      q:'Associa cada elemento ao instrumento ou conceito:',
      pairs:[['🧭 bússola','aponta para Norte'],['🌍 globo','representação esférica'],['🗺️ mapa','representação plana'],['📏 escala','calcular distâncias']],
      exp:'Cada instrumento/elemento tem a sua função na orientação geográfica.' },
    { id:'5he35', s:'hgp', t:'Localização', type:'mc', diff:1,
      q:'🇵🇹 Portugal é um país da:',
      opts:['Ásia','Europa','África','Oceânia'], ans:1,
      exp:'Portugal é um país europeu.' },

    // ----- Fronteiras (30) -----
    { id:'5he36', s:'hgp', t:'Fronteiras', type:'mc', diff:1,
      q:'🇪🇸 Com que país Portugal Continental tem fronteira terrestre?',
      opts:['França','Espanha','Marrocos','Itália'], ans:1,
      exp:'Portugal só tem fronteira terrestre com Espanha.' },
    { id:'5he37', s:'hgp', t:'Fronteiras', type:'fill', diff:1,
      q:'A fronteira terrestre de Portugal é com ___.',
      ans:['Espanha','espanha'],
      exp:'A única fronteira terrestre é com Espanha.' },
    { id:'5he38', s:'hgp', t:'Fronteiras', type:'mc', diff:1,
      q:'🌊 A fronteira a sul e oeste de Portugal Continental é:',
      opts:['terrestre','marítima','fluvial','aérea'], ans:1,
      exp:'A oeste e sul, a fronteira é marítima (Oceano Atlântico).' },
    { id:'5he39', s:'hgp', t:'Fronteiras', type:'tf', diff:1,
      q:'Portugal faz fronteira com França.',
      ans:false,
      exp:'Portugal só faz fronteira terrestre com Espanha.' },
    { id:'5he40', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🇵🇹 A fronteira terrestre de Portugal fica a:',
      opts:['Norte e Oeste','Norte e Este','Sul e Este','Oeste e Sul'], ans:1,
      exp:'A fronteira com Espanha fica a Norte e a Este.' },
    { id:'5he41', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🌊 A fronteira marítima de Portugal Continental fica a:',
      opts:['Norte e Este','Oeste e Sul','Norte e Sul','Este e Sul'], ans:1,
      exp:'A fronteira marítima (Atlântico) fica a Oeste e Sul.' },
    { id:'5he42', s:'hgp', t:'Fronteiras', type:'tf', diff:1,
      q:'A fronteira a oeste de Portugal é o Oceano Atlântico.',
      ans:true,
      exp:'O Atlântico é a fronteira ocidental.' },
    { id:'5he43', s:'hgp', t:'Fronteiras', type:'fill', diff:2,
      q:'A fronteira marítima de Portugal é o Oceano ___ .',
      ans:['Atlântico','atlântico','Atlantico'],
      exp:'O Atlântico forma a fronteira marítima.' },
    { id:'5he44', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🇵🇹 Quantos países fazem fronteira terrestre com Portugal?',
      opts:['1','2','3','4'], ans:0,
      exp:'Apenas 1: Espanha.' },
    { id:'5he45', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🌊 A fronteira a sul de Portugal Continental é:',
      opts:['terrestre','marítima','fluvial','com Espanha'], ans:1,
      exp:'A sul fica o Oceano Atlântico (fronteira marítima).' },
    { id:'5he46', s:'hgp', t:'Fronteiras', type:'tf', diff:1,
      q:'Portugal tem fronteira com Marrocos.',
      ans:false,
      exp:'Marrocos fica em África, separado pelo Oceano Atlântico/Estreito de Gibraltar.' },
    { id:'5he47', s:'hgp', t:'Fronteiras', type:'mc', diff:3,
      q:'🌊 O rio que faz parte da fronteira sul com Espanha é:',
      opts:['Tejo','Douro','Guadiana','Mondego'], ans:2,
      exp:'O Guadiana faz parte da fronteira a sul/leste.' },
    { id:'5he48', s:'hgp', t:'Fronteiras', type:'mc', diff:3,
      q:'🌊 Que rio marca parte da fronteira norte com Espanha?',
      opts:['Tejo','Minho','Sado','Mondego'], ans:1,
      exp:'O rio Minho marca parte da fronteira norte.' },
    { id:'5he49', s:'hgp', t:'Fronteiras', type:'fill', diff:3,
      q:'O rio ___ marca a fronteira a norte com Espanha.',
      ans:['Minho','minho'],
      exp:'O rio Minho separa Portugal e Espanha a norte.' },
    { id:'5he50', s:'hgp', t:'Fronteiras', type:'mc', diff:1,
      q:'🇪🇸 Espanha fica a:',
      opts:['oeste de Portugal','este e norte de Portugal','sul de Portugal','não faz fronteira com Portugal'], ans:1,
      exp:'Espanha fica a leste e norte de Portugal Continental.' },
    { id:'5he51', s:'hgp', t:'Fronteiras', type:'tf', diff:2,
      q:'A fronteira terrestre com Espanha é a mais antiga da Europa.',
      ans:true,
      exp:'A fronteira luso-espanhola é considerada uma das mais antigas e estáveis da Europa.' },
    { id:'5he52', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🌊 Qual destes não é uma fronteira de Portugal Continental?',
      opts:['Espanha','Atlântico','França','linha costeira'], ans:2,
      exp:'França não faz fronteira com Portugal.' },
    { id:'5he53', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🇵🇹 A fronteira de Portugal Continental tem cerca de:',
      opts:['200 km','500 km','1200 km','3000 km'], ans:2,
      exp:'A fronteira terrestre com Espanha tem cerca de 1200 km.' },
    { id:'5he54', s:'hgp', t:'Fronteiras', type:'fill', diff:1,
      q:'A oeste de Portugal Continental fica o Oceano ___ .',
      ans:['Atlântico','atlântico','Atlantico'],
      exp:'O Atlântico está a oeste.' },
    { id:'5he55', s:'hgp', t:'Fronteiras', type:'mc', diff:1,
      q:'🇪🇸 A capital de Espanha é:',
      opts:['Barcelona','Madrid','Sevilha','Valência'], ans:1,
      exp:'Madrid é a capital de Espanha.' },
    { id:'5he56', s:'hgp', t:'Fronteiras', type:'tf', diff:1,
      q:'Portugal tem fronteira marítima com França.',
      ans:false,
      exp:'A França não faz fronteira com Portugal.' },
    { id:'5he57', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🗺️ Os limites de um país chamam-se:',
      opts:['margens','fronteiras','escalas','distritos'], ans:1,
      exp:'As fronteiras delimitam o território de um país.' },
    { id:'5he58', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🌊 Os arquipélagos da Madeira e Açores têm fronteiras:',
      opts:['só terrestres','só marítimas','marítimas e terrestres','não têm'], ans:1,
      exp:'Os arquipélagos têm apenas fronteiras marítimas.' },
    { id:'5he59', s:'hgp', t:'Fronteiras', type:'fill', diff:2,
      q:'A fronteira entre Portugal e Espanha chama-se ___ .',
      ans:['Raia','raia'],
      exp:'A fronteira luso-espanhola é tradicionalmente chamada "Raia".' },
    { id:'5he60', s:'hgp', t:'Fronteiras', type:'mc', diff:3,
      q:'🌊 O rio Douro também faz parte da fronteira com:',
      opts:['França','Espanha','Marrocos','Itália'], ans:1,
      exp:'O Douro é fronteira luso-espanhola em parte do norte.' },
    { id:'5he61', s:'hgp', t:'Fronteiras', type:'tf', diff:2,
      q:'O rio Guadiana é fronteira entre Portugal e Espanha.',
      ans:true,
      exp:'O Guadiana faz parte da fronteira no sul/leste.' },
    { id:'5he62', s:'hgp', t:'Fronteiras', type:'mc', diff:1,
      q:'🇵🇹 A norte de Portugal Continental fica:',
      opts:['o Atlântico','Espanha','França','Marrocos'], ans:1,
      exp:'A norte está Espanha (Galiza).' },
    { id:'5he63', s:'hgp', t:'Fronteiras', type:'mc', diff:2,
      q:'🌊 A linha que divide o mar territorial chama-se também:',
      opts:['raia','fronteira marítima','meridiano','paralelo'], ans:1,
      exp:'A fronteira marítima delimita o mar territorial.' },
    { id:'5he64', s:'hgp', t:'Fronteiras', type:'match', diff:2,
      q:'Associa cada lado de Portugal à fronteira:',
      pairs:[['Norte','Espanha'],['Este','Espanha'],['Oeste','Atlântico'],['Sul','Atlântico']],
      exp:'Norte e Este: Espanha; Oeste e Sul: Atlântico.' },
    { id:'5he65', s:'hgp', t:'Fronteiras', type:'mc', diff:1,
      q:'🇵🇹 Portugal partilha a Península Ibérica com:',
      opts:['França','Espanha','Itália','Marrocos'], ans:1,
      exp:'Portugal e Espanha formam a Península Ibérica.' },

    // ----- Continentes (30) -----
    { id:'5he66', s:'hgp', t:'Continentes', type:'mc', diff:1,
      q:'🌍 Quantos continentes existem?',
      opts:['4','5','6','7'], ans:2,
      exp:'Existem 6 continentes: Europa, Ásia, África, América, Oceânia e Antártida.' },
    { id:'5he67', s:'hgp', t:'Continentes', type:'fill', diff:1,
      q:'🌍 Portugal pertence ao continente ___ .',
      ans:['Europa','europa','europeu'],
      exp:'Portugal está na Europa.' },
    { id:'5he68', s:'hgp', t:'Continentes', type:'mc', diff:1,
      q:'🌍 O maior continente é:',
      opts:['Europa','Ásia','África','América'], ans:1,
      exp:'A Ásia é o maior continente do mundo.' },
    { id:'5he69', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'❄️ O continente mais frio é:',
      opts:['Europa','Antártida','América','Ásia'], ans:1,
      exp:'A Antártida é o continente mais frio (gelo permanente).' },
    { id:'5he70', s:'hgp', t:'Continentes', type:'tf', diff:1,
      q:'A África é um continente.',
      ans:true,
      exp:'África é um dos 6 continentes.' },
    { id:'5he71', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌏 O Brasil pertence a que continente?',
      opts:['Europa','América','África','Oceânia'], ans:1,
      exp:'O Brasil está na América (do Sul).' },
    { id:'5he72', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌏 A Austrália pertence a que continente?',
      opts:['Ásia','Oceânia','América','Antártida'], ans:1,
      exp:'A Austrália é o maior país da Oceânia.' },
    { id:'5he73', s:'hgp', t:'Continentes', type:'fill', diff:1,
      q:'🌍 Angola e Moçambique ficam no continente ___ .',
      ans:['Africano','africano','África','africa'],
      exp:'Angola e Moçambique ficam em África.' },
    { id:'5he74', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 A China fica no continente:',
      opts:['Europa','Ásia','África','América'], ans:1,
      exp:'A China é um país asiático.' },
    { id:'5he75', s:'hgp', t:'Continentes', type:'tf', diff:1,
      q:'A Europa é o maior continente do mundo.',
      ans:false,
      exp:'A Ásia é o maior; a Europa é o 2.º mais pequeno.' },
    { id:'5he76', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 O continente mais pequeno é:',
      opts:['Europa','Antártida','Oceânia','África'], ans:2,
      exp:'A Oceânia é o menor continente.' },
    { id:'5he77', s:'hgp', t:'Continentes', type:'match', diff:2,
      q:'Associa cada país ao seu continente:',
      pairs:[['Portugal','Europa'],['Brasil','América'],['Angola','África'],['China','Ásia']],
      exp:'Cada país pertence a um continente.' },
    { id:'5he78', s:'hgp', t:'Continentes', type:'mc', diff:1,
      q:'🌍 França fica em que continente?',
      opts:['Europa','Ásia','África','América'], ans:0,
      exp:'França é europeia.' },
    { id:'5he79', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 Os Estados Unidos da América ficam:',
      opts:['Europa','Ásia','América','Oceânia'], ans:2,
      exp:'EUA estão na América (do Norte).' },
    { id:'5he80', s:'hgp', t:'Continentes', type:'fill', diff:2,
      q:'🌍 O Egito fica no continente ___ .',
      ans:['Africano','africano','África','africa'],
      exp:'O Egito é um país africano.' },
    { id:'5he81', s:'hgp', t:'Continentes', type:'tf', diff:1,
      q:'A Antártida é habitada por muitas pessoas.',
      ans:false,
      exp:'A Antártida quase não tem habitantes (só cientistas em bases).' },
    { id:'5he82', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 O continente mais populoso é:',
      opts:['Europa','Ásia','África','América'], ans:1,
      exp:'A Ásia tem mais de metade da população mundial.' },
    { id:'5he83', s:'hgp', t:'Continentes', type:'mc', diff:1,
      q:'🌍 A América divide-se em:',
      opts:['América do Norte e do Sul','América Atlântica e Pacífica','América Branca e Negra','América Antiga e Nova'], ans:0,
      exp:'A América divide-se em América do Norte e América do Sul (com a América Central a ligá-las).' },
    { id:'5he84', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 Os Açores ficam ainda no continente:',
      opts:['Africano','Europeu','Americano','Asiático'], ans:1,
      exp:'Os Açores são europeus (Portugal).' },
    { id:'5he85', s:'hgp', t:'Continentes', type:'fill', diff:1,
      q:'🌍 Existem ___ continentes.',
      ans:['6','seis'],
      exp:'São 6 os continentes.' },
    { id:'5he86', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 Cabo Verde, antiga colónia portuguesa, fica em:',
      opts:['Europa','África','América','Ásia'], ans:1,
      exp:'Cabo Verde é um arquipélago em África.' },
    { id:'5he87', s:'hgp', t:'Continentes', type:'tf', diff:2,
      q:'A Europa e a Ásia formam um único bloco continental.',
      ans:true,
      exp:'Sim, Europa e Ásia estão ligadas (Eurásia).' },
    { id:'5he88', s:'hgp', t:'Continentes', type:'mc', diff:3,
      q:'🌍 Como se chama o conjunto Europa + Ásia?',
      opts:['Eurásia','Eurafrica','Asiopa','Euroamérica'], ans:0,
      exp:'Eurásia.' },
    { id:'5he89', s:'hgp', t:'Continentes', type:'mc', diff:1,
      q:'🌍 Timor-Leste fica em que continente?',
      opts:['Europa','Ásia','África','América'], ans:1,
      exp:'Timor fica na Ásia (Sudeste Asiático).' },
    { id:'5he90', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 Macau (antiga administração portuguesa) fica em:',
      opts:['Europa','Ásia','África','América'], ans:1,
      exp:'Macau fica na China (Ásia).' },
    { id:'5he91', s:'hgp', t:'Continentes', type:'fill', diff:2,
      q:'🌍 A Guiné-Bissau fica em ___ .',
      ans:['África','africa','Africa'],
      exp:'A Guiné-Bissau é um país africano.' },
    { id:'5he92', s:'hgp', t:'Continentes', type:'tf', diff:1,
      q:'A Antártida tem muito gelo.',
      ans:true,
      exp:'A Antártida está coberta de gelo quase todo o ano.' },
    { id:'5he93', s:'hgp', t:'Continentes', type:'mc', diff:2,
      q:'🌍 São Tomé e Príncipe fica em:',
      opts:['Europa','África','América','Ásia'], ans:1,
      exp:'São Tomé fica em África (no golfo da Guiné).' },
    { id:'5he94', s:'hgp', t:'Continentes', type:'order', diff:3,
      q:'Ordena os continentes por tamanho (maior → menor):',
      items:['Ásia','América','África','Europa'],
      exp:'Ásia > América > África > Europa. A América (Norte + Sul) é maior que África.' },
    { id:'5he95', s:'hgp', t:'Continentes', type:'mc', diff:1,
      q:'🌍 Em que continente está o deserto do Sara?',
      opts:['Ásia','África','América','Oceânia'], ans:1,
      exp:'O Sara é o maior deserto quente, em África.' },

    // ----- Oceanos (25) -----
    { id:'5he96', s:'hgp', t:'Oceanos', type:'mc', diff:1,
      q:'🌊 Quantos oceanos existem na Terra?',
      opts:['3','4','5','6'], ans:2,
      exp:'5 oceanos: Atlântico, Pacífico, Índico, Glacial Ártico e Glacial Antártico.' },
    { id:'5he97', s:'hgp', t:'Oceanos', type:'mc', diff:1,
      q:'🌊 Que oceano banha Portugal?',
      opts:['Pacífico','Atlântico','Índico','Ártico'], ans:1,
      exp:'O Atlântico banha Portugal.' },
    { id:'5he98', s:'hgp', t:'Oceanos', type:'fill', diff:1,
      q:'🌊 O maior oceano é o ___ .',
      ans:['Pacífico','pacífico','Pacifico'],
      exp:'O Pacífico é o maior oceano do mundo.' },
    { id:'5he99', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 Qual destes não é um oceano?',
      opts:['Pacífico','Atlântico','Mediterrâneo','Índico'], ans:2,
      exp:'O Mediterrâneo é um mar, não um oceano.' },
    { id:'5he100', s:'hgp', t:'Oceanos', type:'tf', diff:1,
      q:'O Atlântico fica entre a Europa/África e a América.',
      ans:true,
      exp:'O Atlântico separa esses continentes.' },
    { id:'5he101', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'❄️ O oceano mais frio é o:',
      opts:['Atlântico','Índico','Glacial Ártico','Pacífico'], ans:2,
      exp:'O Glacial Ártico fica no Pólo Norte.' },
    { id:'5he102', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 O Índico banha:',
      opts:['Europa','África e Ásia','América','Antártida'], ans:1,
      exp:'O Índico banha o leste de África e o sul da Ásia.' },
    { id:'5he103', s:'hgp', t:'Oceanos', type:'fill', diff:1,
      q:'🌊 O segundo maior oceano é o ___ .',
      ans:['Atlântico','atlântico','Atlantico'],
      exp:'O Atlântico é o segundo maior.' },
    { id:'5he104', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 O oceano que rodeia a Antártida chama-se:',
      opts:['Glacial Ártico','Glacial Antártico','Índico','Pacífico'], ans:1,
      exp:'O Glacial Antártico (ou Austral) rodeia a Antártida.' },
    { id:'5he105', s:'hgp', t:'Oceanos', type:'tf', diff:1,
      q:'A Madeira fica no Oceano Atlântico.',
      ans:true,
      exp:'A Madeira fica no Atlântico Norte.' },
    { id:'5he106', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 Os Açores ficam no Oceano:',
      opts:['Pacífico','Atlântico','Índico','Mediterrâneo'], ans:1,
      exp:'Os Açores ficam no meio do Atlântico Norte.' },
    { id:'5he107', s:'hgp', t:'Oceanos', type:'match', diff:2,
      q:'Associa cada oceano à sua localização:',
      pairs:[['Atlântico','entre Europa/África e América'],['Pacífico','entre Ásia e América'],['Índico','sul da Ásia'],['Glacial Ártico','Pólo Norte']],
      exp:'Cada oceano ocupa uma região diferente.' },
    { id:'5he108', s:'hgp', t:'Oceanos', type:'mc', diff:1,
      q:'🌊 Os portugueses, na época dos Descobrimentos, navegaram pelo:',
      opts:['Atlântico','Pacífico','Índico','todos'], ans:3,
      exp:'Os portugueses navegaram pelos vários oceanos.' },
    { id:'5he109', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 A maior parte do planeta é coberta por:',
      opts:['terra','água','floresta','deserto'], ans:1,
      exp:'Cerca de 71% da Terra é água (oceanos).' },
    { id:'5he110', s:'hgp', t:'Oceanos', type:'fill', diff:2,
      q:'🌊 A água do mar é ___ (sabor).',
      ans:['salgada','salgado'],
      exp:'A água do mar é salgada.' },
    { id:'5he111', s:'hgp', t:'Oceanos', type:'tf', diff:1,
      q:'O Pacífico é maior do que o Atlântico.',
      ans:true,
      exp:'O Pacífico é o maior oceano.' },
    { id:'5he112', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 O estreito que separa a Europa de África (entre Espanha e Marrocos) chama-se Estreito de:',
      opts:['Magalhães','Gibraltar','Bering','Bósforo'], ans:1,
      exp:'Estreito de Gibraltar — liga o Oceano Atlântico ao Mar Mediterrâneo e separa a Europa (Espanha) de África (Marrocos).' },
    { id:'5he113', s:'hgp', t:'Oceanos', type:'mc', diff:1,
      q:'🌊 O Cabo Verde fica no Oceano:',
      opts:['Pacífico','Atlântico','Índico','Mediterrâneo'], ans:1,
      exp:'Cabo Verde está no Atlântico.' },
    { id:'5he114', s:'hgp', t:'Oceanos', type:'tf', diff:2,
      q:'O Pacífico banha as costas asiáticas e americanas.',
      ans:true,
      exp:'O Pacífico fica entre Ásia e América.' },
    { id:'5he115', s:'hgp', t:'Oceanos', type:'mc', diff:3,
      q:'🌊 O ZEE (Zona Económica Exclusiva) de Portugal é uma das:',
      opts:['mais pequenas','mais ricas em ouro','maiores da Europa','mais geladas'], ans:2,
      exp:'Portugal tem uma das maiores ZEE da Europa, devido aos arquipélagos.' },
    { id:'5he116', s:'hgp', t:'Oceanos', type:'fill', diff:2,
      q:'🌊 O Brasil é banhado pelo oceano ___ .',
      ans:['Atlântico','atlântico','Atlantico'],
      exp:'O Brasil tem costa atlântica.' },
    { id:'5he117', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 Mar e oceano: qual é maior?',
      opts:['mar','oceano','iguais','depende'], ans:1,
      exp:'O oceano é muito maior do que o mar.' },
    { id:'5he118', s:'hgp', t:'Oceanos', type:'mc', diff:1,
      q:'🌊 Existem ___ oceanos.',
      opts:['3','4','5','6'], ans:2,
      exp:'5 oceanos no total.' },
    { id:'5he119', s:'hgp', t:'Oceanos', type:'order', diff:3,
      q:'Ordena os oceanos do maior para o menor:',
      items:['Pacífico','Atlântico','Índico','Glacial Ártico'],
      exp:'Dos quatro: Pacífico > Atlântico > Índico > Glacial Ártico.' },
    { id:'5he120', s:'hgp', t:'Oceanos', type:'mc', diff:2,
      q:'🌊 O Oceano Atlântico é importante para Portugal porque:',
      opts:['é frio','é grande','liga-nos a outros povos','é doce'], ans:2,
      exp:'O Atlântico permitiu o comércio e os Descobrimentos.' },

    // ----- Europa (25) -----
    { id:'5he121', s:'hgp', t:'Europa', type:'mc', diff:1,
      q:'🇪🇺 Portugal pertence à União Europeia (UE)?',
      opts:['Sim','Não','Só Madeira','Só os Açores'], ans:0,
      exp:'Portugal é membro da UE desde 1986.' },
    { id:'5he122', s:'hgp', t:'Europa', type:'fill', diff:2,
      q:'🇪🇺 Portugal entrou na CEE (atual UE) no ano de ___ .',
      ans:['1986'],
      exp:'Portugal aderiu à CEE em 1986.' },
    { id:'5he123', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇪🇺 Quantos países têm atualmente a União Europeia?',
      opts:['12','25','27','30'], ans:2,
      exp:'A UE tem 27 países (após a saída do Reino Unido).' },
    { id:'5he124', s:'hgp', t:'Europa', type:'mc', diff:1,
      q:'💶 A moeda usada em Portugal e na UE é:',
      opts:['escudo','euro','dólar','libra'], ans:1,
      exp:'O euro é a moeda da maior parte da UE.' },
    { id:'5he125', s:'hgp', t:'Europa', type:'tf', diff:1,
      q:'O euro é a moeda de Portugal.',
      ans:true,
      exp:'Portugal usa o euro desde 2002.' },
    { id:'5he126', s:'hgp', t:'Europa', type:'fill', diff:2,
      q:'💶 O euro entrou em circulação em Portugal em ___ .',
      ans:['2002'],
      exp:'O euro substituiu o escudo em 2002.' },
    { id:'5he127', s:'hgp', t:'Europa', type:'mc', diff:1,
      q:'🇪🇺 A bandeira da União Europeia tem:',
      opts:['12 estrelas amarelas em fundo azul','13 listas','5 estrelas','um sol'], ans:0,
      exp:'12 estrelas douradas em fundo azul.' },
    { id:'5he128', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇪🇺 Antes do euro, a moeda portuguesa era o:',
      opts:['real','escudo','peseta','franco'], ans:1,
      exp:'O escudo foi a moeda portuguesa antes do euro.' },
    { id:'5he129', s:'hgp', t:'Europa', type:'mc', diff:1,
      q:'🌍 A Europa é um:',
      opts:['país','continente','oceano','planeta'], ans:1,
      exp:'A Europa é um continente.' },
    { id:'5he130', s:'hgp', t:'Europa', type:'tf', diff:1,
      q:'A Europa fica a norte de África.',
      ans:true,
      exp:'A Europa está a norte de África.' },
    { id:'5he131', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🌍 A Europa é separada de África pelo:',
      opts:['Mar Báltico','Mar Mediterrâneo','Mar do Norte','Atlântico'], ans:1,
      exp:'O Mediterrâneo separa Europa de África.' },
    { id:'5he132', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇪🇺 Os países da UE podem circular livremente devido ao espaço:',
      opts:['Schengen','Atlântico','Europeu','Comum'], ans:0,
      exp:'O espaço Schengen permite a livre circulação.' },
    { id:'5he133', s:'hgp', t:'Europa', type:'fill', diff:2,
      q:'🇪🇺 A capital da União Europeia é ___ .',
      ans:['Bruxelas','bruxelas'],
      exp:'Bruxelas (Bélgica) é a sede principal da UE.' },
    { id:'5he134', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇪🇸 Que país europeu faz fronteira com Portugal?',
      opts:['França','Espanha','Itália','Alemanha'], ans:1,
      exp:'Apenas Espanha.' },
    { id:'5he135', s:'hgp', t:'Europa', type:'tf', diff:2,
      q:'A Europa é o maior continente.',
      ans:false,
      exp:'A Europa é dos mais pequenos; o maior é a Ásia.' },
    { id:'5he136', s:'hgp', t:'Europa', type:'match', diff:2,
      q:'Associa cada país europeu à sua capital:',
      pairs:[['Portugal','Lisboa'],['Espanha','Madrid'],['França','Paris'],['Itália','Roma']],
      exp:'Capitais europeias.' },
    { id:'5he137', s:'hgp', t:'Europa', type:'mc', diff:1,
      q:'🇫🇷 A capital de França é:',
      opts:['Madrid','Paris','Roma','Berlim'], ans:1,
      exp:'Paris é a capital francesa.' },
    { id:'5he138', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇮🇹 A capital de Itália é:',
      opts:['Madrid','Atenas','Roma','Lisboa'], ans:2,
      exp:'Roma é a capital de Itália.' },
    { id:'5he139', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇩🇪 A capital da Alemanha é:',
      opts:['Berlim','Munique','Hamburgo','Frankfurt'], ans:0,
      exp:'Berlim é a capital alemã.' },
    { id:'5he140', s:'hgp', t:'Europa', type:'fill', diff:1,
      q:'🇪🇺 Portugal usa a moeda ___ .',
      ans:['euro'],
      exp:'A moeda é o euro.' },
    { id:'5he141', s:'hgp', t:'Europa', type:'tf', diff:2,
      q:'A Europa tem mais países que continentes.',
      ans:true,
      exp:'Tem mais de 40 países, contra 6 continentes.' },
    { id:'5he142', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'🇪🇺 Antes da UE existia a:',
      opts:['CEE','ONU','NATO','UNESCO'], ans:0,
      exp:'A CEE (Comunidade Económica Europeia) precedeu a UE.' },
    { id:'5he143', s:'hgp', t:'Europa', type:'mc', diff:3,
      q:'🇪🇺 Em que ano é que Portugal entrou oficialmente na CEE?',
      opts:['1974','1986','1992','2002'], ans:1,
      exp:'O Tratado de Adesão foi assinado a 12 de junho de 1985, mas Portugal só passou a ser membro efetivo a 1 de janeiro de 1986.' },
    { id:'5he144', s:'hgp', t:'Europa', type:'mc', diff:1,
      q:'🌍 A Europa é um continente:',
      opts:['muito grande','médio','pequeno em área, mas com muitos países','vazio'], ans:2,
      exp:'A Europa é pequena em área, mas tem muitos países.' },
    { id:'5he145', s:'hgp', t:'Europa', type:'mc', diff:2,
      q:'💶 As notas e moedas de euro foram introduzidas em:',
      opts:['1986','1992','1999','2002'], ans:3,
      exp:'Notas e moedas de euro circulam desde 1 de janeiro de 2002.' },

    // ----- Pontos cardeais (25) -----
    { id:'5he146', s:'hgp', t:'Pontos cardeais', type:'mc', diff:1,
      q:'🧭 Quantos pontos cardeais existem?',
      opts:['2','3','4','6'], ans:2,
      exp:'4 pontos cardeais: Norte, Sul, Este e Oeste.' },
    { id:'5he147', s:'hgp', t:'Pontos cardeais', type:'fill', diff:1,
      q:'🧭 Os pontos cardeais são: Norte, Sul, Este e ___ .',
      ans:['Oeste','oeste','O'],
      exp:'Norte (N), Sul (S), Este (E), Oeste (O).' },
    { id:'5he148', s:'hgp', t:'Pontos cardeais', type:'mc', diff:1,
      q:'☀️ O Sol nasce a:',
      opts:['Norte','Sul','Este','Oeste'], ans:2,
      exp:'O Sol nasce a Este (Oriente).' },
    { id:'5he149', s:'hgp', t:'Pontos cardeais', type:'mc', diff:1,
      q:'🌅 O Sol põe-se a:',
      opts:['Norte','Sul','Este','Oeste'], ans:3,
      exp:'O Sol põe-se a Oeste (Ocidente).' },
    { id:'5he150', s:'hgp', t:'Pontos cardeais', type:'tf', diff:1,
      q:'A bússola aponta sempre para Norte.',
      ans:true,
      exp:'A bússola aponta para o Norte magnético.' },
    { id:'5he151', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Os pontos colaterais são:',
      opts:['NE, NO, SE, SO','NN, SS, EE, OO','N, S, E, O','não existem'], ans:0,
      exp:'NE (nordeste), NO (noroeste), SE (sudeste), SO (sudoeste).' },
    { id:'5he152', s:'hgp', t:'Pontos cardeais', type:'fill', diff:2,
      q:'🧭 Entre Norte e Este fica o ponto colateral ___ .',
      ans:['Nordeste','nordeste','NE'],
      exp:'NE = Nordeste.' },
    { id:'5he153', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Entre Sul e Oeste fica:',
      opts:['NE','NO','SE','SO'], ans:3,
      exp:'SO = Sudoeste.' },
    { id:'5he154', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Entre Sul e Este fica:',
      opts:['NE','NO','SE','SO'], ans:2,
      exp:'SE = Sudeste.' },
    { id:'5he155', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Entre Norte e Oeste fica:',
      opts:['NE','NO','SE','SO'], ans:1,
      exp:'NO = Noroeste.' },
    { id:'5he156', s:'hgp', t:'Pontos cardeais', type:'tf', diff:1,
      q:'O Sol nasce a Oeste.',
      ans:false,
      exp:'O Sol nasce a Este e põe-se a Oeste.' },
    { id:'5he157', s:'hgp', t:'Pontos cardeais', type:'fill', diff:1,
      q:'🧭 O instrumento que indica o Norte chama-se ___ .',
      ans:['bússola','bussola'],
      exp:'A bússola.' },
    { id:'5he158', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🌟 De noite, podemos orientar-nos pela:',
      opts:['Lua nova','Estrela Polar','Via Láctea','Sol'], ans:1,
      exp:'A Estrela Polar indica o Norte.' },
    { id:'5he159', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'☀️ A meio-dia, em Portugal, a sombra aponta para:',
      opts:['Norte','Sul','Este','Oeste'], ans:0,
      exp:'No Hemisfério Norte, ao meio-dia, a sombra aponta para Norte.' },
    { id:'5he160', s:'hgp', t:'Pontos cardeais', type:'mc', diff:1,
      q:'🧭 Norte abrevia-se por:',
      opts:['N','No','Nor','Nt'], ans:0,
      exp:'N = Norte.' },
    { id:'5he161', s:'hgp', t:'Pontos cardeais', type:'mc', diff:1,
      q:'🧭 Oeste também se chama:',
      opts:['Oriente','Setentrião','Ocidente','Meridiano'], ans:2,
      exp:'Oeste = Ocidente (onde o Sol se põe).' },
    { id:'5he162', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Este também se chama:',
      opts:['Ocidente','Oriente','Sul','Norte'], ans:1,
      exp:'Este = Oriente (onde o Sol nasce).' },
    { id:'5he163', s:'hgp', t:'Pontos cardeais', type:'fill', diff:2,
      q:'🧭 O ponto cardeal oposto a Norte é o ___ .',
      ans:['Sul','sul','S'],
      exp:'Norte e Sul são opostos.' },
    { id:'5he164', s:'hgp', t:'Pontos cardeais', type:'tf', diff:1,
      q:'Norte e Sul são opostos.',
      ans:true,
      exp:'Sim, e Este e Oeste também.' },
    { id:'5he165', s:'hgp', t:'Pontos cardeais', type:'match', diff:2,
      q:'Associa cada ponto à sua abreviatura:',
      pairs:[['Norte','N'],['Sul','S'],['Este','E'],['Oeste','O']],
      exp:'Abreviaturas dos 4 pontos cardeais.' },
    { id:'5he166', s:'hgp', t:'Pontos cardeais', type:'order', diff:2,
      q:'Ordena os pontos cardeais (sentido dos ponteiros do relógio, começando no Norte):',
      items:['Norte','Este','Sul','Oeste'],
      exp:'N → E → S → O (sentido horário).' },
    { id:'5he167', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Olhando para Norte, à direita fica:',
      opts:['Sul','Este','Oeste','Norte'], ans:1,
      exp:'À direita está Este.' },
    { id:'5he168', s:'hgp', t:'Pontos cardeais', type:'mc', diff:2,
      q:'🧭 Olhando para Norte, atrás fica:',
      opts:['Norte','Sul','Este','Oeste'], ans:1,
      exp:'Atrás de Norte fica Sul.' },
    { id:'5he169', s:'hgp', t:'Pontos cardeais', type:'tf', diff:2,
      q:'A rosa-dos-ventos pode ter 4, 8 ou 16 pontos.',
      ans:true,
      exp:'Pode ter 4 (cardeais), 8 (com colaterais) ou 16 (com intermédios).' },
    { id:'5he170', s:'hgp', t:'Pontos cardeais', type:'mc', diff:1,
      q:'🌍 Portugal Continental fica no extremo:',
      opts:['nordeste da Europa','sudoeste da Europa','sul da África','este da Ásia'], ans:1,
      exp:'Portugal está no sudoeste da Europa.' },

    // ----- Distritos (30) -----
    { id:'5he171', s:'hgp', t:'Distritos', type:'mc', diff:1,
      q:'🇵🇹 Quantos distritos tem Portugal Continental?',
      opts:['10','15','18','20'], ans:2,
      exp:'18 distritos no Continente.' },
    { id:'5he172', s:'hgp', t:'Distritos', type:'fill', diff:1,
      q:'🇵🇹 Portugal Continental tem ___ distritos.',
      ans:['18','dezoito'],
      exp:'18 distritos.' },
    { id:'5he173', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🏝️ Os Açores e a Madeira são:',
      opts:['distritos','regiões autónomas','países','colónias'], ans:1,
      exp:'São Regiões Autónomas (RA).' },
    { id:'5he174', s:'hgp', t:'Distritos', type:'tf', diff:1,
      q:'Lisboa é um distrito.',
      ans:true,
      exp:'Lisboa é a capital e também um distrito.' },
    { id:'5he175', s:'hgp', t:'Distritos', type:'mc', diff:1,
      q:'🇵🇹 Qual destes não é um distrito?',
      opts:['Porto','Faro','Évora','Funchal'], ans:3,
      exp:'Funchal é cidade da Madeira (RA), não distrito.' },
    { id:'5he176', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 O distrito mais a sul de Portugal Continental é:',
      opts:['Beja','Évora','Faro','Setúbal'], ans:2,
      exp:'Faro (Algarve) é o mais a sul.' },
    { id:'5he177', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 O distrito mais a norte é:',
      opts:['Porto','Braga','Viana do Castelo','Bragança'], ans:2,
      exp:'Viana do Castelo é o distrito mais a norte.' },
    { id:'5he178', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 O distrito mais a este é:',
      opts:['Bragança','Guarda','Portalegre','Beja'], ans:0,
      exp:'Bragança é o mais a nordeste/este.' },
    { id:'5he179', s:'hgp', t:'Distritos', type:'fill', diff:2,
      q:'🇵🇹 O distrito do Algarve chama-se ___ .',
      ans:['Faro','faro'],
      exp:'O Algarve corresponde ao distrito de Faro.' },
    { id:'5he180', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Em que distrito fica Coimbra?',
      opts:['Lisboa','Coimbra','Aveiro','Leiria'], ans:1,
      exp:'Coimbra é cidade e distrito.' },
    { id:'5he181', s:'hgp', t:'Distritos', type:'tf', diff:1,
      q:'Os Açores formam uma Região Autónoma.',
      ans:true,
      exp:'Açores e Madeira são RA.' },
    { id:'5he182', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Quantas Regiões Autónomas tem Portugal?',
      opts:['1','2','3','4'], ans:1,
      exp:'2 RA: Açores e Madeira.' },
    { id:'5he183', s:'hgp', t:'Distritos', type:'fill', diff:2,
      q:'🇵🇹 Portugal tem 18 distritos e ___ regiões autónomas.',
      ans:['2','duas'],
      exp:'2 RA: Açores e Madeira.' },
    { id:'5he184', s:'hgp', t:'Distritos', type:'mc', diff:1,
      q:'🇵🇹 O distrito do Porto fica em que região?',
      opts:['Norte','Centro','Sul','Algarve'], ans:0,
      exp:'O Porto fica no Norte.' },
    { id:'5he185', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Em que distrito fica a cidade de Évora?',
      opts:['Beja','Évora','Portalegre','Setúbal'], ans:1,
      exp:'Évora é a capital de distrito do Alentejo Central.' },
    { id:'5he186', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Distrito do norte que faz fronteira com o Atlântico:',
      opts:['Bragança','Vila Real','Viana do Castelo','Guarda'], ans:2,
      exp:'Viana do Castelo tem costa atlântica.' },
    { id:'5he187', s:'hgp', t:'Distritos', type:'tf', diff:2,
      q:'A Madeira pertence ao distrito de Lisboa.',
      ans:false,
      exp:'A Madeira é uma Região Autónoma, não pertence a nenhum distrito.' },
    { id:'5he188', s:'hgp', t:'Distritos', type:'mc', diff:3,
      q:'🇵🇹 Quantos distritos têm sede no interior do país?',
      opts:['todos','vários','nenhum','um'], ans:1,
      exp:'Vários distritos do interior: Bragança, Vila Real, Guarda, Portalegre, etc.' },
    { id:'5he189', s:'hgp', t:'Distritos', type:'match', diff:2,
      q:'Associa cada distrito à sua região tradicional:',
      pairs:[['Faro','Algarve'],['Porto','Norte'],['Évora','Alentejo'],['Coimbra','Centro']],
      exp:'Associação distrito-região.' },
    { id:'5he190', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Distrito a sul do Tejo:',
      opts:['Coimbra','Setúbal','Porto','Aveiro'], ans:1,
      exp:'Setúbal fica a sul do Tejo.' },
    { id:'5he191', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Distrito conhecido pelas serras e pelo vinho do Porto:',
      opts:['Vila Real','Faro','Setúbal','Beja'], ans:0,
      exp:'Vila Real (região demarcada do Douro).' },
    { id:'5he192', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 O distrito de Aveiro é conhecido pela:',
      opts:['serra da Estrela','ria','planície alentejana','vinho da Madeira'], ans:1,
      exp:'A Ria de Aveiro é famosa.' },
    { id:'5he193', s:'hgp', t:'Distritos', type:'fill', diff:2,
      q:'🇵🇹 O distrito mais a sul é ___ .',
      ans:['Faro','faro'],
      exp:'Faro (Algarve).' },
    { id:'5he194', s:'hgp', t:'Distritos', type:'mc', diff:1,
      q:'🇵🇹 Qual destes é distrito do Centro?',
      opts:['Bragança','Coimbra','Faro','Setúbal'], ans:1,
      exp:'Coimbra é distrito do Centro.' },
    { id:'5he195', s:'hgp', t:'Distritos', type:'tf', diff:2,
      q:'Os distritos têm uma cidade-sede com o mesmo nome.',
      ans:true,
      exp:'Cada distrito tem nome igual à sua cidade-sede.' },
    { id:'5he196', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Distrito que faz fronteira com Espanha a nordeste:',
      opts:['Bragança','Setúbal','Faro','Lisboa'], ans:0,
      exp:'Bragança (Trás-os-Montes).' },
    { id:'5he197', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Em qual destes distritos fica Sintra?',
      opts:['Lisboa','Setúbal','Santarém','Leiria'], ans:0,
      exp:'Sintra pertence ao distrito de Lisboa.' },
    { id:'5he198', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 A planície alentejana está nos distritos de:',
      opts:['Évora, Beja, Portalegre','Porto, Braga, Aveiro','Faro, Lisboa, Setúbal','Coimbra, Leiria, Aveiro'], ans:0,
      exp:'O Alentejo abrange Évora, Beja e Portalegre.' },
    { id:'5he199', s:'hgp', t:'Distritos', type:'mc', diff:1,
      q:'🇵🇹 A capital de distrito mais populosa é:',
      opts:['Porto','Lisboa','Coimbra','Faro'], ans:1,
      exp:'Lisboa, capital de Portugal.' },
    { id:'5he200', s:'hgp', t:'Distritos', type:'mc', diff:2,
      q:'🇵🇹 Os distritos servem para:',
      opts:['nada','organização administrativa','dividir famílias','fazer feriados'], ans:1,
      exp:'Os distritos são unidades de organização administrativa.' },
];

if (typeof window !== 'undefined') window.EXERCISES_5_H_EXTRA = EXERCISES_5_H_EXTRA;
