// EscolaPlay - Top-up dificuldade 3 do 2.º ano - Português (gerado, alinhado com Supermiúdos)
// 5 exercícios diff:3 para cada um dos 11 tópicos sem dificuldade alta.
const EXERCISES_2_P_EXTRA3 = [
  // Vogais e consoantes
  { id:'2pe3_001', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:3,
    q:'🔤 Quantas vogais diferentes tem a palavra "saudade"?',
    opts:['2','3','4'], ans:1,
    exp:'A palavra "saudade" tem as vogais a, u, e. São 3 vogais diferentes.' },
  { id:'2pe3_002', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:3,
    q:'A letra "y" é uma vogal em português?',
    ans:false,
    exp:'Em português, o "y" não é uma das 5 vogais (a, e, i, o, u). É uma letra estrangeira.' },
  { id:'2pe3_003', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:3,
    q:'Qual destas palavras só tem consoantes diferentes?',
    opts:['mamã','papá','livro'], ans:2,
    exp:'Em "livro" as consoantes são l, v, r — todas diferentes. Em "mamã" e "papá" repetem-se.' },
  { id:'2pe3_004', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:3,
    q:'Escreve quantas consoantes tem a palavra "escola":',
    ans:['3','três'],
    exp:'Em "escola" as consoantes são s, c, l. São 3 consoantes.' },
  { id:'2pe3_005', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:3,
    q:'Qual palavra tem mais vogais do que consoantes?',
    opts:['gato','aula','bola'], ans:1,
    exp:'"aula" tem 3 vogais (a, u, a) e só 1 consoante (l).' },

  // Sílabas
  { id:'2pe3_006', s:'portugues', t:'Sílabas', type:'mc', diff:3,
    q:'🧩 Quantas sílabas tem a palavra "saudade"?',
    opts:['2','3','4'], ans:1,
    exp:'sa-u-da-de tem 4 sílabas? Não! Lê-se "sau-da-de" = 3 sílabas.' },
  { id:'2pe3_007', s:'portugues', t:'Sílabas', type:'fill', diff:3,
    q:'Divide em sílabas: "computador" (usa hífenes)',
    ans:['com-pu-ta-dor'],
    exp:'A palavra "computador" divide-se em com-pu-ta-dor. Tem 4 sílabas.' },
  { id:'2pe3_008', s:'portugues', t:'Sílabas', type:'tf', diff:3,
    q:'A palavra "pão" tem 2 sílabas.',
    ans:false,
    exp:'"pão" tem só 1 sílaba. O "ão" é um ditongo, lê-se de uma só vez.' },
  { id:'2pe3_009', s:'portugues', t:'Sílabas', type:'mc', diff:3,
    q:'Qual destas palavras tem 4 sílabas?',
    opts:['borboleta','janela','sapato'], ans:0,
    exp:'bor-bo-le-ta tem 4 sílabas. "janela" tem 3 e "sapato" tem 3.' },
  { id:'2pe3_010', s:'portugues', t:'Sílabas', type:'mc', diff:3,
    q:'Quantas sílabas tem "guarda-chuva"?',
    opts:['3','4','5'], ans:1,
    exp:'guar-da-chu-va = 4 sílabas. É uma palavra composta.' },

  // Ditongos
  { id:'2pe3_011', s:'portugues', t:'Ditongos', type:'mc', diff:3,
    q:'🎵 Qual destas palavras tem um ditongo nasal?',
    opts:['mão','casa','pera'], ans:0,
    exp:'"mão" tem o ditongo nasal "ão". Os ditongos nasais soam pelo nariz.' },
  { id:'2pe3_012', s:'portugues', t:'Ditongos', type:'tf', diff:3,
    q:'A palavra "pai" tem um ditongo.',
    ans:true,
    exp:'"pai" tem o ditongo "ai" — duas vogais juntas na mesma sílaba.' },
  { id:'2pe3_013', s:'portugues', t:'Ditongos', type:'mc', diff:3,
    q:'Quantos ditongos tem a palavra "papagaio"?',
    opts:['1','2','3'], ans:0,
    exp:'"papagaio" tem 1 ditongo: "aio". A palavra divide-se pa-pa-gai-o.' },
  { id:'2pe3_014', s:'portugues', t:'Ditongos', type:'fill', diff:3,
    q:'Escreve uma palavra com o ditongo "ei":',
    ans:['rei','peixe','leite','meio','cheio','feira'],
    exp:'Palavras como "rei", "peixe" ou "leite" têm o ditongo "ei".' },
  { id:'2pe3_015', s:'portugues', t:'Ditongos', type:'mc', diff:3,
    q:'Qual NÃO tem ditongo?',
    opts:['saúde','mãe','herói'], ans:0,
    exp:'Em "saúde" o "aú" lê-se em sílabas separadas: sa-ú-de. Não é ditongo.' },

  // Sinónimos
  { id:'2pe3_016', s:'portugues', t:'Sinónimos', type:'mc', diff:3,
    q:'💬 Qual é o sinónimo de "veloz"?',
    opts:['lento','rápido','grande'], ans:1,
    exp:'"Veloz" e "rápido" querem dizer a mesma coisa: que se move depressa.' },
  { id:'2pe3_017', s:'portugues', t:'Sinónimos', type:'mc', diff:3,
    q:'Qual palavra tem o mesmo significado de "contente"?',
    opts:['triste','feliz','cansado'], ans:1,
    exp:'"Contente" e "feliz" são sinónimos. Quem está contente está feliz.' },
  { id:'2pe3_018', s:'portugues', t:'Sinónimos', type:'fill', diff:3,
    q:'Escreve um sinónimo de "bonito":',
    ans:['lindo','belo','formoso','giro'],
    exp:'"Lindo", "belo" ou "giro" são sinónimos de "bonito".' },
  { id:'2pe3_019', s:'portugues', t:'Sinónimos', type:'tf', diff:3,
    q:'"Casa" e "lar" são sinónimos.',
    ans:true,
    exp:'Sim! "Casa" e "lar" referem-se ao sítio onde vivemos com a família.' },
  { id:'2pe3_020', s:'portugues', t:'Sinónimos', type:'mc', diff:3,
    q:'Qual é o sinónimo de "começar"?',
    opts:['acabar','iniciar','parar'], ans:1,
    exp:'"Começar" e "iniciar" significam o mesmo: dar início a algo.' },

  // Antónimos
  { id:'2pe3_021', s:'portugues', t:'Antónimos', type:'mc', diff:3,
    q:'↔️ Qual é o antónimo de "claro"?',
    opts:['brilhante','escuro','limpo'], ans:1,
    exp:'O contrário de "claro" é "escuro". São palavras com sentidos opostos.' },
  { id:'2pe3_022', s:'portugues', t:'Antónimos', type:'fill', diff:3,
    q:'Escreve o antónimo de "cheio":',
    ans:['vazio'],
    exp:'O contrário de "cheio" é "vazio". Um copo cheio passa a vazio quando bebes a água.' },
  { id:'2pe3_023', s:'portugues', t:'Antónimos', type:'mc', diff:3,
    q:'Qual é o antónimo de "subir"?',
    opts:['saltar','descer','correr'], ans:1,
    exp:'"Subir" e "descer" são contrários. Sobes as escadas e depois desces.' },
  { id:'2pe3_024', s:'portugues', t:'Antónimos', type:'tf', diff:3,
    q:'"Quente" e "frio" são antónimos.',
    ans:true,
    exp:'Sim! "Quente" e "frio" têm sentidos opostos — são antónimos.' },
  { id:'2pe3_025', s:'portugues', t:'Antónimos', type:'mc', diff:3,
    q:'Qual destes pares NÃO são antónimos?',
    opts:['alto/baixo','forte/fraco','grande/enorme'], ans:2,
    exp:'"Grande" e "enorme" são sinónimos, não antónimos. Os outros pares são contrários.' },

  // Família de palavras
  { id:'2pe3_026', s:'portugues', t:'Família de palavras', type:'mc', diff:3,
    q:'🌳 Qual NÃO pertence à família de "pão"?',
    opts:['padaria','padeiro','panela'], ans:2,
    exp:'"Panela" não vem de "pão". "Padaria" e "padeiro" sim.' },
  { id:'2pe3_027', s:'portugues', t:'Família de palavras', type:'fill', diff:3,
    q:'Escreve uma palavra da família de "flor":',
    ans:['florista','floresta','floricultor','florir','florido'],
    exp:'"Florista", "floresta" ou "florido" pertencem à família de "flor".' },
  { id:'2pe3_028', s:'portugues', t:'Família de palavras', type:'mc', diff:3,
    q:'Qual palavra é da família de "livro"?',
    opts:['livre','livraria','levar'], ans:1,
    exp:'"Livraria" é onde se vendem livros. "Livre" e "levar" são parecidas mas não da mesma família.' },
  { id:'2pe3_029', s:'portugues', t:'Família de palavras', type:'tf', diff:3,
    q:'"Sapato" e "sapateiro" são da mesma família de palavras.',
    ans:true,
    exp:'Sim! O "sapateiro" é quem faz ou arranja sapatos. Vêm da mesma raiz.' },
  { id:'2pe3_030', s:'portugues', t:'Família de palavras', type:'mc', diff:3,
    q:'Qual NÃO é da família de "terra"?',
    opts:['terreno','terraço','torre'], ans:2,
    exp:'"Torre" não vem de "terra". "Terreno" e "terraço" sim.' },

  // Singular e plural
  { id:'2pe3_031', s:'portugues', t:'Singular e plural', type:'fill', diff:3,
    q:'Qual é o plural de "limão"?',
    ans:['limões'],
    exp:'O plural de "limão" é "limões". As palavras em "ão" mudam para "ões".' },
  { id:'2pe3_032', s:'portugues', t:'Singular e plural', type:'mc', diff:3,
    q:'Qual é o plural de "mãe"?',
    opts:['mães','mãos','mães'], ans:0,
    exp:'O plural de "mãe" é "mães". É uma exceção: termina em "ães".' },
  { id:'2pe3_033', s:'portugues', t:'Singular e plural', type:'mc', diff:3,
    q:'Qual é o plural de "pão"?',
    opts:['pãos','pães','pões'], ans:1,
    exp:'O plural de "pão" é "pães". Outra exceção das palavras em "ão".' },
  { id:'2pe3_034', s:'portugues', t:'Singular e plural', type:'tf', diff:3,
    q:'O plural de "papel" é "papels".',
    ans:false,
    exp:'O plural de "papel" é "papéis". Palavras em "el" trocam para "éis".' },
  { id:'2pe3_035', s:'portugues', t:'Singular e plural', type:'fill', diff:3,
    q:'Escreve o plural de "animal":',
    ans:['animais'],
    exp:'O plural de "animal" é "animais". Palavras em "al" mudam para "ais".' },

  // Verbos no presente
  { id:'2pe3_036', s:'portugues', t:'Verbos no presente', type:'mc', diff:3,
    q:'⏰ "Nós ___ na escola." Que verbo está no presente?',
    opts:['estávamos','estamos','estaremos'], ans:1,
    exp:'"Estamos" é o presente do verbo estar. "Estávamos" é passado e "estaremos" é futuro.' },
  { id:'2pe3_037', s:'portugues', t:'Verbos no presente', type:'fill', diff:3,
    q:'Completa: "Eu ___ todos os dias." (verbo estudar)',
    ans:['estudo'],
    exp:'O verbo "estudar" no presente, com "eu", fica "estudo".' },
  { id:'2pe3_038', s:'portugues', t:'Verbos no presente', type:'tf', diff:3,
    q:'A frase "A Maria come uma maçã" está no presente.',
    ans:true,
    exp:'Sim! "Come" é o presente do verbo comer. A ação acontece agora.' },
  { id:'2pe3_039', s:'portugues', t:'Verbos no presente', type:'mc', diff:3,
    q:'Qual destas frases NÃO está no presente?',
    opts:['Tu lês um livro.','Eles brincaram no jardim.','Ele dorme cedo.'], ans:1,
    exp:'"Brincaram" é passado. As outras duas frases estão no presente.' },
  { id:'2pe3_040', s:'portugues', t:'Verbos no presente', type:'mc', diff:3,
    q:'Qual é o presente do verbo "ser" para "vós"?',
    opts:['sois','sereis','éreis'], ans:0,
    exp:'"Vós sois" é o presente. "Sereis" é futuro e "éreis" é passado.' },

  // Verbos no passado e futuro
  { id:'2pe3_041', s:'portugues', t:'Verbos no passado e futuro', type:'mc', diff:3,
    q:'📅 "Amanhã eu ___ ao parque." Qual verbo no futuro?',
    opts:['fui','vou','irei'], ans:2,
    exp:'"Irei" é o futuro do verbo ir. "Vou" é presente e "fui" é passado.' },
  { id:'2pe3_042', s:'portugues', t:'Verbos no passado e futuro', type:'fill', diff:3,
    q:'Passa para o passado: "Ele come pão." → "Ele ___ pão."',
    ans:['comeu'],
    exp:'O passado do verbo "comer" para "ele" é "comeu".' },
  { id:'2pe3_043', s:'portugues', t:'Verbos no passado e futuro', type:'tf', diff:3,
    q:'A frase "Ontem brinquei na rua" está no passado.',
    ans:true,
    exp:'Sim! "Ontem" e "brinquei" mostram que a ação já aconteceu.' },
  { id:'2pe3_044', s:'portugues', t:'Verbos no passado e futuro', type:'mc', diff:3,
    q:'Qual frase está no futuro?',
    opts:['A mãe cozinhou bolo.','A mãe vai cozinhar bolo.','A mãe cozinha bolo.'], ans:1,
    exp:'"Vai cozinhar" é uma forma de futuro. As outras são passado e presente.' },
  { id:'2pe3_045', s:'portugues', t:'Verbos no passado e futuro', type:'mc', diff:3,
    q:'Qual é o passado do verbo "fazer" (eu)?',
    opts:['farei','faço','fiz'], ans:2,
    exp:'"Eu fiz" é o passado. "Faço" é presente e "farei" é futuro.' },

  // Tipos de frase
  { id:'2pe3_046', s:'portugues', t:'Tipos de frase', type:'mc', diff:3,
    q:'❓ Que tipo é a frase "Que dia tão bonito!"?',
    opts:['interrogativa','exclamativa','declarativa'], ans:1,
    exp:'É exclamativa porque mostra emoção e termina com "!".' },
  { id:'2pe3_047', s:'portugues', t:'Tipos de frase', type:'tf', diff:3,
    q:'A frase "Fecha a porta." é uma frase imperativa (de ordem).',
    ans:true,
    exp:'Sim! As frases imperativas dão uma ordem ou um pedido.' },
  { id:'2pe3_048', s:'portugues', t:'Tipos de frase', type:'mc', diff:3,
    q:'Qual destas é uma frase interrogativa?',
    opts:['O cão é bonito.','Como te chamas?','Que pena!'], ans:1,
    exp:'A frase interrogativa faz uma pergunta e termina com "?".' },
  { id:'2pe3_049', s:'portugues', t:'Tipos de frase', type:'fill', diff:3,
    q:'Transforma em pergunta: "O Pedro tem um gato." (escreve a frase)',
    ans:['O Pedro tem um gato?','o pedro tem um gato?'],
    exp:'Para fazer pergunta, troca o ponto final por ponto de interrogação.' },
  { id:'2pe3_050', s:'portugues', t:'Tipos de frase', type:'mc', diff:3,
    q:'Qual é uma frase declarativa?',
    opts:['Adoro chocolate!','Tens fome?','O sol está a brilhar.'], ans:2,
    exp:'A declarativa diz/conta algo e termina com ponto final.' },

  // Pontuação básica
  { id:'2pe3_051', s:'portugues', t:'Pontuação básica', type:'mc', diff:3,
    q:'✏️ Que sinal falta? "Olá ___ Como estás?"',
    opts:['.',',','!'], ans:2,
    exp:'Depois de "Olá" usamos "!" porque é um cumprimento com emoção.' },
  { id:'2pe3_052', s:'portugues', t:'Pontuação básica', type:'fill', diff:3,
    q:'Escreve o sinal certo no fim: "Queres brincar comigo___"',
    ans:['?'],
    exp:'É uma pergunta, então usa ponto de interrogação "?".' },
  { id:'2pe3_053', s:'portugues', t:'Pontuação básica', type:'tf', diff:3,
    q:'Usamos vírgula para separar palavras numa lista, como em "comprei pão, leite e fruta".',
    ans:true,
    exp:'Sim! A vírgula separa elementos de uma lista. Antes do "e" não se põe.' },
  { id:'2pe3_054', s:'portugues', t:'Pontuação básica', type:'mc', diff:3,
    q:'Qual frase está bem pontuada?',
    opts:['Que giro.','Que giro!','Que giro,'], ans:1,
    exp:'"Que giro!" mostra emoção, por isso leva ponto de exclamação.' },
  { id:'2pe3_055', s:'portugues', t:'Pontuação básica', type:'mc', diff:3,
    q:'Onde devem ir vírgulas? "A Ana o João e a Rita brincam."',
    opts:['A Ana, o João, e a Rita','A Ana, o João e a Rita','A Ana o João, e a Rita'], ans:1,
    exp:'Vírgula entre "Ana" e "o João". Antes do "e" não se põe vírgula.' }
];
if (typeof window !== 'undefined') window.EXERCISES_2_P_EXTRA3 = EXERCISES_2_P_EXTRA3;
