// EscolaPlay - Top-up dificuldade 3 do 2.º ano - Estudo do Meio (gerado, alinhado com Supermiúdos)
const EXERCISES_2_E_EXTRA3 = [
  // O meu corpo
  { id:'2ee3_001', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:3,
    q:'🦴 Quantos ossos tem aproximadamente o corpo de um adulto?',
    opts:['cerca de 50','cerca de 100','cerca de 200'], ans:2,
    exp:'O corpo de um adulto tem cerca de 200 ossos (206 ao certo).' },
  { id:'2ee3_002', s:'estudo_meio', t:'O meu corpo', type:'tf', diff:3,
    q:'O coração fica do lado direito do peito.',
    ans:false,
    exp:'O coração fica mais ao lado esquerdo do peito, não à direita.' },
  { id:'2ee3_003', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:3,
    q:'Qual destes órgãos serve para respirar?',
    opts:['estômago','pulmões','fígado'], ans:1,
    exp:'Os pulmões servem para respirar — entram com o ar e saem com o ar usado.' },
  { id:'2ee3_004', s:'estudo_meio', t:'O meu corpo', type:'fill', diff:3,
    q:'Os dentes que servem para cortar a comida chamam-se ___ (à frente da boca).',
    ans:['incisivos','incisivo'],
    exp:'Os dentes incisivos ficam à frente da boca e servem para cortar.' },
  { id:'2ee3_005', s:'estudo_meio', t:'O meu corpo', type:'mc', diff:3,
    q:'O que faz o estômago?',
    opts:['bombeia o sangue','digere a comida','filtra o ar'], ans:1,
    exp:'O estômago digere (desfaz) a comida que comemos.' },

  // Os sentidos
  { id:'2ee3_006', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:3,
    q:'👃 Que sentido usas para saber se o leite está estragado sem o provar?',
    opts:['visão','olfato','tato'], ans:1,
    exp:'Usas o olfato (cheiro) para sentir se o leite cheira mal.' },
  { id:'2ee3_007', s:'estudo_meio', t:'Os sentidos', type:'tf', diff:3,
    q:'A pele só serve para o sentido do tato.',
    ans:false,
    exp:'A pele tem o tato, mas também sente calor, frio e dor — é mais do que tato.' },
  { id:'2ee3_008', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:3,
    q:'Sentes que o gelado é doce e frio. Que dois sentidos usaste?',
    opts:['paladar e tato','visão e olfato','audição e paladar'], ans:0,
    exp:'O paladar sente o doce; o tato (na boca) sente o frio.' },
  { id:'2ee3_009', s:'estudo_meio', t:'Os sentidos', type:'fill', diff:3,
    q:'O órgão do sentido da audição é o ___.',
    ans:['ouvido','ouvidos'],
    exp:'Ouvimos com os ouvidos. É o órgão da audição.' },
  { id:'2ee3_010', s:'estudo_meio', t:'Os sentidos', type:'mc', diff:3,
    q:'Quando uma pessoa cega lê em Braille, que sentido usa?',
    opts:['visão','tato','audição'], ans:1,
    exp:'Lê com os dedos, sentindo os pontinhos. Usa o tato.' },

  // A minha família
  { id:'2ee3_011', s:'estudo_meio', t:'A minha família', type:'mc', diff:3,
    q:'👨‍👩‍👧 O irmão da tua mãe é teu...',
    opts:['primo','tio','padrinho'], ans:1,
    exp:'O irmão da tua mãe (ou do teu pai) é teu tio.' },
  { id:'2ee3_012', s:'estudo_meio', t:'A minha família', type:'tf', diff:3,
    q:'O pai do teu pai é teu bisavô.',
    ans:false,
    exp:'O pai do teu pai é teu avô. O pai do teu avô é que é o bisavô.' },
  { id:'2ee3_013', s:'estudo_meio', t:'A minha família', type:'mc', diff:3,
    q:'A filha do teu tio é tua...',
    opts:['irmã','prima','sobrinha'], ans:1,
    exp:'A filha do teu tio é tua prima.' },
  { id:'2ee3_014', s:'estudo_meio', t:'A minha família', type:'fill', diff:3,
    q:'A mãe da tua mãe é a tua ___.',
    ans:['avó'],
    exp:'A mãe da tua mãe (e a mãe do teu pai) é a tua avó.' },
  { id:'2ee3_015', s:'estudo_meio', t:'A minha família', type:'mc', diff:3,
    q:'Se tens 1 irmão e 2 irmãs, és filho/a de...',
    opts:['1 pessoa','2 pessoas','4 pessoas'], ans:1,
    exp:'Os irmãos partilham os mesmos pais — são 2 pessoas (mãe e pai).' },

  // A escola
  { id:'2ee3_016', s:'estudo_meio', t:'A escola', type:'mc', diff:3,
    q:'🏫 Quem ajuda a manter a escola limpa?',
    opts:['o professor','os auxiliares','o diretor'], ans:1,
    exp:'Os auxiliares (assistentes operacionais) ajudam a limpar e a cuidar da escola.' },
  { id:'2ee3_017', s:'estudo_meio', t:'A escola', type:'tf', diff:3,
    q:'Na escola devemos correr nos corredores.',
    ans:false,
    exp:'Não devemos correr nos corredores para não nos magoarmos nem aos outros.' },
  { id:'2ee3_018', s:'estudo_meio', t:'A escola', type:'mc', diff:3,
    q:'Qual destas regras é a mais importante para haver respeito?',
    opts:['ouvir os colegas','correr depressa','falar alto'], ans:0,
    exp:'Ouvir os colegas é uma regra de respeito muito importante.' },
  { id:'2ee3_019', s:'estudo_meio', t:'A escola', type:'fill', diff:3,
    q:'O sítio onde brincamos no intervalo chama-se ___.',
    ans:['recreio'],
    exp:'O recreio é o espaço para brincarmos no intervalo.' },
  { id:'2ee3_020', s:'estudo_meio', t:'A escola', type:'mc', diff:3,
    q:'Se um colega se magoa no recreio, deves...',
    opts:['rir','chamar um adulto','ir embora'], ans:1,
    exp:'Devemos sempre chamar um adulto para ajudar.' },

  // Animais
  { id:'2ee3_021', s:'estudo_meio', t:'Animais', type:'mc', diff:3,
    q:'🐢 A tartaruga é um animal...',
    opts:['mamífero','réptil','peixe'], ans:1,
    exp:'A tartaruga é um réptil. Tem pele com escamas ou carapaça.' },
  { id:'2ee3_022', s:'estudo_meio', t:'Animais', type:'tf', diff:3,
    q:'A baleia é um peixe porque vive no mar.',
    ans:false,
    exp:'A baleia vive no mar mas é mamífero — respira ar e dá leite às crias.' },
  { id:'2ee3_023', s:'estudo_meio', t:'Animais', type:'mc', diff:3,
    q:'Qual destes animais é omnívoro (come carne e plantas)?',
    opts:['vaca','leão','porco'], ans:2,
    exp:'O porco come de tudo: plantas e carne. É omnívoro.' },
  { id:'2ee3_024', s:'estudo_meio', t:'Animais', type:'fill', diff:3,
    q:'Os animais que comem só plantas chamam-se ___.',
    ans:['herbívoros','herbívoro'],
    exp:'Herbívoros são os animais que comem só plantas, como a vaca.' },
  { id:'2ee3_025', s:'estudo_meio', t:'Animais', type:'mc', diff:3,
    q:'Qual destes animais NÃO põe ovos?',
    opts:['galinha','gato','crocodilo'], ans:1,
    exp:'O gato é mamífero — nasce da mãe. Galinha e crocodilo põem ovos.' },

  // Plantas
  { id:'2ee3_026', s:'estudo_meio', t:'Plantas', type:'mc', diff:3,
    q:'🌱 Qual parte da planta absorve água da terra?',
    opts:['folhas','raiz','flor'], ans:1,
    exp:'A raiz fica enterrada e absorve água e alimento da terra.' },
  { id:'2ee3_027', s:'estudo_meio', t:'Plantas', type:'tf', diff:3,
    q:'As plantas precisam de luz do sol para crescer.',
    ans:true,
    exp:'Sim! As plantas usam a luz do sol para fazer o seu alimento.' },
  { id:'2ee3_028', s:'estudo_meio', t:'Plantas', type:'mc', diff:3,
    q:'A laranja é fruto, mas a alface é...',
    opts:['raiz','folha','flor'], ans:1,
    exp:'Comemos as folhas da alface. É um vegetal de folha.' },
  { id:'2ee3_029', s:'estudo_meio', t:'Plantas', type:'fill', diff:3,
    q:'A parte da planta que dá origem ao fruto é a ___.',
    ans:['flor'],
    exp:'A flor, depois de polinizada, dá origem ao fruto.' },
  { id:'2ee3_030', s:'estudo_meio', t:'Plantas', type:'mc', diff:3,
    q:'Qual destes alimentos é uma raiz que comemos?',
    opts:['cenoura','tomate','maçã'], ans:0,
    exp:'A cenoura é a raiz da planta. Tomate e maçã são frutos.' },

  // Estações do ano
  { id:'2ee3_031', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:3,
    q:'🍂 Em que estação caem as folhas das árvores?',
    opts:['primavera','verão','outono'], ans:2,
    exp:'No outono as folhas mudam de cor e caem das árvores.' },
  { id:'2ee3_032', s:'estudo_meio', t:'Estações do ano', type:'tf', diff:3,
    q:'O verão começa em junho em Portugal.',
    ans:true,
    exp:'Sim! Em Portugal o verão começa em junho e acaba em setembro.' },
  { id:'2ee3_033', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:3,
    q:'Quantas estações tem um ano?',
    opts:['2','4','12'], ans:1,
    exp:'Um ano tem 4 estações: primavera, verão, outono e inverno.' },
  { id:'2ee3_034', s:'estudo_meio', t:'Estações do ano', type:'fill', diff:3,
    q:'A estação em que as flores nascem é a ___.',
    ans:['primavera'],
    exp:'Na primavera as flores nascem e os campos ficam coloridos.' },
  { id:'2ee3_035', s:'estudo_meio', t:'Estações do ano', type:'mc', diff:3,
    q:'Em que estação os dias são mais curtos?',
    opts:['verão','primavera','inverno'], ans:2,
    exp:'No inverno os dias são mais curtos e as noites mais longas.' },

  // Profissões
  { id:'2ee3_036', s:'estudo_meio', t:'Profissões', type:'mc', diff:3,
    q:'👨‍🍳 Quem trata de animais doentes?',
    opts:['médico','veterinário','enfermeiro'], ans:1,
    exp:'O veterinário é o médico dos animais.' },
  { id:'2ee3_037', s:'estudo_meio', t:'Profissões', type:'tf', diff:3,
    q:'O carteiro entrega cartas e encomendas.',
    ans:true,
    exp:'Sim! O carteiro leva o correio às casas das pessoas.' },
  { id:'2ee3_038', s:'estudo_meio', t:'Profissões', type:'mc', diff:3,
    q:'Quem faz pão fresco todos os dias?',
    opts:['pasteleiro','padeiro','cozinheiro'], ans:1,
    exp:'O padeiro faz pão na padaria. O pasteleiro faz bolos.' },
  { id:'2ee3_039', s:'estudo_meio', t:'Profissões', type:'fill', diff:3,
    q:'A pessoa que apaga incêndios é o ___.',
    ans:['bombeiro'],
    exp:'Os bombeiros apagam incêndios e ajudam em emergências.' },
  { id:'2ee3_040', s:'estudo_meio', t:'Profissões', type:'mc', diff:3,
    q:'Quem ajuda os doentes no hospital, mas não é médico?',
    opts:['professor','enfermeiro','engenheiro'], ans:1,
    exp:'O enfermeiro cuida dos doentes e ajuda os médicos.' },

  // Portugal
  { id:'2ee3_041', s:'estudo_meio', t:'Portugal', type:'mc', diff:3,
    q:'🇵🇹 Qual é a capital de Portugal?',
    opts:['Porto','Lisboa','Coimbra'], ans:1,
    exp:'A capital de Portugal é Lisboa.' },
  { id:'2ee3_042', s:'estudo_meio', t:'Portugal', type:'tf', diff:3,
    q:'Os Açores e a Madeira são ilhas portuguesas.',
    ans:true,
    exp:'Sim! Açores e Madeira são arquipélagos (grupos de ilhas) de Portugal.' },
  { id:'2ee3_043', s:'estudo_meio', t:'Portugal', type:'mc', diff:3,
    q:'Que país faz fronteira com Portugal?',
    opts:['França','Espanha','Itália'], ans:1,
    exp:'Portugal só tem fronteira com Espanha. Os outros países ficam mais longe.' },
  { id:'2ee3_044', s:'estudo_meio', t:'Portugal', type:'fill', diff:3,
    q:'O rio mais comprido que passa em Portugal chama-se ___.',
    ans:['Tejo','tejo'],
    exp:'O rio Tejo é o mais comprido. Atravessa Lisboa antes de chegar ao mar.' },
  { id:'2ee3_045', s:'estudo_meio', t:'Portugal', type:'mc', diff:3,
    q:'Que cores tem a bandeira de Portugal?',
    opts:['azul e branco','verde e vermelho','vermelho e amarelo'], ans:1,
    exp:'A bandeira de Portugal é verde e vermelha, com o escudo no meio.' }
];
if (typeof window !== 'undefined') window.EXERCISES_2_E_EXTRA3 = EXERCISES_2_E_EXTRA3;
