// EscolaPlay - Top-up extra do 6.º ano - Português (gerado, AE 2018, alinhado com Mensagens 6 — Texto Editores)
// 3 tópicos novos: Frase ativa e passiva, Pronomes e determinantes, Notícia e entrevista
const EXERCISES_6_P_EXTRA2 = [
  // ===== Tópico A: Frase ativa e passiva (6pe2_001 - 6pe2_025) =====
  { id:'6pe2_001', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:1,
    q:'📝 Numa frase na voz ativa, o sujeito é aquele que…',
    opts:['Sofre a ação','Pratica a ação','É o complemento','Não existe'], ans:1,
    exp:'Na voz ativa, o sujeito é o agente, isto é, quem pratica a ação expressa pelo verbo.' },
  { id:'6pe2_002', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:1,
    q:'📝 Numa frase na voz passiva, o sujeito é aquele que…',
    opts:['Pratica a ação','Sofre a ação','Substitui o verbo','É omitido'], ans:1,
    exp:'Na voz passiva, o sujeito é o paciente, ou seja, quem recebe ou sofre a ação.' },
  { id:'6pe2_003', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:1,
    q:'📝 Em "O João comeu o bolo", a frase está na voz…',
    opts:['Ativa','Passiva','Reflexa','Nenhuma'], ans:0,
    exp:'O sujeito "O João" pratica a ação de comer, logo a frase está na voz ativa.' },
  { id:'6pe2_004', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:1,
    q:'📝 Em "O bolo foi comido pelo João", a frase está na voz…',
    opts:['Ativa','Passiva','Imperativa','Negativa'], ans:1,
    exp:'O sujeito "O bolo" sofre a ação; a frase apresenta o auxiliar "ser" + particípio, sendo voz passiva.' },
  { id:'6pe2_005', s:'portugues', t:'Frase ativa e passiva', type:'tf', diff:1,
    q:'📝 Verdadeiro ou falso: na voz passiva utiliza-se o verbo auxiliar "ser" seguido do particípio passado do verbo principal.',
    ans:true,
    exp:'A construção típica da passiva em português é "ser" + particípio passado (ex.: "foi escrito").' },
  { id:'6pe2_006', s:'portugues', t:'Frase ativa e passiva', type:'tf', diff:1,
    q:'📝 Verdadeiro ou falso: na voz passiva, o agente da passiva é introduzido pelas preposições "por" ou "pelo/pela".',
    ans:true,
    exp:'O agente da passiva surge precedido de "por", "pelo" ou "pela" (ex.: "pelo professor").' },
  { id:'6pe2_007', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:1,
    q:'📝 Em "A carta foi escrita pela Maria", o agente da passiva é…',
    opts:['A carta','foi escrita','pela Maria','escrita'], ans:2,
    exp:'O agente da passiva é "pela Maria", introduzido pela contração "pela".' },
  { id:'6pe2_008', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:1,
    q:'📝 Qual o verbo auxiliar usado na voz passiva?',
    opts:['Ter','Haver','Ser','Estar'], ans:2,
    exp:'O auxiliar próprio da voz passiva em português é o verbo "ser".' },
  { id:'6pe2_009', s:'portugues', t:'Frase ativa e passiva', type:'fill', diff:1,
    q:'📝 Completa: na voz ______, o sujeito sofre a ação.',
    ans:['passiva'],
    exp:'Na voz passiva, o sujeito é paciente — sofre a ação.' },
  { id:'6pe2_010', s:'portugues', t:'Frase ativa e passiva', type:'fill', diff:1,
    q:'📝 Completa: na voz ______, o sujeito pratica a ação.',
    ans:['ativa'],
    exp:'Na voz ativa, o sujeito é o agente da ação.' },
  { id:'6pe2_011', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Transforma na voz passiva: "O Pedro pintou o quadro."',
    opts:['O quadro pintou o Pedro','O quadro foi pintado pelo Pedro','O Pedro foi pintado pelo quadro','O quadro está pintado'], ans:1,
    exp:'O complemento direto "o quadro" passa a sujeito; usa-se "ser" + particípio "pintado" e "pelo Pedro" como agente.' },
  { id:'6pe2_012', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Transforma na voz ativa: "O bolo foi feito pela avó."',
    opts:['A avó fazia o bolo','A avó faz o bolo','A avó fez o bolo','O bolo fez a avó'], ans:2,
    exp:'O agente "pela avó" passa a sujeito "A avó"; o verbo no pretérito perfeito fica "fez" e "o bolo" é complemento direto.' },
  { id:'6pe2_013', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Transforma na voz passiva: "Os alunos resolveram o problema."',
    opts:['O problema foi resolvido pelos alunos','Os alunos foram resolvidos pelo problema','O problema resolveu os alunos','Os alunos resolvem o problema'], ans:0,
    exp:'"O problema" torna-se sujeito; "ser" no pretérito ("foi") + particípio "resolvido" + agente "pelos alunos".' },
  { id:'6pe2_014', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Em "A casa foi construída pelos pedreiros", o sujeito é…',
    opts:['pelos pedreiros','foi construída','A casa','construída'], ans:2,
    exp:'O sujeito gramatical é "A casa", que sofre a ação de ser construída.' },
  { id:'6pe2_015', s:'portugues', t:'Frase ativa e passiva', type:'tf', diff:2,
    q:'📝 Verdadeiro ou falso: na frase "As janelas foram abertas pelo vento", o particípio "abertas" concorda em género e número com o sujeito.',
    ans:true,
    exp:'O particípio passado na voz passiva concorda com o sujeito (feminino plural: "abertas").' },
  { id:'6pe2_016', s:'portugues', t:'Frase ativa e passiva', type:'fill', diff:2,
    q:'📝 Completa a passiva: "O livro ____ lido pela turma." (verbo "ser" no pretérito perfeito)',
    ans:['foi'],
    exp:'O auxiliar "ser" no pretérito perfeito do indicativo é "foi".' },
  { id:'6pe2_017', s:'portugues', t:'Frase ativa e passiva', type:'fill', diff:2,
    q:'📝 Passa para a passiva apenas o verbo: "A Joana escreveu a carta." → "A carta ____ escrita pela Joana." (verbo "ser")',
    ans:['foi'],
    exp:'Pretérito perfeito de "ser" na 3.ª pessoa do singular: "foi".' },
  { id:'6pe2_018', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Em "Os jornais são lidos diariamente pelos leitores", o agente da passiva é…',
    opts:['Os jornais','são lidos','diariamente','pelos leitores'], ans:3,
    exp:'O agente é introduzido por "por/pelo/pela": "pelos leitores".' },
  { id:'6pe2_019', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Qual destas frases está na voz passiva?',
    opts:['O cão ladra alto','A bola foi chutada pelo Tiago','O sol brilha hoje','As crianças correm no recreio'], ans:1,
    exp:'Apenas "A bola foi chutada pelo Tiago" tem "ser" + particípio + agente da passiva.' },
  { id:'6pe2_020', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:2,
    q:'📝 Transforma na voz passiva: "A Inês comprou as flores."',
    opts:['As flores compram a Inês','As flores foram compradas pela Inês','A Inês foi comprada pelas flores','As flores comprou a Inês'], ans:1,
    exp:'Particípio "compradas" no feminino plural concorda com "as flores"; agente "pela Inês".' },
  { id:'6pe2_021', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:3,
    q:'📝 Transforma na voz passiva: "O gato apanhou os ratos."',
    opts:['Os ratos foram apanhados pelo gato','Os ratos foi apanhado pelo gato','Os ratos foram apanhadas pelo gato','O gato foi apanhado pelos ratos'], ans:0,
    exp:'O particípio concorda em masculino plural ("apanhados") com "os ratos"; auxiliar "foram".' },
  { id:'6pe2_022', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:3,
    q:'📝 Identifica a única frase na voz passiva.',
    opts:['Estou cansado','As regras foram explicadas pelo treinador','Ele anda triste','Fomos ao cinema'], ans:1,
    exp:'Apenas a 2.ª frase tem estrutura "ser" + particípio + agente. As restantes usam "estar/ir" e não são passivas.' },
  { id:'6pe2_023', s:'portugues', t:'Frase ativa e passiva', type:'tf', diff:3,
    q:'📝 Verdadeiro ou falso: a frase "Fomos surpreendidos pelo barulho" está na voz passiva.',
    ans:true,
    exp:'"Fomos" é o auxiliar "ser" + particípio "surpreendidos"; "pelo barulho" é o agente da passiva.' },
  { id:'6pe2_024', s:'portugues', t:'Frase ativa e passiva', type:'fill', diff:3,
    q:'📝 Completa o particípio com a concordância correta: "As cartas foram ______ pela professora." (verbo "ler")',
    ans:['lidas'],
    exp:'Particípio de "ler" no feminino plural: "lidas", concordando com "as cartas".' },
  { id:'6pe2_025', s:'portugues', t:'Frase ativa e passiva', type:'mc', diff:3,
    q:'📝 Transforma na voz ativa: "Os trabalhos serão corrigidos pelo professor."',
    opts:['O professor corrige os trabalhos','O professor corrigirá os trabalhos','O professor corrigiu os trabalhos','Os trabalhos corrigirão o professor'], ans:1,
    exp:'O auxiliar "serão" indica futuro; logo, na ativa o verbo principal vai para o futuro: "corrigirá".' },

  // ===== Tópico B: Pronomes e determinantes (6pe2_026 - 6pe2_050) =====
  { id:'6pe2_026', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 O pronome é a palavra que…',
    opts:['Acompanha o nome','Substitui o nome','Modifica o verbo','Liga frases'], ans:1,
    exp:'O pronome substitui o nome (substantivo), evitando a sua repetição.' },
  { id:'6pe2_027', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 O determinante é a palavra que…',
    opts:['Substitui o nome','Acompanha o nome','Substitui o verbo','Indica uma ação'], ans:1,
    exp:'O determinante acompanha o nome, indicando, por exemplo, género, número ou posse.' },
  { id:'6pe2_028', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 Em "O meu livro é novo", a palavra "meu" é…',
    opts:['Pronome possessivo','Determinante possessivo','Pronome pessoal','Determinante artigo'], ans:1,
    exp:'"Meu" acompanha o nome "livro", logo é determinante possessivo.' },
  { id:'6pe2_029', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 Em "Este é o meu", a palavra "meu" é…',
    opts:['Pronome possessivo','Determinante possessivo','Pronome pessoal','Determinante demonstrativo'], ans:0,
    exp:'Aqui "meu" não acompanha nenhum nome, substitui-o, sendo pronome possessivo.' },
  { id:'6pe2_030', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 "Eu", "tu", "ele" são pronomes…',
    opts:['Possessivos','Pessoais','Demonstrativos','Indefinidos'], ans:1,
    exp:'São pronomes pessoais de sujeito.' },
  { id:'6pe2_031', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 "Este", "esse", "aquele" são…',
    opts:['Pronomes pessoais','Demonstrativos','Indefinidos','Relativos'], ans:1,
    exp:'São demonstrativos: indicam proximidade ou distância em relação ao falante.' },
  { id:'6pe2_032', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:1,
    q:'📝 "Algum", "nenhum", "todo" são…',
    opts:['Pronomes pessoais','Possessivos','Indefinidos','Demonstrativos'], ans:2,
    exp:'Indicam quantidade ou identidade de modo vago — são indefinidos.' },
  { id:'6pe2_033', s:'portugues', t:'Pronomes e determinantes', type:'tf', diff:1,
    q:'📝 Verdadeiro ou falso: "o", "a", "um", "uma" são determinantes artigos.',
    ans:true,
    exp:'"O/a" são artigos definidos e "um/uma" são artigos indefinidos.' },
  { id:'6pe2_034', s:'portugues', t:'Pronomes e determinantes', type:'fill', diff:1,
    q:'📝 Completa: a palavra que substitui o nome chama-se ______.',
    ans:['pronome'],
    exp:'Por definição, o pronome substitui o nome.' },
  { id:'6pe2_035', s:'portugues', t:'Pronomes e determinantes', type:'fill', diff:1,
    q:'📝 Completa: a palavra que acompanha o nome chama-se ______.',
    ans:['determinante'],
    exp:'O determinante acompanha o nome no grupo nominal.' },
  { id:'6pe2_036', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:2,
    q:'📝 Em "A Ana viu-o no parque", a palavra "o" é…',
    opts:['Determinante artigo','Pronome pessoal','Pronome demonstrativo','Determinante demonstrativo'], ans:1,
    exp:'"O" liga-se ao verbo por hífen e substitui o complemento direto, sendo pronome pessoal (forma átona).' },
  { id:'6pe2_037', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:2,
    q:'📝 Em "Ofereci-lhe um presente", "lhe" é pronome pessoal…',
    opts:['De sujeito','Complemento direto','Complemento indireto','Reflexo'], ans:2,
    exp:'"Lhe" representa "a ele/a ela", introduzindo o complemento indireto.' },
  { id:'6pe2_038', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:2,
    q:'📝 Em "Esse caderno é teu?", "esse" é…',
    opts:['Pronome demonstrativo','Determinante demonstrativo','Pronome possessivo','Determinante indefinido'], ans:1,
    exp:'"Esse" acompanha o nome "caderno", logo é determinante demonstrativo.' },
  { id:'6pe2_039', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:2,
    q:'📝 Em "Quero aquele.", "aquele" é…',
    opts:['Determinante demonstrativo','Pronome demonstrativo','Pronome possessivo','Determinante artigo'], ans:1,
    exp:'Sem nome a seguir, "aquele" substitui-o — é pronome demonstrativo.' },
  { id:'6pe2_040', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:2,
    q:'📝 Em "O rapaz que fala alto é o meu primo", "que" é pronome…',
    opts:['Pessoal','Relativo','Indefinido','Demonstrativo'], ans:1,
    exp:'"Que" introduz uma oração relativa e refere-se a "rapaz" — é pronome relativo.' },
  { id:'6pe2_041', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:2,
    q:'📝 Em "Ela telefonou-me ontem", "me" é pronome pessoal…',
    opts:['Sujeito','Complemento direto ou indireto átono','Reflexo','Tónico'], ans:1,
    exp:'"Me" é forma átona de complemento (direto/indireto, dependendo do verbo).' },
  { id:'6pe2_042', s:'portugues', t:'Pronomes e determinantes', type:'tf', diff:2,
    q:'📝 Verdadeiro ou falso: em frases negativas, o pronome átono fica antes do verbo (próclise). Ex.: "Não me viste."',
    ans:true,
    exp:'Advérbios de negação como "não", "nunca", "ninguém" atraem o pronome para próclise.' },
  { id:'6pe2_043', s:'portugues', t:'Pronomes e determinantes', type:'tf', diff:2,
    q:'📝 Verdadeiro ou falso: em frases afirmativas neutras, o pronome átono fica depois do verbo, ligado por hífen (ênclise). Ex.: "Vi-o ontem."',
    ans:true,
    exp:'Em afirmativas sem palavras atrativas, usa-se ênclise.' },
  { id:'6pe2_044', s:'portugues', t:'Pronomes e determinantes', type:'fill', diff:2,
    q:'📝 Coloca o pronome corretamente: "Ele não ____ disse a verdade." (pronome "me")',
    ans:['me'],
    exp:'Com "não", o pronome vai para próclise: "Ele não me disse a verdade."' },
  { id:'6pe2_045', s:'portugues', t:'Pronomes e determinantes', type:'fill', diff:2,
    q:'📝 Identifica o tipo de pronome em "Quem chegou primeiro?": pronome ______.',
    ans:['interrogativo'],
    exp:'"Quem", em interrogativas, é pronome interrogativo.' },
  { id:'6pe2_046', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:3,
    q:'📝 Em "Far-lhe-ei um pedido", o pronome "lhe" está em…',
    opts:['Próclise','Ênclise','Mesóclise','Não está colocado'], ans:2,
    exp:'No futuro/condicional sem palavras atrativas, o pronome insere-se no meio do verbo — mesóclise.' },
  { id:'6pe2_047', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:3,
    q:'📝 Em "Todas as crianças cantaram a canção", "Todas" é…',
    opts:['Pronome indefinido','Determinante indefinido','Pronome demonstrativo','Determinante demonstrativo'], ans:1,
    exp:'"Todas" acompanha o nome "crianças", funcionando como determinante indefinido.' },
  { id:'6pe2_048', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:3,
    q:'📝 Em "Ninguém sabe a resposta", "Ninguém" é…',
    opts:['Determinante indefinido','Pronome indefinido','Pronome pessoal','Determinante artigo'], ans:1,
    exp:'"Ninguém" não acompanha nome — é pronome indefinido (vale por si próprio como sujeito).' },
  { id:'6pe2_049', s:'portugues', t:'Pronomes e determinantes', type:'tf', diff:3,
    q:'📝 Verdadeiro ou falso: na frase "A casa onde vivo é antiga", "onde" é pronome relativo.',
    ans:true,
    exp:'"Onde" remete para o antecedente "casa" e introduz oração relativa — é pronome relativo (de lugar).' },
  { id:'6pe2_050', s:'portugues', t:'Pronomes e determinantes', type:'mc', diff:3,
    q:'📝 Em "Quando ele chegar, dir-lho-ei", o pronome "lho" resulta da contração de…',
    opts:['lhe + o','le + ho','la + o','lhe + a'], ans:0,
    exp:'"Lho" é a forma contraída de "lhe" (complemento indireto) + "o" (complemento direto).' },

  // ===== Tópico C: Notícia e entrevista (6pe2_051 - 6pe2_075) =====
  { id:'6pe2_051', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:1,
    q:'📰 A principal intencionalidade comunicativa da notícia é…',
    opts:['Divertir','Informar','Convencer a comprar','Ensinar uma receita'], ans:1,
    exp:'A notícia é um texto informativo: dá a conhecer um acontecimento atual.' },
  { id:'6pe2_052', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:1,
    q:'📰 O título de uma notícia serve para…',
    opts:['Aumentar o tamanho do jornal','Resumir e captar a atenção','Fazer publicidade','Despedir-se do leitor'], ans:1,
    exp:'O título resume o assunto e desperta o interesse do leitor.' },
  { id:'6pe2_053', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:1,
    q:'📰 O lead (ou lide) de uma notícia é…',
    opts:['O fim do texto','O primeiro parágrafo que responde ao essencial','Uma fotografia','Um anúncio'], ans:1,
    exp:'O lead é o parágrafo inicial que responde rapidamente às perguntas essenciais.' },
  { id:'6pe2_054', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:1,
    q:'📰 Quantas perguntas costuma responder o lead?',
    opts:['3','5','6','10'], ans:2,
    exp:'O lead responde habitualmente a 6 perguntas: Quem? O quê? Quando? Onde? Como? Porquê?' },
  { id:'6pe2_055', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:1,
    q:'📰 Numa entrevista existem dois intervenientes principais: o…',
    opts:['Locutor e o ouvinte','Entrevistador e o entrevistado','Autor e o personagem','Narrador e o leitor'], ans:1,
    exp:'O entrevistador faz perguntas; o entrevistado responde.' },
  { id:'6pe2_056', s:'portugues', t:'Notícia e entrevista', type:'tf', diff:1,
    q:'📰 Verdadeiro ou falso: a notícia organiza-se geralmente em título, lead e corpo.',
    ans:true,
    exp:'A estrutura típica é título (e por vezes subtítulo), lead e corpo da notícia.' },
  { id:'6pe2_057', s:'portugues', t:'Notícia e entrevista', type:'tf', diff:1,
    q:'📰 Verdadeiro ou falso: a notícia deve apresentar a opinião pessoal do jornalista no lead.',
    ans:false,
    exp:'A notícia procura ser objetiva; a opinião é própria de outros géneros (editorial, crónica).' },
  { id:'6pe2_058', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:1,
    q:'📰 A pergunta "Quando?" do lead refere-se ao(à)…',
    opts:['Local','Tempo','Motivo','Modo'], ans:1,
    exp:'"Quando?" indica o tempo em que decorreu o acontecimento.' },
  { id:'6pe2_059', s:'portugues', t:'Notícia e entrevista', type:'fill', diff:1,
    q:'📰 Completa: a pergunta do lead que indica o local é "______?".',
    ans:['onde'],
    exp:'"Onde?" identifica o local do acontecimento.' },
  { id:'6pe2_060', s:'portugues', t:'Notícia e entrevista', type:'fill', diff:1,
    q:'📰 Completa: o parágrafo inicial da notícia chama-se ______.',
    ans:['lead','lide'],
    exp:'"Lead" (ou "lide", em português) é o primeiro parágrafo, com a informação essencial.' },
  { id:'6pe2_061', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:2,
    q:'📰 Numa notícia, o "corpo" serve para…',
    opts:['Substituir o lead','Desenvolver e aprofundar a informação','Apresentar publicidade','Concluir o jornal'], ans:1,
    exp:'O corpo desenvolve, em pormenor, a informação anunciada no lead.' },
  { id:'6pe2_062', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:2,
    q:'📰 Diferença essencial entre notícia e reportagem:',
    opts:['Não há diferença','A reportagem é mais aprofundada e pode incluir testemunhos','A notícia é mais longa','A reportagem nunca tem fotografias'], ans:1,
    exp:'A reportagem é mais desenvolvida, aprofunda o tema e pode incluir entrevistas e descrições.' },
  { id:'6pe2_063', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:2,
    q:'📰 O subtítulo de uma notícia tem a função de…',
    opts:['Substituir o título','Acrescentar informação que complementa o título','Identificar o jornalista','Fechar a notícia'], ans:1,
    exp:'O subtítulo complementa o título com mais um dado relevante para o leitor.' },
  { id:'6pe2_064', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:2,
    q:'📰 Numa entrevista, o discurso usado nas respostas é tipicamente…',
    opts:['Discurso indireto','Discurso direto','Narrativo','Descritivo'], ans:1,
    exp:'As respostas surgem em discurso direto, com as palavras tal como foram ditas.' },
  { id:'6pe2_065', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:2,
    q:'📰 Antes de uma entrevista, o entrevistador deve, sobretudo…',
    opts:['Decorar as respostas','Preparar perguntas e informar-se sobre o entrevistado','Não preparar nada','Falar mais do que o entrevistado'], ans:1,
    exp:'Uma boa entrevista exige preparação: estudar o tema e elaborar perguntas pertinentes.' },
  { id:'6pe2_066', s:'portugues', t:'Notícia e entrevista', type:'tf', diff:2,
    q:'📰 Verdadeiro ou falso: numa notícia escrita, é habitual identificar a fonte da informação (agência, jornalista, instituição).',
    ans:true,
    exp:'Indicar a fonte aumenta a credibilidade e permite verificar a informação.' },
  { id:'6pe2_067', s:'portugues', t:'Notícia e entrevista', type:'tf', diff:2,
    q:'📰 Verdadeiro ou falso: numa entrevista, o entrevistado faz as perguntas e o entrevistador responde.',
    ans:false,
    exp:'É o contrário: o entrevistador faz as perguntas; o entrevistado responde.' },
  { id:'6pe2_068', s:'portugues', t:'Notícia e entrevista', type:'fill', diff:2,
    q:'📰 Completa: na entrevista, quem responde às perguntas é o ______.',
    ans:['entrevistado'],
    exp:'O entrevistado é a pessoa convidada a responder.' },
  { id:'6pe2_069', s:'portugues', t:'Notícia e entrevista', type:'fill', diff:2,
    q:'📰 Completa: a pergunta do lead que indica a causa ou motivo é "______?".',
    ans:['porquê','porque'],
    exp:'"Porquê?" introduz a explicação ou o motivo do acontecimento.' },
  { id:'6pe2_070', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:2,
    q:'📰 Lê o lead: "Ontem, em Lisboa, três alunos do 6.º ano venceram um concurso nacional de leitura, ao recitarem poemas de Sophia." A pergunta "O quê?" é respondida por:',
    opts:['Ontem','Em Lisboa','Venceram um concurso nacional de leitura','Ao recitarem poemas'], ans:2,
    exp:'O acontecimento principal é "venceram um concurso nacional de leitura".' },
  { id:'6pe2_071', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:3,
    q:'📰 Tipo de entrevista em que se valoriza sobretudo a vida e a experiência pessoal do entrevistado:',
    opts:['Entrevista de opinião','Entrevista de personalidade ou perfil','Entrevista informativa','Entrevista de rua'], ans:1,
    exp:'A entrevista de personalidade (ou perfil) explora a biografia, percurso e ideias do entrevistado.' },
  { id:'6pe2_072', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:3,
    q:'📰 Numa entrevista, qual destas perguntas é a MENOS adequada por induzir uma resposta?',
    opts:['O que pensa sobre o tema?','Concorda comigo que isto é o melhor que existe?','Pode descrever a sua experiência?','Como começou este projeto?'], ans:1,
    exp:'A pergunta da opção 1 é tendenciosa: leva o entrevistado a concordar com o entrevistador.' },
  { id:'6pe2_073', s:'portugues', t:'Notícia e entrevista', type:'tf', diff:3,
    q:'📰 Verdadeiro ou falso: o lead deve, idealmente, responder ao essencial mesmo que o leitor não leia o restante do texto.',
    ans:true,
    exp:'O lead é construído para que o leitor fique informado do essencial logo no início (princípio da pirâmide invertida).' },
  { id:'6pe2_074', s:'portugues', t:'Notícia e entrevista', type:'mc', diff:3,
    q:'📰 Numa notícia, a chamada "pirâmide invertida" significa que…',
    opts:['A informação menos importante surge primeiro','A informação mais importante surge primeiro','Não há ordem','O título vem no fim'], ans:1,
    exp:'Pirâmide invertida: do mais importante para o menos importante, para o leitor parar quando quiser.' },
  { id:'6pe2_075', s:'portugues', t:'Notícia e entrevista', type:'fill', diff:3,
    q:'📰 Completa: a pessoa que conduz a entrevista e faz as perguntas chama-se ______.',
    ans:['entrevistador'],
    exp:'O entrevistador prepara e formula as perguntas, dirigindo a entrevista.' }
];
if (typeof window !== 'undefined') window.EXERCISES_6_P_EXTRA2 = EXERCISES_6_P_EXTRA2;
