// EscolaPlay - Orientadores 3.º período 5.º ano Inglês
// Banco de exercícios: Telling the time, Daily routines, Jobs,
// Present simple, Prepositions of time.
// ~80 exercícios. PT-PT (Acordo Ortográfico de 1990).

const EXERCISES_5_I_ORIENT = [

    // ============================================================
    // ===================== TELLING THE TIME =====================
    // ============================================================
    { id:'5io_tt_1', s:'ingles', t:'Telling the time', type:'mc', diff:1,
      q:'🕐 Como se pergunta "Que horas são?" em inglês?',
      opts:["What's your name?","What time is it?","Where are you?","How old are you?"], ans:1,
      exp:'"What time is it?" ou "What\'s the time?" — perguntar as horas.' },
    { id:'5io_tt_2', s:'ingles', t:'Telling the time', type:'mc', diff:1,
      q:"🕒 3:00 em inglês:",
      opts:["It's three.","It's three o'clock.","It's three minutes.","Three time."], ans:1,
      exp:"Horas certas usam-se com 'o\\'clock'. 3:00 = It's three o'clock." },
    { id:'5io_tt_3', s:'ingles', t:'Telling the time', type:'mc', diff:1,
      q:'🕧 12:00 (meio-dia) diz-se:',
      opts:['Midnight','Noon (midday)','Twelve night','Half past twelve'], ans:1,
      exp:'Meio-dia = noon ou midday. Meia-noite = midnight.' },
    { id:'5io_tt_4', s:'ingles', t:'Telling the time', type:'mc', diff:2,
      q:'🕠 5:30 em inglês (forma tradicional):',
      opts:['Five thirty','Half past five','Quarter past five','Five and a half'], ans:1,
      exp:'Meias horas = "half past + hora". 5:30 = half past five.' },
    { id:'5io_tt_5', s:'ingles', t:'Telling the time', type:'mc', diff:2,
      q:'🕓 4:15 (forma tradicional):',
      opts:['Quarter to four','Quarter past four','Half past four','Four fifteen past'], ans:1,
      exp:'15 min depois → "quarter past". 4:15 = quarter past four.' },
    { id:'5io_tt_6', s:'ingles', t:'Telling the time', type:'mc', diff:2,
      q:'🕥 10:45 (forma tradicional):',
      opts:['Quarter past ten','Quarter to eleven','Half past ten','Ten forty-five past'], ans:1,
      exp:'15 min antes da próxima hora → "quarter to + próxima hora". 10:45 = quarter to eleven.' },
    { id:'5io_tt_7', s:'ingles', t:'Telling the time', type:'mc', diff:2,
      q:'🕘 9:10 (forma tradicional):',
      opts:['Ten to nine','Ten past nine','Ten o\'clock','Nine and ten'], ans:1,
      exp:'10 min depois das 9 → "ten past nine".' },
    { id:'5io_tt_8', s:'ingles', t:'Telling the time', type:'fill', diff:2,
      q:'🕒 Escreve em inglês (forma tradicional): "3:30"',
      ans:['half past three',"It's half past three.","half past 3"],
      exp:'3:30 = half past three.' },
    { id:'5io_tt_9', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'🕗 8:50 (forma tradicional):',
      opts:['Ten past eight','Ten to nine','Quarter to nine','Fifty past eight'], ans:1,
      exp:'50 min depois das 8 = 10 min antes das 9 → "ten to nine".' },
    { id:'5io_tt_10', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'🌅 9:00 AM significa:',
      opts:['Da manhã (9h da manhã)','Da noite (9h da noite)','Meia-noite e nove','Meio-dia'], ans:0,
      exp:'AM = ante meridiem = antes do meio-dia. 9 AM = 9h da manhã.' },
    { id:'5io_tt_11', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'🌙 9:00 PM em formato 24h é:',
      opts:['9:00','12:00','21:00','18:00'], ans:2,
      exp:'PM = depois do meio-dia. 9 PM = 21:00.' },
    { id:'5io_tt_12', s:'ingles', t:'Telling the time', type:'fill', diff:3,
      q:'🕥 Escreve em inglês (tradicional): "7:45"',
      ans:['quarter to eight',"It's quarter to eight.","quarter to 8"],
      exp:'7:45 = 15 min antes das 8 → quarter to eight.' },

    // ============================================================
    // ===================== DAILY ROUTINES =======================
    // ============================================================
    { id:'5io_dr_1', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'🌅 "Wake up" significa:',
      opts:['Levantar-se','Acordar','Dormir','Tomar banho'], ans:1,
      exp:'wake up = acordar. (get up = levantar-se da cama.)' },
    { id:'5io_dr_2', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'🍞 "Have breakfast" significa:',
      opts:['Almoçar','Jantar','Tomar pequeno-almoço','Lanchar'], ans:2,
      exp:'breakfast = pequeno-almoço; lunch = almoço; dinner = jantar.' },
    { id:'5io_dr_3', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'🛁 "Take a shower" significa:',
      opts:['Pentear-se','Tomar banho/duche','Lavar os dentes','Vestir-se'], ans:1,
      exp:'take/have a shower = tomar banho/duche.' },
    { id:'5io_dr_4', s:'ingles', t:'Daily routines', type:'mc', diff:1,
      q:'🦷 "Brush your teeth" significa:',
      opts:['Lavar a cara','Lavar os dentes','Pentear o cabelo','Calçar sapatos'], ans:1,
      exp:'brush teeth = escovar/lavar os dentes.' },
    { id:'5io_dr_5', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'📝 "Do homework" significa:',
      opts:['Limpar a casa','Fazer trabalhos de casa','Estudar para o teste','Brincar'], ans:1,
      exp:'homework = trabalhos de casa. Do homework = fazer TPC.' },
    { id:'5io_dr_6', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'🛏️ "Go to bed" significa:',
      opts:['Dormir','Ir para a cama','Acordar','Vestir o pijama'], ans:1,
      exp:'go to bed = ir para a cama. (sleep = dormir; o ato em si.)' },
    { id:'5io_dr_7', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:"📚 Frase correta com 3.ª pessoa:",
      opts:["She wake up at 7.","She wakes up at 7.","She waking up at 7.","She is wake up at 7."], ans:1,
      exp:'3.ª pessoa (he/she/it) leva -s no Present simple: wakes up.' },
    { id:'5io_dr_8', s:'ingles', t:'Daily routines', type:'mc', diff:2,
      q:'🥪 Qual é a ordem CORRETA na rotina?',
      opts:['Have dinner → Have breakfast → Have lunch','Have breakfast → Have lunch → Have dinner','Have lunch → Have breakfast → Have dinner','Have dinner → Have lunch → Have breakfast'], ans:1,
      exp:'Pequeno-almoço (manhã) → Almoço (meio-dia) → Jantar (noite).' },
    { id:'5io_dr_9', s:'ingles', t:'Daily routines', type:'fill', diff:2,
      q:"📚 Completa: I ___ to school at 8:30. (verbo 'ir')",
      ans:['go'],
      exp:'I go to school. (1.ª pessoa, sem -s.)' },
    { id:'5io_dr_10', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'🌙 "She ___ TV in the evening." (advérbio: usually = geralmente)',
      opts:['watches usually','usually watches','watch usually','usually watch'], ans:1,
      exp:'Advérbios de frequência (always, usually, often) vão ANTES do verbo principal.' },
    { id:'5io_dr_11', s:'ingles', t:'Daily routines', type:'fill', diff:3,
      q:'🌅 Completa: He ___ (have) breakfast at 7 am. (3.ª pessoa)',
      ans:['has'],
      exp:'have → has na 3.ª pessoa (he/she/it).' },
    { id:'5io_dr_12', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'📚 Forma NEGATIVA: "I don\'t play video games on weekdays." Significa:',
      opts:['Jogo sempre','Não jogo durante a semana','Jogo só ao fim de semana','Jogo às vezes'], ans:1,
      exp:'"don\'t play" = não jogo. weekdays = dias da semana (segunda a sexta).' },

    // ============================================================
    // ========================== JOBS ============================
    // ============================================================
    { id:'5io_jo_1', s:'ingles', t:'Jobs', type:'mc', diff:1,
      q:'👨‍⚕️ "Doctor" em português é:',
      opts:['Enfermeiro','Médico','Polícia','Dentista'], ans:1,
      exp:'doctor = médico. (nurse = enfermeiro/a.)' },
    { id:'5io_jo_2', s:'ingles', t:'Jobs', type:'mc', diff:1,
      q:'👮 "Police officer" é:',
      opts:['Bombeiro','Polícia','Pescador','Soldado'], ans:1,
      exp:'police officer = agente da polícia (também: policeman/policewoman).' },
    { id:'5io_jo_3', s:'ingles', t:'Jobs', type:'mc', diff:1,
      q:'👨‍🍳 "Cook" significa:',
      opts:['Padeiro','Cozinheiro','Açougueiro','Doceiro'], ans:1,
      exp:'cook = cozinheiro (também "chef" para chef profissional).' },
    { id:'5io_jo_4', s:'ingles', t:'Jobs', type:'mc', diff:1,
      q:'👩‍🏫 "Teacher" é:',
      opts:['Aluno','Diretor','Professor','Educador'], ans:2,
      exp:'teacher = professor/a.' },
    { id:'5io_jo_5', s:'ingles', t:'Jobs', type:'mc', diff:2,
      q:'🚒 "Firefighter" é:',
      opts:['Polícia','Bombeiro','Engenheiro','Veterinário'], ans:1,
      exp:'firefighter = bombeiro (palavra moderna, neutra; antigamente "fireman").' },
    { id:'5io_jo_6', s:'ingles', t:'Jobs', type:'mc', diff:2,
      q:'🐶 "Vet" é:',
      opts:['Veterinário','Voluntário','Vendedor','Vendedor de fruta'], ans:0,
      exp:'vet (abreviatura de veterinarian) = veterinário/a.' },
    { id:'5io_jo_7', s:'ingles', t:'Jobs', type:'mc', diff:2,
      q:'📮 "Postman" é:',
      opts:['Camionista','Carteiro','Polícia','Padeiro'], ans:1,
      exp:'postman/postwoman = carteiro/a.' },
    { id:'5io_jo_8', s:'ingles', t:'Jobs', type:'mc', diff:2,
      q:'🎤 "Singer" é:',
      opts:['Cantor/a','Ator/atriz','Dançarino/a','Pintor/a'], ans:0,
      exp:'singer = cantor/a (verbo: to sing = cantar).' },
    { id:'5io_jo_9', s:'ingles', t:'Jobs', type:'mc', diff:2,
      q:'🎨 Qual artigo usar: "She is ___ artist."',
      opts:['a','an','the','—'], ans:1,
      exp:'"An" antes de vogal: an artist, an engineer, an actor.' },
    { id:'5io_jo_10', s:'ingles', t:'Jobs', type:'fill', diff:2,
      q:'👨‍⚕️ Completa: He is ___ doctor.',
      ans:['a'],
      exp:'"A doctor" — artigo "a" antes de consoante.' },
    { id:'5io_jo_11', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'🏥 "A doctor works at a ___."',
      opts:['school','hospital','shop','farm'], ans:1,
      exp:'Médico trabalha num hospital (ou clínica).' },
    { id:'5io_jo_12', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'🚜 "A farmer works on a ___."',
      opts:['ship','farm','train','plane'], ans:1,
      exp:'farmer = agricultor; trabalha numa farm (quinta/herdade).' },
    { id:'5io_jo_13', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'❓ Pergunta correta sobre profissão:',
      opts:["What is your job?","What does your job?","Who your job is?","Where you work?"], ans:0,
      exp:'"What is your job?" ou "What do you do?" — perguntas padrão sobre profissão.' },

    // ============================================================
    // ===================== PRESENT SIMPLE =======================
    // ============================================================
    { id:'5io_ps_1', s:'ingles', t:'Present simple', type:'mc', diff:1,
      q:'📅 O Present simple usa-se para:',
      opts:['Coisas que estão a acontecer AGORA','Rotinas, hábitos e factos','Coisas que vão acontecer','Coisas que aconteceram ontem'], ans:1,
      exp:'Present simple = rotinas, hábitos, factos gerais.' },
    { id:'5io_ps_2', s:'ingles', t:'Present simple', type:'mc', diff:1,
      q:'✏️ "She ___ English every day." (study)',
      opts:['study','studys','studies','studying'], ans:2,
      exp:'study → studies na 3.ª pessoa (consoante + y → -ies).' },
    { id:'5io_ps_3', s:'ingles', t:'Present simple', type:'mc', diff:1,
      q:'✏️ "He ___ TV." (watch)',
      opts:['watch','watchs','watches','watching'], ans:2,
      exp:'Verbos terminados em -ch levam -es na 3.ª pessoa: watches.' },
    { id:'5io_ps_4', s:'ingles', t:'Present simple', type:'mc', diff:1,
      q:'✏️ "I ___ football." (play)',
      opts:['play','plays','playes','playing'], ans:0,
      exp:'1.ª pessoa (I) — verbo na forma base: play.' },
    { id:'5io_ps_5', s:'ingles', t:'Present simple', type:'mc', diff:2,
      q:'❓ Forma INTERROGATIVA: "___ you like pizza?"',
      opts:['Are','Do','Does','Is'], ans:1,
      exp:'Para "you" usa-se "Do" no Present simple: Do you like...?' },
    { id:'5io_ps_6', s:'ingles', t:'Present simple', type:'mc', diff:2,
      q:'❓ "___ she play tennis?"',
      opts:['Do','Does','Is','Are'], ans:1,
      exp:'Para 3.ª pessoa (he/she/it) usa-se "Does".' },
    { id:'5io_ps_7', s:'ingles', t:'Present simple', type:'mc', diff:2,
      q:'🚫 Forma NEGATIVA: "I ___ like coffee."',
      opts:["don't","doesn't","not","isn't"], ans:0,
      exp:"I don't like = não gosto. Para he/she/it seria doesn't." },
    { id:'5io_ps_8', s:'ingles', t:'Present simple', type:'mc', diff:2,
      q:'🚫 "She ___ play football."',
      opts:["don't","doesn't","not play","isn't play"], ans:1,
      exp:"He/she/it usa doesn't + verbo base (sem -s): doesn't play." },
    { id:'5io_ps_9', s:'ingles', t:'Present simple', type:'fill', diff:2,
      q:"✏️ Completa: My brother ___ (go) to school by bus.",
      ans:['goes'],
      exp:'go → goes na 3.ª pessoa.' },
    { id:'5io_ps_10', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:"⏰ \"She ___ never late.\" (be)",
      opts:['are','is','am','be'], ans:1,
      exp:'Verbo "to be" 3.ª pessoa singular = is.' },
    { id:'5io_ps_11', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'⏰ Onde vai o advérbio "always"? "I ___ have breakfast at 7."',
      opts:['have always','always have','have always at','at 7 always'], ans:1,
      exp:'Advérbios de frequência vão ANTES do verbo principal: I always have...' },
    { id:'5io_ps_12', s:'ingles', t:'Present simple', type:'fill', diff:3,
      q:"❓ Pergunta sobre Sofia: \"___ Sofia like chocolate?\"",
      ans:['Does'],
      exp:'3.ª pessoa singular → Does.' },
    { id:'5io_ps_13', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'🔁 Resposta curta: "Do you play tennis?" → "Yes, ___"',
      opts:['I am','I do','I does','I play'], ans:1,
      exp:'Resposta curta afirmativa com "do": Yes, I do.' },
    { id:'5io_ps_14', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'🔁 Resposta curta negativa: "Does she play piano?" → "No, ___"',
      opts:["she isn't","she doesn't","she don't","she not"], ans:1,
      exp:"3.ª pessoa negativa = doesn't. No, she doesn't." },

    // ============================================================
    // ================== PREPOSITIONS OF TIME =====================
    // ============================================================
    { id:'5io_pt_1', s:'ingles', t:'Prepositions of time', type:'mc', diff:1,
      q:'⏰ "I wake up ___ 7 o\'clock." (hora certa)',
      opts:['in','on','at','by'], ans:2,
      exp:"Horas certas usam-se com AT. AT 7 o'clock." },
    { id:'5io_pt_2', s:'ingles', t:'Prepositions of time', type:'mc', diff:1,
      q:'📅 "We have a test ___ Monday."',
      opts:['in','on','at','for'], ans:1,
      exp:'Dias da semana usam-se com ON. ON Monday.' },
    { id:'5io_pt_3', s:'ingles', t:'Prepositions of time', type:'mc', diff:1,
      q:'🗓️ "My birthday is ___ May."',
      opts:['in','on','at','from'], ans:0,
      exp:'Meses usam-se com IN. IN May.' },
    { id:'5io_pt_4', s:'ingles', t:'Prepositions of time', type:'mc', diff:1,
      q:'❄️ "It snows ___ winter."',
      opts:['in','on','at','by'], ans:0,
      exp:'Estações do ano usam-se com IN. IN winter.' },
    { id:'5io_pt_5', s:'ingles', t:'Prepositions of time', type:'mc', diff:2,
      q:'🌅 "I have breakfast ___ the morning."',
      opts:['in','on','at','by'], ans:0,
      exp:'Partes do dia (manhã, tarde) usam-se com IN. IN the morning.' },
    { id:'5io_pt_6', s:'ingles', t:'Prepositions of time', type:'mc', diff:2,
      q:'🌙 "Owls sleep ___ the day and hunt ___ night."',
      opts:['in / at','in / in','on / at','at / at'], ans:0,
      exp:'IN the day (partes do dia) MAS AT night (exceção).' },
    { id:'5io_pt_7', s:'ingles', t:'Prepositions of time', type:'mc', diff:2,
      q:'🎄 "We celebrate ___ Christmas."',
      opts:['in','on','at','by'], ans:2,
      exp:'AT Christmas (período de Natal). MAS ON Christmas Day (dia 25).' },
    { id:'5io_pt_8', s:'ingles', t:'Prepositions of time', type:'mc', diff:2,
      q:'🗓️ "I was born ___ 2015."',
      opts:['in','on','at','during'], ans:0,
      exp:'Anos usam-se com IN. IN 2015.' },
    { id:'5io_pt_9', s:'ingles', t:'Prepositions of time', type:'fill', diff:2,
      q:'⏰ Completa: "School starts ___ 8:30 am."',
      ans:['at','At'],
      exp:'Hora específica → AT.' },
    { id:'5io_pt_10', s:'ingles', t:'Prepositions of time', type:'fill', diff:2,
      q:'📅 Completa: "Her birthday is ___ 12 May."',
      ans:['on','On'],
      exp:'Data específica (dia) → ON.' },
    { id:'5io_pt_11', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'❓ Frase CORRETA:',
      opts:['I go swimming on Saturday in the afternoon.','I go swimming in Saturday in the afternoon.','I go swimming at Saturday on the afternoon.','I go swimming on Saturday on afternoon.'], ans:0,
      exp:'ON Saturday (dia) + IN the afternoon (parte do dia).' },
    { id:'5io_pt_12', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'❓ Qual está ERRADA?',
      opts:['at noon','on Tuesday','in March','at Monday'], ans:3,
      exp:'"at Monday" está errado — dias usam-se com ON: ON Monday.' },
    { id:'5io_pt_13', s:'ingles', t:'Prepositions of time', type:'fill', diff:3,
      q:'🎯 Completa com IN/ON/AT: "I have lunch ___ 12:30 ___ Mondays ___ school."',
      ans:['at on at','At on at','at On at','AT ON AT'],
      exp:'AT 12:30 (hora) ON Mondays (dias) AT school (lugar específico).' },
    { id:'5io_pt_14', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'🎉 "My family gets together ___ New Year\'s Eve."',
      opts:['in','on','at','during'], ans:1,
      exp:'ON New Year\'s Eve (dia específico).' },
    { id:'5io_pt_15', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'📚 "The library is open ___ Friday mornings."',
      opts:['in','on','at','by'], ans:1,
      exp:'Dias + parte do dia específico = ON: ON Friday mornings.' },

    // ============================================================
    // ============= EXTRA DIFICULDADE 3 (avançado) ================
    // ============================================================

    // ----- Telling the time (mais 8 d3) -----
    { id:'5io_tt_13', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'🎬 A film starts at 7:15 and lasts 1 hour and 45 minutes. What time does it end?',
      opts:['8:30','9:00','8:00','9:15'], ans:1,
      exp:'7:15 + 1h45 = 9:00. Soma 1h → 8:15; +45min → 9:00.' },
    { id:'5io_tt_14', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'⏰ 18:30 in 12-hour format with am/pm:',
      opts:['6:30 am','6:30 pm','8:30 pm','12:30 pm'], ans:1,
      exp:'18:30 = 6:30 pm. (Subtrai 12 da hora; pm porque é depois do meio-dia.)' },
    { id:'5io_tt_15', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'🕰️ "Twenty to nine" em horas digitais:',
      opts:['9:20','8:40','8:20','9:40'], ans:1,
      exp:'"Twenty to nine" = 20 min antes das 9 = 8:40.' },
    { id:'5io_tt_16', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'⏱️ A class starts at 10:25 and ends at 11:10. How long is it?',
      opts:['35 min','45 min','50 min','1 hour'], ans:1,
      exp:'10:25 → 11:10. De 10:25 a 11:00 são 35 min; +10 min até 11:10 = 45 min.' },
    { id:'5io_tt_17', s:'ingles', t:'Telling the time', type:'fill', diff:3,
      q:'🕒 Escreve em inglês (tradicional): "14:50"',
      ans:['ten to three','It\'s ten to three.','ten to three pm','10 to 3'],
      exp:'14:50 = 2:50 pm = 10 min antes das 3 → ten to three.' },
    { id:'5io_tt_18', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'🌙 "It\'s midnight." Que horas digitais?',
      opts:['00:00 / 12:00 am','12:00 pm','24:00','11:00 pm'], ans:0,
      exp:'Midnight = 00:00 ou 12:00 am (meia-noite).' },
    { id:'5io_tt_19', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'☀️ Sofia wakes up at quarter past seven. What time exactly?',
      opts:['7:15','7:45','8:15','6:45'], ans:0,
      exp:'Quarter past seven = 7:15 (15 min depois das 7).' },
    { id:'5io_tt_20', s:'ingles', t:'Telling the time', type:'mc', diff:3,
      q:'⏰ "It\'s five to twelve." Que horas?',
      opts:['12:05','11:55','11:05','12:55'], ans:1,
      exp:'5 min antes das 12 = 11:55.' },

    // ----- Daily routines (mais 8 d3) -----
    { id:'5io_dr_13', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'❓ "What time ___ you ___ up?" (perguntar a alguém)',
      opts:['do / get','does / get','are / getting','do / gets'], ans:0,
      exp:'Pergunta com "you" → "do you get up?" (sem -s).' },
    { id:'5io_dr_14', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'🚌 "She ___ to school by bus." (verbo: go, 3.ª pessoa)',
      opts:['gos','goes','goees','going'], ans:1,
      exp:'go → goes na 3.ª pessoa (irregular do +es).' },
    { id:'5io_dr_15', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'🍽️ Escolhe a frase CORRETA:',
      opts:['He never eat vegetables.','He never eats vegetables.','He eats never vegetables.','He doesn\'t never eat vegetables.'], ans:1,
      exp:'"Never" é negativo por si só. Vai ANTES do verbo + verbo na forma normal (3.ª pessoa com -s).' },
    { id:'5io_dr_16', s:'ingles', t:'Daily routines', type:'fill', diff:3,
      q:'⏰ Completa: She ___ (not / wake) up early on Sundays.',
      ans:['doesn\'t wake','does not wake'],
      exp:'Negativa 3.ª pessoa = doesn\'t + verbo base (wake, não wakes).' },
    { id:'5io_dr_17', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'📖 "I ___ a book before sleep." (verbo: read)',
      opts:['reading','read','reads','am read'], ans:1,
      exp:'1.ª pessoa (I) → verbo na forma base: read.' },
    { id:'5io_dr_18', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'❓ Resposta a "What time do you have breakfast?":',
      opts:['Yes, I do.','I have breakfast at 7:30.','I am breakfast.','Breakfast is good.'], ans:1,
      exp:'Pergunta com "what time" pede uma hora — responde com "at + hora".' },
    { id:'5io_dr_19', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'🛁 Qual é mais frequente: always > usually > often > sometimes > rarely > never. "Carolina ___ takes a shower in the morning" (quase sempre):',
      opts:['never','rarely','sometimes','usually'], ans:3,
      exp:'"Usually" = geralmente, quase sempre — alta frequência.' },
    { id:'5io_dr_20', s:'ingles', t:'Daily routines', type:'mc', diff:3,
      q:'📚 Ordena: home / homework / I / do / my',
      opts:['I do my homework home.','I do home my homework.','I do my homework at home.','Home my I homework do.'], ans:2,
      exp:'Ordem natural: Sujeito + verbo + objeto + lugar. "I do my homework at home."' },

    // ----- Jobs (mais 8 d3) -----
    { id:'5io_jo_14', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'⚖️ "Lawyer" é:',
      opts:['Médico','Advogado/a','Juiz/a','Professor/a'], ans:1,
      exp:'lawyer = advogado/a. (judge = juiz.)' },
    { id:'5io_jo_15', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'🔬 "Scientist" é:',
      opts:['Cientista','Cirurgião','Pesquisador (jornalista)','Aluno'], ans:0,
      exp:'scientist = cientista (de "science" = ciência).' },
    { id:'5io_jo_16', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'✂️ "Hairdresser" é:',
      opts:['Costureiro/a','Cabeleireiro/a','Barbeiro/a só (homens)','Estilista de moda'], ans:1,
      exp:'hairdresser = cabeleireiro/a (corta cabelo de homens e mulheres).' },
    { id:'5io_jo_17', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'🛠️ "A mechanic works at a ___."',
      opts:['hospital','garage','bakery','farm'], ans:1,
      exp:'mechanic = mecânico; trabalha numa garage (oficina).' },
    { id:'5io_jo_18', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'🎨 Escolhe a frase CORRETA:',
      opts:['She is an actor.','She is a actor.','She is an actress.','Ambas A e C estão corretas.'], ans:3,
      exp:'Em inglês moderno "actor" é usado para ambos os géneros. Mas "actress" ainda é válido. "An" antes de vogal.' },
    { id:'5io_jo_19', s:'ingles', t:'Jobs', type:'fill', diff:3,
      q:'👨‍🍳 Completa: A chef ___ (cook) delicious food.',
      ans:['cooks'],
      exp:'3.ª pessoa singular (a chef) → cooks.' },
    { id:'5io_jo_20', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'❓ Pergunta apropriada: "___ does your mum work?"',
      opts:['What','Where','How','Why'], ans:1,
      exp:'Para pedir LUGAR de trabalho → Where does your mum work?' },
    { id:'5io_jo_21', s:'ingles', t:'Jobs', type:'mc', diff:3,
      q:'👨‍🚒 "Firefighters help people in case of ___."',
      opts:['rain','fires','accidents only','homework'], ans:1,
      exp:'firefighter (bombeiro) ajuda em fogos/incêndios. (fire = fogo)' },

    // ----- Present simple (mais 7 d3) -----
    { id:'5io_ps_15', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'🌍 "The sun ___ in the east." (rise)',
      opts:['rise','rises','rising','is rise'], ans:1,
      exp:'Facto científico — Present simple. Sun (3.ª pessoa) → rises.' },
    { id:'5io_ps_16', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'❓ "Where ___ your sister live?"',
      opts:['do','does','is','are'], ans:1,
      exp:'3.ª pessoa singular (your sister) → Does.' },
    { id:'5io_ps_17', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'🚫 Forma negativa: "We ___ live in Lisbon."',
      opts:['don\'t','doesn\'t','aren\'t','isn\'t'], ans:0,
      exp:'"We" (plural) → don\'t.' },
    { id:'5io_ps_18', s:'ingles', t:'Present simple', type:'fill', diff:3,
      q:'✏️ "Mia ___ (fly) to Paris every summer." Forma na 3.ª pessoa:',
      ans:['flies'],
      exp:'fly termina em consoante + y → -ies: flies.' },
    { id:'5io_ps_19', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'🎓 "He has homework every day." → forma negativa:',
      opts:['He has no homework every day.','He doesn\'t have homework every day.','He hasn\'t homework every day.','He don\'t has homework.'], ans:1,
      exp:'"have" no Present simple negativo 3.ª pessoa = doesn\'t have.' },
    { id:'5io_ps_20', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'❓ "Does your dog like cats?" Resposta curta negativa:',
      opts:['No, it doesn\'t.','No, it don\'t.','No, it isn\'t.','No, doesn\'t it.'], ans:0,
      exp:'Resposta curta negativa para 3.ª pessoa singular = "No, [sujeito] doesn\'t."' },
    { id:'5io_ps_21', s:'ingles', t:'Present simple', type:'mc', diff:3,
      q:'🎯 Escolhe a frase com TODOS os elementos corretos:',
      opts:['He always go to school at 8.','He goes always to school at 8.','He always goes to school at 8.','Always he goes to school at 8.'], ans:2,
      exp:'Sujeito + advérbio de frequência + verbo (3.ª pessoa -s) + complemento.' },

    // ----- Prepositions of time (mais 7 d3) -----
    { id:'5io_pt_16', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'🎂 "We have a party ___ my birthday."',
      opts:['in','on','at','during'], ans:1,
      exp:'ON my birthday (dia específico).' },
    { id:'5io_pt_17', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'⏰ "The shop opens ___ 9 am and closes ___ 7 pm."',
      opts:['in / in','on / on','at / at','at / on'], ans:2,
      exp:'Horas específicas → AT. AT 9 am e AT 7 pm.' },
    { id:'5io_pt_18', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'🍂 "I love going to the beach ___ summer ___ August."',
      opts:['on / in','in / in','at / in','in / on'], ans:1,
      exp:'IN summer (estação) + IN August (mês).' },
    { id:'5io_pt_19', s:'ingles', t:'Prepositions of time', type:'fill', diff:3,
      q:'🎯 Completa com IN/ON/AT: "The wedding is ___ 15 June ___ noon."',
      ans:['on at','On at','On At'],
      exp:'ON 15 June (data) + AT noon (momento específico).' },
    { id:'5io_pt_20', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'🌃 Qual é a EXCEÇÃO?',
      opts:['in the morning','in the afternoon','in the evening','at night'], ans:3,
      exp:'AT night é a exceção (não "in the night"). Outras partes do dia usam IN.' },
    { id:'5io_pt_21', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'📅 Qual está ERRADA?',
      opts:['in 2024','on Tuesday','at 5 pm','in 25 December'], ans:3,
      exp:'"in 25 December" está errado — datas usam ON: ON 25 December.' },
    { id:'5io_pt_22', s:'ingles', t:'Prepositions of time', type:'mc', diff:3,
      q:'🏖️ "School is closed ___ the summer holidays."',
      opts:['in','on','at','for'], ans:0,
      exp:'IN the summer (estação/período).' }

];

if (typeof window !== 'undefined') window.EXERCISES_5_I_ORIENT = EXERCISES_5_I_ORIENT;
