// EscolaPlay - Top-up extra do 2.º ano - Português (gerado, AE 2018)
// PT-PT, Acordo Ortográfico de 1990. Vocabulário do 1.º ciclo.
const EXERCISES_2_P_EXTRA2 = [

    // ----- Vogais e consoantes (40) -----
    { id:'2pe1', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🍌 Quantas vogais tem a palavra "bola"?',
      opts:['1','2','3','4'], ans:1,
      exp:'bola → "o" e "a" → 2 vogais.' },
    { id:'2pe2', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:2,
      q:'🐟 Qual é a primeira vogal da palavra "elefante"?',
      opts:['e','l','f','a'], ans:0,
      exp:'elefante começa com a vogal "e".' },
    { id:'2pe3', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 A letra "a" é uma vogal.',
      ans:true,
      exp:'As vogais são a, e, i, o, u.' },
    { id:'2pe4', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 A letra "m" é uma vogal.',
      ans:false,
      exp:'O "m" é uma consoante.' },
    { id:'2pe5', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐟 Quantas vogais tem a palavra "peixe"?',
      opts:['1','2','3','4'], ans:1,
      exp:'peixe → "e" e "e" → 2 vogais (incluindo o ditongo "ei").' },
    { id:'2pe6', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'☀️ Escreve as vogais da palavra "sol".',
      ans:['o'],
      exp:'sol → só tem a vogal "o".' },
    { id:'2pe7', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🌳 Quantas consoantes tem a palavra "rua"?',
      opts:['0','1','2','3'], ans:1,
      exp:'rua → só "r" é consoante.' },
    { id:'2pe8', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐶 Qual é a vogal da palavra "cão"?',
      opts:['c','ã','o','ão'], ans:3,
      exp:'cão → as vogais são "ã" e "o".' },
    { id:'2pe9', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 A letra "i" é uma vogal.',
      ans:true,
      exp:'As vogais são a, e, i, o, u.' },
    { id:'2pe10', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 A letra "p" é uma consoante.',
      ans:true,
      exp:'O "p" é uma consoante.' },
    { id:'2pe11', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🍎 Quantas vogais tem "uva"?',
      opts:['1','2','3','0'], ans:1,
      exp:'uva → "u" e "a" → 2 vogais.' },
    { id:'2pe12', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'🐱 Escreve as vogais da palavra "pato".',
      ans:['ao','a o','a,o'],
      exp:'pato → vogais "a" e "o".' },
    { id:'2pe13', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🦋 Quantas vogais tem a palavra "borboleta"?',
      opts:['2','3','4','5'], ans:2,
      exp:'borboleta → o, o, e, a → 4 vogais.' },
    { id:'2pe14', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐠 Qual destas letras é uma vogal?',
      opts:['b','d','o','t'], ans:2,
      exp:'O "o" é uma vogal.' },
    { id:'2pe15', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐔 Qual destas letras é uma consoante?',
      opts:['a','e','f','i'], ans:2,
      exp:'O "f" é uma consoante.' },
    { id:'2pe16', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🌻 Quantas vogais tem a palavra "flor"?',
      opts:['0','1','2','3'], ans:1,
      exp:'flor → só "o" é vogal.' },
    { id:'2pe17', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'🌙 Escreve as vogais de "lua".',
      ans:['ua','u a','u,a'],
      exp:'lua → vogais "u" e "a".' },
    { id:'2pe18', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'📚 Quantas consoantes tem a palavra "livro"?',
      opts:['1','2','3','4'], ans:2,
      exp:'livro → l, v, r → 3 consoantes.' },
    { id:'2pe19', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 A letra "u" é uma vogal.',
      ans:true,
      exp:'As vogais são a, e, i, o, u.' },
    { id:'2pe20', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐟 Qual destas palavras só tem vogais?',
      opts:['ui','sol','mar','pão'], ans:0,
      exp:'ui → só tem vogais.' },
    { id:'2pe21', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🌈 Quantas vogais tem "arco-íris"?',
      opts:['2','3','4','5'], ans:2,
      exp:'arco-íris → a, o, í, i → 4 vogais.' },
    { id:'2pe22', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'🐝 Escreve as vogais de "abelha".',
      ans:['aea','a e a','a,e,a'],
      exp:'abelha → a, e, a.' },
    { id:'2pe23', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐰 Quantas vogais tem "rato"?',
      opts:['1','2','3','4'], ans:1,
      exp:'rato → "a" e "o" → 2 vogais.' },
    { id:'2pe24', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:2,
      q:'🌟 Qual destas palavras tem mais vogais?',
      opts:['mar','sol','rua','pé'], ans:2,
      exp:'rua → "u" e "a" → 2 vogais (mais do que as outras).' },
    { id:'2pe25', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🎈 Qual destas letras é vogal?',
      opts:['s','m','e','r'], ans:2,
      exp:'O "e" é uma vogal.' },
    { id:'2pe26', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 A letra "o" é uma consoante.',
      ans:false,
      exp:'O "o" é uma vogal.' },
    { id:'2pe27', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🍰 Quantas vogais tem a palavra "bolo"?',
      opts:['1','2','3','4'], ans:1,
      exp:'bolo → "o" e "o" → 2 vogais.' },
    { id:'2pe28', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'🐶 Quantas consoantes tem "rato"? ___',
      ans:['2','duas','dois'],
      exp:'rato → r, t → 2 consoantes.' },
    { id:'2pe29', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🎀 Qual destas letras é consoante?',
      opts:['a','e','n','i'], ans:2,
      exp:'O "n" é uma consoante.' },
    { id:'2pe30', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:2,
      q:'🏠 Qual é a primeira consoante da palavra "casa"?',
      opts:['a','c','s','o'], ans:1,
      exp:'casa → começa com "c", que é consoante.' },
    { id:'2pe31', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'🔤 No alfabeto português há 5 vogais.',
      ans:true,
      exp:'As 5 vogais são a, e, i, o, u.' },
    { id:'2pe32', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🌊 Quantas consoantes tem "praia"?',
      opts:['1','2','3','4'], ans:1,
      exp:'praia → p, r → 2 consoantes.' },
    { id:'2pe33', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🐝 Quantas vogais tem "mel"?',
      opts:['1','2','3','0'], ans:0,
      exp:'mel → só "e" é vogal.' },
    { id:'2pe34', s:'portugues', t:'Vogais e consoantes', type:'fill', diff:1,
      q:'🦒 Escreve as vogais da palavra "girafa".',
      ans:['iaa','i a a','i,a,a'],
      exp:'girafa → i, a, a.' },
    { id:'2pe35', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🎵 Qual destas palavras tem 2 vogais?',
      opts:['sol','pé','mar','rio'], ans:3,
      exp:'rio → "i" e "o" → 2 vogais.' },
    { id:'2pe36', s:'portugues', t:'Vogais e consoantes', type:'match', diff:1,
      q:'Liga cada letra ao seu tipo.',
      pairs:[['a','vogal'],['b','consoante'],['e','vogal'],['t','consoante']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'a, e são vogais; b, t são consoantes.' },
    { id:'2pe37', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:2,
      q:'🐔 Qual destas palavras começa por vogal?',
      opts:['gato','árvore','pato','sapo'], ans:1,
      exp:'árvore começa com "á", que é vogal.' },
    { id:'2pe38', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:2,
      q:'🌷 Qual destas palavras começa por consoante?',
      opts:['ovo','urso','mesa','elefante'], ans:2,
      exp:'mesa começa com "m", que é consoante.' },
    { id:'2pe39', s:'portugues', t:'Vogais e consoantes', type:'tf', diff:1,
      q:'A palavra "ar" só tem vogais.',
      ans:false,
      exp:'ar tem "a" (vogal) e "r" (consoante).' },
    { id:'2pe40', s:'portugues', t:'Vogais e consoantes', type:'mc', diff:1,
      q:'🍇 Quantas vogais diferentes tem "amigo"?',
      opts:['2','3','4','1'], ans:1,
      exp:'amigo → a, i, o → 3 vogais diferentes.' },

    // ----- Sílabas (38) -----
    { id:'2pe41', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐝 Quantas sílabas tem "mel"?',
      ans:['1','um','uma'],
      exp:'mel = 1 sílaba.' },
    { id:'2pe42', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🏠 Quantas sílabas tem "casa"?',
      ans:['2','dois','duas'],
      exp:'ca-sa = 2 sílabas.' },
    { id:'2pe43', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐔 Como se divide "pato" em sílabas?',
      opts:['pa-to','p-ato','pat-o','p-a-to'], ans:0,
      exp:'pa-to → 2 sílabas.' },
    { id:'2pe44', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🌳 Como se divide "árvore"?',
      opts:['ár-vo-re','ar-vore','árvo-re','á-rv-ore'], ans:0,
      exp:'ár-vo-re → 3 sílabas.' },
    { id:'2pe45', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🌞 Quantas sílabas tem "menino"?',
      ans:['3','três','tres'],
      exp:'me-ni-no = 3 sílabas.' },
    { id:'2pe46', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐶 Como se divide "cachorro"?',
      opts:['ca-cho-rro','cach-or-ro','ca-chor-ro','cac-ho-rro'], ans:2,
      exp:'ca-chor-ro → 3 sílabas.' },
    { id:'2pe47', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🎈 Quantas sílabas tem "bola"?',
      ans:['2','dois','duas'],
      exp:'bo-la = 2 sílabas.' },
    { id:'2pe49', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐘 Quantas sílabas tem "elefante"?',
      ans:['4','quatro'],
      exp:'e-le-fan-te = 4 sílabas.' },
    { id:'2pe50', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🍐 Quantas sílabas tem "pera"?',
      opts:['1','2','3','4'], ans:1,
      exp:'pe-ra = 2 sílabas.' },
    { id:'2pe51', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'☁️ Quantas sílabas tem "céu"?',
      ans:['1','um','uma'],
      exp:'céu = 1 sílaba.' },
    { id:'2pe52', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🍎 Quantas sílabas tem "maçã"?',
      opts:['1','2','3','4'], ans:1,
      exp:'ma-çã = 2 sílabas.' },
    { id:'2pe53', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🦁 Como se divide "cachorrinho"?',
      opts:['ca-chor-ri-nho','cachor-ri-nho','ca-cho-rri-nho','ca-chorr-i-nho'], ans:0,
      exp:'ca-chor-ri-nho → 4 sílabas.' },
    { id:'2pe54', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐭 Quantas sílabas tem "rato"?',
      ans:['2','dois','duas'],
      exp:'ra-to = 2 sílabas.' },
    { id:'2pe55', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🪑 Quantas sílabas tem "mesa"?',
      opts:['1','2','3','4'], ans:1,
      exp:'me-sa = 2 sílabas.' },
    { id:'2pe56', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🌷 Como se divide "tulipa"?',
      opts:['tu-li-pa','tul-i-pa','tu-lip-a','t-uli-pa'], ans:0,
      exp:'tu-li-pa → 3 sílabas.' },
    { id:'2pe58', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐟 Como se divide "peixinho"?',
      opts:['pei-xi-nho','peix-i-nho','pe-ixi-nho','pei-xin-ho'], ans:0,
      exp:'pei-xi-nho → 3 sílabas.' },
    { id:'2pe59', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🌸 Quantas sílabas tem "florista"?',
      ans:['3','três','tres'],
      exp:'flo-ris-ta = 3 sílabas.' },
    { id:'2pe60', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🎨 Quantas sílabas tem "lápis"?',
      opts:['1','2','3','4'], ans:1,
      exp:'lá-pis = 2 sílabas.' },
    { id:'2pe61', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'☔ Quantas sílabas tem "chuva"?',
      opts:['1','2','3','4'], ans:1,
      exp:'chu-va = 2 sílabas.' },
    { id:'2pe62', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🍞 Quantas sílabas tem "pão"?',
      ans:['1','um','uma'],
      exp:'pão = 1 sílaba.' },
    { id:'2pe63', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐢 Como se divide "tartaruga"?',
      opts:['tar-ta-ru-ga','tart-aru-ga','ta-rta-ru-ga','tar-tar-uga'], ans:0,
      exp:'tar-ta-ru-ga → 4 sílabas.' },
    { id:'2pe64', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'☀️ Quantas sílabas tem "dia"?',
      ans:['2','dois','duas'],
      exp:'di-a = 2 sílabas.' },
    { id:'2pe65', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🌙 Quantas sílabas tem "noite"?',
      opts:['1','2','3','4'], ans:1,
      exp:'noi-te = 2 sílabas.' },
    { id:'2pe66', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐝 Como se divide "abelhinha"?',
      opts:['a-be-lhi-nha','ab-el-hi-nha','a-bel-hi-nha','abe-lhi-nha'], ans:0,
      exp:'a-be-lhi-nha → 4 sílabas.' },
    { id:'2pe67', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐠 Quantas sílabas tem "água"?',
      ans:['2','dois','duas'],
      exp:'á-gua = 2 sílabas.' },
    { id:'2pe68', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🎂 Quantas sílabas tem "bolo"?',
      opts:['1','2','3','4'], ans:1,
      exp:'bo-lo = 2 sílabas.' },
    { id:'2pe69', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐘 Como se divide "elefante"?',
      opts:['e-le-fan-te','ele-fan-te','e-lef-an-te','el-e-fa-nte'], ans:0,
      exp:'e-le-fan-te → 4 sílabas.' },
    { id:'2pe70', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐎 Quantas sílabas tem "cavalo"?',
      ans:['3','três','tres'],
      exp:'ca-va-lo = 3 sílabas.' },
    { id:'2pe71', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🍓 Quantas sílabas tem "morango"?',
      opts:['2','3','4','5'], ans:1,
      exp:'mo-ran-go = 3 sílabas.' },
    { id:'2pe72', s:'portugues', t:'Sílabas', type:'tf', diff:1,
      q:'A palavra "mar" tem 1 sílaba.',
      ans:true,
      exp:'mar = 1 sílaba.' },
    { id:'2pe73', s:'portugues', t:'Sílabas', type:'tf', diff:1,
      q:'A palavra "menina" tem 2 sílabas.',
      ans:false,
      exp:'me-ni-na = 3 sílabas.' },
    { id:'2pe74', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🦒 Como se divide "girafa"?',
      opts:['gi-ra-fa','gir-afa','gi-raf-a','g-ira-fa'], ans:0,
      exp:'gi-ra-fa → 3 sílabas.' },
    { id:'2pe75', s:'portugues', t:'Sílabas', type:'fill', diff:1,
      q:'🐠 Quantas sílabas tem "passarinho"?',
      ans:['4','quatro'],
      exp:'pas-sa-ri-nho = 4 sílabas.' },
    { id:'2pe76', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'⚽ Quantas sílabas tem "bola"?',
      opts:['1','2','3','4'], ans:1,
      exp:'bo-la = 2 sílabas.' },
    { id:'2pe77', s:'portugues', t:'Sílabas', type:'order', diff:2,
      q:'Ordena as sílabas para formar a palavra "borboleta".',
      items:['bor','bo','le','ta'],
      ans:'1,2,3,4',
      exp:'bor-bo-le-ta → 4 sílabas pela ordem indicada.' },
    { id:'2pe78', s:'portugues', t:'Sílabas', type:'mc', diff:1,
      q:'🐦 Quantas sílabas tem "ave"?',
      opts:['1','2','3','4'], ans:1,
      exp:'a-ve = 2 sílabas.' },

    // ----- Ditongos (39) -----
    { id:'2pe79', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐂 Qual é o ditongo da palavra "boi"?',
      opts:['bo','oi','bi','io'], ans:1,
      exp:'boi → ditongo "oi".' },
    { id:'2pe80', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'👨 Qual é o ditongo da palavra "pai"?',
      opts:['pa','ai','pi','pa-i'], ans:1,
      exp:'pai → ditongo "ai".' },
    { id:'2pe81', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'A palavra "rei" tem um ditongo.',
      ans:true,
      exp:'rei → "ei" é um ditongo.' },
    { id:'2pe82', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'A palavra "casa" tem um ditongo.',
      ans:false,
      exp:'casa não tem duas vogais juntas.' },
    { id:'2pe83', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐦 Qual destas palavras tem o ditongo "ai"?',
      opts:['mãe','pai','sol','rei'], ans:1,
      exp:'pai → ditongo "ai".' },
    { id:'2pe85', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'👑 Escreve o ditongo da palavra "rei".',
      ans:['ei'],
      exp:'rei → ditongo "ei".' },
    { id:'2pe86', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'🐂 Escreve o ditongo da palavra "boi".',
      ans:['oi'],
      exp:'boi → ditongo "oi".' },
    { id:'2pe87', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌧️ Qual destas palavras tem um ditongo?',
      opts:['noite','sol','casa','flor'], ans:0,
      exp:'noite → "oi" é ditongo.' },
    { id:'2pe88', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🦁 Qual é o ditongo da palavra "leão"?',
      opts:['le','ão','eo','la'], ans:1,
      exp:'leão → ditongo "ão".' },
    { id:'2pe89', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐎 Qual destas palavras tem ditongo?',
      opts:['cavalo','mãe','livro','sol'], ans:1,
      exp:'mãe → "ãe" é um ditongo nasal.' },
    { id:'2pe90', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'A palavra "lua" tem um ditongo.',
      ans:false,
      exp:'lu-a → as vogais estão em sílabas diferentes.' },
    { id:'2pe91', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌳 Qual é o ditongo da palavra "couve"?',
      opts:['co','ou','uv','ve'], ans:1,
      exp:'couve → ditongo "ou".' },
    { id:'2pe92', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'🐂 Escreve o ditongo da palavra "mau".',
      ans:['au'],
      exp:'mau → ditongo "au".' },
    { id:'2pe93', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐈 Qual destas palavras tem o ditongo "ui"?',
      opts:['fui','sol','mãe','dia'], ans:0,
      exp:'fui → ditongo "ui".' },
    { id:'2pe94', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'👵 Qual destas palavras tem um ditongo nasal?',
      opts:['avó','pão','sol','mar'], ans:1,
      exp:'pão → "ão" é ditongo nasal.' },
    { id:'2pe95', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌽 Qual é o ditongo da palavra "saudade"?',
      opts:['sa','au','ud','de'], ans:1,
      exp:'saudade → ditongo "au".' },
    { id:'2pe96', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'O ditongo "ão" é nasal.',
      ans:true,
      exp:'"ão" é um ditongo nasal (tem som de nariz).' },
    { id:'2pe97', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌟 Qual é o ditongo da palavra "põe"?',
      opts:['oe','õe','po','pe'], ans:1,
      exp:'põe → ditongo nasal "õe".' },
    { id:'2pe98', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'🌳 Escreve o ditongo de "anão".',
      ans:['ão','ao'],
      exp:'anão → ditongo "ão".' },
    { id:'2pe99', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐝 Qual destas palavras NÃO tem ditongo?',
      opts:['pai','rei','sol','boi'], ans:2,
      exp:'sol não tem ditongo.' },
    { id:'2pe100', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐦 Qual destas palavras tem o ditongo "ei"?',
      opts:['rei','sol','casa','lua'], ans:0,
      exp:'rei → ditongo "ei".' },
    { id:'2pe101', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🍞 Qual é o ditongo da palavra "pão"?',
      opts:['pa','ão','po','an'], ans:1,
      exp:'pão → ditongo "ão".' },
    { id:'2pe102', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'👶 Escreve o ditongo de "mãe".',
      ans:['ãe','ae'],
      exp:'mãe → ditongo nasal "ãe".' },
    { id:'2pe103', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌅 Qual é o ditongo da palavra "azeite"?',
      opts:['az','ei','it','te'], ans:1,
      exp:'azeite → ditongo "ei".' },
    { id:'2pe104', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'A palavra "noite" tem o ditongo "oi".',
      ans:true,
      exp:'noite → "oi" é um ditongo.' },
    { id:'2pe105', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'A palavra "rua" tem um ditongo.',
      ans:false,
      exp:'ru-a → as vogais estão em sílabas diferentes.' },
    { id:'2pe106', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐠 Qual é o ditongo da palavra "peixe"?',
      opts:['pe','ei','ix','xe'], ans:1,
      exp:'peixe → ditongo "ei".' },
    { id:'2pe107', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐢 Qual destas palavras tem ditongo nasal?',
      opts:['boi','mãe','pai','rei'], ans:1,
      exp:'mãe → "ãe" é ditongo nasal.' },
    { id:'2pe108', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🍇 Qual destas palavras tem o ditongo "au"?',
      opts:['mau','rei','noite','pão'], ans:0,
      exp:'mau → ditongo "au".' },
    { id:'2pe109', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'☔ Escreve o ditongo de "céu".',
      ans:['éu','eu'],
      exp:'céu → ditongo "éu".' },
    { id:'2pe110', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐢 Qual é o ditongo da palavra "viu"?',
      opts:['vi','iu','ui','vu'], ans:1,
      exp:'viu → ditongo "iu".' },
    { id:'2pe111', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐢 Qual destas palavras tem o ditongo "ou"?',
      opts:['couve','mãe','rei','boi'], ans:0,
      exp:'couve → ditongo "ou".' },
    { id:'2pe112', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'O ditongo "ai" é oral.',
      ans:true,
      exp:'"ai" é um ditongo oral (não nasal).' },
    { id:'2pe113', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🦁 Qual destas palavras tem o ditongo "ão"?',
      opts:['mão','sol','rei','boi'], ans:0,
      exp:'mão → ditongo "ão".' },
    { id:'2pe114', s:'portugues', t:'Ditongos', type:'fill', diff:1,
      q:'🐦 Escreve o ditongo de "pai".',
      ans:['ai'],
      exp:'pai → ditongo "ai".' },
    { id:'2pe115', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🌸 Qual é o ditongo da palavra "lições"?',
      opts:['li','ões','çõe','oi'], ans:1,
      exp:'lições → ditongo nasal "ões".' },
    { id:'2pe116', s:'portugues', t:'Ditongos', type:'mc', diff:2,
      q:'🐠 Qual destas palavras tem ditongo?',
      opts:['gato','pato','jaula','rato'], ans:2,
      exp:'jaula → "au" é ditongo.' },
    { id:'2pe117', s:'portugues', t:'Ditongos', type:'tf', diff:1,
      q:'A palavra "saudade" tem o ditongo "au".',
      ans:true,
      exp:'saudade → "au" é ditongo.' },

    // ----- Sinónimos (36) -----
    { id:'2pe118', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌟 Qual é o sinónimo de "lindo"?',
      opts:['feio','bonito','triste','grande'], ans:1,
      exp:'lindo = bonito.' },
    { id:'2pe119', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🐘 Qual é o sinónimo de "grande"?',
      opts:['pequeno','enorme','baixo','curto'], ans:1,
      exp:'grande = enorme.' },
    { id:'2pe120', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🗣️ Qual é o sinónimo de "falar"?',
      opts:['ouvir','conversar','calar','dormir'], ans:1,
      exp:'falar = conversar.' },
    { id:'2pe121', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'😀 Qual é o sinónimo de "alegre"?',
      opts:['triste','feliz','zangado','cansado'], ans:1,
      exp:'alegre = feliz.' },
    { id:'2pe122', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'😡 Sinónimo de "zangado": ___',
      ans:['irritado','furioso'],
      exp:'zangado = irritado.' },
    { id:'2pe123', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🚗 Qual é o sinónimo de "carro"?',
      opts:['mota','automóvel','bicicleta','barco'], ans:1,
      exp:'carro = automóvel.' },
    { id:'2pe124', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🍽️ Qual é o sinónimo de "comer"?',
      opts:['beber','alimentar-se','dormir','correr'], ans:1,
      exp:'comer = alimentar-se.' },
    { id:'2pe125', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'😱 Qual é o sinónimo de "assustado"?',
      opts:['feliz','medroso','calmo','rápido'], ans:1,
      exp:'assustado = medroso.' },
    { id:'2pe126', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🏃 Sinónimo de "começar": ___',
      ans:['iniciar','principiar'],
      exp:'começar = iniciar.' },
    { id:'2pe127', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'😂 Qual é o sinónimo de "rir"?',
      opts:['chorar','gargalhar','dormir','correr'], ans:1,
      exp:'rir = gargalhar.' },
    { id:'2pe128', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌻 Qual é o sinónimo de "florir"?',
      opts:['murchar','desabrochar','plantar','colher'], ans:1,
      exp:'florir = desabrochar.' },
    { id:'2pe129', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🎈 Qual é o sinónimo de "leve"?',
      opts:['pesado','fraco','ligeiro','grande'], ans:2,
      exp:'leve = ligeiro.' },
    { id:'2pe130', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🚪 Sinónimo de "terminar": ___',
      ans:['acabar','finalizar','concluir'],
      exp:'terminar = acabar = finalizar.' },
    { id:'2pe131', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🐶 Qual é o sinónimo de "perto"?',
      opts:['longe','próximo','alto','baixo'], ans:1,
      exp:'perto = próximo.' },
    { id:'2pe132', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🐱 Qual é o sinónimo de "pequeno"?',
      opts:['grande','minúsculo','alto','enorme'], ans:1,
      exp:'pequeno = minúsculo.' },
    { id:'2pe133', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'😀 Sinónimo de "feliz": ___',
      ans:['alegre','contente'],
      exp:'feliz = alegre = contente.' },
    { id:'2pe134', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌧️ Qual é o sinónimo de "molhado"?',
      opts:['seco','húmido','frio','quente'], ans:1,
      exp:'molhado = húmido.' },
    { id:'2pe135', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🛏️ Qual é o sinónimo de "deitar"?',
      opts:['levantar','sentar','dormir','descansar'], ans:3,
      exp:'deitar (deitar-se) ≈ descansar.' },
    { id:'2pe136', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'😢 Qual é o sinónimo de "chorar"?',
      opts:['rir','soluçar','correr','dormir'], ans:1,
      exp:'chorar = soluçar.' },
    { id:'2pe137', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🦁 Sinónimo de "valente": ___',
      ans:['corajoso','bravo'],
      exp:'valente = corajoso = bravo.' },
    { id:'2pe138', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'📚 Qual é o sinónimo de "estudar"?',
      opts:['brincar','aprender','dormir','correr'], ans:1,
      exp:'estudar ≈ aprender.' },
    { id:'2pe139', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🎁 Qual é o sinónimo de "oferta"?',
      opts:['venda','presente','compra','troca'], ans:1,
      exp:'oferta = presente.' },
    { id:'2pe140', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌳 Qual é o sinónimo de "antigo"?',
      opts:['novo','velho','jovem','grande'], ans:1,
      exp:'antigo = velho.' },
    { id:'2pe141', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🏠 Sinónimo de "casa": ___',
      ans:['lar','moradia','habitação'],
      exp:'casa = lar = moradia.' },
    { id:'2pe142', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🐎 Qual é o sinónimo de "correr"?',
      opts:['andar','disparar','sentar','dormir'], ans:1,
      exp:'correr ≈ disparar.' },
    { id:'2pe143', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🍰 Qual é o sinónimo de "doce"?',
      opts:['amargo','açucarado','salgado','azedo'], ans:1,
      exp:'doce = açucarado.' },
    { id:'2pe144', s:'portugues', t:'Sinónimos', type:'match', diff:1,
      q:'Liga cada palavra ao seu sinónimo.',
      pairs:[['bonito','lindo'],['grande','enorme'],['feliz','alegre'],['rápido','veloz']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'bonito=lindo, grande=enorme, feliz=alegre, rápido=veloz.' },
    { id:'2pe145', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌅 Qual é o sinónimo de "começo"?',
      opts:['fim','início','meio','dia'], ans:1,
      exp:'começo = início.' },
    { id:'2pe146', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🍎 Qual é o sinónimo de "saudável"?',
      opts:['doente','sadio','triste','grande'], ans:1,
      exp:'saudável = sadio.' },
    { id:'2pe147', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🏃 Sinónimo de "rápido": ___',
      ans:['veloz','ligeiro'],
      exp:'rápido = veloz.' },
    { id:'2pe148', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🎒 Qual é o sinónimo de "ajudar"?',
      opts:['atrapalhar','auxiliar','correr','dormir'], ans:1,
      exp:'ajudar = auxiliar.' },
    { id:'2pe149', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌧️ Qual é o sinónimo de "chuva"?',
      opts:['neve','aguaceiro','vento','sol'], ans:1,
      exp:'chuva = aguaceiro.' },
    { id:'2pe150', s:'portugues', t:'Sinónimos', type:'tf', diff:1,
      q:'"Bonito" e "lindo" são sinónimos.',
      ans:true,
      exp:'Sim, têm o mesmo significado.' },
    { id:'2pe151', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🌟 Qual é o sinónimo de "estrela"?',
      opts:['lua','astro','sol','planeta'], ans:1,
      exp:'estrela = astro.' },
    { id:'2pe152', s:'portugues', t:'Sinónimos', type:'fill', diff:1,
      q:'🐘 Sinónimo de "enorme": ___',
      ans:['grande','gigante','imenso'],
      exp:'enorme = grande = gigante.' },
    { id:'2pe153', s:'portugues', t:'Sinónimos', type:'mc', diff:2,
      q:'🎵 Qual é o sinónimo de "cantar"?',
      opts:['gritar','entoar','correr','dormir'], ans:1,
      exp:'cantar ≈ entoar.' },

    // ----- Antónimos (36) -----
    { id:'2pe154', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'⬆️ Qual é o antónimo de "alto"?',
      opts:['grande','baixo','forte','rápido'], ans:1,
      exp:'alto ≠ baixo.' },
    { id:'2pe155', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'❄️ Qual é o antónimo de "frio"?',
      opts:['fresco','quente','gelado','húmido'], ans:1,
      exp:'frio ≠ quente.' },
    { id:'2pe156', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'😄 Qual é o antónimo de "alegre"?',
      opts:['feliz','triste','contente','rir'], ans:1,
      exp:'alegre ≠ triste.' },
    { id:'2pe157', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'☀️ Antónimo de "noite": ___',
      ans:['dia'],
      exp:'noite ≠ dia.' },
    { id:'2pe158', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🐢 Qual é o antónimo de "lento"?',
      opts:['veloz','rápido','calmo','grande'], ans:1,
      exp:'lento ≠ rápido.' },
    { id:'2pe159', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🍞 Qual é o antónimo de "duro"?',
      opts:['mole','grande','rijo','forte'], ans:0,
      exp:'duro ≠ mole.' },
    { id:'2pe160', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🌊 Antónimo de "molhado": ___',
      ans:['seco'],
      exp:'molhado ≠ seco.' },
    { id:'2pe161', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🚪 Qual é o antónimo de "abrir"?',
      opts:['fechar','tocar','bater','girar'], ans:0,
      exp:'abrir ≠ fechar.' },
    { id:'2pe162', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🛏️ Qual é o antónimo de "acordar"?',
      opts:['dormir','correr','sentar','ler'], ans:0,
      exp:'acordar ≠ dormir.' },
    { id:'2pe163', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🐘 Antónimo de "pequeno": ___',
      ans:['grande'],
      exp:'pequeno ≠ grande.' },
    { id:'2pe164', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🏠 Qual é o antónimo de "entrar"?',
      opts:['sair','abrir','fechar','correr'], ans:0,
      exp:'entrar ≠ sair.' },
    { id:'2pe165', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🍰 Qual é o antónimo de "doce"?',
      opts:['amargo','salgado','quente','azedo'], ans:0,
      exp:'doce ≠ amargo.' },
    { id:'2pe166', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🌅 Antónimo de "começar": ___',
      ans:['acabar','terminar'],
      exp:'começar ≠ acabar = terminar.' },
    { id:'2pe167', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'⬅️ Qual é o antónimo de "esquerda"?',
      opts:['cima','baixo','direita','meio'], ans:2,
      exp:'esquerda ≠ direita.' },
    { id:'2pe168', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'😴 Qual é o antónimo de "cansado"?',
      opts:['triste','descansado','feliz','rápido'], ans:1,
      exp:'cansado ≠ descansado.' },
    { id:'2pe169', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'⬆️ Antónimo de "subir": ___',
      ans:['descer'],
      exp:'subir ≠ descer.' },
    { id:'2pe170', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🌟 Qual é o antónimo de "lembrar"?',
      opts:['esquecer','pensar','olhar','falar'], ans:0,
      exp:'lembrar ≠ esquecer.' },
    { id:'2pe171', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🍐 Qual é o antónimo de "verde" (verde=novo)?',
      opts:['azul','maduro','vermelho','grande'], ans:1,
      exp:'verde (novo) ≠ maduro.' },
    { id:'2pe172', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🎈 Qual é o antónimo de "leve"?',
      opts:['ligeiro','pesado','rápido','grande'], ans:1,
      exp:'leve ≠ pesado.' },
    { id:'2pe174', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'😀 Qual é o antónimo de "rir"?',
      opts:['cantar','chorar','correr','dormir'], ans:1,
      exp:'rir ≠ chorar.' },
    { id:'2pe175', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🎁 Qual é o antónimo de "dar"?',
      opts:['receber','levar','trazer','correr'], ans:0,
      exp:'dar ≠ receber.' },
    { id:'2pe176', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🐶 Antónimo de "amigo": ___',
      ans:['inimigo'],
      exp:'amigo ≠ inimigo.' },
    { id:'2pe177', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🌲 Qual é o antónimo de "longe"?',
      opts:['perto','alto','baixo','grande'], ans:0,
      exp:'longe ≠ perto.' },
    { id:'2pe178', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🌟 Qual é o antónimo de "doente"?',
      opts:['saudável','triste','cansado','grande'], ans:0,
      exp:'doente ≠ saudável.' },
    { id:'2pe179', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'⏰ Antónimo de "depressa": ___',
      ans:['devagar'],
      exp:'depressa ≠ devagar.' },
    { id:'2pe180', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🎈 Qual é o antónimo de "cheio"?',
      opts:['grande','vazio','leve','pesado'], ans:1,
      exp:'cheio ≠ vazio.' },
    { id:'2pe181', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'😇 Qual é o antónimo de "bom"?',
      opts:['mau','grande','feliz','triste'], ans:0,
      exp:'bom ≠ mau.' },
    { id:'2pe182', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'⬇️ Antónimo de "em cima": ___',
      ans:['em baixo','embaixo','baixo'],
      exp:'em cima ≠ em baixo.' },
    { id:'2pe183', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'🌳 Qual é o antónimo de "novo"?',
      opts:['velho','grande','feliz','curto'], ans:0,
      exp:'novo ≠ velho.' },
    { id:'2pe184', s:'portugues', t:'Antónimos', type:'tf', diff:1,
      q:'"Alto" e "baixo" são antónimos.',
      ans:true,
      exp:'Sim, têm significados opostos.' },
    { id:'2pe185', s:'portugues', t:'Antónimos', type:'tf', diff:1,
      q:'"Feliz" e "alegre" são antónimos.',
      ans:false,
      exp:'Não, são sinónimos (têm o mesmo significado).' },
    { id:'2pe186', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'😴 Qual é o antónimo de "começar"?',
      opts:['iniciar','acabar','principiar','correr'], ans:1,
      exp:'começar ≠ acabar.' },
    { id:'2pe187', s:'portugues', t:'Antónimos', type:'match', diff:1,
      q:'Liga cada palavra ao seu antónimo.',
      pairs:[['dia','noite'],['frio','quente'],['grande','pequeno'],['alto','baixo']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'dia≠noite, frio≠quente, grande≠pequeno, alto≠baixo.' },
    { id:'2pe188', s:'portugues', t:'Antónimos', type:'mc', diff:2,
      q:'😢 Qual é o antónimo de "alegrar"?',
      opts:['cantar','entristecer','correr','dormir'], ans:1,
      exp:'alegrar ≠ entristecer.' },
    { id:'2pe189', s:'portugues', t:'Antónimos', type:'fill', diff:1,
      q:'🌟 Antónimo de "barulho": ___',
      ans:['silêncio','silencio'],
      exp:'barulho ≠ silêncio.' },

    // ----- Família de palavras (39) -----
    { id:'2pe190', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌸 Qual destas palavras pertence à família de "flor"?',
      opts:['florista','sapato','livro','escola'], ans:0,
      exp:'flor → florista, florido, florescer.' },
    { id:'2pe191', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🏠 Qual destas palavras pertence à família de "casa"?',
      opts:['carro','casinha','livro','escola'], ans:1,
      exp:'casa → casinha, caseiro, casarão.' },
    { id:'2pe192', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🍞 Onde se compra pão? Na ___.',
      ans:['padaria'],
      exp:'pão → padaria.' },
    { id:'2pe193', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐟 Qual destas palavras é da família de "peixe"?',
      opts:['peixaria','mesa','árvore','livro'], ans:0,
      exp:'peixe → peixaria, peixeiro.' },
    { id:'2pe194', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras é da família de "flor"?',
      opts:['florido','livro','escola','sapato'], ans:0,
      exp:'flor → florido, florista.' },
    { id:'2pe195', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🌳 Onde há muitas árvores juntas? Numa ___.',
      ans:['floresta'],
      exp:'flor → floresta.' },
    { id:'2pe196', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐱 Qual destas palavras pertence à família de "gato"?',
      opts:['gatinho','cão','rato','peixe'], ans:0,
      exp:'gato → gatinho, gatão.' },
    { id:'2pe197', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐶 Qual destas palavras NÃO é da família de "casa"?',
      opts:['casinha','caseiro','casarão','sapato'], ans:3,
      exp:'sapato não vem de casa.' },
    { id:'2pe198', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🐠 Quem vende peixe é o ___.',
      ans:['peixeiro'],
      exp:'peixe → peixeiro.' },
    { id:'2pe199', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌊 Qual destas palavras é da família de "mar"?',
      opts:['marinheiro','livro','escola','flor'], ans:0,
      exp:'mar → marinheiro, marítimo, maré.' },
    { id:'2pe200', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐘 Qual destas palavras pertence à família de "livro"?',
      opts:['livraria','sapataria','padaria','peixaria'], ans:0,
      exp:'livro → livraria, livreiro.' },
    { id:'2pe201', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🥛 Onde se compra leite? Na ___.',
      ans:['leitaria'],
      exp:'leite → leitaria.' },
    { id:'2pe202', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🍞 Qual destas palavras é da família de "pão"?',
      opts:['padeiro','cozinheiro','jardineiro','professor'], ans:0,
      exp:'pão → padeiro, padaria.' },
    { id:'2pe203', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌷 Qual destas palavras é da família de "jardim"?',
      opts:['jardineiro','padeiro','pintor','médico'], ans:0,
      exp:'jardim → jardineiro, jardinagem.' },
    { id:'2pe204', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🌳 Quem cuida do jardim é o ___.',
      ans:['jardineiro'],
      exp:'jardim → jardineiro.' },
    { id:'2pe205', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🍐 Qual destas palavras é da família de "fruta"?',
      opts:['fruteiro','padeiro','sapateiro','ferreiro'], ans:0,
      exp:'fruta → fruteiro, frutaria.' },
    { id:'2pe206', s:'portugues', t:'Família de palavras', type:'mc', diff:1,
      q:'👞 Quem faz sapatos é o ___?',
      opts:['padeiro','sapateiro','peixeiro','professor'], ans:1,
      exp:'sapato → sapateiro, sapataria.' },
    { id:'2pe207', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🌷 Quem vende flores é a ___.',
      ans:['florista'],
      exp:'flor → florista.' },
    { id:'2pe208', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐶 Qual destas palavras é da família de "cão"?',
      opts:['cãozinho','gatinho','passarinho','peixinho'], ans:0,
      exp:'cão → cãozinho, canino.' },
    { id:'2pe209', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras é da família de "terra"?',
      opts:['terreno','água','sol','vento'], ans:0,
      exp:'terra → terreno, terrestre.' },
    { id:'2pe210', s:'portugues', t:'Família de palavras', type:'fill', diff:2,
      q:'🍎 Casinha pequena de uma palavra grande: a casinha é da família de ___.',
      ans:['casa'],
      exp:'casinha → casa.' },
    { id:'2pe211', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐎 Qual destas palavras é da família de "cavalo"?',
      opts:['cavalinho','passarinho','gatinho','cãozinho'], ans:0,
      exp:'cavalo → cavalinho, cavaleiro.' },
    { id:'2pe212', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras NÃO é da família de "flor"?',
      opts:['florido','floresta','florescer','farinha'], ans:3,
      exp:'farinha não vem de flor.' },
    { id:'2pe213', s:'portugues', t:'Família de palavras', type:'fill', diff:2,
      q:'🐱 Diminutivo de "gato": ___.',
      ans:['gatinho'],
      exp:'gato → gatinho.' },
    { id:'2pe214', s:'portugues', t:'Família de palavras', type:'mc', diff:1,
      q:'🥛 Quem vende leite é o ___?',
      opts:['leiteiro','padeiro','peixeiro','sapateiro'], ans:0,
      exp:'leite → leiteiro.' },
    { id:'2pe215', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras é da família de "água"?',
      opts:['aquário','padaria','livraria','escola'], ans:0,
      exp:'água → aquário, aquático.' },
    { id:'2pe216', s:'portugues', t:'Família de palavras', type:'fill', diff:1,
      q:'🌊 A pessoa que trabalha no mar é o ___.',
      ans:['marinheiro'],
      exp:'mar → marinheiro.' },
    { id:'2pe217', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐦 Qual destas palavras é da família de "passar" (passarinho)?',
      opts:['passarinho','cavalinho','gatinho','peixinho'], ans:0,
      exp:'pássaro → passarinho.' },
    { id:'2pe218', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌞 Qual destas palavras é da família de "sol"?',
      opts:['solar','marítimo','escolar','rural'], ans:0,
      exp:'sol → solar, ensolarado.' },
    { id:'2pe220', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'⚽ Qual destas palavras é da família de "bola"?',
      opts:['bolinha','linha','livro','casa'], ans:0,
      exp:'bola → bolinha, bolão.' },
    { id:'2pe221', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐟 Qual destas palavras NÃO pertence à família de "peixe"?',
      opts:['peixaria','peixeiro','peixinho','padeiro'], ans:3,
      exp:'padeiro vem de pão, não de peixe.' },
    { id:'2pe222', s:'portugues', t:'Família de palavras', type:'fill', diff:2,
      q:'🐶 Diminutivo de "cão": ___.',
      ans:['cãozinho'],
      exp:'cão → cãozinho.' },
    { id:'2pe223', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🌳 Qual destas palavras pertence à família de "fruta"?',
      opts:['frutaria','padaria','peixaria','livraria'], ans:0,
      exp:'fruta → frutaria, fruteiro.' },
    { id:'2pe224', s:'portugues', t:'Família de palavras', type:'tf', diff:1,
      q:'"Padeiro" pertence à família de "pão".',
      ans:true,
      exp:'Sim, padeiro vem de pão.' },
    { id:'2pe225', s:'portugues', t:'Família de palavras', type:'tf', diff:1,
      q:'"Florista" pertence à família de "casa".',
      ans:false,
      exp:'Não, florista pertence à família de "flor".' },
    { id:'2pe226', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'📚 Qual é o lugar onde se compram livros?',
      opts:['livraria','padaria','peixaria','frutaria'], ans:0,
      exp:'livro → livraria.' },
    { id:'2pe227', s:'portugues', t:'Família de palavras', type:'fill', diff:2,
      q:'🏠 Diminutivo de "casa": ___.',
      ans:['casinha'],
      exp:'casa → casinha.' },
    { id:'2pe228', s:'portugues', t:'Família de palavras', type:'mc', diff:2,
      q:'🐝 Qual destas palavras é da família de "menino"?',
      opts:['meninice','menina','meninada','todas as anteriores'], ans:3,
      exp:'menino → menina, meninice, meninada.' },

    // ----- Tipos de frase (37) -----
    { id:'2pe229', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'❓ "Como te chamas?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe230', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🌞 "Hoje está sol." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe231', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎈 "Que dia bonito!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe232', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🚪 "Fecha a janela!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem → imperativa.' },
    { id:'2pe233', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐱 "O gato dorme." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe234', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🍰 "Que delícia!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe235', s:'portugues', t:'Tipos de frase', type:'fill', diff:2,
      q:'Que sinal usamos no fim de uma frase declarativa? ___',
      ans:['.','ponto final','ponto'],
      exp:'A frase declarativa termina com ".".' },
    { id:'2pe236', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐶 "Vens brincar?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe237', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'📚 "Lê este livro." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem → imperativa.' },
    { id:'2pe238', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🌧️ "Está a chover." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe239', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎉 "Viva!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe240', s:'portugues', t:'Tipos de frase', type:'mc', diff:2,
      q:'🎒 "Onde puseste a mochila?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe241', s:'portugues', t:'Tipos de frase', type:'fill', diff:2,
      q:'🎉 Que sinal de pontuação tem uma frase exclamativa? ___',
      ans:['!','ponto de exclamação','exclamação'],
      exp:'A frase exclamativa termina com "!".' },
    { id:'2pe242', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🛏️ "Vai dormir." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem → imperativa.' },
    { id:'2pe243', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🌳 "A árvore é alta." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe244', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎨 "Que desenho lindo!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe245', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🏠 "Onde moras?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe246', s:'portugues', t:'Tipos de frase', type:'fill', diff:2,
      q:'❓ Que sinal usamos no fim de uma frase interrogativa? ___',
      ans:['?','ponto de interrogação','interrogação'],
      exp:'A frase interrogativa termina com "?".' },
    { id:'2pe247', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🚌 "O autocarro chegou." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe248', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐶 "Não corras na rua!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem (negativa) → imperativa.' },
    { id:'2pe249', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎂 "Que festa!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe250', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐱 "Quantos gatos tens?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe251', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'☀️ "O dia está bonito." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe252', s:'portugues', t:'Tipos de frase', type:'tf', diff:1,
      q:'A frase "Que rico!" é uma frase exclamativa.',
      ans:true,
      exp:'Termina com "!" → exclamativa.' },
    { id:'2pe253', s:'portugues', t:'Tipos de frase', type:'tf', diff:1,
      q:'A frase "Está sol." é uma frase interrogativa.',
      ans:false,
      exp:'Termina com "." → declarativa.' },
    { id:'2pe254', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐶 "Anda cá!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem → imperativa.' },
    { id:'2pe255', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎈 "Tu gostas de balões?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe256', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🌧️ "Que chuva forte!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe257', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐦 "Os pássaros voam." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe258', s:'portugues', t:'Tipos de frase', type:'fill', diff:2,
      q:'Que sinal usamos numa frase imperativa (que pode ser "." ou "!")? ___',
      ans:['.','!','ponto','exclamação'],
      exp:'Pode usar "." ou "!".' },
    { id:'2pe259', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐱 "Que gato fofo!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:2,
      exp:'Exprime emoção → exclamativa.' },
    { id:'2pe260', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🏃 "Tu corres rápido?" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:1,
      exp:'Pergunta → interrogativa.' },
    { id:'2pe261', s:'portugues', t:'Tipos de frase', type:'mc', diff:2,
      q:'🚪 "Por favor, fecha a porta." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'É um pedido → imperativa.' },
    { id:'2pe262', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🐶 "O cão ladra." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:0,
      exp:'Afirma um facto → declarativa.' },
    { id:'2pe263', s:'portugues', t:'Tipos de frase', type:'mc', diff:2,
      q:'🍫 "Dá-me chocolate, por favor." é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'É um pedido → imperativa.' },
    { id:'2pe264', s:'portugues', t:'Tipos de frase', type:'match', diff:1,
      q:'Liga cada frase ao seu tipo.',
      pairs:[['Tens fome?','interrogativa'],['Que bom!','exclamativa'],['Está sol.','declarativa'],['Senta-te.','imperativa']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'Cada frase corresponde ao tipo certo.' },
    { id:'2pe265', s:'portugues', t:'Tipos de frase', type:'mc', diff:1,
      q:'🎵 "Canta uma canção!" é uma frase:',
      opts:['declarativa','interrogativa','exclamativa','imperativa'], ans:3,
      exp:'Dá uma ordem → imperativa.' },

    // ----- Singular e plural (36) -----
    { id:'2pe266', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐱 Plural de "gato": ___',
      ans:['gatos'],
      exp:'gato → gatos.' },
    { id:'2pe268', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🍎 Plural de "maçã": ___',
      ans:['maçãs','macãs','macas'],
      exp:'maçã → maçãs.' },
    { id:'2pe269', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🍞 Plural de "pão": ___',
      ans:['pães','paes'],
      exp:'pão → pães.' },
    { id:'2pe270', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🌳 Plural de "árvore": ___',
      ans:['árvores','arvores'],
      exp:'árvore → árvores.' },
    { id:'2pe271', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🍐 Qual é o plural de "pera"?',
      opts:['peras','peres','peros','peraões'], ans:0,
      exp:'pera → peras.' },
    { id:'2pe272', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🌹 Plural de "flor": ___',
      ans:['flores'],
      exp:'flor → flores.' },
    { id:'2pe273', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🏠 Plural de "casa": ___',
      ans:['casas'],
      exp:'casa → casas.' },
    { id:'2pe274', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🐦 Qual é o plural de "ave"?',
      opts:['aves','aveis','aveos','avões'], ans:0,
      exp:'ave → aves.' },
    { id:'2pe278', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'👩 Plural de "mulher": ___',
      ans:['mulheres'],
      exp:'mulher → mulheres.' },
    { id:'2pe280', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🎨 Qual é o plural de "lápis"?',
      opts:['lápis','lápises','lápiss','lapises'], ans:0,
      exp:'lápis → lápis (não muda).' },
    { id:'2pe281', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐭 Plural de "rato": ___',
      ans:['ratos'],
      exp:'rato → ratos.' },
    { id:'2pe282', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'✋ Plural de "mão": ___',
      ans:['mãos','maos'],
      exp:'mão → mãos.' },
    { id:'2pe283', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🍌 Qual é o plural de "banana"?',
      opts:['bananas','bananes','bananos','banano'], ans:0,
      exp:'banana → bananas.' },
    { id:'2pe284', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'📚 Plural de "lição": ___',
      ans:['lições','licoes','lições'],
      exp:'lição → lições.' },
    { id:'2pe285', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐔 Plural de "galinha": ___',
      ans:['galinhas'],
      exp:'galinha → galinhas.' },
    { id:'2pe286', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'👴 Qual é o plural de "anão"?',
      opts:['anãos','anões','anães','anão'], ans:1,
      exp:'anão → anões.' },
    { id:'2pe287', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐒 Plural de "macaco": ___',
      ans:['macacos'],
      exp:'macaco → macacos.' },
    { id:'2pe288', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐎 Plural de "papel": ___',
      ans:['papéis','papeis'],
      exp:'papel → papéis.' },
    { id:'2pe289', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🐶 Qual é o singular de "gatos"?',
      opts:['gato','gata','gatinhos','gatão'], ans:0,
      exp:'gatos → gato (singular).' },
    { id:'2pe290', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🎀 Plural de "menina": ___',
      ans:['meninas'],
      exp:'menina → meninas.' },
    { id:'2pe291', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐦 Plural de "pássaro": ___',
      ans:['pássaros','passaros'],
      exp:'pássaro → pássaros.' },
    { id:'2pe293', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'☀️ Plural de "estrela": ___',
      ans:['estrelas'],
      exp:'estrela → estrelas.' },
    { id:'2pe294', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🐎 Plural de "irmão": ___',
      ans:['irmãos','irmaos'],
      exp:'irmão → irmãos.' },
    { id:'2pe295', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🌟 Qual é o plural de "balão"?',
      opts:['balãos','balões','balães','balons'], ans:1,
      exp:'balão → balões.' },
    { id:'2pe296', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🍇 Plural de "uva": ___',
      ans:['uvas'],
      exp:'uva → uvas.' },
    { id:'2pe297', s:'portugues', t:'Singular e plural', type:'tf', diff:1,
      q:'O plural de "cão" é "cãos".',
      ans:false,
      exp:'O plural de cão é "cães".' },
    { id:'2pe298', s:'portugues', t:'Singular e plural', type:'tf', diff:1,
      q:'O plural de "menino" é "meninos".',
      ans:true,
      exp:'menino → meninos.' },
    { id:'2pe299', s:'portugues', t:'Singular e plural', type:'mc', diff:1,
      q:'🌷 Qual é o singular de "flores"?',
      opts:['flor','flora','flori','floras'], ans:0,
      exp:'flores → flor.' },
    { id:'2pe300', s:'portugues', t:'Singular e plural', type:'match', diff:1,
      q:'Liga o singular ao plural.',
      pairs:[['cão','cães'],['mão','mãos'],['flor','flores'],['pão','pães']],
      ans:[[0,0],[1,1],[2,2],[3,3]],
      exp:'cão→cães, mão→mãos, flor→flores, pão→pães.' },
    { id:'2pe301', s:'portugues', t:'Singular e plural', type:'fill', diff:1,
      q:'🍞 Plural de "limão": ___',
      ans:['limões','limoes'],
      exp:'limão → limões.' },

    // ----- Verbos no presente (37) -----
    { id:'2pe302', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🍎 Eu ___ (gostar) de maçãs.',
      ans:['gosto'],
      exp:'Verbo gostar → eu gosto.' },
    { id:'2pe303', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎨 Tu ___ (pintar) um desenho.',
      ans:['pintas'],
      exp:'Verbo pintar → tu pintas.' },
    { id:'2pe304', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐶 O cão ___ (latir) muito.',
      ans:['ladra'],
      exp:'Verbo ladrar → ele ladra.' },
    { id:'2pe305', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🚲 Nós ___ (andar) de bicicleta.',
      ans:['andamos'],
      exp:'Verbo andar → nós andamos.' },
    { id:'2pe306', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎵 Eles ___ (tocar) piano.',
      ans:['tocam'],
      exp:'Verbo tocar → eles tocam.' },
    { id:'2pe307', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🏃 "Eu ___ no parque." Qual é a forma certa?',
      opts:['brinco','brincas','brinca','brincam'], ans:0,
      exp:'eu brinco (verbo brincar).' },
    { id:'2pe308', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'📚 A Maria ___ (ler) um livro.',
      ans:['lê','le'],
      exp:'Verbo ler → ela lê.' },
    { id:'2pe309', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🐦 "Os pássaros ___ no céu." Qual é a forma certa?',
      opts:['voa','voam','voas','voo'], ans:1,
      exp:'eles voam (3.ª pessoa do plural).' },
    { id:'2pe310', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'☕ A mãe ___ (fazer) o pequeno-almoço.',
      ans:['faz'],
      exp:'Verbo fazer → ela faz.' },
    { id:'2pe311', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎒 Eu ___ (levar) a mochila.',
      ans:['levo'],
      exp:'Verbo levar → eu levo.' },
    { id:'2pe312', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🛌 Tu ___ (dormir) cedo.',
      ans:['dormes'],
      exp:'Verbo dormir → tu dormes.' },
    { id:'2pe313', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐱 O gato ___ (saltar) na cadeira.',
      ans:['salta'],
      exp:'Verbo saltar → ele salta.' },
    { id:'2pe314', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🍎 Nós ___ (comer) fruta.',
      ans:['comemos'],
      exp:'Verbo comer → nós comemos.' },
    { id:'2pe315', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'⚽ Eles ___ (jogar) à bola.',
      ans:['jogam'],
      exp:'Verbo jogar → eles jogam.' },
    { id:'2pe316', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🌳 "A árvore ___ alta." Qual é a forma certa?',
      opts:['é','são','sou','és'], ans:0,
      exp:'Verbo ser → ela é.' },
    { id:'2pe317', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🍰 "Eu ___ um bolo." Qual é a forma certa?',
      opts:['como','comes','come','comem'], ans:0,
      exp:'eu como (verbo comer).' },
    { id:'2pe318', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'☔ Eu ___ (ter) um chapéu.',
      ans:['tenho'],
      exp:'Verbo ter → eu tenho.' },
    { id:'2pe319', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐶 Tu ___ (ter) um cão.',
      ans:['tens'],
      exp:'Verbo ter → tu tens.' },
    { id:'2pe320', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'📚 Ele ___ (ter) muitos livros.',
      ans:['tem'],
      exp:'Verbo ter → ele tem.' },
    { id:'2pe321', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐱 Nós ___ (ter) um gato.',
      ans:['temos'],
      exp:'Verbo ter → nós temos.' },
    { id:'2pe322', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎁 Eles ___ (ter) muitos brinquedos.',
      ans:['têm','tem'],
      exp:'Verbo ter → eles têm.' },
    { id:'2pe323', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🌧️ "Tu ___ feliz." Qual é a forma certa do verbo "estar"?',
      opts:['estou','estás','está','estão'], ans:1,
      exp:'tu estás (verbo estar).' },
    { id:'2pe324', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🚶 Eu ___ (ir) à escola.',
      ans:['vou'],
      exp:'Verbo ir → eu vou.' },
    { id:'2pe325', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🛒 Tu ___ (ir) ao mercado.',
      ans:['vais'],
      exp:'Verbo ir → tu vais.' },
    { id:'2pe326', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🚗 Ela ___ (ir) de carro.',
      ans:['vai'],
      exp:'Verbo ir → ela vai.' },
    { id:'2pe327', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🎵 "A Ana ___ uma canção." Qual é a forma certa?',
      opts:['canto','cantas','canta','cantam'], ans:2,
      exp:'ela canta (verbo cantar).' },
    { id:'2pe328', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'💧 Nós ___ (beber) água.',
      ans:['bebemos'],
      exp:'Verbo beber → nós bebemos.' },
    { id:'2pe329', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐢 As tartarugas ___ (ser) lentas.',
      ans:['são'],
      exp:'Verbo ser → elas são.' },
    { id:'2pe330', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'😊 "Eu ___ feliz." Qual é a forma certa?',
      opts:['sou','és','é','somos'], ans:0,
      exp:'eu sou (verbo ser).' },
    { id:'2pe331', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🎨 O João ___ (desenhar) uma casa.',
      ans:['desenha'],
      exp:'Verbo desenhar → ele desenha.' },
    { id:'2pe332', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐶 Vós ___ (correr) no parque.',
      ans:['correis'],
      exp:'Verbo correr → vós correis.' },
    { id:'2pe333', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'📚 Eles ___ (estudar) muito.',
      ans:['estudam'],
      exp:'Verbo estudar → eles estudam.' },
    { id:'2pe334', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'🛏️ "Os meninos ___ cedo." Qual é a forma certa do verbo "dormir"?',
      opts:['durmo','dormes','dorme','dormem'], ans:3,
      exp:'eles dormem (3.ª pessoa do plural).' },
    { id:'2pe335', s:'portugues', t:'Verbos no presente', type:'tf', diff:1,
      q:'A frase "Eu corro." está no presente.',
      ans:true,
      exp:'Sim, "corro" é o presente do verbo correr.' },
    { id:'2pe336', s:'portugues', t:'Verbos no presente', type:'tf', diff:1,
      q:'A frase "Nós cantamos agora." está no presente.',
      ans:true,
      exp:'Sim, "cantamos" é o presente do verbo cantar.' },
    { id:'2pe337', s:'portugues', t:'Verbos no presente', type:'mc', diff:2,
      q:'☀️ "O sol ___ no céu." Qual é a forma certa?',
      opts:['brilho','brilhas','brilha','brilham'], ans:2,
      exp:'ele brilha (verbo brilhar).' },
    { id:'2pe338', s:'portugues', t:'Verbos no presente', type:'fill', diff:1,
      q:'🐝 As abelhas ___ (fazer) mel.',
      ans:['fazem'],
      exp:'Verbo fazer → elas fazem.' },

];
if (typeof window !== 'undefined') window.EXERCISES_2_P_EXTRA2 = EXERCISES_2_P_EXTRA2;
