// EscolaPlay - Top-up extra do 2.º ano - Matemática (gerado, AE 2018)
const EXERCISES_2_M_EXTRA2 = [

    // ===== Números até 100 (+36) =====
    { id:'2me1', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o número que vem depois de 47?',
      opts:['46','48','50','40'], ans:1,
      exp:'47 + 1 = 48.' },
    { id:'2me2', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o número que vem antes de 60?',
      opts:['58','59','61','70'], ans:1,
      exp:'60 - 1 = 59.' },
    { id:'2me3', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve por extenso o número 35: ___',
      ans:['trinta e cinco'],
      exp:'35 = trinta e cinco.' },
    { id:'2me4', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve em algarismos: setenta e dois → ___',
      ans:['72'],
      exp:'Setenta e dois = 72.' },
    { id:'2me5', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual destes números é maior?',
      opts:['56','65','62','58'], ans:1,
      exp:'65 é o maior.' },
    { id:'2me6', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual destes números é menor?',
      opts:['41','37','45','39'], ans:1,
      exp:'37 é o menor.' },
    { id:'2me7', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Que número está entre 49 e 51? ___',
      ans:['50','cinquenta'],
      exp:'O número 50 está entre 49 e 51.' },
    { id:'2me8', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o número par?',
      opts:['7','13','24','19'], ans:2,
      exp:'24 é par (acaba em 4).' },
    { id:'2me9', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o número ímpar?',
      opts:['28','40','62','37'], ans:3,
      exp:'37 é ímpar (acaba em 7).' },
    { id:'2me10', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Conta de 2 em 2 a partir de 10: 10, 12, 14, ___',
      ans:['16','dezasseis'],
      exp:'14 + 2 = 16.' },
    { id:'2me11', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Conta de 5 em 5: 25, 30, 35, ___',
      ans:['40','quarenta'],
      exp:'35 + 5 = 40.' },
    { id:'2me12', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Conta de 10 em 10: 30, 40, 50, ___',
      ans:['60','sessenta'],
      exp:'50 + 10 = 60.' },
    { id:'2me13', s:'matematica', t:'Números até 100', type:'order', diff:2,
      q:'Ordena do menor para o maior:',
      items:['78','45','62','30'],
      ans:'4,2,3,1',
      exp:'30 < 45 < 62 < 78.' },
    { id:'2me14', s:'matematica', t:'Números até 100', type:'order', diff:2,
      q:'Ordena do maior para o menor:',
      items:['41','85','17','60'],
      ans:'2,4,1,3',
      exp:'85 > 60 > 41 > 17.' },
    { id:'2me15', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 Qual é o número anterior a 80?',
      opts:['78','79','81','82'], ans:1,
      exp:'80 - 1 = 79.' },
    { id:'2me16', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 Qual é o número posterior a 99?',
      opts:['98','100','101','90'], ans:1,
      exp:'99 + 1 = 100.' },
    { id:'2me17', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve por extenso: 100 → ___',
      ans:['cem'],
      exp:'100 = cem.' },
    { id:'2me18', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve em algarismos: oitenta e três → ___',
      ans:['83'],
      exp:'Oitenta e três = 83.' },
    { id:'2me19', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Quantas dezenas tem o número 70?',
      opts:['5','6','7','8'], ans:2,
      exp:'70 = 7 dezenas.' },
    { id:'2me20', s:'matematica', t:'Números até 100', type:'tf', diff:1,
      q:'🔢 O número 18 é par.',
      ans:true,
      exp:'18 acaba em 8 → par.' },
    { id:'2me21', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 Qual é o número que tem 4 dezenas e 3 unidades?',
      opts:['34','43','40','30'], ans:1,
      exp:'4D + 3U = 43.' },
    { id:'2me22', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Qual é o sucessor de 64? ___',
      ans:['65','sessenta e cinco'],
      exp:'64 + 1 = 65.' },
    { id:'2me23', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Qual é o antecessor de 50? ___',
      ans:['49','quarenta e nove'],
      exp:'50 - 1 = 49.' },
    { id:'2me24', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o maior número de 2 algarismos?',
      opts:['89','90','98','99'], ans:3,
      exp:'99 é o maior número com 2 algarismos.' },
    { id:'2me25', s:'matematica', t:'Números até 100', type:'mc', diff:1,
      q:'🔢 Qual é o menor número de 2 algarismos?',
      opts:['1','9','10','11'], ans:2,
      exp:'10 é o menor de 2 algarismos.' },
    { id:'2me26', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Conta de 2 em 2: 20, 22, 24, ___',
      ans:['26','vinte e seis'],
      exp:'24 + 2 = 26.' },
    { id:'2me27', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 Quantos números pares há entre 1 e 10?',
      opts:['3','4','5','6'], ans:2,
      exp:'2,4,6,8,10 → 5 números pares.' },
    { id:'2me28', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve por extenso: 47 → ___',
      ans:['quarenta e sete'],
      exp:'47 = quarenta e sete.' },
    { id:'2me29', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Escreve em algarismos: noventa → ___',
      ans:['90'],
      exp:'Noventa = 90.' },
    { id:'2me30', s:'matematica', t:'Números até 100', type:'order', diff:2,
      q:'Ordena do menor para o maior:',
      items:['66','19','88','40'],
      ans:'2,4,1,3',
      exp:'19 < 40 < 66 < 88.' },
    { id:'2me31', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 Qual destes números está entre 70 e 80?',
      opts:['68','75','82','90'], ans:1,
      exp:'75 está entre 70 e 80.' },
    { id:'2me32', s:'matematica', t:'Números até 100', type:'tf', diff:1,
      q:'🔢 O número 45 é maior do que 54.',
      ans:false,
      exp:'45 < 54 (54 tem mais dezenas).' },
    { id:'2me33', s:'matematica', t:'Números até 100', type:'problem', diff:2,
      q:'📚 A Maria tem 38 cromos e o João tem 41. Qual deles tem mais cromos?',
      material:['Comparação 38 vs 41.'],
      solution:'41 > 38, logo o João tem mais cromos.',
      ans:'O João',
      exp:'Compara as dezenas: 4 > 3.' },
    { id:'2me34', s:'matematica', t:'Números até 100', type:'mc', diff:2,
      q:'🔢 Qual destes é um número ímpar?',
      opts:['20','44','67','80'], ans:2,
      exp:'67 é ímpar (acaba em 7).' },
    { id:'2me35', s:'matematica', t:'Números até 100', type:'fill', diff:1,
      q:'🔢 Conta de 10 em 10 a partir de 20: 20, 30, 40, ___',
      ans:['50','cinquenta'],
      exp:'40 + 10 = 50.' },
    { id:'2me36', s:'matematica', t:'Números até 100', type:'mc', diff:3,
      q:'🔢 O número que tem 9 dezenas e 9 unidades é:',
      opts:['18','81','99','100'], ans:2,
      exp:'9D + 9U = 99.' },

    // ===== Dezenas e unidades (+39) =====
    { id:'2me37', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Quantas dezenas tem o número 40?',
      opts:['2','3','4','5'], ans:2,
      exp:'40 = 4D + 0U.' },
    { id:'2me38', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Quantas unidades tem o número 8?',
      opts:['8','18','80','88'], ans:0,
      exp:'8 = 0D + 8U.' },
    { id:'2me39', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 35 = ___ D + 5 U',
      ans:['3','três','tres'],
      exp:'35 = 3 dezenas + 5 unidades.' },
    { id:'2me40', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 67 = 6 D + ___ U',
      ans:['7','sete'],
      exp:'67 = 6D + 7U.' },
    { id:'2me41', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 5 D + 2 U = ___',
      ans:['52','cinquenta e dois'],
      exp:'50 + 2 = 52.' },
    { id:'2me42', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 8 D + 0 U = ___',
      ans:['80','oitenta'],
      exp:'8 dezenas = 80.' },
    { id:'2me43', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 No número 73, o algarismo 7 representa:',
      opts:['7 unidades','7 dezenas','7 centenas','70 unidades'], ans:1,
      exp:'O 7 está na casa das dezenas → 7D = 70.' },
    { id:'2me44', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 No número 29, o algarismo 9 representa:',
      opts:['9 dezenas','9 unidades','90','19'], ans:1,
      exp:'O 9 está na casa das unidades.' },
    { id:'2me45', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 46 em dezenas e unidades: 46 = ___ + 6',
      ans:['40','quarenta'],
      exp:'46 = 40 + 6.' },
    { id:'2me46', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 28: 28 = 20 + ___',
      ans:['8','oito'],
      exp:'28 = 20 + 8.' },
    { id:'2me47', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:2,
      q:'🔢 Quantas dezenas há em 100?',
      opts:['1','5','10','100'], ans:2,
      exp:'100 = 10 dezenas.' },
    { id:'2me48', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 9 D + 9 U = ___',
      ans:['99','noventa e nove'],
      exp:'90 + 9 = 99.' },
    { id:'2me49', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Qual o número formado por 7 dezenas e 4 unidades?',
      opts:['47','74','704','740'], ans:1,
      exp:'7D + 4U = 74.' },
    { id:'2me50', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 91: 91 = ___ + 1',
      ans:['90','noventa'],
      exp:'91 = 90 + 1.' },
    { id:'2me51', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:2,
      q:'🔢 No número 50, o 5 vale:',
      opts:['5','15','50','55'], ans:2,
      exp:'5D = 50.' },
    { id:'2me52', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 6 D + 3 U = ___',
      ans:['63','sessenta e três','sessenta e tres'],
      exp:'60 + 3 = 63.' },
    { id:'2me53', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 4 D + 9 U = ___',
      ans:['49','quarenta e nove'],
      exp:'40 + 9 = 49.' },
    { id:'2me54', s:'matematica', t:'Dezenas e unidades', type:'tf', diff:1,
      q:'🔢 No número 36, o algarismo 3 vale 30.',
      ans:true,
      exp:'O 3 está na casa das dezenas → 3D = 30.' },
    { id:'2me55', s:'matematica', t:'Dezenas e unidades', type:'tf', diff:1,
      q:'🔢 5 dezenas e 4 unidades é igual a 45.',
      ans:false,
      exp:'5D + 4U = 54, não 45.' },
    { id:'2me56', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:2,
      q:'🔢 Que número tem 1 dezena e 5 unidades?',
      opts:['51','15','105','150'], ans:1,
      exp:'1D + 5U = 15.' },
    { id:'2me57', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 57: 57 = 50 + ___',
      ans:['7','sete'],
      exp:'57 = 50 + 7.' },
    { id:'2me58', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 84: 84 = ___ + 4',
      ans:['80','oitenta'],
      exp:'84 = 80 + 4.' },
    { id:'2me59', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Quantas dezenas tem 90?',
      opts:['7','8','9','10'], ans:2,
      exp:'90 = 9 dezenas.' },
    { id:'2me60', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 7 D + 0 U = ___',
      ans:['70','setenta'],
      exp:'70.' },
    { id:'2me61', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:2,
      q:'🔢 No número 82, o algarismo 2 vale:',
      opts:['2','20','82','12'], ans:0,
      exp:'O 2 está na casa das unidades → 2.' },
    { id:'2me62', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 73: 73 = ___ + ___',
      ans:['70 + 3','70+3'],
      exp:'73 = 70 + 3.' },
    { id:'2me63', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 25: 25 = ___ + ___',
      ans:['20 + 5','20+5'],
      exp:'25 = 20 + 5.' },
    { id:'2me64', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Que número tem 2 dezenas e 6 unidades?',
      opts:['62','26','206','260'], ans:1,
      exp:'2D + 6U = 26.' },
    { id:'2me65', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:2,
      q:'🔢 Em 38, quantas unidades há ao todo?',
      opts:['8','18','30','38'], ans:3,
      exp:'38 = 38 unidades (3D = 30 + 8U).' },
    { id:'2me66', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 3 D + 7 U = ___',
      ans:['37','trinta e sete'],
      exp:'30 + 7 = 37.' },
    { id:'2me67', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 1 D + 9 U = ___',
      ans:['19','dezanove'],
      exp:'10 + 9 = 19.' },
    { id:'2me68', s:'matematica', t:'Dezenas e unidades', type:'problem', diff:2,
      q:'🍪 A avó fez 6 dezenas de bolachas. Quantas bolachas fez ao todo?',
      material:['1 dezena = 10.'],
      solution:'6 dezenas = 6 × 10 = 60 bolachas.',
      ans:'60',
      exp:'6D = 60.' },
    { id:'2me69', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:2,
      q:'🔢 Qual número está entre 4D + 5U e 4D + 7U?',
      opts:['44','45','46','47'], ans:2,
      exp:'45 < 46 < 47.' },
    { id:'2me70', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 60: 60 = 60 + ___',
      ans:['0','zero'],
      exp:'60 = 60 + 0.' },
    { id:'2me71', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Que número tem 5 dezenas e 5 unidades?',
      opts:['50','55','5','505'], ans:1,
      exp:'5D + 5U = 55.' },
    { id:'2me72', s:'matematica', t:'Dezenas e unidades', type:'fill', diff:1,
      q:'🔢 Decompõe 12: 12 = 10 + ___',
      ans:['2','dois'],
      exp:'12 = 10 + 2.' },
    { id:'2me73', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:1,
      q:'🔢 Quantas unidades tem 1 dezena?',
      opts:['1','5','10','100'], ans:2,
      exp:'1 dezena = 10 unidades.' },
    { id:'2me74', s:'matematica', t:'Dezenas e unidades', type:'tf', diff:1,
      q:'🔢 No número 100 há 10 dezenas.',
      ans:true,
      exp:'100 = 10D.' },
    { id:'2me75', s:'matematica', t:'Dezenas e unidades', type:'mc', diff:3,
      q:'🔢 Que número tem 0 dezenas e 7 unidades?',
      opts:['70','7','17','77'], ans:1,
      exp:'0D + 7U = 7.' },

    // ===== Adição até 100 (+34) =====
    { id:'2me76', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 25 + 14 = ___',
      ans:['39','trinta e nove'],
      exp:'25 + 14 = 39.' },
    { id:'2me77', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 30 + 20 = ___',
      ans:['50','cinquenta'],
      exp:'30 + 20 = 50.' },
    { id:'2me78', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 47 + 10 = ___',
      ans:['57','cinquenta e sete'],
      exp:'47 + 10 = 57.' },
    { id:'2me79', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 60 + 30 = ___',
      ans:['90','noventa'],
      exp:'60 + 30 = 90.' },
    { id:'2me80', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 18 + 12 = ?',
      opts:['28','29','30','31'], ans:2,
      exp:'18 + 12 = 30.' },
    { id:'2me81', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 45 + 5 = ?',
      opts:['40','45','50','55'], ans:2,
      exp:'45 + 5 = 50.' },
    { id:'2me82', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 70 + 20 = ?',
      opts:['80','85','90','100'], ans:2,
      exp:'70 + 20 = 90.' },
    { id:'2me83', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 33 + 6 = ___',
      ans:['39','trinta e nove'],
      exp:'33 + 6 = 39.' },
    { id:'2me84', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 50 + 25 = ___',
      ans:['75','setenta e cinco'],
      exp:'50 + 25 = 75.' },
    { id:'2me85', s:'matematica', t:'Adição até 100', type:'mc', diff:2,
      q:'➕ 28 + 17 = ?',
      opts:['35','45','55','40'], ans:1,
      exp:'28 + 17 = 45.' },
    { id:'2me86', s:'matematica', t:'Adição até 100', type:'mc', diff:2,
      q:'➕ 36 + 24 = ?',
      opts:['50','55','60','65'], ans:2,
      exp:'36 + 24 = 60.' },
    { id:'2me87', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 20 + 80 = ___',
      ans:['100','cem'],
      exp:'20 + 80 = 100.' },
    { id:'2me88', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 56 + 19 = ___',
      ans:['75','setenta e cinco'],
      exp:'56 + 19 = 75.' },
    { id:'2me89', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 47 + 33 = ___',
      ans:['80','oitenta'],
      exp:'47 + 33 = 80.' },
    { id:'2me90', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 41 + 8 = ?',
      opts:['48','49','50','51'], ans:1,
      exp:'41 + 8 = 49.' },
    { id:'2me91', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ Quanto falta a 70 para chegar a 100? ___',
      ans:['30','trinta'],
      exp:'70 + 30 = 100.' },
    { id:'2me92', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ Quanto falta a 60 para chegar a 100? ___',
      ans:['40','quarenta'],
      exp:'60 + 40 = 100.' },
    { id:'2me93', s:'matematica', t:'Adição até 100', type:'tf', diff:1,
      q:'➕ 25 + 25 = 50.',
      ans:true,
      exp:'25 + 25 = 50.' },
    { id:'2me94', s:'matematica', t:'Adição até 100', type:'tf', diff:1,
      q:'➕ 40 + 30 = 60.',
      ans:false,
      exp:'40 + 30 = 70.' },
    { id:'2me95', s:'matematica', t:'Adição até 100', type:'mc', diff:2,
      q:'➕ 65 + 25 = ?',
      opts:['80','85','90','95'], ans:2,
      exp:'65 + 25 = 90.' },
    { id:'2me96', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 38 + 26 = ___',
      ans:['64','sessenta e quatro'],
      exp:'38 + 26 = 64.' },
    { id:'2me97', s:'matematica', t:'Adição até 100', type:'problem', diff:2,
      q:'🍎 A Joana tem 23 maçãs e o irmão tem 18. Quantas maçãs têm os dois juntos?',
      material:['Adição: 23 + 18.'],
      solution:'23 + 18 = 41 maçãs.',
      ans:'41',
      exp:'Soma as quantidades.' },
    { id:'2me98', s:'matematica', t:'Adição até 100', type:'problem', diff:2,
      q:'📚 Numa estante há 35 livros e na outra 27. Quantos livros há ao todo?',
      material:['Adição: 35 + 27.'],
      solution:'35 + 27 = 62 livros.',
      ans:'62',
      exp:'Total de livros.' },
    { id:'2me99', s:'matematica', t:'Adição até 100', type:'problem', diff:2,
      q:'🚌 Num autocarro entram 28 pessoas e na próxima paragem entram mais 15. Quantas pessoas estão no autocarro?',
      material:['Adição: 28 + 15.'],
      solution:'28 + 15 = 43 pessoas.',
      ans:'43',
      exp:'Soma as pessoas.' },
    { id:'2me100', s:'matematica', t:'Adição até 100', type:'problem', diff:2,
      q:'⚽ A equipa marcou 19 golos numa época e 22 noutra. Quantos golos marcou ao todo?',
      material:['Adição: 19 + 22.'],
      solution:'19 + 22 = 41 golos.',
      ans:'41',
      exp:'Total de golos.' },
    { id:'2me101', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 50 + 50 = ?',
      opts:['90','95','100','110'], ans:2,
      exp:'50 + 50 = 100.' },
    { id:'2me102', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 13 + 7 = ___',
      ans:['20','vinte'],
      exp:'13 + 7 = 20.' },
    { id:'2me103', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 44 + 44 = ___',
      ans:['88','oitenta e oito'],
      exp:'44 + 44 = 88.' },
    { id:'2me104', s:'matematica', t:'Adição até 100', type:'mc', diff:2,
      q:'➕ 27 + 13 = ?',
      opts:['30','35','40','45'], ans:2,
      exp:'27 + 13 = 40.' },
    { id:'2me105', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 90 + 10 = ___',
      ans:['100','cem'],
      exp:'90 + 10 = 100.' },
    { id:'2me106', s:'matematica', t:'Adição até 100', type:'mc', diff:1,
      q:'➕ 15 + 15 = ?',
      opts:['25','30','35','40'], ans:1,
      exp:'15 + 15 = 30.' },
    { id:'2me107', s:'matematica', t:'Adição até 100', type:'fill', diff:2,
      q:'➕ 19 + 19 = ___',
      ans:['38','trinta e oito'],
      exp:'19 + 19 = 38.' },
    { id:'2me108', s:'matematica', t:'Adição até 100', type:'mc', diff:3,
      q:'➕ 49 + 49 = ?',
      opts:['89','98','99','100'], ans:1,
      exp:'49 + 49 = 98.' },
    { id:'2me109', s:'matematica', t:'Adição até 100', type:'fill', diff:1,
      q:'➕ 60 + 35 = ___',
      ans:['95','noventa e cinco'],
      exp:'60 + 35 = 95.' },

    // ===== Subtração até 100 (+34) =====
    { id:'2me110', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 50 - 20 = ___',
      ans:['30','trinta'],
      exp:'50 - 20 = 30.' },
    { id:'2me111', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 80 - 30 = ___',
      ans:['50','cinquenta'],
      exp:'80 - 30 = 50.' },
    { id:'2me112', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 45 - 5 = ___',
      ans:['40','quarenta'],
      exp:'45 - 5 = 40.' },
    { id:'2me113', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 67 - 7 = ___',
      ans:['60','sessenta'],
      exp:'67 - 7 = 60.' },
    { id:'2me114', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
      q:'➖ 40 - 10 = ?',
      opts:['20','25','30','35'], ans:2,
      exp:'40 - 10 = 30.' },
    { id:'2me115', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
      q:'➖ 70 - 50 = ?',
      opts:['10','15','20','25'], ans:2,
      exp:'70 - 50 = 20.' },
    { id:'2me116', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
      q:'➖ 100 - 50 = ?',
      opts:['40','45','50','55'], ans:2,
      exp:'100 - 50 = 50.' },
    { id:'2me117', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 38 - 8 = ___',
      ans:['30','trinta'],
      exp:'38 - 8 = 30.' },
    { id:'2me118', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 90 - 40 = ___',
      ans:['50','cinquenta'],
      exp:'90 - 40 = 50.' },
    { id:'2me119', s:'matematica', t:'Subtração até 100', type:'mc', diff:2,
      q:'➖ 56 - 23 = ?',
      opts:['23','33','43','53'], ans:1,
      exp:'56 - 23 = 33.' },
    { id:'2me120', s:'matematica', t:'Subtração até 100', type:'mc', diff:2,
      q:'➖ 72 - 18 = ?',
      opts:['44','54','64','56'], ans:1,
      exp:'72 - 18 = 54.' },
    { id:'2me121', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 65 - 27 = ___',
      ans:['38','trinta e oito'],
      exp:'65 - 27 = 38.' },
    { id:'2me122', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 84 - 36 = ___',
      ans:['48','quarenta e oito'],
      exp:'84 - 36 = 48.' },
    { id:'2me123', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 20 - 5 = ___',
      ans:['15','quinze'],
      exp:'20 - 5 = 15.' },
    { id:'2me124', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 100 - 1 = ___',
      ans:['99','noventa e nove'],
      exp:'100 - 1 = 99.' },
    { id:'2me125', s:'matematica', t:'Subtração até 100', type:'tf', diff:1,
      q:'➖ 30 - 30 = 0.',
      ans:true,
      exp:'Qualquer número menos ele próprio = 0.' },
    { id:'2me126', s:'matematica', t:'Subtração até 100', type:'tf', diff:1,
      q:'➖ 50 - 25 = 30.',
      ans:false,
      exp:'50 - 25 = 25.' },
    { id:'2me127', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
      q:'➖ 100 - 99 = ?',
      opts:['0','1','2','9'], ans:1,
      exp:'100 - 99 = 1.' },
    { id:'2me128', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 73 - 14 = ___',
      ans:['59','cinquenta e nove'],
      exp:'73 - 14 = 59.' },
    { id:'2me129', s:'matematica', t:'Subtração até 100', type:'mc', diff:2,
      q:'➖ 60 - 35 = ?',
      opts:['15','20','25','30'], ans:2,
      exp:'60 - 35 = 25.' },
    { id:'2me130', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 92 - 47 = ___',
      ans:['45','quarenta e cinco'],
      exp:'92 - 47 = 45.' },
    { id:'2me131', s:'matematica', t:'Subtração até 100', type:'problem', diff:2,
      q:'🍪 A mãe fez 40 bolachas e os filhos comeram 15. Quantas bolachas sobraram?',
      material:['Subtração: 40 - 15.'],
      solution:'40 - 15 = 25 bolachas.',
      ans:'25',
      exp:'Sobraram 25.' },
    { id:'2me132', s:'matematica', t:'Subtração até 100', type:'problem', diff:2,
      q:'🚗 Num parque havia 60 carros. Saíram 22. Quantos ficaram?',
      material:['Subtração: 60 - 22.'],
      solution:'60 - 22 = 38 carros.',
      ans:'38',
      exp:'Ficaram 38.' },
    { id:'2me133', s:'matematica', t:'Subtração até 100', type:'problem', diff:2,
      q:'🐟 No aquário havia 32 peixes. Foram dados 12. Quantos sobraram?',
      material:['Subtração: 32 - 12.'],
      solution:'32 - 12 = 20 peixes.',
      ans:'20',
      exp:'Sobraram 20.' },
    { id:'2me134', s:'matematica', t:'Subtração até 100', type:'problem', diff:2,
      q:'🎒 A escola tem 75 alunos e 30 são meninos. Quantas são meninas?',
      material:['Subtração: 75 - 30.'],
      solution:'75 - 30 = 45 meninas.',
      ans:'45',
      exp:'Há 45 meninas.' },
    { id:'2me135', s:'matematica', t:'Subtração até 100', type:'mc', diff:2,
      q:'➖ 88 - 44 = ?',
      opts:['33','44','55','66'], ans:1,
      exp:'88 - 44 = 44.' },
    { id:'2me136', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 99 - 9 = ___',
      ans:['90','noventa'],
      exp:'99 - 9 = 90.' },
    { id:'2me137', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 26 - 6 = ___',
      ans:['20','vinte'],
      exp:'26 - 6 = 20.' },
    { id:'2me138', s:'matematica', t:'Subtração até 100', type:'mc', diff:1,
      q:'➖ 50 - 0 = ?',
      opts:['0','5','50','100'], ans:2,
      exp:'Subtrair zero não muda nada.' },
    { id:'2me139', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 81 - 19 = ___',
      ans:['62','sessenta e dois'],
      exp:'81 - 19 = 62.' },
    { id:'2me140', s:'matematica', t:'Subtração até 100', type:'mc', diff:2,
      q:'➖ 45 - 18 = ?',
      opts:['25','27','29','31'], ans:1,
      exp:'45 - 18 = 27.' },
    { id:'2me141', s:'matematica', t:'Subtração até 100', type:'fill', diff:2,
      q:'➖ 100 - 25 = ___',
      ans:['75','setenta e cinco'],
      exp:'100 - 25 = 75.' },
    { id:'2me142', s:'matematica', t:'Subtração até 100', type:'fill', diff:1,
      q:'➖ 35 - 15 = ___',
      ans:['20','vinte'],
      exp:'35 - 15 = 20.' },
    { id:'2me143', s:'matematica', t:'Subtração até 100', type:'mc', diff:3,
      q:'➖ 100 - 37 = ?',
      opts:['53','63','73','67'], ans:1,
      exp:'100 - 37 = 63.' },

    // ===== Tabuada do 2 (+38) =====
    { id:'2me144', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 0 = ___',
      ans:['0','zero'],
      exp:'Qualquer número × 0 = 0.' },
    { id:'2me145', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 1 = ___',
      ans:['2','dois'],
      exp:'2 × 1 = 2.' },
    { id:'2me146', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 2 = ___',
      ans:['4','quatro'],
      exp:'2 × 2 = 4.' },
    { id:'2me147', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 3 = ___',
      ans:['6','seis'],
      exp:'2 × 3 = 6.' },
    { id:'2me148', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 4 = ___',
      ans:['8','oito'],
      exp:'2 × 4 = 8.' },
    { id:'2me149', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 5 = ___',
      ans:['10','dez'],
      exp:'2 × 5 = 10.' },
    { id:'2me150', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 6 = ___',
      ans:['12','doze'],
      exp:'2 × 6 = 12.' },
    { id:'2me151', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 7 = ___',
      ans:['14','catorze','quatorze'],
      exp:'2 × 7 = 14.' },
    { id:'2me152', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 8 = ___',
      ans:['16','dezasseis'],
      exp:'2 × 8 = 16.' },
    { id:'2me153', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 9 = ___',
      ans:['18','dezoito'],
      exp:'2 × 9 = 18.' },
    { id:'2me154', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 2 × 10 = ___',
      ans:['20','vinte'],
      exp:'2 × 10 = 20.' },
    { id:'2me155', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ 2 × 4 = ?',
      opts:['6','7','8','10'], ans:2,
      exp:'2 × 4 = 8.' },
    { id:'2me156', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ 2 × 7 = ?',
      opts:['12','13','14','16'], ans:2,
      exp:'2 × 7 = 14.' },
    { id:'2me157', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ 2 × 9 = ?',
      opts:['16','17','18','19'], ans:2,
      exp:'2 × 9 = 18.' },
    { id:'2me158', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ Qual é o dobro de 6?',
      opts:['10','11','12','14'], ans:2,
      exp:'2 × 6 = 12.' },
    { id:'2me159', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ Qual é o dobro de 8?',
      opts:['14','15','16','18'], ans:2,
      exp:'2 × 8 = 16.' },
    { id:'2me160', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ Qual é o dobro de 10?',
      opts:['12','15','20','25'], ans:2,
      exp:'2 × 10 = 20.' },
    { id:'2me161', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ O dobro de 5 é ___',
      ans:['10','dez'],
      exp:'2 × 5 = 10.' },
    { id:'2me162', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ O dobro de 9 é ___',
      ans:['18','dezoito'],
      exp:'2 × 9 = 18.' },
    { id:'2me163', s:'matematica', t:'Tabuada do 2', type:'tf', diff:1,
      q:'✖️ 2 × 5 = 10.',
      ans:true,
      exp:'2 × 5 = 10.' },
    { id:'2me164', s:'matematica', t:'Tabuada do 2', type:'tf', diff:1,
      q:'✖️ 2 × 6 = 14.',
      ans:false,
      exp:'2 × 6 = 12 (não 14).' },
    { id:'2me165', s:'matematica', t:'Tabuada do 2', type:'problem', diff:2,
      q:'👟 Cada par de sapatos tem 2 sapatos. Quantos sapatos há em 5 pares?',
      material:['Multiplicação: 2 × 5.'],
      solution:'2 × 5 = 10 sapatos.',
      ans:'10',
      exp:'Tabuada do 2.' },
    { id:'2me166', s:'matematica', t:'Tabuada do 2', type:'problem', diff:2,
      q:'🚲 Cada bicicleta tem 2 rodas. Quantas rodas têm 7 bicicletas?',
      material:['Multiplicação: 2 × 7.'],
      solution:'2 × 7 = 14 rodas.',
      ans:'14',
      exp:'Tabuada do 2.' },
    { id:'2me167', s:'matematica', t:'Tabuada do 2', type:'problem', diff:2,
      q:'👁️ Cada pessoa tem 2 olhos. Quantos olhos têm 8 pessoas?',
      material:['Multiplicação: 2 × 8.'],
      solution:'2 × 8 = 16 olhos.',
      ans:'16',
      exp:'Tabuada do 2.' },
    { id:'2me168', s:'matematica', t:'Tabuada do 2', type:'problem', diff:2,
      q:'🐦 Cada pássaro tem 2 asas. Quantas asas têm 6 pássaros?',
      material:['Multiplicação: 2 × 6.'],
      solution:'2 × 6 = 12 asas.',
      ans:'12',
      exp:'Tabuada do 2.' },
    { id:'2me169', s:'matematica', t:'Tabuada do 2', type:'mc', diff:2,
      q:'✖️ Os múltiplos de 2 são números:',
      opts:['ímpares','pares','primos','negativos'], ans:1,
      exp:'2, 4, 6, 8… são pares.' },
    { id:'2me170', s:'matematica', t:'Tabuada do 2', type:'fill', diff:2,
      q:'✖️ ___ × 2 = 14',
      ans:['7','sete'],
      exp:'7 × 2 = 14.' },
    { id:'2me171', s:'matematica', t:'Tabuada do 2', type:'fill', diff:2,
      q:'✖️ 2 × ___ = 16',
      ans:['8','oito'],
      exp:'2 × 8 = 16.' },
    { id:'2me172', s:'matematica', t:'Tabuada do 2', type:'fill', diff:2,
      q:'✖️ ___ × 2 = 20',
      ans:['10','dez'],
      exp:'10 × 2 = 20.' },
    { id:'2me173', s:'matematica', t:'Tabuada do 2', type:'mc', diff:1,
      q:'✖️ 2 × 8 = ?',
      opts:['14','16','18','20'], ans:1,
      exp:'2 × 8 = 16.' },
    { id:'2me174', s:'matematica', t:'Tabuada do 2', type:'order', diff:2,
      q:'Ordena os múltiplos de 2 (do menor ao maior):',
      items:['2','6','8','14'],
      ans:'1,2,3,4',
      exp:'2 < 6 < 8 < 14.' },
    { id:'2me175', s:'matematica', t:'Tabuada do 2', type:'mc', diff:2,
      q:'✖️ 5 × 2 = ?',
      opts:['7','10','12','15'], ans:1,
      exp:'5 × 2 = 10.' },
    { id:'2me176', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 6 × 2 = ___',
      ans:['12','doze'],
      exp:'6 × 2 = 12.' },
    { id:'2me177', s:'matematica', t:'Tabuada do 2', type:'fill', diff:1,
      q:'✖️ 9 × 2 = ___',
      ans:['18','dezoito'],
      exp:'9 × 2 = 18.' },
    { id:'2me178', s:'matematica', t:'Tabuada do 2', type:'mc', diff:2,
      q:'✖️ Qual é o dobro do dobro de 3?',
      opts:['6','9','12','15'], ans:2,
      exp:'Dobro de 3 = 6; dobro de 6 = 12.' },
    { id:'2me179', s:'matematica', t:'Tabuada do 2', type:'problem', diff:2,
      q:'🍐 A Ana tem 4 sacos com 2 peras cada. Quantas peras tem ao todo?',
      material:['Multiplicação: 4 × 2.'],
      solution:'4 × 2 = 8 peras.',
      ans:'8',
      exp:'Tabuada do 2.' },
    { id:'2me180', s:'matematica', t:'Tabuada do 2', type:'tf', diff:1,
      q:'✖️ 2 × 10 = 20.',
      ans:true,
      exp:'2 × 10 = 20.' },
    { id:'2me181', s:'matematica', t:'Tabuada do 2', type:'mc', diff:3,
      q:'✖️ Quantos pés têm 9 pessoas?',
      opts:['12','16','18','20'], ans:2,
      exp:'9 × 2 = 18 pés.' },

    // ===== Tabuada do 5 (+37) =====
    { id:'2me182', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 0 = ___',
      ans:['0','zero'],
      exp:'5 × 0 = 0.' },
    { id:'2me183', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 4 = ___',
      ans:['20','vinte'],
      exp:'5 × 4 = 20.' },
    { id:'2me184', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 5 = ___',
      ans:['25','vinte e cinco'],
      exp:'5 × 5 = 25.' },
    { id:'2me185', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 5 × 9 = ___',
      ans:['45','quarenta e cinco'],
      exp:'5 × 9 = 45.' },
    { id:'2me186', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 5 × 4 = ?',
      opts:['15','20','25','30'], ans:1,
      exp:'5 × 4 = 20.' },
    { id:'2me187', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 5 × 5 = ?',
      opts:['20','25','30','35'], ans:1,
      exp:'5 × 5 = 25.' },
    { id:'2me188', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 5 × 8 = ?',
      opts:['35','40','45','50'], ans:1,
      exp:'5 × 8 = 40.' },
    { id:'2me189', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 5 × 9 = ?',
      opts:['40','45','50','55'], ans:1,
      exp:'5 × 9 = 45.' },
    { id:'2me190', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 5 × 10 = ?',
      opts:['40','45','50','55'], ans:2,
      exp:'5 × 10 = 50.' },
    { id:'2me191', s:'matematica', t:'Tabuada do 5', type:'tf', diff:1,
      q:'✖️ 5 × 6 = 30.',
      ans:true,
      exp:'5 × 6 = 30.' },
    { id:'2me192', s:'matematica', t:'Tabuada do 5', type:'tf', diff:1,
      q:'✖️ 5 × 4 = 25.',
      ans:false,
      exp:'5 × 4 = 20 (não 25).' },
    { id:'2me193', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ ___ × 5 = 25',
      ans:['5','cinco'],
      exp:'5 × 5 = 25.' },
    { id:'2me194', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ ___ × 5 = 35',
      ans:['7','sete'],
      exp:'7 × 5 = 35.' },
    { id:'2me195', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ 5 × ___ = 50',
      ans:['10','dez'],
      exp:'5 × 10 = 50.' },
    { id:'2me196', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ 5 × ___ = 15',
      ans:['3','três','tres'],
      exp:'5 × 3 = 15.' },
    { id:'2me197', s:'matematica', t:'Tabuada do 5', type:'problem', diff:2,
      q:'💶 Cada bilhete custa €5. Quanto custam 4 bilhetes?',
      material:['Multiplicação: 5 × 4.'],
      solution:'5 × 4 = €20.',
      ans:'20',
      exp:'Tabuada do 5.' },
    { id:'2me198', s:'matematica', t:'Tabuada do 5', type:'problem', diff:2,
      q:'🌸 Cada ramo tem 5 flores. Quantas flores há em 7 ramos?',
      material:['Multiplicação: 5 × 7.'],
      solution:'5 × 7 = 35 flores.',
      ans:'35',
      exp:'Tabuada do 5.' },
    { id:'2me199', s:'matematica', t:'Tabuada do 5', type:'problem', diff:2,
      q:'🍪 Cada saco tem 5 bolachas. Quantas bolachas há em 8 sacos?',
      material:['Multiplicação: 5 × 8.'],
      solution:'5 × 8 = 40 bolachas.',
      ans:'40',
      exp:'Tabuada do 5.' },
    { id:'2me200', s:'matematica', t:'Tabuada do 5', type:'problem', diff:2,
      q:'⚽ Numa equipa há 5 jogadores. Quantos jogadores há em 9 equipas?',
      material:['Multiplicação: 5 × 9.'],
      solution:'5 × 9 = 45 jogadores.',
      ans:'45',
      exp:'Tabuada do 5.' },
    { id:'2me201', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 4 × 5 = ___',
      ans:['20','vinte'],
      exp:'4 × 5 = 20.' },
    { id:'2me202', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 6 × 5 = ___',
      ans:['30','trinta'],
      exp:'6 × 5 = 30.' },
    { id:'2me203', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ 9 × 5 = ___',
      ans:['45','quarenta e cinco'],
      exp:'9 × 5 = 45.' },
    { id:'2me204', s:'matematica', t:'Tabuada do 5', type:'mc', diff:2,
      q:'✖️ Quanto é metade de 50?',
      opts:['10','20','25','30'], ans:2,
      exp:'50 ÷ 2 = 25.' },
    { id:'2me205', s:'matematica', t:'Tabuada do 5', type:'order', diff:2,
      q:'Ordena os múltiplos de 5 (do menor ao maior):',
      items:['25','10','40','15'],
      ans:'2,4,1,3',
      exp:'10 < 15 < 25 < 40.' },
    { id:'2me206', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 5 × 7 = ?',
      opts:['25','30','35','40'], ans:2,
      exp:'5 × 7 = 35.' },
    { id:'2me207', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ ___ × 5 = 45',
      ans:['9','nove'],
      exp:'9 × 5 = 45.' },
    { id:'2me208', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ 5 × ___ = 0',
      ans:['0','zero'],
      exp:'5 × 0 = 0.' },
    { id:'2me209', s:'matematica', t:'Tabuada do 5', type:'mc', diff:2,
      q:'✖️ Que número é múltiplo de 5?',
      opts:['12','27','33','45'], ans:3,
      exp:'45 = 5 × 9.' },
    { id:'2me210', s:'matematica', t:'Tabuada do 5', type:'tf', diff:1,
      q:'✖️ 5 × 8 = 40.',
      ans:true,
      exp:'5 × 8 = 40.' },
    { id:'2me211', s:'matematica', t:'Tabuada do 5', type:'problem', diff:2,
      q:'🪙 A Maria tem 6 moedas de 5 cêntimos. Quanto dinheiro tem?',
      material:['Multiplicação: 5 × 6.'],
      solution:'5 × 6 = 30 cêntimos.',
      ans:'30',
      exp:'Tabuada do 5.' },
    { id:'2me212', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 7 × 5 = ?',
      opts:['25','30','35','40'], ans:2,
      exp:'7 × 5 = 35.' },
    { id:'2me213', s:'matematica', t:'Tabuada do 5', type:'mc', diff:1,
      q:'✖️ 8 × 5 = ?',
      opts:['30','35','40','45'], ans:2,
      exp:'8 × 5 = 40.' },
    { id:'2me214', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ Conta de 5 em 5: 5, 10, 15, 20, ___',
      ans:['25','vinte e cinco'],
      exp:'20 + 5 = 25.' },
    { id:'2me215', s:'matematica', t:'Tabuada do 5', type:'fill', diff:1,
      q:'✖️ Conta de 5 em 5: 35, 40, 45, ___',
      ans:['50','cinquenta'],
      exp:'45 + 5 = 50.' },
    { id:'2me216', s:'matematica', t:'Tabuada do 5', type:'mc', diff:2,
      q:'✖️ 5 × 5 + 5 = ?',
      opts:['25','30','35','40'], ans:1,
      exp:'25 + 5 = 30.' },
    { id:'2me217', s:'matematica', t:'Tabuada do 5', type:'fill', diff:2,
      q:'✖️ Quantas vezes cabe 5 em 25? ___',
      ans:['5','cinco'],
      exp:'25 ÷ 5 = 5.' },
    { id:'2me218', s:'matematica', t:'Tabuada do 5', type:'mc', diff:3,
      q:'✖️ Quantas mãos são precisas para somar 35 dedos?',
      opts:['5','6','7','8'], ans:2,
      exp:'7 × 5 = 35 dedos → 7 mãos.' },

    // ===== Tabuada do 10 (+41) =====
    { id:'2me219', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 0 = ___',
      ans:['0','zero'],
      exp:'10 × 0 = 0.' },
    { id:'2me220', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 2 = ___',
      ans:['20','vinte'],
      exp:'10 × 2 = 20.' },
    { id:'2me221', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 3 = ___',
      ans:['30','trinta'],
      exp:'10 × 3 = 30.' },
    { id:'2me222', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 5 = ___',
      ans:['50','cinquenta'],
      exp:'10 × 5 = 50.' },
    { id:'2me223', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 7 = ___',
      ans:['70','setenta'],
      exp:'10 × 7 = 70.' },
    { id:'2me224', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 10 × 8 = ___',
      ans:['80','oitenta'],
      exp:'10 × 8 = 80.' },
    { id:'2me225', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 2 = ?',
      opts:['10','20','30','40'], ans:1,
      exp:'10 × 2 = 20.' },
    { id:'2me226', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 3 = ?',
      opts:['20','30','40','50'], ans:1,
      exp:'10 × 3 = 30.' },
    { id:'2me227', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 5 = ?',
      opts:['40','45','50','55'], ans:2,
      exp:'10 × 5 = 50.' },
    { id:'2me228', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 7 = ?',
      opts:['60','70','80','90'], ans:1,
      exp:'10 × 7 = 70.' },
    { id:'2me229', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 8 = ?',
      opts:['70','80','90','100'], ans:1,
      exp:'10 × 8 = 80.' },
    { id:'2me230', s:'matematica', t:'Tabuada do 10', type:'tf', diff:1,
      q:'✖️ 10 × 10 = 100.',
      ans:true,
      exp:'10 × 10 = 100.' },
    { id:'2me231', s:'matematica', t:'Tabuada do 10', type:'tf', diff:1,
      q:'✖️ 10 × 5 = 60.',
      ans:false,
      exp:'10 × 5 = 50 (não 60).' },
    { id:'2me232', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ ___ × 10 = 60',
      ans:['6','seis'],
      exp:'6 × 10 = 60.' },
    { id:'2me233', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ ___ × 10 = 80',
      ans:['8','oito'],
      exp:'8 × 10 = 80.' },
    { id:'2me234', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ 10 × ___ = 30',
      ans:['3','três','tres'],
      exp:'10 × 3 = 30.' },
    { id:'2me235', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ 10 × ___ = 100',
      ans:['10','dez'],
      exp:'10 × 10 = 100.' },
    { id:'2me236', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ 10 × ___ = 70',
      ans:['7','sete'],
      exp:'10 × 7 = 70.' },
    { id:'2me237', s:'matematica', t:'Tabuada do 10', type:'problem', diff:2,
      q:'💶 Cada nota vale €10. Quanto valem 6 notas?',
      material:['Multiplicação: 10 × 6.'],
      solution:'10 × 6 = €60.',
      ans:'60',
      exp:'Tabuada do 10.' },
    { id:'2me238', s:'matematica', t:'Tabuada do 10', type:'problem', diff:2,
      q:'🥚 Cada caixa tem 10 ovos. Quantos ovos há em 8 caixas?',
      material:['Multiplicação: 10 × 8.'],
      solution:'10 × 8 = 80 ovos.',
      ans:'80',
      exp:'Tabuada do 10.' },
    { id:'2me239', s:'matematica', t:'Tabuada do 10', type:'problem', diff:2,
      q:'🌳 Cada fila tem 10 árvores. Quantas árvores há em 4 filas?',
      material:['Multiplicação: 10 × 4.'],
      solution:'10 × 4 = 40 árvores.',
      ans:'40',
      exp:'Tabuada do 10.' },
    { id:'2me240', s:'matematica', t:'Tabuada do 10', type:'problem', diff:2,
      q:'🚗 Cada parque tem 10 lugares. Quantos lugares há em 3 parques?',
      material:['Multiplicação: 10 × 3.'],
      solution:'10 × 3 = 30 lugares.',
      ans:'30',
      exp:'Tabuada do 10.' },
    { id:'2me241', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 2 × 10 = ___',
      ans:['20','vinte'],
      exp:'2 × 10 = 20.' },
    { id:'2me242', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 3 × 10 = ___',
      ans:['30','trinta'],
      exp:'3 × 10 = 30.' },
    { id:'2me243', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 5 × 10 = ___',
      ans:['50','cinquenta'],
      exp:'5 × 10 = 50.' },
    { id:'2me244', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 7 × 10 = ___',
      ans:['70','setenta'],
      exp:'7 × 10 = 70.' },
    { id:'2me245', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 9 × 10 = ___',
      ans:['90','noventa'],
      exp:'9 × 10 = 90.' },
    { id:'2me246', s:'matematica', t:'Tabuada do 10', type:'mc', diff:2,
      q:'✖️ Os múltiplos de 10 acabam sempre em:',
      opts:['1','5','0','9'], ans:2,
      exp:'10, 20, 30… acabam em 0.' },
    { id:'2me247', s:'matematica', t:'Tabuada do 10', type:'order', diff:2,
      q:'Ordena os múltiplos de 10 (do menor ao maior):',
      items:['50','20','80','30'],
      ans:'2,4,1,3',
      exp:'20 < 30 < 50 < 80.' },
    { id:'2me248', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ Conta de 10 em 10: 60, 70, 80, ?',
      opts:['85','90','95','100'], ans:1,
      exp:'80 + 10 = 90.' },
    { id:'2me249', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ Conta de 10 em 10: 70, 80, 90, ___',
      ans:['100','cem'],
      exp:'90 + 10 = 100.' },
    { id:'2me250', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 6 = ?',
      opts:['50','60','70','80'], ans:1,
      exp:'10 × 6 = 60.' },
    { id:'2me251', s:'matematica', t:'Tabuada do 10', type:'tf', diff:1,
      q:'✖️ Para multiplicar por 10 basta juntar um zero ao número.',
      ans:true,
      exp:'4 × 10 = 40, 7 × 10 = 70.' },
    { id:'2me252', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ Quantas dezenas há em 70? ___',
      ans:['7','sete'],
      exp:'70 = 7 dezenas.' },
    { id:'2me253', s:'matematica', t:'Tabuada do 10', type:'mc', diff:2,
      q:'✖️ Quantas vezes cabe 10 em 50?',
      opts:['3','4','5','6'], ans:2,
      exp:'50 ÷ 10 = 5.' },
    { id:'2me254', s:'matematica', t:'Tabuada do 10', type:'fill', diff:2,
      q:'✖️ 10 × 4 = ___',
      ans:['40','quarenta'],
      exp:'10 × 4 = 40.' },
    { id:'2me255', s:'matematica', t:'Tabuada do 10', type:'mc', diff:1,
      q:'✖️ 10 × 1 = ?',
      opts:['1','10','11','100'], ans:1,
      exp:'10 × 1 = 10.' },
    { id:'2me256', s:'matematica', t:'Tabuada do 10', type:'problem', diff:2,
      q:'🎈 Cada amigo levou 10 balões para a festa. Quantos balões levaram 5 amigos?',
      material:['Multiplicação: 10 × 5.'],
      solution:'10 × 5 = 50 balões.',
      ans:'50',
      exp:'Tabuada do 10.' },
    { id:'2me257', s:'matematica', t:'Tabuada do 10', type:'mc', diff:2,
      q:'✖️ Que número é múltiplo de 10?',
      opts:['25','40','55','77'], ans:1,
      exp:'40 acaba em 0 → múltiplo de 10.' },
    { id:'2me258', s:'matematica', t:'Tabuada do 10', type:'fill', diff:1,
      q:'✖️ 8 × 10 = ___',
      ans:['80','oitenta'],
      exp:'8 × 10 = 80.' },
    { id:'2me259', s:'matematica', t:'Tabuada do 10', type:'mc', diff:3,
      q:'✖️ Quantos dedos têm 10 mãos?',
      opts:['50','100','10','20'], ans:0,
      exp:'10 × 5 = 50 dedos.' },

    // ===== Sólidos geométricos (+41) =====
    { id:'2me260', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'⚽ Uma bola de futebol tem a forma de:',
      opts:['cubo','esfera','cone','cilindro'], ans:1,
      exp:'A bola é uma esfera.' },
    { id:'2me261', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🎲 Quantas faces tem um cubo?',
      opts:['4','5','6','8'], ans:2,
      exp:'O cubo tem 6 faces quadradas.' },
    { id:'2me262', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🌍 A Terra tem a forma aproximada de:',
      opts:['cubo','esfera','cone','pirâmide'], ans:1,
      exp:'A Terra é (quase) esférica.' },
    { id:'2me263', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🏛️ As pirâmides do Egito têm a forma de:',
      opts:['cubo','cone','pirâmide','cilindro'], ans:2,
      exp:'Têm forma de pirâmide.' },
    { id:'2me264', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🥫 Uma lata de atum tem a forma de:',
      opts:['cubo','cone','cilindro','esfera'], ans:2,
      exp:'A lata é um cilindro.' },
    { id:'2me265', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🧊 Um cubo de gelo tem a forma de:',
      opts:['esfera','cubo','cone','pirâmide'], ans:1,
      exp:'É um cubo.' },
    { id:'2me266', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🪅 Um chapéu de aniversário (em ponta) tem a forma de:',
      opts:['cone','cubo','esfera','cilindro'], ans:0,
      exp:'É um cone.' },
    { id:'2me267', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'📚 Um livro tem a forma de:',
      opts:['cubo','paralelepípedo','esfera','cone'], ans:1,
      exp:'O livro é um paralelepípedo.' },
    { id:'2me268', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:1,
      q:'🎲 O cubo tem ___ faces.',
      ans:['6','seis'],
      exp:'6 faces quadradas.' },
    { id:'2me269', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:1,
      q:'⚽ A esfera tem ___ faces planas.',
      ans:['0','zero','nenhuma'],
      exp:'A esfera não tem faces planas.' },
    { id:'2me270', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:2,
      q:'🥫 O cilindro tem ___ faces planas (em cima e em baixo).',
      ans:['2','duas'],
      exp:'O cilindro tem 2 bases circulares planas.' },
    { id:'2me271', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:2,
      q:'🪅 O cone tem ___ vértice (ponta).',
      ans:['1','um'],
      exp:'O cone tem 1 vértice (a ponta).' },
    { id:'2me272', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:1,
      q:'🎲 Todas as faces de um cubo são quadradas.',
      ans:true,
      exp:'O cubo tem 6 faces quadradas iguais.' },
    { id:'2me273', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:1,
      q:'⚽ A esfera rola facilmente.',
      ans:true,
      exp:'É arredondada, por isso rola.' },
    { id:'2me274', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:1,
      q:'🎲 O cubo rola facilmente.',
      ans:false,
      exp:'O cubo tem faces planas, não rola.' },
    { id:'2me275', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🔺 Quantas arestas (lados) tem um cubo?',
      opts:['6','8','10','12'], ans:3,
      exp:'O cubo tem 12 arestas.' },
    { id:'2me276', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🎲 Quantos vértices (cantos) tem um cubo?',
      opts:['4','6','8','12'], ans:2,
      exp:'O cubo tem 8 vértices.' },
    { id:'2me277', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'📦 Qual destes objetos NÃO é um sólido geométrico?',
      opts:['caixa','bola','triângulo desenhado','cone'], ans:2,
      exp:'O triângulo desenhado é figura plana.' },
    { id:'2me278', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'⚽ Qual destes sólidos NÃO tem nenhum vértice?',
      opts:['cubo','cone','esfera','pirâmide'], ans:2,
      exp:'A esfera não tem vértices.' },
    { id:'2me279', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🍦 Qual destes rola facilmente?',
      opts:['cubo','paralelepípedo','esfera','pirâmide'], ans:2,
      exp:'A esfera rola.' },
    { id:'2me280', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'📦 Uma caixa de cereais tem a forma de:',
      opts:['cubo','paralelepípedo','cilindro','esfera'], ans:1,
      exp:'É um paralelepípedo.' },
    { id:'2me281', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🪙 Qual destes sólidos tem 2 bases circulares?',
      opts:['cubo','cone','cilindro','esfera'], ans:2,
      exp:'O cilindro tem 2 bases circulares.' },
    { id:'2me282', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🔺 A pirâmide tem uma base e termina em:',
      opts:['círculo','vértice (ponta)','quadrado','linha'], ans:1,
      exp:'Termina num vértice (ponta).' },
    { id:'2me283', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:1,
      q:'📦 Diz o nome do sólido: caixa de sapatos → ___',
      ans:['paralelepípedo','paralelepipedo'],
      exp:'É um paralelepípedo.' },
    { id:'2me284', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:1,
      q:'⚽ Diz o nome do sólido: bola → ___',
      ans:['esfera'],
      exp:'É uma esfera.' },
    { id:'2me285', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:1,
      q:'🍦 Diz o nome do sólido: gelado de ponta → ___',
      ans:['cone'],
      exp:'É um cone.' },
    { id:'2me286', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:1,
      q:'🥫 Diz o nome do sólido: lata → ___',
      ans:['cilindro'],
      exp:'É um cilindro.' },
    { id:'2me287', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🎲 Qual destes objetos é um cubo?',
      opts:['lata','dado','bola','livro'], ans:1,
      exp:'O dado é um cubo.' },
    { id:'2me288', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'⚽ Quantas faces tem uma esfera?',
      opts:['1 (curva)','2','4','6'], ans:0,
      exp:'A esfera tem 1 superfície curva.' },
    { id:'2me289', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:1,
      q:'🥫 O cilindro tem 2 bases iguais.',
      ans:true,
      exp:'As 2 bases são círculos iguais.' },
    { id:'2me290', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:1,
      q:'📦 O paralelepípedo tem 6 faces.',
      ans:true,
      exp:'Sim, 6 faces (retângulos).' },
    { id:'2me291', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🍦 O cone tem ___ base(s) circular(es).',
      opts:['0','1','2','3'], ans:1,
      exp:'O cone tem 1 base circular.' },
    { id:'2me292', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🌐 Qual destes objetos é uma esfera?',
      opts:['lata','globo','caixa','dado'], ans:1,
      exp:'O globo terrestre é uma esfera.' },
    { id:'2me293', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🔺 Quais sólidos têm faces planas?',
      opts:['cubo e paralelepípedo','esfera','só a bola','só a lata'], ans:0,
      exp:'Cubo e paralelepípedo só têm faces planas.' },
    { id:'2me294', s:'matematica', t:'Sólidos geométricos', type:'fill', diff:2,
      q:'🎲 O cubo tem ___ vértices.',
      ans:['8','oito'],
      exp:'O cubo tem 8 vértices.' },
    { id:'2me295', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🥫 Qual destes sólidos tem forma redonda no meio?',
      opts:['cubo','paralelepípedo','cilindro','pirâmide'], ans:2,
      exp:'O cilindro é redondo no meio.' },
    { id:'2me296', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🎂 Um bolo redondo tem a forma de:',
      opts:['cubo','cilindro','cone','esfera'], ans:1,
      exp:'É um cilindro.' },
    { id:'2me297', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:1,
      q:'🪙 Uma moeda tem (em forma de sólido):',
      opts:['esfera','cilindro muito fino','cubo','cone'], ans:1,
      exp:'A moeda é um cilindro fino.' },
    { id:'2me298', s:'matematica', t:'Sólidos geométricos', type:'tf', diff:1,
      q:'🔺 A pirâmide tem uma ponta no topo.',
      ans:true,
      exp:'Sim, termina num vértice.' },
    { id:'2me299', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:2,
      q:'🎲 Qual destes sólidos não rola?',
      opts:['esfera','cilindro','cone','cubo'], ans:3,
      exp:'O cubo não rola (tem só faces planas).' },
    { id:'2me300', s:'matematica', t:'Sólidos geométricos', type:'mc', diff:3,
      q:'🔺 A pirâmide com base quadrada tem quantas faces ao todo?',
      opts:['4','5','6','8'], ans:1,
      exp:'1 base quadrada + 4 triângulos = 5 faces.' },

    // ===== Figuras planas (+38) =====
    { id:'2me301', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🔺 Qual figura tem 3 lados?',
      opts:['quadrado','triângulo','retângulo','círculo'], ans:1,
      exp:'O triângulo tem 3 lados.' },
    { id:'2me302', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'⬜ Qual figura tem 4 lados todos iguais?',
      opts:['retângulo','quadrado','triângulo','círculo'], ans:1,
      exp:'O quadrado tem 4 lados iguais.' },
    { id:'2me303', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🟦 Qual figura tem 4 lados, 2 a 2 iguais?',
      opts:['quadrado','triângulo','retângulo','pentágono'], ans:2,
      exp:'O retângulo tem 4 lados (2 grandes e 2 pequenos iguais).' },
    { id:'2me304', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🔵 Qual destas figuras é redonda (sem lados)?',
      opts:['triângulo','quadrado','círculo','retângulo'], ans:2,
      exp:'O círculo é redondo.' },
    { id:'2me305', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'🔺 O triângulo tem ___ lados.',
      ans:['3','três','tres'],
      exp:'3 lados.' },
    { id:'2me306', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'⬜ O quadrado tem ___ lados.',
      ans:['4','quatro'],
      exp:'4 lados iguais.' },
    { id:'2me307', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'🟦 O retângulo tem ___ lados.',
      ans:['4','quatro'],
      exp:'4 lados.' },
    { id:'2me308', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'🔵 O círculo tem ___ lados.',
      ans:['0','zero','nenhum'],
      exp:'O círculo é redondo (sem lados retos).' },
    { id:'2me309', s:'matematica', t:'Figuras planas', type:'fill', diff:2,
      q:'⬠ O pentágono tem ___ lados.',
      ans:['5','cinco'],
      exp:'O pentágono tem 5 lados.' },
    { id:'2me310', s:'matematica', t:'Figuras planas', type:'fill', diff:2,
      q:'⬡ O hexágono tem ___ lados.',
      ans:['6','seis'],
      exp:'O hexágono tem 6 lados.' },
    { id:'2me311', s:'matematica', t:'Figuras planas', type:'mc', diff:2,
      q:'⬠ Quantos lados tem um pentágono?',
      opts:['3','4','5','6'], ans:2,
      exp:'5 lados.' },
    { id:'2me312', s:'matematica', t:'Figuras planas', type:'mc', diff:2,
      q:'⬡ Quantos lados tem um hexágono?',
      opts:['5','6','7','8'], ans:1,
      exp:'6 lados.' },
    { id:'2me313', s:'matematica', t:'Figuras planas', type:'tf', diff:1,
      q:'🔺 Um triângulo tem 3 vértices.',
      ans:true,
      exp:'3 lados → 3 vértices.' },
    { id:'2me314', s:'matematica', t:'Figuras planas', type:'tf', diff:1,
      q:'⬜ Um quadrado tem todos os lados iguais.',
      ans:true,
      exp:'Sim, 4 lados iguais.' },
    { id:'2me315', s:'matematica', t:'Figuras planas', type:'tf', diff:1,
      q:'🔵 O círculo tem 4 vértices.',
      ans:false,
      exp:'O círculo não tem vértices.' },
    { id:'2me316', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'⬜ Um quadrado tem ___ vértices (cantos).',
      opts:['2','3','4','5'], ans:2,
      exp:'4 vértices.' },
    { id:'2me317', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🟦 Um retângulo tem ___ vértices.',
      opts:['3','4','5','6'], ans:1,
      exp:'4 vértices.' },
    { id:'2me318', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🍕 Que forma tem uma fatia de pizza?',
      opts:['quadrado','triângulo','círculo','retângulo'], ans:1,
      exp:'A fatia é triangular.' },
    { id:'2me319', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🪟 Que forma tem normalmente uma janela?',
      opts:['triângulo','retângulo','círculo','pentágono'], ans:1,
      exp:'As janelas são geralmente retângulos.' },
    { id:'2me320', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🚸 Os sinais de aviso (triangulares) têm forma de:',
      opts:['quadrado','triângulo','círculo','retângulo'], ans:1,
      exp:'São triângulos.' },
    { id:'2me321', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🔵 Que forma tem um prato?',
      opts:['quadrado','triângulo','círculo','pentágono'], ans:2,
      exp:'O prato é um círculo.' },
    { id:'2me322', s:'matematica', t:'Figuras planas', type:'mc', diff:2,
      q:'🔷 Quantos lados tem um losango?',
      opts:['3','4','5','6'], ans:1,
      exp:'O losango tem 4 lados.' },
    { id:'2me323', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'🔺 Diz o nome da figura com 3 lados: ___',
      ans:['triângulo','triangulo'],
      exp:'É o triângulo.' },
    { id:'2me324', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'⬜ Diz o nome da figura com 4 lados iguais: ___',
      ans:['quadrado'],
      exp:'É o quadrado.' },
    { id:'2me325', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'🔵 Diz o nome da figura redonda: ___',
      ans:['círculo','circulo'],
      exp:'É o círculo.' },
    { id:'2me326', s:'matematica', t:'Figuras planas', type:'fill', diff:2,
      q:'⬠ Diz o nome da figura com 5 lados: ___',
      ans:['pentágono','pentagono'],
      exp:'É o pentágono.' },
    { id:'2me327', s:'matematica', t:'Figuras planas', type:'fill', diff:2,
      q:'⬡ Diz o nome da figura com 6 lados: ___',
      ans:['hexágono','hexagono'],
      exp:'É o hexágono.' },
    { id:'2me328', s:'matematica', t:'Figuras planas', type:'mc', diff:2,
      q:'🐝 As células do favo de mel são:',
      opts:['triângulos','quadrados','hexágonos','círculos'], ans:2,
      exp:'As abelhas constroem hexágonos.' },
    { id:'2me329', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'⚽ A bola de futebol tem partes em forma de:',
      opts:['só círculos','pentágonos e hexágonos','só quadrados','só triângulos'], ans:1,
      exp:'Tem pentágonos e hexágonos.' },
    { id:'2me330', s:'matematica', t:'Figuras planas', type:'mc', diff:2,
      q:'🟥 Quantos vértices tem o pentágono?',
      opts:['3','4','5','6'], ans:2,
      exp:'5 vértices.' },
    { id:'2me331', s:'matematica', t:'Figuras planas', type:'mc', diff:2,
      q:'🟧 Quantos vértices tem o hexágono?',
      opts:['4','5','6','7'], ans:2,
      exp:'6 vértices.' },
    { id:'2me332', s:'matematica', t:'Figuras planas', type:'tf', diff:1,
      q:'🔺 O triângulo é uma figura plana.',
      ans:true,
      exp:'Sim, desenha-se num plano.' },
    { id:'2me333', s:'matematica', t:'Figuras planas', type:'tf', diff:1,
      q:'⚽ A bola de futebol é uma figura plana.',
      ans:false,
      exp:'A bola é um sólido (esfera), não uma figura plana.' },
    { id:'2me334', s:'matematica', t:'Figuras planas', type:'order', diff:2,
      q:'Ordena as figuras pelo número de lados (do menor ao maior):',
      items:['hexágono','triângulo','pentágono','quadrado'],
      ans:'2,4,3,1',
      exp:'Triângulo(3), quadrado(4), pentágono(5), hexágono(6).' },
    { id:'2me335', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🟦 Em que figura os 4 lados são, 2 a 2, do mesmo tamanho mas não todos iguais?',
      opts:['quadrado','retângulo','círculo','triângulo'], ans:1,
      exp:'O retângulo tem 2 lados curtos e 2 lados longos.' },
    { id:'2me336', s:'matematica', t:'Figuras planas', type:'mc', diff:1,
      q:'🔵 Em vez de lados, o círculo tem:',
      opts:['vértices','arestas','uma linha curva','triângulos'], ans:2,
      exp:'É uma linha curva fechada.' },
    { id:'2me337', s:'matematica', t:'Figuras planas', type:'fill', diff:1,
      q:'⬜ Quantos vértices tem o quadrado? ___',
      ans:['4','quatro'],
      exp:'O quadrado tem 4 vértices.' },
    { id:'2me338', s:'matematica', t:'Figuras planas', type:'mc', diff:3,
      q:'🔺 Um triângulo com todos os lados iguais chama-se:',
      opts:['equilátero','retângulo','isósceles','escaleno'], ans:0,
      exp:'Triângulo equilátero (todos os lados iguais).' },

    // ===== Medir tempo (+38) =====
    { id:'2me339', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'⏰ Um dia tem ___ horas.',
      ans:['24','vinte e quatro'],
      exp:'1 dia = 24 horas.' },
    { id:'2me340', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 Uma semana tem ___ dias.',
      ans:['7','sete'],
      exp:'1 semana = 7 dias.' },
    { id:'2me341', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 Um ano tem ___ meses.',
      ans:['12','doze'],
      exp:'1 ano = 12 meses.' },
    { id:'2me342', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'⏱️ Uma hora tem ___ minutos.',
      ans:['60','sessenta'],
      exp:'1 hora = 60 minutos.' },
    { id:'2me343', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'⏱️ Meia hora tem ___ minutos.',
      ans:['30','trinta'],
      exp:'½ hora = 30 minutos.' },
    { id:'2me344', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'⏱️ Um quarto de hora tem ___ minutos.',
      ans:['15','quinze'],
      exp:'¼ hora = 15 minutos.' },
    { id:'2me345', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Quantos dias tem o fim de semana?',
      opts:['1','2','3','7'], ans:1,
      exp:'Sábado e domingo = 2 dias.' },
    { id:'2me346', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Quantas semanas tem 1 mês (aproximadamente)?',
      opts:['2','3','4','5'], ans:2,
      exp:'1 mês ≈ 4 semanas.' },
    { id:'2me347', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Que mês vem depois de Maio?',
      opts:['Abril','Junho','Julho','Setembro'], ans:1,
      exp:'Junho vem depois de Maio.' },
    { id:'2me348', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Que mês vem antes de Setembro?',
      opts:['Julho','Agosto','Outubro','Junho'], ans:1,
      exp:'Agosto vem antes de Setembro.' },
    { id:'2me349', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'⏰ A que horas costumas almoçar?',
      opts:['8h da manhã','13h','19h','22h'], ans:1,
      exp:'O almoço é por volta das 13h.' },
    { id:'2me350', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'⏰ Quando dormimos, é geralmente:',
      opts:['de manhã','à tarde','de noite','ao meio-dia'], ans:2,
      exp:'Dormimos de noite.' },
    { id:'2me351', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Em que estação caem as folhas das árvores?',
      opts:['primavera','verão','outono','inverno'], ans:2,
      exp:'No outono caem as folhas.' },
    { id:'2me352', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'❄️ A estação mais fria é:',
      opts:['primavera','verão','outono','inverno'], ans:3,
      exp:'O inverno é a estação mais fria.' },
    { id:'2me353', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'☀️ A estação mais quente é:',
      opts:['primavera','verão','outono','inverno'], ans:1,
      exp:'O verão é a estação mais quente.' },
    { id:'2me354', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 O ano tem ___ estações.',
      ans:['4','quatro'],
      exp:'4 estações: primavera, verão, outono e inverno.' },
    { id:'2me355', s:'matematica', t:'Medir tempo', type:'order', diff:2,
      q:'Ordena os dias da semana:',
      items:['quarta-feira','segunda-feira','sexta-feira','quinta-feira'],
      ans:'2,1,4,3',
      exp:'Segunda, quarta, quinta, sexta.' },
    { id:'2me356', s:'matematica', t:'Medir tempo', type:'order', diff:2,
      q:'Ordena os meses:',
      items:['Maio','Fevereiro','Agosto','Novembro'],
      ans:'2,1,3,4',
      exp:'Fevereiro(2), Maio(5), Agosto(8), Novembro(11).' },
    { id:'2me357', s:'matematica', t:'Medir tempo', type:'order', diff:2,
      q:'Ordena as estações (começando pela primavera):',
      items:['primavera','verão','outono','inverno'],
      ans:'1,2,3,4',
      exp:'Primavera → verão → outono → inverno.' },
    { id:'2me358', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'⏰ O ponteiro pequeno do relógio marca as ___:',
      opts:['horas','minutos','segundos','dias'], ans:0,
      exp:'O ponteiro pequeno marca as horas.' },
    { id:'2me359', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'⏰ O ponteiro grande do relógio marca os ___:',
      opts:['horas','minutos','dias','meses'], ans:1,
      exp:'O ponteiro grande marca os minutos.' },
    { id:'2me360', s:'matematica', t:'Medir tempo', type:'tf', diff:1,
      q:'⏰ 1 hora = 60 minutos.',
      ans:true,
      exp:'1 h = 60 min.' },
    { id:'2me361', s:'matematica', t:'Medir tempo', type:'tf', diff:1,
      q:'📅 1 ano = 10 meses.',
      ans:false,
      exp:'1 ano = 12 meses.' },
    { id:'2me362', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 Há ___ dias num fim de semana.',
      ans:['2','dois'],
      exp:'Sábado + domingo = 2 dias.' },
    { id:'2me363', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'📅 Quantos dias tem o mês de Abril?',
      opts:['28','30','31','29'], ans:1,
      exp:'Abril tem 30 dias.' },
    { id:'2me364', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'📅 Quantos dias tem o mês de Janeiro?',
      opts:['28','29','30','31'], ans:3,
      exp:'Janeiro tem 31 dias.' },
    { id:'2me365', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Que dia da semana vem depois de quarta-feira?',
      opts:['terça','quinta','sexta','sábado'], ans:1,
      exp:'Quinta-feira.' },
    { id:'2me366', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Que dia da semana vem antes de domingo?',
      opts:['sexta','sábado','segunda','quinta'], ans:1,
      exp:'Sábado.' },
    { id:'2me367', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 Há ___ dias úteis numa semana (de segunda a sexta).',
      ans:['5','cinco'],
      exp:'Segunda, terça, quarta, quinta, sexta = 5.' },
    { id:'2me368', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'⏰ Quantas meias horas há numa hora?',
      opts:['1','2','3','4'], ans:1,
      exp:'1 hora = 2 meias horas.' },
    { id:'2me369', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'⏰ Quantos quartos de hora há numa hora?',
      opts:['2','3','4','5'], ans:2,
      exp:'1 hora = 4 quartos de hora.' },
    { id:'2me370', s:'matematica', t:'Medir tempo', type:'problem', diff:2,
      q:'⏰ A escola começa às 9h e dura 4 horas. A que horas termina?',
      material:['Adição: 9 + 4.'],
      solution:'9 + 4 = 13h.',
      ans:'13h',
      exp:'Termina às 13h.' },
    { id:'2me371', s:'matematica', t:'Medir tempo', type:'problem', diff:2,
      q:'📅 Em quantos dias se faz 2 semanas?',
      material:['Multiplicação: 2 × 7.'],
      solution:'2 × 7 = 14 dias.',
      ans:'14',
      exp:'2 semanas = 14 dias.' },
    { id:'2me372', s:'matematica', t:'Medir tempo', type:'mc', diff:1,
      q:'📅 Aniversário acontece quantas vezes por ano?',
      opts:['1','2','12','365'], ans:0,
      exp:'1 vez por ano.' },
    { id:'2me373', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'⏰ Se o relógio marca 3:30, são:',
      opts:['3 e meia','3 e um quarto','3 e dez','3 em ponto'], ans:0,
      exp:'3:30 = 3 e meia.' },
    { id:'2me374', s:'matematica', t:'Medir tempo', type:'mc', diff:2,
      q:'⏰ Se o relógio marca 6:15, são:',
      opts:['6 e meia','6 e um quarto','6 em ponto','6 e três quartos'], ans:1,
      exp:'6:15 = 6 e um quarto.' },
    { id:'2me375', s:'matematica', t:'Medir tempo', type:'fill', diff:1,
      q:'📅 Que mês comemora o Natal? ___',
      ans:['Dezembro','dezembro'],
      exp:'O Natal é a 25 de Dezembro.' },
    { id:'2me376', s:'matematica', t:'Medir tempo', type:'mc', diff:3,
      q:'📅 Quantos dias tem 1 ano normal?',
      opts:['360','365','366','400'], ans:1,
      exp:'1 ano normal = 365 dias (366 se for bissexto).' },

    // ===== Dinheiro (€) (+36) =====
    { id:'2me377', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Qual é a moeda de menor valor?',
      opts:['€0,01','€0,05','€0,10','€0,50'], ans:0,
      exp:'1 cêntimo (€0,01) é a moeda de menor valor.' },
    { id:'2me378', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Qual é a moeda de maior valor?',
      opts:['€0,50','€1','€2','€5'], ans:2,
      exp:'A moeda de maior valor é €2 (€5 é nota).' },
    { id:'2me379', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Qual destas é uma nota?',
      opts:['€0,50','€1','€2','€5'], ans:3,
      exp:'€5 é nota; €1 e €2 são moedas.' },
    { id:'2me380', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Quantos cêntimos tem €1?',
      opts:['10','50','100','1000'], ans:2,
      exp:'€1 = 100 cêntimos.' },
    { id:'2me381', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 €1 = ___ cêntimos.',
      ans:['100','cem'],
      exp:'€1 = 100 cêntimos.' },
    { id:'2me382', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 €2 = ___ cêntimos.',
      ans:['200','duzentos'],
      exp:'€2 = 200 cêntimos.' },
    { id:'2me383', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 2 moedas de €1 = €___',
      ans:['2','dois'],
      exp:'1 + 1 = 2.' },
    { id:'2me384', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 5 moedas de €1 = €___',
      ans:['5','cinco'],
      exp:'5 × €1 = €5.' },
    { id:'2me385', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 2 moedas de 50 cêntimos = €___',
      ans:['1','um','1,00'],
      exp:'50 + 50 = 100 cêntimos = €1.' },
    { id:'2me386', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:2,
      q:'💶 4 moedas de 50 cêntimos = €___',
      ans:['2','dois','2,00'],
      exp:'4 × 50 = 200 cêntimos = €2.' },
    { id:'2me387', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:2,
      q:'💶 10 moedas de 10 cêntimos = €___',
      ans:['1','um','1,00'],
      exp:'10 × 10 = 100 cêntimos = €1.' },
    { id:'2me388', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Quantas moedas de €1 são precisas para fazer €5?',
      opts:['2','3','4','5'], ans:3,
      exp:'5 × €1 = €5.' },
    { id:'2me389', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Quantas moedas de €2 são precisas para fazer €10?',
      opts:['3','4','5','6'], ans:2,
      exp:'5 × €2 = €10.' },
    { id:'2me390', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 Quantas moedas de €0,50 são precisas para fazer €5?',
      opts:['5','8','10','12'], ans:2,
      exp:'10 × €0,50 = €5.' },
    { id:'2me391', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 €1 + €0,50 = €?',
      opts:['€0,50','€1,00','€1,50','€2,00'], ans:2,
      exp:'1 + 0,50 = 1,50.' },
    { id:'2me392', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 €2 + €1 + €0,50 = €?',
      opts:['€2,50','€3,00','€3,50','€4,00'], ans:2,
      exp:'2 + 1 + 0,50 = 3,50.' },
    { id:'2me393', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:2,
      q:'💶 €5 + €5 = €___',
      ans:['10','dez','10,00'],
      exp:'5 + 5 = 10.' },
    { id:'2me394', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:2,
      q:'💶 €10 + €5 = €___',
      ans:['15','quinze','15,00'],
      exp:'10 + 5 = 15.' },
    { id:'2me395', s:'matematica', t:'Dinheiro (€)', type:'tf', diff:1,
      q:'💶 Existe uma nota de €1.',
      ans:false,
      exp:'€1 é moeda, não nota.' },
    { id:'2me396', s:'matematica', t:'Dinheiro (€)', type:'tf', diff:1,
      q:'💶 €0,50 é o mesmo que 50 cêntimos.',
      ans:true,
      exp:'€0,50 = 50 cêntimos.' },
    { id:'2me397', s:'matematica', t:'Dinheiro (€)', type:'tf', diff:1,
      q:'💶 €2 é igual a 200 cêntimos.',
      ans:true,
      exp:'€2 = 200 cêntimos.' },
    { id:'2me398', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🍞 Um pão custa €0,60. Quanto pago por 2 pães?',
      material:['Adição/Multiplicação: 0,60 + 0,60.'],
      solution:'0,60 + 0,60 = €1,20.',
      ans:'1,20',
      exp:'Total €1,20.' },
    { id:'2me399', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🍫 Um chocolate custa €1,50. Tinha €5. Quanto recebo de troco?',
      material:['Subtração: 5 - 1,50.'],
      solution:'5 - 1,50 = €3,50.',
      ans:'3,50',
      exp:'O troco é €3,50.' },
    { id:'2me400', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🥐 Um croissant custa €1. Quanto custam 4 croissants?',
      material:['Multiplicação: 1 × 4.'],
      solution:'1 × 4 = €4.',
      ans:'4',
      exp:'Total €4.' },
    { id:'2me401', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🪙 A Maria tem 3 moedas de €2 e 1 de €1. Quanto tem?',
      material:['Adição: 2 + 2 + 2 + 1.'],
      solution:'3 × 2 + 1 = 6 + 1 = €7.',
      ans:'7',
      exp:'Total €7.' },
    { id:'2me402', s:'matematica', t:'Dinheiro (€)', type:'problem', diff:2,
      q:'🍎 Uma maçã custa €0,50. Quanto custam 4 maçãs?',
      material:['Multiplicação: 0,50 × 4.'],
      solution:'0,50 × 4 = €2.',
      ans:'2',
      exp:'4 × 50 cêntimos = 200 cêntimos = €2.' },
    { id:'2me403', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 Tinha €10 e gastei €3. Quanto sobrou?',
      opts:['€5','€6','€7','€8'], ans:2,
      exp:'10 - 3 = €7.' },
    { id:'2me404', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 Tinha €20 e gastei €8. Quanto sobrou?',
      opts:['€10','€11','€12','€13'], ans:2,
      exp:'20 - 8 = €12.' },
    { id:'2me405', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 €0,10 = ___ cêntimos.',
      ans:['10','dez'],
      exp:'10 cêntimos.' },
    { id:'2me406', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:1,
      q:'💶 €0,20 = ___ cêntimos.',
      ans:['20','vinte'],
      exp:'20 cêntimos.' },
    { id:'2me407', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:1,
      q:'💶 Qual destas notas existe?',
      opts:['€3','€7','€10','€15'], ans:2,
      exp:'Existe nota de €10 (também €5, €20, €50).' },
    { id:'2me408', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 Quantas moedas de €0,20 são precisas para €1?',
      opts:['2','3','4','5'], ans:3,
      exp:'5 × 20 = 100 cêntimos = €1.' },
    { id:'2me409', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 €0,50 + €0,50 + €0,50 + €0,50 = €?',
      opts:['€1','€1,50','€2','€2,50'], ans:2,
      exp:'4 × 0,50 = 2.' },
    { id:'2me410', s:'matematica', t:'Dinheiro (€)', type:'fill', diff:2,
      q:'💶 €1 + €2 + €5 = €___',
      ans:['8','oito','8,00'],
      exp:'1 + 2 + 5 = 8.' },
    { id:'2me411', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:2,
      q:'💶 Para pagar €15 sem trocos, podes usar:',
      opts:['1 nota de €10 e 1 nota de €5','1 nota de €20','3 moedas de €2','5 moedas de €1'], ans:0,
      exp:'€10 + €5 = €15.' },
    { id:'2me412', s:'matematica', t:'Dinheiro (€)', type:'mc', diff:3,
      q:'💶 Tinha €20 e comprei um livro por €12,50. Quanto recebo de troco?',
      opts:['€7,00','€7,50','€8,00','€8,50'], ans:1,
      exp:'20 - 12,50 = €7,50.' }

];
if (typeof window !== 'undefined') window.EXERCISES_2_M_EXTRA2 = EXERCISES_2_M_EXTRA2;
