// EscolaPlay - Top-up dificuldade 3 do 2.º ano - Inglês (gerado, A1- CEFR, alinhado com Kids Box 1)
const EXERCISES_2_I_EXTRA3 = [
  // Cumprimentos
  { id:'2ie3_001', s:'ingles', t:'Cumprimentos', type:'mc', diff:3,
    q:'👋 Como dizes "Boa noite" (ao deitar) em inglês?',
    opts:['Good evening','Good night','Good morning'], ans:1,
    exp:'"Good night" é quando vais dormir. "Good evening" é "Boa tarde/noite" ao chegar.' },
  { id:'2ie3_002', s:'ingles', t:'Cumprimentos', type:'tf', diff:3,
    q:'"How are you?" significa "Como te chamas?".',
    ans:false,
    exp:'"How are you?" significa "Como estás?". "Como te chamas?" é "What is your name?".' },
  { id:'2ie3_003', s:'ingles', t:'Cumprimentos', type:'mc', diff:3,
    q:'Que respondes a "How are you?"?',
    opts:['I am 7 years old.','I am fine, thank you.','My name is Ana.'], ans:1,
    exp:'Respondes como te sentes: "I am fine, thank you." (Estou bem, obrigado/a.)' },
  { id:'2ie3_004', s:'ingles', t:'Cumprimentos', type:'fill', diff:3,
    q:'Completa: "___ morning, teacher!" (de manhã)',
    ans:['Good','good'],
    exp:'"Good morning" significa "Bom dia".' },
  { id:'2ie3_005', s:'ingles', t:'Cumprimentos', type:'mc', diff:3,
    q:'Para te despedires à tarde, dizes...',
    opts:['Hello!','Goodbye!','Good night!'], ans:1,
    exp:'"Goodbye!" significa "Adeus!". Usa-se a qualquer hora para te despedires.' },

  // Números
  { id:'2ie3_006', s:'ingles', t:'Números', type:'mc', diff:3,
    q:'🔢 Quanto é "twelve" + "three"?',
    opts:['fifteen','thirteen','fourteen'], ans:0,
    exp:'twelve = 12, three = 3. 12 + 3 = 15 = "fifteen".' },
  { id:'2ie3_007', s:'ingles', t:'Números', type:'fill', diff:3,
    q:'Escreve em inglês o número 11:',
    ans:['eleven'],
    exp:'O número 11 em inglês é "eleven".' },
  { id:'2ie3_008', s:'ingles', t:'Números', type:'tf', diff:3,
    q:'O número 13 em inglês é "thirty".',
    ans:false,
    exp:'13 é "thirteen". "Thirty" é 30.' },
  { id:'2ie3_009', s:'ingles', t:'Números', type:'mc', diff:3,
    q:'Qual é o número maior?',
    opts:['eight','eleven','seven'], ans:1,
    exp:'eight=8, eleven=11, seven=7. O maior é eleven (11).' },
  { id:'2ie3_010', s:'ingles', t:'Números', type:'mc', diff:3,
    q:'"Twenty" significa quanto?',
    opts:['12','20','2'], ans:1,
    exp:'"Twenty" é 20. Não confundas com "twelve" (12) ou "two" (2).' },

  // Cores
  { id:'2ie3_011', s:'ingles', t:'Cores', type:'mc', diff:3,
    q:'🎨 De que cor é tipicamente a relva (grass)?',
    opts:['blue','green','yellow'], ans:1,
    exp:'A relva é "green" (verde).' },
  { id:'2ie3_012', s:'ingles', t:'Cores', type:'tf', diff:3,
    q:'"Colour" e "color" são a mesma palavra. "Colour" é inglês britânico e "color" americano.',
    ans:true,
    exp:'Sim! Em Inglaterra escreve-se "colour"; nos EUA "color". Significam o mesmo.' },
  { id:'2ie3_013', s:'ingles', t:'Cores', type:'mc', diff:3,
    q:'Qual é a "odd one out" (a que não pertence)?',
    opts:['red','blue','apple'], ans:2,
    exp:'"Apple" (maçã) não é cor. "Red" e "blue" são cores.' },
  { id:'2ie3_014', s:'ingles', t:'Cores', type:'fill', diff:3,
    q:'Como se escreve a cor "preto" em inglês?',
    ans:['black'],
    exp:'A cor preta em inglês é "black".' },
  { id:'2ie3_015', s:'ingles', t:'Cores', type:'mc', diff:3,
    q:'Misturando "red" e "yellow" obténs...',
    opts:['orange','purple','green'], ans:0,
    exp:'Vermelho + amarelo = laranja ("orange").' },

  // Família
  { id:'2ie3_016', s:'ingles', t:'Família', type:'mc', diff:3,
    q:'👨‍👩‍👧 O que é "grandmother"?',
    opts:['mãe','avó','tia'], ans:1,
    exp:'"Grandmother" significa avó. "Grand" é "grande/grão" e "mother" é mãe.' },
  { id:'2ie3_017', s:'ingles', t:'Família', type:'tf', diff:3,
    q:'"Brother" significa irmão.',
    ans:true,
    exp:'Sim! "Brother" = irmão. "Sister" = irmã.' },
  { id:'2ie3_018', s:'ingles', t:'Família', type:'mc', diff:3,
    q:'Qual é o plural de "child" (criança)?',
    opts:['childs','children','childes'], ans:1,
    exp:'O plural de "child" é "children". É um plural irregular.' },
  { id:'2ie3_019', s:'ingles', t:'Família', type:'fill', diff:3,
    q:'Como se diz "primo" em inglês?',
    ans:['cousin'],
    exp:'"Cousin" significa primo ou prima. Lê-se "câzin".' },
  { id:'2ie3_020', s:'ingles', t:'Família', type:'mc', diff:3,
    q:'O que é "uncle"?',
    opts:['avô','tio','primo'], ans:1,
    exp:'"Uncle" significa tio. "Aunt" significa tia.' },

  // Animais
  { id:'2ie3_021', s:'ingles', t:'Animais', type:'mc', diff:3,
    q:'🐭 Qual é o plural de "mouse" (rato)?',
    opts:['mouses','mice','mouse'], ans:1,
    exp:'O plural de "mouse" é "mice". É um plural irregular.' },
  { id:'2ie3_022', s:'ingles', t:'Animais', type:'tf', diff:3,
    q:'"Sheep" no plural fica "sheeps".',
    ans:false,
    exp:'O plural de "sheep" (ovelha) é igual: "sheep". Não muda!' },
  { id:'2ie3_023', s:'ingles', t:'Animais', type:'mc', diff:3,
    q:'Qual destes animais NÃO é um "pet" comum?',
    opts:['cat','dog','lion'], ans:2,
    exp:'O "lion" (leão) é um animal selvagem, não um animal de estimação.' },
  { id:'2ie3_024', s:'ingles', t:'Animais', type:'fill', diff:3,
    q:'Escreve em inglês o nome do animal que faz "moo":',
    ans:['cow'],
    exp:'A vaca ("cow") faz "moo".' },
  { id:'2ie3_025', s:'ingles', t:'Animais', type:'mc', diff:3,
    q:'"Fish" no plural é...',
    opts:['fishes','fish','fishs'], ans:1,
    exp:'O plural de "fish" (peixe) é normalmente "fish" — não muda.' },

  // Food
  { id:'2ie3_026', s:'ingles', t:'Food', type:'mc', diff:3,
    q:'🍞 Qual destas palavras é um falso amigo? "Pasta" em inglês significa...',
    opts:['pasta de dentes','massa (comida)','pastel'], ans:1,
    exp:'"Pasta" em inglês significa massa (esparguete, etc.), não pasta de dentes.' },
  { id:'2ie3_027', s:'ingles', t:'Food', type:'tf', diff:3,
    q:'"Bread" significa pão.',
    ans:true,
    exp:'Sim! "Bread" = pão.' },
  { id:'2ie3_028', s:'ingles', t:'Food', type:'mc', diff:3,
    q:'Qual é a "odd one out"?',
    opts:['apple','banana','milk'], ans:2,
    exp:'"Apple" e "banana" são frutas. "Milk" (leite) é uma bebida.' },
  { id:'2ie3_029', s:'ingles', t:'Food', type:'fill', diff:3,
    q:'Como se diz "queijo" em inglês?',
    ans:['cheese'],
    exp:'"Cheese" significa queijo.' },
  { id:'2ie3_030', s:'ingles', t:'Food', type:'mc', diff:3,
    q:'O que tomas tipicamente ao "breakfast"?',
    opts:['pequeno-almoço','jantar','lanche da tarde'], ans:0,
    exp:'"Breakfast" é o pequeno-almoço — a primeira refeição do dia.' },

  // Toys
  { id:'2ie3_031', s:'ingles', t:'Toys', type:'mc', diff:3,
    q:'🧸 Qual destes brinquedos é um "teddy bear"?',
    opts:['boneca','urso de peluche','carrinho'], ans:1,
    exp:'"Teddy bear" é um urso de peluche.' },
  { id:'2ie3_032', s:'ingles', t:'Toys', type:'tf', diff:3,
    q:'"Ball" significa bola.',
    ans:true,
    exp:'Sim! "Ball" = bola.' },
  { id:'2ie3_033', s:'ingles', t:'Toys', type:'mc', diff:3,
    q:'Qual é o plural de "toy" (brinquedo)?',
    opts:['toies','toys','toyes'], ans:1,
    exp:'O plural de "toy" é "toys". Acrescenta-se só um "s".' },
  { id:'2ie3_034', s:'ingles', t:'Toys', type:'fill', diff:3,
    q:'Como se diz "boneca" em inglês?',
    ans:['doll'],
    exp:'"Doll" significa boneca.' },
  { id:'2ie3_035', s:'ingles', t:'Toys', type:'mc', diff:3,
    q:'Qual é a "odd one out"?',
    opts:['kite','car','milk'], ans:2,
    exp:'"Kite" (papagaio de papel) e "car" (carro) são brinquedos. "Milk" não é brinquedo.' }
];
