// EscolaPlay - Orientadores 3.º período 2.º ano
// Banco de exercícios alinhado com Aprendizagens Essenciais (AE)
// e manuais do 2.º ano. ~150 exercícios distribuídos por 19 tópicos.
// PT-PT (Acordo Ortográfico de 1990).

const EXERCISES_2_ORIENT_P3 = [

    // ============================================================
    // ===================== MATEMÁTICA ===========================
    // ============================================================

    // ----- Números até 1000 (10) -----
    { id:'2op_n1k_1', s:'matematica', t:'Números até 1000', type:'mc', diff:1,
      q:'🔢 O número 354 lê-se:',
      opts:['Trezentos e cinquenta e quatro','Três cinco quatro','Trinta e cinco quatro','Quatro cinquenta três'], ans:0,
      exp:'354 = trezentos e cinquenta e quatro.' },
    { id:'2op_n1k_2', s:'matematica', t:'Números até 1000', type:'fill', diff:1,
      q:'🔢 Escreve o número "duzentos e oito" em algarismos.',
      ans:['208'],
      exp:'Duzentos = 200; oito unidades = 8. Sem dezenas, escrevemos 0 no lugar das dezenas. 208.' },
    { id:'2op_n1k_3', s:'matematica', t:'Números até 1000', type:'mc', diff:1,
      q:'🔢 Qual destes números é maior?',
      opts:['418','481','148','184'], ans:1,
      exp:'481 > 418 > 184 > 148. As centenas vencem; depois as dezenas.' },
    { id:'2op_n1k_4', s:'matematica', t:'Números até 1000', type:'fill', diff:2,
      q:'🔢 Decompõe: 627 = ___ centenas + ___ dezenas + ___ unidades (escreve só os 3 algarismos com espaços).',
      ans:['6 2 7'],
      exp:'627 = 6 centenas + 2 dezenas + 7 unidades.' },
    { id:'2op_n1k_5', s:'matematica', t:'Números até 1000', type:'mc', diff:2,
      q:'🔢 Em 504, o algarismo 5 vale:',
      opts:['5','50','500','5000'], ans:2,
      exp:'O 5 está nas centenas → vale 500.' },
    { id:'2op_n1k_6', s:'matematica', t:'Números até 1000', type:'fill', diff:2,
      q:'🔢 Que número está entre 399 e 401?',
      ans:['400'],
      exp:'400. Vem logo a seguir a 399 e antes de 401.' },
    { id:'2op_n1k_7', s:'matematica', t:'Números até 1000', type:'mc', diff:2,
      q:'🔢 Ordena por ordem crescente: 712, 127, 271, 172.',
      opts:['127, 172, 271, 712','712, 271, 172, 127','127, 271, 172, 712','172, 127, 271, 712'], ans:0,
      exp:'Crescente = do menor para o maior: 127 < 172 < 271 < 712.' },
    { id:'2op_n1k_8', s:'matematica', t:'Números até 1000', type:'fill', diff:3,
      q:'🔢 Arredonda 348 à dezena mais próxima.',
      ans:['350'],
      exp:'348 está mais perto de 350 do que de 340 (8 ≥ 5, sobe).' },
    { id:'2op_n1k_9', s:'matematica', t:'Números até 1000', type:'mc', diff:3,
      q:'🔢 Qual é o número anterior a 600?',
      opts:['599','601','590','690'], ans:0,
      exp:'599 vem antes de 600.' },
    { id:'2op_n1k_10', s:'matematica', t:'Números até 1000', type:'fill', diff:3,
      q:'🔢 Numa biblioteca há 4 estantes com 100 livros cada e mais 35 livros. Quantos livros há ao todo?',
      ans:['435'],
      exp:'4 × 100 = 400 livros. +35 = 435 livros.' },

    // ----- Propriedades da multiplicação (8) -----
    { id:'2op_pmul_1', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Se 4 × 6 = 24, quanto é 6 × 4?',
      opts:['24','12','30','10'], ans:0,
      exp:'A ordem dos factores não altera o produto (propriedade comutativa). 6 × 4 = 4 × 6 = 24.' },
    { id:'2op_pmul_2', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Qual o resultado de 7 × 1?',
      opts:['1','7','8','0'], ans:1,
      exp:'Qualquer número multiplicado por 1 dá o próprio número (elemento neutro). 7 × 1 = 7.' },
    { id:'2op_pmul_3', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:1,
      q:'✖️ Quanto é 9 × 0?',
      opts:['9','0','1','90'], ans:1,
      exp:'Qualquer número multiplicado por 0 dá 0 (elemento absorvente).' },
    { id:'2op_pmul_4', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:2,
      q:'✖️ Sabes que 3 × 8 = 24. Quanto é 8 × 3?',
      ans:['24'],
      exp:'8 × 3 = 3 × 8 = 24 (comutativa).' },
    { id:'2op_pmul_5', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:2,
      q:'✖️ 5 × (2 × 3) = ?',
      opts:['30','15','25','11'], ans:0,
      exp:'(2 × 3) = 6. Depois 5 × 6 = 30. Podes também fazer (5×2)×3 = 10×3 = 30 (associativa).' },
    { id:'2op_pmul_6', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:2,
      q:'✖️ Completa: 6 × (4 + 2) = (6 × 4) + (6 × ___).',
      ans:['2'],
      exp:'Distributiva: a × (b + c) = (a × b) + (a × c). Aqui, c = 2.' },
    { id:'2op_pmul_7', s:'matematica', t:'Propriedades da multiplicação', type:'mc', diff:3,
      q:'✖️ Calcula 7 × 12 separando: 7 × 12 = 7 × 10 + 7 × 2 = ?',
      opts:['72','84','70','94'], ans:1,
      exp:'7 × 10 = 70; 7 × 2 = 14. 70 + 14 = 84. Usei a propriedade distributiva.' },
    { id:'2op_pmul_8', s:'matematica', t:'Propriedades da multiplicação', type:'fill', diff:3,
      q:'✖️ Calcula 8 × 25 mentalmente usando 8 × 25 = 8 × (20 + 5).',
      ans:['200'],
      exp:'8 × 20 = 160; 8 × 5 = 40. 160 + 40 = 200.' },

    // ----- Relação multiplicação e divisão (8) -----
    { id:'2op_rmd_1', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:1,
      q:'➗ Se 5 × 6 = 30, então 30 ÷ 5 = ?',
      opts:['6','5','30','25'], ans:0,
      exp:'A divisão é a operação inversa da multiplicação. 30 ÷ 5 = 6.' },
    { id:'2op_rmd_2', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:1,
      q:'➗ Sabendo que 4 × 7 = 28, quanto é 28 ÷ 7?',
      opts:['7','4','28','14'], ans:1,
      exp:'28 ÷ 7 = 4. Usar a multiplicação que conheces para descobrir a divisão.' },
    { id:'2op_rmd_3', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:1,
      q:'➗ Completa a família de factos: 3 × 8 = 24, 8 × 3 = 24, 24 ÷ 3 = ___, 24 ÷ 8 = ___ (escreve os dois resultados separados por espaço).',
      ans:['8 3'],
      exp:'A família tem 4 factos: 3×8=24, 8×3=24, 24÷3=8, 24÷8=3.' },
    { id:'2op_rmd_4', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:2,
      q:'➗ Que multiplicação ajuda a calcular 45 ÷ 9?',
      opts:['9 × 5 = 45','9 × 4 = 36','45 × 9 = 405','9 + 5 = 14'], ans:0,
      exp:'9 × 5 = 45, portanto 45 ÷ 9 = 5.' },
    { id:'2op_rmd_5', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:2,
      q:'➗ 56 ÷ 8 = ___',
      ans:['7'],
      exp:'Pensar: 8 × ? = 56. Como 8 × 7 = 56, então 56 ÷ 8 = 7.' },
    { id:'2op_rmd_6', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:2,
      q:'➗ Quantos grupos de 4 cabem em 32?',
      opts:['6','7','8','9'], ans:2,
      exp:'32 ÷ 4 = 8 (porque 4 × 8 = 32).' },
    { id:'2op_rmd_7', s:'matematica', t:'Relação multiplicação e divisão', type:'fill', diff:3,
      q:'➗ A Eduarda tem 36 bombons para dividir igualmente por 6 amigos. Quantos bombons recebe cada um?',
      ans:['6'],
      exp:'36 ÷ 6 = 6. Cada amigo recebe 6 bombons (6 × 6 = 36).' },
    { id:'2op_rmd_8', s:'matematica', t:'Relação multiplicação e divisão', type:'mc', diff:3,
      q:'➗ A Vanessa tem 24€ e quer comprar livros que custam 3€ cada. Quantos livros consegue comprar?',
      opts:['7','8','9','6'], ans:1,
      exp:'24 ÷ 3 = 8 livros (3 × 8 = 24).' },

    // ----- Cálculo mental (10) -----
    { id:'2op_cm_1', s:'matematica', t:'Cálculo mental', type:'fill', diff:1,
      q:'🧠 47 + 10 = ___',
      ans:['57'],
      exp:'Somar 10 a 47 muda só a dezena: 47 → 57.' },
    { id:'2op_cm_2', s:'matematica', t:'Cálculo mental', type:'fill', diff:1,
      q:'🧠 80 − 10 = ___',
      ans:['70'],
      exp:'Tirar 10 a 80: 80 → 70.' },
    { id:'2op_cm_3', s:'matematica', t:'Cálculo mental', type:'mc', diff:1,
      q:'🧠 Dobro de 25 = ?',
      opts:['45','50','55','75'], ans:1,
      exp:'25 + 25 = 50. Ou 2 × 25 = 50.' },
    { id:'2op_cm_4', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 47 + 9 = ___ (truque: 47 + 10 − 1)',
      ans:['56'],
      exp:'47 + 10 = 57. Como somei 1 a mais, subtraio 1: 57 − 1 = 56.' },
    { id:'2op_cm_5', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 35 + 27 = ___ (decompõe: 30+20 + 5+7)',
      ans:['62'],
      exp:'30+20 = 50; 5+7 = 12; 50+12 = 62.' },
    { id:'2op_cm_6', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 Metade de 80 = ___',
      ans:['40'],
      exp:'80 ÷ 2 = 40.' },
    { id:'2op_cm_7', s:'matematica', t:'Cálculo mental', type:'fill', diff:2,
      q:'🧠 64 − 9 = ___ (truque: 64 − 10 + 1)',
      ans:['55'],
      exp:'64 − 10 = 54; somo 1 porque tirei 1 a mais: 54 + 1 = 55.' },
    { id:'2op_cm_8', s:'matematica', t:'Cálculo mental', type:'mc', diff:3,
      q:'🧠 53 + 38 (calcula mentalmente)',
      opts:['81','91','85','89'], ans:1,
      exp:'53 + 40 = 93; −2 (porque somei 2 a mais) = 91.' },
    { id:'2op_cm_9', s:'matematica', t:'Cálculo mental', type:'fill', diff:3,
      q:'🧠 100 − 47 = ___',
      ans:['53'],
      exp:'Pensa que números faltam de 47 até 100: 47 + 3 = 50; 50 + 50 = 100. Total: 3 + 50 = 53.' },
    { id:'2op_cm_10', s:'matematica', t:'Cálculo mental', type:'fill', diff:3,
      q:'🧠 Dobro do dobro de 6 = ___',
      ans:['24'],
      exp:'Dobro de 6 = 12. Dobro de 12 = 24. (= 4 × 6).' },

    // ----- Sequências de crescimento (8) -----
    { id:'2op_seq_1', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Qual é o número seguinte? 2, 4, 6, 8, ___',
      ans:['10'],
      exp:'A sequência aumenta de 2 em 2 (pares). Depois do 8 vem 10.' },
    { id:'2op_seq_2', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Qual é o número seguinte? 5, 10, 15, 20, ___',
      ans:['25'],
      exp:'Aumenta de 5 em 5. Depois de 20 vem 25.' },
    { id:'2op_seq_3', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:1,
      q:'📈 Qual é o número seguinte? 10, 20, 30, 40, ___',
      ans:['50'],
      exp:'Aumenta de 10 em 10. Depois de 40 vem 50.' },
    { id:'2op_seq_4', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Qual a regra? 3, 6, 9, 12, 15... aumenta de ___ em ___ (escreve só um número).',
      ans:['3'],
      exp:'Diferença entre termos: 6−3=3, 9−6=3, etc. Aumenta de 3 em 3.' },
    { id:'2op_seq_5', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Que número está em falta? 11, 14, ___, 20, 23',
      ans:['17'],
      exp:'Aumenta de 3 em 3. 14 + 3 = 17.' },
    { id:'2op_seq_6', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:2,
      q:'📈 Continua a sequência: 100, 110, 120, ___',
      ans:['130'],
      exp:'Aumenta de 10 em 10. Depois de 120 vem 130.' },
    { id:'2op_seq_7', s:'matematica', t:'Sequências de crescimento', type:'mc', diff:3,
      q:'📈 Qual o 6.º termo da sequência 7, 14, 21, 28, ...?',
      opts:['35','42','49','56'], ans:1,
      exp:'Tabuada do 7: 7, 14, 21, 28, 35, 42. O 6.º termo é 42.' },
    { id:'2op_seq_8', s:'matematica', t:'Sequências de crescimento', type:'fill', diff:3,
      q:'📈 Que número falta? 50, 45, ___, 35, 30 (sequência DECRESCENTE de 5)',
      ans:['40'],
      exp:'Diminui de 5 em 5. 45 − 5 = 40.' },

    // ----- Perímetro (8) -----
    { id:'2op_per_1', s:'matematica', t:'Perímetro', type:'mc', diff:1,
      q:'📏 O perímetro de uma figura é:',
      opts:['A área de dentro','A soma de todos os lados','O lado maior','O número de lados'], ans:1,
      exp:'Perímetro = comprimento da linha que contorna a figura = soma de todos os lados.' },
    { id:'2op_per_2', s:'matematica', t:'Perímetro', type:'fill', diff:1,
      q:'📏 Qual o perímetro de um quadrado com 4 cm de lado?',
      ans:['16','16 cm','16cm'],
      exp:'Quadrado tem 4 lados iguais. 4 × 4 = 16 cm.' },
    { id:'2op_per_3', s:'matematica', t:'Perímetro', type:'fill', diff:1,
      q:'📏 Um triângulo tem lados de 3 cm, 4 cm e 5 cm. Qual o perímetro?',
      ans:['12','12 cm','12cm'],
      exp:'Soma dos lados: 3 + 4 + 5 = 12 cm.' },
    { id:'2op_per_4', s:'matematica', t:'Perímetro', type:'fill', diff:2,
      q:'📏 Um retângulo tem 6 cm de comprimento e 3 cm de largura. Qual o perímetro?',
      ans:['18','18 cm','18cm'],
      exp:'Retângulo: 2 lados iguais e 2 iguais. 6+3+6+3 = 18 cm. Ou 2×(6+3) = 18.' },
    { id:'2op_per_5', s:'matematica', t:'Perímetro', type:'mc', diff:2,
      q:'📏 Quadrado com 7 cm de lado tem perímetro:',
      opts:['14 cm','21 cm','28 cm','49 cm'], ans:2,
      exp:'4 × 7 = 28 cm.' },
    { id:'2op_per_6', s:'matematica', t:'Perímetro', type:'fill', diff:2,
      q:'📏 Pentágono regular (5 lados iguais) com cada lado de 6 cm. Perímetro = ___',
      ans:['30','30 cm','30cm'],
      exp:'5 × 6 = 30 cm.' },
    { id:'2op_per_7', s:'matematica', t:'Perímetro', type:'fill', diff:3,
      q:'📏 Um terreno retangular tem 25 m de comprimento e 15 m de largura. Quantos metros de rede são precisos para o cercar todo?',
      ans:['80','80 m','80m'],
      exp:'Perímetro = 2×(25+15) = 2×40 = 80 m.' },
    { id:'2op_per_8', s:'matematica', t:'Perímetro', type:'mc', diff:3,
      q:'📏 Um quadrado tem perímetro 36 cm. Quanto mede cada lado?',
      opts:['9 cm','6 cm','12 cm','4 cm'], ans:0,
      exp:'4 lados iguais → 36 ÷ 4 = 9 cm.' },

    // ----- Ângulos retos (8) -----
    { id:'2op_ang_1', s:'matematica', t:'Ângulos retos', type:'mc', diff:1,
      q:'📐 Um ângulo reto tem:',
      opts:['Mais de 90°','Menos de 90°','Exatamente 90°','180°'], ans:2,
      exp:'O ângulo reto mede exatamente 90 graus. Forma o canto de um "L" ou de um quadrado.' },
    { id:'2op_ang_2', s:'matematica', t:'Ângulos retos', type:'tf', diff:1,
      q:'📐 Os 4 cantos de um quadrado são ângulos retos.',
      ans:true,
      exp:'Verdadeiro. Todo o quadrado e todo o retângulo têm 4 ângulos retos (90° cada).' },
    { id:'2op_ang_3', s:'matematica', t:'Ângulos retos', type:'mc', diff:1,
      q:'📐 Qual destas formas TEM sempre ângulos retos?',
      opts:['Triângulo equilátero','Círculo','Retângulo','Pentágono'], ans:2,
      exp:'O retângulo tem sempre 4 ângulos retos. O círculo não tem ângulos. Os outros podem ou não.' },
    { id:'2op_ang_4', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Um ângulo MAIOR que reto chama-se:',
      opts:['Agudo','Reto','Obtuso','Pequeno'], ans:2,
      exp:'Agudo < 90° (reto) < Obtuso. Obtuso é maior que 90°.' },
    { id:'2op_ang_5', s:'matematica', t:'Ângulos retos', type:'mc', diff:2,
      q:'📐 Um ângulo MENOR que reto chama-se:',
      opts:['Obtuso','Agudo','Raso','Giro'], ans:1,
      exp:'Ângulo agudo é menor que 90°. "Agudo" como uma faca afiada (estreito).' },
    { id:'2op_ang_6', s:'matematica', t:'Ângulos retos', type:'tf', diff:2,
      q:'📐 Os ponteiros do relógio às 3 horas formam um ângulo reto.',
      ans:true,
      exp:'Verdadeiro. Às 3:00 o ponteiro pequeno aponta para o 3 e o grande para o 12 — formam exatamente 90°.' },
    { id:'2op_ang_7', s:'matematica', t:'Ângulos retos', type:'mc', diff:3,
      q:'📐 Quantos ângulos retos tem um quadrado?',
      opts:['1','2','3','4'], ans:3,
      exp:'4 ângulos retos — um em cada canto.' },
    { id:'2op_ang_8', s:'matematica', t:'Ângulos retos', type:'mc', diff:3,
      q:'📐 Qual destes objetos do dia-a-dia mostra um ângulo reto?',
      opts:['Uma bola','Uma página de caderno (no canto)','Uma laranja','Uma roda'], ans:1,
      exp:'O canto da folha de papel ou de um caderno é um ângulo reto. Bolas e rodas são redondas (sem ângulos).' },

    // ============================================================
    // ===================== PORTUGUÊS ============================
    // ============================================================

    // ----- Conetores (e, ou) (8) -----
    { id:'2op_con_1', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:1,
      q:'🔗 "Comi pão ___ bebi leite." Que conetor encaixa?',
      opts:['e','ou','mas','porque'], ans:0,
      exp:'"E" liga duas ações que aconteceram juntas (adição).' },
    { id:'2op_con_2', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:1,
      q:'🔗 "Queres maçã ___ banana?" Que conetor encaixa?',
      opts:['e','ou','porque','com'], ans:1,
      exp:'"OU" indica alternativa — escolhe uma das duas.' },
    { id:'2op_con_3', s:'portugues', t:'Conetores (e, ou)', type:'tf', diff:1,
      q:'🔗 O conetor "e" serve para LIGAR duas ideias.',
      ans:true,
      exp:'Verdadeiro. "E" é um conetor de ADIÇÃO — junta ideias.' },
    { id:'2op_con_4', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:2,
      q:'🔗 "Posso ir contigo ___ ficar em casa, escolho eu." Qual o conetor certo?',
      opts:['e','ou','mas','porque'], ans:1,
      exp:'É uma alternativa (uma OU outra opção).' },
    { id:'2op_con_5', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:2,
      q:'🔗 Qual frase usa "e" CORRETAMENTE?',
      opts:['Choveu e fez sol no mesmo segundo.','O cão e o gato dormem na cesta.','Comi e não comi.','E ou não?'], ans:1,
      exp:'"O cão e o gato dormem" — "e" liga dois sujeitos que fazem a mesma ação.' },
    { id:'2op_con_6', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:2,
      q:'🔗 Liga as frases com UM conetor: "Tenho fome. Tenho sede." → "Tenho fome ___ sede."',
      ans:['e'],
      exp:'"E" junta as duas ideias relacionadas.' },
    { id:'2op_con_7', s:'portugues', t:'Conetores (e, ou)', type:'mc', diff:3,
      q:'🔗 "O cão é castanho ___ branco — não sei bem qual." A frase pede:',
      opts:['e (ambos)','ou (um dos dois)','mas','porque'], ans:1,
      exp:'"OU" — incerteza, uma das duas cores. Se fossem ambas seria "e".' },
    { id:'2op_con_8', s:'portugues', t:'Conetores (e, ou)', type:'fill', diff:3,
      q:'🔗 Escolhe E ou OU para esta frase: "Hoje vou ao cinema ___ ao parque, ainda não decidi."',
      ans:['ou'],
      exp:'Vou a UM dos dois (alternativa) — "ou".' },

    // ----- Interjeições (8) -----
    { id:'2op_int_1', s:'portugues', t:'Interjeições', type:'mc', diff:1,
      q:'❗ "Ah! Que surpresa!" A palavra "Ah" é uma:',
      opts:['Verbo','Interjeição','Adjetivo','Nome'], ans:1,
      exp:'Interjeição = palavra que exprime EMOÇÃO. "Ah!" mostra surpresa/admiração.' },
    { id:'2op_int_2', s:'portugues', t:'Interjeições', type:'mc', diff:1,
      q:'❗ Que interjeição se usa para CUMPRIMENTAR?',
      opts:['Olá!','Ai!','Bah!','Ufa!'], ans:0,
      exp:'"Olá!" é interjeição de saudação.' },
    { id:'2op_int_3', s:'portugues', t:'Interjeições', type:'tf', diff:1,
      q:'❗ "Ai!" exprime dor ou aflição.',
      ans:true,
      exp:'Verdadeiro. "Ai!" usa-se quando nos magoamos ou ficamos surpreendidos.' },
    { id:'2op_int_4', s:'portugues', t:'Interjeições', type:'mc', diff:2,
      q:'❗ Que interjeição mostra ALEGRIA?',
      opts:['Ai!','Viva!','Bah!','Ué!'], ans:1,
      exp:'"Viva!" celebra, mostra alegria. Também: "Hurra!", "Boa!".' },
    { id:'2op_int_5', s:'portugues', t:'Interjeições', type:'mc', diff:2,
      q:'❗ "Ufa! Que cansaço!" A interjeição "Ufa!" exprime:',
      opts:['Alegria','Cansaço/alívio','Surpresa','Dor'], ans:1,
      exp:'"Ufa!" é alívio depois de um esforço.' },
    { id:'2op_int_6', s:'portugues', t:'Interjeições', type:'fill', diff:2,
      q:'❗ Que interjeição se usa para DESPEDIR?',
      ans:['adeus','adeus!','tchau','tchau!','até logo'],
      exp:'"Adeus!" ou "Tchau!" são interjeições de despedida.' },
    { id:'2op_int_7', s:'portugues', t:'Interjeições', type:'mc', diff:3,
      q:'❗ "Coitado!" exprime:',
      opts:['Alegria','Pena/compaixão','Raiva','Ordem'], ans:1,
      exp:'"Coitado!" mostra pena por alguém que sofre.' },
    { id:'2op_int_8', s:'portugues', t:'Interjeições', type:'mc', diff:3,
      q:'❗ Qual destas frases TEM uma interjeição?',
      opts:['O sol nasceu.','Bravo! Que jogo!','A Maria estuda.','O cão dorme.'], ans:1,
      exp:'"Bravo!" — interjeição de aplauso/aprovação. É o típico ponto de exclamação a seguir.' },

    // ----- Determinantes artigos (8) -----
    { id:'2op_da_1', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "O", "a", "os", "as" são:',
      opts:['Nomes','Verbos','Artigos definidos','Adjetivos'], ans:2,
      exp:'O, a, os, as = artigos DEFINIDOS (já conheço a coisa específica).' },
    { id:'2op_da_2', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "Um", "uma", "uns", "umas" são:',
      opts:['Artigos indefinidos','Artigos definidos','Pronomes','Verbos'], ans:0,
      exp:'Um, uma, uns, umas = artigos INDEFINIDOS (não específico, qualquer um).' },
    { id:'2op_da_3', s:'portugues', t:'Determinantes artigos', type:'mc', diff:1,
      q:'🔤 "A menina lê um livro." Qual é o artigo DEFINIDO?',
      opts:['A','um','livro','menina'], ans:0,
      exp:'"A" — sabemos qual menina. "Um" é INDEFINIDO (qualquer livro).' },
    { id:'2op_da_4', s:'portugues', t:'Determinantes artigos', type:'fill', diff:2,
      q:'🔤 Escreve o artigo definido apropriado: ___ cão dorme.',
      ans:['o','O'],
      exp:'"O cão" — masculino singular. Artigo definido = O.' },
    { id:'2op_da_5', s:'portugues', t:'Determinantes artigos', type:'mc', diff:2,
      q:'🔤 Plural de "a flor":',
      opts:['o flores','as flores','uma flores','umas flor'], ans:1,
      exp:'"a" no plural feminino = "as". "as flores".' },
    { id:'2op_da_6', s:'portugues', t:'Determinantes artigos', type:'mc', diff:2,
      q:'🔤 Qual frase usa o artigo INDEFINIDO?',
      opts:['O sol brilha.','As crianças cantam.','Uma menina chegou.','Os meus pais.'], ans:2,
      exp:'"Uma" é indefinido — uma qualquer menina, não específica.' },
    { id:'2op_da_7', s:'portugues', t:'Determinantes artigos', type:'fill', diff:3,
      q:'🔤 Completa com o artigo certo: ___ lápis estão na mesa (plural masculino definido).',
      ans:['os','Os'],
      exp:'Masculino plural definido = "os".' },
    { id:'2op_da_8', s:'portugues', t:'Determinantes artigos', type:'mc', diff:3,
      q:'🔤 Em "A Joana viu uma estrela", quantos artigos há no total?',
      opts:['1','2','3','0'], ans:1,
      exp:'2 artigos: "A" (definido — sabemos qual Joana) + "uma" (indefinido — uma estrela qualquer).' },

    // ----- Sílaba átona (8) -----
    { id:'2op_sa_1', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 A sílaba que se diz com MAIS FORÇA chama-se:',
      opts:['Átona','Tónica','Forte','Grande'], ans:1,
      exp:'Sílaba TÓNICA = a que se ouve mais forte. As outras sílabas são ÁTONAS.' },
    { id:'2op_sa_2', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 Em "ca-SA", qual é a sílaba tónica?',
      opts:['CA','SA','Nenhuma','As duas'], ans:1,
      exp:'CA-SA. A força está em SA. As outras (CA) são átonas.' },
    { id:'2op_sa_3', s:'portugues', t:'Sílaba átona', type:'mc', diff:1,
      q:'🔡 Em "BO-la", qual é a sílaba átona?',
      opts:['BO','la','As duas','Nenhuma'], ans:1,
      exp:'BO-LA. Tónica = BO. Átona = la.' },
    { id:'2op_sa_4', s:'portugues', t:'Sílaba átona', type:'mc', diff:2,
      q:'🔡 Em "MA-LA", as sílabas átonas são:',
      opts:['Só MA','Só LA','MA e LA','Nenhuma — todas são tónicas'], ans:1,
      exp:'Tónica = MA (a que se ouve mais). Átona = LA.' },
    { id:'2op_sa_5', s:'portugues', t:'Sílaba átona', type:'mc', diff:2,
      q:'🔡 Em "ca-DER-no" qual a tónica?',
      opts:['CA','DER','NO','Nenhuma'], ans:1,
      exp:'CA-DER-NO. Tónica = DER. As outras (CA e NO) são átonas.' },
    { id:'2op_sa_6', s:'portugues', t:'Sílaba átona', type:'fill', diff:2,
      q:'🔡 Em "GA-to", a sílaba átona é: ___',
      ans:['to','TO','to (segunda)'],
      exp:'GA-TO. Tónica = GA (forte). Átona = TO.' },
    { id:'2op_sa_7', s:'portugues', t:'Sílaba átona', type:'mc', diff:3,
      q:'🔡 Em "bor-bo-LE-ta", quantas sílabas átonas há?',
      opts:['1','2','3','4'], ans:2,
      exp:'BOR-BO-LE-TA. Tónica = LE. Átonas = BOR, BO, TA. Total: 3.' },
    { id:'2op_sa_8', s:'portugues', t:'Sílaba átona', type:'mc', diff:3,
      q:'🔡 Em "ca-VA-lo", as sílabas átonas são:',
      opts:['CA e VA','VA e LO','CA e LO','VA apenas'], ans:2,
      exp:'CA-VA-LO. Tónica = VA. Átonas = CA e LO.' },

    // ----- Compreensão de texto (8) -----
    { id:'2op_ct_1', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 Lê: "O sol brilhava no céu. A Maria corria no jardim com o seu cão."\nQuem corria no jardim?',
      opts:['O sol','A Maria','O cão sozinho','Ninguém'], ans:1,
      exp:'O texto diz "A Maria corria no jardim com o seu cão" — Maria é o sujeito.' },
    { id:'2op_ct_2', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 Lê: "Choveu toda a manhã. À tarde, o sol apareceu." Quando apareceu o sol?',
      opts:['De manhã','À tarde','À noite','Não diz'], ans:1,
      exp:'O texto é claro: "À tarde, o sol apareceu."' },
    { id:'2op_ct_3', s:'portugues', t:'Compreensão de texto', type:'mc', diff:1,
      q:'📖 Lê: "O João tem 3 maçãs. Comeu 1." Quantas maçãs lhe restam?',
      opts:['1','2','3','4'], ans:1,
      exp:'3 − 1 = 2 maçãs.' },
    { id:'2op_ct_4', s:'portugues', t:'Compreensão de texto', type:'mc', diff:2,
      q:'📖 "A Eduarda foi à escola de mochila às costas. Tinha lápis, borracha e livros lá dentro." O que NÃO estava na mochila?',
      opts:['Lápis','Borracha','Livros','Régua'], ans:3,
      exp:'O texto menciona lápis, borracha e livros. Régua NÃO é referida.' },
    { id:'2op_ct_5', s:'portugues', t:'Compreensão de texto', type:'mc', diff:2,
      q:'📖 "Ontem fez frio. A Sofia vestiu o casaco verde e foi para a escola." Que cor era o casaco?',
      opts:['Vermelho','Azul','Verde','Amarelo'], ans:2,
      exp:'O texto diz "casaco verde".' },
    { id:'2op_ct_6', s:'portugues', t:'Compreensão de texto', type:'fill', diff:2,
      q:'📖 "O pai do João é professor." Que profissão tem o pai do João?',
      ans:['professor'],
      exp:'O texto diz claramente "é professor".' },
    { id:'2op_ct_7', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "A Carolina adora ler. Tem livros de aventuras, mistério e poesia. Os preferidos são os de mistério." Qual género ela prefere?',
      opts:['Aventuras','Mistério','Poesia','Banda desenhada'], ans:1,
      exp:'O texto diz "Os preferidos são os de mistério".' },
    { id:'2op_ct_8', s:'portugues', t:'Compreensão de texto', type:'mc', diff:3,
      q:'📖 "O cão do João partiu uma cadeira. O João ficou triste mas perdoou-o." Como se sentiu o João?',
      opts:['Feliz','Triste','Zangado para sempre','Não diz'], ans:1,
      exp:'O texto diz que "ficou triste" mas depois perdoou.' },

    // ----- Textos narrativos (8) -----
    { id:'2op_tn_1', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 Um texto narrativo serve para:',
      opts:['Dar instruções','Contar uma história','Listar regras','Mostrar imagens'], ans:1,
      exp:'Narrativo = NARRA, conta uma história com personagens, espaço, tempo e ação.' },
    { id:'2op_tn_2', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 As "personagens" de uma história são:',
      opts:['O sítio onde acontece','Quem participa na ação','O tempo','O fim'], ans:1,
      exp:'Personagens são as pessoas/animais que vivem a história.' },
    { id:'2op_tn_3', s:'portugues', t:'Textos narrativos', type:'mc', diff:1,
      q:'📚 O "espaço" de uma narrativa é:',
      opts:['Quem','O quê','Onde acontece','Quando'], ans:2,
      exp:'Espaço = onde se passa a história (casa, escola, floresta...).' },
    { id:'2op_tn_4', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 Quem CONTA a história num texto narrativo chama-se:',
      opts:['Personagem','Narrador','Autor','Leitor'], ans:1,
      exp:'NARRADOR é quem conta. Autor é quem escreve (pessoa real).' },
    { id:'2op_tn_5', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 Toda a história tem geralmente:',
      opts:['Só fim','Início, meio e fim','Só meio','Só personagens'], ans:1,
      exp:'A estrutura clássica é: introdução (início) → desenvolvimento (meio) → conclusão (fim).' },
    { id:'2op_tn_6', s:'portugues', t:'Textos narrativos', type:'mc', diff:2,
      q:'📚 "Era uma vez uma princesa que vivia num castelo." Que tipo de texto é?',
      opts:['Informativo','Narrativo','Receita','Carta'], ans:1,
      exp:'É o início típico de um conto/narrativa. "Era uma vez..." é um marcador clássico.' },
    { id:'2op_tn_7', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 "Há muito tempo, num castelo, vivia uma princesa." Aqui já estão indicados:',
      opts:['Só personagem','Só espaço','Personagem, espaço e tempo','Só tempo'], ans:2,
      exp:'Tempo: "há muito tempo". Espaço: "num castelo". Personagem: "uma princesa".' },
    { id:'2op_tn_8', s:'portugues', t:'Textos narrativos', type:'mc', diff:3,
      q:'📚 Numa narrativa, a "ação" é:',
      opts:['O que acontece (sequência de eventos)','As personagens em si','A cor do livro','O título'], ans:0,
      exp:'AÇÃO = a sequência de eventos que acontecem na história.' },

    // ----- Poesia e BD (8) -----
    { id:'2op_pbd_1', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'📜 Uma poesia organiza-se em:',
      opts:['Capítulos','Versos e estrofes','Linhas em prosa','Bocados'], ans:1,
      exp:'Verso = linha do poema. Estrofe = grupo de versos.' },
    { id:'2op_pbd_2', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'📜 Quando duas palavras acabam com o mesmo som diz-se que:',
      opts:['Ficam iguais','Rimam','Voam','São sinónimos'], ans:1,
      exp:'Rimam → "gato" e "pato" rimam (ambas terminam em -ato).' },
    { id:'2op_pbd_3', s:'portugues', t:'Poesia e BD', type:'mc', diff:1,
      q:'💬 Numa BD, o "balão" serve para:',
      opts:['Decorar','Mostrar o que a personagem diz ou pensa','Numerar páginas','Cor de fundo'], ans:1,
      exp:'O balão (ou balão de fala) mostra o que a personagem diz/pensa.' },
    { id:'2op_pbd_4', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'💬 Em BD, cada quadrado/cena chama-se:',
      opts:['Página','Vinheta','Estrofe','Capítulo'], ans:1,
      exp:'Vinheta é cada quadrado/cena da BD. Várias vinhetas em sequência formam a história.' },
    { id:'2op_pbd_5', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'💥 "BUM!" "ZÁS!" "PAFT!" em BD são:',
      opts:['Personagens','Onomatopeias','Títulos','Acentos'], ans:1,
      exp:'Onomatopeias = palavras que IMITAM sons (explosão, batida, queda).' },
    { id:'2op_pbd_6', s:'portugues', t:'Poesia e BD', type:'mc', diff:2,
      q:'📜 "O sol é vivo, é cor de mel / brilha no céu como pastel." Que som rima?',
      opts:['mel e pastel (rima -el)','sol e céu','vivo e brilha','As duas linhas não rimam'], ans:0,
      exp:'"mel" e "pastel" terminam ambas em -el — rimam.' },
    { id:'2op_pbd_7', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'💬 Um balão de fala COM ZIGZAG geralmente indica:',
      opts:['Sussurro','Grito ou choque','Pensamento','Canto'], ans:1,
      exp:'Balão em ziguezague = grito, gritaria, susto.' },
    { id:'2op_pbd_8', s:'portugues', t:'Poesia e BD', type:'mc', diff:3,
      q:'📜 Um conjunto de 4 versos juntos forma uma:',
      opts:['Quadra (estrofe de 4 versos)','Frase','Linha','Música'], ans:0,
      exp:'Estrofe de 4 versos = QUADRA. De 3 = terceto. De 2 = dístico.' },

    // ============================================================
    // ==================== ESTUDO DO MEIO ========================
    // ============================================================

    // ----- Portugal na Europa e no mundo (8) -----
    { id:'2op_pem_1', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🌍 Portugal é um país do continente:',
      opts:['África','Ásia','Europa','América'], ans:2,
      exp:'Portugal fica na Europa, mais especificamente na Península Ibérica (oeste da Europa).' },
    { id:'2op_pem_2', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🏛️ A capital de Portugal é:',
      opts:['Porto','Lisboa','Coimbra','Faro'], ans:1,
      exp:'Lisboa é a capital de Portugal.' },
    { id:'2op_pem_3', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:1,
      q:'🌊 Portugal fica à beira do oceano:',
      opts:['Atlântico','Pacífico','Índico','Ártico'], ans:0,
      exp:'Portugal está na costa do Oceano Atlântico.' },
    { id:'2op_pem_4', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:2,
      q:'🤝 O único país com que Portugal partilha fronteira terrestre é:',
      opts:['França','Espanha','Marrocos','Itália'], ans:1,
      exp:'Portugal só faz fronteira terrestre com Espanha (a leste e a norte).' },
    { id:'2op_pem_5', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'tf', diff:2,
      q:'🌍 Portugal faz parte da União Europeia.',
      ans:true,
      exp:'Verdadeiro. Portugal entrou na União Europeia (na altura CEE) em 1986.' },
    { id:'2op_pem_6', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:2,
      q:'🏝️ Quais são as duas regiões autónomas de Portugal?',
      opts:['Algarve e Alentejo','Açores e Madeira','Porto e Lisboa','Minho e Beira'], ans:1,
      exp:'Açores e Madeira são as duas Regiões Autónomas (arquipélagos no Atlântico).' },
    { id:'2op_pem_7', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:3,
      q:'🗣️ A língua portuguesa também é falada noutros países como:',
      opts:['Espanha e França','Brasil, Angola, Moçambique','Inglaterra e Alemanha','China e Japão'], ans:1,
      exp:'Brasil, Angola, Moçambique, Cabo Verde, S. Tomé, Guiné-Bissau e Timor — todos países lusófonos (de língua portuguesa).' },
    { id:'2op_pem_8', s:'estudo_meio', t:'Portugal na Europa e no mundo', type:'mc', diff:3,
      q:'🇪🇺 A moeda de Portugal é:',
      opts:['Escudo','Euro (€)','Libra','Dólar'], ans:1,
      exp:'O Euro (€) é a moeda de Portugal desde 2002 (antes era o Escudo).' },

    // ----- Influências de outras culturas (8) -----
    { id:'2op_inf_1', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:1,
      q:'🍕 A pizza, comida muito apreciada em Portugal, vem da:',
      opts:['China','Itália','Japão','Inglaterra'], ans:1,
      exp:'A pizza é típica de Itália. Adotámo-la na nossa alimentação.' },
    { id:'2op_inf_2', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:1,
      q:'🍣 O sushi vem de que país?',
      opts:['China','Tailândia','Japão','Coreia'], ans:2,
      exp:'O sushi é um prato típico do Japão. Hoje há restaurantes japoneses em Portugal.' },
    { id:'2op_inf_3', s:'estudo_meio', t:'Influências de outras culturas', type:'tf', diff:1,
      q:'🌍 Em Portugal vivem pessoas de muitos países diferentes.',
      ans:true,
      exp:'Verdadeiro. Em Portugal há comunidades brasileira, ucraniana, cabo-verdiana, chinesa, nepalesa, etc.' },
    { id:'2op_inf_4', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:2,
      q:'☕ O hábito de tomar chá veio em parte da:',
      opts:['Inglaterra/Ásia','Espanha','Brasil','Marrocos'], ans:0,
      exp:'O chá veio para a Europa através de comerciantes ingleses, mas as folhas vinham da Ásia (China, Índia).' },
    { id:'2op_inf_5', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:2,
      q:'🎵 Que estilo de música americano é hoje muito ouvido em Portugal?',
      opts:['Fado','Hip-hop','Música clássica','Folclore'], ans:1,
      exp:'O hip-hop nasceu nos EUA e é hoje muito ouvido por jovens portugueses.' },
    { id:'2op_inf_6', s:'estudo_meio', t:'Influências de outras culturas', type:'tf', diff:2,
      q:'🌱 As batatas, tomates e milho que comemos hoje vieram originalmente da América.',
      ans:true,
      exp:'Verdadeiro. Trouxeram-nas para a Europa após os Descobrimentos. Antes não existiam cá.' },
    { id:'2op_inf_7', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'🛕 A festa do Diwali (festa das luzes) vem de:',
      opts:['Portugal','Índia','Japão','França'], ans:1,
      exp:'Diwali é uma festa hindu da Índia. Em Portugal celebram-na as comunidades indianas.' },
    { id:'2op_inf_8', s:'estudo_meio', t:'Influências de outras culturas', type:'mc', diff:3,
      q:'👋 Saber dizer "olá" noutras línguas é importante porque:',
      opts:['Não tem utilidade','Mostra respeito pela cultura do outro','Só quem viaja precisa','Substitui o português'], ans:1,
      exp:'Saber palavras de outras línguas é uma forma de respeito e curiosidade pelas culturas dos outros.' },

    // ----- Múltiplas pertenças e grupos (8) -----
    { id:'2op_mp_1', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:1,
      q:'👨‍👩‍👧 Pertenço à minha:',
      opts:['Família','Cidade','Família, escola, turma — todos','Só escola'], ans:2,
      eque:'Cada criança pertence a vários grupos ao mesmo tempo: família, turma, escola, talvez clube, vizinhança, etc.',
      exp:'Cada criança pertence a vários grupos ao mesmo tempo: família, turma, escola, talvez clube, vizinhança, etc.' },
    { id:'2op_mp_2', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'tf', diff:1,
      q:'👥 Uma pessoa pode pertencer a vários grupos ao mesmo tempo.',
      ans:true,
      exp:'Verdadeiro. Posso ser irmão (família), aluno (escola), jogador de futebol (clube) — tudo em simultâneo.' },
    { id:'2op_mp_3', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:1,
      q:'🏫 A turma é um grupo:',
      opts:['Familiar','Escolar','Desportivo','Religioso'], ans:1,
      exp:'A turma é o grupo escolar mais próximo — colegas que partilham a mesma sala/professor.' },
    { id:'2op_mp_4', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:2,
      q:'⚽ Um clube de futebol é um grupo:',
      opts:['Familiar','Religioso','Desportivo','Político'], ans:2,
      exp:'Clube desportivo. Reúne pessoas que partilham gosto pelo desporto.' },
    { id:'2op_mp_5', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:2,
      q:'🤝 Numa turma diversa, cada colega pode ter:',
      opts:['A mesma religião só','As mesmas roupas','Origens e culturas diferentes','Os mesmos pais'], ans:2,
      exp:'A diversidade enriquece a turma — colegas podem vir de várias culturas, países, religiões.' },
    { id:'2op_mp_6', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'tf', diff:2,
      q:'👨‍👩‍👧‍👦 Há diferentes tipos de família (com pai e mãe, só com mãe, com avós, etc.) e todas são válidas.',
      ans:true,
      exp:'Verdadeiro. Há famílias muito diferentes, todas igualmente válidas e importantes.' },
    { id:'2op_mp_7', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🌍 "Pertencer" significa:',
      opts:['Ter coisas','Fazer parte de um grupo e sentir-se ligado','Mandar nos outros','Estar sozinho'], ans:1,
      exp:'Pertencer é sentir-se parte de algo (família, turma, etc.) — laços de identidade e ligação.' },
    { id:'2op_mp_8', s:'estudo_meio', t:'Múltiplas pertenças e grupos', type:'mc', diff:3,
      q:'🤗 Quando alguém é novo na turma, devemos:',
      opts:['Ignorar','Acolher e ajudar a integrar','Rir','Ficar em silêncio'], ans:1,
      exp:'Acolher os colegas novos é importante para que se sintam parte do grupo.' },

    // ----- Direitos da criança (8) -----
    { id:'2op_dc_1', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:1,
      q:'📜 Todas as crianças têm o direito à:',
      opts:['Trabalho','Educação','Conduzir','Casamento'], ans:1,
      exp:'A educação é um direito FUNDAMENTAL de todas as crianças.' },
    { id:'2op_dc_2', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:1,
      q:'🏥 Outro direito da criança é:',
      opts:['Pagar impostos','Saúde','Votar','Conduzir'], ans:1,
      exp:'Direito à saúde — todas as crianças devem ter cuidados de saúde.' },
    { id:'2op_dc_3', s:'estudo_meio', t:'Direitos da criança', type:'tf', diff:1,
      q:'🎈 As crianças têm o direito a brincar.',
      ans:true,
      exp:'Verdadeiro. O direito ao lazer e à brincadeira está na Convenção dos Direitos da Criança.' },
    { id:'2op_dc_4', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:2,
      q:'🗣️ As crianças têm o direito a:',
      opts:['Estar caladas sempre','Ser ouvidas e dar a sua opinião','Mandar nos adultos','Não ir à escola'], ans:1,
      exp:'Direito de participação: a criança tem direito a ser ouvida e expressar a sua opinião.' },
    { id:'2op_dc_5', s:'estudo_meio', t:'Direitos da criança', type:'tf', diff:2,
      q:'👨‍👩‍👧 Toda a criança tem direito a uma família/cuidadores que tomam conta dela.',
      ans:true,
      exp:'Verdadeiro. Direito à proteção familiar e a viver em ambiente seguro.' },
    { id:'2op_dc_6', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:2,
      q:'🛡️ As crianças devem ser protegidas:',
      opts:['Só algumas','Só os mais pequenos','Todas, sem distinção','Só se obedecerem'], ans:2,
      exp:'TODAS as crianças têm direito à proteção, sem distinção (nem por origem, religião, género, etc.).' },
    { id:'2op_dc_7', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'📋 O documento internacional sobre direitos da criança chama-se:',
      opts:['Constituição','Convenção dos Direitos da Criança','Manual da escola','Lei das férias'], ans:1,
      exp:'A Convenção sobre os Direitos da Criança foi aprovada pelas Nações Unidas em 1989.' },
    { id:'2op_dc_8', s:'estudo_meio', t:'Direitos da criança', type:'mc', diff:3,
      q:'🌍 Os direitos da criança aplicam-se:',
      opts:['Só em Portugal','Em todos os países do mundo','Só na Europa','Só nas escolas'], ans:1,
      exp:'A Convenção dos Direitos da Criança aplica-se em todos os países que a assinaram (quase todos).' },

    // ----- Diálogo e compromisso (8) -----
    { id:'2op_di_1', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:1,
      q:'💬 Quando alguém fala devemos:',
      opts:['Interromper','Ouvir com atenção','Falar mais alto','Sair'], ans:1,
      exp:'Ouvir com atenção é o primeiro passo para um bom diálogo.' },
    { id:'2op_di_2', s:'estudo_meio', t:'Diálogo e compromisso', type:'tf', diff:1,
      q:'🤝 É importante usar palavras como "por favor" e "obrigado".',
      ans:true,
      exp:'Verdadeiro. São palavras que mostram respeito.' },
    { id:'2op_di_3', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:1,
      q:'😡 Quando há um desacordo, a melhor forma de resolver é:',
      opts:['Bater','Gritar mais alto','Conversar com calma','Não falar nunca mais'], ans:2,
      exp:'Falar com calma — o diálogo resolve conflitos melhor que a violência.' },
    { id:'2op_di_4', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:2,
      q:'🤝 Quando dois amigos querem coisas diferentes, podem:',
      opts:['Brigar até alguém ceder','Procurar um compromisso (cada um cede um pouco)','Não brincar mais','Esperar que alguém decida por eles'], ans:1,
      exp:'Compromisso = cada um cede um pouco para chegar a um acordo onde ambos ficam satisfeitos.' },
    { id:'2op_di_5', s:'estudo_meio', t:'Diálogo e compromisso', type:'tf', diff:2,
      q:'💬 No diálogo é importante ouvir o outro e expressar a sua opinião sem agressividade.',
      ans:true,
      exp:'Verdadeiro. Ouvir + falar com respeito = bom diálogo.' },
    { id:'2op_di_6', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:2,
      q:'🤝 Cumprir o que se combina chama-se:',
      opts:['Compromisso','Conflito','Discussão','Castigo'], ans:0,
      exp:'Compromisso é o que assumimos cumprir. Se prometo, devo cumprir.' },
    { id:'2op_di_7', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🕊️ "Negociar" significa:',
      opts:['Lutar','Conversar para chegar a acordo','Mandar','Fugir'], ans:1,
      exp:'Negociar = falar/discutir até chegar a um acordo que sirva às partes.' },
    { id:'2op_di_8', s:'estudo_meio', t:'Diálogo e compromisso', type:'mc', diff:3,
      q:'🌟 Numa turma, regras combinadas em conjunto são respeitadas porque:',
      opts:['Foram impostas','Todos contribuíram e concordaram','São fáceis de quebrar','Ninguém quer'], ans:1,
      exp:'Quando todos participam na criação das regras, sentem-nas como suas e cumprem mais facilmente.' }

];

// Limpar campo 'eque' (typo) — fallback se algum exercicio tiver atributo incorreto
for (const e of EXERCISES_2_ORIENT_P3) { if (e.eque !== undefined) delete e.eque; }

if (typeof window !== 'undefined') window.EXERCISES_2_ORIENT_P3 = EXERCISES_2_ORIENT_P3;
